codeigniter4/CodeIgniter4

- phpunit.xml
- system/Debug/Exceptions.php
- system/HTTP/ContentSecurityPolicy.php
- system/Session/Handlers/MemcachedHandler.php
- system/Session/Handlers/RedisHandler.php
> Fixes for generating code coverage report

- index.php
- system/Debug/Exceptions.php
- system/Debug/Toolbar.php
- tests/_support/_bootstrap.php
- tests/system/Config/DotEnvTest.php
- tests/system/View/ViewTest.php
Probably you know, `__DIR__` is equivalent to `dirname(__FILE__)`.
See <http://php.net/manual/en/language.constants.predefined.php>.
> Replace `dirname(__FILE__)` with `__DIR__`

- system/CodeIgniter.php
1. If `empty($this->controller)` is true, it shows nothing.
2. if `$this->router->get404Override()` is not false, it always shows the 404 page.
See https://github.com/lonnieezell/CodeIgniter4/compare/develop...kenjis:fix-404-logic?expand=1&w=1
> Fix 404 logic

- system/CodeIgniter.php
- system/HTTP/Message.php
The current logic for 404 is complex.
This PR refactors it to use `PageNotFoundException`.
And This PR fixes behavior when you run via CLI:
* removes debug toolbar
* does not set/get HTTP Protocol Version
> Refactor 404 logic

- tests/_support/_bootstrap.php
The code is there: https://github.com/lonnieezell/CodeIgniter4/blob/develop/tests/_support/_bootstrap.php#L105-L106
This is probably because of my PRs. Sorry.
> Remove duplicated line

- system/CodeIgniter.php
- system/Router/Router.php
- tests/system/CodeIgniterTest.php
* `php index.php` should be routed to the default route
* Now Router throws PageNotFoundException
> Fix routing

- tests/_support/MockCommon.php
- tests/_support/_bootstrap.php
We need a special `is_cli()` function for testing.
> Add mock is_cli() function

- system/CodeIgniter.php
- tests/system/CodeIgniterTest.php
And refactor CodeIgniter::run(). Now all Hooks::trigger() are in the run() method.
> Fix bug that closure route does not work

- application/Views/welcome_message.php
- system/CodeIgniter.php
- tests/_support/Database/MockConnection.php
A cleaner and test-safe way to define this constant
> Define CI_VERSION as class constant

- system/ComposerScripts.php
I suggest this reflection way to get class filepaths instead of hard coding file start paths which should be moved.
> Replacing hard coded file paths with class reflection file paths

- system/Session/Session.php
- system/Session/SessionInterface.php
- user_guide_src/source/libraries/index.rst
- user_guide_src/source/libraries/sessions.rst
Fixed API docs & copied user guide section from CI3 - it will probably need more work.
> Session documentation.

- user_guide_src/source/contributing/styleguide.rst
Fleshed out the missing pieces, added examples.
Added a section for IDE configuration ... it needs details.
> Revise the style guide

- system/Config/DotEnv.php
> Small thing, but "sanitise" s/b "sanitize"

- user_guide_src/source/concepts/security.rst
> First crack at security guidelines.

- user_guide_src/source/changelog.rst
- user_guide_src/source/contributing/index.rst
- user_guide_src/source/contributing/roadmap.rst
> Added roadmap & related changelog

- system/Debug/CustomExceptions.php
- user_guide_src/source/contributing/guidelines.rst
- user_guide_src/source/contributing/process.rst
- user_guide_src/source/contributing/styleguide.rst
> Update the contributing guide & process to explain signed commits.

- user_guide_src/source/contributing/process.rst
Update to the "contribution process" in the user guide.
Answers #107
> Explain reasoning for secure signing

- user_guide_src/source/contributing/index.rst
- user_guide_src/source/contributing/signing.rst
- user_guide_src/source/contributing/workflow.rst
> Rewrite workflow explanation

- user_guide_src/Makefile
> gh-pages mods to user guide makefile

- system/Commands/MigrationsCommand.php
Just replaces 4 spaces with a tab.
> Fix white spaces

- system/Debug/Toolbar/Collectors/Routes.php
- system/Debug/Toolbar/View/toolbar.css
>  	Improvement, debug bar Matched Route - Params

- system/Session/Handlers/BaseHandler.php
fix typo  $config->cookoieDomain; in system/Session/Handlers/BaseHandler.php
> fix typo $config->cookoieDomain; 

- user_guide_src/source/database/migration.rst
- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/general/routing.rst
- user_guide_src/source/general/views.rst
- user_guide_src/source/libraries/caching.rst
- user_guide_src/source/libraries/cli.rst
- user_guide_src/source/libraries/curlrequest.rst
- user_guide_src/source/libraries/incomingrequest.rst
- user_guide_src/source/libraries/index.rst
- user_guide_src/source/libraries/security.rst
- user_guide_src/source/libraries/sessions.rst
- user_guide_src/source/libraries/uploaded_files.rst
- user_guide_src/source/libraries/uri.rst
some user_guide contents, formating already corrected. Please comment here if I done wrong or some suggestions. thx
> correcting several user_guide sections

- tests/system/HTTP/URITest.php
Forgot to create a feature branch for this, sorry.
> Additional URI unit tests

- public/index.php
Because if set $composerAutoload = TRUE; in Config/App.php the path to vendor folder is not correct is not correct.
> Correct PATH composer autoload

- user_guide_src/source/general/filters.rst
- user_guide_src/source/general/index.rst
> correcting user guide

- user_guide_src/source/contributing/styleguide.rst
- Naming: being equally picky about interface & trait names.
- Address control structures, with suggestion(s) from url_helper PR.  Note: the strictly braced blocks seem to fit better into the current guidelines, though at the expense of extra lines.
- Propose more flexible tab & space treatment, for indenting & alignment. Trying to come up with something that *everyone* can live with. We spend way too much time fighting this, arguing over its interpretation, or fighting our IDEs to format things the way we think the guidelines are to be interpreted.
> Style guide: Address control structures & alignment.

- user_guide_src/source/general/controllers.rst
- user_guide_src/source/general/index.rst
- user_guide_src/source/general/view_cells.rst
- user_guide_src/source/general/view_parser.rst
- user_guide_src/source/general/view_renderer.rst
- user_guide_src/source/general/views.rst
- user_guide_src/source/libraries/response.rst
Split the view page into several, as it is getting long!
Addressed options explicitly, making it clear they are used.
Closes #181
> Revise view section(s) in user guide

- user_guide_src/ghpages.rst
> User guide rebuilding

- application/Config/Cache.php
- system/Cache/Handlers/PredisHandler.php
- system/Config/AutoloadConfig.php
Signed-off-by: Geoffrey Hughes <geoffrey.hughes@otago.ac.nz>
As discussed in #192, here's the cache drive for predis/predis.
> Add cache handler for predis

- user_guide_src/source/concepts/services.rst
- user_guide_src/source/general/controllers.rst
Signed-off-by: Mitha Aprilia <mitha@mithaaprilia.com>
> added missing backslash

- system/HTTP/Files/UploadedFile.php
Random file name function obviously gives exception error without this fix.
> UploadedFile typo fix

- system/HTTP/Files/UploadedFile.php
Outputs bunch of garbage (binary) as new filename, this should fix that.
> Random file name fix

- application/Config/App.php
- application/Config/Services.php
- system/CodeIgniter.php
- system/Common.php
- system/HTTP/IncomingRequest.php
- system/HTTP/Request.php
- system/HTTP/RequestInterface.php
- system/Language/Language.php
- system/Language/Loader.php
- system/Router/Router.php
- tests/_support/Config/MockAppConfig.php
- tests/_support/Language/MockLanguage.php
- tests/system/HTTP/IncomingRequestTest.php
- tests/system/HTTP/RequestTest.php
- tests/system/Language/LanguageTest.php
- tests/system/Router/RouterTest.php
- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/general/routing.rst
- user_guide_src/source/intro/requirements.rst
- user_guide_src/source/libraries/index.rst
- user_guide_src/source/libraries/localization.rst
Language string replacement for locales, and two methods of Locale detection: router-based and automatic through content negotiation.
> Language and Locale work

- user_guide_src/source/libraries/localization.rst
Signed-off-by: Mutasim Ridlo, S.Kom <ridho@mutasimridlo.com>
> fix missing double backquote

- user_guide_src/source/libraries/pagination.rst
Signed-off-by: Mitha Aprilia <mitha@mithaaprilia.com>
> to make bold text, should use double asterik

- user_guide_src/source/helpers/inflector_helper.rst
Signed-off-by: Mutasim Ridlo, S.Kom <ridho@mutasimridlo.com>
> fix ordinalize example

- system/View/View.php
return view('welcome_message', [], ['cache' => 60, ['cache_name' => 'welcome_message']]); // works fine
return view('welcome_message', [], ['cache' => 60]); // gives ErrorException but it also should be fine (according to doc)
> Fix ErrorException (Undefined index)

- system/Router/Router.php
Minor Router\Router change so prevent NetBeans from choking on what it considers to be strange syntax.
> Silly fix to make NetBeans happy

- application/Config/Services.php
- system/Common.php
- system/Config/AutoloadConfig.php
- system/Debug/Toolbar/Collectors/Views.php
- system/Pager/Pager.php
- system/View/RendererInterface.php
- system/View/View.php
- tests/system/View/ViewTest.php
- user_guide_src/source/changelog.rst
- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/general/view_cells.rst
- user_guide_src/source/general/view_renderer.rst
- user_guide_src/source/general/views.rst
Renamed the RenderableInterface more meaningfully, and added renderString() to it.
> Refactor producing RendererInterface

- user_guide_src/source/helpers/text_helper.rst
It should be **application/Config/ForeignCharacters.php**
> fix ForeignCharacters path in user guide

- system/HTTP/Response.php
To make variable variables is by using two dollar signs.
> fix variable variables

- system/CLI/CLI.php
- user_guide_src/source/libraries/cli.rst
The variable $thisStep never will be false. Always will be integer.
Issue #135
> CLI problem with progress complete's message.

- application/Config/Services.php
- system/Typography/Typography.php
- user_guide_src/source/libraries/typography.rst
Initial pull request to Typography helper. Changed to a Library class, no test. Thanks.
> Typography helper

- system/Debug/Toolbar/View/toolbar.css
- system/Debug/Toolbar/View/toolbar.js
- system/Debug/Toolbar/View/toolbar.tpl.php
Possiblity to click on Debug bar to hide , and click icon to show
> Add icon debug bar conversion

- system/CodeIgniter.php
When we save full page cache we should save also headers which were set.
It's important especially when we set response as json or xml that when it's loaded from cache it also should be served as this content type.
More over - we even got method Resonse::setCache which has $options parameter but when we get page from cache we get standard headers with "no-cache" on top of it :-]
> Cache headers with content

- system/Helpers/cookie_helper.php
- tests/_support/HTTP/MockResponse.php
- tests/system/Helpers/CookieHelperTest.php
- user_guide_src/source/helpers/cookie_helper.rst
Note that the unit testing isn't fully implemented/executed due to header issues when setting up cookies. This was tested however, on the browser, which works correctly as expected.
> Created cookie helper, user guide and unit test.

- tests/.htaccess
- user_guide_src/.htaccess
- writable/logs/.htaccess
> fix lack of .htaccess to prevent direct access

- user_guide_src/source/database/configuration.rst
- user_guide_src/source/database/model.rst
- user_guide_src/source/database/queries.rst
- user_guide_src/source/database/query_builder.rst
- user_guide_src/source/general/routing.rst
- user_guide_src/source/helpers/filesystem_helper.rst
- user_guide_src/source/helpers/form_helper.rst
- user_guide_src/source/helpers/number_helper.rst
- user_guide_src/source/libraries/cli.rst
- user_guide_src/source/libraries/curlrequest.rst
- user_guide_src/source/libraries/incomingrequest.rst
- user_guide_src/source/libraries/uri.rst
- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/tutorial/news_section.rst
It is not all. I fix just where I can understand.
> fix typo on document and sphinx warning

- user_guide_src/source/general/errors.rst
see: https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Debug/CustomExceptions.php#L179
Probably, typo on document. Not on source code.
> fix document: DatabaseException exit-code is 8

- user_guide_src/source/concepts/services.rst
> fix services concept document

- system/Helpers/cookie_helper.php
Funky assignment in cookie_helper's set_cookie upsets NetBeans IDE. Have sanitized it.
Reformatted as part of this.
> Make cookie_helper better for NetBeans

- .gitignore
* vscode: micorsoft editor
* phpenv: multiple php version manager
> add .gitignore for phpenv and vscode

- tests/system/Database/Live/UpdateTest.php
https://github.com/bcit-ci/CodeIgniter4/pull/348
oops... sorry. it's my mistake.
> fix testcase #348

- application/Config/App.php
- application/Config/Autoload.php
- application/Config/Boot/development.php
- application/Config/Boot/production.php
- application/Config/Boot/testing.php
- application/Config/Constants.php
- application/Config/Paths.php
- application/Filters/DebugToolbar.php
- application/Models/TempModel.php
- ci.php
- public/index.php
- system/CLI/Console.php
- system/CodeIgniter.php
- system/Config/AutoloadConfig.php
- system/Database/Config.php
- system/Database/Database.php
- system/bootstrap.php
- tests/_support/Models/EntityModel.php
- tests/_support/_bootstrap.php
- tests/system/CodeIgniterTest.php
Besides just cleaning things up a little, this has the following benefits: 
- removes as much information as possible out of the public index file
- allows the CLI tools to interact directly with the application, instead of going through `passthru` which should make integrating tools like a REPL possible.
> Refactoring and cleaning up the bootstrap process.

- system/Security/Security.php
> remove unused $this->_csrf_hash assignment in Security::CSRFVerify()

- system/API/FormatterInterface.php
- system/API/JSONFormatter.php
- system/API/ResponseTrait.php
- system/API/XMLFormatter.php
- system/Autoloader/FileLocator.php
- system/CLI/BaseCommand.php
- system/CLI/CLI.php
- system/CLI/CommandRunner.php
- system/Config/Services.php
Replace white spaces with tabs.
> Fix indentation

- composer.json
- phpunit.xml.dist
- system/Test/CIUnitTestCase.php
- tests/system/Autoloader/FileLocatorTest.php
- tests/system/Config/DotEnvTest.php
- tests/system/Database/BaseConnectionTest.php
- tests/system/Database/Builder/InsertTest.php
- tests/system/Database/Builder/ReplaceTest.php
- tests/system/Database/Builder/SelectTest.php
- tests/system/Database/Builder/UpdateTest.php
- tests/system/Database/Live/DeleteTest.php
- tests/system/Filters/FiltersTest.php
- tests/system/HTTP/MessageTest.php
- tests/system/HTTP/ResponseTest.php
- tests/system/HTTP/URITest.php
- tests/system/Helpers/URLHelperTest.php
- tests/system/Language/LanguageTest.php
- tests/system/Log/LoggerTest.php
- tests/system/Pager/PagerTest.php
- tests/system/Router/RouteCollectionTest.php
- tests/system/Security/SecurityTest.php
- tests/system/View/ViewTest.php
or, we can just use phpunit 6 since we use php7
> add phpunit 6

- phpunit.xml.dist
- tests/system/CLI/CLITest.php
- tests/system/CodeIgniterTest.php
- tests/system/CommonFunctionsTest.php
- tests/system/Config/DotEnvTest.php
- tests/system/Filters/FiltersTest.php
- tests/system/HTTP/IncomingRequestTest.php
- tests/system/HTTP/RequestTest.php
- tests/system/Helpers/URLHelperTest.php
- tests/system/Pager/PagerTest.php
- tests/system/Router/RouteCollectionTest.php
- tests/system/Security/SecurityTest.php
* Set `backupGlobals="false"`
* Add `@backupGlobals enabled` to tests which set `$_SERVER`
Related: #391
> Set backupGlobals false in phpunit.xml

- user_guide_src/source/concepts/security.rst
I think XSS has nothing to do with authentication.
> Fix about XSS in Security Guidelines

- user_guide_src/source/concepts/security.rst
> Change "inbuilt" to "built-in"

- system/Validation/Validation.php
- system/Validation/ValidationInterface.php
- tests/system/Validation/ValidationTest.php
- user_guide_src/source/libraries/validation.rst
Added the ability to do a one-off validation for a single value and single set of rules.
Issue: #418
> Validation Check

- system/CLI/BaseCommand.php
- system/CLI/CommandRunner.php
- system/CLI/Console.php
- system/Commands/Database/CreateMigration.php
- system/Commands/Database/MigrateCurrent.php
- system/Commands/Database/MigrateLatest.php
- system/Commands/Database/MigrateRefresh.php
- system/Commands/Database/MigrateRollback.php
- system/Commands/Database/MigrateStatus.php
- system/Commands/Database/MigrateVersion.php
- system/Commands/Database/Seed.php
- system/Commands/Help.php
- system/Commands/ListCommands.php
- system/Commands/Sessions/CreateMigration.php
- system/Language/en/CLI.php
- user_guide_src/source/general/cli_commands.rst
Hi,
This will add  (help feature) to each command where php ci.php help [command] will display:
1) description
2) usage
3) Arguments, if exists
4) options, if exists
Also updated all existing commands to display proper help.
> Add help functionality 

- composer.json
on next move, we can register at packagist under "codeigniter" package https://packagist.org/packages/codeigniter/
> set project name in composer.json to codeigniter4/framework

- user_guide_src/source/database/examples.rst
> Removed $this reference from examples

- application/Config/Events.php
- system/CodeIgniter.php
- system/Debug/Toolbar/Collectors/Database.php
- system/Events/Events.php
- user_guide_src/source/changelog.rst
- user_guide_src/source/contributing/documentation.rst
- user_guide_src/source/database/events.rst
- user_guide_src/source/database/index.rst
- user_guide_src/source/database/metadata.rst
- user_guide_src/source/general/controllers.rst
- user_guide_src/source/general/filters.rst
- user_guide_src/source/general/view_parser.rst
- user_guide_src/source/general/view_renderer.rst
- user_guide_src/source/helpers/form_helper.rst
- user_guide_src/source/helpers/html_helper.rst
- user_guide_src/source/libraries/api_responses.rst
- user_guide_src/source/libraries/benchmark.rst
- user_guide_src/source/libraries/incomingrequest.rst
- user_guide_src/source/libraries/localization.rst
- user_guide_src/source/libraries/pagination.rst
- user_guide_src/source/libraries/uploaded_files.rst
- user_guide_src/source/tutorial/create_news_items.rst
- user_guide_src/source/tutorial/news_section.rst
Main changes:
- Fixed 44 Sphinx warnings (15 left).
- Few codeblocks tabs fixed.
- Hooks renamed to Events on left places.
> Docs updated

- tests/system/HTTP/MessageTest.php
Signed-off-by:Lin Yang <bcityang@gmail.com>
> add more test function to populateHeaders

- .gitignore
Added the necessary folders and files to the `.gitignore` so contributors don't commit their Vagrant Environment
> Updated .gitignore for Vagrant environments

- system/Autoloader/FileLocator.php
- system/Common.php
- system/Config/AutoloadConfig.php
- system/Config/DotEnv.php
- system/Debug/CustomExceptions.php
- system/Debug/Exceptions.php
- system/Entity.php
- system/Files/Exceptions.php
- system/Files/File.php
- system/HTTP/Files/UploadedFile.php
- system/HTTP/IncomingRequest.php
- system/HTTP/Request.php
- system/HTTP/RequestInterface.php
- system/HTTP/ResponseInterface.php
- system/HTTP/URI.php
- system/Helpers/number_helper.php
- system/Session/Session.php
- system/Session/SessionInterface.php
- system/Typography/Typography.php
- system/View/Filters.php
- system/View/Parser.php
- system/View/Plugins.php
- system/View/RendererInterface.php
- system/View/View.php
This is the fix for (#507) where some files were missing the headers and the namespace was not on the first line.
> This adds consistency across all files

- public/.htaccess
`CI_ENV` has been changed to `CI_ENVIRONMENT`
> Fix the environment variable name

- user_guide_src/source/concepts/services.rst
- user_guide_src/source/database/model.rst
Services & Model document description error .
> service  description of the document changes

- user_guide_src/source/libraries/incomingrequest.rst
- user_guide_src/source/libraries/request.rst
Changes documentation of `ipAddress()` to `getIPAddress()`
> Updated documentation to reflect the method for ip address

- application/Views/errors/html/error_exception.php
simple leaves the paramter var empty to get the correct exception page
> Fix closure exception throw exception

- user_guide_src/source/general/environments.rst
> Environment name inconsistent

- system/Debug/Toolbar/Views/toolbar.tpl.php
- system/Files/File.php
- tests/system/Files/FileTest.php
- user_guide_src/source/libraries/files.rst
- user_guide_src/source/libraries/response.rst
Just a few minor changes I've noticed. Toolbar links need to get off hashes, cookie doc was incorrect with referencing variable, and making the file class constructor check file as an optional argument like the docs promote.
> Few documentation changes and updating file check to be optional

- .travis.yml
- rewrite.php
- system/Config/AutoloadConfig.php
> Changed CI_ENV to CI_ENVIRONMENT

- user_guide_src/source/libraries/sessions.rst
session set_userdata which was set for backward compatibility seem not to exist anymore
> Update sessions Doc.rst

- system/Throttle/Throttler.php
- system/Throttle/ThrottlerInterface.php
- tests/system/Throttle/ThrottleTest.php
- user_guide_src/source/libraries/throttler.rst
- Updated the user guide, with a note about the minimum time if a bucket is emptied
- Updated ThrottlerInterface, with correct "check" signature, and adding "getTokenTime"
- Beefed up ThrottleTest, with more tests, resulting in 100% coverage
- Throttler coincidentally reformatted
> Enhanced unit testing for Throttle

- tests/system/ControllerTest.php
Exercise our core Controller class. Not a lot of business logic, so concentrate on making sure we can exercise everything without blowing up :-/
> Add unit testing for Controller

- tests/system/Format/JSONFormatterTest.php
Embarassingly simple additional test, but it improves code coverage :-/
> Additional JSONFormatter test

- system/Router/RouteCollection.php
This fixes an issue with route groups and route options not merging correctly.
> Fix for issue #612

- system/API/ResponseTrait.php
- system/Controller.php
- system/Database/BaseConnection.php
- system/Database/Config.php
- system/HTTP/IncomingRequest.php
- system/HTTP/Message.php
- system/HTTP/Request.php
- system/HTTP/RequestInterface.php
- system/HTTP/Response.php
- system/HTTP/ResponseInterface.php
> Update some PHPDoc Types

- user_guide_src/source/libraries/caching.rst
Caching Driver Document ,isSupported method has no parameters
> Caching Driver Document ,isSupported method has no parameters

- application/Controllers/Home.php
- system/Helpers/inflector_helper.php
> Inflector Quiz

- application/Controllers/Home.php
- system/Helpers/inflector_helper.php
- system/Helpers/number_helper.php
- tests/system/Helpers/NumberHelperTest.php
Number to Roman conversion range of `if ($num < 1 OR $num > 3999)`
output conversion [here](http://webpad.apphb.com/ci4-number-to-roman)
> Number to roman

- system/Router/RouteCollection.php
- tests/system/Router/RouteCollectionTest.php
- user_guide_src/source/general/routing.rst
1.resource method.increase edit and new routes.
2.listAll to index
> URI Routing update

- system/Helpers/text_helper.php
> set more_entropy = true on uniquid at md5 random_string helper

- system/Common.php
> replace md5(mt_rand()) with bin2hex(random_bytes(16)) at Common::is_really_writable

- system/Helpers/text_helper.php
- tests/system/Helpers/TextHelperTest.php
- user_guide_src/source/helpers/text_helper.rst
I named it "crypto". If there is preferable name, please let me know.
> add random_bytes() into random_string() helper

- system/Autoloader/FileLocator.php
- system/CLI/CLI.php
- system/Commands/ListCommands.php
- system/Common.php
- system/Database/BaseBuilder.php
- system/Database/BaseResult.php
- system/Database/BaseUtils.php
- system/Debug/Toolbar/Views/toolbar.tpl.php
- system/HTTP/ContentSecurityPolicy.php
- system/HTTP/Files/FileCollection.php
- system/Helpers/form_helper.php
- system/Helpers/text_helper.php
- system/Helpers/url_helper.php
- system/Language/Language.php
- system/Validation/Rules.php
- system/Validation/Validation.php
- system/Validation/Views/list.php
- system/View/Cell.php
ref: http://maettig.com/code/php/php-performance-benchmarks.php#empty
> count() usage improvement: replace with empty() when possible, assign to variable on loop

- system/CLI/CLI.php
- system/View/Cell.php
- system/View/Parser.php
ref: http://maettig.com/code/php/php-performance-benchmarks.php#empty
> use empty() check instead of == [] compare

- system/HTTP/IncomingRequest.php
- system/HTTP/Request.php
- user_guide_src/source/libraries/incomingrequest.rst
- user_guide_src/source/libraries/request.rst
getVar, getGet, getPost, getPostGet, getGetPost, getCookie, getEnv, getServer
> forward flags support for filter_var in fetchGlobal ( and all helper func )

- system/Model.php
> using sha256 in Model::getHash()

- .travis.yml
in travis: 
7.2       -> PHP 7.2.0beta3
nightly -> PHP 7.3.0-dev
> both php 7.2 and nightly in travis

- user_guide_src/README.rst
- user_guide_src/source/contributing/documentation.rst
Fix style guideline refer error. Update tools required version.
Signed-off-by: Hex <hex@codeigniter.org.cn>
> Fix doc small error.

- system/Database/MySQLi/Connection.php
- system/Database/Postgre/Connection.php
> Fixes BaseConnection::connID false value which previously interpreted as null ( is_null )

- user_guide_src/source/libraries/request.rst
Fix name function in docs (isValidIP)
> Fix doc name function

- system/CodeIgniter.php
> Support custom App errorViewPath 

- user_guide_src/source/concepts/services.rst
- user_guide_src/source/general/filters.rst
- user_guide_src/source/general/routing.rst
- user_guide_src/source/general/urls.rst
- user_guide_src/source/general/view_parser.rst
- user_guide_src/source/general/view_renderer.rst
- user_guide_src/source/tutorial/static_pages.rst
This align the rendered user_guide codes
> Fix some example code alignments

- system/Language/en/Validation.php
- system/Validation/FormatRules.php
- tests/system/Validation/ValidationTest.php
rename rule from alpha_numeric_spaces to alpha_numeric_space
> Fix Rule name  alpha_numeric_spaces

- system/Database/Forge.php
The values ​​of delete cascade are being applied to the update
> Fixed cascade Update

- system/Config/Services.php
https://bcit-ci.github.io/CodeIgniter4/libraries/curlrequest.html#base-uri
> Enable usage of the base_uri option on Service curlrequest()

- system/Model.php
This fix will create a new Valdation instance for each model so rules from one model will stay separate from another and you can validate independently.
> Model validation fix

- system/Database/MySQLi/Connection.php
- user_guide_src/source/database/connecting.rst
> Fixes #813 unitialized connID check at \MySQLi\Connection::setDatabase()

- system/API/ResponseTrait.php
- user_guide_src/source/libraries/api_responses.rst
Add default descriptions to do not need to write this always
> Api responses

- system/HTTP/CURLRequest.php
- system/HTTP/IncomingRequest.php
- system/HTTP/RequestInterface.php
- system/HTTP/ResponseInterface.php
> Add some doc mixins to help IDEs detect default classes

- system/Language/en/Validation.php
- system/Validation/FormatRules.php
- tests/system/Validation/ValidationTest.php
- user_guide_src/source/libraries/validation.rst
Not sure if it is _really_ necessary but is done.
> Add valid_date Validation rule

- system/CLI/CLI.php
- tests/system/CLI/CLITest.php
- user_guide_src/source/libraries/cli.rst
> Add CLI::table

- README.md
Added hyperlink of Contributingmd file
https://github.com/bcit-ci/CodeIgniter4/blob/develop/contributing.md to ReadMe
> Added hyperlink to Contributing to codeigniter section

- system/Validation/Validation.php
- tests/system/Validation/RulesTest.php
- user_guide_src/source/libraries/validation.rst
"if_set" was the best name I found for this rule.
It acts like the "[sometimes](https://github.com/bcit-ci/CodeIgniter4/issues/830#issuecomment-343696307)" and cancels the field validation if no data is sent with the rule key.
"if set" because is possible set data out of an input request...
> Validation if set

- system/CodeIgniter.php
- system/Config/DotEnv.php
- system/Database/BaseResult.php
- system/Database/Forge.php
- system/HTTP/Files/FileCollection.php
- system/Helpers/html_helper.php
- system/Router/Router.php
I've cleaned the `else`s when we have already returned something, this saves us some lines of code :put_litter_in_its_place:
[`PHP-CS-Fixes`](https://github.com/FriendsOfPHP/PHP-CS-Fixer) helped me find them.
> [CS] Clean up elses

- system/Debug/Iterator.php
- system/Router/RouteCollection.php
- system/View/Parser.php
> update call_user_func with invoked function

- tests/system/Helpers/FormHelperTest.php
fix the FormHelperTest's for CSRF usage
> CSRF check in FormHelperTest

- tests/system/HTTP/IncomingRequestTest.php
Use separated config for testSetLocaleSaves
> Fix testSetLocaleSaves for non 'en' configuration

- system/Validation/Validation.php
Issue commented at https://github.com/bcit-ci/CodeIgniter4/commit/ecfe1fec774676dbc34e774832c96cd94b0ae6bf#diff-9395cda73a10792d653d5540c1b7b97b
> Avoid the session usage if is_cli() in Validation getErrors()

- system/Validation/FormatRules.php
See: https://github.com/bcit-ci/CodeIgniter/issues/5300
> Fix valid_email idn_to_ascii() on PHP 7.2

- system/Database/BaseBuilder.php
- system/Email/Email.php
- system/Helpers/form_helper.php
- system/Helpers/url_helper.php
found anothers with `OR` operator which can be replaced with `||`
> replace anothers OR operator with || operator

- system/Email/Email.php
should be uppercase `Email::CRLF`
> Fixes undefined property Email::crlf

- user_guide_src/source/libraries/index.rst
- user_guide_src/source/libraries/user_agent.rst
https://bcit-ci.github.io/CodeIgniter4/libraries/user_agent.html
> Enable user_agent in sidebar and minor updates

- system/CodeIgniter.php
```
$ php spark 
CodeIgniter CLI Tool - Version 4.0-dev - Server-Time: 2018-02-17 07:23:34am
An uncaught Exception was encountered
Type:        ErrorException
Message:     Undefined property: CodeIgniter\HTTP\CLIRequest::$uri
Filename:    /system/CodeIgniter.php
Line Number: 530
```
> Update environment check

- system/Model.php
- system/Router/Router.php
- system/Router/RouterInterface.php
- system/View/Cell.php
- tests/system/Router/RouterTest.php
> change call_user_func_array() with instance->method(...$args)

- tests/system/View/ViewTest.php
Previous version of the file had a wrong format
> Update ViewTest.php tab spacing to 4

- user_guide_src/source/database/entities.rst
this attribute creates some confusion, i changed updated_on in updated_at
'deleted_at' also seems confused. The attribute is set in the CodeIgniter\Entity class but is not used by the CodeIgniter\Model class (this one updates update_at when a record is deleted)
> user-guide database/entities change attribute  updated_on

- index.html
As index.php is moved into public directory, lets display a nice formatted guideline rather than a simple text message.
> New getup for index.html

- user_guide_src/source/contributing/styleguide.rst
Signed-off-by: codekaar <kharelbarun@gmail.com>
> Update example to be more appropriate and correct

- system/Language/en/HTTP.php
> Add pageNotFound HTTP lang

- application/Config/ContentSecurityPolicy.php
rename base_uri to baseURI and set its default to none ( based on [Google](https://csp.withgoogle.com/docs/strict-csp.html) suggestion )
> fix CSP Config baseURI name

- .gitignore
- system/Router/Router.php
> Fix exception path in Router

- system/Database/BaseResult.php
> Fix typo in BaseResult::getCustomRowObject()

- tests/system/Helpers/TextHelperTest.php
Flesh out text_helper testing; code coverage for helpers now maxed.
> Add alternator text_helper testing

- tests/system/Test/FeatureTestCaseTest.php
Oops - forgot this. Otherwise, the FeatureTestCaseTest fails :-/
> Add FeatureTestCase to DatabaseLive group

- user_guide_src/source/concepts/services.rst
- user_guide_src/source/general/testing.rst
- user_guide_src/source/general/view_parser.rst
- user_guide_src/source/libraries/user_agent.rst
- user_guide_src/source/libraries/validation.rst
Corrected errors in services, testing, view_parser, user_agent and validation pages.
> Fix sphinx errors in user guide

- application/Config/ContentSecurityPolicy.php
- system/HTTP/ContentSecurityPolicy.php
- user_guide_src/source/libraries/response.rst
> Added manifest to ContentSecurityPolicy

- user_guide_src/source/index.rst
- user_guide_src/source/libraries/index.rst
> Fix missing menu points (doc)

- tests/system/HTTP/ResponseTest.php
> Fix expected exception message for ResponseTest

- system/Cache/Handlers/MemcachedHandler.php
- system/Helpers/inflector_helper.php
- tests/system/Database/Live/ModelTest.php
- tests/system/Helpers/InflectorHelperTest.php
- tests/system/Test/FeatureResponseTest.php
- tests/system/Validation/RulesTest.php
- user_guide_src/source/helpers/inflector_helper.rst
Fixes to address travis breaking.
Some of these are [backwards incompatible PHP7.2 changes](http://php.net/manual/en/migration72.incompatible.php) to work around
> Fix travis breaking from backwards incompatiblity

- system/Common.php
by create a `static variable` of escaper. refs https://3v4l.org/e4gRE
> implements @todo Optimize Escaper instance creation to only load a single instance during page request

- system/HTTP/IncomingRequest.php
> Fix IncomingRequestURI parsing

- system/CodeIgniter.php
If a Response instance is returned,  script execution is not stop.
See application/Filters/Throttle.php for an example. Did not send 429 Code. script execution is not stop.
> Controller Filters Bug. 

- user_guide_src/source/tutorial/news_section.rst
> Add a namespace to the controller.

- user_guide_src/source/tutorial/static_pages.rst
The sample file lost the namespace
> Add a namespace to the Pages.php

- system/Files/File.php
- tests/system/Files/FileTest.php
with `SplFileInfo` instead of `SPLFileInfo`
> SplFileInfo type case

- system/Session/Session.php
- tests/system/Session/SessionTest.php
implements https://github.com/bcit-ci/CodeIgniter4/issues/1136
> implements session->push()

- system/HTTP/IncomingRequest.php
- tests/system/HTTP/IncomingRequestDetectingTest.php
fix #1109 and add a test for this case
( [easy compare](https://github.com/bcit-ci/CodeIgniter4/pull/1146/files?utf8=%E2%9C%93&diff=split&w=1) )
> Fix uri detection with no index in uri

- system/HTTP/RedirectResponse.php
- tests/system/HTTP/RedirectResponseTest.php
fixed the default parameter to call the function like docu shows
fixed the missing baseurl in resulting location
added test for route
* relative redirection only works if the baseurl has no sub folder *
> fix RedirectResponse::route and added test

- composer.json
based on https://github.com/bcit-ci/CodeIgniter4/blob/develop/README.md#server-requirements
> add ext-intl to require at composer.json

- system/View/Parser.php
> remove if ($template==forums/categories) check in View/Parser

- system/Model.php
allows to deliver to the paginate method an optional parameter with page number , useful for custom pagination implementation like:  host.com/segment/[pageNumber]
> pagination - optional page number

- composer.json
- contributing.md
- system/CodeIgniter.php
- user_guide_src/source/conf.py
Fix some of the small annoyances:
- remove unneeded composer dependency
- fix PHP version in contributing page
- make version numbers consistent
> Niggly fixes

- user_guide_src/source/libraries/api_responses.rst
> doc fix: FormatterInterface namespace

- system/Database/Forge.php
> use short array syntax

- admin/README.md
- admin/docbot.md
- admin/docbot.sh
- admin/release.md
- admin/release.sh
- user_guide_src/Makefile
Admin script to build & deploy user guide as gh-pages branch.
> Admin script for user guide build & deploy

- user_guide_src/source/database/model.rst
> typo in unset

- user_guide_src/source/installation/index.rst
- user_guide_src/source/installation/troubleshooting.rst
- user_guide_src/source/tutorial/index.rst
- user_guide_src/source/tutorial/static_pages.rst
It looks like the PHP builtin server isn't very useful with CI4, as it doesn't process .htaccess files :(
> WIP Fix docs re PHP server

- admin/post_release
- admin/release
- admin/release.md
- user_guide_src/source/changelog.rst
Further tweaking of the release build scripts - don't actually update the main repo! 
Leave that to human (error) until proven.
> Adjusting the release build scripts

- system/Helpers/form_helper.php
Change the form_hidden function declaration to fix bug #1244
> Fix #1244 (form_hidden declaration)

- public/index.php
See: https://www.grammarly.com/blog/its-vs-its
> Fix grammar in front controller comment.

- system/HTTP/RedirectResponse.php
- system/HTTP/URI.php
- tests/system/HTTP/RedirectResponseTest.php
- user_guide_src/source/general/common_functions.rst
Allows query vars to be retained when doing a redirect->back().
> Allow redirect with Query Vars from the current request.

- spark
> Change chdir('public') to chdir($public)

- system/Database/BaseUtils.php
- system/Database/MySQLi/Utils.php
- system/Helpers/xml_helper.php
- user_guide_src/source/database/index.rst
- user_guide_src/source/database/utilities.rst
by add xml helper ported from CI3 source
> Fix undefined function xml_convert at Database\BaseUtils

- system/Helpers/url_helper.php
- user_guide_src/source/helpers/xml_helper.rst
Missing page, and removed todo annotation from url_helper
> Added missing xml_helper UG page

- user_guide_src/source/changelog.rst
Revert alpha.2 until I can sort out the binaries for the release :(
> Revert alpha.2

- system/CodeIgniter.php
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/libraries/sessions.rst
supports running the after filter
Fixes issue #1315
**Checklist:**
> Filter in the router Fixes #1315

- user_guide_src/source/libraries/sessions.rst
Fixes issue #1330 
**Checklist:**
> Error in user guide for session config. Fixes #1330

- user_guide_src/source/libraries/sessions.rst
> Fix sphinx formatting in sessions

- system/CLI/CommandRunner.php
> Checks if class is instantiable and is a command

- system/View/View.php
Using a monolog will cause an error. Fixes #1358
**Checklist:**
> fix monolog will cause an error. Fixes #1358

- system/Commands/Database/CreateMigration.php
- system/Language/en/Migrations.php
- user_guide_src/source/dbmgmt/migration.rst
Have this check the settings and see what migration type of file it should create (timestamp or sequential).  Fixes #1249
**Checklist:**
- [ x User guide updated
> Missing feature migration.Fixes #1249

- system/Database/MigrationRunner.php
change method name  CheckMigrations   to  checkMigrations
**Checklist:**
> update method name in coding style

- admin/release.md
> typo fix: nanually -> manually

- system/Entity.php
Remove invisible character
**Checklist:**
- [ N ] Securely signed commits
- [ N/A ] Unit testing, with >80% coverage
- [ N/A ] User guide updated
- [ N/A ] Conforms to style guide
> Remove invisible character

- system/Model.php
The `$properties` always be array. Empty or has data can be checked with truthy check which is faster than count usage.
**Checklist:**
> count() improvement, use truthy check when possible in Model::classToArray()

- user_guide_src/source/changelog.rst
- user_guide_src/source/dbmgmt/migration.rst
> Fix migration page; update changelog

- system/Email/Email.php
Lowercase was not working on Linux
**Checklist:**
> Capitalize email filename

- user_guide_src/source/database/configuration.rst
- user_guide_src/source/database/examples.rst
- user_guide_src/source/database/queries.rst
- user_guide_src/source/database/query_builder.rst
- user_guide_src/source/dbmgmt/forge.rst
- user_guide_src/source/general/helpers.rst
- user_guide_src/source/helpers/filesystem_helper.rst
- user_guide_src/source/helpers/form_helper.rst
- user_guide_src/source/helpers/html_helper.rst
- user_guide_src/source/helpers/text_helper.rst
- user_guide_src/source/helpers/url_helper.rst
- user_guide_src/source/incoming/incomingrequest.rst
- user_guide_src/source/incoming/request.rst
- user_guide_src/source/libraries/email.rst
- user_guide_src/source/libraries/sessions.rst
- user_guide_src/source/outgoing/response.rst
- user_guide_src/source/outgoing/view_parser.rst
- user_guide_src/source/testing/benchmark.rst
Apply short array syntax in `user_guide_src` directory.
**Checklist:**
> short array syntax in docs

- tests/system/Throttle/ThrottleTest.php
> Tweak throttle testing

- system/Router/RouteCollectionInterface.php
RouteCollectionInterface needs a third parameter, per usage and examples in the user guide.
This could be what is messing up phpcbf!
> Add missing parameter to RouteCollectionInterface

- system/Commands/Database/CreateMigration.php
Fix Migrations.classNotFound. Fixes #1420
**Checklist:**
> fix Migrations.classNotFound. Fixes #1420

- system/Helpers/array_helper.php
- `array_value_dot` -> `dot_array_search`
- `array_search_dot` -> `_array_search_dot`
**Checklist:**
> function_exists() typo fixes on array_helper

- system/HTTP/Files/UploadedFile.php
- system/HTTP/Response.php
- tests/_support/HTTP/MockResponse.php
- tests/system/HTTP/RedirectResponseTest.php
- tests/system/HTTP/ResponseTest.php
- tests/system/HTTP/URITest.php
Improving unit testing coverage; clarifying some original code.
> Beef up HTTP URI & Response testing

- user_guide_src/source/concepts/structure.rst
To match application directory folders.
**Checklist:**
> documentation: add missing application structures: Database, Filters, ThirdParty directory

- system/Email/Email.php
- tests/system/Router/RouteCollectionTest.php
- tests/system/Router/RouterTest.php
Refactoring ot the last few classes referencing github issues, to use the new repo org name.
These were done separately to segregate the code that phpcbf mangled.
> Tailor the last few repo org names (3of4)

- README.md
- application/Views/welcome_message.php
- system/Debug/Toolbar/Views/_config.tpl.php
- tests/system/Database/Builder/UpdateTest.php
- tests/system/Database/Live/UpdateTest.php
bcit-ci/CodeIgniter4 transferred to codeigniter4/CodeIgniter4
This fixes the last of the references to bcit-ci
> Fix the remaining bcit-ci references

- system/HTTP/RedirectResponse.php
- system/Router/RouteCollection.php
> remove unused use statements

- system/Format/XMLFormatter.php
> remove unused local variable $result in XMLFormatter::format()

- tests/system/I18n/TimeTest.php
Add the "close enough" time testing to TimeTest::testTestNow()
> Fuzzify another time test

- system/Database/Forge.php
- user_guide_src/source/dbmgmt/forge.rst
Correct the phpdocs in Forge::addField, as well as the user guiode page fot that class.
Fixes #1474
> Correct phpdocs for Forge::addField()

- system/Session/Handlers/BaseHandler.php
$this->ipAdddress to $this->ipAddress (triple d)
**Checklist:**
**Notes**
> Small typo in Session\Handlers\BaseHandler.php

- admin/post_release
> missing slash

- system/Language/Language.php
> Load Language strings from other locations

- system/Database/BaseBuilder.php
- system/Database/BaseConnection.php
- system/HTTP/Response.php
Log errors as indicated by todo tags.
Closes #1250 #1254
> Error logging

- tests/system/HTTP/URITest.php
Test segment *fallback*?
**Checklist:**
> Add URI segment test

- user_guide_src/source/helpers/form_helper.rst
reported on forum: https://forum.codeigniter.com/thread-72192.html
> Fix form_helper's set_value writeup

- .gitignore
Some files registered in `.gitignore` no longer there.
**Checklist:**
> .gitignore clean up

- system/CodeIgniter.php
- system/Router/Router.php
- tests/system/Router/RouterTest.php
> Check if the matched route regex is filtered

- system/Router/RouteCollection.php
- tests/system/Router/RouteCollectionTest.php
Increases coverage.
**Checklist:**
> Test routes resource with 'websafe' option

- user_guide_src/source/concepts/security.rst
- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/models/entities.rst
Add rules description
**Checklist:**
> Update validation class User Guide

- system/Database/Config.php
- tests/system/Database/Live/ConnectTest.php
Database connect now stores separate instances for multiple custom configurations. Fixes #1533
> Serviceinstances

- system/Helpers/url_helper.php
- tests/system/Helpers/URLHelperTest.php
site_url should add / only if a path is provided
-> fix debugbar loading url
.../index.php/?debugbar -> .../index.php?debugbar
**Checklist:**
> Fix site_url generate invalid url

- system/Debug/Toolbar/Views/toolbarloader.js.php
adjust length calculation for the style blocks - fix the time-line-0 css
**Checklist:**
> Fix Toolbar invalid css

- system/Test/CIUnitTestCase.php
- system/Test/FeatureResponse.php
- system/Test/FeatureTestCase.php
- tests/system/Test/FeatureResponseTest.php
- tests/system/Test/FeatureTestCaseTest.php
- tests/system/Test/TestCaseTest.php
- user_guide_src/source/testing/overview.rst
Brings code coverage for system/Test as close to complete as practical
> Flesh out the Test package testing

- system/I18n/Time.php
- tests/system/I18n/TimeDifferenceTest.php
- tests/system/I18n/TimeTest.php
Added tests, better code coverage.
Still issues with Time::toFormattedDateString, previously commented on
Removed Time::__set, as it is inconsistent with returning a value for a setter
> Flesh out I18n testing

- system/HTTP/Files/UploadedFile.php
For concistency with other classes which uses statements are applied after license doc block.
**Checklist:**
> move use statement after License doc at UploadedFile class

- system/Model.php
DBGroup should be passed to ->run instead of ->setRules
> DBGroup should be passed to ->run instead of ->setRules

- admin/starter/README.md
> Fix starter README

- system/HTTP/ContentSecurityPolicy.php
- system/Helpers/xml_helper.php
- system/Language/Language.php
- system/Log/Exceptions/LogException.php
- system/Log/Handlers/FileHandler.php
- tests/system/HTTP/ContentSecurityPolicyTest.php
- tests/system/HTTP/IncomingRequestTest.php
- tests/system/Helpers/NumberHelperTest.php
- tests/system/Helpers/TextHelperTest.php
- tests/system/Helpers/XMLHelperTest.php
- tests/system/Log/FileHandlerTest.php
Improve code coverage for HTTP, Helper, Language & Log modules.
Remove some extransous code; fix xml_helper bug
> More unit testing tweaks

- system/HTTP/ContentSecurityPolicy.php
> CSP nonce attribute value in "" 

- system/Debug/Toolbar/Collectors/Logs.php
> Toolbar - Return Logger::$logCache items when collecting

- tests/system/View/ParserPluginTest.php
- tests/system/View/ParserTest.php
> Enhance Parser & Plugin testing

- user_guide_src/source/installation/downloads.rst
- user_guide_src/source/installation/installing.rst
- user_guide_src/source/installation/running.rst
Updated installation docs, all flavors
> Updated download & installation docs

- admin/release-appstarter
- admin/starter/app/Config/Paths.php
- user_guide_src/source/changelogs/next.rst
> Fix admin - app starter creation

- system/Filters/CSRF.php
- system/Filters/DebugToolbar.php
- system/Filters/Honeypot.php
Oops - forgot to add these earlier
> Add copyright blocks to filters

- user_guide_src/source/installation/installing_composer.rst
- user_guide_src/source/installation/running.rst
Update the "running your app" page, thanks to feedback from my COMP4711 class
> Update the running docs

- user_guide_src/source/changelogs/next.rst
> Update changelog for alpha.5

- app/Config/Routes.php
- system/Router/RouteCollection.php
Ensure  isn't checked during RouteCollection calls when called from C…LI. Fixes #1724
> Ensure  isn't checked during RouteCollection calls when called from CLI

- app/Config/Routes.php
- system/Router/RouteCollection.php
Reverts codeigniter4/CodeIgniter4#1730
> Revert "Ensure  isn't checked during RouteCollection calls when called from CLI"

- system/Router/RouteCollection.php
> Don't check  from CLI in Routes. Fixes #1724

- system/Database/Postgre/Builder.php
> Fix increment and decrement errors with Postgres

- admin/release-appstarter
- admin/release-framework
- admin/starter/phpunit.xml.dist
- system/Test/ControllerResponse.php
- system/Test/ControllerTester.php
- system/Test/DOMParser.php
- system/Test/FeatureResponse.php
- tests/_support/Helpers/ControllerResponse.php
- tests/system/Database/Live/SQLite/AlterTableTest.php
- tests/system/Helpers/FilesystemHelperTest.php
- tests/system/Test/DOMParserTest.php
- user_guide_src/source/testing/controllers.rst
> Refactor test support for app starter

- system/Model.php
- system/Validation/Validation.php
- tests/_support/Models/ValidErrorsModel.php
- tests/system/Database/Live/ModelTest.php
- tests/system/Validation/ValidationTest.php
Ensure validation works in Model with errors as part of rules. Fixes #1574
> Ensure validation works in Model with errors as part of rules. Fixes #1574

- system/Router/Router.php
- user_guide_src/source/tutorial/static_pages.rst
Fix routing when no default route has been specified. Fixes #1758
> Fix routing when no default route has been specified. Fixes #1758

- app/Views/welcome_message.php
- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/next.rst
- user_guide_src/source/installation/installing_composer.rst
- user_guide_src/source/installation/installing_git.rst
- user_guide_src/source/installation/running.rst
> Housekeeping for beta.1

- user_guide_src/source/libraries/files.rst
**Checklist:**
**Notes**
Fixes issue #1781 by correcting two typos in the documentation section "Taking Advantage of Spl"
> Correction of typos in documentation as mentioned in issue #1781

- system/Validation/ValidationInterface.php
- user_guide_src/source/incoming/controllers.rst
Controller form validation changes
**Checklist:**
> Controller form data validation correction

- system/Helpers/form_helper.php
- system/Helpers/html_helper.php
- system/Helpers/number_helper.php
- system/Helpers/text_helper.php
- system/Helpers/url_helper.php
- system/Helpers/xml_helper.php
- tests/system/Helpers/TextHelperTest.php
- user_guide_src/source/helpers/url_helper.rst
Some Helper changes w.r.t,
- Changing fields names according to documentation to maintain the consistency
- Added doxygen comments wherever missing
- Changed datatype of variable according to documentaion on the doxygen comments
- Changed user guide documentation according to the function definitions.
- Removed the word_censor test scenario where second argument is string. According to function definition and documentation, second parameter should be array
**Checklist:**
> Some Helper Changes

- system/CodeIgniter.php
- system/ComposerScripts.php
- system/Entity.php
- system/Model.php
Some Base functional changes w.r.t.
- Doxygen comments
- Datatypes and return types
- Added exceptions in function comments
**Checklist:**
> Some Base Functional Changes

- system/Database/Query.php
Some changes in Query Class w.r.t.,
- Typos
- Bind value correction
- Return Types
**Checklist:**
> Query Class Changes

- system/Database/BaseBuilder.php
want to know what tests this will break.
If all tests will pass I will write what is better in this approach.
> test - replace only last operator in field name.

- system/CodeIgniter.php
- system/Controller.php
- system/Debug/Exceptions.php
- system/Filters/CSRF.php
- system/HTTP/Files/UploadedFile.php
- system/HTTP/Request.php
- system/Helpers/form_helper.php
- system/Helpers/text_helper.php
- system/Language/en/HTTP.php
- system/Model.php
- system/Router/RouteCollection.php
- system/Session/Handlers/MemcachedHandler.php
- system/Session/Session.php
- tests/system/Helpers/FormHelperTest.php
Fix the fix #1808 for the fix #1804
> Fix: Model::save needs to call insert properly

- system/CodeIgniter.php
- system/Config/BaseConfig.php
- system/Config/BaseService.php
- system/Controller.php
- system/Debug/Exceptions.php
- system/HTTP/Files/UploadedFile.php
- system/HTTP/Request.php
- system/Helpers/form_helper.php
- system/Helpers/text_helper.php
- system/Language/en/HTTP.php
- system/Router/RouteCollection.php
- system/Session/Handlers/MemcachedHandler.php
- system/Session/Session.php
- tests/_support/Config/BadRegistrar.php
- tests/_support/Config/MockServices.php
- tests/system/Config/BaseConfigTest.php
- tests/system/Config/ConfigTest.php
- tests/system/Config/ServicesTest.php
- tests/system/Helpers/FormHelperTest.php
- user_guide_src/source/concepts/services.rst
More unit tests; updated user guide page.
Cruft from the style fixer :-/
> Test: Config module coverage improved

- system/Validation/Rules.php
Removed the if condition as it was not required.
**Checklist:**
> Code improvement in exact_length Rule

- system/Model.php
- tests/system/Database/Live/ModelTest.php
- user_guide_src/source/models/model.rst
W.r.t #1657, I have added functionality in Model,
- Added functions for setValidationMessage & setValidationMessages
- Added respective test scenarios
- Added user guide documentation
**Checklist:**
> Model setValidationMessage functions introduced

- admin/alldocs
- admin/apibot
- admin/apibot.md
- admin/docbot.md
- phpdoc.dist.xml
New scripts: apibot, alldocs
Tied in to new repo: codeigniter4/api
> Add apibot for API docs using phpDocumentor

- user_guide_src/source/models/model.rst
> Fix: sphinx errors in model.rst

- tests/system/Router/RouteCollectionTest.php
Add missing tests for Router\RouteCollection
> Test: enhance RouteCollection coverage

- system/View/View.php
- tests/system/View/ViewTest.php
- tests/system/View/Views/extend_include.php
- user_guide_src/source/outgoing/view_layouts.rst
> Adding include method to View library to render view partials within layout-driven views. Fixes #1826

- user_guide_src/source/general/configuration.rst
- user_guide_src/source/tutorial/news_section.rst
Correct mistakes pointed out in the tutorial news section & configuration pages
> Docs: fix niggly errors

- system/API/ResponseTrait.php
- system/HTTP/ContentSecurityPolicy.php
- system/HTTP/DownloadResponse.php
- system/HTTP/IncomingRequest.php
- system/HTTP/Message.php
- system/HTTP/Request.php
Fix some PHPDoc comments error
**Checklist:**
> Fix some PHPDoc comments error

- tests/system/View/ViewTest.php
- tests/system/View/Views/apples.php
- tests/system/View/Views/broken.php
Two more Layout tests, to bring code coverage back up to 100%
> Test: Improve View\View coverage

- system/Database/BaseBuilder.php
- system/Database/BaseConnection.php
- system/Database/Config.php
- system/Database/MigrationRunner.php
- system/Database/MySQLi/Utils.php
- system/Database/Postgre/Utils.php
- system/Database/SQLite3/Forge.php
- system/Database/SQLite3/Result.php
- system/Database/SQLite3/Utils.php
Typos correction in DB module
**Checklist:**
> Typos correction in DB module

- system/Events/Events.php
- tests/system/Events/EventsTest.php
Events should actually work with any callable now. Fixes #1835
> Events should actually work with any callable now. Fixes #1835

- contributing/styleguide.rst
- phpdoc.dist.xml
Use better template; simplify files directives.
> Docs: fix phpdoc config

- system/API/ResponseTrait.php
- system/Autoloader/Autoloader.php
- system/Autoloader/FileLocator.php
Move namespace declarations for API docs
> Docs: fix phpdocs for API & Autoloader

- system/CLI/BaseCommand.php
- system/CLI/CLI.php
- system/CLI/CommandRunner.php
- system/CLI/Console.php
Move namespace declaration; add needed class docblocks
> Docs: fix phpdocs for CLI

- system/CodeIgniter.php
- system/Commands/Database/CreateMigration.php
- system/Commands/Database/MigrateCurrent.php
- system/Commands/Database/MigrateLatest.php
- system/Commands/Database/MigrateRefresh.php
- system/Commands/Database/MigrateRollback.php
- system/Commands/Database/MigrateStatus.php
- system/Commands/Database/MigrateVersion.php
- system/Commands/Database/Seed.php
- system/Commands/Help.php
- system/Commands/ListCommands.php
- system/Commands/Server/Serve.php
- system/Commands/Sessions/CreateMigration.php
- system/Commands/Utilities/Namespaces.php
- system/Commands/Utilities/Routes.php
- system/Config/AutoloadConfig.php
- system/Config/BaseConfig.php
- system/Config/BaseService.php
- system/Config/Config.php
- system/Config/DotEnv.php
- system/Config/ForeignCharacters.php
- system/Config/Services.php
- system/Config/View.php
> Docs: fix phpdocs for CodeIgniter, Commands & Config

- system/Cache/CacheFactory.php
- system/Cache/CacheInterface.php
- system/Cache/Handlers/DummyHandler.php
- system/Cache/Handlers/FileHandler.php
- system/Cache/Handlers/MemcachedHandler.php
- system/Cache/Handlers/PredisHandler.php
- system/Cache/Handlers/RedisHandler.php
- system/Cache/Handlers/WincacheHandler.php
Move namespace declarations; add missing class docblocks.
> Docs: fix phpdocs for Cache

- system/Debug/Exceptions.php
- system/Debug/Iterator.php
- system/Debug/Timer.php
- system/Debug/Toolbar.php
- system/Debug/Toolbar/Collectors/BaseCollector.php
- system/Debug/Toolbar/Collectors/Config.php
- system/Debug/Toolbar/Collectors/Database.php
- system/Debug/Toolbar/Collectors/Events.php
- system/Debug/Toolbar/Collectors/Files.php
- system/Debug/Toolbar/Collectors/History.php
- system/Debug/Toolbar/Collectors/Logs.php
- system/Debug/Toolbar/Collectors/Routes.php
- system/Debug/Toolbar/Collectors/Timers.php
- system/Debug/Toolbar/Collectors/Views.php
- system/Events/Events.php
Move namespace declarations; add missing class docblocks
> Docs: fix phpdocs for Debug & Events

- system/Files/File.php
- system/Filters/CSRF.php
- system/Filters/DebugToolbar.php
- system/Filters/FilterInterface.php
- system/Filters/Filters.php
- system/Filters/Honeypot.php
- system/Format/FormatterInterface.php
- system/Format/JSONFormatter.php
- system/Format/XMLFormatter.php
> Docs: fix phpdocs for Files, Filters & Format

- system/HTTP/CLIRequest.php
- system/HTTP/CURLRequest.php
- system/HTTP/ContentSecurityPolicy.php
- system/HTTP/DownloadResponse.php
- system/HTTP/Exceptions/HTTPException.php
- system/HTTP/Files/FileCollection.php
- system/HTTP/Files/UploadedFile.php
- system/HTTP/Files/UploadedFileInterface.php
- system/HTTP/Header.php
- system/HTTP/IncomingRequest.php
- system/HTTP/Message.php
- system/HTTP/Negotiate.php
- system/HTTP/RedirectResponse.php
- system/HTTP/Request.php
- system/HTTP/RequestInterface.php
- system/HTTP/Response.php
- system/HTTP/ResponseInterface.php
- system/HTTP/URI.php
- system/HTTP/UserAgent.php
> Docs: fix phpdocs for HTTP

- system/CodeIgniter.php
- system/ComposerScripts.php
- system/Controller.php
- system/Entity.php
- system/Model.php
Move namespace declarations; add missing class docblocks
> Docs: fix phpdocs for core classes

- system/Helpers/array_helper.php
- system/Helpers/date_helper.php
- system/Helpers/filesystem_helper.php
- system/Helpers/form_helper.php
- system/Helpers/html_helper.php
- system/Helpers/number_helper.php
- system/Helpers/security_helper.php
- system/Helpers/text_helper.php
- system/Helpers/url_helper.php
- system/Helpers/xml_helper.php
- system/Honeypot/Honeypot.php
- system/I18n/Time.php
- system/I18n/TimeDifference.php
- system/Images/Handlers/BaseHandler.php
- system/Images/Handlers/GDHandler.php
- system/Images/Handlers/ImageMagickHandler.php
- system/Images/Image.php
- system/Images/ImageHandlerInterface.php
- system/Language/Language.php
> Docs: fix phpdocs for Helpers, I18n, Images & Language

- system/Log/Handlers/BaseHandler.php
- system/Log/Handlers/ChromeLoggerHandler.php
- system/Log/Handlers/FileHandler.php
- system/Log/Handlers/HandlerInterface.php
- system/Log/Logger.php
- system/Pager/Pager.php
- system/Pager/PagerInterface.php
- system/Pager/PagerRenderer.php
- system/Router/RouteCollection.php
- system/Router/RouteCollectionInterface.php
- system/Router/Router.php
- system/Router/RouterInterface.php
- system/Security/Security.php
> Docs: fix phpdocs for Log, Pager, Router & Security

- system/Session/Handlers/BaseHandler.php
- system/Session/Handlers/DatabaseHandler.php
- system/Session/Handlers/FileHandler.php
- system/Session/Handlers/MemcachedHandler.php
- system/Session/Handlers/RedisHandler.php
- system/Session/Session.php
- system/Session/SessionInterface.php
- system/Test/CIDatabaseTestCase.php
- system/Test/CIUnitTestCase.php
- system/Test/ControllerResponse.php
- system/Test/ControllerTester.php
- system/Test/DOMParser.php
- system/Test/FeatureResponse.php
- system/Test/FeatureTestCase.php
- system/Test/Filters/CITestStreamFilter.php
- system/Test/ReflectionHelper.php
- system/Throttle/Throttler.php
- system/Throttle/ThrottlerInterface.php
> Docs: fix phpdocs for Session, Test & Throttle

- system/Typography/Typography.php
- system/Validation/CreditCardRules.php
- system/Validation/FileRules.php
- system/Validation/FormatRules.php
- system/Validation/Rules.php
- system/Validation/Validation.php
- system/Validation/ValidationInterface.php
- system/View/Cell.php
- system/View/Filters.php
- system/View/Parser.php
- system/View/Plugins.php
- system/View/RendererInterface.php
- system/View/View.php
> Docs: fix phpdocs for Typography, Validation & View

- system/Filters/Honeypot.php
- system/Honeypot/Honeypot.php
Some Typos Fixings
**Checklist:**
> Typos fixings

- system/Router/Router.php
Router Changes w.r.t #1541
**Checklist:**
> Router Changes w.r.t #1541

- system/Debug/Toolbar.php
Toolbar fix w.r.t #1779
**Checklist:**
> Toolbar fix w.r.t #1779

- system/Database/BaseBuilder.php
- tests/system/Database/Live/WhereTest.php
SubQuery related test cases w.r.t #1775
**Checklist:**
> SubQuery related test cases w.r.t #1775

- tests/system/Router/RouteCollectionTest.php
The reported problem tests behave as expected.
The second :non-working" test was actually working - with two rules that both matchm the second will overwrite the first.
> More RouteCollection tests for overwriting. Closes #1692

- system/HTTP/CURLRequest.php
Fix for POST + JSON (Content-Length added)
> Fix for POST + JSON (Content-Length added)

- system/Database/BaseResult.php
- system/Database/BaseUtils.php
- system/Database/Forge.php
- system/Database/SQLite3/Connection.php
- system/Database/SQLite3/Result.php
- system/Language/en/Database.php
- tests/_support/Database/MockTestClass.php
- tests/system/Database/BaseQueryTest.php
- tests/system/Database/Live/DbUtils.php
- tests/system/Database/Live/DbUtilsTest.php
- tests/system/Database/Live/ForgeTest.php
- tests/system/Database/Live/GetTest.php
- tests/system/Database/Migrations/MigrationRunnerTest.php
W.r.t #512, adding database test cases
**Checklist:**
> Database Test Cases

- system/Format/FormatterInterface.php
- system/Format/JSONFormatter.php
- system/Format/XMLFormatter.php
> JSONFormatter

- system/Debug/Toolbar.php
Make sure the value is a string before using preg_match function
> Check if the value is string

- admin/framework/composer.json
- admin/starter/composer.json
- composer.json
- user_guide_src/source/installation/running.rst
Resolve hiccup with different composer installs
> Update phpunit.xml scripts. Fixes #1932

- user_guide_src/source/libraries/validation.rst
Fix validation table format mistake introduced in #1952
> Fix validation table format

- system/HTTP/CLIRequest.php
- system/Images/Handlers/BaseHandler.php
Just a small refactoring, following #861 💅 
**Checklist:**
> Use Null Coalesce Operator

- system/API/ResponseTrait.php
> WIP - Fix side issue

- user_guide_src/source/libraries/validation.rst
Fix RST table format syntax error introduced during one of the recent changes
> Fix validation rules table format

- system/View/Table.php
- tests/_support/View/MockTable.php
- tests/system/View/TableTest.php
- user_guide_src/source/libraries/index.rst
- user_guide_src/source/outgoing/index.rst
- user_guide_src/source/outgoing/table.rst
This CI3 component fell through the cracks originally.
Noticed & requested in a forum thread: https://forum.codeigniter.com/thread-73324.html
**Checklist:**
> Implement HTML Table for CI4

- system/View/Table.php
- tests/system/View/TableTest.php
- user_guide_src/source/libraries/index.rst
- user_guide_src/source/outgoing/table.rst
Provide for <tfoot>, pointed out on the forum.
**Checklist:**
> Add footing to HTML Table

- admin/release-appstarter
- admin/release-deploy
- phpdoc.dist.xml
- user_guide_src/source/changelogs/next.rst
- admin script tuning
- phpdoc config tuning
- changelog for beta.3
> Prep for beta.3

- system/Debug/Toolbar/Collectors/Routes.php
The `Routes` toolbar collector needs to pass the new additional parameter for the router service.
**Checklist:**
> Support the new `router` service in Debug Toolbar

- system/Commands/Database/MigrateRollback.php
- user_guide_src/source/concepts/autoloader.rst
- user_guide_src/source/database/query_builder.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/installation/installing_composer.rst
- user_guide_src/source/libraries/sessions.rst
- user_guide_src/source/models/entities.rst
I've been noting typos as I go, this is a rollup of what I have so far.
**Checklist:**
> Various typos and Guide corrections

- user_guide_src/source/concepts/autoloader.rst
> Fix autoloader.rst formatting

- system/Entity.php
#2080 
(...) And I thought the correct code was (strpos($value, '"') === 0 && strrpos($value, '"') === strlen($value) - 1 ) (...)
> JSON format checking improved

- admin/release-framework
- admin/starter/composer.json
> Update the starters

- user_guide_src/source/outgoing/localization.rst
Correct the composer autoload config in the translations repo, and re-released its beta.4
Adjusted the localization writeup.
> Fix localization writeup

- user_guide_src/source/dbmgmt/migration.rst
A few quick User Guide adjustments for recent Migrations refactor.
**Checklist:**
> Migrations user guide fixes

- app/Controllers/Home.php
Remove the `UserModel` reference from `Home` Controller (referenced on https://github.com/codeigniter4/appstarter/pull/4).
**Checklist:**
> Remove UserModel reference from Home controller

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/next.rst
- user_guide_src/source/dbmgmt/migration.rst
- user_guide_src/source/libraries/email.rst
Correct user guide errors on migration & email pages.
Update changelog, getting ready for RC.1
> Fix email & migrations docs; update changelog

- app/Config/Migrations.php
Migrations should be enabled by default.
> Update migrations config

- user_guide_src/source/libraries/images.rst
Quick User Guide update to explain how to change JPEG image quality.
Ref. https://forum.codeigniter.com/thread-74206.html
**Checklist:**
> Add $quality usage for Image Library

- system/Honeypot/Honeypot.php
> Fix missing form close tag

- user_guide_src/source/outgoing/view_parser.rst
> [ci skip] Fix malformed table in view_parser.rst

- user_guide_src/source/outgoing/api_responses.rst
Align class ref in user guide to source code ... ResponseTrait.
Fixes #2176
> Fix class ref parameter types

- system/Debug/Exceptions.php
> Fix parameter type in Debug/Exceptions

- tests/system/Database/Builder/UpdateTest.php
A simple test to make sure everything is ok - #1929.
**Checklist:**
> Test set() method in Builder class more

- system/Session/Handlers/FileHandler.php
> Resolve session save handler issue

- user_guide_src/source/incoming/restful.rst
A couple of notes to make things clearer.
**Checklist:**
> RESTful User Guide cleanup

- user_guide_src/source/models/model.rst
Add to the Model's user guide page.
Closes #2304
> Add getValidationRules() to model UG page

- system/Helpers/url_helper.php
- tests/system/Helpers/URLHelperTest.php
This PR fixes the problem with lowercasing the diacritics.
Ref: #2323
**Checklist:**
> Fix bug in url_title() function with diacritics

- user_guide_src/source/incoming/routing.rst
Amend the docs, per Lonnie's explanation.
The routing situation that doesn't work wasn't intended to.
Closes #2299
> Correct the routing UG page

- tests/README.md
Just a bit of rewriting seeking clarity.
> Tests readme polish

- user_guide_src/source/installation/upgrade_4xx.rst
Update the documentation.
**Checklist:**
> Update Application Structure

- system/Email/Email.php
> Fix SMTP protocol problem

- user_guide_src/source/extending/core_classes.rst
Changed example code in docs to match what is found in  core code
> Docs Rev: Replacing Core Classes [ci skip]

- system/Commands/Database/Seed.php
Replaces a pasted comment with proper description.
**Checklist:**
> Fix copypaste command comment

- public/.htaccess
When we try open real directory, server add end slash, htaccess removes it, server add slash...
And we get recursive redirectings
Added check for directory existence
> Edit .htaccess

- user_guide_src/source/incoming/incomingrequest.rst
> Looks like a typo.

- system/Helpers/url_helper.php
> fix. safe_mailto multi-byte safe

- user_guide_src/source/incoming/incomingrequest.rst
> [ci skip] Fix Message method reference

- system/Debug/Toolbar.php
- system/Debug/Toolbar/Views/toolbar.css
Nice array view in debug toolbar https://prnt.sc/q6am3e
(Button Vars in tollbar)
> Nice array view in debug toolbar 

- user_guide_src/README.rst
> fix sphinx version.

- system/View/Cell.php
> view_cell call controller on initController method.

- user_guide_src/source/testing/debugging.rst
> [ci skip] update toolbar userguide

- app/Config/Autoload.php
- system/Autoloader/FileLocator.php
- tests/system/Autoloader/FileLocatorTest.php
- tests/system/Language/LanguageTest.php
Update ordering of search locations for better prioritization. Fixes #2354
Now will search in the following order: 
- App
- Config
- Any Modules
- CodeIgniter
> Update ordering of search locations for better prioritization. Fixes #2354

- user_guide_src/source/models/entities.rst
Working With Entities - Handling Business Logic had an incorrect description on how to update attributes.
https://forum.codeigniter.com/thread-75268-post-371258.html
**Checklist:**
> [ci skip] Typo in userguide "Entity Classes - Business Logic"

- system/Debug/Toolbar/Collectors/Database.php
Add highlight to JOIN
Now highlight like ".. JO<strong>IN</strong> ..."
> Database add highlight

- .travis.yml
- system/Autoloader/FileLocator.php
- system/HTTP/Files/UploadedFile.php
> Update TravisCI config for PHP7.4

- system/Common.php
- system/Database/ModelFactory.php
- tests/system/Database/ModelFactoryTest.php
- user_guide_src/source/models/model.rst
New model factory to make it simple to share a single instance of model files, just like you would config files, etc.
> Added new model helper method.

- admin/userguide/README.md
Fixed Markdown heading:
Added a space in a Markdown file so the heading is displayed properly.
**Checklist:**
> Fixed Markdown heading

- system/Email/Email.php
- tests/system/Email/EmailTest.php
Fix issue #2580 
**Checklist:**
> Fix type error in email validation

- CONTRIBUTING.md
Typos changes
forusm -> forums
quality -> the quality
open source -> open-source
**Checklist:**
> Typos change in contributing.md

- system/Commands/Utilities/Routes.php
- system/Debug/Toolbar/Collectors/Routes.php
- system/Debug/Toolbar/Views/_routes.tpl
w.r.t #2568 
made changes to make it live on Monday 24th Feb
**Checklist:**
> Better debug routes

- contributing/css.rst
Added color scheme information in the documentation
**Checklist:**
> Add color scheme information in the documentation

- user_guide_src/source/extending/authentication.rst
- user_guide_src/source/extending/index.rst
This is my last ditch effort at getting some consistency around user definitions in before release.
**Checklist:**
> User Guide authentication recommendations

- app/Views/welcome_message.php
Added a "Go further" section on the welcome page
**Checklist:**
> Add a "Go further" section on the welcome page

- user_guide_src/source/_themes/sphinx_rtd_theme/static/css/citheme.css
Brings graphic improvements. See commits below for a detailed list of modifications.
**Checklist:**
> [UG] Sphinx_rtd_theme fixes and improvements

- system/Test/FeatureTestCase.php
- tests/system/Test/FeatureTestCaseTest.php
Fixing buffer in test case:
```
There was 1 risky test:
1) FeatureTestCaseTest::testEchoes
Test code or tested code did not (only) close its own output buffers
```
**Checklist:**
> Fixing buffer FeaturetestCaseTest::testEchoes()

- user_guide_src/source/cli/cli.rst
- user_guide_src/source/concepts/autoloader.rst
- user_guide_src/source/concepts/security.rst
- user_guide_src/source/concepts/services.rst
- user_guide_src/source/extending/contributing.rst
- user_guide_src/source/extending/events.rst
- user_guide_src/source/general/errors.rst
- user_guide_src/source/general/logging.rst
- user_guide_src/source/helpers/filesystem_helper.rst
- user_guide_src/source/helpers/url_helper.rst
- user_guide_src/source/incoming/incomingrequest.rst
- user_guide_src/source/incoming/message.rst
- user_guide_src/source/incoming/request.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/installation/installing_manual.rst
- user_guide_src/source/installation/repositories.rst
- user_guide_src/source/intro/credits.rst
- user_guide_src/source/intro/psr.rst
- user_guide_src/source/intro/requirements.rst
- user_guide_src/source/libraries/caching.rst
- user_guide_src/source/libraries/curlrequest.rst
- user_guide_src/source/libraries/encryption.rst
- user_guide_src/source/libraries/files.rst
- user_guide_src/source/libraries/sessions.rst
- user_guide_src/source/libraries/time.rst
- user_guide_src/source/outgoing/localization.rst
- user_guide_src/source/outgoing/response.rst
- user_guide_src/source/outgoing/view_parser.rst
**Steps to reproduce**
Navigate to "user_guide_src". Run command "make linkcheck". It checks all links in the documentation. This is a feature of Sphinx. **Many warnings are displayed.**
Commit 1:  Files with simple fixes, mostly "http" replaced by "https"
Commit 2: Files with broken links, or links requiring text changes
**The test is 100% successful after these changes are applied.**
> [UG] Fix all links to pass "linkcheck" test

- user_guide_src/source/general/configuration.rst
Revised configuration.rst as discussed in issue #2554
> [ci skip] Revamp Configuration docs page.

- user_guide_src/source/tutorial/index.rst
Fix a typo : renmae > rename
**Checklist:**
> Fix a typo.

- user_guide_src/source/general/urls.rst
- user_guide_src/source/installation/running.rst
An error was found in the userguide by [tweenietomatoes](https://forum.codeigniter.com/thread-75696-post-372919.html).
I also added Nginx as a supported way of "Running Your App" with a fix for 404 pages, that normally are undocumented. Bitnami hyperlink rendering issue have also been fixed, on the same page.
**Checklist:**
> Added default configuration for Nginx in "Running Your App" [ci-skip]

- README.md
add some useful badges :  downloads, latest release, stars, license, contributions
**Checklist:**
> [ci skip] add some useful badges - README.md

- README.md
Reverts codeigniter4/CodeIgniter4#2672
> Revert "[ci skip] add some useful badges - README.md"

- README.md
link fixed for latest release and License badges.
**Checklist:**
> [ci skip] link fixed - latest release and License

- user_guide_src/source/general/ajax.rst
fix a link text problem
**Checklist:**
> fix a link text problem

- user_guide_src/source/installation/installing_composer.rst
- Fix unpaired backquotes and missing '4' in vendor path
- Rewrite the same line to make it clear what needs to be done, with an example
> [Docs] Fix Composer Installation Page - existing Project

- system/Model.php
- tests/system/Database/Live/ModelTest.php
> Add exception to undefined method call in model

- README.md
- admin/framework/README.md
- admin/starter/README.md
- admin/userguide/README.md
The pre-release not no longer needed in readmes
**Checklist:**
> [ci skip] remove "pre-release" note in readmes

- system/Database/BaseBuilder.php
Fix pull MR https://github.com/codeigniter4/CodeIgniter4/pull/2675
**Checklist:**
**Notes**
> hotfix: fix return type in BaseBuilder.php

- system/Validation/Validation.php
- tests/system/Validation/ValidationTest.php
> Adding tests for custom errors with rule group

- system/Model.php
This is the right way to set testMode
**Checklist:**
> the right way to set testMode

- system/HTTP/IncomingRequest.php
- system/HTTP/URI.php
- system/Router/Router.php
- tests/system/HTTP/URITest.php
- tests/system/Router/RouteCollectionTest.php
- tests/system/Router/RouterTest.php
- tests/system/Test/FeatureTestCaseTest.php
> Bug Fix: Fix #2716 open path /0 got error on development and 200OK on production, which should be 404

- system/Router/RouteCollection.php
- tests/system/Router/RouteCollectionTest.php
Fix thread: https://forum.codeigniter.com/thread-75781.html
**Checklist:**
> Adjust reverse route for multi-language apps

- tests/_support/Controllers/Popcorn.php
- tests/system/Config/DotEnvTest.php
- tests/system/HTTP/CLIRequestTest.php
- tests/system/HTTP/RequestTest.php
remove commented require_once and var_dump
**Checklist:**
> remove commented require_once and var_dump

- system/Log/Logger.php
- tests/system/Log/FileHandlerTest.php
- tests/system/Log/LoggerTest.php
Fixes issue #2743 
Revise ``CodeIgniter\Log\Logger::determineFile()`` to produce the expected output.
This change required a unit test change.
> Logger {file} {line} fix

- system/CodeIgniter.php
in "production" environment:
**Before**
**After**
**Checklist:**
> Don't show message 404 error, eg: Controller or its method not found in "production" environment and ! is_cli()

- user_guide_src/source/outgoing/view_parser.rst
Hi, I'm currently reading through the docs and wonder if some minor fixes would be appreciated? 
If so, I will sign this commit to make it mergeable.
**Checklist:**
> Fixes code example in documentation for view parser

- user_guide_src/source/incoming/controllers.rst
`_remap` must return 
**Checklist:**
> [ci skip] _remap method must have return

- system/Database/Query.php
- tests/system/Database/BaseQueryTest.php
> Fix ? bind with := bind

- user_guide_src/source/outgoing/views.rst
- user_guide_src/source/tutorial/conclusion.rst
- user_guide_src/source/tutorial/create_news_items.rst
- user_guide_src/source/tutorial/index.rst
- user_guide_src/source/tutorial/news_section.rst
- user_guide_src/source/tutorial/static_pages.rst
- Reference the view() function (for rendering templates) as a function instead of method.
- Removed unused code (that got copied from CI3)
- Added references to other part of the userguide
- Code examples are up to CI4 coding standards
- Using esc() to prevent XSS, and give hints about it.
- Use view() method consistent in the tutorial. First pages had showme, and later on used view() for News. Give user a warning about the different view() method and function.
- Improved rendering on some elements
- Always reference a method by index() and not index. 
**Checklist:**
> Update on "Build Your First Application"

- tests/system/Config/ServicesTest.php
Test for `CodeIgniter\Config\Services::email()`. Make `CodeIgniter\Config\Services` class 100% tested.
**Checklist:**
> test for CodeIgniter\Config\Services::email()

- tests/system/HTTP/IncomingRequestTest.php
With this, `CodeIgniter\HTTP\IncomingRequest` should have 100% test coverage.
**Checklist:**
> test for IncomingRequest::getFileMultiple()

- tests/_support/View/SampleClassWithInitController.php
- tests/system/View/CellTest.php
By this, `CodeIgniter\View\Cell` will have 100% test coverage.
**Checklist:**
> test for View\Cell::render() with class has initController() method

- tests/system/CLI/CLITest.php
By this, `CodeIgniter\CLI\CLI` will have 100% test coverage.
**Checklist:**
> test CLI\CLI::strlen(null)

- tests/system/I18n/TimeTest.php
By this, `CodeIgniter\I18n\Time` will have 100% test coverage.
**Checklist:**
> test for I18n\Time::toFormattedDateString

- system/CodeIgniter.php
- system/Commands/Server/Serve.php
- system/Common.php
- system/ComposerScripts.php
- system/Debug/Exceptions.php
as never hit in tests.
**Checklist:**
> ignore coverage on exit and die

- system/HTTP/URI.php
- tests/system/HTTP/URITest.php
fix. #2822. path is empty and '', URI can't normal work
**Checklist:**
> fix. URI path is empty

- user_guide_src/source/cli/cli_library.rst
- user_guide_src/source/database/query_builder.rst
- user_guide_src/source/database/results.rst
- user_guide_src/source/extending/basecontroller.rst
- user_guide_src/source/extending/core_classes.rst
- user_guide_src/source/helpers/text_helper.rst
- user_guide_src/source/libraries/sessions.rst
- user_guide_src/source/libraries/uploaded_files.rst
- user_guide_src/source/outgoing/response.rst
- user_guide_src/source/outgoing/table.rst
- user_guide_src/source/testing/controllers.rst
- user_guide_src/source/testing/overview.rst
I made some minor improvements while reading the documentation.
There are two commits: One with what I think are more obvious improvements and one commit with what might be a bit opinionated.
**Checklist:**
> Documentation fixes

- tests/system/CommonFunctionsTest.php
More tests on Common functions to tests the following functions:
- model();
- trace();
**Checklist:**
> more tests for Common functions

- system/Filters/Filters.php
- tests/system/Filters/FiltersTest.php
- tests/system/Filters/fixtures/Multiple1.php
- tests/system/Filters/fixtures/Multiple2.php
> fix. filters alias multiple

- user_guide_src/source/installation/installing_composer.rst
`codeigniter4/translations` have stable version
> [ci skip] update translations version

- tests/system/View/ViewTest.php
test for `View::renderString()` when tempData still null. By this, `CodeIgniter\ViewView` class will have 100% test coverage.
**Checklist:**
> more test for View::renderString() for null tempData

- system/HTTP/Negotiate.php
- tests/system/HTTP/IncomingRequestTest.php
- tests/system/HTTP/NegotiateTest.php
Fixes #2774 by implementing a match for locales against the broad locale group.
> Better locale matching against broad groups. Fixes #2774

- system/Helpers/url_helper.php
- user_guide_src/source/tutorial/create_news_items.rst
We are referring to an incorrect default values of url_title, so force it to be as described in the user guide.
https://forum.codeigniter.com/thread-76192.html
I also removed some leftover code from CodeIgniter 3.
**Checklist:**
> Build Your First Application used url_title incorrectly

- user_guide_src/source/outgoing/localization.rst
Fixed lang() example in user guide
> Fixed lang() example in user guide

- user_guide_src/source/libraries/pagination.rst
Updated documentation on the Pagination library adding information about the new features added to the library in PR #2899.
**Checklist:**
> Added information about the new features of the Pagination library

- user_guide_src/README.rst
This is just PR #2896 reopened.
Update user guide's README to include instructions for using Python Launcher for Windows.
**Checklist:**
> [ci skip] Add usage for Windows using Python Launcher

- system/RESTful/ResourceController.php
- system/RESTful/ResourcePresenter.php
Use shortcut to create model, also by using `model()` function, uses shared instance.
**Checklist:**
> make model object via model() function in restful controllers

- user_guide_src/source/dbmgmt/migration.rst
use `latest` replace `progess`
> [ci skip] the method is not exists

- system/Language/Language.php
- tests/_support/Language/en/Foo.php
- tests/system/Language/LanguageTest.php
By move the logic to get translation output to separate method.
**Checklist:**
> Ensure get translation output logic work on selected locale, dashed locale, and fallback "en"

- system/Commands/Utilities/Routes.php
- system/Debug/Toolbar/Collectors/Routes.php
- system/Format/JSONFormatter.php
- system/Log/Handlers/ChromeLoggerHandler.php
- system/Pager/PagerRenderer.php
- tests/system/Database/Live/EscapeTest.php
- tests/system/HTTP/Files/FileCollectionTest.php
- tests/system/Helpers/InflectorHelperTest.php
- tests/system/Pager/PagerRendererTest.php
- tests/system/View/ParserFilterTest.php
Currently, the cs-fix only run on `pre-commit` with the diff only fix. The old changes still remain. I run the phpcbf to `system` and `tests` directory: 
```
vendor/bin/phpcbf --standard=./vendor/codeigniter4/codeigniter4-standard/CodeIgniter4 --encoding=utf-8 system tests
```
**Checklist:**
> Running phpcbf to system and tests

- app/Config/Autoload.php
- system/bootstrap.php
This should fix the issue reported by @kloukas  https://github.com/codeigniter4/CodeIgniter4/pull/2976#issuecomment-626948222
**Checklist:**
> ensure load "SYSTEMPATH . Config/Services.php" in system/bootstrap.php

- system/Database/BaseResult.php
> Fix variable name

- system/Language/en/Core.php
- system/Language/en/Entity.php
- system/Language/en/HTTP.php
Typographic fixes in the language files.
**Checklist:**
> Typographic fixes

- app/Config/Boot/development.php
- app/Config/Boot/production.php
- app/Config/Boot/testing.php
Fixes #2975 
**Checklist:**
-  [x] Conforms to style guide
> Fix type of CI_DEBUG

- system/CLI/CLI.php
Remove dark_blue it uses light_blue color effect
correct light_yellow and yellow colors
> Fix CLI output colors

- app/Config/Autoload.php
- system/Config/AutoloadConfig.php
Simplify app\Config\Autoload file
marked framework psr4 and classmap proprieties  as protected and merged app ones to with them for security reasons
> Autoload improvement 

- system/Test/FeatureResponse.php
How about using the interface as a constructor parameter
> Fix FeatureResponse constructor parameter

- app/Config/Routes.php
> Fixed grammer in comment

- composer.json
- system/Cache/Handlers/DummyHandler.php
- system/Cache/Handlers/FileHandler.php
- system/Cache/Handlers/MemcachedHandler.php
- system/Cache/Handlers/PredisHandler.php
- system/Cache/Handlers/RedisHandler.php
- system/Cache/Handlers/WincacheHandler.php
- tests/system/Cache/Handlers/PredisHandlerTest.php
- user_guide_src/source/libraries/caching.rst
- add PredisHandlerTest
- add PredisHandler userguide
- add Predis composer-dev config
- fix. PredisHandler `clean`, `getMetaData` return type.
- fix. `clean`,`delete` doc return type, in userguide, type is bool.
**Checklist:**
> perfect Cache PredisHandler

- user_guide_src/source/helpers/url_helper.rst
> Fix info about return value for uri_string() function

- user_guide_src/source/general/common_functions.rst
> Fix info about return value for route_to() function

- system/Test/FeatureTestTrait.php
- tests/system/Test/FeatureTestCaseTest.php
This might be a long shot at #3063 but I can't run feature tests locally so I'm giving it a try here.
**Checklist:**
> Clean buffers after feature test

- system/HTTP/UserAgent.php
- tests/system/HTTP/UserAgentTest.php
> Fix default type of UserAgent::$agent

- .travis.yml
- system/Images/Handlers/ImageMagickHandler.php
- tests/system/Images/ImageMagickHandlerTest.php
This PR adds tests for the ImageMagick image handler.
In addition, I had to make some small changes to make some functions of this handler to actually work.
**Checklist:**
> ImageMagick class updates and tests

- user_guide_src/source/incoming/incomingrequest.rst
There was no closing parenthesis on #579 in `user_guide_src/source/incoming/incomingrequest.rst:243`. I've added the missing ) to the line.
> fixed missing ) after statement [ci skip]

- .github/workflows/userguide_ci.yml
When a change in any files within `user_guide_src` are changed, will build the user guide and display any errors within the pull requests. 
See: https://github.com/ammaraskar/sphinx-action
> Check sphinx warnings when user guide source is changed.

- .github/workflows/docs_nightly.yml
Fixes syntax error on run.
**Checklist:**
> Fix syntax error of docs_nightly.yml

- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/libraries/caching.rst
- user_guide_src/source/libraries/uri.rst
- user_guide_src/source/testing/fabricator.rst
Fixes warnings as shown in running UserGuide CI.
**Checklist:**
> Fix sphinx warnings emitted by User Guide CI

- user_guide_src/source/outgoing/response.rst
Quick fix it an incorrect reference in the UG
> UG forced download error

- .github/workflows/docs_nightly.yml
Related to #3130 . 
**Checklist:**
> More fixes to docs nightly

- app/Config/Modules.php
- system/Modules/Modules.php
- system/Test/bootstrap.php
- system/bootstrap.php
Creating new system/Modules/Modules.php file and moves shouldDiscover function into it away from user hand like before app/Config/Modules.php
to help avoid tampering with the core functions
> Move shouldDiscover in a new system/Modules class

- system/CodeIgniter.php
https://github.com/codeigniter4/CodeIgniter4/issues/3138#issue-642431631
> Define environment variables

- system/Model.php
Fix testMode() for batch methods in Model.
Ref: #3158
**Checklist:**
> Fix testMode() for batch methods in Model

- system/Files/File.php
The permissions of the new file should be modified, not the old file
> The permissions of the new file should be modified, not the old file

- tests/system/Database/Live/FabricatorLiveTest.php
Make the test more stable, to avoid random failures.
**Checklist:**
> Update for FabricatorLiveTest

- system/Test/CIUnitTestCase.php
- user_guide_src/source/testing/overview.rst
* Adds methods for mocking intrusive services (Email, Session)
* Defines new properties for set up / tear down method callbacks
* Implements new properties for these new services
* Updates User Guide with docs on staging
**Checklist:**
> Test Case Mocking

- app/Views/errors/html/debug.css
Added just a overflow-x: scroll to mimic the expected result reported in the issue #3199
> Fixed #3199

- tests/system/Autoloader/FileLocatorTest.php
Added more tests on `Autoloader\FileLocator`. Added tests for `locateFile()` on not found file on existing namespace and `listNamespace()` with empty prefix and path. 
By this, the `Autoloader\FileLocator` will have 100% test coverage.
**Checklist:**
> more tests on Autoloader\FileLocator

- user_guide_src/source/outgoing/view_parser.rst
There was an issue with the boldfacing of two words.
> Fix formatting issue in userguide/outgoing/view_parser

- system/Cache/CacheFactory.php
- system/Cache/CacheInterface.php
- system/Cache/Exceptions/CacheException.php
- system/Cache/Exceptions/ExceptionInterface.php
- system/Cache/Handlers/DummyHandler.php
- system/Cache/Handlers/FileHandler.php
- system/Cache/Handlers/MemcachedHandler.php
- system/Cache/Handlers/PredisHandler.php
- system/Cache/Handlers/RedisHandler.php
- system/Cache/Handlers/WincacheHandler.php
Update PHPDocs of Cache library and fix its compilation errors
**Checklist:**
> Update phpdocs of Cache library

- tests/system/HTTP/URITest.php
This PR adds more checks to better illustrate the current behavior of `getSegment()` method in the URI class.
Related to: #3212
**Checklist:**
> Add more URI class tests to fully illustrate current behavior

- system/CLI/CommandRunner.php
- system/Test/FeatureTestTrait.php
> cs : remove unused import use statements and sort use statements

- system/Throttle/Throttler.php
Code style fixes for Throttler class.
Ref: #2873
**Checklist:**
> Throttler code style update

- system/Session/Session.php
> cs fix in Session class

- system/HTTP/IncomingRequest.php
- tests/system/HTTP/IncomingRequestTest.php
This PR makes changes to check server headers via Request class.
See: #3246
**Checklist:**
> Check server headers via Request class

- system/Cache/Handlers/RedisHandler.php
> typo fix s/Memcached/Redis in RedisHandler cache

- system/Session/Session.php
> optimize Session : use foreach instead of for with count when possible

- spark
- system/Database/BaseBuilder.php
> using strpos instead of substr when possible

- system/I18n/Exceptions/I18nException.php
- system/I18n/Time.php
- system/I18n/TimeDifference.php
Fix PHPDoc compilation errors for I18n
**Checklist:**
> Fix PHPDocs for I18n

- system/Filters/CSRF.php
- system/Filters/Exceptions/FilterException.php
- system/Filters/Filters.php
- system/Filters/Honeypot.php
Fix PHPDoc compilation errors for Filters lib.
**Checklist:**
> Fix PHPDocs for Filters

- system/I18n/Time.php
> add break; in foreach at Time::getDst() when daylightSaving set

- env
Add Honeypot::$container to `env` file
**Checklist:**
> Add Honeypot::$container to env file

- system/HTTP/DownloadResponse.php
> Fix protocol version for DownloadResponse

- user_guide_src/source/changelogs/v4.0.4.rst
> Changelog update

- system/Helpers/text_helper.php
> optimize excerpt text helper : no need strtolower on strpos, replace with stripos

- user_guide_src/source/models/entities.rst
Fixed an error in the code of Array/Json Casting that prevent the example to execute
**Checklist:**
**Notes**
> Fixed an error in the code of Array/Json Casting

- system/Test/Filters/CITestStreamFilter.php
> Update PHPDocs of CITestStreamFilter

- system/HTTP/CLIRequest.php
- tests/system/HTTP/CLIRequestTest.php
> New method: CLIRequest::isCLI

- user_guide_src/source/incoming/routing.rst
Added an example describing multi-segment routes since this may be good to know.
**Checklist:**
> Added routes example with multiple segments to docs

- user_guide_src/source/general/modules.rst
Change **application** to **app** to keep directory name consistency
> Keep app directory name consistency

- tests/system/Config/ServicesTest.php
Test unshared email service with check empty and non empty config passed. By this, `Config\Services` class will have 100% test coverage.
**Checklist:**
> add more tests for Config\Services::email()

- system/Router/Router.php
> optimize Router::checkRoutes() : remove unneded uri check when routes is empty

- system/Model.php
use truthy check is enough
**Checklist:**
> optimize Model::doProtectFields(): remove unneded count($data)

- system/Helpers/array_helper.php
as `$array` already type hinted in parameter.
**Checklist:**
> optimize array helper: remove unneded is_array($array) check

- system/Router/RouteCollection.php
> Fix docblock of RouteCollection::group()

- system/Images/Handlers/GDHandler.php
> Fix for aligning text in center middle

- user_guide_src/source/changelogs/v4.0.4.rst
Something strange happened and we lost the changelog for v4.0.4.
**Checklist:**
> Restore changelog for 4.0.4

- system/HTTP/Request.php
> optimize Request::getIPAddress() : use foreach instead of for with count()

- system/CLI/Commands.php
- system/Language/en/CLI.php
- tests/system/Commands/CommandsTest.php
This is included in the **`4.1 Roadmap`**.
To be honest, I sought inspiration for the code here from Symfony Console and further trimmed it down based on my understanding of the code and our framework design. So far, manual tests don't fail my expectations and local unit tests turned green. I'm open for improvements. 😁
Requesting review from @lonnieezell .
**Checklist:**
> New feature: Spark command suggestion list

- system/Router/Router.php
This PR fixes `$localeSegment` reset. Resetting wasn't triggered every time and it was causing problems.
See: #3386
**Checklist:**
> Fix localeSegment reset

- CONTRIBUTING.md
Update links to github.com in the CONTRIBUTING.md.
- Update the link to git push doc to the latest url where current url is redirected to.
- Change the link to pull request doc, where current url is broken, to the url describing how to create a pull request from a folk.
**Checklist:**
> Update links to github.com in the CONTRIBUTING.md.

- system/Router/RouteCollection.php
As can be combined in single if.
**Checklist:**
> optimize RouteCollection::create() : reduce repetitive call is_string($to)

- system/Commands/Encryption/GenerateKey.php
- tests/system/Commands/GenerateKeyTest.php
Added new command for encryption key generation to `.env` file.
**Checklist:**
> Command "key:generate"

- system/View/View.php
Use the `??` operator where possible, and change double negative conditionals to a positive.
**Checklist:**
> View renderer optimization

- system/CodeIgniter.php
- Add `\Config\App` type hint in constructor config parameter
- add `|null` to docblock to parameter function that allow null
- add `Cache` parameter to cache parameter in `gatherOutput()` and `handleRequest()` function
- remove unnecessary `$routes instanceof RouteCollectionInterface` check in `tryToRouteIt()` function as already has `RouteCollectionInterface` type hinted parameter. Null check is enough.
- apply unset `$override` variable after close if in `display404errors()` function.
**Checklist:**
> some optimization of CodeIgniter class

- system/CLI/BaseCommand.php
- system/CLI/CommandRunner.php
- system/CLI/Commands.php
- system/CLI/Console.php
- system/Commands/ListCommands.php
- tests/system/CLI/ConsoleTest.php
Remove unless before/after newLine()
Fix Windows cmd colors
Remove useless methods
Here's some examples:
https://i.ibb.co/r3JnQPs/Annotation-2020-07-31-210349.png
https://i.ibb.co/SnwwdJV/Annotation-2020-07-31-213208.png
> CLI Print Pretty

- system/HTTP/Response.php
- tests/system/HTTP/ResponseCookieTest.php
> Fix deleteCookie() when prefix is defined

- system/Model.php
- tests/system/Database/Live/ModelTest.php
> Add support for Entities to insertBatch() method

- app/Config/Mimes.php
PHP bug: https://bugs.php.net/bug.php?id=79045
See: #3439
**Checklist:**
> Add image/svg mime type

- user_guide_src/requirements.txt
- user_guide_src/source/_templates/layout.html
This PR fixes search functionality in the user guide and updates some dependencies to the latest versions.
See: #3458
**Checklist:**
> Fix user guide search functionality

- app/Config/Events.php
Set constant CI_DEBUG into TRUE must be enable debug toolbar
We can define in file https://github.com/codeigniter4/CodeIgniter4/blob/develop/app/Config/Boot/production.php
> Turn on toolbar if CI_DEBUG equals true

- system/Autoloader/FileLocator.php
- system/bootstrap.php
- tests/system/Autoloader/FileLocatorTest.php
Make `system/bootstrap.php` namespaced so no need to make `FileLocator::legacyLocate()` locate system directory.
**Checklist:**
> apply FileLocator::legacyLocate() autoloader to only locate app directory

- public/index.php
> ensure to use realpath() when require bootstrap.php file in index.php

- system/Helpers/url_helper.php
- tests/system/Helpers/URLHelperTest.php
- user_guide_src/source/changelogs/v4.0.5.rst
- user_guide_src/source/helpers/url_helper.rst
New helper method, `url_is()` to compare the current URL with one of your choice. With (*) wildcard.
> New helper: url_is

- .github/workflows/static-analysis-check.yml
- composer.json
- phpstan.neon
- qa-bootstrap.php
- system/API/ResponseTrait.php
- system/CodeIgniter.php
- system/Config/DotEnv.php
- system/Config/Services.php
- system/Database/BaseUtils.php
- system/Database/MigrationRunner.php
- system/Database/MySQLi/Result.php
- system/Files/File.php
- system/HTTP/URI.php
- system/Helpers/form_helper.php
- system/I18n/Time.php
- system/Session/Handlers/FileHandler.php
- system/Test/Mock/MockEvents.php
- system/Test/Mock/MockResourcePresenter.php
- system/Test/Mock/MockResult.php
- system/Test/Mock/MockTable.php
- system/View/Table.php
apply code static analysis check with phpstan. start with level 0.
**Checklist:**
> apply code static analysis check with phpstan

- system/HTTP/Files/UploadedFile.php
> Fix setPath method in UploadedFile class

- system/Model.php
- tests/system/Database/Live/ModelTest.php
> Fix handling returnSQL parameter in Model::replace()

- app/Config/UserAgents.php
> Add Edge browser to UserAgents

- public/index.php
- spark
> ensure add realpath() in spark

- system/Database/BaseBuilder.php
- system/Database/Postgre/Builder.php
- system/HTTP/Request.php
- system/Helpers/text_helper.php
- system/Model.php
- system/Router/RouteCollection.php
- system/Test/FeatureResponse.php
Clean up unnecessary cast when already type hinted.
**Checklist:**
> clean up: remove unnecessary casting

- system/HTTP/IncomingRequest.php
The intl extension check loaded, for non-composer usage, already handled at https://github.com/codeigniter4/CodeIgniter4/blob/21b635c7737b806693255abc734f99e1a48653ee/system/CodeIgniter.php#L226-L249
For composer usage, already handled on composer create-project/install process.
**Checklist:**
> clean up: remove unneeded class_exists(Locale, false) in IncomingRequest

- user_guide_src/source/models/entities.rst
Adds a brief note of the array conversion methods.
Fixes #2317
> User Guide: Entity toArray

- public/index.php
- spark
- system/Commands/Server/Serve.php
- system/Commands/Server/rewrite.php
Some optimizations:
- replace function calls to equivalent constants to prevent overriding of those functions
- using `version_compare` to handle comparison of pre-release versions
```
var_dump('7.2-rc.1' < '7.2'); // false
var_dump(version_compare('7.2-rc.1', '7.2', '<')); // true
```
- Using unary `++` instead of `+= 1`
- and others
**Checklist:**
> Index.php optimization

- .github/workflows/static-analysis-check.yml
- phpstan.neon
- system/Autoloader/Autoloader.php
- system/Cache/Handlers/MemcachedHandler.php
- system/CodeIgniter.php
- system/Commands/Generators/CreateScaffold.php
- system/Common.php
- system/Database/Config.php
- system/Database/Database.php
- system/Database/Postgre/PreparedQuery.php
- system/Debug/Exceptions.php
- system/Email/Email.php
- system/HTTP/CURLRequest.php
- system/HTTP/DownloadResponse.php
- system/Helpers/text_helper.php
- system/I18n/Time.php
- system/Log/Handlers/FileHandler.php
- system/Pager/PagerRenderer.php
- system/Session/Handlers/BaseHandler.php
- system/Session/Handlers/FileHandler.php
- system/Session/Handlers/RedisHandler.php
- system/Session/Session.php
- system/Test/CIUnitTestCase.php
- system/Test/bootstrap.php
- system/View/Filters.php
Fixes the following things:
- incorrect set error_reporting via ini_set, should be via `error_reporting` function
- ensure ini_set values to be string
- fix 4th parameter value to be 0 for preg_match instead of null
- ensure to use correct type in function values
- fix incorrect 2nd passed parameter of `lang()` function to be array.
**Checklist:**
> Apply phpstan level 5

- qa-bootstrap.php
- system/Test/bootstrap.php
- system/bootstrap.php
- `realpath` on string paths with trailing whitespace will return `false`
- resolve phpstan errors on bootstrap
- change Docblocks to comments
**Checklist:**
> Optimize bootstrap files

- system/Common.php
- system/Router/RouteCollection.php
Update PHPDoc param from array to mixed
**Checklist:**
> Update PHPDoc param from array to mixed

- system/Model.php
- tests/system/Database/Live/ModelTest.php
Continuing on #3466 and closes #3466 .
**Checklist:**
> Add setAllowedFields method to Model

- system/Format/XMLFormatter.php
- tests/system/Format/XMLFormatterTest.php
> Add XML tags normaliser

- system/CodeIgniter.php
There is `EXIT_ERROR` constant that can be used.
**Checklist:**
> using EXIT_ERROR constant in CodeIgniter::bootstrapEnvironment()

- app/Config/Generators.php
- system/CLI/GeneratorCommand.php
- system/Commands/Generators/CreateCommand.php
- system/Commands/Generators/CreateController.php
- system/Commands/Generators/CreateEntity.php
- system/Commands/Generators/CreateFilter.php
- system/Commands/Generators/CreateMigration.php
- system/Commands/Generators/CreateModel.php
- system/Commands/Generators/CreateScaffold.php
- system/Commands/Generators/CreateSeeder.php
- system/Commands/Generators/CreateSessionMigration.php
- system/Commands/Generators/MigrateCreate.php
- system/Commands/Generators/Views/migration.tpl.php
- system/Commands/Generators/Views/seed.tpl.php
- system/Commands/Generators/Views/session_migration.tpl.php
- tests/system/Commands/CreateMigrationTest.php
- user_guide_src/source/changelogs/v4.0.5.rst
- user_guide_src/source/cli/cli_generators.rst
- user_guide_src/source/dbmgmt/migration.rst
Use view stubs for the templates required by generator commands for future maintainability.
**Checklist:**
> Use view files for generator commands

- system/HTTP/Request.php
> Cast null value to string

- user_guide_src/source/cli/cli_library.rst
> [CI SKIP] Typo CLI Library userguide

- system/HTTP/URI.php
> using new self in URI::resolveRelativeURI()

- system/Database/ModelFactory.php
Comments appear to be copy-pasted and are wrong.
**Checklist:**
> Fix ModelFactory Comments

- user_guide_src/source/database/configuration.rst
User guide syntax fixes.
**Checklist:**
> Fix some user guide syntax mistakes

- README.md
It seems the note no longer relevant for now.
**Checklist:**
> Remove "awkward" note from readme

- user_guide_src/source/tutorial/static_pages.rst
Corrected date 2019 to new date 2020.
**Checklist:**
- [ x] Securely signed commits
> Updated static_pages.rst [ci skip]

- user_guide_src/source/outgoing/response.rst
- user_guide_src/source/outgoing/view_parser.rst
- user_guide_src/source/outgoing/view_renderer.rst
Removed \ not nedded this is a common helper method.
**Checklist:**
- [ x] Securely signed commits
> Update view_renderer.rst [ci skip]

- user_guide_src/source/intro/index.rst
> Update intro/index.rst [ci skip]

- user_guide_src/source/outgoing/view_cells.rst
Fixes #3668 .
~Along the way, I found a teeny error in `intro/index` so I fixed that too.~
**Checklist:**
> Update view cell doc [ci skip]

- user_guide_src/source/incoming/restful.rst
- user_guide_src/source/models/entities.rst
1. entities.rst  Array/Json
casting The following describes the forced type conversion when setting
2. restful.rst Presenter 
delete action error
**Checklist:**
> [CI SKIP] Update Userguide errror

- system/Helpers/array_helper.php
- tests/system/Helpers/ArrayHelperTest.php
- user_guide_src/source/helpers/array_helper.rst
Supersedes #3684 with updated provider tests.
**Checklist:**
> New Array Helper Function

- rector.php
- system/CLI/GeneratorCommand.php
- system/Commands/Generators/CreateCommand.php
- system/Commands/Generators/CreateController.php
- system/Common.php
- system/Format/XMLFormatter.php
Check to remove unneded variable assignment on return via rector.
**Checklist:**
> apply rector: SimplifyUselessVariableRector

- rector.php
- system/CodeIgniter.php
- system/Database/BaseConnection.php
- system/Debug/Exceptions.php
- system/Email/Email.php
- system/HTTP/Header.php
- system/Helpers/filesystem_helper.php
- system/View/Parser.php
Use rector to detect no need else when there is already return, continue, throw early.
**Checklist:**
> apply rector: RemoveAlwaysElseRector

- .github/workflows/test-phpunit.yml
cool new version is out ;)
**Checklist:**
> DX: Use upstream php-coveralls in Actions

- .github/workflows/test-phpunit.yml
> Run phpunit tests on changed PHP files only

- user_guide_src/source/incoming/controllers.rst
Updated the controllers to use the BaseController and added references to the original controller.
**Checklist:**
- [ x] Securely signed commits
> Update controllers.rst [ci skip]

- user_guide_src/source/testing/fabricator.rst
> Fix User Guide table reference

- user_guide_src/source/incoming/controllers.rst
Related to #3678 
**Checklist:**
> Remove erroneous FQCN of BaseController

- system/Database/Seeder.php
- system/Test/CIDatabaseTestCase.php
Make `Faker` available to seeders through `Seeder::$faker` property. Since faker is only available as a dev dependency, I made it conditionally available and set to `null` if not installed.
**Checklist:**
> Make Faker available on Seeder

- system/Commands/Database/Migrate.php
- system/Commands/Database/MigrateRefresh.php
- system/Commands/Database/MigrateRollback.php
- system/Commands/Database/MigrateStatus.php
- system/Commands/Database/Seed.php
- system/Database/MigrationRunner.php
- system/Database/Seeder.php
- tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
- tests/_support/Database/Seeds/AnotherSeeder.php
- tests/_support/Database/Seeds/CITestSeeder.php
- tests/system/Commands/DatabaseCommandsTest.php
> Add tests for database commands

- system/Commands/Database/CreateDatabase.php
- system/Database/Config.php
- system/Database/Forge.php
- tests/system/Commands/CreateDatabaseTest.php
Supersedes and closes #3695 . 
Added special handling for SQLite3 connections.
**Checklist:**
> Create database command

- system/Database/Forge.php
- system/View/View.php
- tests/system/View/ViewTest.php
- tests/system/View/Views/Nested/simple.php
> Fix view caching with directory separators

- system/CLI/CLI.php
> Enclose CLI::generateDimensions in a try-catch

- .github/workflows/test-rector.yml
- rector.php
The cache feature in latest rector 0.8.28 https://github.com/rectorphp/rector/releases/tag/0.8.28
**Checklist:**
> apply Option::ENABLE_CACHE to rector config

- composer.json
auto sort package for install new package
**Checklist:**
> composer auto sort package

- system/CodeIgniter.php
- system/Database/Query.php
- system/Entity.php
- system/HTTP/CURLRequest.php
- system/HTTP/Header.php
- system/HTTP/URI.php
- system/Helpers/number_helper.php
- system/Router/RouteCollection.php
- system/Test/DOMParser.php
- system/View/Parser.php
> Use elseif instead of else if

- system/Config/Services.php
Due new PHPStan release https://github.com/phpstan/phpstan/releases/tag/0.12.52
**Checklist:**
> Fixes PHPStan error notice at latest develop

- user_guide_src/source/installation/installing_composer.rst
> Fix tests folder not in framework

- system/CodeIgniter.php
- system/Database/MySQLi/Connection.php
- system/Database/Sqlsrv/PreparedQuery.php
- system/Format/XMLFormatter.php
- system/HTTP/Response.php
- system/HTTP/ResponseInterface.php
- system/I18n/Time.php
- system/Images/Handlers/ImageMagickHandler.php
- system/Test/ControllerTester.php
Import PHP's native classes to global namespace.
**Checklist:**
> Import native classes

- system/RESTful/ResourcePresenter.php
> Fix doc return type

- system/Database/Sqlsrv/Connection.php
> Proper use INFORMATION_SCHEMA.COLUMNS

- composer.json
fzaninotto has archived his project and asked others to continue it on fork. The solution seems to be `FakerPHP/Faker`, which this PR implements.
See: https://github.com/fzaninotto/Faker/pull/2063
**Checklist:**
> Switch to FakerPHP

- admin/framework/composer.json
- admin/module/composer.json
- admin/starter/composer.json
This is a continuation to #3827 
**Checklist:**
> Use fakerphp/faker on other composer.json

- user_guide_src/source/incoming/filters.rst
> Clarify before filters behavior

- system/Email/Email.php
> Remove useless elseif, else

- system/View/Parser.php
- tests/system/View/ParserTest.php
Fixes #3824 and alternative to #3846 
**Checklist:**
> Parser: Escape hashes in main pattern

- system/Database/Forge.php
> Fix latest phpstan error on Forge

- phpstan.neon.dist
- system/Helpers/url_helper.php
- system/Router/Exceptions/RouterException.php
- utils/PHPStan/CheckFrameworkExceptionInstantiationViaNamedConstructorRule.php
- utils/PHPStan/CheckFrameworkExceptionInstantiationViaStaticCallRule.php
Ref https://github.com/codeigniter4/CodeIgniter4/pull/3866/files#r519355043 /cc @paulbalandan 
**Checklist:**
> [PHPStan] Add PHPStan rule to check FrameworkException Instantiation Via Static Call

- system/RESTful/BaseResource.php
- system/RESTful/ResourceController.php
- system/RESTful/ResourcePresenter.php
ResourceController and ResourcePresenter classes extends BaseResouce class
> RESTful Base class

- rector.php
Set rector config `Option::PHP_VERSION_FEATURES` to 7.2
**Checklist:**
> Apply Rector Option::PHP_VERSION_FEATURES 7.2

- system/Helpers/cookie_helper.php
Just update PHP doc block
**Checklist:**
> Update PHPdocs at cookie_helper.php

- app/Config/Services.php
- app/Controllers/BaseController.php
- app/Controllers/Home.php
- app/Views/errors/cli/error_404.php
- app/Views/errors/cli/error_exception.php
- app/Views/errors/html/error_exception.php
> Fix whitespaces in app/

- admin/pre-commit
Attempt to Fix #3920
**Checklist:**
> Fix Pre-Commit on windows

- app/Config/ContentSecurityPolicy.php
- system/HTTP/ContentSecurityPolicy.php
- Add missing docblocks.
- Fix phpstan ignored line.
- Fix formatting
- Fix IDE errors
**Checklist:**
> Update Content Security Policy

- system/Email/Email.php
This only does the fixing of code style within the Email class to make it less stuffy to read and not the big refactor as originally envisioned.
**Checklist:**
> Fix CS for Email

- user_guide_src/source/tutorial/create_news_items.rst
Adjustment of coding style.
**Checklist:**
> Fix tutorial create news items code

- admin/framework/composer.json
- admin/module/composer.json
- admin/starter/composer.json
- admin/userguide/composer.json
- composer.json
Avoid open ended PHP version constraints.
**Checklist:**
> Update php version constraints

- user_guide_src/source/testing/feature.rst
- user_guide_src/source/testing/overview.rst
"PHPUnit" is the correct representation.
**Checklist:**
- [n/a] Conforms to style guide
> Fix phpUnit

- user_guide_src/source/testing/feature.rst
Fix testing feature.
**Checklist:**
> Fix testing feature

- spark
- system/Commands/Server/Serve.php
> [re-PR] spark: validate PHP version

- user_guide_src/source/testing/database.rst
Fix typos.
**Checklist:**
- [n/a] Conforms to style guide
> Fix testing database doc

- user_guide_src/source/helpers/test_helper.rst
two spelling mistakes in userguide corrected
> fix another typo

- user_guide_src/source/helpers/text_helper.rst
- user_guide_src/source/installation/running.rst
- user_guide_src/source/libraries/caching.rst
- user_guide_src/source/libraries/images.rst
- user_guide_src/source/libraries/security.rst
fixed some typos and misspellings in userguide
> fixing typos in userguide

- system/Helpers/form_helper.php
- tests/system/Helpers/FormHelperTest.php
- user_guide_src/source/helpers/form_helper.rst
remove extra space in the input field 
**Checklist:**
> remove extra space in the input field

- env
Fix missing .env security config
> Add Security Configs to .env

- user_guide_src/source/testing/feature.rst
Fix feature testing sample code.
**Checklist:**
> docs: fix feature testing sample code

- admin/starter/.gitattributes
Exclude some files when users run `create-project`
**Checklist:**
> ignore files when using composer

- README.md
- admin/framework/README.md
- admin/starter/README.md
> Update spell on readme.

- user_guide_src/source/license.rst
Update License copyright at User Guide
**Checklist:**
> [UG] Update License copyright

- system/Database/Database.php
- system/HTTP/IncomingRequest.php
- system/Images/Handlers/BaseHandler.php
- system/Log/Logger.php
- system/Router/RouteCollection.php
- system/Validation/Rules.php
- system/Validation/Validation.php
Applies PHP 8 changes done to `4.1` back into `develop` now that we want to support 8 in `4.0.5`.
**Checklist:**
> Backfill 4.1

- system/Database/Postgre/Connection.php
See <https://github.com/codeigniter4/CodeIgniter4/pull/4015#issuecomment-749393424>.
**Checklist:**
- [n/a] User guide updated
> fix: postgres column metadata order

- admin/userguide/README.md
Missed the update on #4009 
**Checklist:**
> remove extra comma in readme

- admin/module/tests/README.md
- admin/starter/tests/README.md
- tests/README.md
Update PHPUnit latest version in test
**Checklist:**
> Update PHPUnit version in `tests`.

- app/Controllers/BaseController.php
> Add Params to constructor dockblock

- system/Database/MySQLi/Forge.php
- system/Database/Postgre/Forge.php
- system/Database/SQLSRV/Forge.php
- system/Database/SQLite3/Forge.php
Alias Forge with use operator in all drivers
> Alias Forge with use operator

- user_guide_src/source/installation/installing_composer.rst
Continuation of #3816.
**Checklist:**
> Remove 'tests'

- system/Database/Database.php
Add new method initDriver() to Database\Database:class to initialize database driver
closes #4024
> Add initDriver Method

- LICENSE
- admin/module/tests/_support/Libraries/ConfigReader.php
- admin/starter/tests/_support/Libraries/ConfigReader.php
- user_guide_src/source/conf.py
- user_guide_src/source/license.rst
- user_guide_src/source/tutorial/static_pages.rst
> New Year 2021

- user_guide_src/source/general/logging.rst
There is no `LoggerAwareTrait`.
**Checklist:**
> Remove discussion on LoggerAwareTrait

- system/Database/Query.php
- system/Debug/Toolbar/Collectors/Database.php
Moved Debug Toolbar Collector display method in Query class to allow overriding for custom highlighting in 3rd party DB drivers.
**Checklist:**
> DebugToolbar - Handle Query display in Query class

- user_guide_src/source/incoming/filters.rst
Change sample code of `redirect()` to be more common.
**Checklist:**
> docs: change sample code of redirect() to be more common

- user_guide_src/source/dbmgmt/migration.rst
- user_guide_src/source/installation/installing_composer.rst
- user_guide_src/source/installation/installing_manual.rst
- user_guide_src/source/tutorial/static_pages.rst
Make note as note-block like:
Before:
https://codeigniter4.github.io/CodeIgniter4/installation/installing_composer.html
After:
**Checklist:**
> set note-block for some notes

- user_guide_src/source/changelogs/v4.0.0-alpha.3.rst
- user_guide_src/source/changelogs/v4.0.0-alpha.4.rst
- user_guide_src/source/changelogs/v4.0.0-alpha.5.rst
- user_guide_src/source/changelogs/v4.0.0-beta.1.rst
- user_guide_src/source/changelogs/v4.0.0-beta.2.rst
- user_guide_src/source/changelogs/v4.0.0-beta.3.rst
- user_guide_src/source/changelogs/v4.0.0-beta.4.rst
- user_guide_src/source/changelogs/v4.0.0-rc.1.rst
- user_guide_src/source/changelogs/v4.0.0-rc.2.rst
- user_guide_src/source/changelogs/v4.0.0-rc.3.rst
- user_guide_src/source/database/call_function.rst
- user_guide_src/source/database/configuration.rst
- user_guide_src/source/database/connecting.rst
- user_guide_src/source/database/examples.rst
- user_guide_src/source/database/helpers.rst
- user_guide_src/source/database/metadata.rst
- user_guide_src/source/database/queries.rst
- user_guide_src/source/database/query_builder.rst
- user_guide_src/source/database/results.rst
- user_guide_src/source/database/transactions.rst
- user_guide_src/source/index.rst
- convert indentation tabs to spaces
- update code-block
- update sample
**Checklist:**
> convert indentation from tabs to spaces & update code-block [changelogs, database]

- env
Add `logger.threshold` in env as comment.
Every time I install CI4, I change the value for development.
**Checklist:**
> config: add logger.threshold in env as comment

- system/View/Table.php
> Fix misplaced closing tbody

- composer.json
Reverts codeigniter4/CodeIgniter4#4170
> Revert "Update phpstan/phpstan requirement from 0.12.69 to 0.12.70"

- system/View/View.php
> Wrap extract calls in IIFEs in View

- system/Database/BaseBuilder.php
- tests/system/Database/Builder/DeleteTest.php
> fix: BaseBuilder::getCompiledDelete() runs real query

- tests/system/HTTP/IncomingRequestTest.php
Fixes typo in test.
**Checklist:**
> Fix typo in IncomingRequestTest

- system/HTTP/Files/UploadedFile.php
> fix: UploadedFile::store() return type inconsistancy

- system/Common.php
- user_guide_src/source/general/common_functions.rst
- change confusing param name
- add `use` for PHPDoc
**Checklist:**
> Minor fixes in Common.php

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.1.0.rst
- user_guide_src/source/changelogs/v4.1.1.rst
- user_guide_src/source/conf.py
Updates changelog and version references for `4.1.0`.
**Checklist:**
> Prep for 4.1.0 release

- admin/framework/.gitattributes
> Delete .gitattributes in framework.

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.1.1.rst
- user_guide_src/source/changelogs/v4.1.2.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_410.rst
- user_guide_src/source/installation/upgrading.rst
Updates changelog and version references for hotfix `4.1.1`.
**Checklist:**
> Prep for 4.1.1 release

- rector.php
- system/Database/Forge.php
- system/Email/Email.php
- system/Helpers/url_helper.php
- system/Typography/Typography.php
Apply `ForToForeachRector` rector rule to use foreach instead of for when possible.
**Checklist:**
> [Rector] Apply Rector: ForToForeachRector

- rector.php
- system/Validation/Validation.php
Reduce nested if inside foreach by continue early with `ChangeNestedForeachIfsToEarlyContinueRector` rule.
**Checklist:**
> [Rector] Apply Rector: ChangeNestedForeachIfsToEarlyContinueRector

- rector.php
- system/Model.php
Change if/else value to early return with `ChangeIfElseValueAssignToEarlyReturnRector` rector rule.
**Checklist:**
> [Rector] Apply Rector: ChangeIfElseValueAssignToEarlyReturnRector

- rector.php
- system/Commands/ListCommands.php
- system/Validation/Validation.php
Make use of array_key_first() and array_key_last() with `ArrayKeyFirstLastRector` rector rule.
**Checklist:**
> [Rector] Apply Rector: ArrayKeyFirstLastRector

- spark
> Fix minPHPVersion in spark

- phpstan.neon.dist
- system/Config/BaseService.php
- system/Config/Services.php
> Fix cannot resolve Services::xxx()

- rector.php
- system/Helpers/form_helper.php
To change `strpos(strtolower(...))` with `stripos(...)` with `SimplifyStrposLowerRector` rector rule.
**Checklist:**
> [Rector] Apply Rector: SimplifyStrposLowerRector

- rector.php
- system/CLI/CLI.php
- system/Common.php
- system/Config/BaseConfig.php
- system/Database/SQLSRV/Builder.php
- system/Database/SQLite3/Table.php
- system/Debug/Exceptions.php
- system/Email/Email.php
- system/Entity.php
- system/HTTP/DownloadResponse.php
- system/HTTP/ResponseTrait.php
- system/HTTP/URI.php
- system/Helpers/array_helper.php
- system/I18n/Time.php
- system/Model.php
- system/RESTful/BaseResource.php
- system/Router/RouteCollection.php
- system/Validation/Rules.php
- system/Validation/Validation.php
- system/View/Parser.php
Merges nested if statements with `CombineIfRector` rector rule.
**Checklist:**
> [Rector] Apply Rector: CombineIfRector

- rector.php
- system/BaseModel.php
- system/HTTP/IncomingRequest.php
- system/Model.php
- system/Test/ControllerResponse.php
- system/Test/FeatureResponse.php
Shortens if return false/true to direct return with `SimplifyIfReturnBoolRector` rector rule.
**Checklist:**
> [Rector] Apply Rector: SimplifyIfReturnBoolRector

- admin/RELEASE.md
Adding my own docs on how I handled the release so these are available centrally.
**Checklist:**
> Release Docs

- user_guide_src/source/general/environments.rst
This is undocumented.
See <https://github.com/codeigniter4/CodeIgniter4/issues/3309#issuecomment-660295895>, <https://github.com/codeigniter4/CodeIgniter4/issues/4033#issuecomment-751584280>.
**Checklist:**
> docs: add about env `testing`

- user_guide_src/source/database/query_builder.rst
Fix User Guide Example about `$builder->join()`.
**Checklist:**
> fix example  $builder->join()

- rector.php
- system/Test/Fabricator.php
reduce 2 following switch keys with identical to one result with `RemoveDuplicatedCaseInSwitchRector` rector rule.
**Checklist:**
> [Rector] Apply Rector: RemoveDuplicatedCaseInSwitchRector

- user_guide_src/source/helpers/text_helper.rst
Update list of parameter in `random_string()`
**Checklist:**
> fix list parameter random_string()

- .github/workflows/test-phpunit.yml
`phpunit.xml.dist` is duplicated.
**Checklist:**
> Fix github/workflows/test-phpunit.yml

- app/Views/welcome_message.php
Ensure user to see latest develop branch link update.
**Checklist:**
> Use develop branch for contributing link in welcome page

- app/Controllers/BaseController.php
> Add CLIRequest to request property in BaseController

- tests/system/Security/SecurityTest.php
Adds tests to `Security` to demonstrate that CSRF regeneration works as expected using `Config\Security`.
Closes #4224 
**Checklist:**
> Add tests on Security CSRF regenerate

- env
> Adds to env the additional cookie settings in App

- user_guide_src/source/general/configuration.rst
> Add docs on behavior of .env

- system/Test/Fabricator.php
> Fix PHP8 behavior of method_exists

- .github/workflows/test-rector.yml
- rector.php
- system/Email/Email.php
- system/Session/Session.php
Change inline if to explicit if with `InlineIfToExplicitIfRector` rector rule.
**Checklist:**
> [Rector] Apply Rector: InlineIfToExplicitIfRector

- app/Views/errors/html/debug.css
- app/Views/errors/html/error_exception.php
Matches the `error_exception` page to the default home page styling for more consistency in the product and a friendlier error message (no more in-your-face red bar).
> Friendlier error page to match default home style.

- system/Database/BaseBuilder.php
- system/Database/BaseResult.php
- system/Database/Forge.php
- system/Database/MySQLi/Connection.php
- system/Database/MySQLi/Forge.php
- system/Database/Postgre/Connection.php
- system/Database/SQLSRV/Builder.php
- system/Email/Email.php
- system/Helpers/filesystem_helper.php
- system/Helpers/form_helper.php
- system/Session/Handlers/RedisHandler.php
- system/Session/Session.php
- system/View/Table.php
/cc @paulbalandan Rector 0.9.30 released with improved `InlineIfToExplicitIfRector` for `BooleanOr` and `AssignOp`
**Checklist:**
> [Rector] Re-run rector with improved InlineIfToExplicitIfRector

- rector.php
handled in rector bin
**Checklist:**
> [Rector] Clean up tweak require phpstan stub

- user_guide_src/source/incoming/incomingrequest.rst
> Fix docs: remove $_SESSION in IncomingRequest

- user_guide_src/source/libraries/encryption.rst
The code does not work when you type as it is.
Because no namespace is stated.
https://forum.codeigniter.com/thread-78655-post-384575.html#pid384575
**Checklist:**
> Fix docs Encryption Library code classnames

- rector.php
- system/BaseModel.php
- system/Database/BaseBuilder.php
Return early prepared value in ifs with `PreparedValueToEarlyReturnRector` rector rule.
**Checklist:**
> [Rector] Apply Rector: PreparedValueToEarlyReturnRector

- app/Config/ContentSecurityPolicy.php
- env
- system/HTTP/ContentSecurityPolicy.php
- tests/system/HTTP/ContentSecurityPolicyTest.php
I could not push to @colethorsen's branch so here is #3924 rebased and with a test added.
**Checklist:**
> Content Security Policy "frame-src"

- system/Database/Query.php
- tests/system/Database/BaseQueryTest.php
Fixes #3566 with ~the suggested solution therein.~ `preg_match`.
**Checklist:**
> Fix named binds in Query

- system/View/Table.php
> Fix incomplete fillup of table template

- app/Config/Logger.php
- system/Language/en/Log.php
- system/Log/Exceptions/LogException.php
- system/Log/Handlers/ErrorlogHandler.php
- tests/system/Log/Handlers/ErrorlogHandlerTest.php
- user_guide_src/source/changelogs/v4.1.2.rst
- user_guide_src/source/general/logging.rst
Enhances the errorlog handler implemented in #3898. 
**Checklist:**
> Enhancements to ErrorlogHandler

- rector.php
- system/Autoloader/FileLocator.php
- system/CLI/CLI.php
- system/CodeIgniter.php
- system/Commands/Database/CreateDatabase.php
- system/Config/BaseConfig.php
- system/Config/Factories.php
- system/HTTP/ContentSecurityPolicy.php
- system/Helpers/form_helper.php
- system/Model.php
Shortens else/if to elseif with `ShortenElseIfRector` rector rule.
**Checklist:**
> [Rector] Apply Rector: ShortenElseIfRector

- system/HTTP/IncomingRequest.php
- tests/system/HTTP/IncomingRequestTest.php
Added the ability to pass a filter to getJsonVar
**Checklist:**
> Filter Json Variables

- system/Database/Postgre/Builder.php
> #4302 - postgre wrong placement of IGNORE part of statment (insert)

- user_guide_src/source/installation/upgrade_4xx.rst
- user_guide_src/source/installation/upgrade_configuration.rst
- user_guide_src/source/installation/upgrade_controllers.rst
- user_guide_src/source/installation/upgrade_migrations.rst
- user_guide_src/source/installation/upgrade_models.rst
- user_guide_src/source/installation/upgrade_views.rst
We have extended the documentation for upgrading 3.x projects to 4.x
In addition we plan to create more documentation pages for different classes and libraries to provide a easy to understand guideline for upgrading various projects
**Checklist:**
> Extended documentation for upgrading from CI3 to CI4

- user_guide_src/source/installation/upgrade_4xx.rst
- user_guide_src/source/installation/upgrade_configuration.rst
- user_guide_src/source/installation/upgrade_controllers.rst
- user_guide_src/source/installation/upgrade_migrations.rst
- user_guide_src/source/installation/upgrade_models.rst
- user_guide_src/source/installation/upgrade_views.rst
- user_guide_src/source/installation/upgrading.rst
Expands the documentation fixes suggested in #4338 
**Checklist:**
> Expand documentation fixes

- user_guide_src/source/installation/upgrade_models.rst
Fixes wrong words.
**Checklist:**
> docs: fix Upgrade Models

- system/CLI/GeneratorTrait.php
> Fix greedy namespace replacement

- system/View/Parser.php
- tests/system/View/ParserTest.php
> Fix errant regex not considering new lines

- admin/framework/README.md
The link is 404.
Reported on the forum:
https://forum.codeigniter.com/thread-78743.html
**Checklist:**
> docs: update link in framework README

- user_guide_src/source/libraries/validation.rst
Shorten the width of the table so you can't see the Example.
See <https://codeigniter4.github.io/CodeIgniter4/libraries/validation.html#available-rules>.
**Checklist:**
> docs: Validation shorten the width of the table

- .github/workflows/test-phpstan.yml
- .github/workflows/test-phpunit.yml
- .github/workflows/test-rector.yml
- .github/workflows/test-userguide.yml
> Fix missing extensions in CI/CD

- tests/system/HTTP/URITest.php
- tests/system/Helpers/URLHelperTest.php
- remove `helper('text')` , which is already running on the `mb_url_title()`
- Use Factories
**Checklist:**
> Use Factories -> \Helpers\URLHelperTest.php & \HTTP\URITest.php

- system/Database/MySQLi/Connection.php
> Fix exception object passed to log_message

- rector.php
- system/Common.php
- system/Config/Factories.php
- system/Database/MySQLi/Connection.php
- system/Database/Query.php
- system/Database/SQLSRV/Builder.php
- system/Database/SQLite3/Table.php
- system/Email/Email.php
- system/Encryption/Handlers/OpenSSLHandler.php
- system/HTTP/ResponseTrait.php
- system/Helpers/html_helper.php
- system/Model.php
- system/Test/Fabricator.php
- system/Test/ReflectionHelper.php
- tests/system/CommonSingleServiceTest.php
- tests/system/Helpers/URLHelperTest.php
Changes if/else for same value as assign to ternary with `SimplifyIfElseToTernaryRector` rule.
**Checklist:**
> [Rector] Apply Rector: SimplifyIfElseToTernaryRector

- rector.php
- system/BaseModel.php
- system/CLI/BaseCommand.php
- system/CLI/Commands.php
- system/CodeIgniter.php
- system/Commands/Database/MigrateStatus.php
- system/Commands/ListCommands.php
- system/Config/BaseConfig.php
- system/Database/BaseUtils.php
- system/Email/Email.php
- system/HTTP/CURLRequest.php
- system/HTTP/Cookie/CookieStore.php
- system/HTTP/MessageTrait.php
- system/HTTP/ResponseTrait.php
- system/Helpers/form_helper.php
- system/Model.php
- system/View/Cell.php
- tests/system/HTTP/RedirectResponseTest.php
Change foreach with unused `$value` but only `$key`, to `array_keys()` with `UnusedForeachValueToArrayKeysRector` rule.
**Checklist:**
> [Rector] Apply Rector: UnusedForeachValueToArrayKeysRector

- app/Config/Mimes.php
> xlsb&xlsm Mime Add

- system/Language/en/Cache.php
- system/Language/en/Cast.php
- system/Language/en/Fabricator.php
- system/Language/en/Files.php
- tests/system/Language/LanguageTest.php
- Add missing periods to lang files
- Remove a extra period
**Checklist:**
> Add missing periods to lang files

- system/Language/en/CLI.php
> fix typo name

- system/Test/FeatureResponse.php
- tests/system/Test/FeatureResponseTest.php
- user_guide_src/source/testing/feature.rst
Adds a few inverses to feature test response assertions.
**Checklist:**
> Negative feature assertions

- .github/workflows/test-rector.yml
- system/Filters/Filters.php
- system/Test/FilterTestTrait.php
- tests/system/Filters/FiltersTest.php
- tests/system/Test/ControllerTesterTest.php
- tests/system/Test/FilterTestTraitTest.php
- user_guide_src/source/testing/controllers.rst
This adds a new test trait to assist with testing filters in an efficient and concise manner.
**Checklist:**
> Filter Test Trait

- system/Database/Query.php
post-fix for #4444
Fix regexp's and optimize "if" statement. 
https://regex101.com/r/pMoYqY/1
**Checklist:**
> Fix expressions in Database/Query

- user_guide_src/source/incoming/incomingrequest.rst
- user_guide_src/source/outgoing/view_renderer.rst
fix indentation to fix this:
**Checklist:**
> [UG] fix indentation IncomingRequest & view_renderer

- system/I18n/TimeDifference.php
- tests/system/I18n/TimeDifferenceTest.php
- user_guide_src/source/libraries/time.rst
- Fixes TimeDifference property values
- Fixes #4452
- Fixes user guide classname notation
- Fix time zone bug in TimeDifference https://github.com/codeigniter4/CodeIgniter4/pull/4453/commits/dfba12806ff658ba7bc6956a1d609754626048ed
**Checklist:**
> Fix TimeDifference property values

- composer.json
Handled in new rector release.
> [Rector] Revert add symplify/rule-doc-generator-contracts 

- rector.php
- system/HTTP/Cookie/Cookie.php
Remove (string) casting when it comes to concat, that does this by default with `RemoveConcatAutocastRector` rector rule.
**Checklist:**
> [Rector] Apply RemoveConcatAutocastRector

- system/Security/Security.php
Fixes implementation in security component when using cookie prefixes.
https://github.com/codeigniter4/CodeIgniter4/pull/4193
**Checklist:**
> Security: Fix Cookie implementation

- user_guide_src/source/database/query_builder.rst
> docs: fix wrong QueryBuilder sample code

- user_guide_src/source/database/helpers.rst
Fix "Query Helper Methods".
**Checklist:**
> Fix docs Query Helper Methods

- system/Test/ControllerTester.php
`ControllerTester` has fallen behind `FeatureTestTrait` quite a bit. This PR touches the class up a bit:
* Implements the new trait-aware test setup
* Fixes some type mismatches
* Uses Services to ensure any extended classes are in use
**Checklist:**
> Controller Tester improvements

- system/Commands/Database/CreateDatabase.php
Fixes #4498 . I cannot make a unit test for this but tested working in local.
**Checklist:**
> Fix connection error on db:create

- system/CLI/GeneratorTrait.php
- tests/system/Commands/CommandGeneratorTest.php
Fixes #4495 
@datamweb can you test this solution?
**Checklist:**
> Fixes generator not preserving letter case

- .github/workflows/test-phpunit.yml
- composer.json
- phpunit.xml.dist
Enhancement to `johnkary/phpunit-speedtrap` that can have inline annotations for Github Actions.
**Checklist:**
> Switch to tachycardia for slow tests profiling and reporting

- system/Common.php
- system/Cookie/CloneableCookieInterface.php
- system/Cookie/Cookie.php
- system/Cookie/CookieInterface.php
- system/Cookie/CookieStore.php
- system/HTTP/RedirectResponse.php
- system/HTTP/Response.php
- system/HTTP/ResponseInterface.php
- system/HTTP/ResponseTrait.php
- system/Security/Security.php
- system/Session/Session.php
- system/Test/Mock/MockSession.php
- tests/system/Cookie/CookieStoreTest.php
- tests/system/Cookie/CookieTest.php
- tests/system/HTTP/ResponseCookieTest.php
- user_guide_src/source/libraries/cookies.rst
Moving cookie class to main system folder, while its a single component and doesn't depends on http class
> Relocate Cookie

- system/Helpers/form_helper.php
make `form_submit()` & `form_reset()` based on `form_input()`
**Checklist:**
> make form_submit() & form_reset() based on form_input()

- .github/workflows/test-rector.yml
- rector.php
- utils/Rector/PassStrictParameterToFunctionParameterRector.php
- utils/Rector/UnderscoreToCamelCaseVariableNameRector.php
> [Rector] Fixes Custom Rector Rule CodeSample use statement class

- system/Model.php
> Suppress PhpStorm warning to `db` in `Model`

- .github/workflows/test-phpunit.yml
> Fix cannot create database in SQLSRV in Actions

- .github/workflows/test-rector.yml
- composer.json
- rector.php
- system/HTTP/RequestInterface.php
- system/HTTP/ResponseInterface.php
- tests/system/Autoloader/AutoloaderTest.php
- tests/system/Config/BaseConfigTest.php
- tests/system/Test/ControllerTestTraitTest.php
> [Rector] Fixing rector action hang

- composer.json
Rector 0.10.4 just released. https://github.com/rectorphp/rector/releases/tag/0.10.4
**Checklist:**
> [Rector] Pin Rector 0.10.4

- user_guide_src/source/outgoing/api_responses.rst
> Fix wrong argument passed in doc

- rector.php
- system/Config/DotEnv.php
- system/Database/BaseUtils.php
- system/Validation/Validation.php
Remove unnecessary ternary expressions with `UnnecessaryTernaryExpressionRector` rector rule.
**Checklist:**
> [Rector] Apply Rector: UnnecessaryTernaryExpressionRector

- system/Validation/Validation.php
https://github.com/codeigniter4/CodeIgniter4/issues/4552
**Checklist:**
> Fix: Validation::withRequest() with Content-Type: multipart/form-data

- rector.php
- utils/Rector/RemoveDefaultArgumentValueRector.php
> [Rector] Add Comment for reason RemoveDefaultArgumentValueRector copied to utils/Rector

- system/BaseModel.php
https://github.com/codeigniter4/CodeIgniter4/blob/63d0b27420e7506f3ac84147a3d7bc6c0adc6e39/system/BaseModel.php#L554
**Checklist:**
> Fix: BaseModel. Removed duplicate code.

- app/Config/App.php
- env
> Removes deprecated settings in env file

- app/Views/errors/html/error_exception.php
There was just an extra end tag in the HTML.
> extra </li> in tabs area

- system/Common.php
PHPDoc fix for service() and single_service() methods
**Checklist:**
> Fix service methods …$params type

- app/Config/Exceptions.php
> whitespaces

- app/Views/errors/html/error_404.php
adjust the style 
**Checklist:**
> format style

- system/Autoloader/FileLocator.php
Fixes #4318 
Fixes #4597 
**Checklist:**
> Use realpath() to fix app prioritization of validation messages

- composer.json
Add a branch alias to composer.json to alias `develop` branch as `4.x-dev`. This way libraries can just write `codeigniter4/codeigniter4: 4.x-dev` in their `require` section.
**Checklist:**
> Add branch alias for develop branch

- .github/workflows/deploy-apidocs.yml
- .github/workflows/deploy-framework.yml
- .github/workflows/deploy-userguide-latest.yml
- .github/workflows/test-phpstan.yml
- .github/workflows/test-phpunit.yml
- .github/workflows/test-rector.yml
- .github/workflows/test-userguide.yml
Reverts codeigniter4/CodeIgniter4#4678
> Revert Actions minor versioning

- .github/workflows/deploy-apidocs.yml
- .github/workflows/test-phpstan.yml
- .github/workflows/test-phpunit.yml
- .github/workflows/test-rector.yml
Reverts codeigniter4/CodeIgniter4#4679
> Revert Actions minor version

- public/.htaccess
- user_guide_src/source/libraries/uri.rst
A couple quick formatting fixes.
**Checklist:**
> Spacing issues

- user_guide_src/source/_static/css/citheme.css
Reverts codeigniter4/CodeIgniter4#4252
This PR did not have the desired effect on the User Guide. Reverting this until it can be handled later.
> Revert UG margins

- tests/system/CLI/CLITest.php
- tests/system/Cache/Handlers/FileHandlerTest.php
- tests/system/Cache/Handlers/MemcachedHandlerTest.php
- tests/system/Cache/Handlers/PredisHandlerTest.php
- tests/system/Cache/Handlers/RedisHandlerTest.php
- tests/system/Debug/TimerTest.php
> Annotate specifically designed slow tests with custom limits

- system/Commands/Generators/ValidationGenerator.php
- system/Database/SQLSRV/Connection.php
- system/Database/SQLite3/Connection.php
- system/HTTP/IncomingRequest.php
- system/Router/RouteCollection.php
- system/Test/DatabaseTestTrait.php
- system/Test/Fabricator.php
- system/Test/Mock/MockServices.php
- system/Test/TestResponse.php
Removed unused imports, because removed code is good code 😅 
:octocat:
> Remove unused imports

- user_guide_src/source/helpers/array_helper.rst
> update return sample of `dot array_search()`

- public/index.php
- spark
- user_guide_src/source/general/managing_apps.rst
Reduce repetitive definition to easier update. Based on http://forum.codeigniter.com/thread-79249-post-386973.html#pid386973
**Checklist:**
> Use variable for Config/Paths config to reduce repetitive definition

- rector.php
- system/Cache/Handlers/MemcachedHandler.php
- system/Config/DotEnv.php
- system/Cookie/Cookie.php
- system/Filters/Filters.php
- system/HTTP/Negotiate.php
- system/I18n/Time.php
- system/Images/Handlers/BaseHandler.php
- system/Images/Handlers/ImageMagickHandler.php
- system/Language/Language.php
- system/Log/Logger.php
- system/Router/Router.php
- system/Test/DOMParser.php
- system/Validation/Rules.php
- system/View/Cell.php
Change `list()` to array destruct with `ListToArrayDestructRector` rector rule.
**Checklist:**
> [Rector] Apply Rector : ListToArrayDestructRector

- .github/workflows/test-phpunit.yml
Trying to fix the build...
**Checklist:**
> Fix imagemagick build

- .gitattributes
- .github/workflows/test-phpunit.yml
- .gitignore
- .php-cs-fixer.dist.php
- admin/framework/composer.json
- composer.json
- utils/PhpCsFixer/CodeIgniter4.php
Recreates #4763 and limit PR changes to the addition of the actual configurations and libraries.
Actual changes to the entire codebase will be done in batches and in separate PRs (that's why the `$rules` is an empty array here).
This is aligned to the adoption of the PSR-12 standard plus some customized rules for the CI4 org.
**Checklist:**
> Use php-cs-fixer as coding style tool

- system/Commands/Database/CreateDatabase.php
- system/Config/DotEnv.php
- system/Email/Email.php
- system/Helpers/text_helper.php
- system/I18n/Time.php
- system/Test/DOMParser.php
- system/View/Cell.php
- tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
- tests/system/Commands/GeneratorsTest.php
- tests/system/Database/Migrations/MigrationTest.php
- tests/system/View/ParserTest.php
- utils/PhpCsFixer/CodeIgniter4.php
> [CS Migration]Enable `binary_operator_spaces`

- system/CLI/CLI.php
- system/Cache/Handlers/MemcachedHandler.php
- system/Database/BaseBuilder.php
- system/Database/BasePreparedQuery.php
- system/Database/Postgre/PreparedQuery.php
- system/Database/SQLSRV/Builder.php
- system/Database/SQLSRV/Forge.php
- system/HTTP/ContentSecurityPolicy.php
- system/Helpers/html_helper.php
- system/Images/Handlers/ImageMagickHandler.php
- system/Test/CIUnitTestCase.php
- system/Test/DOMParser.php
- system/Test/Fabricator.php
This is certainly one of those micro-optimizations, but depending on how often these methods are called, the fewer variable assignments/passings could add up 🤞
:octocat:
> Remove unused local variables

- .editorconfig
- admin/pre-commit
- phpunit.xml.dist
- system/Commands/Generators/Views/command.tpl.php
- system/Commands/Generators/Views/config.tpl.php
- system/Commands/Generators/Views/controller.tpl.php
- system/Commands/Generators/Views/entity.tpl.php
- system/Commands/Generators/Views/filter.tpl.php
- system/Commands/Generators/Views/migration.tpl.php
- system/Commands/Generators/Views/model.tpl.php
- system/Commands/Generators/Views/seeder.tpl.php
- system/Commands/Generators/Views/validation.tpl.php
Continuation for #4771 
**Checklist:**
> [CS Migration]Update indentation to spaces

- system/CodeIgniter.php
- system/Database/BaseBuilder.php
- system/Database/BaseConnection.php
- system/Router/RouteCollection.php
- tests/system/Test/FeatureTestTraitTest.php
- utils/PhpCsFixer/CodeIgniter4.php
I noticed @paulbalandan's https://github.com/codeigniter4/CodeIgniter4/pull/4442#discussion_r596571689 
> We don't do yoda conditions. :)
and thought: "While I'm at it, why rulified not shall it be" 😬 
:octocat:
> Define yoda_style rule and initially apply no_yoda style

- system/CLI/CLI.php
- system/Debug/Toolbar/Collectors/Routes.php
- system/I18n/Time.php
[Operator precedence](https://www.php.net/manual/en/language.operators.precedence.php) always is a headscratcher for me 😅 
:octocat:
> Add brackets to clarify intent and avoid unwanted side-effects

- system/BaseModel.php
- system/CLI/BaseCommand.php
- system/CLI/CLI.php
- system/Database/BaseConnection.php
- system/Email/Email.php
- system/Model.php
- system/Router/RouteCollection.php
- system/Test/Mock/MockCache.php
- utils/PhpCsFixer/CodeIgniter4.php
The null coalescing operator saves code and reduces cognitive overload 💆 
:octocat:
> Use null coalescing operator

- system/Language/en/CLI.php
- tests/_support/Models/ValidErrorsModel.php
- tests/system/Commands/CommandTest.php
- tests/system/Config/fixtures/RegistrarConfig.php
- tests/system/Database/Builder/InsertTest.php
- tests/system/Filters/FiltersTest.php
- tests/system/HTTP/ResponseTest.php
- tests/system/Helpers/FilesystemHelperTest.php
- tests/system/Language/LanguageTest.php
- tests/system/View/ParserTest.php
- utils/PhpCsFixer/CodeIgniter4.php
> Enable rules fixing array notations

- system/Config/Services.php
- system/Test/FilterTestTrait.php
- system/Test/Mock/MockCache.php
- system/Test/Mock/MockServices.php
- tests/system/Autoloader/AutoloaderTest.php
- tests/system/Cache/Handlers/BaseHandlerTest.php
- tests/system/Config/BaseConfigTest.php
- tests/system/Database/Live/ConnectTest.php
- tests/system/EntityTest.php
- tests/system/Images/ImageMagickHandlerTest.php
- tests/system/Router/RouterTest.php
- tests/system/Test/ControllerTestTraitTest.php
- tests/system/Test/FilterTestTraitTest.php
- utils/PhpCsFixer/CodeIgniter4.php
- utils/Rector/RemoveVarTagFromClassConstantRector.php
> Enable `ordered_imports`

- app/Views/welcome_message.php
Before: https://prnt.sc/1559re2
After: https://prnt.sc/1559uou
> Graphic fix on some screen res

- user_guide_src/source/libraries/sessions.rst
Just rename folder name in UG 
`application` to `app`.
**Checklist:**
> rename `application` to `app`

- admin/module/tests/_support/Libraries/ConfigReader.php
- admin/starter/tests/_support/Libraries/ConfigReader.php
- app/Common.php
- app/Config/Logger.php
- system/Common.php
- system/Email/Email.php
- system/HTTP/Response.php
- system/Modules/Modules.php
- system/Pager/Views/default_head.php
- tests/_support/Controllers/Popcorn.php
- tests/_support/Language/en/Core.php
- tests/_support/Models/SimpleEntity.php
- tests/system/CLI/CommandRunnerTest.php
- tests/system/Database/Builder/InsertTest.php
- tests/system/Database/Builder/UpdateTest.php
- tests/system/Database/Builder/WhereTest.php
- tests/system/Database/Live/UpdateTest.php
- tests/system/Test/ControllerTestTraitTest.php
- utils/PhpCsFixer/CodeIgniter4.php
> Initial Phpdoc-related rules

- utils/PhpCsFixer/CodeIgniter4.php
> Define rules for ternary operators

- system/Debug/Toolbar.php
- system/Entity/Cast/JsonCast.php
- system/Test/Mock/MockResult.php
- tests/system/Cache/Handlers/BaseHandlerTest.php
- tests/system/CommonFunctionsTest.php
- tests/system/Database/Builder/WhereTest.php
- tests/system/Database/DatabaseSeederTest.php
- tests/system/Database/Live/GetTest.php
- tests/system/Database/Migrations/MigrationTest.php
- tests/system/EntityTest.php
- tests/system/HTTP/HeaderTest.php
- tests/system/Images/ImageMagickHandlerTest.php
- tests/system/Models/GeneralModelTest.php
- tests/system/Models/InsertModelTest.php
- tests/system/Models/SaveModelTest.php
- tests/system/Models/UpdateModelTest.php
- tests/system/RESTful/ResourceControllerTest.php
- tests/system/Router/RouterTest.php
- tests/system/View/ParserTest.php
- utils/PhpCsFixer/CodeIgniter4.php
This is regardless whether the instantiated class has constructor arguments or not.
**Checklist:**
> PSR12: All instances created with `new` keyword must be followed by braces.

- spark
- system/HTTP/IncomingRequest.php
- utils/PhpCsFixer/CodeIgniter4.php
> Master language constructs shall be used instead of aliases.

- rector.php
- tests/system/Database/Builder/InsertTest.php
- tests/system/Database/Builder/UpdateTest.php
- tests/system/Helpers/URLHelper/SiteUrlTest.php
- tests/system/Router/RouterTest.php
Remove extra parameters in method call / function call with `RemoveExtraParametersRector` rule.
**Checklist:**
> [Rector] Apply Rector: RemoveExtraParametersRector

- admin/framework/composer.json
- composer.json
- system/ThirdParty/Escaper/Escaper.php
- system/ThirdParty/Escaper/Exception/ExceptionInterface.php
- system/ThirdParty/Escaper/Exception/InvalidArgumentException.php
- system/ThirdParty/Escaper/Exception/RuntimeException.php
Ref https://github.com/laminas/laminas-escaper/releases/tag/2.8.0
**Checklist:**
> Update to latest laminas-escaper ^2.8

- system/Common.php
Simple docblock update for `redirect()` function.
Closes #4732
**Checklist:**
> Update docblock for redirect() function

- utils/PhpCsFixer/CodeIgniter4.php
> Enable `echo_tag_syntax` until `error_suppression` fixers

- system/Database/SQLSRV/Builder.php
- system/Database/SQLSRV/Connection.php
- system/Database/SQLSRV/Forge.php
- system/Database/SQLSRV/Utils.php
- tests/system/Database/Live/PreparedQueryTest.php
- tests/system/Database/Migrations/MigrationRunnerTest.php
Proper  schema support for SQLSRV driver for 4.2 branch
This is related to defect: #4853  and previous PR #4860 
**Checklist:**
> Finalize SQLSRV schema support for 4.2 branch

- user_guide_src/source/libraries/throttler.rst
> Update docs for Throttler

- system/Database/BaseBuilder.php
- system/Database/MySQLi/Connection.php
- system/Debug/Exceptions.php
- system/Filters/Filters.php
- system/Session/Handlers/MemcachedHandler.php
- system/Session/Session.php
- utils/PhpCsFixer/CodeIgniter4.php
- `->` and `?->` should have no whitespace in between
- operators on line breaks should be at the beginning for consistency
- set ordering rules of elements
**Checklist:**
> Define "o" rules

- .github/workflows/deploy-apidocs.yml
- phpdoc.dist.xml
Fixes #1988 
Snippet of successful run: https://github.com/paulbalandan/CodeIgniter4/actions/runs/903865690
**Checklist:**
> Update to phpdocumentor v3.0

- .github/workflows/test-coding-standards.yml
> Add workflow for linting framework

- admin/pre-commit
- admin/setup.sh
> Update pre-commit to lint code

- .github/workflows/deploy-apidocs.yml
- Update to phpdoc v3.1
- Bump php runtime to 8.0
- ~Run on pull requests affecting this file to test it~
- ~Push to `codeigniter4/api` if this is a push event only~
- Push to `codeigniter4/api` if there are changes that need to be committed
**Checklist:**
> Update to phpdoc v3.1

- rector.php
- system/Helpers/text_helper.php
- system/Test/ReflectionHelper.php
Refactor `func_get_args()` in to a variadic param with `FuncGetArgsToVariadicParamRector` rector rule.
**Checklist:**
> [Rector] Apply FuncGetArgsToVariadicParamRector

- rector.php
- system/Database/MySQLi/Connection.php
- system/Database/Postgre/Builder.php
- system/Database/Postgre/Connection.php
- system/Database/SQLSRV/Connection.php
- system/Database/SQLite3/Connection.php
- system/Images/Handlers/GDHandler.php
- system/Images/Handlers/ImageMagickHandler.php
- system/Test/Constraints/SeeInDatabase.php
- system/Test/Mock/MockIncomingRequest.php
- system/Test/Mock/MockSecurity.php
- user_guide_src/source/changelogs/v4.1.4.rst
Make method visibility same as parent one with `MakeInheritedMethodVisibilitySameAsParentRector` rector rule.
**Checklist:**
> [Rector] Apply MakeInheritedMethodVisibilitySameAsParentRector

- rector.php
- tests/system/HTTP/IncomingRequestDetectingTest.php
Remove duplicated assign with `RemoveDoubleAssignRector` rector rule.
**Checklist:**
> [Rector] Apply Rector: RemoveDoubleAssignRector

- app/Config/Generators.php
Add missing make:config command view file
> Add missing generators' config view file

- system/Files/File.php
Related to #4883
**Checklist:**
> Make File compatible with SplFileInfo

- system/Debug/Exceptions.php
- tests/system/Debug/ExceptionsTest.php
Fixes #5051
Added some tests
**Checklist:**
> Fixes and enhancements to Exceptions

- system/Commands/Generators/ModelGenerator.php
- system/Commands/Generators/Views/entity.tpl.php
- system/Commands/Generators/Views/model.tpl.php
- tests/system/Commands/ModelGeneratorTest.php
> Fix entity name generation when bundled in model

- user_guide_src/source/changelogs/v4.1.4.rst
Fix indentation of the list.
**Checklist:**
> docs: fix indentation of the changelog v4.1.4

- .github/workflows/deploy-apidocs.yml
> Add phive to tools in workflow

- .github/workflows/deploy-apidocs.yml
The phive installation seems more than meets the eye.
> Test fixing apidocs action

- user_guide_src/source/installation/repositories.rst
- update coding-standard repo links
**Checklist:**
> docs: update coding-standard links

- user_guide_src/source/installation/upgrade_420.rst
- user_guide_src/source/installation/upgrading.rst
Add upgrade instruction for database session.
See <https://github.com/codeigniter4/CodeIgniter4/issues/4807#issuecomment-860288412>, #2256. 
**Checklist:**
> docs: add session table change for upgrade

- user_guide_src/source/intro/psr.rst
Now our coding style meets PSR-12.
**Checklist:**
> docs: update PSR Compliance (PSR-12)

- user_guide_src/source/outgoing/view_parser.rst
- replace all tabs with spaces
- tab is converted to 8 spaces
- add or remove spaces
**Checklist:**
> docs: fix view_parser

- user_guide_src/source/dbmgmt/forge.rst
- add missing addForeignKey() in Class Reference
**Checklist:**
> docs: fix db_forge

- user_guide_src/source/installation/upgrade_4xx.rst
- user_guide_src/source/installation/upgrade_database.rst
- user_guide_src/source/installation/upgrade_emails.rst
- user_guide_src/source/installation/upgrade_encryption.rst
- user_guide_src/source/installation/upgrade_file_upload.rst
- user_guide_src/source/installation/upgrade_html_tables.rst
- user_guide_src/source/installation/upgrade_localization.rst
- user_guide_src/source/installation/upgrade_migrations.rst
- user_guide_src/source/installation/upgrade_pagination.rst
- user_guide_src/source/installation/upgrade_responses.rst
- user_guide_src/source/installation/upgrade_routing.rst
- user_guide_src/source/installation/upgrade_security.rst
- user_guide_src/source/installation/upgrade_sessions.rst
- user_guide_src/source/installation/upgrade_validations.rst
- user_guide_src/source/installation/upgrade_view_parser.rst
Supersedes and closes #4565
**Checklist:**
> docs: extended upgrading from CI3 to CI4

- user_guide_src/source/installation/upgrade_migrations.rst
Add instruction to upgrade migration table.
**Checklist:**
> docs: add about upgrading migration table

- user_guide_src/source/installation/upgrade_routing.rst
Controller classnames are PascalCase.
**Checklist:**
> docs: fix sample code in upgrade_routing

- user_guide_src/source/general/configuration.rst
- fix indentation in sample code
**Checklist:**
> docs: small fixes for configuration

- user_guide_src/source/dbmgmt/migration.rst
- fix indentation
- align indentations
**Checklist:**
> docs: fix indentation for migration

- system/Config/Factories.php
- fix typo in doc comment
**Checklist:**
> Fix typo in Config/Factories.php
