system/Router/RouteCollection.php
system/Router/Router.php
tests/system/CodeIgniterTest.php
tests/system/Router/RouteCollectionTest.php

Fix. router no set, Redirect can't work

---

system/CodeIgniter.php

Added a default locale setting during application initialization.
When I tried to create a Time object without additional parameters, it turned out that the time zone is set by default, but the locale is not.
**Checklist:**

Added a default locale setting during application initialization.

---

.github/scripts/deploy-appstarter
.github/scripts/deploy-framework
admin/framework/.gitignore
admin/starter/.gitignore

Adds a version of `.gitignore` to **admin/starter** and **admin/framework** that does not include `composer.lock` on the ignore list. Projects should be committing their lock files, but if they start with our current repos they will receive this repo's `.gitignore` which (correctly) does *not* commit the lock file.
**Checklist:**

Cease ignoring composer.lock in deployable repos

---

system/Model.php

This should fix https://github.com/codeigniter4/CodeIgniter4/issues/3039 .
**Checklist:**

Fix: Model::getValidationRules() return when using shared rules

---

system/Debug/Exceptions.php

In `Exceptions::render()`, added `$altPath` and `$altView` so that if the path configured in `Config\Exceptions` does not exist or the view does not exist either, then it will look for the error view file provided as default by the framework.
**Checklist:**

Add altPath to choose in Exceptions::render

---

system/HTTP/URI.php
tests/system/HTTP/URITest.php
user_guide_src/source/libraries/uri.rst

This PR adds a second parameter to the `getSegment()` method, so we can change the default value that will be returned when there is no segment set. Usually, this feature will be used along with `setSilent()`, so that the exception will be not thrown.
**Checklist:**

Add default value to getSegment() method

---

system/Common.php
system/Test/FeatureTestTrait.php

Currently `FeatureTest` initiates an insecure request, which means if `forceGlobalSecureRequests` is activated then every status will be `302`. This PR has `FeatureTestTrait::setupRequest` check for that configuration and notify the app to make a special exemption so requests will be both a) secure and b) not redirected.
**Checklist:**

Feature Tests & forceSecure

---

system/Test/FeatureResponse.php
tests/system/Test/FeatureResponseTest.php
user_guide_src/source/testing/feature.rst

Often validating that a response is a redirect is not enough to determine what happened during a controller method, as there may be multiple redirect routes. This PR adds `getRedirectUrl()` to make it easy to acquire the actual URL to verify HTTP test results.
**Checklist:**

Get redirect URL from FeatureResponse

---

system/HTTP/Response.php
tests/system/CodeIgniterTest.php

From #3041
Thanks @MichalPB1 's suggest
Redirect HTTP Code can't work. when method is get, it always set as 307.
**Checklist:**

Fix. redirect custom HTTP Code not work

---

system/Test/FeatureTestTrait.php

Validation uses `Request::getVar()` to load input data. During feature testing, `populateGlobals()` fills the appropriate method ('post', 'get', etc) but not the super-var 'request', so validation always fails to receive any input data.
This PR adds an additional call to `setGlobal()` to fill 'request' with the same data as the method-specific version.
**Checklist:**

Fix FeatureTest validation

---

system/Debug/Exceptions.php

Fixes #3067. Apparently, I was at fault for this bug. My apologies.
The bug occurs on line 299 of `Exceptions` upon extraction of `$vars` into the current symbol table. On lines 288 to 295, we check which of the available views to use and assign the value to `$file`. Then on line 298, we collect the exception's variables. Examining the array returned by `$this->collectVars`, we can see that there exists a `file` key corresponding to the file of the current exception.
Upon import of the `$vars`, the `$file` variable which we originally determined in lines 288 to 295 was replaced by the `file` key of `$vars`. Thus, on `include` of the `$file`, we erroneously included the exception file itself, not the supposed error view file. This resulted to the class re-declaration fatal …

Fix wrong included file in exception rendering

---

system/Test/FeatureTestTrait.php
tests/system/Test/FeatureTestCaseTest.php
user_guide_src/source/testing/feature.rst

Currently, running a Feature Test will start with a fresh Session when you make the call(). While this helps ensure that each test is contained it means you cannot prep anything in the Session, such as logging a user in.
This PR is solution "Plan B" which overloads `withSession()` to default to use the current Session values. This still requires calling `withSession()` on every feature test, but allows the session to prepared by all the usual means by the test case.
See also #3077.
Ref. https://forum.codeigniter.com/thread-76673.html
**Checklist:**

Add withSession null case

---

system/Helpers/url_helper.php
tests/system/Helpers/URLHelperTest.php
user_guide_src/source/helpers/url_helper.rst

This PR adds a new function: `mb_url_title()` that supports accented characters.
Ref: #3038
**Checklist:**

Add mb_url_title() function

---

system/Test/Fabricator.php
system/Test/Interfaces/FabricatorModel.php
user_guide_src/source/testing/fabricator.rst

`Fabricator` supports core framework models, but also allows for non-framework models if users want to craft their own. This PR tries to lighten and clarify what requirements exist on the model class in order for it to function with `Fabricator`.
**Checklist:**

Clarify non-framework Fabricator model use

---

user_guide_src/source/tutorial/create_news_items.rst

In the "First application" tutorial, in the section "Create news item", we validate input data for every type of request. In this case, validation should take place only with the `POST` request, to avoid displaying a validation error messages when we load the page for the first time.
Ref: #3071
**Checklist:**

Tutorial - validate data only with POST request

---

system/Model.php
tests/system/Database/Live/ModelTest.php

This PR fixes the lack of exception when we add an empty object to `insert()` method.
Ref: #2998
**Checklist:**

Fix - throw an exception on insert for an empty object

---

system/Format/XMLFormatter.php
tests/system/Format/XMLFormatterTest.php

XMLFormatter in some cases produce not valid XML.
Ref: #3092
**Checklist:**

Fix for XMLFormatter class to produce a valid XML

---

system/Router/Router.php

Fixed calls to filters when adding them from routes in the presence of {locale}.
The same problem is described in [#2390]([url](https://github.com/codeigniter4/CodeIgniter4/issues/2390))
**Checklist:**

Fixed calls to filters when adding them from routes in the presence of {locale}.

---

system/Entity.php

Don't escape unicode characters when saving JSON from Entities. Fixes #3059

---

system/Debug/Toolbar/Views/_routes.tpl
system/Debug/Toolbar/Views/toolbar.css
system/Debug/Toolbar/Views/toolbar.js

I think this useful when we would test or check an URI by click the link without write or copy/paste to address bar. Only GET method.
Support custom placeholder.
**Checklist:**

Small Feature: debugbar link

---

system/Router/RouteCollection.php
tests/system/Router/RouteCollectionTest.php

Fixes #3048. 
While I'm at it, I also fixed the "Nested ternary operation" deprecation warning for PHP 7.4. 
**Checklist:**

Fix regex of fillRouteParams

---

system/Validation/Validation.php
tests/system/Validation/ValidationTest.php

Fix for custom validation message defined via config file

---

system/Validation/FileRules.php
tests/system/Validation/FileRulesTest.php
user_guide_src/source/libraries/validation.rst

In general, when the uploaded file exceeds the `upload_max_filesize` from php.ini, we should also return `false`. Right now, developers can be confused about what is going on. With this change, we can at least direct them to the problem.
Ref: #3032
**Checklist:**

Update max_size validation rule to check also upload_max_filesize

---

system/Validation/FileRules.php
tests/system/Validation/FileRulesTest.php

Currently, all validation checks of `FileRules` allows validating array file uploads, except for `uploaded`. This PR adds that functionality. The documentation had already said that **all** file validation rules check for both single and multiple file uploads.
Fixes #3018 
**Checklist:**

Allow array file uploads to be validated also by 'uploaded'. Fixes #3018

---

system/Test/FeatureTestTrait.php

Currently two separate test cases will cause a conflict in the resulting `$routes` used in the simulated application. I think this ultimately has to do with re-requiring **Routes.php** in `tryToRouteIt()`:
```
if (empty($routes) || ! $routes instanceof RouteCollectionInterface)
{
require APPPATH . 'Config/Routes.php';
}
```
This PR forces `FeatureTestTrait::call()` to load `$routes` from Services (if none were specified) to prevent the corruption. See also #3105 for symptoms.
**Checklist:**

Use explicit Routes in feature testing

---

tests/system/Cache/Handlers/MemcachedHandlerTest.php

Updated 3rd parameter from 1 to 2.
**Checklist:**

Update 3rd parameter of memcachedHandler::save() call on MemcachedHandlerTest::testGet() to ensure no random failure at Travis 

---

system/HTTP/CURLRequest.php
tests/system/HTTP/CURLRequestTest.php

In `CURLRequest` class we shouldn't set encoding by default (when there are no headers set). It's not expected and confuses. It can lead to different results when we call out code via webpage and e.g. when we fire a CRON task.
Ref: #3034
**Checklist:**

Remove Accept-Encoding header after using populateHeaders() method

---

.github/workflows/docs_nightly.yml

Added workflow to build userguide changes when pushed to develop branh and commit to gh-pages so dev docs are always up to date.
See: https://github.com/ammaraskar/sphinx-action

Keep development docs up to date

---

system/CLI/CLI.php

At present, actual checking of terminal height and width happens only for *nix systems. For Windows, only default values are given.
This PR uses [`mode CON`](https://www.computerhope.com/modehlp.htm) to get the actual lines and columns for Windows systems. However, there were reports that Cygwin and GitBash returns incorrect values when using `mode CON` so, as fallback, `tput` was used.
As for Unix systems, added `stty size` as primary check before fallback to `tput`.
**Checklist:**

Update CLI getHeight and getWidth

---

system/Images/Handlers/BaseHandler.php
system/Images/Handlers/ImageMagickHandler.php

Fixe #3006
I think the rotation from exif is not in the good direction 
Change the rotation direction on image reorient()
Maybe reorient methode should be add in the doc
**Checklist:**

Fixe rotation direction on reorient()

---

tests/system/Cache/Handlers/FileHandlerTest.php
tests/system/Cache/Handlers/PredisHandlerTest.php
tests/system/Cache/Handlers/RedisHandlerTest.php

These tests seem to randomly fail from time to time. Hopefully increasing TTL will help.
**Checklist:**

Increase TTL for cache in testGet

---

system/Model.php
tests/system/Database/Live/ModelTest.php

When we set the `$reset` parameter to `false` in `countAllResults()`, the  "soft delete" method should not be reset because it affects the form of the query we want to use next time.
Ref: #3121
**Checklist:**

Fix reset functionality for countAllResults()

---

system/Session/Handlers/RedisHandler.php

When we set `$sessionExpiration = 0` for RedisHandler, we have to actually use `ini_get('session.gc_maxlifetime')` under the hood, because otherwise, we can't save session data - `0` is not valid value for `set` method.
Setting `null` would not work either since data would be never expired. Using `ini_get('session.gc_maxlifetime')` makes it reasonable enough. CI3 handles this in the same way.
Ref: #3111 
**Checklist:**

RedisHandler update for sessionExpiration = 0

---

system/Email/Email.php
system/Test/Mock/MockEmail.php
tests/system/Email/EmailTest.php
user_guide_src/source/extending/events.rst

Defines a new Event, "email", triggered on successful email send. The event receives the Email class's current set of properties so listeners can respond to email specifics.
@samsonasik Please review the move of `archive` on the MockEmail class per my other comment. If you want to review this whole PR I would appreciate it :)
**Checklist:**

Email Event

---

system/Email/Email.php

Currently `Email::$subject` is only set internally before calling `sendWithMail()`, but there are a number of cases the property can show up during testing and debugging. This PR sets the property when using `setSubject()` (which currently skips `$subject` and just sets the `header`) to make it accessible for those cases, without affecting its use during `sendWithMail()`.
**Checklist:**

Set Email subject property

---

tests/system/Pager/PagerRendererTest.php

Added more test to PagerRenderer for testing `getPreviousPage()` and `getNextPage()` when segment > 0. By this,  `Pager\PagerRenderer` class will have 100% test coverage.
**Checklist:**

more test for PagerRenderer

---

system/HTTP/Request.php
tests/system/HTTP/RequestTest.php

This PR fixes the issue with `fetchGlobal()` method in Request class. Right now, when using a filter or flag, these will be applied only to the first level of input data.
Ref: #3128
**Checklist:**

Fix filtering for fetchGlobal() method

---

.gitignore
system/Database/SQLite3/Connection.php
user_guide_src/source/changelogs/index.rst
user_guide_src/source/changelogs/v4.0.4.rst
user_guide_src/source/database/configuration.rst
writable/data/index.html

We should make it very clear in the release notes that the default location has changed. I know this is more a bugfix, but it also may break "things" for some people.
See: #3113 
**Checklist:**

Fix default location for SQLite3 database

---

system/Email/Email.php
system/Test/Mock/MockEmail.php
tests/system/Email/EmailTest.php
user_guide_src/source/libraries/email.rst

My last PR on this subject (#3141) both missed some other properties that are set only into headers and had a logical error in that class properties without autoClear can persist and override values on next send. Oops. This PR moves all the gathering of "last successful send" data into a dedicated property, modeled after `MockEmail`'s way of doing it, and uses that to track header-only values.
Side note, it's clear to me that `Email` is in sore need of updating. I know this was a temporary port of CI3 but it really would benefit from some attention soon, especially splitting out the handlers.
**Checklist:**

Implement Email archive

---

system/Email/Email.php
system/Test/Mock/MockEmail.php
tests/system/Email/EmailTest.php

Real sorry to do this fam - more issues with the new Email archive functionality. I added a test this time that will fail under the current conditions - basically repeated email sends with the same instance will overwrite archive values with blanks sometimes. This PR addresses it by using the `$tmpArchive` property instead of trying to bundle it all onto `$archive`. I've also consolidated the functionality to a new method to make it cleaner.
Hopefully the last on Email from me for a bit. :)
**Checklist:**

Revamp Email archive

---

.github/workflows/docs_nightly.yml

The `docs_nightly` workflow is set to trigger whenever a push is made to `develop`. However, this also causes it to trigger on forks cause Action errors. This PR puts a conditional in place to ensure it only runs on the main repo.
**Checklist:**

Prevent docs Action on forks

---

system/Email/Email.php

Another `Email` issue. `sendWithMail` actually updates the `$recipient` property to a string, violating its `array` property declaration (and causing issues with anything that relies on them). This PR implodes to a local variable instead leaving `$recipients` correctly as an array.
**Checklist:**

Email property violation

---

system/Test/CIUnitTestCase.php

In the `createApplication` method of `CIUnitTestCase`, the `$paths` variable was not used (or forgotten to be used?) so there's no need to retain that.
**Checklist:**

Remove unused code in CIUnitTestCase

---

system/Database/MySQLi/Connection.php

Change default value of `$socket` from `null` to an empty string instead.
See #2996 .
**Checklist:**

Fix type of $socket in MySQLi\Connection

---

system/Commands/Utilities/Namespaces.php

Currently, the `$path` is determined by using a `realpath` on it, or itself on failure. **BUT** this uses the `null coalescing operator`. Since `realpath` returns `false` on failure, the right-hand side of the statement will never be reached even on failure. Thus, this PR addresses this by using an `Elvis operator` instead.
**Checklist:**

Fix ternary operator for $path in Namespaces Command

---

system/CLI/CLI.php
tests/system/CLI/CLITest.php

Currently, colored output support is disabled for Windows and only works for Unix systems. This PR adds a new method `hasColorSupport` which uses a number of variables to check if the current terminal or environment has support for colorized output.
PS. I'm running my tests on Windows so I needed to normalize the tests' line endings of `LF` to `PHP_EOL` to eliminate unrelated failures on testing.
**Checklist:**

More robust color support detection in CLI

---

system/Helpers/filesystem_helper.php
tests/system/Helpers/FilesystemHelperTest.php

Support for removing hidden folders. See: #3015
**Checklist:**

Update delete_files() helper function

---

.github/workflows/docs_nightly.yml

Docs action still fails because it cannot `cp` the user guide folder. This adds the `actions/upload-artifact`. This is also referenced in [`ammaraskar/sphinx-action-test` default workflow](https://github.com/ammaraskar/sphinx-action-test/blob/master/.github/workflows/default.yml).
**Checklist:**

Add the upload artifact action

---

system/CLI/CLI.php
tests/system/CLI/CLITest.php

This PR fixes multicolored strings in CLI. See: #3173
**Checklist:**

Fix for multicolored strings in CLI

---

system/CLI/CLI.php

Running `CLITest` on Windows will likely fail on the `testWrap` method giving this error message:
Upon investigation, this was because `CLI::wrap` uses the `wordwrap` function and sets the third parameter into its default value of `\n` instead of the platform-specific `PHP_EOL`. This PR adds that.
**Checklist:**

Use explicit 'PHP_EOL' in wordwrap

---

system/CLI/CLI.php

Windows starting Win10 has support for VT100, thus it can handle nicely CSI sequences such as Erase in Display. This PR adds an additional check to `CLI::clearScreen` if Windows has VT100 support. Otherwise, it will default to the 40 new lines.
**Checklist:**

Improve CLI clear screen

---

system/CLI/CLI.php
tests/system/CLI/CLITest.php

Refactor color support detection in CLI. Move detection in `CLI::init` rather than on every call to `CLI::color`.
**Checklist:**

Refactor color detection in CLI

---

system/Images/Handlers/GDHandler.php
system/Images/Handlers/ImageMagickHandler.php
system/Images/Image.php
system/Language/en/Images.php

Support webp image in Image Manipulation Class
**Checklist:**
**Notes**

Add webp support to Image Manipulation Class

---

system/HTTP/CURLRequest.php

Following RFC 7230, CURL requests currently set the `Content-Length` header to `0` for every POST and PUT request, to make sure it is present. This is overwritten by the actual length for `application/x-www-form-urlencoded` requests, but left in place for `multipart/form-data` which causes some servers to close the connection early (since 0 bytes are already done).
This PR makes the `0` setting conditional on the presence of `multipart` data, so the native CURL client can set the actual `Content-Length` automatically.
**Checklist:**

Bugfix: Multipart Content-Length

---

admin/framework/composer.json
admin/module/composer.json
admin/starter/composer.json
composer.json

This repo holds the master copies of **composer.json** for the other CodeIgniter 4 repositories and project launchers. A few fo them have become out of sync. This PR cleans them up and updates versions and names to be consistent.
Issues addressed:
* Incorrect project name for **framework**
* Missing `dev` requirements added since last release (`faker`, `predis`)
* Missing script command "test"
* Inconsistent PHPUnit version scheme (`8.5.*` standardized to `^8.5`)
* Inconsistent tabs/spaces standardized to tabs
**Checklist:**

Refresh Composer files

---

system/Language/en/Email.php
system/Language/en/HTTP.php
system/Language/en/Images.php

First noticed when sending an email using the Email class, a few of the language strings in System/Language/en/*.php use an argtype of "string" which isn't valid in the PHP MessageFormatter class. This causes an error to be logged, or in a production environment, an error to be shown and the script halted. Removing this argType (leaving it undefined) fixes this completely.
There was also a typo in System/Language/en/Images.php in the same place (closing bracket instead of a closing brace) which I fixed at the same time.

ArgType 'String' is not valid in MessageFormatter class (fixes #3191)

---

user_guide_src/source/models/model.rst

On validation example, closing parenthesis missed
**Checklist:**

Add closing parenthesis

---

system/Test/FeatureTestTrait.php

Using `FeatureTestCase::get('/')` currently results in a URI of `//` due to an extra slash in the URI. This resolves fine during auto-routing but circumvents explicit route definitions such as `$routes->get('/', 'Foo::index');`.
This PR ensures the slashes are correct going into the URI regardless of `baseUrl` and `$path`.
**Checklist:**

Fix extra slash in URI

---

system/CLI/CLI.php
system/HTTP/CLIRequest.php
tests/system/CLI/CLITest.php
tests/system/HTTP/CLIRequestTest.php

This PR fixes the use of strings with dashes in CLI.
See: #3205
**Checklist:**

Allow dashes in the CLI segment

---

tests/system/Filters/FiltersTest.php

Added test for filter with empty array except. Use dataprovider as it will result with same except data found. By this, Filters class will have 100% test coverage.
**Checklist:**

add test for Filters with empty except

---

system/Router/RouteCollection.php

use `in_array()` instead for check `$this->currentSubdomain` inside `$subdomains`
**Checklist:**

remove unnecessary foreach in RouteCollection::checkSubdomains()

---

system/Database/BaseConnection.php
system/Database/ConnectionInterface.php
system/Model.php

This PR fixes a bug regarding the method used to get the database error. All DB drivers use `error()` method but in our interface, we had `getError()` which wasn't really used anywhere except for the `Model` class. 
See: #3204
**Checklist:**

Fix for getting database error

---

system/Test/CIDatabaseTestCase.php
system/Test/Fabricator.php
tests/system/Database/Live/FabricatorLiveTest.php
tests/system/Test/FabricatorTest.php
user_guide_src/source/testing/fabricator.rst

Adds counters for table items created by `Fabricator` to assist with simulated environments that have cross-referenced tables. *See the updated User Guide for example.*
**Checklist:**

Add Fabricator counts

---

system/Database/SQLite3/Builder.php
system/Database/SQLite3/Connection.php

This PR fixes `escapeChar` for the SQLite database. The `escapeChar` variable was placed in the wrong file. Incorrect escape char may cause unpredictable behavior in some cases.
**Checklist:**

SQLite3 escapeChar fix

---

.gitignore

Since we are ignoring sqlite DBs inside the `writable` folder, might as well ignore db files inside folders within the `writable`.
**Checklist:**

Allow ignoring *.db inside folders

---

system/Model.php

I add check that $data->{$primaryKey} is set, before add it to $data. Otherwise we get error on insert:
> pg_query(): Query failed: ERROR: null value in column "id" violates not-null constraint
because sql:
> INSERT INTO table (key, id) VALUES('value', NULL)

Fix insert Entity object on postgres

---

.github/workflows/docs_nightly.yml

In [comment to #3167 ](https://github.com/codeigniter4/CodeIgniter4/pull/3167#issuecomment-653716546), docs still fails the build process. Done a little checking and found that we used the build path as `_build` instead of `build` used in the `Makefile`.
Checked this locally for a green build: https://github.com/paulbalandan/CodeIgniter4/actions/runs/157521660
**Checklist:**

Remove underscore in UG build path

---

.github/workflows/apidocs-action.yml
admin/apibot

Adds the action to update API docs. ~~I have made this barely working up to `Make the new API docs` step. The deploy step fails for the username. Perhaps it is because I don't have credentials to push to `codeigniter4/api` in my testing.~~
~~Another is the use of the phar file. I'm more inclined to download the phar file per run rather than maintain the phar in the codebase so as to save disk space. But, I cannot make the download through curl successful. But if you think otherwise, it's fine.~~
After a series of runs, had finally made this turn green.
[Workflow run](https://github.com/paulbalandan/CodeIgniter4/actions/runs/157498787)
[API push](https://github.com/paulbalandan/api)
**Checklist:**

Add apidocs action

---

system/Pager/Pager.php
tests/system/Pager/PagerTest.php

This PR fixes lack of casting for `currentPage` when using segments.
See: https://github.com/codeigniter4/CodeIgniter4/pull/3194#issuecomment-653206930
**Checklist:**

Cast currentPage value to integer in Pager class

---

system/Test/CIDatabaseTestCase.php
user_guide_src/source/testing/database.rst

Changes `CIDatabaseTestCase` to run migrations regardless of `$refresh` status. This enables consecutive tests to set up the database without wiping it between tests, and minimizes failures from calling `seed()` where the migrations aren't in place.
This PR also exposes two new methods (used by `setUp()`) to let developers manipulate the database state on demand: `regressDatabase()` and `migrateDatabase()`.
User Guide updated with new functionality, and corrected a few mistakes left from old passes.
Ref. https://forum.codeigniter.com/thread-76921.html
**Checklist:**

DatabaseTestCase migrations

---

system/Helpers/filesystem_helper.php

Replace `Exception` with `Throwable` in catch blocks of other filesystem helpers. Others are using `Throwable` while these are not. Seems odd to me.
**Checklist:**

Use Throwable in catch block of filesystem helper

---

system/CLI/CLI.php

Since `CLI::error` uses `STDERR` as stream, this PR attempts to check if the stream supports terminal colors by modifying the `$isColored` variable used by `CLI::color`. Afterwards, this returns the variable to its previous state.
**Checklist:**

Check color support for STDERR for CLI::error

---

.github/workflows/apidocs-action.yml

In [#3183 (comment)](https://github.com/codeigniter4/CodeIgniter4/pull/3183#issuecomment-653798106), the action exits on `Download phpDocumentor` step with code 23. I must admit that there was an oversight when I copied the working version of the action in my test branch to that PR branch. I have overlooked adding `cd ./source` before calling `curl`.
Green build is on this PR's first commit.
[Test fix for apidocs locally](https://github.com/paulbalandan/CodeIgniter4/actions/runs/157961164)
**Checklist:**

Fix 'exit code 23' in apidocs action

---

system/Helpers/form_helper.php
tests/system/Helpers/FormHelperTest.php

This PR fixes `set_checkbox()` and `set_radio()` when the `$default` parameter is set to `true`.
See: #3228 and https://github.com/codeigniter4/CodeIgniter4/pull/2729#commitcomment-39947798
**Checklist:**

Fix set_checkbox() and set_radio() when default is set to true

---

system/Database/BaseBuilder.php
system/Model.php
tests/system/Database/Live/ModelTest.php

This PR fixes incorrect handling of result objects in the Model class.
Ref: https://github.com/codeigniter4/CodeIgniter4/issues/3204#issuecomment-653521556
**Checklist:**

Fix result object handling in Model class

---

system/Files/File.php
tests/system/Files/FileTest.php

more test `Files\File` class, for `getSizeByUnit('b')`. 
For `function_exists('finfo_open')` check in `getMimeType()` function. I added `@codeCoverageIgnoreStart` and `@codeCoverageIgnoreEnd` as will not never hit in tests.
By this, the `Files\File` class will have 100% test coverage.
**Checklist:**

more test Files\File class

---

.gitignore

Since we removed cilexer as dependency in #2671 , I updated `.gitignore` to remove that also.
**Checklist:**

Remove cilexer from gitignore

---

system/CLI/CLI.php

This PR fixes `CLI::validate()` when field value in `prompt()` uses dot sign.
Ref: #3233
**Checklist:**

Fix CLI::validate() usage when using dot sign

---

.github/workflows/apidocs-action.yml

Currently, `apidocs-action` runs on every push to `develop` regardless if there are changes to system files. So this PR adds a `paths` to the action's syntax. This is consistent with our `phpdoc.dist.xml` which transforms only files in the `system` directory.
**Checklist:**

Run apidocs action only when system files are changed

---

user_guide_src/source/dbmgmt/migration.rst

Syntax fixes for `migration.rst`, fixing #3243 along the way.
**Checklist:**

Syntax fix for migration.rst

---

system/Test/FeatureTestTrait.php

`CodeIgniter::handleRequest()` uses the shared `Filters` service to determine which filters to run for a particular route. The problem is that between feature tests this service remains, so different routes may actually run or not run filters they should.
This PR implements a bit of a hack to reset just the Filters service before making a feature test call. If other services turn out to have similar carry-over baggage it might make sense to have some way of doing selective service resets.
**Checklist:**

Reset Filters between feature tests

---

system/CLI/BaseCommand.php
system/CLI/CLI.php
system/CLI/CommandRunner.php
system/CLI/Commands.php
system/Common.php
system/Config/Services.php
tests/system/CLI/CommandRunnerTest.php
tests/system/Commands/CommandClassTest.php
tests/system/Commands/CommandsTest.php
user_guide_src/source/cli/cli_commands.rst

- Refactored CommandRunner to bring all logic out to its own class.
- added new `command` common helper function to allow calling other commands programatically.
- Updated CLI class to be able to handle being ran when NOT on the cli. Will echo out the content instead.

Add ability to call commands programatically.

---

app/Config/Images.php
system/Config/Services.php
system/Images/Handlers/BaseHandler.php
system/Images/Handlers/GDHandler.php
system/Images/Handlers/ImageMagickHandler.php
system/Images/Image.php
system/Images/ImageHandlerInterface.php

Fixes doc blocks of the Images library. Basis for this was the actual usage.
Fixes #3249 too.
**Checklist:**

Fix PHPDocBlock of Images library

---

system/Model.php
tests/system/Database/Live/ModelTest.php
user_guide_src/source/models/model.rst

This PR adds additional functionality to `Model` to allow/deny callbacks via a property (`$allowCallbacks`) or a per-execution method (`allowCallbacks(bool)`). This will help for testing, for extending models, or for unique situations where a developer needs a "safe mode" of model execution.
**Checklist:**

Implement model callback overrides

---

system/Test/Fabricator.php
tests/system/Test/FabricatorTest.php

When I expended `Fabricator` to allow non-framework models (https://github.com/codeigniter4/CodeIgniter4/commit/e93fcce48207ef8735e44f9f59123302fbb13769) I removed the exception thrown for an invalid model. This was a little too lenient as now `model()` can return `null` yet the fabricator instance remains intact, causing weird errors when using it that are hard to track down.
This PR ensures that `Fabricator` receives input that is valid for `model()`, throwing otherwise. Also bonus: a test.
**Checklist:**

Add Fabricator model error

---

app/Language/en/Validation.php
system/Autoloader/FileLocator.php
system/Language/Language.php
tests/system/Autoloader/FileLocatorTest.php

Alternative of #3126 to allow override existing translation validation.
**Checklist:**

Fixes #3125 : add ability to override existing translation en in system language from App

---

system/Commands/Database/CreateSeeder.php
system/Language/en/Seed.php

Add seed command generation
**Checklist:**

Feature seed command

---

system/CLI/CLI.php
tests/system/CLI/CLITest.php

Put `@codeCoverageIgnore` flags in CLI where testing is impossible or not yet possible, and also update test to increase coverage.
**Checklist:**

PHPUnit-annotate untestable code in CLI

---

app/Config/Honeypot.php
system/Honeypot/Honeypot.php

If the CSP policy is on, the style wouldn't work. So if the project use Bootstrap 4 or Bootstrap 3, it will be better to add thes classes.

Hide in bootstrap4

---

app/Config/Honeypot.php
system/Honeypot/Honeypot.php
tests/system/Honeypot/HoneypotTest.php

Use named variable in honeypot container and some additional tests.
**Checklist:**

Use named variable in honeypot container

---

system/Throttle/Throttler.php

While I was structuring an example to compose my book, I found that even if I correctly set the parameters for the `check()` method, a request was always executed more than the defined limit.
This was because when checking for the existence of the cache (`($tokens = $this->cache->get($tokenName)) === null`) if it was null, `true` was returned, and just created the cache, without start the count, which always allowed one more request, because only the next time the counter would start.
The `return true` was removed in this check and in checking the amount of tokens it was adjusted to `$tokens> = 0`.
After these changes, the limit defined in `check` started to be applied successfully.
**Checklist:**

Bug fix in Throttler class check validation

---

system/Images/Handlers/GDHandler.php
system/Images/Handlers/ImageMagickHandler.php
tests/system/Images/GDHandlerTest.php
tests/system/Images/ImageMagickHandlerTest.php

This PR fixes a bug when `$target` parameter in the `save()` method is `null`. We also take into consideration the `$quality` parameter for every case.
**Checklist:**

Fix Image::save() when target value is null

---

system/HTTP/CURLRequest.php
tests/system/HTTP/CURLRequestTest.php

This PR fixes "HTTP/1.1 100 Continue" header handling. 
Optional headers are allowed with 1xx statuses: https://tools.ietf.org/html/rfc2616#section-10.1
Ref: #3261
**Checklist:**

Fix "100 Continue" header handling in CURLRequest class

---

system/Autoloader/FileLocator.php

optimize FileLocator autoloader : use foreach instead of for with count when possible

---

system/Router/RouteCollection.php

optimize RouteCollection : use foreach instead of for with count when possible

---

system/CLI/BaseCommand.php
system/CLI/CommandRunner.php
system/CLI/Commands.php
system/CLI/Exceptions/CLIException.php

Fixes PHPDoc compilation errors for the CLI lib.
**Checklist:**

Fix PHPDocs for CLI

---

system/Router/Exceptions/RedirectException.php
system/Router/Exceptions/RouterException.php
system/Router/RouteCollection.php

Fix PHPDoc compilation errors for Router lib.
**Checklist:**

Fix PHPDocs for Router

---

system/HTTP/ContentSecurityPolicy.php
system/HTTP/DownloadResponse.php
system/HTTP/Exceptions/HTTPException.php
system/HTTP/Negotiate.php
system/HTTP/Response.php

Fix PHPDoc compilation errors for HTTP lib.
Most of the errors for the lib are the parse errors on the `?` nullable typehint which PHPDoc v2 can't handle yet. Since we have given a default value of `null` to these affected parameters and similar codes within the codebase remove the `?` typehint, I also removed it as temporary fix.
**Checklist:**

Fix PHPDocs for HTTP

---

system/Common.php
system/HTTP/URI.php
tests/system/HTTP/URITest.php

Fix for force_https() function

---

system/Database/BaseBuilder.php

optimize Database BaseBuilder : use foreach instead of for with count when possible

---

system/Database/MySQLi/Result.php
system/Database/Postgre/Result.php
system/Database/SQLite3/Result.php

As per pull request
https://github.com/codeigniter4/CodeIgniter4/pull/3287
added field type name.
had to redo it as I had to re-fork the repo and that broke the previous pull request.
Will return NULL if mapped field type name not found
the DB version of the type returned by driver is stored in the type column
Where applicable length is stored or made equal to max_length as in for example MySQL the max_length is based on
the data returned and not the DB schema where length is closer to the truth but still not 100%
cant think of a alternative that wont be affect the performance of the procedure. Is a need if want to build schema
from this data in the future
**Checklist:**

FieldData -> add typeName field and length field 

---

tests/system/CLI/CommandRunnerTest.php

By this, `CLI`'s CommandRunner class will have 100% test coverage.
**Checklist:**

add test for CommandRunner::_remap() with empty first params

---

system/Router/Router.php

reduce repetitive getDefaultNamespace() and controllerName() function call in Router

---

system/Common.php

when https:// is present in a defined base URL and a user accesses the site on on an insecure protocol, it would not force them onto secure.
just because the baseURL defines the protocol as https the user isn't necessarily forced onto https. This forces the user onto https.
**Checklist:**

force_https didn’t force https

---

system/Commands/Cache/ClearCache.php
tests/system/Commands/ClearCacheTest.php

Implements a new command `cache:clear` that will destroy all content on the current cache from the CLI.

New command: cache:clear

---

system/Helpers/number_helper.php
system/Helpers/url_helper.php

Replace \CodeIgniter\Config\Services with \Config\Services

count on \Config\Services

---

app/Config/Format.php
system/Format/JSONFormatter.php
system/Format/XMLFormatter.php

linked to 
https://github.com/codeigniter4/CodeIgniter4/pull/3286
This allows encoding to make numeric data more true to its type (not enclose them with "", making the receiving system identify
the types easier.
Note making the options variable configurable might be handy in the future depending on the needs of the users
people they interface with they might need additional options added here
**Checklist:**

add JSON_NUMERIC_CHECK to json encode options

---

system/Filters/CSRF.php
system/Filters/DebugToolbar.php
system/Filters/FilterInterface.php
system/Filters/Filters.php
system/Filters/Honeypot.php
tests/system/Filters/FiltersTest.php
tests/system/Filters/fixtures/GoogleCurious.php
tests/system/Filters/fixtures/GoogleEmpty.php
tests/system/Filters/fixtures/GoogleMe.php
tests/system/Filters/fixtures/GoogleYou.php
tests/system/Filters/fixtures/Multiple1.php
tests/system/Filters/fixtures/Multiple2.php
tests/system/Filters/fixtures/Role.php
user_guide_src/source/changelogs/v4.0.4.rst
user_guide_src/source/incoming/filters.rst
user_guide_src/source/incoming/routing.rst
user_guide_src/source/libraries/throttler.rst

Fixing #3216 by changing the FilterInterface::after() and before() to contain the arguments from the routing setup.
Updating core classes implementing FilterInterface, tests and docs.
**Checklist:**

Pass filter arguments to after() and before() methods

---

system/Test/DOMParser.php
tests/system/Test/DOMParserTest.php

Fixes #3319 add multibyte support on DOMParser::see()

---

system/Debug/Toolbar/Views/toolbar.css

Image width debug-bar has conflict with third party css template
Image in debug-bar conflict with css img width 100%.
So it must defined self with !important attribute
**Checklist:**
**Notes**

Image width debug-bar has conflict

---

system/CLI/CLI.php

Use the negated if condition for `CLI::fwrite` to achieve 100% test coverage for the class.
**Checklist:**

Reverse if condition in CLI::fwrite

---

system/Autoloader/Autoloader.php

Fix PHPDoc compilation error of Autoloader.
**Checklist:**

Fix PHPDoc for Autoloader

---

user_guide_src/source/installation/upgrade_404.rst
user_guide_src/source/installation/upgrading.rst

Added clear upgrade instructions to 4.0.4 docs

---

user_guide_src/source/models/model.rst

Minute changes to the section on Model Events. 
Since the $data to beforeDelete and afterDelete is the same, the table was compacted. [ci skip]
**Checklist:**

Cleaned up model docs

---

system/Model.php
tests/_support/Models/EventModel.php
tests/system/Database/Live/ModelTest.php
user_guide_src/source/models/model.rst

This one grew a bit. Original intent was to define the `beforeModel` callback event. That's done but I also discovered I had a logic error with `allowCallbacks` resetting during `trigger()`, because most (now all) methods that use triggers actually call `trigger()` twice - fixed. I discovered a Model test that should not have been passing (`db_job` is not a valid table) - fixed. And also there were no tests for `beforeDelete` - added.
**Checklist:**

Model beforeFind

---

public/.htaccess

When using /$1 it doesn't prepend RewriteBase to the uri, so going to /sub/controller/ will redirect to /controller instead of /sub/controller

Make Redirect trailing slashes redirect with base

---

system/Common.php
tests/system/CommonFunctionsTest.php

Use a common function `clean_path` as a means for nicer looking output instead of defining it as a method for class that needs it, e.g. `Exceptions`, `Logger`, `BaseCollector`, etc. With this, we can dispense use of redundant methods like `Exceptions::cleanPath` in favor of a global function.
**Checklist:**

New common function: clean_path

---

app/Views/errors/cli/error_exception.php

Refactor and improve the exception output for the terminal.
Before:
After:
**Checklist:**

Refactor and beautify error_exception.php for CLI

---

.gitignore
system/Commands/Housekeeping/ClearDebugbar.php
tests/system/Commands/ClearDebugbarTest.php

Adds the `debugbar:clear` command to help devs wanting to keep their `debugbar` directory tidy.
https://forum.codeigniter.com/thread-75733.html
**Checklist:**

New command: 'debugbar:clear'

---

system/Images/Handlers/GDHandler.php

While trying to reproduce #3356 , I encountered an `ErrorException: Undefined offset 2` using the details provided. This was because, the user was using the shorthand hex format `'color' => '#fff'` so when that was split into 3 groups of 2, index 2 was missing. This PR changes shorthand hex `fff` to its long form `ffffff`.
**Checklist:**

Account for shorthand hex format in GDHandler::textOverlay

---

user_guide_src/source/database/configuration.rst
user_guide_src/source/database/examples.rst
user_guide_src/source/incoming/routing.rst
user_guide_src/source/outgoing/response.rst
user_guide_src/source/outgoing/view_parser.rst
user_guide_src/source/outgoing/view_renderer.rst

Remove excess close brace in optional parameters.
Add missing colon for return type.
Add formatted note.
Change directory name config into Config.
Format file location as bold.

Remove close brace, add missing colon and text format

---

system/Debug/Toolbar/Views/_config.tpl

`Timezone` is a single word. It is not written `TimeZone`.
**Checklist:**

Timezone is a single word

---

system/Entity.php
user_guide_src/source/changelogs/v4.0.5.rst

When we declare class properties for Entity class then `__set()` method won't be called.
> __set() is run when writing data to inaccessible (protected or private) or non-existing properties
See: #3368
**Checklist:**

Fix fill() method in Entity class

---

system/Router/RouteCollection.php

at RouteCollection::fillRouteParams()
**Checklist:**

optimize RouteCollection: remove unnecessary strpos check when preg_match not match

---

system/Common.php

The `env()` common function has a different order of searching environment variables as compared with `DotEnv` and `BaseConfig`. The latter two searches in the following order: `$_ENV, $_SERVER, getenv`. While for env() it searches this way: `getenv, $_ENV, $_SERVER`. 
While this may be trivial for some, this may impact Windows systems with regard to resolving binary strings in the environment. Pending resolutions of PRs #3361 and #3362, this may affect Windows users getting the encryption key via `env('encryption.key')` and later will get an encryption failed error because it did not match with the configured `encryption.key` in `.env` file.
**Checklist:**

Fix env search order

---

system/CLI/Console.php

I know it is a bit of nitpicking but I always get confused why my local time is different from server time. I'm suggesting putting a UTC offset to the server time printed by spark.
**Checklist:**

Add UTC offset to spark header

---

system/HTTP/CURLRequest.php
tests/system/HTTP/CURLRequestTest.php

CURLRequest library makes a curl request and parse the result to set headers and body content to the correct objects. This parsing checks the first double carriage return and put the first part of the curl result as headers and the rest as body.
Problem is when using digest auth we get 2 headers in the curl response causing response headers being falsy and body containing a header.
This pull request handle this case by skipping the first headers generated by the first digest http call and start splitting for body and headers at the second double carriage return when having a successful digest auth.
Forum threads here : https://forum.codeigniter.com/thread-77046.html
**Checklist:**

Bug: CURLRequest lib doesn't set correct headers with digest auth

---

system/Config/DotEnv.php
tests/system/Config/DotEnvTest.php
user_guide_src/source/changelogs/index.rst
user_guide_src/source/changelogs/v4.0.5.rst

Per comment by the php maintainer in my bug report [here](https://bugs.php.net/bug.php?id=79875), they presented two advice in properly dealing with binary strings in the environment. This applies only for Windows. So I'll be presenting two mutually-exclusive PRs for the CI4 maintainers to decide the appropriate approach.
This is the **first** alternative: **Do not pass binary strings to the environment variables.** `BaseConfig` already has a parser for the prefix handling so `DotEnv` can be relieved from that responsibility.
Result for DotEnvTest
```
PS C:\Users\P\Desktop\Web Dev\CodeIgniter4> vendor/bin/phpunit -v --filter DotEnvTest
PHPUnit 8.5.8 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.4.8 with Xdebug 2.9.4
Configuration: C:\Users\P\Desktop\Web …
```

DotEnv: No binary strings to environment variables

---

system/Database/MySQLi/Connection.php

Throw correct exceptin type as per function comments
Was linked to this pull request
https://github.com/codeigniter4/CodeIgniter4/pull/3364
but had a fork/git version issue and redid fork and made sure develop branch is now in line
**Checklist:**

mysql connection throw correct  Exception type as per function comments

---

app/Views/errors/cli/error_exception.php

Differentiate empty array from a nonempty array in printing backtrace's `args`.
**Checklist:**

Differentiate empty array

---

tests/_support/Commands/InvalidCommand.php

By this, `CLI\Commands` class will have 100% test coverage.
**Checklist:**

add fixture class for Invalid Command class that throws \ReflectionException on Commands::discoverCommands()

---

system/CLI/CLI.php
tests/system/CLI/CLITest.php

#3208 fixed #3205 with regard to resolving dashes within CLI segments. However, if we have an option like `-opt-in` then `CLI::getOptions` will give `optin` as the key, removing the dash in between.
**Checklist:**

Allow dashes within CLI options

---

user_guide_src/source/libraries/uploaded_files.rst

Added "\" to code example throw new \RuntimeException... 
I copied the code block to test uploading files and got a Class not found error.  After not being able to determine the cause, I thought of adding the "\" which I understand has to do with namespace protocol.  Hope this is right!

Small correction in example code

---

system/Test/FeatureTestCase.php
system/Test/FeatureTestTrait.php

When you develop a protected api, sometimes you need to send tokens in the request header to authenticate that you can use this api. So you can create a filter that verifies that field in the header of the request.
When you want to test this API, with FeatureTestCase, you can't because it doesn't have the option to add headers to the order.
So I added this method, `withHeaders`, which before submitting the order, inserts custom headers.
**Checklist:**

Allow to customize the request's headers in FeatureTestCase

---

user_guide_src/source/installation/index.rst

By sort menu with `composer` first, it may make people more use composer. Manual composer make some more and more questions like : got error `undefined function locale_set_default` because new user don't read the requirement. via composer, the error for it is more verbose : ext-intl must be enabled.
**Checklist:**

[ci skip] prefer composer installation over manual in menu documentation

---

system/HTTP/CLIRequest.php
tests/system/HTTP/CLIRequestTest.php

Sync `CLIRequest::parseCommand` with recent changes in `CLI::parseCommandLine` (#3398) and also align it with `CLI::parseCommandLine`'s current behavior, see `CLITest::testParseCommandMixed`.
**Checklist:**

Sync CLIRequest::parseCommand

---

system/Autoloader/Autoloader.php
tests/system/Autoloader/AutoloaderTest.php

The `loadLegacy()` function was always called in `Autoloader::loadClass()` function for just normal `Home` Controller accessing `/` page, while there is no legacy class. /cc @paulbalandan if you can verify.
Tested in MacOS.
**Checklist:**

Fixes Autoloader::loadLegacy() always called

---

app/Config/Encryption.php
env
system/Encryption/EncrypterInterface.php
system/Encryption/Encryption.php
system/Encryption/Handlers/BaseHandler.php
system/Encryption/Handlers/OpenSSLHandler.php

Make `HMAC digest` configurable through `Config\Encryption` or through `.env` file. Also optimized some code in the Encryption library.
**Checklist:**

Make encryption HMAC digest configurable

---

tests/system/HTTP/RedirectResponseTest.php

Added tests for `withHeaders()` and `withCookies()` with empty headers and empty cookies. By this, the `HTTP\RedirectResponse` will have 100% test coverage.
**Checklist:**

more tests for RedirectResponse class

---

system/Helpers/url_helper.php

mb_url_title()  function are not working correctly for Bengali language. So I fixed it. Now it's working.
I expect : মশিউর-রহমান-তন্ময়
It gives outputs me before: মশউর-রহমন-তনময
See it the sentence meaning are changed.
I solved this bug and fixed it.
**Checklist:**
- [√ ] Securely signed commits
- [√ ] Component(s) with PHPdocs
- [√ ] Conforms to style guide

mb_url_title are not working correctly

---

system/Email/Email.php
user_guide_src/source/libraries/email.rst

Making sure connection for email submissions to port 465 is always using implicit TLS as per RFC8314.
Updating docs to describe the differences between port 465 and 587 and why/when STARTTLS is required and the setting `$SMTPCrypto`.
Current implementation only enables TLSv1.0 for the upgrade after STARTTLS, this PR enables versions 1.0, 1.1 and 1.2.
**Checklist:**

Clearing up confusion with TLS and SSL in Email Library, fixes #3429

---

system/HTTP/RedirectResponse.php

```
$this->setCookie(
$cookie['name'],
$cookie['value'],
$cookie['expires'], //The expiration time will be double-counted
$cookie['domain'],
$cookie['path'],
'', // prefix
$cookie['secure'],
$cookie['httponly']
);
```

Fix $cookie['expires'] double calculation error

---

admin/starter/composer.json

The starter app is mostly installed via composer create-project. I think it is better to use composer autoload for it.
**Checklist:**

add app and app/Config to autoload composer.json for app starter

---

system/Helpers/url_helper.php
tests/system/Helpers/URLHelperTest.php
user_guide_src/source/changelogs/v4.0.5.rst
user_guide_src/source/helpers/url_helper.rst

This PR adds a URL helper function called `url_to()`.
I added a URL helper called `url_to()`. It creates absolute URLs based on controllers. I'm commonly using this function in basically all of my CodeIgniter projects. Here is an example:
```php
service('routes')->get('/welcome', 'Pages::welcome');
echo url_to('Pages::welcome'); # => http://example.com/welcome
service('routes')->get('/page/(:segment)', 'Pages::view/$1');
echo url_to('Pages::view', 'home'); # => http://example.com/page/home
```
It is meant to be used inside of views to generate links. The main advantage of this function is that you can change your routes later on, but not having to change your links across all your views.
This is the first time I'm contributing code to CodeIgniter, I hope I didn't miss …

Add url_to() URL helper function

---

system/CodeIgniter.php
system/Language/en/Core.php
tests/system/Language/LanguageTest.php

Reading through the forums, many users, especially those manual installation users, are complaining undefined functions, such as `locale_set_default`, which can be resolved by installing the required PHP extensions. I think if we can warn them beforehand that their systems are missing these extensions and enforce them to install these then we'll have fewer problems along the road. I think this is much better than suggesting to comment out those undefined functions.
**Checklist:**

Enforce platform requirements

---

user_guide_src/source/installation/running.rst

Fix CLI option error in user guide
It should be a `<space>` instead of `=`
**Checklist:**

Fix CLI option error in user guide

---

user_guide_src/source/testing/feature.rst

The function that works is assertSeeInField an not seeInField for the current version (Maybe this is the same for others functions)
**Checklist:**
**Notes**

Update to add insert and match the function name

---

admin/framework/.gitattributes
user_guide_src/source/installation/installing_composer.rst

With `.gitattributes`, when running `--prefer-dist` (mostly default implementation), we can get the something like this:
```
└─- vendor/codeigniter4
├── framework
├── license.txt
├── README.md
├── composer.json
├── license.txt
├── system
```
We can still get the full of framework structure in `vendor` directory with `--prefer-source`, documentation updated in `Upgrading` section in `Composer Installation` page.
**Checklist:**

add .gitattributes to admin/framework to allow --prefer-dist install only core framework

---

system/CLI/Console.php
system/Commands/Database/Migrate.php
system/Commands/Database/MigrateRefresh.php
system/Commands/Database/MigrateRollback.php
system/Commands/Database/MigrateStatus.php
system/Commands/Database/Seed.php

Currently, `CLI::parseCommandLine`, `CLIRequest::parseCommand`, and `command()` parses CLI options stripping away the beginning `-`. If we are making programmatic calls, we should do the same when providing the options.
**Checklist:**

Refactor use of $params

---

system/Model.php
tests/system/Database/Live/ModelTest.php

This PR adds support for Entities to `updateBatch()` method.
See: #3451
**Checklist:**

Add support for Entities to updateBatch() method

---

system/CLI/Console.php

Mini change. Change `Console`'s header color to `green` for comfort in dark terminals. IMHO, `blue` is an eye strain.
**Checklist:**

Change console header color

---

system/Database/BaseConnection.php
system/Database/Postgre/Connection.php

In the documentation, it is named "Postgre", while in the code, it named "postgre" lower case. This change ensure to make it consistent to use "Postgre" naming in PostgreSQL Connection's DBDriver property. 
Also, on **non case sensitive** operating system, it caused an issue when we can configure `.env` as lower "postgre" and when moving to **case sensitive** operating system, it got error class not found.
This patch fixed it.
**Checklist:**

Make PostgreSQL DBDriver consistent : using Postgre instead of postgre

---

user_guide_src/source/models/model.rst

#3450. Fix description of beforeUpdate/afterUpdate events in user guide. **id** is array of primary keys.
**Checklist:**

Fix description of beforeUpdate/afterUpdate events in user guide

---

system/Filters/Filters.php
tests/system/Filters/FiltersTest.php
user_guide_src/source/incoming/filters.rst

The `toolbar` filter should be run as the last one since in other case it can't register all things are happening in other filters.
See: #3470
**Checklist:**

Run the toolbar filter as the last one

---

system/CLI/CLI.php
tests/system/CLI/CLITest.php

Use `foreach()` in parsing, instead of relying on `$_SERVER['argc']`
**Checklist:**

Optimization: CLI parseCommandLine

---

system/CLI/Commands.php
system/Commands/Help.php
tests/system/Commands/CommandTest.php
tests/system/Commands/HelpCommandTest.php

We have made spark give suggestions when possible for inexistent commands but failed to account for cases when we use the `help` command to get info on a command, which can be inexistent too.
**Checklist:**

Fix help command on inexistent commands

---

system/Language/en/Validation.php
system/Validation/Rules.php
tests/system/Validation/RulesTest.php
user_guide_src/source/libraries/validation.rst

Per [#3462 (comment)](https://github.com/codeigniter4/CodeIgniter4/issues/3462#issuecomment-671363390), adds the `not_in_list` rule.
Fixes: #3462 
**Checklist:**

Add not_in_list rule

---

system/Common.php
tests/system/Commands/CommandTest.php

While making tests for my generators PR, I've noticed that we cannot pass in a multi-worded option value to `command()` simply because we are making an `explode` on the string input using the spaces. With this, `command('command -d "some value"')` will be broken into `array(0 => 'command', '-d' => '"some', 1 => 'value"')`, instead of the expected `array(0 => 'command', '-d' => 'some value')` just like how getopt will give it.
After searching the net, I came across this solution from Symfony's `StringInput::tokenize` which perfectly did the job right.
**Checklist:**

Make command() mimic getopt parsing

---

system/CLI/BaseCommand.php

While trying to induce an error in calling `php spark migrate` using incorrect DB credentials, I was expecting a good error message but instead received a `TypeError`.
```
[TypeError]
Argument 1 passed to CodeIgniter\CLI\BaseCommand::showError() must be an instance of Exception, instance of CodeIgniter\Database\Exceptions\DatabaseException given, called in C:\Users\P\Desktop\Web Dev\CodeIgniter4\system\Commands\Database\Migrate.php on line 143
at SYSTEMPATH\CLI\BaseCommand.php:166
```
`DatabaseException` is a subclass of `Error` so this does not pass the type hint. This PR changes the typehint to use the `Throwable` interface instead of the more specific `Exception`. This also changes the rendering to use the built-in pretty output of `error_exception.php`.
**Checklist:**

Use Throwable in BaseCommand::showError

---

system/Validation/Rules.php
tests/system/Validation/RulesTest.php

This PR adds support for nested params. Right now rules like `matches[nested.value]` are not supported.
See: #3492
**Checklist:**

Add support for nested params in matches/differs rules

---

system/Commands/Housekeeping/ClearLogs.php
tests/system/Commands/ClearLogsTest.php

Addition to the `Housekeeping` department, this command will automatically delete all logs files, just like how `debugbar:clear` deletes all debugbar.json files.
**Checklist:**

Add command 'logs:clear'

---

.github/workflows/static-analysis-check.yml

when merging to develop, it seems the static analysis didn't run. I updated it to use paths : 
```
- 'app/**'
- 'system/**'
```
**Checklist:**

Fixes paths to run static analysis check on develop and 4.1 branch

---

system/Autoloader/Autoloader.php
tests/system/Autoloader/AutoloaderTest.php
user_guide_src/source/changelogs/index.rst
user_guide_src/source/changelogs/v4.1.0.rst
user_guide_src/source/concepts/autoloader.rst

`Autoloader::loadLegacy()` method was previously used for migration non-namespaced classes transition to CodeIgniter v4. Since `4.1.0`, I think this can be removed.
**Checklist:**

4.1.0: remove Autoloader::loadLegacy() method

---

system/Model.php
user_guide_src/source/changelogs/v4.1.0.rst

I think for 4.1.0, deprecated `Model::fillPlaceholders` can be removed. 
**Checklist:**

4.1.0 : remove deprecated Model::fillPlaceholders()

---

system/Encryption/Encryption.php
system/Encryption/Exceptions/EncryptionException.php

Two things:
- `EncryptionException::forNoHandlerAvailable` is for to pass handler name, it was passed driver in `Encryption::__construct()`.
- `EncryptionException::forNoHandlerAvailable()` require `$handler` parameter, it was no parameter.
**Checklist:**

Fixes EncryptionException::forNoHandlerAvailable() handler parameter call

---

app/Config/Logger.php
tests/system/Commands/ClearLogsTest.php

Looking through the forums, I've realized that developers' dilemma of `Unable to connect to database` exceptions can be known its root cause by logging the errors also. The default is set to `3` which logs only critical errors and higher. This PR suggests increasing the threshold to `4` to make errors logged too.
**Checklist:**

Set default logging threshold to 4

---

system/Entity.php
tests/system/EntityTest.php
tests/system/View/ParserTest.php

Added boolean $deep parameter in toArray and toRawArray methods. This parameters allows casting inner custom and entity objects to array as well
Additionally added :
- Unit Tests
- Return Type Declaration for Entity Getters to avoid IDE errors
- Some Code Style Fixes
**Checklist:**

Codeigniter\Entity - Added $deep parameter in toArray and toRawArray

---

system/CLI/BaseCommand.php
system/CLI/GeneratorCommand.php
system/Commands/Generators/CreateCommand.php
system/Commands/Generators/CreateController.php
system/Commands/Generators/CreateEntity.php
system/Commands/Generators/CreateFilter.php
system/Commands/Generators/CreateModel.php
system/Commands/Generators/CreateScaffold.php
system/Commands/Generators/Views/command.tpl.php
system/Commands/Generators/Views/controller.tpl.php
system/Commands/Generators/Views/entity.tpl.php
system/Commands/Generators/Views/filter.tpl.php
system/Commands/Generators/Views/model.tpl.php
system/Language/en/CLI.php
tests/system/Commands/CreateCommandTest.php
tests/system/Commands/CreateControllerTest.php
tests/system/Commands/CreateEntityTest.php
tests/system/Commands/CreateFilterTest.php
tests/system/Commands/CreateModelTest.php
tests/system/Commands/CreateScaffoldTest.php
user_guide_src/source/cli/cli_commands.rst
user_guide_src/source/cli/cli_generators.rst
user_guide_src/source/cli/index.rst

Add code generators that leverages the power of `GeneratorCommand`.
- `make:controller <name> [options]`
- `make:model <name> [options]`
- `make:entity <name> [options]`
- `make:scaffold <name> [options]`
- `make:command <name> [options]`
- `make:filter <name> [options]`
Tests are underway, but I would like to have a few feedback of additions or removals from current proposed.
Default property values are lifted from the respective parent class.
**Checklist:**

[Feature] Robust code scaffolder commands

---

system/Config/BaseService.php
system/Config/Services.php
user_guide_src/source/changelogs/v4.0.5.rst

Remove unneeded lines of code by:
- Switching to `??` where possible
- No `is_object` checks for nullable typehints
- Use Elvis operator where possible
- et al.
I have a failing test for `router` though I didn't touch that before:
```php
$routes  = $routes ?? static::routes();
// this line is missing in the original, causing the passed request object to be actually <null>,
// causing 'Undefined getMethod() on null' on CodeIgniter\Router\Router line 149.
// for fix, I added this line. but I don't know why Travis is not erring in here
$request = $request ?? static::request(); 
return new Router($routes, $request);
```
**Checklist:**

Optimize: Services

---

app/Config/Mimes.php

Fixes in `app/Config/Mimes.php`, after trim, null will always be string. I updated to compare with empty string.
```
php > var_dump(trim(strtolower(null)));
string(0) ""
```
**Checklist:**

Fixes change is_null after trim with empty string comparison

---

system/Session/Session.php

Use predefined `Session` class property values when it defined as fallback when passed config->propertyName value is null/not exists.
**Checklist:**

using predefined Session property values when config->propertyName null in Session  __construct

---

system/Entity.php
tests/system/EntityTest.php

There are couple of issues with the way datamap works 
- It keeps doubles the values original and mapped where only mapped should be kept
- If datamap is used on existing attribute it will not work properly as value is already processed through data map in the getter
- When unsetting the key we need to double check if there is not another map that uses the key in $to map as if unset it won't be accessible in the next loop
I've added the getSwappedEntity() method which returns the entity which is affected by all those issues. 
**Checklist:**

Codeigniter\Entity - Fix ToArray datamap

---

user_guide_src/source/dbmgmt/forge.rst

Adds a note about the third parameter to `Forge::dropTable()`
Fixes #2575

User Guide: Forge dropTable parameter

---

system/Security/Security.php

Use predefined Security class property values when it defined as fallback when passed config->propertyName value is null/not exists.
**Checklist:**

using predefined Security property values when config->{$propertyName} null/not exists in Security __construct

---

composer.json
system/HTTP/Response.php
system/I18n/Time.php

It seems new phpstan released https://github.com/phpstan/phpstan/releases/tag/0.12.40 that make we can clean up unneeded `// @phpstan-ignore-line` at 
-  `system/HTTP/Response.php` line 902
- `system/I18n/Time.php` line 560
after update to phpstan v0.12.40
**Checklist:**

Fix phpstan error notice after update to v0.12.40

---

system/Session/Session.php

Fix session class setcookie not getting renewed when using ajax and put expire date in the past.
**Checklist:**
**Notes**

Fix Session gets expired using AJAX with Session

---

system/Debug/Toolbar/Views/toolbar.js

This PR adds samesite attribute when setting cookies in the toolbar.js. I'm going with `Lex` since it's the most reasonable choice.
> Cookie “debug-bar-state” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute.
https://developer.mozilla.org/pl/docs/Web/HTTP/Headers/Set-Cookie/SameSite
**Checklist:**

Add samesite attribute for debug-bar related cookies

---

user_guide_src/source/database/query_builder.rst

Updates the `query_builder.rst`.
- Fixes #3551 
- Removes unnecessary or wrong whitespace.
- Use lowercase `true`, `false`, `null`
- Fixes some return types in class reference
- and others
**Checklist:**

Update query builder doc

---

.github/workflows/test-phpstan.yml
app/Config/Autoload.php
phpstan.neon
system/Config/AutoloadConfig.php
system/Config/View.php

Update `phpstan.neon`
- use 2-space indent since this is yaml
- add the rule `level` to parameters
- add `paths` to check to parameters
- `excludes_analyse` will now exclude all tpl files in generator commands' views
- all error views are excluded
- add `parallel.processTimeout` to parameters for running in local machines
- add missing `$psr4` and `$classmap` properties of `AutoloadConfig`. These will be overwritten by `Config\Autoload`'s similarly named properties.
- add missing `$filters` and `$plugins` properties of `CodeIgniter\Config\Views`. These will be overwritten by `Config\Views` similarly named properties.
**Checklist:**

Update phpstan.neon and resolve some errors

---

system/I18n/Time.php
tests/system/I18n/TimeTest.php

Fixes #3553 
Little side note on `__wakeup()`.
- Simple fix for the problem is just provide an empty `__wakeup` method to `Time` for the sake of overriding `DateTime::__wakeup()`. However, with that, we cannot initialize the parent, `DateTime`. With this fix, we can get an "equal" Time object (but not the "same" since they are not referencing to the same object).
Continuing on the controller code:
```php
{
// return view('welcome_message');
$web = new Web();
$web->url = 123;
$web->created_at = date('Y-m-d H:i:s');
var_dump($web->created_at);
$cache = Services::cache();
$cache->save('webname', $web, 300);
$web = $cache->get('webname');
var_dump($web->created_at);
}
```
we will get this:
```php
C:\Users\P\Desktop\Web …
```

Add __wakeup method to Time

---

system/CLI/BaseCommand.php
tests/_support/Commands/AppInfo.php
tests/system/Commands/HelpCommandTest.php
user_guide_src/source/changelogs/v4.0.5.rst

With the changes brought by #3435 , the method `BaseCommand::getPad` is not used anymore. I've checked for usage references within the codebase using VSCode and found none. This was because it was replaced by `setPad`. Since this is a public function, I'm proposing to deprecate this.
Also, with that PR's changes, some lines got uncovered by tests. So I've added a test for that.
**Checklist:**

Deprecate BaseCommand::getPad and add more tests

---

system/HTTP/RedirectResponse.php

Continuing on and closes #3279 
Additional:
- Removed unneeded `empty` check before `foreach` for arrays. `foreach` won't execute if passed array is empty.
**Checklist:**

Refactor RedirectResponse

---

.github/workflows/test-phpstan.yml
phpstan.neon

I used `build/phpstan` since `build/` is already ignored in `.gitignore` and is used by `phpunit`
**Checklist:**

Implement caching of phpstan result cache

---

system/Config/BaseService.php

`method_exists()` allow pass object to 1st parameter.
**Checklist:**

remove get_class() on method_exists

---

system/Test/ReflectionHelper.php

There is `is_object($obj)` check and its otherwise condition using `ReflectionClass`, that make it possible to pass a string parameter.
**Checklist:**

Allow string for parameter $obj in ReflectionHelper::getAccessibleRefProperty()

---

system/Test/FeatureTestTrait.php
tests/system/HomeTest.php

This change will allow us to not be constrained in using `FeatureTestTrait` within the context only of `FeatureResponse`. We can also use this on other test cases, like `CIUnitTestCase`. This also resolves phpstan's error "Ternary operation always return true."
**Checklist:**

Use null coalescing to routes resolution in FeatureTestTrait::call

---

app/Config/Format.php
system/API/ResponseTrait.php
system/Config/Services.php
system/Format/Format.php
system/HTTP/Response.php
system/Language/en/Format.php
system/RESTful/ResourceController.php
system/Test/FeatureResponse.php
system/Test/Mock/MockResourcePresenter.php
tests/system/Config/ServicesTest.php
tests/system/Format/FormatTest.php
tests/system/HTTP/ResponseTest.php
tests/system/Test/FeatureResponseTest.php
user_guide_src/source/changelogs/v4.0.5.rst

Closes #3149 .
I tried to pull that PR and continuing from that but when I rebased to latest develop I got merge conflicts. I am not yet adept in solving merge conflicts, even IDE-aided, so I opted for the long road. This PR also adds tests for the new class addition and new inserted function to `Services`.
**Checklist:**

Refactor Format class

---

system/Test/FeatureResponse.php
tests/system/Test/FeatureResponseTest.php

Fixes #3562 
Added an optional argument to `assertJSONFragment`, `bool $strict = false` to mimic `assertArraySubset`'s third param.
To demonstrate that this replacement mimics `assertArraySubset`, in the new test method, try the following locally. It should still pass:
```diff
- $this->feature->assertJSONFragment(['config' => 124]);
+ $this->assertArraySubset(['config' => 124], json_decode($this->feature->getJSON(), true));
- $this->feature->assertJSONFragment(['config' => '124'], true);
+ $this->assertArraySubset(['config' => '124'], json_decode($this->feature->getJSON(), true), true);
```
Then on the not strict test, adding `true` must fail the assert.
**Checklist:**

Fixes deprecation of assertArraySubset

---

system/Cache/Handlers/RedisHandler.php
system/Common.php
system/Database/BaseBuilder.php
system/Database/BaseConnection.php
system/Database/BaseResult.php
system/Database/BaseUtils.php
system/Database/Forge.php
system/Database/Postgre/Connection.php
system/Database/SQLite3/Result.php
system/Email/Email.php
system/Filters/Filters.php
system/HTTP/DownloadResponse.php
system/HTTP/IncomingRequest.php
system/Model.php
system/Session/Handlers/DatabaseHandler.php
system/Session/Handlers/FileHandler.php
system/Session/Handlers/MemcachedHandler.php
system/Session/Handlers/RedisHandler.php
system/Session/Session.php
system/Test/FeatureResponse.php
system/Validation/FormatRules.php

When there is already `return` or `throw`  or `continue` early in previous `if`, we can remove `else`.
**Checklist:**

remove `else` on return/throw/continue early

---

system/Debug/Toolbar/Collectors/Events.php

If event count > 1 and duration more than 1000 ms it's rise 
```
CRITICAL - 2020-09-01 10:54:24 --> A non well formed numeric value encountered
#0 vendor\codeigniter4\framework\system\Debug\Toolbar\Collectors\Events.php(155): CodeIgniter\Debug\Exceptions->errorHandler(8, 'A non well form...', 'E:\\progdev\\Proj...', 155, Array)
#1 vendor\codeigniter4\framework\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Events->display()
#2 vendor\codeigniter4\framework\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 vendor\codeigniter4\framework\system\Debug\Toolbar.php(353): CodeIgniter\Debug\Toolbar->run(1598946859.601, 4.642, Object(CodeIgniter\HTTP\IncomingRequest), …
```

Fix Toolbar event collector number formatting

---

system/Commands/Generators/CreateScaffold.php

Without the fallback, we'll get the Error `Undefined offset: 0`.
**Checklist:**

Allow fallback when make:scaffold's argument is missing

---

system/CLI/CLI.php
system/CLI/GeneratorCommand.php

I've noticed that `getSegment`'s code deducts 1 from the index parameter before checking which made me realize that it is one-based instead of zero-based. This PR updates `GeneratorCommand::getClassName()` to use that.
In retrospect, why was it that way?
**Checklist:**

Use CLI::getSegment(2) to refer to the first argument of generator command

---

system/Router/Router.php

Fix [#3591](https://github.com/codeigniter4/CodeIgniter4/issues/3591)
**Checklist:**

fix(Router): reset filter info before get defined filters

---

system/Autoloader/Autoloader.php
tests/system/Autoloader/AutoloaderTest.php

Mini refinements
- Ensure paths have correct ending directory separators.
- When removing namespaces, ensure the namespace is set.
- Add more tests to Autoloader and remove redundant test
**Checklist:**

Refinements to Autoloader

---

system/Helpers/url_helper.php
tests/system/Helpers/URLHelperTest.php

This PR fixes the `current_url()` helper function to correctly propagate the `baseURL` when working in the subfolder.
Fixes #3594
**Checklist:**

Fix current_url() helper function when working with subfolders

---

system/HTTP/CURLRequest.php
system/HTTP/Message.php
tests/system/HTTP/CURLRequestTest.php

This PR fix issue where the short HTTP protocol version is not acceptable.
Thanks to @JanZelenka for the regex update.
Fixes #3586
**Checklist:**

Make short HTTP protocol version acceptable

---

.github/workflows/test-phpstan.yml
admin/pre-commit

- Run actions only on main repo
- Add phpstan analysis to `precommit`
- Strictly check only for PHP files ending in `.php`. Will exclude `.phpcs`, `.php_cs`, etc.
- Run linting if there are PHP files to check
**Checklist:**

[DEV] Enhancements to dev workflows

---

system/HTTP/URI.php

Fixed `@param` at `URI::stripQuery(...$params)`, make  no need `// @phpstan-ignore-line` on `unset($this->query[$param]);`
**Checklist:**

Fix @param at URI::stripQuery(...$params)

---

system/HTTP/URI.php
system/Helpers/url_helper.php
tests/system/Helpers/URLHelperTest.php

This PR fixes some issues with `URI` class when `baseURL` contains a sub-folder.
Now we get the same results as when we would get when calling `Services::request()`. Before, the results were polluted with `baseURI` path.
Also fixes #3603
**Checklist:**

URI class update for better handling of URLs with sub-folders

---

system/CLI/GeneratorCommand.php
tests/_support/Commands/Foobar.php
tests/_support/Commands/LanguageCommand.php
tests/system/Commands/ConfigurableSortImportsTest.php

I am making a spark command that publishes a module's language files to userland or to other language folders. The problem is the method `GeneratorCommand::sortImports` is interfering with the file created.
Initially, the idea for the sort imports method is to automatically sort the class imports a class template is using before outputting the final product. This is not a problem if the file contains classes that uses class imports. For language files, however, we are using a return array with translations defined as index-value pairs. The `sortImports` algorithm checks for word matches starting with `use blah blah`, collects those matches, sorts them, then output them. If in the translation array I have the pairs:
```php
return [
'foo' => 'This one will use {0} on foo.', …
```

Allow GeneratorCommand's sortImports to be configurable

---

system/CLI/CLI.php
system/CLI/GeneratorCommand.php
system/Commands/Database/Migrate.php
system/Commands/Database/MigrateRefresh.php
system/Commands/Encryption/GenerateKey.php
system/Commands/Generators/CreateCommand.php
system/Commands/Generators/CreateController.php
system/Commands/Generators/CreateModel.php
system/Commands/Generators/CreateScaffold.php
system/Commands/Generators/MigrateCreate.php
system/Commands/Housekeeping/ClearLogs.php
system/Commands/Server/Serve.php
system/HTTP/CLIRequest.php
tests/system/CLI/CLITest.php
tests/system/HTTP/CLIRequestTest.php
user_guide_src/source/cli/cli_generators.rst
user_guide_src/source/cli/cli_request.rst

I just realized that we are unknowingly accepting options to be written either starting with `-` or `--`. This is because on trimming the options we are using `ltrim` which greedily trims the dashes. So:
```php
echo ltrim('-allow', '-'); // allow
echo ltrim('--allow', '-'); // allow
```
This PR suggests using the "longopts-style" for writing long options, i.e. using `--`. This change will not affect previous usages because of the `ltrim` above and `mb_strpos($arg, '-') === 0` will match for both `-` and `--`. Additionally, I intentionally did not change the unit tests for commands that uses `-` to show that it will still work as intended.
For `getOptionString`, I added optional parameters that will change the existing parsing to use the longopts style. It is default to …

Write console long options using '--'

---

system/Test/CIUnitTestCase.php
tests/system/Commands/ClearCacheTest.php

The default Cache driver is `FileHandler` which can create unwanted files on the local filesystem during testing, especially for the CLI user has permissions that differ from a web user. This PR adds a `mockCache()` method to `CIUnitTestCase` and includes it in the array of `setUpMethods` by default.
**Checklist:**

Use MockCache during testing

---

phpstan.neon
system/Commands/Database/MigrateStatus.php

If I have set the value of `APP_NAMESPACE` to a value other than the default `App`, then I would not want `App` to be listed in the `migrate:status` as it would be practically redundant with the value in `APP_NAMESPACE`.
**Checklist:**

Eliminate 'App' in migrate:status if different from APP_NAMESPACE

---

tests/_support/Database/Migrations/20160428212500_Create_test_tables.php

seem to work, it creates a constraint that is not autoinc
each time. By doing it the same way as the other databases
one can use it now as a autoinc and not get
not null errors when inserting data
This is how definition looks after change
Data is inserted with seeder still correctly
The table without auto inc looks like all the others did before change
**Checklist:**

Remove the autoinc logic as it dont

---

system/Commands/Database/MigrateStatus.php
system/Language/en/Migrations.php

For beautiful and more verbose output of `migrate:status`.
`Before`
`After`
**Checklist:**

Write migrate status in tabular format

---

system/Database/MigrationRunner.php
tests/system/Database/Migrations/MigrationRunnerTest.php
tests/system/Events/EventsTest.php
user_guide_src/source/extending/events.rst

Adds an event after running migration `latest` or `regress`.
**Checklist:**

Add post-migration event

---

composer.json
phpstan.neon.dist
qa-bootstrap.php
system/Commands/Server/Serve.php
system/Common.php
system/Config/AutoloadConfig.php
system/Debug/Exceptions.php
system/Log/Logger.php
system/Test/CIDatabaseTestCase.php
system/Test/bootstrap.php
user_guide_src/source/installation/running.rst

This PR adjusts our PHPUnit bootstrap file to work with PHPStan, and hopefully any other external code processor. Not only does this allow us to unify the process, but modules and projects should now be able to use the same one without needing to define their own.
**Checklist:**

Unify QA bootstrap files

---

system/HTTP/URI.php
tests/system/HTTP/URITest.php

This PR adds support for respecting `forceGlobalSecureRequests` config variable when using `current_url()` function.
Fixes #3648
**Checklist:**

Make current_url() function respect forceGlobalSecureRequests 

---

system/Model.php
tests/_support/Models/EventModel.php
tests/system/Database/Live/ModelTest.php
user_guide_src/source/models/model.rst

Currently the `beforeFind` and `afterFind` events can be triggered by three different methods, each of which has different data conditions which are difficult for the event recipient to parse. For example, if `$eventData['data']` contains an array is it an array of results or a single result array?
This PR defines "singletons" - model `find*` methods intended to return a single result array - and adds the boolean value to the event data. Additionally this adds the calling method to `trigger()`'s event data for `afterFind`, same as is currently available for `beforeFind`.
**Checklist:**

Clarify model find* event data

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/CountTest.php

This PR fixes the `countAllResults()` method when `DBPrefix` is defined and additionally we use `groupBy()` or `distinct()` method with the query.
Fixes #3651
A `DBPrefix` was always added again to the next query when the `countAllResults()` method was set to not reset the SELECT part.
**Checklist:**

Fix countAllResults() when DBPrefix is defined

---

system/Filters/Filters.php
tests/system/Filters/FiltersTest.php

In a new project I have defined `Config => app/Config/` in my `composer.json`'s `autoload.psr-4` so that phpstan will not complain later of undiscovered symbols. However, I am getting class redeclaration error for `Config\Filters`, particularly on the `discoverFilters` method of `CodeIgniter\Filters\Filters`.
This is because `Services::locator` will locate two `Config\Filters` in my case, 1) as defined by `Config\Autoload` and 2) as defined by Composer. Now, the discoverFilters method will just check if the path to the file is not equal to `APPPATH . 'Config/Filters.php`. Since the Composer one is a relative route usually having the `vendor` in its path, it will fail the check and will be `include`d. Since it is really identical to the main filter config, the PHP error will be thrown for …

Fix Filters' discoverFilters on class redeclaration

---

system/Pager/Pager.php
system/Pager/PagerInterface.php
tests/system/Pager/PagerTest.php

This PR implement getTotal() item on pager.
Example:
```php
$model = new SampleModel();
$data = $model->paginate();
$total = $model->pager->getTotal();
```
**Checklist:**

Implement getTotal item on pager

---

system/Security/Security.php

If CSRFExpire specifies 0, set 0 as it is.
fix: #3655
**Checklist:**

If CSRFExpire specifies 0, set 0 as it is

---

system/CodeIgniter.php
system/Log/Logger.php
system/Validation/Validation.php

phpstan 0.12.43 handle $_SESSION always exists check. ref https://github.com/phpstan/phpstan/releases/tag/0.12.43
**Checklist:**

phpstan update: no longer need ignore error on isset($_SESSION)

---

system/Commands/Cache/InfoCache.php
tests/system/Commands/InfoCacheTest.php

Command cache info to show cache in the current system.
Example: 
**Checklist:**

Command cache info to show cache in current system

---

phpstan.neon.dist
system/HTTP/Message.php

A number of `Message` methods have docblocks for `@return Message` which makes static analysis angry when a child class is returned. This PR switches to `$this` and specifies a `self` return type on the function. I also cleaned up the file a bit but nothing that would affect code.
**Checklist:**

Fix Message return types

---

system/Language/en/Cast.php
system/Language/en/Email.php
system/Language/en/Encryption.php
system/Language/en/Files.php
system/Language/en/RESTful.php
system/Language/en/View.php

Blank lines harmonised.
...I tried to find guidelines or some logic in the core files, but there it's not uniformly. But there it doesn't matter... 
To visually compare translation-files accross diffferent languages, it's helpful if each file has the same code style.

PHPDoc blocks unified

---

system/Helpers/url_helper.php

Addresses an issue where the tested path for `url_is()` could have inconsistent results based on preceding slashes.
The underlying issue should be addressed in #3672 but this will ensure `url_is()` works in the meantime, and should function as a general precaution against `URI` return values.
**Checklist:**

Normalize url_is test path

---

system/Commands/Cache/InfoCache.php
tests/system/Commands/InfoCacheTest.php

This command cache:info only supports the file cache handler.
Related discussion https://github.com/codeigniter4/CodeIgniter4/pull/3660#issuecomment-695786132
**Checklist:**

Cache command info only for file cache handler

---

admin/framework/phpunit.xml.dist
admin/module/phpunit.xml.dist
admin/starter/phpunit.xml.dist
phpunit.xml.dist
system/HTTP/URI.php
system/Helpers/url_helper.php
system/Test/ControllerTester.php
system/Test/Mock/MockAppConfig.php
system/Test/Mock/MockCLIConfig.php
system/Test/bootstrap.php
tests/system/API/ResponseTraitTest.php
tests/system/CLI/CommandRunnerTest.php
tests/system/CLI/ConsoleTest.php
tests/system/CodeIgniterTest.php
tests/system/CommonFunctionsTest.php
tests/system/HTTP/IncomingRequestTest.php
tests/system/HTTP/RedirectResponseTest.php
tests/system/HTTP/ResponseTest.php
tests/system/Helpers/URLHelperTest.php
tests/system/Validation/ValidationTest.php
user_guide_src/source/helpers/url_helper.rst
user_guide_src/source/installation/running.rst

This PR clarifies the requirement for a trailing slash on `baseURL` configuration. Most changes are updating tests to start with a base URL that uses a trailing slash. I also fixed a few places to try to make them a little more lenient when there is no trailing slash, and added more tests to detect errors due to base URL discrepancies.
**Checklist:**

Base URL trailing slash

---

system/Commands/Cache/ClearCache.php
system/Commands/Cache/InfoCache.php
tests/system/Commands/ClearCacheTest.php
tests/system/Commands/InfoCacheTest.php

- Adds file-level header docblocks to cache commands.
- Adds class-level docblocks.
- Adds test for uncovered lines
- Adds `// @codeCoverageIgnore` for untestable lines
- Removes unnecessary variables
**Checklist:**

Update cache commands

---

system/Config/BaseConfig.php
tests/_support/Config/TestRegistrar.php
tests/system/Config/BaseConfigTest.php
user_guide_src/source/general/configuration.rst

Currently `Registrar` discovery is disabled during testing. This is an attempt to reenable it. Also fixes a fair amount of missing and incorrect info on Registrars in the docs.
**Checklist:**

Enable Testing Registrars

---

system/Database/Exceptions/DatabaseException.php

`DatabaseException` intentionally has its own `ExceptionInterface` to allow catching database-specific errors. However, the `use` statement included on the `DatabaseException` class prevents it from using the namespaced version. Since `CodeIgniter\Database\Exceptions\ExceptionInterface` extends the core `ExceptionInterface` this should not break anything that was lumping those together, but this change will now allow catching database exceptions directly using the interface.
**Checklist:**

Remove erroneous interface reference

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/BaseTest.php
user_guide_src/source/database/query_builder.rst

It is a source of frequent confusion that the Query Builder cannot return the last insert ID, errors, or other data related to the database connection. Because $db is protected there is no way to access the database instance once you have instantiated a Builder. This adds a method to return the `ConnectionInterface` in use on a builder.
Supersedes #3697 because I realized that `ConnectionInterface` does not specific a `insertID()` method. Not sure if that is an oversight but this is a little more flexible anyways.
**Checklist:**

Builder Get Connection

---

system/Autoloader/FileLocator.php
system/Cache/Handlers/FileHandler.php
system/Files/File.php
system/HTTP/CURLRequest.php
system/Test/CIUnitTestCase.php

I'm a fan of virtual filesystems for testing (like vfsStream) but the biggest failure is always that `realpath()` fails to resolve resource stream references to a file. The framework has been made mostly "virtual-safe" but these are a few lingering references.
**Checklist:**

Failover realpath

---

composer.json
rector.php

Update to use rector/rector ^0.8, version 0.8.14 also enable Option::SKIP to allow skip check file(s)/directory(es) by rule.
**Checklist:**

update rector ^0.8

---

system/Controller.php

`helper()` already prefers an array, so unpacking the names with `foreach` is just a performance cost.
**Checklist:**

Controller Helpers

---

admin/framework/README.md
admin/starter/README.md

Clean up the following note : 
```
The user guide updating and deployment is a bit awkward at the moment, but we are working on it!
```
at admin/framework/README.md and admin/starter/README.md
**Checklist:**

[ci skip] remove awkward note at admin/framework/README.md and admin/starter/README.md

---

README.md

no need `?branch` in uri.
**Checklist:**

Fix PHPUnit status badge in readme

---

.github/workflows/test-phpunit.yml

Try make PHPUnit workflow faster.
**Checklist:**

Removing unused --dev and autoload on PHPUnit workflow

---

.github/workflows/test-phpunit.yml

Run composer update after composer remove --dev on PHPUnit workflow to make faster.
**Checklist:**

Run composer update after composer remove --dev on PHPUnit workflow

---

system/Autoloader/Autoloader.php

This issue arose with the Autoloader. I don't understand all the nuances of the difference but I thought I'd at least run it through the tests and see if anyone else here with more Autoloader experience had ideas.
See: https://github.com/phpstan/phpstan/issues/3907
**Checklist:**

Autoloader include

---

.gitattributes

When using the development branch as dependency for a module, or just even using in `appstarter` for catching up with the latest changes, the downloaded package is always "bloated" with regard to unnecessary files and folders. This PR attempts to clean up the distributable package (when using `--prefer-dist`) by putting in `.gitattributes` (through `export-ignore`) the "unusable" files.
**Checklist:**

Streamline gitattributes

---

system/Helpers/html_helper.php
tests/system/Helpers/HTMLHelperTest.php
user_guide_src/source/helpers/html_helper.rst

Adds an image helper function to create a data tag from a file path.
**Checklist:**

Add img_data() helper

---

system/Router/RouteCollection.php

This is useful to avoid IDE warnings as this param can be a closure or an array
**Checklist:**
- [ x] Securely signed commits
- [x ] Component(s) with PHPdocs
- [ x] Unit testing, with >80% coverage

Fix PHPDoc on RouteCollection / group

---

system/Controller.php
user_guide_src/source/changelogs/v4.0.5.rst

remove loadHelpers  method while it isn't used somewhere else, since we can use helper() method anywhere

Load helpers directly from the initController

---

user_guide_src/source/helpers/html_helper.rst

Fixes the lingering `unexpected unindent` warning of sphinx on the html helper doc.
**Checklist:**

Fix unexpected unindent

---

system/Database/SQLite3/Table.php

Resets the connection `dataCache` after SQLite modified table structures to ensure that the new structures are rediscovered. This is a bit of a "blast" fix but should be performance-safe because of when Forge is actually used.
Fixes #3752.
**Checklist:**

Reset data cache after SQLite3 table modifications

---

system/HTTP/Message.php
system/Validation/Validation.php
tests/system/HTTP/MessageTest.php
tests/system/Validation/ValidationTest.php

fixes #3719 
Adjusted Validation::withRequest so that it recognizes when the request is a json request and loads the data appropriately.
This allows someone who is building a JSON API to be able to validate their incoming JSON's using the Controller::validate function.
**Checklist:**

Load a JSON request into Validator 

---

public/index.php

I think `$pathsPath` can be removed and use its value to require directly.
**Checklist:**

clean up public/index.php : remove unneeded $pathsPath var

---

system/Database/Seeder.php
tests/system/Database/DatabaseSeederTest.php
user_guide_src/source/dbmgmt/seeds.rst

This attempts to hasten database live tests by extracting `Faker` instantiation from `Seeder`'s constructor to a new static method and using a static property so that it will persist across instances. I've added tests for uncovered lines.
My only worry for this is that the `use` statement for `Faker\Factory` may break if the library is not installed for manual installations. @samsonasik I've tried using `@noRector` but still it imports them. Any ideas?
**Checklist:**

Don't instantiate Faker on Seeder constructor

---

system/Entity.php

`Entity::__set()` has the wrong parameter type specified which prevents it from being successfully declared as a `universalObjectCratesClasses`.
https://github.com/phpstan/phpstan/issues/3938
**Checklist:**

Correct parameter type

---

.github/workflows/test-phpunit.yml
system/Config/Factories.php

I tried latest `dev-develop` when running test in a codeigniter4 module and without set `autoload=false` in 2nd parameter of `class_exists()` in `Factories::locateClass()`, I got the error:
```bash
Cannot declare class Config\App, because the name is already in use
at APPPATH/Config/App.php:7
Backtrace:
1    [internal function]
CodeIgniter\Debug\Exceptions()->shutdownHandler()
Fatal error: Cannot declare class Config\App, because the name is already in use in /Users/samsonasik/www/codeigniter4-files/vendor/codeigniter4/codeigniter4/app/Config/App.php on line 7
```
This patch fixed the issue.
**Checklist:**

Bug fix: ensure to use autoload = false in class_exists() in low-hanging fruit in Factories::locateClass()

---

.github/workflows/test-phpunit.yml

`composer remove` error that tried to be fixed at commit https://github.com/codeigniter4/CodeIgniter4/pull/3772/commits/b263bac61e48fd0f1b114ac2fa00e0098f987a28  actually can be solved by only re-sort order of command of removing between `rector` and `phpstan`. 
The `--update-with-dependencies` actually already handle by default.
**Checklist:**

remove deprecated  --update-with-dependencies in composer remove command

---

phpstan.neon.dist
system/Model.php

Optimized `Model`.
- Removes unneeded variables.
- Uses truthy checks and null coalescing operators where possible
- Make setter methods return `$this` for easy method chaining.
**Checklist:**

Optimize Model

---

.github/workflows/test-phpunit.yml

@michalsn I think report coveralls can be only in specific php version to handle false positive decreased coverage.
As I see, it seems the stable report in php <strike>7.3</strike> 7.4. I added if php version check to handle it. Please verify if it is ok.
**Checklist:**

report coveralls only in specific php version

---

system/Common.php
system/Config/BaseService.php
tests/_support/Autoloader/FatalLocator.php
tests/_support/Helpers/baguette_helper.php
tests/system/CommonFunctionsTest.php

Adds a local static cache of helpers that have already been loaded, so multiple calls to the same file with `helper()` won't result in duplicate filesystem searches.
Bonus: This sped up tests on `CommonFunctionTest.php` by 7 seconds (30s -> 20s) so will likely help overall test time!
**Checklist:**

Helper cache

---

user_guide_src/source/libraries/files.rst

getSize() does not accept the unit parameter like getSizeByUnit() as stated on the user guide.
Not sure if that is suposed to be like that or it was a "copy/paste" issue on this document, but does induce into error.
**Checklist:**

getSize() does not accept parameters like getSizeByUnit()

---

phpstan.neon.dist
system/bootstrap.php
utils/PHPStan/CheckUseStatementsAfterLicenseRule.php

I created custom PHPStan rule to check Use statement after license docblock like in `system/boostrap.php` which previously use statement is missplaced before license.
**Checklist:**

Add Custom PHPStan rule to check Use statement after license docblock

---

system/Common.php
system/Config/Config.php
system/Config/Factories.php
system/Config/Factory.php
system/Database/ModelFactory.php
tests/system/Config/FactoriesTest.php
user_guide_src/source/concepts/factories.rst

After using `Factories` for a bit I've found some of the functionality to be a bit awkward. The classes that `Factories` replaced had a single option, `getShared`, which I gave undue prominence to in the abstracted class. But with the limit on passable parameters this forced other directives to come from the configuration.
This PR renames factory "configurations" to "options" to help distinguish them from actual `Config` classes. It moves `getShared` to be another option and changes `__callStatic` to take a set of options as the second parameter, which allows full customization by each call.
An example of what this enables... Say an `Authentication` services needs to look up a user via its `UserModel`. By using `Factories`'s `preferApp`, it can allow a developer to provide …

Factory parameter options

---

system/Entity.php
tests/system/EntityTest.php
user_guide_src/source/models/entities.rst

Adds support for Entity's `castAs` to use comma-separated values, a common "sub-collection" database storage format.
```
class Widget extends Entity
{
protected $casts = [
'colors' => 'csv',
];
}
$widget->colors = ['red', 'yellow', 'green']; // Stored in the database as "red,yellow,green"
...
$widget = model(WidgetModel::class)->find(1);
var_dump($widget->colors); // ['red', 'yellow', 'green']
```
**Checklist:**

Add CSV casting

---

CONTRIBUTING.md

Add BC Break Policy

---

system/Test/CIDatabaseTestCase.php
system/Test/CIUnitTestCase.php

This is PR I propose to fix #3788 (my own issue)
**Checklist:**

Set CIDatabaseTestCase and CIUnitTestCase abstract

---

admin/framework/composer.json
admin/module/composer.json
admin/starter/composer.json
composer.json

I don't know the original intent for this but `composer dump-autoload` is already called after every `install`, `update`, `remove` operation, so there's no need to call it again. If there's a reasoning behind this, please correct me. 😊
**Checklist:**

Remove dump-autoload in post-update-cmd

---

system/Autoloader/FileLocator.php
system/Common.php
system/ComposerScripts.php
system/Database/BaseBuilder.php
system/Database/BaseConnection.php
system/Database/Postgre/Connection.php
system/HTTP/IncomingRequest.php
system/Helpers/filesystem_helper.php
system/Helpers/form_helper.php
system/Helpers/number_helper.php
system/Images/Handlers/BaseHandler.php
system/Router/Router.php
system/Typography/Typography.php
system/View/Cell.php
system/View/Parser.php

**Description:**
Removes WordPress-style spacing inside parentheses.
**Checklist:**

Remove extra spaces inside parentheses

---

system/Events/Events.php
tests/system/Events/EventsTest.php

I have always been wondering why on `appstarter` the `pre_system` event is called twice, as shown in the toolbar. Then, this [forum thread](https://forum.codeigniter.com/thread-77765.html) emerged also discussing this *duplication*. It turns out, as pointed by OP, that on events discovery the `Config\Events` file is included twice even though they are referencing the same file. This PR attempts to filter `Events::$files` to have only unique found files to `include`.
**Checklist:**

Prevent events duplication on initialisation

---

user_guide_src/source/libraries/caching.rst

Fix wrong method: getCacheInfo() instead of cache_info()

---

app/Config/Mimes.php
phpstan.neon.dist
rector.php
system/Common.php
system/Config/Services.php
system/Database/Sqlsrv/Forge.php
system/Router/RouteCollection.php
system/Validation/Validation.php
system/View/Table.php
utils/Rector/PassStrictParameterToFunctionParameterRector.php
utils/Rector/PassTrueToThirdParameterInArrayRector.php

Added new Custom Rector Rule to Pass `true` to 3rd parameter of `in_array` when no value provided.
**Checklist:**

Add new Custom Rector Rule to Pass true to 3rd parameter of in_array when no value provided

---

system/Filters/Filters.php
system/Log/Logger.php
system/Router/Router.php
system/Session/Handlers/DatabaseHandler.php
system/Validation/FormatRules.php
utils/Rector/PassStrictParameterToFunctionParameterRector.php

This continues on #3799 to add `true` param to `base64_decode` and `array_search`, which are used in the framework. This does not change yet other functions that can be made strict (e.g., `array_keys`, `mb_detect_encoding`) as it is not yet used.
**Checklist:**

Enable strict param on base64_decode and array_search

---

system/Database/BaseBuilder.php
system/Model.php
tests/system/Database/Builder/BaseTest.php
tests/system/Database/Live/ModelTest.php
user_guide_src/source/models/model.rst

*See #3793 for the underlying issue*
This one might be controversial, but there's a bug and I have not found a simpler fix. `Model::builder($tableName)` will return an existing shared instance of the `Builder` regardless of `$tableName`'s value. This is for a couple reasons:
* `builder()` is protected and the `__call()` method that loads it in turn does not pass on parameters
* If `builder()` detects a existing shared instance it will return it immediately, regardless of the table name
This PR attempts to fix the issue by:
1. Defining a `$tableName` property for `Builder`, assigned during initialization
2. Providing a getter to access this property
3. Adjusting `Model::builder()` to be public (also cleans up some unnecessary `__call()` steps)
4. Using `Builder::getTable()` …

Builder Tables

---

system/Debug/Toolbar.php

I have a form to edit email content, the body of which includes a `<head>` tag. The toolbar filter is injecting itself into the form to edit this content because it matches `<head>`. This PR limits the toolbar replacement to the first instance of the head tag.
**Checklist:**

Limit toolbar to initial head tag

---

phpstan.neon.dist
system/Database/MySQLi/PreparedQuery.php
system/Database/Postgre/PreparedQuery.php
system/Database/SQLite3/PreparedQuery.php
system/Database/Sqlsrv/PreparedQuery.php

Fixes the ignoredError `#Call to function is_null\(\) with mysqli_stmt\|resource will always evaluate to false#`
**Checklist:**

Fix phpstan issue with PreparedQuery classes' statement property

---

phpstan.neon.dist
system/Config/BaseConfig.php

Before PHPStan v0.12.51, initialisation of `Config\Encryption`'s `$key` property via `BaseConfig` is not marked as error. This was due to, as the author states, PHPStan not really doing the check at all. However, this is now being marked as erroneous.
See: [phpstan/phpstan@3998](https://github.com/phpstan/phpstan/issues/3998)
**Checklist:**

Fix undefined property BaseConfig::$key

---

system/Debug/Toolbar.php

@MGatner this is fixes missing regex delimiter at Toolbar at https://github.com/codeigniter4/CodeIgniter4/pull/3804#issuecomment-716097763
**Checklist:**

Fixes missing regex delimiter at Toolbar

---

system/RESTful/ResourceController.php
system/RESTful/ResourcePresenter.php

Return types are not specified on the RESTful controllers but they are in the doc blocks. Frequently an endpoint will need to return a RedirectResponse or ResponseInterface which will cause static analysis complaints. This PR loosens the return type doc completely to allow developers to set their own.
**Checklist:**

Loosen return type docs

---

.github/workflows/test-phpunit.yml
composer.json

Composer v2 is now released. `ammaraskar/setup-php` is now by default using v2 so no need to add the `v2` tag.
Other changes:
- Used `composer update` instead of `composer install` because no lock file is present
- `--no-suggest` is deprecated so no need to include
- `--no-progress` does not actually hide the installation progress
- moved options `--optimize-autoloader` and `--prefer-dist` to `composer.json` so these will be used both by `update` and `remove` operations
- add `--unused` option to `remove` to make sure unused packages are removed (available as of v2)
- `--ansi` for colored output 😁
**Checklist:**

Use Composer v2 for workflow

---

rector.php
system/Database/BaseBuilder.php
system/Database/Forge.php
system/Database/SQLite3/Table.php
system/Database/Sqlsrv/Builder.php
system/Database/Sqlsrv/Forge.php
system/View/Table.php

Change count array comparison to empty array comparison to improve performance
**Checklist:**

Apply Rector: CountArrayToEmptyArrayComparisonRector

---

rector.php

Previously, in `develop`, it skipped due conflict with deprecated code. In 4.1, deprecated code is removed.
**Checklist:**

[4.1] Remove Skip UnderscoreToCamelCaseVariableNameRector for Autoloader.php file

---

system/CLI/CLI.php
system/CodeIgniter.php
system/Database/Forge.php
system/Database/MigrationRunner.php
system/Database/MySQLi/Connection.php
system/Database/SQLite3/Connection.php
system/Database/SQLite3/Forge.php
system/Debug/Toolbar/Collectors/History.php
system/HTTP/DownloadResponse.php
system/Helpers/array_helper.php
system/Helpers/inflector_helper.php
system/Helpers/url_helper.php
system/I18n/TimeDifference.php
system/Pager/Pager.php
system/Session/Handlers/FileHandler.php
system/Test/DOMParser.php
system/Validation/CreditCardRules.php
system/Validation/Rules.php
system/View/Parser.php

Standardizes typecasting
- Cast and casted variable should have one space in between
- Use cast instead of cast functions (intval, strval, etc.) or settype
- Remove unnecessary casting
**Checklist:**

Standardize types casting

---

system/Language/Language.php
tests/system/Language/LanguageTest.php

Fixes #3822 if it is more of a bug than a documentation issue.
**Checklist:**

Language: Allow parsing language strings without file

---

system/View/Parser.php
tests/system/View/ParserPluginTest.php

Parser: Allow dashes and parentheses in parser plugin information

---

tests/system/Commands/ClearDebugbarTest.php
tests/system/Commands/ClearLogsTest.php

With PHPUnit 9, `assertFileNotExists` is renamed to `assertFileDoesNotExist`.
**Checklist:**

4.1: Change deprecated assertFileNotExists

---

.github/workflows/test-phpstan.yml
.github/workflows/test-rector.yml

As of Composer v2, `composer update` is preferred over `composer install` if installing from without a lock file. Also removes deprecated option.
**Checklist:**

DX: Use composer update

---

admin/starter/tests/unit/HealthTest.php

Fixed the call to the reader baseURL in HealthTest.php.
**Checklist:**

HealthTest BaseUrl property being called wrong

---

system/Test/FeatureTestCase.php
system/Test/FeatureTestTrait.php
tests/_support/Controllers/Popcorn.php
tests/system/Test/FeatureTestCaseTest.php
user_guide_src/source/testing/feature.rst

I added the ability to set a body format on Feature Tests so that the request body can be set according to that format. This allows the Feature Tests to work on controllers that are using functions such as `$request->getJson()` or are expecting the body to contain a JSON or XML.
**Checklist:**

Feature Tests with a Formatted Request Body

---

system/Exceptions/FrameworkException.php
system/Language/en/Fabricator.php
system/Test/Fabricator.php
tests/system/Database/Live/FabricatorLiveTest.php
utils/PHPStan/CheckUseStatementsAfterLicenseRule.php

Fixes a bug in `Fabricator` where `create()` could fail to insert anything causing `reset($ids)` to be null and `model->find()` would then return all rows. This PR has Fabricator throw a helpfully-descriptive error message when the create call fails.
**Checklist:**

Fabricator failure

---

system/Commands/ListCommands.php
tests/system/Commands/CommandTest.php
user_guide_src/source/cli/cli_commands.rst

This adds a new command list format "simple" that is a parsable list of commands, e.g.:
```
CodeIgniter v4.0.4 Command Line Tool - Server Time: 2020-11-09 10:42:28 UTC-05:00
cache:clear
cache:info
db:create
db:seed
debugbar:clear
...
```
**Checklist:**

Add simple command list format

---

system/CodeIgniter.php

Standardizes **CodeIgniter.php**'s handling of responses with `ResponseInterface`. Also makes sure always to check `$returnResponse`, even after `Filters` return (fixes an issue reported in #3863, superseded).
**Checklist:**

Response Standards

---

system/Test/Fabricator.php

An addendum to #3866 where I failed to account for `Model::errors()` returning `null` instead of an empty array.
**Checklist:**

Handle errors() null return

---

system/HTTP/CLIRequest.php

Expressly forbid CLIRequest from running in non-CLI env

---

tests/system/Database/Live/ModelTest.php

There have a been a few reports of `Model::insertBatch()` not setting timestamps. This adds some tests to confirm it is at least generally working.
**Checklist:**

Add insert batch timestamps tests

---

system/Common.php
system/Config/BaseService.php
tests/system/CommonFunctionsTest.php
tests/system/CommonSingleServiceTest.php
tests/system/Config/ServicesTest.php

Fixes #3854 .
This PR deprecates the protected `BaseService::discoverServices()` method and splitting its services discovery function into a new protected `buildServicesCache()`. The resolution of where the service might be defined is now defined in a new public static method `serviceExists()` that takes the name of service as lone argument. This returns an array of `bool $result, ?string $service`.
For the `single_service` function, this takes use of `ReflectionMethod` and `ReflectionParameter` to introspect the signature of the method requested and fills up the `$params` by the default values but also ensures that the last argument is always `false` to ensure no shared instance.
@sfadschm, please stress test this solution to find any possible regressions.
So far, the …

Dynamically fill arguments for single service

---

system/Database/BasePreparedQuery.php
system/Database/Forge.php
system/Database/SQLite3/Forge.php

`BaseConnection` is already implementing `ConnectionInterface` and the `$db` used is an instanceof `BaseConnection`
**Checklist:**

Fix PHPStan notice in latest develop

---

system/Database/BasePreparedQuery.php
system/Database/Forge.php
system/Database/SQLite3/Forge.php
system/Database/SQLite3/PreparedQuery.php

This one needs arbitration.
PHPStan flags the requirement of docblock using `BaseConnection` but constructor accepts `ConnectionInterface`. `BaseConnection` implements `ConnectionInterface` so it should not pose a problem but maybe phpstan flags this as error because there may be utility methods in `BaseConnection` that are not present in the interface.
This PR changes requirement to `BaseConnection` altogether as it meets the `ConnectionInterface` requirement and may cover the methods unique to BaseConnection. I think this should not be a BC as users would be using the configured DB drivers which already extends `BaseConnection`.
**Checklist:**

Fix phpstan error on database

---

system/Database/MySQLi/Connection.php
system/Database/MySQLi/PreparedQuery.php
system/Database/MySQLi/Result.php
system/Database/Postgre/Connection.php
system/Database/Postgre/PreparedQuery.php
system/Database/Postgre/Result.php
system/Database/SQLite3/Connection.php
system/Database/SQLite3/PreparedQuery.php
system/Database/SQLite3/Result.php
system/Database/Sqlsrv/Connection.php
system/Database/Sqlsrv/PreparedQuery.php
system/Database/Sqlsrv/Result.php
system/HTTP/Exceptions/HTTPException.php
system/I18n/Exceptions/I18nException.php
system/Log/Exceptions/LogException.php
system/Log/Handlers/ChromeLoggerHandler.php
system/Log/Handlers/FileHandler.php
system/Pager/Exceptions/PagerException.php
system/Router/Exceptions/RouterException.php
system/Security/Exceptions/SecurityException.php
system/Session/Exceptions/SessionException.php
system/Session/Handlers/ArrayHandler.php
system/Session/Handlers/DatabaseHandler.php
system/Session/Handlers/FileHandler.php
system/Session/Handlers/MemcachedHandler.php
system/Session/Handlers/RedisHandler.php
system/Validation/Exceptions/ValidationException.php
system/View/Exceptions/ViewException.php

If a parent class already implements an interface, then the extending child class need not implement again the interface in its class definition.
**Checklist:**

Remove superfluous interface definition in classes

---

tests/system/Database/Live/ModelTest.php

This changes the test from `assertEquals` to `assertCloseEnough` for time comparisons to mitigate failures due to a second difference.
**Checklist:**

Fix volatile time comparison in insert batch testing

---

system/Helpers/form_helper.php

When array type form fields are used like multiple select it is needed to pass back multiple values as array
**Checklist:**

form_helper - Allow arrays as default and return values in set_value method

---

system/HTTP/CURLRequest.php
tests/system/HTTP/CURLRequestTest.php
user_guide_src/source/libraries/curlrequest.rst

Adds support for the `user_agent` option for cURL headers.
**Checklist:**

Allow cURL user agent

---

system/Database/BaseBuilder.php

@mixin BaseBuilder is used in Model class. By having return BaseBulder type it will make further autocompletion then chaning methods show only code suggestions for methods/properties from BaseBuilder class.
Returning $this as type solves the issue
**Checklist:**

BaseBuilder - Return Types for chaining in Model classes

---

admin/pre-commit

In some workflows like  MAMP on OSX default php version is set using alias in bash profile
```
alias php='/Applications/MAMP/bin/php/php7.4.2/bin/php -c "/Library/Application Support/appsolute/MAMP PRO/conf/php7.4.2.ini"'
```
In such case when phpstan and codesniffer are executed via git hoot it will run them using the default system php instead of using the alias.
Prefixing the method call with php triggers the alias and solves the issue.
**Checklist:**
- [x ] Securely signed commits

pre-commit hook does not work with alias

---

tests/system/Helpers/ArrayHelperTest.php

With this PR, `array_helper` tests will have 100% coverage.
However, I am not sure, if the current behavior of `_array_search_dot` is desired.
https://github.com/codeigniter4/CodeIgniter4/blob/e6bfd328b3353e178c8b3fe852dbfcccd940501c/system/Helpers/array_helper.php#L90
This line can only be reached, if either the current index is not the last in the dot-notation search string (i.e., we want to search in a deeper level) and at the same time `$array[$currentIndex]` is not an array (i.e., there is no deeper level to search in).
So instead of failing because the search depth is smaller than the array depth, we just break the search and return the deepest level found. Is that desired?
**Checklist:**

Array_helper: Add missing test for _array_search_dot.

---

system/Filters/Filters.php

This fixes #3902
**Checklist:**

Filters: Fix route filters running twice

---

system/Helpers/array_helper.php
tests/system/Helpers/ArrayHelperTest.php
user_guide_src/source/helpers/array_helper.rst

This PR adds a convenience method to CI's `array_helper` to allow sorting a multidimensional array by a list of columns contained in the array. As I find myself using this regularly, I thought maybe others would appreciate this functionality, too.
The helper function takes the reference to an array `&$array` that is to be sorted and an associative array `$sortColumns` of column names and SORT_* flags.
The referenced array is looped and a onedimensional array of values for each column defined in the `$sortColumns` array is generated. Then all of these arrays are passed to the array_multisort function together.
This results in `&$array` being sorted by all of the defined columns and flags hierarchically, which might be useful, e.g., for sorting arrays of entities returned …

Array_helper: Add function array_sort_by_multiple_keys.

---

system/Router/RouteCollection.php
tests/system/Router/RouteCollectionTest.php
user_guide_src/source/incoming/routing.rst

I ran into bit of an issue while grouping my routes and wanted to achieve something like the below.
```
$routes->group('v1', ['namespace' => 'App\Controllers\V1'], function ($routes) {
$routes->post('verify/begin', 'VerificationController::generateVerificationCode');
$routes->post('verify/code', 'VerificationController::verifyCode');
$routes->post('users', 'UserController::createUser');
$routes->post('auth', 'AuthController::authenticateUser');
$routes->group(null, ['filter' => 'api-auth', 'namespace' => 'App\Controllers\V1'], function($routes) {
$routes->put('users', 'UserController::updateUser');
});
});
```
In essence i wanted to group some routes without a prefix but have them run under …

Group routes without a prefix.

---

user_guide_src/source/changelogs/v4.0.5.rst

Fixes typo SameSate -> SameSite
**Checklist:**

fix typo on changelog

---

system/Database/Database.php
system/HTTP/IncomingRequest.php
system/Images/Handlers/BaseHandler.php
system/Log/Logger.php
system/Router/RouteCollection.php
system/Validation/Rules.php
system/Validation/Validation.php

This PR addresses the now-deprecated(PHP 8) use of mandatory parameters following optional parameters. Split off from #3931.
**Checklist:**

Backfill Parameters

---

system/CodeIgniter.php
system/Debug/Toolbar.php
system/HTTP/CURLRequest.php
system/HTTP/IncomingRequest.php
system/HTTP/Message.php
system/Security/Security.php
user_guide_src/source/changelogs/v4.0.5.rst
user_guide_src/source/incoming/incomingrequest.rst
user_guide_src/source/incoming/message.rst
user_guide_src/source/installation/upgrade_405.rst

In the interest of moving towards partial PSR-7 compliance this PR adds the `header()` and `headers()` methods to `Message` and deprecates the current `getHeader()` and `getHeaders()` methods which conflict with the PSR's interface.
Note that I've left tests pointing to the original methods since they call the new ones and thus should not adversely affect code coverage.
**Checklist:**

Deprecate Message::getHeader(s)

---

system/I18n/Time.php
system/Validation/Rules.php
tests/system/Helpers/ArrayHelperTest.php

Fixes the test failures identified by #3932
**Checklist:**

Apply PHP 8 compatibility changes

---

app/Config/Mimes.php

Fixes #3921.
Came across this when trying to upload `.vtt` files.
**Checklist:**

Fix mime types for .srt and .vtt.

---

user_guide_src/source/general/configuration.rst

Updated documentation to remind users that information from .env is available in the output from phpinfo() and other commands dumping Environment Variables.
**Checklist:**

[ci skip] added varning about .env and phpinfo()

---

user_guide_src/source/incoming/filters.rst

There is no Security filter, but CSRF filter.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/app/Config/Filters.php#L6-L8
**Checklist:**
- [n/a] Conforms to style guide

Fix Provided Filter name in user guide

---

user_guide_src/source/tutorial/news_section.rst

It is better that body in the `<p>` tag.
Current code shows body and footer without line breaks.
**Checklist:**

Fix tutorial news section HTML tag

---

user_guide_src/source/libraries/caching.rst

$cache::save() returns a `bool`, not a `string`.
**Checklist:**

Fix "$cache::save()" return type in the documentation

---

user_guide_src/source/incoming/routing.rst

Added to the documentation that when nesting ``$routes->group()``, the options passed to the outer group() is not merged with the inner group(). A definition such as:
```php
$routes->group('config', ['filter' => 'myfilter:config'], function ($routes) {
$routes->group('region', ['filter' => 'myfilter:region'], function ($routes) {
});
});
```
would only call ``myfilter:region`` for config/region which may not be what a user expects.
**Checklist:**

Clarifying nested $routes->group() options [ci skip]

---

user_guide_src/source/dbmgmt/migration.rst

The method name is wrong.
**Checklist:**

docs: fix method name in sample code

---

system/CLI/CLI.php
tests/system/CLI/CLITest.php

CLI::strlen() does not handle mutibyte letters correctly.
Before:
After:
**Checklist:**
- [n/a] User guide updated

Fix: CLI::strlen() does not handle mutibyte letters correctly

---

user_guide_src/source/testing/benchmark.rst
user_guide_src/source/testing/debugging.rst
user_guide_src/source/testing/fabricator.rst
user_guide_src/source/testing/overview.rst

A tab is converted to 8 spaces. So it is better to use only spaces for indentation.
**Checklist:**

Fix testing docs indentation

---

user_guide_src/source/cli/cli.rst
user_guide_src/source/cli/cli_commands.rst
user_guide_src/source/cli/cli_generators.rst
user_guide_src/source/cli/cli_library.rst

- Replace tab indentation with space.
- A tab is converted to 8 spaces. So it is better to use only spaces for indentation.
- Fix sample code coding stye.
**Checklist:**

docs: fix cli indentation

---

user_guide_src/source/installation/troubleshooting.rst
user_guide_src/source/installation/upgrading.rst

Replace tab indentation with space.
**Checklist:**

docs: fix installation indentation

---

system/Helpers/form_helper.php
tests/system/Helpers/FormHelperTest.php

As far as I know, hidden fields do not require additional styles.
And with this, make form_input the basis for creating form_hidden.
**Checklist:**

make form_hidden based on form_input

---

system/Autoloader/Autoloader.php

Removed spl_autoload_extensions() function
This function is used with spl_autoload() or spl_autoload_register() (no arguments). 
But CI4 does not use such methods for class autoloading.  
The anonymous function defined in a class has access to the class context. 
This means that we can use the $this variable inside an anonymous function.

Changes in Autoloader::register() method

---

system/Config/Routes.php

While the route methods is sensitive to letters we still can access BaseController::index via localhost/BaseController or localhost/BaseController/index, because route configured to prevent access localhost/basecontroller, since autoRoute method ucfirst('basecontroller') :: output > Basecontroller that is not actually found.

Fix Access BaseController Methods via url

---

admin/starter/app/Config/Paths.php

Since #3607 app folder in develop branch is up-to-date, but in appstarter not
**Checklist:**

appstarter forgetting to update from develop branch

---

.github/workflows/test-phpunit.yml
phpunit.xml.dist

Enables `coverage` mode for Xdebug 3, should have no affect on Xdebug 2.x
**Checklist:**

Supply Xdebug 3 mode

---

tests/system/Database/Live/ForgeTest.php

This is my lazy attempt at circumventing the Postrgres database failures during testing. They seem to be related to a test table hanging around (or maybe concurrency issue?) so I'm dropping the table much sooner.
**Checklist:**

Improve Postgres testing

---

system/BaseModel.php
system/Model.php

The goal with this change is to have BaseModel which does not contain any database related code so that it can easily be extended to support other kinds of databases like NoSQL document based
**Checklist:**

Split Model to have BaseModel without database related stuff

---

system/CodeIgniter.php
system/Database/BaseBuilder.php
system/Database/Postgre/Builder.php
system/Pager/Pager.php
system/Test/DOMParser.php
system/Validation/CreditCardRules.php
system/Validation/FileRules.php
system/Validation/FormatRules.php
tests/system/Validation/FormatRulesTest.php

This PR addresses the case when a typed function argument has a defined default of `null` and is followed by a required argument.
In this case, the assigned default value is only used to enable a nullable type before PHP 7.1.
In this PR, such assignements are changed to real nullable types.
Also fixed some DocBlocks that I came across.
Possible extension: Use nullable type also for typed optional arguments with a default `null` value.
**Checklist:**

Use nullable typehints for non-optional typed function arguments.

---

system/Security/Security.php
system/Security/SecurityInterface.php

While Security Class is one of core system classes and it might be replaced by user Security class, it should have it's own interface for more flexibility.
closes #4013

Add Interface to Security Component

---

system/Validation/Rules.php
tests/system/Validation/RulesTest.php

Closes #3965
Added dot_array_search to required_with and required_without so that they work when using array as key in a form.

fix: add dot_array_search to required_with and required_without

---

user_guide_src/source/concepts/factories.rst
user_guide_src/source/concepts/http.rst
user_guide_src/source/concepts/index.rst
user_guide_src/source/concepts/services.rst
user_guide_src/source/concepts/structure.rst

Replace tab indentation with space. 
See #3988
**Checklist:**

docs: fix concepts indentation

---

.github/workflows/test-phpunit.yml
system/Database/SQLSRV/Builder.php
system/Database/SQLSRV/Connection.php
system/Database/SQLSRV/Forge.php
system/Database/SQLSRV/PreparedQuery.php
system/Database/SQLSRV/Result.php
system/Database/SQLSRV/Utils.php
tests/_support/Config/Registrar.php
tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
tests/_support/Database/Seeds/CITestSeeder.php
tests/system/Database/Live/DbUtilsTest.php
tests/system/Database/Live/ForgeTest.php
tests/system/Database/Live/GetTest.php
tests/system/Database/Live/ModelTest.php
tests/system/Database/Live/OrderTest.php
tests/system/Database/Live/PreparedQueryTest.php
tests/system/Database/Migrations/MigrationRunnerTest.php
user_guide_src/source/intro/requirements.rst

Rename `Sqlsrv` driver to `SQLSRV` to compatible with PHP extension name, like other drivers MySQLi, SQLite3 etc...

Rename Sqlsrv driver

---

user_guide_src/source/license.rst

I didn't render before, and the result is like below: (https://codeigniter4.github.io/CodeIgniter4/license.html)
And now, the expected is: 
**Checklist:**

New line for License copyright 

---

user_guide_src/source/helpers/form_helper.rst

Update code block in [UG] from_helper.php
Before:
After:
**Checklist:**

fix codeblock

---

user_guide_src/source/general/caching.rst
user_guide_src/source/general/common_functions.rst
user_guide_src/source/general/configuration.rst
user_guide_src/source/general/environments.rst
user_guide_src/source/general/helpers.rst
user_guide_src/source/general/urls.rst

Replace tab indentation with space.
See #3988
**Checklist:**

docs: fix general indentation

---

user_guide_src/source/cli/cli_generators.rst
user_guide_src/source/concepts/factories.rst
user_guide_src/source/concepts/http.rst
user_guide_src/source/database/configuration.rst
user_guide_src/source/database/query_builder.rst
user_guide_src/source/dbmgmt/migration.rst
user_guide_src/source/extending/contributing.rst
user_guide_src/source/general/ajax.rst
user_guide_src/source/general/logging.rst
user_guide_src/source/helpers/form_helper.rst
user_guide_src/source/helpers/html_helper.rst
user_guide_src/source/helpers/number_helper.rst
user_guide_src/source/helpers/text_helper.rst
user_guide_src/source/helpers/url_helper.rst
user_guide_src/source/helpers/xml_helper.rst
user_guide_src/source/incoming/filters.rst
user_guide_src/source/incoming/incomingrequest.rst
user_guide_src/source/incoming/routing.rst
user_guide_src/source/installation/installing_composer.rst
user_guide_src/source/installation/running.rst
user_guide_src/source/installation/upgrade_4xx.rst
user_guide_src/source/libraries/encryption.rst
user_guide_src/source/libraries/images.rst
user_guide_src/source/libraries/security.rst
user_guide_src/source/libraries/uploaded_files.rst
user_guide_src/source/models/entities.rst
user_guide_src/source/outgoing/localization.rst
user_guide_src/source/outgoing/view_parser.rst
user_guide_src/source/testing/controllers.rst
user_guide_src/source/tutorial/news_section.rst

Rrecommends a comma after use: i.e., and e.g.,
**Checklist:**

[UG] a comma after use: i.e., and e.g.,

---

tests/system/Database/DatabaseTestCaseTest.php

Properties are reset by PHPUnit, so `$this->loaded` in `setUp()` is always `false`.
```diff
--- a/tests/system/Database/DatabaseTestCaseTest.php
+++ b/tests/system/Database/DatabaseTestCaseTest.php
@@ -45,6 +47,7 @@ class DatabaseTestCaseTest extends CIDatabaseTestCase
{
Services::autoloader()->addNamespace('Tests\Support\MigrationTestMigrations', SUPPORTPATH . 'MigrationTestMigrations');
$this->loaded = true;
+           echo '!!! addNamespace !!!'.PHP_EOL;
}
parent::setUp();
```
You see `!!! addNamespace !!!` twice.
```
$ vendor/bin/phpunit --no-coverage tests/system/Database/DatabaseTestCaseTest.php --debug
PHPUnit 8.5.4 by Sebastian Bergmann and contributors.
Test 'CodeIgniter\Database\DatabaseTestCaseTest::testMultipleSeeders' started
Test …
```

Fix database test case test

---

user_guide_src/source/helpers/filesystem_helper.rst

While using the `delete_files` helper function, i noticed that a parameter was not documented. This pull request takes care of that.
**Checklist:**
- [x ] Unit testing, with >80% coverage

Added omitted function parameter description.

---

system/Database/BaseBuilder.php
user_guide_src/source/database/query_builder.rst

Fix countAll() documentation.
**Checklist:**

Fix countAll() docs

---

user_guide_src/source/general/managing_apps.rst

see: 
https://github.com/codeigniter4/CodeIgniter4/blob/4ea15f84d0bccb5c01b91d67d38c68051e2731b9/app/Config/Paths.php#L45
https://github.com/codeigniter4/CodeIgniter4/blob/4ea15f84d0bccb5c01b91d67d38c68051e2731b9/spark#L44
https://github.com/codeigniter4/CodeIgniter4/blob/4ea15f84d0bccb5c01b91d67d38c68051e2731b9/public/index.php#L28
**Checklist:**

fix userguide config path

---

system/Test/CIDatabaseTestCase.php
tests/system/Database/DatabaseTestCase/DatabaseTestCaseMigrationOnce1Test.php
tests/system/Database/DatabaseTestCase/DatabaseTestCaseMigrationOnce2Test.php
user_guide_src/source/testing/database.rst

Now you can't disable migration on database testing if you want.
And running migration/seed on each test may slow tests.
- You can disable migration: `$migrate = false`
- You can run migration only once: `$migrateOnce = true`
- You can run seed only once: `$seedOnce = true`
**Checklist:**

feat: make migration/seed settings flexible on database testing

---

.github/workflows/test-phpstan.yml
.github/workflows/test-phpunit.yml
composer.json

*Supercedes #3932*
Adds PHP 8 to the testing and analysis workflows. This will give some idea of the work left to do for `4.0.5` to support PHP 8, and any conflicts among dependencies for supporting both `7.2` and `8.0`
**Checklist:**

PHP 8 Actions

---

tests/system/Helpers/URLHelperTest.php

We are still getting a lot of reports about issues related to URLs and routing when installed in a subdirectory. This PR consolidates `site_url()` testing with a data provider to make it easier to see what is tested, and easier to add tests in the future. All existing cases are accounted for, as well as a few more subdirectory scenarios.
**Checklist:**

site_url tests

---

system/HTTP/Exceptions/HTTPException.php
system/Language/en/HTTP.php
tests/system/HTTP/ResponseCookieTest.php
tests/system/HTTP/ResponseTest.php
tests/system/Helpers/CookieHelperTest.php

With the merge of the refactored Security class, the redundant `HTTP.disallowedAction` and `HTTP.invalidSamSiteSetting` can be removed in favor of the `Security` counterpart.
**Checklist:**

Deprecate redundant HTTP keys

---

.github/workflows/test-phpstan.yml
phpstan.neon.dist
system/Test/Filters/CITestStreamFilter.php

We’ve run into our first PHP 7/8 PHPStan issue: https://github.com/codeigniter4/CodeIgniter4/runs/1650630303
For whatever reason this line in **CITestStreamFilter** is no longer an issue in PHP 8, but persists in PHP 7:
```
public function filter($in, $out, &$consumed, $closing)
{
while ($bucket = stream_bucket_make_writeable($in))
{
static::$buffer .= $bucket->data;
$consumed += $bucket->datalen;
}
// @phpstan-ignore-next-line
return PSFS_PASS_ON;
}
```
Ondre is considering work on how to improve this split handling (https://github.com/phpstan/phpstan/issues/4223 by our own @paulbalandan, https://github.com/phpstan/phpstan/issues/4060#issuecomment-723559902) but the current solution is to have different config files for each version.
Given that the problem currently is …

PHPStan Ignore File

---

user_guide_src/source/models/entities.rst
user_guide_src/source/models/model.rst

Replace tab indentation with space.
See #3988
**Checklist:**

docs: fix models indentation

---

user_guide_src/source/changelogs/v4.0.5.rst

Warn users on system messages being for internal use

---

system/BaseModel.php
system/Model.php

This fixes the issue with primaryKey property which was unintentionally left inside base model. This also ads @throws for builder() method
**Checklist:**

Model/BaseModel - Fix primary key and  add @throws for builder method

---

user_guide_src/source/helpers/form_helper.rst

fix mistake from previous PR (#4075)
see: (before)
then 
**Checklist:**

Fix userguide indent

---

rector.php

As documented at rector's readme https://github.com/rectorphp/rector/tree/fe639838d5ba70b716a3caa66d40ef21f9185ab1#full-config-configuration
**Checklist:**

[4.1][Static Analysis] Using PhpVersion::PHP_73 constant in rector ^0.9

---

user_guide_src/source/installation/installing_composer.rst

update codeblock
before:
after:
**Checklist:**

fix codeblock in installing_composer.rst

---

system/BaseModel.php
system/Model.php

Here is one way of keeping escape parameter outside of method definitions. But the existing solution is much more elegant
@michalsn What's your opinion on this one ? 
Should we keep the existing implementation and just update the docs or should this one be merged
**Checklist:**

BaseModel/Model - Attempt to rework escape parameter

---

system/HTTP/Message.php
tests/system/HTTP/MessageTest.php

Fixes the bug pointed out in a comment on #3719.
Fixed an issue in isJSON that was breaking it if the content type header had the encoding in it as well.
**Checklist:**

Fixing a bug in Message::isJSON

---

system/BaseModel.php
system/Model.php

This is additional fix on top of #4072 since $escape is not needed anymore in the doUpdate method
**Checklist:**

BaseModel/Model - Removed $escape from doUpdate

---

system/Database/BaseConnection.php
system/Test/Mock/MockConnection.php

If there is a driver specific query class defined it will be automatically used by the BaseConnection
**Checklist:**

BaseConnection - Added automatic handling of query class for 3rd party drivers

---

composer.json
system/I18n/Exceptions/I18nException.php
system/I18n/Time.php
system/Language/en/Time.php
tests/system/I18n/TimeTest.php

If `DateTime::createFromFormat` fails then it causes unexpected behavior in our own `createFromFormat`. This checks for failure (return `false`) and throws an exception.
See: https://www.php.net/manual/en/datetime.createfromformat.php
**Checklist:**

Catch DateTime failure

---

CHANGELOG.md
admin/framework/composer.json
admin/module/composer.json
admin/starter/composer.json
app/Config/Mimes.php
composer.json
system/HTTP/Files/UploadedFile.php
system/Validation/FileRules.php
tests/system/HTTP/Files/FileCollectionTest.php
user_guide_src/source/changelogs/v4.0.5.rst
user_guide_src/source/libraries/uploaded_files.rst

This PR continues the discussion in #4054.
- Removed the `application/octet-stream` mime type from non-binary file extensions (e.g., `csv`, `srt`, `vtt`, `pdf`).
- Add comment to hint towards enabling the `fileinfo` extension.
- Modify the `guessExtensionFromType` method to
- return `null` if an extension is proposed but the mime type does not match the extension.
- reverse search the `$mimes` array only if no extension was proposed.
**Things to do**
- Add not to Changelog/Update Guide to alert developers to check their mime type handling (and possibly also to enable `fileinfo` again, as several recent bug reports are potentially solved by this).
**Note**
Symphony is using this repo for their mime type list:
https://github.com/jshttp/mime-db …

Solidate mime type guessing.

---

system/Config/View.php
system/View/RendererInterface.php
system/View/View.php
user_guide_src/source/outgoing/view_renderer.rst

Fixes a discrepancy between the interface docblock and the actual method definitions. Clarifies the usage in `View`.
* Fixes https://github.com/codeigniter4/CodeIgniter4/issues/4086
* Replaces https://github.com/codeigniter4/CodeIgniter4/pull/4093
**Checklist:**

Clarify Renderer discrepancy

---

system/Validation/FormatRules.php
tests/system/Validation/FormatRulesTest.php

I want it to be false when
```php
<?php
$validation->check("0\n", 'decimal');
```
However, the regular expression validation implemented in CodeIgniter4 allowed a trailing newline code.
**Checklist:**

Fixed a bug where a newline was treated as a valid value even if it was included at the end.

---

app/Config/Cache.php
system/Cache/Handlers/FileHandler.php
system/Cache/Handlers/MemcachedHandler.php
system/Cache/Handlers/PredisHandler.php
system/Cache/Handlers/RedisHandler.php
system/Cache/Handlers/WincacheHandler.php
tests/system/Cache/Handlers/FileHandlerTest.php
user_guide_src/source/changelogs/v4.0.5.rst
user_guide_src/source/libraries/caching.rst

* Adds support for configurable file modes when using the `FileHandler` for caching.
* Deprecates `Config\Cache::$storePath` in favor of a new driver-specific array of settings (similar to other drivers)
* Fixes a bug where `'0'` was not allowed as a cache prefix
**Checklist:**

Add Cache File mode

---

system/HTTP/Request.php

Fix Request::withMethod()

---

admin/module/tests/_support/SessionTestCase.php
admin/starter/tests/_support/SessionTestCase.php

Fix `@var` in SessionTestCase.
`MockSession` is not `SessionHandler`.
**Checklist:**

Fix `@var` in SessionTestCase.

---

user_guide_src/source/dbmgmt/migration.rst
user_guide_src/source/helpers/cookie_helper.rst
user_guide_src/source/helpers/date_helper.rst
user_guide_src/source/helpers/filesystem_helper.rst
user_guide_src/source/helpers/form_helper.rst
user_guide_src/source/helpers/inflector_helper.rst
user_guide_src/source/helpers/number_helper.rst
user_guide_src/source/helpers/test_helper.rst
user_guide_src/source/helpers/text_helper.rst
user_guide_src/source/helpers/url_helper.rst
user_guide_src/source/helpers/xml_helper.rst
user_guide_src/source/libraries/email.rst
user_guide_src/source/libraries/encryption.rst
user_guide_src/source/libraries/sessions.rst
user_guide_src/source/outgoing/table.rst

I think it's useless,
```
.. raw:: html	
<div class="custom-index container"></div>
```
**Checklist:**

remove useless "raw html"

---

user_guide_src/source/installation/upgrade_405.rst

Dir `Config` is start with capital
**Checklist:**

set uppercase

---

user_guide_src/source/libraries/pagination.rst
user_guide_src/source/libraries/typography.rst

TOC is missing in Typography and Pagination.
**Checklist:**

docs: add table of contents in 2 libs

---

system/Helpers/url_helper.php
tests/system/Helpers/URLHelperTest.php
user_guide_src/source/helpers/url_helper.rst

Add parameter to force https in `prep_url()`
**Checklist:**

prep_url() with https://

---

app/Views/errors/html/error_exception.php

`errors/html/error_exception.php` throws error when constants contain resource and can't see the real exception.
```
ErrorException #1
Uncaught ErrorException: htmlspecialchars() expects parameter 1 to be string, resource given in .../app/Views/errors/html/error_exception.php:182 Stack trace: #0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'htmlspecialchar...', '/Users/kenji/wo...', 182, Array) #1 .../app/Views/errors/html/error_exception.php(182): htmlspecialchars(Resource id #4, 8, 'UTF-8') #2 .../vendor/codeigniter4/codeigniter4/system/Debug/Exceptions.php(281): include('/Users/kenji/wo...') #3 .../vendor/codeigniter4/codeigniter4/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(...\Exception\NotSupportedException), …
```

Fix errors/html/error_exception.php

---

system/Session/Session.php
system/Session/SessionInterface.php

You can set not only `string|array`, but also int, bool, object in the Session.
**Checklist:**

Fix Session phpdoc

---

.github/workflows/test-phpstan.yml
app/Config/App.php
app/Config/Security.php
system/CodeIgniter.php
system/Security/Security.php
system/Session/Session.php

* Adds **composer.json** to the path list for PHPStan Action
* Specifies the Same Site Cookie string values for PHPStan compliance
* Removes the ignore line for a now-passing check
See https://github.com/codeigniter4/CodeIgniter4/pull/4134
**Checklist:**

PHPStan Fixes

---

system/Security/Security.php
system/Session/Session.php

Temporary set `// @phpstan-ignore-next-line` in Session and Security class for `@var string 'Lax'|'None'|'Strict'`, todo: clean up in 4.1 with rector 0.9
**Checklist:**

Fix phpstan notice

---

system/CLI/Exceptions/CLIException.php
system/Cache/Exceptions/CacheException.php
system/Database/Exceptions/DataException.php
system/Encryption/Exceptions/EncryptionException.php
system/Exceptions/CastException.php
system/Exceptions/ConfigException.php
system/Exceptions/DebugTraceableTrait.php
system/Exceptions/DownloadException.php
system/Exceptions/FrameworkException.php
system/Exceptions/PageNotFoundException.php
system/Files/Exceptions/FileException.php
system/Files/Exceptions/FileNotFoundException.php
system/Format/Exceptions/FormatException.php
tests/system/DebugTraceableTraitTest.php

When using the normal way of instantiating exceptions, the `getLine` and `getFile` will show where it is raised:
```
// file1.php
$e = new Exception('');
var_dump($e->getFile()); // file1.php
```
However, when using the framework's way of calling exceptions, `getLine` and `getFile` will show where it is instantiated, i.e., inside the exception's factory static methods.
```
// file2.php
$e = FrameworkException::forCopyError();
var_dump($e->getFile()); // FrameworkException.php
```
This PR resolves this by assigning to the `$line` and `$file` property of the exception the `debug_backtrace` function's second array, which is the place where the exception is raised. For this purpose, this creates the `DebugTraceableTrait::trace()` which does that.
Fixes #4110 
**Checklist:**

Precise exception trace

---

system/Commands/Database/CreateDatabase.php

According to the [SQLite documentation](https://sqlite.org/inmemorydb.html),
> Note that in order for the special ":memory:" name to apply and to create a pure in-memory database, there must be no additional text in the filename. Thus, a disk-based database can be created in a file by prepending a pathname, like this: "./:memory:".
Thus, we need to be strictly checking if the name is `:memory:` rather than checking if it is part of the name.
**Checklist:**

Fix strict checking for SQLite3 memory filename

---

admin/framework/phpunit.xml.dist
admin/module/phpunit.xml.dist
admin/starter/phpunit.xml.dist
phpunit.xml.dist

Fixes #4114 on Xdebug 3, changed test suite name in phpunit.xml.dist from "app" to "App" seems fixed it, changed the "system" and "database" to uppercase first char for consistency.
**Checklist:**

[Develop] Fixes #4114 Cannot declare class Config\App error on running PHPUnit

---

admin/framework/phpunit.xml.dist
admin/module/phpunit.xml.dist
admin/starter/phpunit.xml.dist
phpunit.xml.dist

Fixes #4114 on Xdebug 3, changed test suite name in phpunit.xml.dist from "app" to "App" seems fixed it, changed the "system" and "database" to uppercase first char for consistency.
**Checklist:**

[4.1] Fixes #4114 Cannot declare class Config\App error on running PHPUnit

---

user_guide_src/source/dbmgmt/forge.rst

Discuss dbcreate in userguide

---

admin/framework/.gitattributes

when using --prefer-dist, it is not needed to be included.
**Checklist:**

add phpunit.xml.dist to .gitattributes for admin/framework

---

admin/framework/composer.json
admin/module/composer.json
admin/starter/composer.json
composer.json

With Composer 2, user classes with filenames not conforming to PSR4 will not be autoloaded anymore giving a warning message in the terminal. Since migrations do not need autoloading per se, we can safely dismiss this warning by specifically excluding them in the class map.
Fixes #3195 
**Checklist:**

Specifically exclude migrations from class mapping

---

system/HTTP/IncomingRequest.php
system/HTTP/Message.php
tests/system/HTTP/IncomingRequestTest.php
user_guide_src/source/incoming/incomingrequest.rst

This pull request gives more options when building a JSON API for accessing data in the JSON of a request. This was done by making getVar() smart enough to know when it is a JSON request and grab the data accordingly. This also allows for using "dot" notation for getting data outside of the root level. For more control this PR also gives a new function called getJsonVar() which allows the developer to control the format of the returned data.
**Checklist:**

Get JSON Variable

---

app/Views/errors/html/error_exception.php

- Escaping all variable and function output in `error_exception.php`.
- Use `esc()` in all places.
I can not see the message containing `<...>`.
In the current code, some variables are escaped with `ENT_IGNORE`, but 
I don't know why. It is not recommended, so I change esc()'s default.
> ENT_IGNORE
> Silently discard invalid code unit sequences instead of returning             an empty string. Using this flag is discouraged as it             » may have security implications.
https://www.php.net/manual/en/function.htmlspecialchars.php
**Checklist:**

Add missing escaping in error_exception.php

---

system/Cache/CacheInterface.php
system/Cache/Handlers/BaseHandler.php
system/Cache/Handlers/DummyHandler.php
system/Cache/Handlers/FileHandler.php
system/Cache/Handlers/MemcachedHandler.php
system/Cache/Handlers/PredisHandler.php
system/Cache/Handlers/RedisHandler.php
system/Cache/Handlers/WincacheHandler.php
system/Test/Mock/MockCache.php
tests/system/Cache/Handlers/DummyHandlerTest.php
tests/system/Cache/Handlers/FileHandlerTest.php
tests/system/Cache/Handlers/MemcachedHandlerTest.php
tests/system/Cache/Handlers/PredisHandlerTest.php
tests/system/Cache/Handlers/RedisHandlerTest.php
user_guide_src/source/libraries/caching.rst

Retrieve & Store cache
Sometimes we wish to retrieve an item from the cache, but also store a default value if the requested item doesn't exist.
Usage:
```php
$value = Service::cache->remember('sample', 3600, function () {
return [
'sample' => 'data',
];
});
``` 
**Checklist:**

Cache remember

---

user_guide_src/source/libraries/caching.rst

- fix guide not showing up after #4107
- fix typo
- convert indentation from tabs to spaces
before (#4107)
after (this PR)
**Checklist:**

fix the missing / hidden userguide

---

.github/workflows/test-rector.yml

To avoid regression like previous dependabot bump update version phpstan as rector uses phpstan as dependency.
**Checklist:**

[Rector] Run Rector when composer.json updated

---

app/Config/Mimes.php

STL files are a common 3D model file format. I've been using my own MIME config to support them but they are so standard these days we really should have this centrally.
**Checklist:**

Add STL mime support

---

system/Helpers/array_helper.php
system/Validation/Validation.php
tests/system/Helpers/ArrayHelperTest.php
tests/system/Validation/RulesTest.php
tests/system/Validation/ValidationTest.php
user_guide_src/source/helpers/array_helper.rst

Supersedes and closes #4166 .
This PR introduces a new array helper, `array_flatten_with_dots`, to flatten multidimensional arrays using the dot syntax. This is useful for validations involving multi-keys just like the predicament in the linked PR, `if_exist` validation.
to @jahmedk, can you test this one to see if it will solve your issue. I've tested this locally with your test script and the error message is now showing.
**Checklist:**

new array helper: array_flatten_with_dots

---

user_guide_src/source/general/errors.rst
user_guide_src/source/libraries/time.rst

Removes unneeded `the`.
**Checklist:**

docs: Fix double "the"

---

system/View/Parser.php
tests/system/View/ParserTest.php

- add invalid file path in ViewException message, so that we can see the invalid view name.
- fix indentation
**Checklist:**

Fix Parser file path in ViewException message is empty

---

system/Pager/PagerRenderer.php
tests/system/Pager/PagerRendererTest.php

Supersedes #4141
Add methods to get page numbers in PagerRenderer.
To generate Pager HTML that is the same as CI3's.
- getFirstPageNumber()
- getCurrentPageNumber()
- getLastPageNumber()
- getPreviousPageNumber()
- getNextPageNumber()
The template would be like this:
```php
<?php if ($pager->hasPreviousPage()) : ?>
<a href="<?= $pager->getFirst() ?>" data-ci-pagination-page="<?= $pager->getPageNumberFirst() ?>" rel="start">&laquo;First</a>
<a href="<?= $pager->getPreviousPage() ?>" data-ci-pagination-page="<?= $pager->getPreviousPageNumber() ?>" rel="prev">&lt;</a>
<?php endif ?>
```
**Checklist:**

feat: add methods to get page numbers in PagerRenderer

---

app/Config/Services.php
phpstan.neon.dist
system/Common.php
system/Config/BaseService.php
system/Config/Services.php
tests/_support/Config/Services.php
tests/system/Config/ServicesTest.php
user_guide_src/source/changelogs/v4.0.5.rst
user_guide_src/source/installation/upgrade_405.rst

Right now the only way to replace a core service is to create a new version in the extended version **app/Config/Services.php**. This means that modules and other namespaces cannot offer service replacements.
The problem is twofold:
1. All the system static methods are public which means they will match without using `__callStatic`’s lookup
2. The Services config discovery appends classes and then match the first instance, so the default system class will always match first
~~This PR provides a test case demonstrating the failure. If we want this as a "feature" (namespace replacement of core services) I could come back later and add it to this PR.~~
***
EDIT: This PR now applies the changes necessary to replace core services from any namespace. I took a different approach than outlined …

Replace Core Services

---

app/Config/Generators.php
system/CLI/GeneratorTrait.php
system/Commands/Generators/ConfigGenerator.php
system/Commands/Generators/ControllerGenerator.php
system/Commands/Generators/MigrateCreate.php
system/Commands/Generators/ScaffoldGenerator.php
system/Commands/Generators/SeederGenerator.php
system/Commands/Generators/SessionMigrationGenerator.php
system/Commands/Generators/Views/controller.tpl.php
system/Commands/Generators/Views/migration.tpl.php
system/Commands/Generators/Views/validation.tpl.php
tests/system/Commands/ModelGeneratorTest.php
tests/system/Commands/ScaffoldGeneratorTest.php
user_guide_src/source/cli/cli_generators.rst

Follow up finishes to #4121 
**Checklist:**

Finishing touches to generator refactor

---

system/BaseModel.php
tests/system/Models/InsertModelTest.php
tests/system/Models/UpdateModelTest.php

Fixes #3896.
This PR adds additional empty data checks to the `Model` `update` and `insert` methods.
These are needed because `doProtectFields` is currently called after the last empty dataset check, but can further remove elements from the `data` array.
See linked issue for details.
Will add tests later today.
**Checklist:**

Add additional empty checks after field protection for update/insert.

---

app/Config/Modules.php
user_guide_src/source/general/modules.rst

`$activeExplorers` was renamed in <https://github.com/codeigniter4/CodeIgniter4/commit/3626206ca7784bd6d63e0daecbf9484ac302319e>.
**Checklist:**

docs: fix out-of-dated property name in Config/Modules.php

---

system/HTTP/Files/FileCollection.php

Fixes #4221 
Change the way to obtain the first key from multiple file array. With array_key_first it does not matter if the first key is "0" or another
**Checklist:**

Bug #4221  FIX Undefined offset: 0 error on getFileMultiple

---

system/Pager/PagerRenderer.php
tests/system/Pager/PagerRendererTest.php

To generate the same link as the pagination in CI3, #4188 is not enough.
I also need the `$pageCount` value.
I need `$pager->getCurrentPageNumber() < $pager->getPageCount() - $surroundCount`.
Example:
```php
/**
* @var \CodeIgniter\Pager\PagerRenderer $pager
*/
$surroundCount = 2;
$pager->setSurroundCount($surroundCount);
?>
<p class="pagination">
<?php if ($pager->hasPreviousPage()) : ?>
<?php if ($pager->getPreviousPageNumber() > $surroundCount) : ?>
<a href="<?= $pager->getFirst() ?>" data-ci-pagination-page="<?= $pager->getFirstPageNumber() ?> rel="start">
&laquo;<?= lang('Pager.first') ?></a>
<?php endif ?>
<a href="<?= $pager->getPreviousPage() ?>" data-ci-pagination-page="<?= $pager->getPreviousPageNumber() ?>" rel="prev">&lt;</a>
<?php endif ?>
<?php foreach …
```

Add PagerRenderer::getPageCount()

---

system/HTTP/IncomingRequest.php
system/HTTP/Message.php
system/Validation/Validation.php
tests/system/HTTP/MessageTest.php

Based on the following discussion https://github.com/codeigniter4/CodeIgniter4/pull/4080#discussion_r571238865
**Checklist:**

[HTTP] Remove Message::isJson()

---

system/CLI/GeneratorTrait.php
tests/_support/Commands/Unsuffixable.php
tests/system/Commands/GeneratorsTest.php

The `--suffix` option was added in the refactor to allow classes to be suffixed by their corresponding component name. Although this flag is optional, there is no way to totally disregard this in other generators where the suffix is not desired. Intercepting the `$params` parsing is not possible as there is a separate route where this is processed. That said, if a user passes the `--suffix` option even if it is not in the list of allowed options, the `GeneratorTrait` will still process the suffixing.
This PR adds an internal flag to enable/disable this behavior.
**Checklist:**

Allow disabling the --suffix option

---

system/Commands/Generators/CommandGenerator.php

The original `CreateCommand` class allows custom command generators to be grouped under anything. This is especially useful for external libraries creating their own commands. However, the refactor made this impossible as it checks if the command type is `generator` then force set the group under `Generators`. This PR fixes and returns the old behavior.
**Checklist:**

Fix restriction on command group

---

user_guide_src/source/libraries/pagination.rst

The documentation for #4188 #4198
- getFirstPageNumber()
- getCurrentPageNumber()
- getLastPageNumber()
- getPreviousPageNumber()
- getNextPageNumber()
- getPageCount()
**Checklist:**

docs: add methods to get page numbers

---

contributing/guidelines.rst

Now, CI4 requires PHP 7.3
**Checklist:**

update PHP Compatibility

---

user_guide_src/source/_static/css/citheme.css

I got fed up to scroll horizontally on large tables in the Validations section of the documentation and then I added some styles to widen the page content size on large monitors (screens with more than 1100px in width and beyond) to be able to use all of my monitor size. 
**Checklist:**

Fixed documentation styles to widen the content frame on large screens

---

system/HTTP/IncomingRequest.php
tests/system/HTTP/IncomingRequestTest.php

Fixes #4263 by check path is not using `index.php` 
**Checklist:**

Fixes #4263: Fixes /*.php shows home page

---

system/HTTP/ResponseTrait.php

Other clean up php < 7.3 should covered at https://github.com/codeigniter4/CodeIgniter4/pull/4193
**Checklist:**

[API] Remove PHP < 7.3 check on ResponseTrait

---

system/HTTP/Cookie/Cookie.php

`Cookie::$defaults` is a private property.
**Checklist:**

Use self instead of static

---

app/Controllers/BaseController.php

Controller that extends `BaseController` mostly on http, I think it will be better for IDE detection with mark as `@var IncomingRequest` for its `$request` property.
**Checklist:**

[DocBlock] Add property $request with @var IncomingRequest in BaseController

---

admin/starter/tests/unit/HealthTest.php

Fixes #3977
Tests about `baseURL`:
- `baseURL` is a valid URL
- Set it in `.env` or `app/Config/App.php`
**Checklist:**

Fix HealthTest::testBaseUrlHasBeenSet()

---

system/Session/Session.php

To avoid `ErrorException : session_destroy(): Trying to destroy uninitialized session`.
**Checklist:**

Skip session_destroy() in testing

---

user_guide_src/source/libraries/validation.rst

adjust the guide the same as the source.
**Checklist:**

[libraries/validation] make userguide same as source

---

user_guide_src/source/models/model.rst

Round brackets are missing in two places and cause errors if the code is just copied and pasted.

Add round brackets in a code example

---

system/BaseModel.php
system/Database/ConnectionInterface.php
system/Database/MySQLi/Connection.php
system/Database/Postgre/Connection.php
system/Database/SQLSRV/Connection.php
system/Database/SQLite3/Connection.php
system/Model.php
system/Validation/Validation.php
system/Validation/ValidationInterface.php
user_guide_src/source/changelogs/v4.1.2.rst

There is currently a bug where `BaseModel::errors()` returns a `string` error message despite specifying `array|null` as the return type. This is causing runtime errors in `Fabricator` when trying to `implode()` error values (see discussion at #4272).
This PR traces errors back through their two potential sources: `Validation::errors()` and `ConnectionInterface::error()`. These return very different formats (which I have tightened in their docblocks) which `Model` should be handling.
Due to this bug and the preexisting formats from `Validation` and `Connection` I am updating the docblock for `BaseModel::errors` and `Model::errors` no longer to allow `null` because a) null values are never inherited from their sources, they were only set in the model, and b) they introduce …

Enforce errors format

---

system/Commands/Generators/Views/model.tpl.php

The generator refactor removed the 's' in `$useSoftDeletes`.
Fixes #4316

Fix $useSoftDeletes in model.tpl.php

---

user_guide_src/source/extending/authentication.rst

Authentication interest waxes and wanes over time. It seems like we are on the rise at the moment, for whatever reason. We remain committed to keeping authentication out of the core, but do provide [some recommendations](https://codeigniter4.github.io/CodeIgniter4/extending/authentication.html) for parties that wish to publish authentication components.
This PR defines a new provision `codeigniter/authentication-implementation` so packages can acknowledge their adherence to the recommendations above. This is a weak implementation since we have no actual interfaces but it should a) encourage people to use the recommendations, and b) help firm up some standards.
I would be open to recommendations for a stronger implementation but this seems like the most consistent solution …

[UG] Authentication provide clause

---

system/Database/ConnectionInterface.php
system/Database/MySQLi/Connection.php
system/Database/Postgre/Connection.php
system/Database/SQLSRV/Connection.php
system/Database/SQLite3/Connection.php
system/Model.php
tests/system/Models/ValidationModelTest.php

While standardizing error formats (#4312) test and I both failed to account for the fact that `ConnectionInterface::errors()` returns content even when there is no error. This extends the work from that PR to define a "no error" value. This is a little awkward because the "no error" value of `code` for each driver varies:
* MySQL: `0`
* SQLite3: `0`
* Postgres: `''`
* SQLSRV: `'00000'`
I settled on `interval(code) === 0` which is consistent with our current drivers and hopefully works with any third-party extensions.
FYI this was yet another bug in the code previous to #4312 because `BaseModel::errors()` would return `null` only when `message` was empty (`return $error['message'] ?? null;`) which was not always the case (e.g. SQLite3 returns `'not an error`'). …

Bugfix empty Model errors

---

system/CodeIgniter.php

remove unused namespace in file CodeIgniter.php
**Checklist:**

remove unused namespace

---

user_guide_src/source/database/queries.rst

The expected is `newprefix_tablename` but the steps produce `newprefixtablename`
**Checklist:**

fix setPrefix() sample

---

system/Config/Factories.php
tests/system/Config/FactoriesTest.php

This one is a bit obscure but currently `Factories` is failing to check the `instanceOf` option for classes that match an existing shared instance. An example:
```
namespace Bar\Models
class UserModel
{
}
=======
namespace Foo\Models;
class UserModel
{
}
=======
$model = Factories::model('UserModel'); // Bar\Models\UserModel
$model = Factories::model('UserModel', ['instanceOf' => 'Foo\Models\UserModel']); // Bar\Models\UserModel
```
This PR adds a test to demonstrate the issue and fixes it by running shared instances through the `verifyInstanceOf()` method.
**Checklist:**

Enforce instanceOf for factory shares

---

system/Throttle/Throttler.php
tests/system/Throttle/ThrottleTest.php
user_guide_src/source/libraries/throttler.rst

This allows to manual remove throttler buckets manually.
E.g. after paying a plan or a successful login.
**Checklist:**

Throttle: allow removal of throttler buckets

---

Vagrantfile.dist

Without this change, vagrant will not install php.
It will have an error 'Unable to locate package php7.3' during `vagrant up`

Allow php3.7 installation

---

tests/system/Database/Live/SQLite/AlterTableTest.php

When we run this test case twice, it fails the second time.
See <https://github.com/codeigniter4/CodeIgniter4/pull/4176#issuecomment-784608210>.
**Checklist:**

Fix Database/Live/SQLite/AlterTableTest.php 

---

system/Session/Handlers/DatabaseHandler.php
user_guide_src/source/libraries/sessions.rst

Choose better types for the ci_sessions table: 
* for Postgres, use type BYTEA for binary data. Compared to storing base64-encoded text, this takes less space
* update the user guide to suggest using type INET for storing IP addresses in Postgres. This type offers input error checking and specialized operators and functions
* for both MySQL and Postgres, use type timestamp instead of integer. This type is easier to work with when analyzing session activity.
**Checklist:**

Choose better types for the ci_sessions table

---

app/Config/Logger.php
system/Log/Handlers/ErrorlogHandler.php
tests/system/Log/Handlers/ErrorlogHandlerTest.php
user_guide_src/source/general/logging.rst

A simple Log Handler for error_log.
We use this Handler to log to stdout for Docker Container.
**Checklist:**

simple error_log Log Handler

---

system/Test/CIUnitTestCase.php
system/Test/DatabaseTestTrait.php
tests/system/Database/Live/DatabaseTestTraitCaseTest.php

This splits the properties out of DatabaseTestTrait to resolve trait conflicts introduced during #4335. I also took the liberty of moving the test methods back to `CIUnitTestCase` since that seemed to be the original intent.
This PR leverages two new internal properties to work around the property conflict: `setUpMethodsDatabase` and `tearDownMethodsDatabase`. I've marked them as internal because I would like these to go away when we get around to refactoring the entire test suite.
**Checklist:**

Resolve DB test trait conflicts

---

app/Views/errors/html/error_404.php
app/Views/errors/html/error_exception.php
system/Database/BaseConnection.php
tests/system/Database/BaseConnectionTest.php

This PR changes the error output for DB connections to be more verbose than the generic `Unable to connect to the database.`. This is an attempt to reduce questions on the forum regarding this despite raising the logging threshold to `4`.
`php spark migrate --all`
**Checklist:**

Use verbose DB output for errors

---

system/Common.php
system/Helpers/form_helper.php
tests/system/Helpers/FormHelperTest.php
tests/system/Helpers/URLHelperTest.php

Supersedes and closes #4298
fixes #4235 
**Checklist:**

Fix incorrect html output caused by escaping

---

system/Helpers/form_helper.php

-since in_array is now being enforced as strict, and the option keys are being forced as strings, the selected items also need to be forced as strings.
**Checklist:**

fix form dropdowns

---

user_guide_src/source/extending/authentication.rst

A slight extension to the Composer provision as recommended by @agungsugiarto.
**Checklist:**

Authentication: Add Packagist link

---

system/BaseModel.php
system/Model.php

Fixes the IDE errors reported by Intelephense on `Model` and `BaseModel`. This is on `$db` and `$validation`.
Fixes #4329 
**Checklist:**

Fixes IDE errors on Model/BaseModel

---

system/Config/BaseService.php
system/Config/Services.php
system/bootstrap.php

In the current implementation, there is no way to extend the class `CodeIgniter`.
This PR enables users to extend `CodeIgniter`.
**Checklist:**

Add Services::codeigniter()

---

system/HTTP/Cookie/Cookie.php

Per Sections 15 and 16 of RFC 6265, handling of special cookie prefixes, `__Secure-` and `__Host-` is done case-sensitively.
**Checklist:**

Use case-sensitive matching for special cookie prefixes

---

system/HTTP/Response.php
tests/system/HTTP/ResponseCookieTest.php

Fixes the notice.
> Notice: Undefined property: Config\App::$cookieSameSite
See <https://forum.codeigniter.com/thread-78693.html>.
**Checklist:**

Fix Undefined property: Config\App::$cookieSameSite

---

system/Test/ControllerTester.php

Fixes a bug where `ControllerTester` would set any Exception code as an HTTP code which could cause a lot of debugging confusion:
> CodeIgniter\HTTP\Exceptions\HTTPException: 0 is not a valid HTTP return status code
**Checklist:**

Bugfix invalid HTTP codes

---

tests/system/Cache/Handlers/FileHandlerTest.php
tests/system/Cache/Handlers/MemcachedHandlerTest.php
tests/system/Cache/Handlers/PredisHandlerTest.php
tests/system/Cache/Handlers/RedisHandlerTest.php

Every now and then tests fail because the cache handlers' metadata tests fail, particularly on the `mtime` key. The current tests assert that the time saved in `mtime` is the same with the current time. But occasionally this assertion fails by a second because the assertion used is too strict - it allows no margin of error.
This PR relaxes the assertion to allow the edge case of 1 sec difference. Since more often the result is `0` the tests will still pass (`0 === 1 || 0 < 1`).
**Checklist:**

Fix volatile metadata testing in cache handlers

---

system/Router/Router.php
tests/system/Router/RouterTest.php

Fixes #4294 
I have made a minor tweak to CodeIgniter\Router::validateRequest so that dashes in a subdirectory are mapped to underscores if `translateURIDashes`= `true`. This appears to correctly auto-route requests when you have a dash in the URI that corresponds to a controller directory.
**Checklist:**

updated Router to properly translate uri dashes that map to controller subdirs

---

system/HTTP/IncomingRequest.php
system/HTTP/RequestTrait.php

When using the flag parameter in the filter_var function, the default value was incorrectly passed. 
By default, null is passed, but an array or integer is expected.
Soft type casting may mask future problems. 
Changes:
* Updated variable types in docBlock 
* Added nullable type for filter parameter 
* Defined a default value for the filter and flag arguments if passed null.
* The filter and flag arguments are cast to the expected types. 
* Adjusted the data validation condition based on the changes above. 
**Checklist:**

Fix: filter_var usage

---

system/Database/Forge.php

`BaseConnection::$dataCache` is an array of cached data of varying formats. Unfortunately this is not enumerated anymore so it is easy to mistake the format. This PR fixes just such a bug, where `table_names` was assumed to have keys for each table when in fact it is just a list of strings.
This fixes a rare issue where calling `createTable()` immediately after `resetDataCache()` would incorrectly set the list of tables to just the single newly create table. Go ahead, ask me how long I spent tracking this one down 🙄
**Checklist:**

Bugfix data cache

---

user_guide_src/source/database/call_function.rst
user_guide_src/source/database/connecting.rst
user_guide_src/source/database/events.rst
user_guide_src/source/database/examples.rst
user_guide_src/source/database/helpers.rst
user_guide_src/source/database/transactions.rst
user_guide_src/source/testing/controllers.rst
user_guide_src/source/testing/fabricator.rst

Add missing TOC.
**Checklist:**

docs: add missing TOC

---

system/Helpers/form_helper.php
tests/system/Helpers/FormHelperTest.php

Helper function form_multiselect $data parameter type should be mixed as form_dropdown. 
So when passed array it should handle the array instead of error.
**Checklist:**

Helper form_multiselect $data param as array

---

system/Test/CIUnitTestCase.php
system/Test/Constraints/SeeInDatabase.php
tests/system/Database/Live/DatabaseTestTraitCaseTest.php

Refactored the seeInDatabase assertion into a Constraint so we can provide context when it fails by showing potentially similar rows within the database.

Add more info to `seeInDatabase` assertions

---

system/Helpers/url_helper.php
tests/system/Helpers/URLHelperTest.php

Handle `base_url("0")` to ensure point to `/0` with compare to empty string instead of using `empty($uri)` check.
**Checklist:**

[Helper] Fixes base_url("0") and site_url("0") to correctly point to /0

---

system/Config/BaseService.php
system/Config/Factories.php

Cherry-pick from https://github.com/codeigniter4/CodeIgniter4/pull/4426/commits/abae0fd9bc92794995191f49c81e84fac08dcba6
**Checklist:**

[Rector] Fixes rector notice use

---

system/Test/CIUnitTestCase.php
system/Test/DatabaseTestTrait.php
user_guide_src/source/testing/overview.rst

An alternative to #4422 (see the description of the problem there). I think this simpler solution is the better choice. I do think `class_uses_recursive()` is probably costly so I took advantage still of storing the results for a little performance boost.
**Checklist:**

Prioritize database trait methods

---

phpstan.neon.dist
system/Cache/Exceptions/CacheException.php
system/Cache/Exceptions/ExceptionInterface.php
system/Exceptions/DebugTraceableTrait.php
system/HTTP/Cookie/Cookie.php
system/HTTP/Cookie/CookieStore.php

Removes PHPStan ignoreErrors: `Unsafe usage of new static()`.
See <https://phpstan.org/blog/solving-phpstan-error-unsafe-usage-of-new-static>.
**Checklist:**

Remove PHPStan ignoreErrors: Unsafe usage of new static()

---

system/Test/CIUnitTestCase.php
system/Test/DatabaseTestTrait.php

This PR moves the database test methods back to `DatabaseTestTrait` and reorganizes the class a little better. This brings it in line with the test support class organization that is firming up: methods on traits, properties on `CIUnitTestCase`.
**Checklist:**

Database trait methods

---

system/Test/CIUnitTestCase.php
system/Test/FeatureTestCase.php
user_guide_src/source/changelogs/v4.1.2.rst
user_guide_src/source/testing/feature.rst

Continuing the trend of a core test class with supplemental traits, this PR moves `FeatureTestCase` properties (already made optional when we split out `FeatureTestTrait`) into `CIUnitTestCase` and deprecated the class in favor of using the trait directly on an extension of `CIUnitTestCase`.
**Checklist:**

Traitify Feature Tests

---

system/Test/FeatureTestTrait.php

Presumably for performance reasons, `RouteCollection` skips re-loading routes from `App`. This works until feature tests reset services and reload routes. Then the collection fails to discover App routes during `discoverRoutes()`.
I think the root of this issue is because the original Routes service is initiated during bootstrap (see **system/Test/bootstrap.php** at the bottom) so there may be a better solution by moving that into the test classes somewhere, but I spent so long tracking this down I have to get it written all out or I will forget it.
EDIT: My thought was correct. I've replaced my original solution with this variant. Feature Tests will now use the App initialized version of `RouteCollection` instead of the raw service version.
**Checklist:**
- n/a User guide …

Repeat App Routes

---

system/Router/RouteCollection.php

Fixes #4435 by supplying an initial string placeholder so `$HTTPVerb` will never be `null`.
**Checklist:**

Default HTTPVerb

---

system/Database/BaseConnection.php
system/Database/Query.php
tests/system/Database/Builder/WhereTest.php
tests/system/Database/Live/WhereTest.php

Fixes #4443 by changing the regex used by `Query` on how it recognizes a named bind by including parentheses.
**Checklist:**

Fix Query named bind recognition

---

composer.json

The interface is moved to `symplify/rule-doc-generator-contracts` package. While wait for next rector release, we need to require-dev it.
**Checklist:**

[Rector] Fix rector notice Interface Symplify\RuleDocGenerator\Contract\DocumentedRuleInterface not found

---

system/Test/FilterTestTrait.php
tests/system/Test/FilterTestTraitTest.php
user_guide_src/source/testing/controllers.rst

One small tweak to the recent `FilterTestTrait` addition, to specify the actual return type since it is a `Closure`.
**Checklist:**

FilterTestTrait: Closure

---

.github/workflows/test-phpunit.yml
composer.json
phpunit.xml.dist

Use `johnkary/phpunit-speedtrap` to document slow tests in the framework's test suites. This is the starting point to optimize the speed of our tests.
Ref: #4438 
**Checklist:**

Use speedtrap to document slow tests

---

system/Language/Language.php

Makes `getTranslationOutput` overridable by child classes.
**Checklist:**

Language: getTranslationOutput: make method overridable by child classes

---

composer.json
rector.php
system/Autoloader/FileLocator.php
system/CLI/BaseCommand.php
system/Database/BaseBuilder.php
system/Database/BaseConnection.php
system/Database/BasePreparedQuery.php
system/Database/BaseUtils.php
system/Database/Config.php
system/Database/ConnectionInterface.php
system/Database/Database.php
system/Database/Forge.php
system/Database/Migration.php
system/HTTP/CURLRequest.php
system/HTTP/DownloadResponse.php
system/HTTP/IncomingRequest.php
system/HTTP/Negotiate.php
system/HTTP/Request.php
system/Images/Handlers/BaseHandler.php
system/Log/Handlers/BaseHandler.php
system/Router/RouteCollection.php
system/Router/Router.php
system/Test/FeatureResponse.php
system/Throttle/Throttler.php
system/Validation/FileRules.php
system/Validation/Validation.php
system/View/Parser.php

[Rector] Update rector to ^0.10

---

system/Database/BaseBuilder.php
system/Model.php

`Model` has been causing PHPStan segmentation faults for me for months (e.g. https://github.com/tattersoftware/codeigniter4-forms/pull/7/checks?check_run_id=2179115051). I've always found ways to change the code to work around it but I finally hit a wall. After hours of digging I determined the issue is the recursive `@mixin`s: `Model` mixes in `BaseBuilder` which mixes in `Model`. The `@mixin` on `BaseBuilder` is actually a mistake, and I think was done to solve the issue of Model line 173 where PHPStan detects the `select()` as coming from `BaseBuilder` (because of the `@mixin`) so baulks at `asArray()` which does not exist on `BaseBuilder`. I think simply ignoring the line is the best approach, but we could break the chain up and specify types if that feels better. …

Remove erroneous mixin

---

rector.php

in Rector 0.10, the option to include files in config was removed, as included files are now processed by static reflection.
There is addition of  `BOOTSTRAP_FILES` in `0.10.2` to make include constants, class aliases or custom autoloader working again. ref https://github.com/rectorphp/rector/pull/5964
**Checklist:**

[Rector] Using Option::BOOTSTRAP_FILES

---

system/Test/FeatureResponse.php

Our `FeatureResponse` constructor allows `null` input but very clearly relies on having a valid `ResponseInterface`. ~~For now this PR provides a fallback when `null` is provided to prevent breaking changes but IMO the parameter should be made mandatory at some point.~~ This PR removes the `null` option.
Along those lines, this is part of some bigger test response changes I have in the works but I didn't want to bundle this bugfix with that PR.
**Checklist:**

Feature Response null

---

system/BaseModel.php
system/Model.php
tests/system/Models/GeneralModelTest.php
user_guide_src/source/models/model.rst

I frequently find myself extending the constructor on module models to do some additional configuration. That makes for some awkward repeating of parameters, like:
```
/**
* @param ConnectionInterface $db
* @param ValidationInterface $validation
*/
public function __construct(ConnectionInterface &$db = null, ValidationInterface $validation = null)
{
// Call the module constructor
parent::__construct($db, $validation);
// Do whatever I needed to do
}
```
With the split into `BaseModel` and `Model` this gets even more uncomfortable, as additional extensions of `BaseModel` likely won't have the same constructor parameters.
This PR defines a new "event" during `BaseModel::__construct()` that checks for an `initModel()` method which will allow developers to handle model …

Add Model::initialize()

---

system/Test/TestResponse.php
tests/system/Test/FeatureTestCaseTest.php

This is a slight "addendum" to the `TestResponse` PR. Fixes a few things:
1. `assertSessionHas()` uses a nice display for failed assertions, however `$value` is not always a string which can lead to errors like "array to string conversion". This PR limits the value display to when it is actually a string. You still get the PHPUnit comparison, e.g.:
```
The value of 'session-var' does not match expected value.
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
Array (
0 => Array (
-        'class' => 'foobar'
+        'class' => 'success'
'text' => 'New factory created successfully.'
)
)
```
2. `assertJSONExact()` accepts an `array` which it will automatically convert to JSON which is very handy for testing RESTful responses. This PR expands that to …

Tweaks to TestResponse

---

system/Test/ControllerTester.php
system/Test/TestResponse.php

Fixes a few incorrect types on test classes. Presumably the missing imports on the trait are because PHPStan expects traits to be mixed in.
**Checklist:**

Test Types

---

system/Debug/Toolbar/Views/toolbarloader.js.php

Chromium browsers raise a scary-looking but non-blocking error in the console if a referenced header is null. The issue is well-explained [here](https://trackjs.com/blog/refused-unsafe-header/).
The current check for the header only looks for a non-null value, which seems insufficient to prevent Chrome raising this error. 
I have added to the logic here to include a check for the header itself first to hopefully avoid the console error.

Address Chromium 'Unsafe header' error with 

---

system/Test/ControllerTester.php

`ControllerTester` catches any exceptions and wraps them into a `TestResponse`. If the error is a valid HTTP status code then it will set it on the response, otherwise it ignores them. This ignoring means that any regular exception (i.e. developer mistake) will return a `TestResponse` with `200` status and a `null` body - very misleading.
This PR re-throws exceptions that are non-HTTP statuses to prevent masking underlying issues.
**Checklist:**

Cease catching non-HTTP errors

---

system/HTTP/IncomingRequest.php
tests/system/HTTP/IncomingRequestTest.php

The getVar method is compatible with version 4.0.4 #4381 
In the current version, when the request is the get method and the content-type is json, the $_REQUEST parameter cannot be obtained 
**Checklist:**
**Notes**
- Increase the length of the judgment body 
- Add unit tests under json and get methods

The getVar method is compatible with version 4.0.4 

---

phpunit.xml.dist
system/Router/RouteCollection.php
system/Test/ControllerResponse.php
system/Test/ControllerTestTrait.php
system/Test/FeatureTestCase.php
system/Test/FeatureTestTrait.php
tests/_support/Controllers/Popcorn.php
tests/system/HomeTest.php
tests/system/Test/ControllerTestTraitTest.php
tests/system/Test/FeatureTestTraitTest.php
user_guide_src/source/changelogs/v4.1.2.rst
user_guide_src/source/installation/upgrade_412.rst
user_guide_src/source/testing/controllers.rst

In preparation for the next release, this PR reverts the changes to "Feature" and "Controller" testing to leave them deprecated in place. The unreleased `FeatureTestTrait` can now return a `TestResponse` directly, and this PR introduces an alternate trait for controller testing, `ControllerTestTrait` (more consistent with our new naming scheme too). With these changes we can separate the deprecated classes and remove them from coverage and start using their updated versions.
Also fixes a number of logic errors in `execute()` for controller testing:
* `getStatusCode()` can never be empty
* Controller buffered output should be prepended to response bodies, not discarded
* `null` bodies should be allowed
**Checklist:**

Tests deprecate

---

system/Cache/Handlers/FileHandler.php

Cache's `FileHandler` will attempt to se the file mode after writes using `chmod()`. This is already allowed to fail (i.e. return `false`) since files can be writable but not owned, however some circumstances can actually cause a fatal error:
```
chmod(): Operation not permitted
at SYSTEMPATH/Cache/Handlers/FileHandler.php:127
Backtrace:
1    [internal function]
CodeIgniter\Debug\Exceptions()->errorHandler()
2    SYSTEMPATH/Cache/Handlers/FileHandler.php:127
chmod()
```
This PR catches any throwable and log and ignores the exception.
**Checklist:**

Allow chmod failures on cache write

---

app/Config/Events.php

`Toolbar` is already disabled under CLI, but the listener events still trigger. This PR excludes those Events from triggering as well, which could prevent some performance hits (especially if developers add their own collectors).
**Checklist:**

Shortcircuit toolbar on CLI

---

system/Database/Query.php

Fixes #4518 
The thing is the Database Collector call `Query::debugToolbarDisplay` to return a nicely formatted SQL string. However, that method will erroneously call `$this->compileBinds()` everytime. The problem with this approach is that the DB operation had run before the toolbar display collection so all queries have been compiled. Calling it again will give false positives for bind markers when special syntaxes uses the bind marker (such as Postgres' JSON operations).
What we really need is the compiled final query string. Since the compiling was done before collection, we can be sure that it is already set. However, for the sake of prudence, we'll put up a guard if the requested string is not yet initialized and then we'll call `compileBinds()` right away.
ping …

[Query] Do not recompile binds if already compiled

---

rector.php
system/Encryption/Handlers/SodiumHandler.php
system/Entity.php
tests/system/CommonFunctionsTest.php
tests/system/Database/Live/SQLite/AlterTableTest.php
tests/system/HTTP/CURLRequestTest.php
tests/system/Helpers/FormHelperTest.php
tests/system/View/ParserFilterTest.php
tests/system/View/ParserTest.php

Remove argument value, if it is the same as default value with `RemoveDefaultArgumentValueRector` rector rule.
**Checklist:**

[Rector] Apply RemoveDefaultArgumentValueRector

---

app/Views/errors/html/error_404.php
app/Views/errors/html/error_exception.php

Fix #4533 
Changed the order of `nl2br` and `esc`
**Checklist:**

Fix html formatting for exceptions and errors

---

app/Config/App.php
app/Config/Cookie.php
env
system/Cookie/CloneableCookieInterface.php
system/Cookie/Cookie.php
system/Cookie/CookieInterface.php
system/Cookie/CookieStore.php
system/HTTP/Response.php
system/Security/Security.php
system/Session/Session.php
tests/system/Cookie/CookieTest.php
tests/system/HTTP/ResponseCookieTest.php
tests/system/Security/SecurityTest.php
tests/system/Session/SessionTest.php

While we are taking a step forward to make config folder separated as much as possible, Cookie class should have it's own config file

Create Config::Cookie Class

---

system/CodeIgniter.php
system/Exceptions/FrameworkException.php

If `intl` is among the list of missing extensions, then it doesn't make sense to use `intl`'s message formatting features to format the missing extension exception. If so, we default to plain message.
**Checklist:**

Use message directly if intl is not available

---

rector.php

It previously skipped due hang on check `tests/system/Models`, it working ok in latest rector 0.10.4.
**Checklist:**

[Rector] Enable check tests/system/Models

---

rector.php
system/CLI/GeneratorTrait.php
system/Config/BaseService.php
system/Files/File.php
system/HTTP/Negotiate.php
system/HTTP/URI.php

Change array_push() to direct variable assign with `ChangeArrayPushToArrayAssignRector` rector rule.
**Checklist:**

[Rector] Apply Rector: ChangeArrayPushToArrayAssignRector

---

system/CodeIgniter.php

Without intl extension check, it previously got the following output if no intl:
```bash
Your PHP version must be {0} or higher to run CodeIgniter. Current version: {1}%  
```
**Checklist:**

Check intl extension loaded on check min PHP version

---

composer.json
rector.php

In rector 0.10.4, previously, auto imports options is disabled due change spacing in `@param`, `@throws`. It fixed in latest rector.
**Checklist:**

[Rector] Update Rector 0.10.6, re-enable auto imports

---

rector.php
tests/system/CommonFunctionsTest.php
utils/Rector/RemoveDefaultArgumentValueRector.php

This rule is removed in latest rector `dev-main` ref https://github.com/rectorphp/rector/pull/6148
**Checklist:**

[Rector] Copy RemoveDefaultArgumentValueRector to utils/Rector

---

system/Cache/CacheInterface.php
system/Cache/Handlers/BaseHandler.php
system/Cache/Handlers/DummyHandler.php
system/Cache/Handlers/FileHandler.php
system/Cache/Handlers/MemcachedHandler.php
system/Cache/Handlers/PredisHandler.php
system/Cache/Handlers/RedisHandler.php
system/Cache/Handlers/WincacheHandler.php
system/Test/Mock/MockCache.php
tests/system/Cache/Handlers/DummyHandlerTest.php
tests/system/Cache/Handlers/FileHandlerTest.php
tests/system/Cache/Handlers/MemcachedHandlerTest.php
tests/system/Cache/Handlers/PredisHandlerTest.php
tests/system/Cache/Handlers/RedisHandlerTest.php
user_guide_src/source/libraries/caching.rst

Maintaining a big number of cache keys with dependencies to each other can be a hassle with the current existing methods in the cache service.
This feature allows for deleting multiple cache items at once using a [glob pattern](https://en.wikipedia.org/wiki/Glob_(programming)):
```php
cache()->deleteMatching('some_prefix*');
cache()->deleteMatching('*some_suffix');
// etc.
```
To handle cache dependencies, CI4 users would be able to structure their cache items with the same key prefix and delete the whole "pack" in one go.
Initially discussed in this post: https://forum.codeigniter.com/thread-77789-post-380976.html and on [Slack](https://codeigniterchat.slack.com/archives/C47FK3GRY/p1617614168038800).
**Limitations**
The implementation is only effective for **file** and …

feat(cache): add deleteMatching method to remove multiple cache items

---

system/Validation/Validation.php
tests/system/Validation/ValidationTest.php

Fixes #4521 
This is a patch fix only for the `if_exist` rule and DOES NOT yet cover other rules.
**Checklist:**

Fix dot notation for if_exist

---

system/Helpers/array_helper.php
tests/system/Helpers/ArrayHelperTest.php
user_guide_src/source/helpers/array_helper.rst

Sometimes an array key can contain a dot. In this case, you cannot access the value of this key using dot notation.
This PR makes available keys containing a dot, with dot notation.
```php
$data = [
'foo' => [
'bar.baz' => 23
],
];
// Returns: 23
$barBaz = dot_array_search('foo.bar\.baz', $data);
```
**Checklist:**

Feature: Escaping array dot notation

---

.github/workflows/test-phpunit.yml
system/Database/SQLSRV/Connection.php

Debugging SQL Server in Actions

---

system/Config/BaseConfig.php
tests/system/Config/BaseConfigTest.php
tests/system/Config/DotEnvTest.php
tests/system/Config/fixtures/.env
tests/system/Config/fixtures/loose.env
user_guide_src/source/changelogs/v4.1.2.rst

Fixes #4559 
Closes #4556 
**Checklist:**

Prefix calls to getenv() during config resolution

---

system/Debug/Toolbar.php
system/View/Parser.php

Fixes #4408 
Fixes #4412 
**Checklist:**

Add compatibility for strict types

---

system/Helpers/test_helper.php
tests/system/Database/Live/FabricatorLiveTest.php
user_guide_src/source/testing/fabricator.rst

Added a parameter to the fake() test helper so that you can use it without saving the object in the database.
**Checklist:**

Non-persistent fake

---

phpstan.neon.dist
system/Autoloader/Autoloader.php

Optimizations include:
- Make loading classmaps as a separate method
- Load classmaps from Composer, if available
**Checklist:**

Optimizations for Autoloader

---

system/Helpers/array_helper.php
system/Validation/Validation.php
tests/system/Helpers/ArrayHelperTest.php
tests/system/Validation/ValidationTest.php
user_guide_src/source/changelogs/v4.1.2.rst

Fixes #4510 
This changes the behavior of `_array_search_dot`. Currently, the function returns early when it matched a non-null element in its value traversal, leaving the remaining elements in the loop as untouched. This PR accumulates the finds in an array, filters out the nulls. If resulting array contains only one element, then we'll return that element instead of an array in order to preserve BC. Otherwise, an array containing matches will be returned.
@luispastendev, can you check this? This passes locally on your use case .
**Checklist:**

Fix validation of array data

---

rector.php

Alternative of https://github.com/codeigniter4/CodeIgniter4/pull/4600 with skip JsonThrowOnError & StringifyStrNeedlesRector.
**Checklist:**

[Rector] Apply Full PHP 7.3 Rector Set List (Skip JsonThrowOnErrorRector & StringifyStrNeedlesRector)

---

.github/workflows/test-rector.yml
utils/Rector/UnderscoreToCamelCaseVariableNameRector.php

[Rector] Refactor UnderscoreToCamelCaseVariableNameRector with latest Rector compatible code

---

system/Common.php
system/Cookie/CloneableCookieInterface.php
system/Cookie/Cookie.php
system/HTTP/ResponseTrait.php
system/Security/Security.php
system/Session/Session.php
system/Test/Mock/MockSession.php
tests/system/Cookie/CookieStoreTest.php
tests/system/Cookie/CookieTest.php
user_guide_src/source/libraries/cookies.rst

Since we use php min version `7.3`, why not passing all cookie options to the constructor itself directly.
Removed `Cookie::create` while `new Cookie` do the same thing directly.
Renamed `Cookie::getExpiresTimestamp` to `Cookie::getExpires` to be short and refer to it's property,
Renamed `Cookie::withExpiresAt` to `Cookie::withExpires` to fit it's property and also it may return expired cookie.
I think this is last change to new Cookie class should be done before the upcoming release
@paulbalandan what do you think about this changes? is it keeps the interface "fluent"? Thanks in advance

Simplify Cookie Class

---

app/Config/Autoload.php
system/Autoloader/Autoloader.php
system/Config/AutoloadConfig.php
tests/_support/Autoloader/functions.php
tests/system/Autoloader/AutoloaderTest.php
user_guide_src/source/changelogs/v4.1.2.rst
user_guide_src/source/general/modules.rst

This PR now allows `Autoloader` to load **non-class files** beside classes. This is similar to Composer's `files` array in composer.json. A user will now need to put the list of paths to the files in `Config\Autoload::$files`` and CI4 will autoload these on autoload registration.
Fixes #4447 
**Checklist:**

[Feat][Autoloader] Allow autoloading non-class files

---

phpunit.xml.dist
system/Controller.php
system/Database/ModelFactory.php
system/Exceptions/CastException.php
system/HTTP/Message.php
system/HTTP/Request.php
system/HTTP/Response.php
system/Router/Router.php
system/Test/ControllerResponse.php
system/Test/ControllerTester.php
system/Test/FeatureTestCase.php

[Test] Use @codeCoverageIgnore for deprecated class/method

---

system/Cookie/Cookie.php
system/HTTP/Response.php
system/Security/Security.php
system/Session/Session.php
tests/system/Cookie/CookieTest.php

Add fallback for Config\Cookie

---

system/ThirdParty/PSR/Log/AbstractLogger.php
system/ThirdParty/PSR/Log/LogLevel.php
system/ThirdParty/PSR/Log/LoggerAwareInterface.php
system/ThirdParty/PSR/Log/LoggerAwareTrait.php
system/ThirdParty/PSR/Log/LoggerInterface.php
system/ThirdParty/PSR/Log/LoggerTrait.php
system/ThirdParty/PSR/Log/NullLogger.php

The `Psr\Log` code in **ThirdParty** is a few versions old. This PR updates to the latest code from the PSR repo.
**Checklist:**

Patch Log code

---

system/Cache/Handlers/DummyHandler.php
system/Cache/Handlers/FileHandler.php
system/Cache/Handlers/PredisHandler.php
system/Cache/Handlers/RedisHandler.php
tests/system/Cache/Handlers/DummyHandlerTest.php
tests/system/Cache/Handlers/FileHandlerTest.php
tests/system/Cache/Handlers/PredisHandlerTest.php
tests/system/Cache/Handlers/RedisHandlerTest.php
user_guide_src/source/libraries/caching.rst

The deleteMatching implementation for the RedisHandler is not deleting all matching cache items as intended.
This PR is meant to fix that bug and fix the tests that were supposed to fail.
Also, the deleteMatching method now returns the number of deleted items as it is offers better feedback than true/false (mainly for testing purposes).
Thanks to @benjaminbellamy for the heads up!
**Checklist:**

fix(cache): add check for redis empty results in deleteMatching

---

system/I18n/Time.php
tests/system/I18n/TimeTest.php
user_guide_src/source/changelogs/v4.1.2.rst

Many libraries use `DateTimeInterface` to allow `DateTime` or `DateTimeImmutable`. In a few cases in `Time` our functions are already compatible with either yet the docblocks limit it to `DateTime`. This PR expands the use for the interface, with one deprecation for an explicit method type.
**Checklist:**

Expand Time for interface

---

system/Cache/CacheInterface.php
system/Cache/Handlers/DummyHandler.php
system/Cache/Handlers/FileHandler.php
system/Cache/Handlers/MemcachedHandler.php
system/Cache/Handlers/PredisHandler.php
system/Cache/Handlers/RedisHandler.php
system/Cache/Handlers/WincacheHandler.php

Adjusts a number of "mixed" return types to match their handler and User Guide specifications.
**Checklist:**

Cache Returns Types

---

system/Cache/CacheInterface.php
system/Cache/Handlers/FileHandler.php
system/Cache/Handlers/MemcachedHandler.php
system/Cache/Handlers/PredisHandler.php
system/Cache/Handlers/RedisHandler.php
system/Cache/Handlers/WincacheHandler.php
user_guide_src/source/changelogs/v4.1.2.rst
user_guide_src/source/libraries/caching.rst

`CacheInterface::getMetadata()` thus far returns a generic array of info "dependent on each adapter", as well as `false` or `null` for missing items (also dependent on each adapter). This PR attempts to standardize the expected return values while still leaving the `false` in place for now. Additionally:
* Fixes a bug where "expire" was not always an absolute time value
* Fixes a discrepancy between relative and absolute TTL values
* Adds support for `null` values to "expire" when a TTL was specified as "never expire"
**Checklist:**

Cache getMetadata() Format

---

system/Debug/Toolbar.php

This is the very simple method to avoid memory leak issue #4137 when entity objects with circular references are passed to the view. 
**Checklist:**

Debug/Toolbar - Memory issue fix

---

system/ComposerScripts.php

Refactor `CodeIgniter\ComposerScripts` to make it a little performant while allowing new direct dependencies to be added with ease.
This class is technically a "development" class so this can be changed at will without worrying for BC breaks.
**Checklist:**

Refactor ComposerScripts

---

system/Cache/Handlers/DummyHandler.php
system/Cache/Handlers/FileHandler.php
system/Cache/Handlers/MemcachedHandler.php
system/Cache/Handlers/PredisHandler.php
system/Cache/Handlers/RedisHandler.php
system/Cache/Handlers/WincacheHandler.php

- Allow covariant return types in docblocks of Cache handlers
- Simplify other code
**Checklist:**

[Cache] Allow covariant returns and optimize code

---

composer.json

Latest "nikic/php-parser": "4.10.5" seems temporary cause error notice in rector repo, ref https://github.com/rectorphp/rector/runs/2495148646#step:6:6 . 
This patch pin to 4.10.4 which is working. We can use dependabot to ensure `php-parser`, `phpstan`, and `rector` version run ok on every new release.
**Checklist:**

[Rector] Pin "nikic/php-parser": "4.10.4"

---

user_guide_src/source/incoming/filters.rst

Removes the reference to `ajax` filters as an available method since it is not implemented. 
Long time coming :)

[ci skip] Remove ajax filter reference from docs. Fixes #2314

---

system/HTTP/URI.php
tests/system/HTTP/URITest.php

This is "stage one" for some bugfixes in URI resolution. This changes the internal `removeDotSegments()` method to static and fixes a logic bug (`ltrim()` could never leave a single slash).
**Checklist:**

URI::removeDotSegments()

---

system/HTTP/IncomingRequest.php
system/HTTP/URI.php
tests/system/API/ResponseTraitTest.php
tests/system/HTTP/URITest.php
user_guide_src/source/changelogs/v4.1.2.rst

"Stage two" of URI changes, this PR backs off some of the heavy-handed coercing that `URI::__toString()` does to create "project URLs". IMO `URI` should not be in the business of dealing with `baseURL` at all, but since this is currently the case we can't remove it entirely. Also improves `IncomingRequest`'s interactions with `URI` to detect the "current" URL, and fixes a bug where scheme inconsistencies could create looping redirects.
Note: This PR relies on #4644
**Checklist:**

Internal URI handling

---

system/View/View.php
tests/system/View/ViewTest.php
tests/system/View/Views/nested_section.php
user_guide_src/source/changelogs/v4.1.2.rst
user_guide_src/source/outgoing/view_layouts.rst

Based on http://forum.codeigniter.com/thread-79132.html
This fix allows the use of nested sections in templates. 
**Checklist:**

Fix: Nested sections rendering

---

system/Cache/Handlers/BaseHandler.php
system/Cache/Handlers/FileHandler.php
system/Cache/Handlers/MemcachedHandler.php
system/Cache/Handlers/PredisHandler.php
system/Cache/Handlers/RedisHandler.php
system/Cache/Handlers/WincacheHandler.php
tests/_support/Cache/RestrictiveHandler.php
tests/system/Cache/Handlers/BaseHandlerTest.php
tests/system/Cache/Handlers/FileHandlerTest.php
user_guide_src/source/libraries/caching.rst

Cache keys are currently a free-for-all, though the specification is much tighter than that. Additionally, some handlers have limits on the length of key that can be used. So far the only one I know for sure is `FileHandler`, because using too long of a key fails to create the file since it is invalid in the filesystem.
This PR adds cache key validation and hashing to address the above issues. Note that I am *not* a cache expert, so if someone with more knowledge or experience wants to chime in I would be grateful. For example, the restricted characters were based on PSR-6 but some handlers may actually allow broader key usage than that.
**Checklist:**

Cache Key Validation

---

composer.json

This ensure check `admin/setup.sh` exists before run it as `admin` directory is on `.gitattributes`.
https://github.com/codeigniter4/CodeIgniter4/blob/7546ee04a55071d4731c77346deb47843f397c87/.gitattributes#L12
To avoid usage of download and run composer update with got error: 
```bash
Script bash admin/setup.sh handling the post-update-cmd event returned with error code 127
```
**Checklist:**

[Scipts] Ensure admin/setup.sh exists before run bash admin/setup.sh

---

system/I18n/Time.php
user_guide_src/source/libraries/time.rst

The `instance()` is deprecated
**Checklist:**

change instance() to  createFromInstance()

---

composer.json

#4650 does not work on Windows.
```console
> CodeIgniter\ComposerScripts::postUpdate
> if [ -f "admin/setup.sh" ]; then bash admin/setup.sh; fi
Script if [ -f "admin/setup.sh" ]; then bash admin/setup.sh; fi handling the post-update-cmd event returned with error code 1
```
Fixed:
```console
> CodeIgniter\ComposerScripts::postUpdate
> bash -c "if [ -f admin/setup.sh ]; then bash admin/setup.sh; fi"
```

[Scripts] Make sure bash script still works in Windows

---

system/Database/MigrationRunner.php
tests/system/Commands/MigrationIntegrationTest.php

Fixes #4579 
Replaces and closes #4584 
**Checklist:**

Unify migration message format for `migrate` and `migrate:rollback`

---

system/Config/BaseConfig.php
user_guide_src/source/general/configuration.rst

Fixes #3845 so **.env** files will always have priority over values from a Registrar. This has the added bonus that a Registrar can provide a configuration template for non-existent properties which **.env** could then fill.
I beefed up the docs on Registrars as well, since IMO implicit Registrars are way more useful and were not even covered correctly.
**Checklist:**

Registrar and .env priority

---

system/Config/BaseService.php
tests/system/CommonSingleServiceTest.php
tests/system/Config/ServicesTest.php
user_guide_src/source/testing/overview.rst

Frequently I find myself doing acrobatics to accomplish this. It is past time this was added: the ability to reset a single Service by its name.
**Checklist:**

Reset Single Service

---

spark
system/CLI/Console.php
tests/system/CLI/ConsoleTest.php
user_guide_src/source/cli/cli_commands.rst

Fixes #3918. I went with the simple solution, but I'm open to expanding on this down the road (like @paulbalandan's environment variable option) as anything could work alongside this.
**Checklist:**

Spark header suppression

---

system/Test/CIUnitTestCase.php

Instead of the generic `Failed asserting that false is true.`, display the message that was failed to be logged.
**Checklist:**

Use descriptive failure message for `assertLogged`

---

system/Cache/Handlers/FileHandler.php
tests/system/Cache/Handlers/FileHandlerTest.php

It turns out that `PHP_MAXPATHLEN` refers to internal PHP handling, not applicable to the local filesystem. From my research most filesystems cap at 255 so I'm reverting to that value.
**Checklist:**

Limit cache filenames

---

system/I18n/Time.php
tests/system/I18n/TimeTest.php

Fixes #3951. The test case for this was actually incorrect, since `strtotime()` uses the current default timezone. I confirmed that fixing the test case broke the previous implementation, and the update implementation passes the fixed test.
**Checklist:**

UTC Time from timestamp

---

composer.json
rector.php
tests/system/Helpers/DateHelperTest.php

Remove unused private properties with `RemoveUnusedPrivatePropertyRector` rector rule.
**Checklist:**

[Rector] Apply Rector: RemoveUnusedPrivatePropertyRector

---

composer.json

https://github.com/codeigniter4/CodeIgniter4/pull/4671#issuecomment-838476350 temporary add symplify/composer-json-manipulator fixed in 0.10.22.
**Checklist:**

[Rector] Update rector to 0.10.22, remove symplify/composer-json-manipulator

---

composer.json
rector.php
system/Cache/Handlers/RedisHandler.php

Update to rector 0.11.2. Rector now prefixed by default, so need `symplify/package-builder` for string format converter usage in 
https://github.com/codeigniter4/CodeIgniter4/blob/43e0e9611b7e527a4b927127fc6f26a1c6d123a5/utils/Rector/UnderscoreToCamelCaseVariableNameRector.php#L16
Also update phpstan to 0.12.86
**Checklist:**

[Rector] Update rector 0.11.2 and phpstan 0.12.86

---

system/Test/Mock/MockCache.php

When testing with `MockCache` using an unknown cache agent it is impossible to determine what happens in the cache without using private property inspectors. This PR expands `MockCache::cacehInfo()` to return the current keys so it is easy to make assertions like "did use cache".
**Checklist:**

MockCache::getCacheInfo()

---

system/Entity/Cast/URICast.php
system/Entity/Entity.php
tests/system/EntityTest.php
user_guide_src/source/models/entities.rst

Adds `uri` as a cast option for Entities.
**Checklist:**

Add URI cast

---

system/CodeIgniter.php

For historic purposes with TravisCI, if `CodeIgniter` detected a continuous development environment it would lock the environment to `testing`. This is no longer needs with GitHub Actions and prevents CodeIgniter applets from being run under CI, so I am removing it.
Fixes #4428.
**Checklist:**

Allow CI Environments

---

user_guide_src/source/intro/psr.rst

Now that the Cache PSR repo is official, updates the UG.
**Checklist:**

Add reference to cache repo

---

system/Config/BaseService.php
system/Config/Services.php

This fixes #4483 
Replacing `static::foobar()` with `\Config\Services::foobar()` (https://regex101.com/r/QyahlU/1).
**Checklist:**

Fix new service replacement service provider precedence on core factory implementations

---

system/BaseModel.php
system/Model.php
user_guide_src/source/changelogs/v4.1.2.rst

This makes it possible to use protected idValue() method from outside of the model to get the id value of the entity. 
**Checklist:**

BaseModel - Add public getIdValue() method

---

system/CLI/BaseCommand.php
system/CLI/CommandRunner.php
system/CLI/Commands.php
tests/system/CLI/CommandRunnerTest.php

Optimize CommandRunner and Commands

---

system/Database/Forge.php
system/Database/MySQLi/Forge.php
system/Database/Postgre/Forge.php
system/Database/SQLite3/Forge.php
tests/system/Database/Live/ForgeTest.php

Fixes #4693 .
It appears the Base Forge provides use of `$null` property but all DB extensions uses the underscored version `$_null`. Then the Base Forge uses `$this->null` so I don't know which to follow. For now, I followed the extensions' work.
**Checklist:**

Fix nullable type not showing in SQL string

---

admin/setup.sh

Greetings 👋 ,
the Composer `post-update-cmd` failed on my machine because the `admin/setup.sh` script tried to copy the pre-commit hook into `.git/hooks`, which didn't exist yet.
:octocat:

Create .git/hooks directory if not already present

---

tests/system/Database/Live/DbUtilsTest.php

Greetings 👋,
I'm currently setting up this repo and its test suite on my local machine (PHP 8.0.5, MySQL 8.0.23) and am coming across some problems while I'm learning the ropes 😅.
With the help of @MGatner I was able to connect the test suite to my local database by adding this snippet to my `phpunit.xml`:
```xml
<phpunit>
<php>
<env name="database.tests.strictOn" value="true"/>
<env name="database.tests.hostname" value="localhost"/>
<env name="database.tests.database" value="codeigniter"/>
<env name="database.tests.username" value="root"/>
<env name="database.tests.password" value=""/>
<env name="database.tests.DBDriver" value="MySQLi"/>
<env name="database.tests.DBPrefix" value="tests_"/>
</php>
</phpunit>
```
Since I like to name my local databases after the project I'm working with, I …

Check for configured instead of hard-coded database in DbUtilsTest

---

system/Cache/Handlers/FileHandler.php

Cache's `FileHandler` still chokes in some circumstances when files are unreadable or non-existent. This PR routes all file access through `getItem()` and adds some extra robustness to make sure `Cache` won't take down the whole app when it has problems.
**Checklist:**

Cache robustness

---

system/Database/SQLSRV/Result.php

Detected by latest rector dev-main that I run in my local dev.
**Checklist:**

Remove unused private rowOffset property in Database/SQLSRV/Result.php

---

system/Helpers/filesystem_helper.php
tests/system/Helpers/FilesystemHelperTest.php
user_guide_src/source/helpers/filesystem_helper.rst

Adds a couple more functions to the `filesystem_helper`: `directoy_mirror()` (from @paulbalandan's `ComposerScripts PR) as `samefile()`.
**Checklist:**

Additional File functions

---

rector.php
system/Helpers/filesystem_helper.php
utils/Rector/RemoveErrorSuppressInTryCatchStmtsRector.php

Based on https://github.com/codeigniter4/CodeIgniter4/pull/4719 Closes https://github.com/codeigniter4/CodeIgniter4/pull/4719 This rector rule will only remove `@` inside try catch stmts.
**Checklist:**

[Rector] Add custom Rector Rule: RemoveErrorSuppressInTryCatchStmtsRector rector rule

---

.github/workflows/test-phpunit.yml
tests/system/Database/Live/ForgeTest.php

Greetings 👋 ,
I'm running PHP 8 and MySQL 8 on my machine and noticed one failing test (`ForgeTest::testAddFields()`, it seems that the `max_length` cannot be retrieved for `BIGINT` fields).
https://github.com/codeigniter4/CodeIgniter4/blob/6da0e5bdc6213edc40ef040de5cbfdcc45a03ead/tests/system/Database/Live/ForgeTest.php#L617-L623
Here's the failing test on my fork: https://github.com/jeromegamez/CodeIgniter4/runs/2643301715?check_suite_focus=true
In order to be able to show the error, I started by adding it to the test matrix (but am not sure how to change the workflow name to reflect it, since all matrix combinations start all types of databases).
<s>The added `mysql8` branch in the triggers is only so that I could run the action, this would of course be removed before merging, if you …

Test with MySQL 8

---

system/Common.php
tests/system/CommonFunctionsTest.php

Fixes #4699 to cover scripts running in `php-cgi`.
**Checklist:**

Expand CLI detection

---

system/Database/Seeder.php
system/Format/XMLFormatter.php

I noticed that `$seeder = new $class($this->config);` was called twice and that this could be an opportunity to shorten the `Seeder::call()` method a bit - similarly in the XMLFormatter 💪 
:octocat:

Deduplicate code

---

system/Helpers/text_helper.php

The relevant part is in the `excerpt()` function, the rest was automatically applied by phpcbf.
The condition previously was
```php
if (isset($phrase)) {
// ...
} elseif (!isset($phrase)) {
// ...
}
```
Replacing the second `elseif` with just `else` also removes the need to ignore the following lines with PHPStan 🥳
:octocat:

Remove explicit condition that is always true

---

system/HTTP/IncomingRequest.php

It appears that some PHP web servers do not guarantee the `SCRIPT_NAME` as a substring of `REQUEST_URI`. From consulting other frameworks, it is still safe to determine the relative path this way, but we need to ensure the segments before checking.
**Checklist:**

Fix truncated SCRIPT_NAME

---

rector.php
system/CLI/CLI.php
system/Database/Forge.php
system/Database/MySQLi/Result.php
system/Database/SQLSRV/Result.php
system/Database/SQLite3/Result.php
system/Database/SQLite3/Table.php
system/Email/Email.php
system/HTTP/RequestTrait.php
system/Session/Session.php
system/View/Table.php

Since the minimum PHP version is PHP 7.3, we can make use of the language features it provides 🥳, in this case:
```php
$x = $y ?? null
```
instead of
```php
$x = isset($y) ? $y : null
``` 
:octocat:

Replace `isset()` with the `??` null coalesce operator

---

system/Config/Factories.php
system/Helpers/test_helper.php
system/Test/CIUnitTestCase.php
system/Test/ControllerTestTrait.php
system/Test/ControllerTester.php
system/Test/Fabricator.php

Some class imports were missing - they were only used in PHPDocs, but it helps IDEs with not complaining about it and autocompletion 😅 
:octocat:

Add missing imports

---

system/Common.php

After checking existence of `REMOTE_ADDR` and `HTTP_USER_AGENT` keys in `$_SERVER`, additionally check if the `$argv` is set. Please note this will fail if the ini directive `register_argv_argc` is turned on for non-CLI requests.
**Checklist:**

Additional check for `$argv` variable when detecting CLI

---

system/Cookie/Cookie.php
tests/system/HTTP/ResponseCookieTest.php
user_guide_src/source/libraries/cookies.rst

- Fixes a bug in Cookie constructor where you cannot set a falsy value for `HttpOnly` and `Secure` attributes. Also removed extra code for `$defaults` merging.
- Fixes some errors in the docs
**Checklist:**

Fix setting of value in Cookie's flag attributes

---

system/HTTP/CURLRequest.php
tests/system/HTTP/CURLRequestTest.php

Fixes #4707, where `CURLRequest`'s `baseURI` could get muddled with `App::$baseUrl` during `URI::__toString()`.
**Checklist:**

Format URI directly

---

system/CodeIgniter.php
system/HTTP/RedirectResponse.php
system/Helpers/url_helper.php
system/Log/Handlers/ChromeLoggerHandler.php
system/Pager/Pager.php
system/Pager/PagerRenderer.php
tests/system/HTTP/RedirectResponseTest.php
tests/system/Helpers/URLHelper/CurrentUrlTest.php
user_guide_src/source/libraries/uri.rst

Due to the following: https://github.com/codeigniter4/CodeIgniter4/blob/7eef1f708750fe11089e5eb056e7c817a691d0fa/system/HTTP/URI.php#L681-L702
... `URI::__toString()` is only suitable for project URLs, because any partial match of `baseURL` will be a false positive. Following on #4715, this PR removes the remaining string casts of `URI` when they are not explicitly a project URI.
**Checklist:**

Replace URI string casts

---

contributing/internals.rst
system/Commands/Utilities/Environment.php
tests/system/Commands/EnvironmentCommandTest.php

Adds a spark command to show/change the current environment. Changes will be effected in the next script execution.
```console
$ php spark env
$ php spark env development
```
**Checklist:**

Add environment spark command

---

app/Config/Cache.php
user_guide_src/source/libraries/caching.rst

I am constantly adding a default Cache Time To Live value to modules and projects that interact with the cache. It's quite frustrating that the framework interface and handlers have this value hard-coded, so we cannot change that in version 4, but supplying this in the config file gives an opportunity for developers to implement it themselves (and to replace the hard-coded interface in version 5).
**Checklist:**

Add default TTL

---

system/Database/SQLite3/Table.php
tests/system/Database/Live/SQLite/AlterTableTest.php

The correct Forge attribute for handling `null` columns is "null", not "nullable": https://github.com/codeigniter4/CodeIgniter4/blob/1b5f05e63a6489a90672b1d4a9f04d2c69730f56/system/Database/Forge.php#L995
Super scary to me that this has always been wrong and never been reported. 😳 Fixes #4746
**Checklist:**

SQLite3 "nullable"

---

composer.json
rector.php
system/Pager/Pager.php

Move variable declaration near its reference with `MoveVariableDeclarationNearReferenceRector` rector rule. It needs latest rector `0.11.7`. I updated phpstan/phpstan to `0.12.88` as well.
**Checklist:**

[Rector] Apply Rector: MoveVariableDeclarationNearReferenceRector

---

system/Autoloader/Autoloader.php
tests/system/Autoloader/AutoloaderTest.php

include_once is not needed on get class with no namespace for `Autoloader::loadClass()` call as it try to get `app\Config` that autoloaded.
**Checklist:**

[Autoloader] include_once is not needed on Autoloader::loadClass() with no namespace

---

rector.php
system/Cache/Handlers/BaseHandler.php
system/Cache/Handlers/FileHandler.php
system/CodeIgniter.php
system/Cookie/CookieInterface.php
system/HTTP/ResponseInterface.php
system/HTTP/URI.php
system/Log/Handlers/ErrorlogHandler.php
tests/system/Validation/FormatRulesTest.php
utils/Rector/PassStrictParameterToFunctionParameterRector.php

Add `@var` to Class Constants with `VarConstantCommentRector` rector rule.
**Checklist:**

[Rector] Apply Rector: VarConstantCommentRector

---

rector.php
system/Cache/Handlers/BaseHandler.php
system/Cache/Handlers/FileHandler.php
system/CodeIgniter.php
system/Cookie/CookieInterface.php
system/HTTP/ResponseInterface.php
system/HTTP/URI.php
system/Log/Handlers/ChromeLoggerHandler.php
system/Log/Handlers/ErrorlogHandler.php
tests/system/Validation/FormatRulesTest.php
utils/Rector/PassStrictParameterToFunctionParameterRector.php
utils/Rector/RemoveVarTagFromClassConstantRector.php
utils/Rector/UnderscoreToCamelCaseVariableNameRector.php

I created new custom rector rule `RemoveVarTagFromClassConstantRector` to remove `@var` from class const per this discussion https://github.com/codeigniter4/CodeIgniter4/pull/4759#issuecomment-852125720
**Checklist:**

[Rector] Remove @var from class constant

---

system/Database/SQLSRV/Connection.php

Description
We have moved `sqlsrv_configure('WarningsReturnAsErrors', 0);` prior to `sqlsrv_connect($this->hostname, $connection)` because if there is a warning or an information message establishing the connection, it will treat it as an error and Codeigniter will throw an exception. Driver's configuration should be set prior the connection.
Example:
Before change, exception shows up (image1): "Unable to connect to the database. Main connection [SQLSRV]: Driver's SQLSetConnectAttr failed", but it is thrown by information message (IM006), as we can see when executing `sqlsrv_errors()` (image2).
Image1:
Image2:
After change: Connection is established without problems:
**Checklist:**

Set WarningsReturnAsErrors = 0 before connection

---

system/Database/Query.php

Another pass to fixing named binds recognition by adding a negative lookahead for `:=` types.
Fixes #4760 .
Supersedes and closes #4764 
**Checklist:**

Expand Query named binds recognition

---

rector.php
system/Database/BaseBuilder.php
system/Database/SQLSRV/Builder.php
system/HTTP/UserAgent.php
system/Session/Handlers/FileHandler.php
system/View/Parser.php

`preg_quote()` delimiters were missing in some places - some of them are potential bugs, for example, when `#` was used in the pattern, but `preg_quote()` was defaulting to `/`.
:octocat:

Use/Fix `preg_quote()` delimiters

---

system/Autoloader/Autoloader.php

`$path` is given as parameter and overridden in case `$namespace` is an array. While it doesn't make a difference when executing the method, it could introduce side effects in the future in case the method is changed and the override is overlooked 🤞 
:octocat:

Don't override `$path` parameter

---

system/Database/BaseBuilder.php

`$value` is given as a parameter and overridden when iterating over the `$keys`. While it doesn't make a difference when executing the method, it could introduce side effects in the future in case the method is changed and the override is overlooked 🤞
:octocat:

Don't override `$value` parameter

---

app/Views/errors/html/error_exception.php
system/BaseModel.php
system/CLI/CLI.php
system/Database/BaseConnection.php
system/Database/BasePreparedQuery.php
system/Debug/Toolbar/Collectors/Config.php
system/Email/Email.php
system/HTTP/ResponseTrait.php
system/Images/Handlers/ImageMagickHandler.php
system/Test/Mock/MockConnection.php
utils/PhpCsFixer/CodeIgniter4.php

Using constants instead of methods saves some OPCode steps 💪 
[`PHP_OS_FAMILY` has a smaller, predefined set of possible values](https://www.php.net/manual/en/reserved.constants.php#constant.php-os-family)
:octocat:

Use constants instead of functions

---

system/Database/MySQLi/PreparedQuery.php
system/Database/SQLite3/PreparedQuery.php
system/Email/Email.php
tests/system/Filters/fixtures/Role.php
utils/PhpCsFixer/CodeIgniter4.php

In order to avoid surprises (e.g. `mysqli_*` aliases were dropped in PHP 5.4 or `magic_quotes_runtime` was dropped in PHP 7.0), we should not rely on alias functions at all.
:octocat:

Replace alias functions with origins

---

system/Common.php

`safe_mode` was removed in PHP 5.4 🙈 
:octocat:

Remove removed `safe_mode` ini Option

---

system/Session/Handlers/DatabaseHandler.php
tests/system/API/ResponseTraitTest.php
tests/system/Database/Migrations/MigrationRunnerTest.php
tests/system/Filters/FiltersTest.php
tests/system/HTTP/HeaderTest.php
tests/system/Models/ValidationModelTest.php
tests/system/Pager/PagerTest.php
tests/system/Validation/RulesTest.php
utils/PhpCsFixer/CodeIgniter4.php

This enables the `cast_spaces` fixer and set to ensure there's a single space between the cast and the casted variable.
**Checklist:**

Ensure single space between cast and variable

---

rector.php
system/HTTP/CURLRequest.php
system/I18n/Time.php
system/Validation/FormatRules.php

Simplify regex pattern to known ranges with `SimplifyRegexPatternRector` rule.
**Checklist:**

[Rector] Apply Rector: SimplifyRegexPatternRector

---

utils/PhpCsFixer/CodeIgniter4.php

Whitespace around the keywords of a class, trait or interfaces definition should be one space.
**Checklist:**

Enable `class_definition` fixer

---

system/Model.php

The following change was made to `Model::__get()` to simplify code with null coalescence: https://github.com/codeigniter4/CodeIgniter4/commit/ace9df0da6e3a09937e7d38c40016e31cae22d9f#diff-1a690370bdbdc5997068f9ff210bacef314eeb65d1df73af206783ce055d8d1d
However, because of the magic accessors on `BaseModel` and `Connection` this did not end up being logically equivalent. Reverting that part of the PR.
**Checklist:**

Revert Model coalesce

---

tests/system/API/ResponseTraitTest.php
tests/system/Database/Builder/DeleteTest.php
tests/system/Database/Builder/UpdateTest.php
tests/system/Format/XMLFormatterTest.php
tests/system/Helpers/FormHelperTest.php
tests/system/Helpers/HTMLHelperTest.php
tests/system/View/ParserFilterTest.php
tests/system/View/ParserTest.php
utils/PhpCsFixer/CodeIgniter4.php
utils/Rector/RemoveErrorSuppressInTryCatchStmtsRector.php
utils/Rector/RemoveVarTagFromClassConstantRector.php
utils/Rector/UnderscoreToCamelCaseVariableNameRector.php

This enables:
- Heredoc indentations (available as of PHP 7.3)
- Converts heredoc syntaxes to nowdoc if not involving variables
**Checklist:**

Heredocs-related rules

---

app/Config/Publisher.php
system/Commands/Utilities/Publish.php
system/Config/Publisher.php
system/Language/en/Publisher.php
system/Publisher/Exceptions/PublisherException.php
system/Publisher/Publisher.php
tests/_support/Config/Registrar.php
tests/_support/Publishers/TestPublisher.php
tests/system/Commands/PublishCommandTest.php
tests/system/Helpers/FilesystemHelperTest.php
tests/system/Publisher/PublisherInputTest.php
tests/system/Publisher/PublisherOutputTest.php
tests/system/Publisher/PublisherRestrictionsTest.php
tests/system/Publisher/PublisherSupportTest.php
user_guide_src/source/libraries/index.rst
user_guide_src/source/libraries/publisher.rst

This PR introduces a new component: the Publisher Class. This combines a handful of different solutions I've been using in my modules to solve a variety of problems:
1. How do I maintain project assets with version dependencies?
2. How do I manage uploads and other "dynamic" files that need to be web accessible?
3. How can I update my project when the framework or modules change?
4. How can the framework/modules publish their modified content to a project?
`Publisher` has two functional modes: it can be instantiated and used dynamically with runtime input, or can use predefined workflows staged for automatic discovery. With either approach developers use fluent-style methods to build a payload manifest and then one of the "write" commands to deliver the files. For example, …

Publisher Class

---

tests/system/Test/BootstrapFCPATHTest.php
utils/PhpCsFixer/CodeIgniter4.php

- Ensures all PHP magic constants (`__FILE__`, `__DIR__`, etc.) and methods (`__sleep()`, `__get()`, etc.) are written in the correct case.
- Sets the `mb_str_functions` fixer as `false` (off) by default
**Checklist:**

Define initial "m" rules

---

system/Commands/Server/Serve.php

The min php version check already moved to CodeIgniter class.
**Checklist:**

[Commands] Remove unused $minPHPVersion property at Serve command

---

system/Common.php

CLI detection is a problematic case as it involves a lot of factors to consider, which may not work at all times at all platforms. This attempts to make detection independent of the interface (i.e. no longer depending on the value of `PHP_SAPI`) but instead rely on other variables.
Fixes #4843 
Fixes #4848 
**Checklist:**

Make CLI detection as interface independent as possible

---

system/Database/MySQLi/Connection.php
user_guide_src/source/database/results.rst

Added public property $resultMode to MySQLi's Connection.php. Then added the property to MySQLi's query method. This allows for the use of MYSQLI_USE_RESULT for unbuffered queries. The unbuffered queries will save a lot of memory when running large queries. Also updated user guide to demonstrate use.
**Checklist:**

Added MySQLi resultMode and updated user guide

---

composer.json
rector.php

- Update PHPStan to 0.12.90
- Update Rector to 0.11.21
- Remove deprecated `Option::ENABLE_CACHE` in rector config as enabled by default.
**Checklist:**

Update to latest PHPStan and Rector and Rector config compat

---

system/Debug/Toolbar.php

Closes and supersedes #4863 to target the 4.2 branch.

[Debug] [4.2] Sort timeline elements by start and duration.

---

system/CLI/GeneratorTrait.php
tests/system/Commands/CommandGeneratorTest.php

Namespace extracted by GeneratorTrait should always end in backslash

---

system/Cache/Handlers/FileHandler.php
system/Cache/Handlers/PredisHandler.php
tests/system/Cache/Handlers/FileHandlerTest.php
tests/system/Cache/Handlers/MemcachedHandlerTest.php
tests/system/Cache/Handlers/PredisHandlerTest.php
tests/system/Cache/Handlers/RedisHandlerTest.php

After answering a question on Slack I noticed some small bugs in the Predis and File cache handler.
* In Predis, we couldn't set the cache as permanent even if we specified `0` as TTL.
* In the File cache, we were getting the incorrect `expire` metadata when a given key was stored as permanent.
This PR fixes these bugs.
**Checklist:**

Fix bug with respecting TTL in Predis and File cache

---

system/Session/Handlers/DatabaseHandler.php
tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
tests/_support/Database/Seeds/CITestSeeder.php
tests/system/Database/Live/MetadataTest.php
tests/system/Session/Handlers/DatabaseHandlerTest.php

This PR fixes a bug in MySQLi with the timestamp column.
Ref: #4807
**Checklist:**

Fix database session bug with timestamp in MySQLi

---

system/Commands/Generators/MigrationGenerator.php
system/Commands/Generators/Views/migration.tpl.php

This PR fixes the invalid table structure that is generated by migrations: `php spark make:migration --session`
Ref: #4827
**Checklist:**

Fix for generating session table structure via migrations

---

system/Files/Exceptions/FileException.php
system/Files/FileCollection.php
system/Language/en/Files.php
system/Language/en/Publisher.php
system/Publisher/Exceptions/PublisherException.php
system/Publisher/Publisher.php
tests/system/Files/FileCollectionTest.php
tests/system/Publisher/PublisherInputTest.php
tests/system/Publisher/PublisherSupportTest.php
user_guide_src/source/libraries/files.rst
user_guide_src/source/libraries/publisher.rst

This PR extracts a lot of the file operations from the recent `Publisher` PR into a dedicated class: `FileCollection`. `Publisher` then becomes an extension of this class, while allowing the core functionality to stand on its own for gather files and `File` objects from across the filesystem.
**Checklist:**

FileCollection

---

system/Database/MySQLi/Connection.php

This PR fixes MySQLi SSL connection - a certificate should not be required to establish a secure connection.
Closes #4616
**Checklist:**

Fix mysqli ssl connection

---

system/Debug/Toolbar.php
system/Debug/Toolbar/Views/toolbar.css
system/Debug/Toolbar/Views/toolbar.js

This is an extension of #4865.
This PR intrduces structuring of the debugbar timeline elements.
They are now sorted in a parent-children structure like this:
[
'name'     => 'parentTimer',
'start'    => '0',
'duration' => '10',
'children' => [
[
'name'     => 'childTimer',
'start'    => 2,
'duration' => 4
]
]
]
These elements are then echoed recursively and embedded in JS collapsible table rows.
For now, the `Controller` parent element is unfolded by default, as this will likely alway be the biggest and last part of the timeline.
One thing I am not yet fond of is the flexible indentation of the `Timer` name in the current state. That is, each deeper level is indented by an additional 10px, which I think might pose some issue on very narrow screens.
**Demonstration** …

[Debug] [4.2] Structure debug toolbar timeline with collapsible elements.

---

app/Views/errors/html/error_exception.php
system/Commands/Encryption/GenerateKey.php
system/Config/DotEnv.php
system/Database/BaseBuilder.php
system/Database/Postgre/Builder.php
system/Database/SQLSRV/Builder.php
system/Debug/Toolbar.php
system/Format/XMLFormatter.php
system/Helpers/form_helper.php
tests/system/CLI/CLITest.php
tests/system/HTTP/MessageTest.php
tests/system/Helpers/CookieHelperTest.php
tests/system/Helpers/FormHelperTest.php
tests/system/Log/LoggerTest.php
utils/PhpCsFixer/CodeIgniter4.php

_(excerpted from the fixers' summary and description)_
- `explicit_string_variable`
Converts implicit variables into explicit ones in double-quoted strings or heredoc syntax. The reasoning behind this rule is the following: - When there are two valid ways of doing the same thing, using both is confusing, there should be a coding standard to follow - PHP manual marks `"$var"` syntax as implicit and `"${var}"` syntax as explicit: explicit code should always be preferred - Explicit syntax allows word concatenation inside strings, e.g. `"${var}IsAVar"`, implicit doesn't - Explicit syntax is easier to detect for IDE/editors and therefore has colors/highlight with higher contrast, which is easier to read Backtick operator is skipped because it is harder to handle; you can use …

Convert to explicit those implicit string variables

---

composer.json

Fix the notice error `Call to a member function getType() on null`
https://github.com/codeigniter4/CodeIgniter4/runs/2934093327#step:10:5
**Checklist:**

Update to rector 0.11.29

---

user_guide_src/source/database/queries.rst
user_guide_src/source/database/query_builder.rst

The current version of the user guide presents some confusion making it appear that the custom string option of the `where` function in the Query Builder would escape the data. That was incorrect. It appears that NO escaping is done in that case. 
The user guide has been updated to make it very clear that user-supplied data MUST be escaped manually when using that option.

Updated Query Build custom string option for where to remove make it clear the values do not get escaped.

---

system/HTTP/IncomingRequest.php
tests/system/HTTP/IncomingRequestTest.php

Fix getVar() method when trying to get JSON variable that does not exists

---

system/CodeIgniter.php

This PR gives a little change to the execution time collection, by only overwriting the `startTime` property of the `CodeIgniter4` object, if it is not yet set.
This property gets first set here in the constructor:
https://github.com/codeigniter4/CodeIgniter4/blob/9ceb5e3c023afd083ebeb9dfb8b47e5bcabf6770/system/CodeIgniter.php#L160
After that, it gets overwritten from `bootstrap.php` during `$app->run()` via:
https://github.com/codeigniter4/CodeIgniter4/blob/9ceb5e3c023afd083ebeb9dfb8b47e5bcabf6770/system/CodeIgniter.php#L514
I am not sure what was the goal here. In the current state, we basically restart the "total execution" timer and possibly miss some ms (i.e., the time that `$app->initialize();` takes).  This is not really helpful I think.
As far as I can tell, the part now included …

[4.2][Debug] Do not overwrite startTime.

---

system/CodeIgniter.php

This PR adds timers for the `before` and `after` filters.
During #4863, I found that significant gaps in the timeline can be produced by the `filters`.
As far as I could find, these are the only parts missing in the benchmarking.
For now, I opted to
- start the timers in `CodeIgniter4::handleRequest`,
- not divide the filter timers further into the individual filters.
In the current state, the `Filters` timer is displayed even if no filters are defined for the `$position`, this is not really the best solution in my opinion, however, `$filters->run` is called  each time anyway, so why not log those ms, too.
The alternative would be to run `$filters->initialize($uri)` in `handelRequest` and then check the `$filters->filtersClass` property for defined filters.
On another note, I would like …

[4.2][Debug] Add benchmarking for filters.

---

admin/css/debug-toolbar/_graphic-charter.scss
admin/css/debug-toolbar/_mixins.scss
admin/css/debug-toolbar/_theme-dark.scss
admin/css/debug-toolbar/_theme-light.scss
admin/css/debug-toolbar/toolbar.scss
system/Debug/Toolbar/Views/toolbar.css

In #4886, the toolbar styles were updated, but I failed to notice that they are defined in `admin` in `scss` files.
This PR pulls the changes over to the preprocessor files.
**Checklist:**

[4.2] Add toolbar timer styles to sass files.

---

system/CLI/CLI.php
system/Debug/Toolbar.php
system/Entity/Entity.php
system/Files/File.php
system/HTTP/URI.php
system/I18n/Time.php
system/Pager/Pager.php
system/Validation/ValidationInterface.php
tests/system/Validation/FormatRulesTest.php
utils/PhpCsFixer/CodeIgniter4.php

- Inside class or interface element `self` should be preferred to the class name itself.
- Inside a final class or anonymous class `self` should be preferred to `static`.
- ~Instructions must be terminated with a semicolon.~
- Simplify if control structures that return the boolean result of their condition.
**Checklist:**

Define initial "s" rules

---

utils/PhpCsFixer/CodeIgniter4.php

Aside from #4933 , this defines the last remaining built-in fixers from php-cs-fixer into our ruleset. However, these are turned off by default.
- global_namespace_import, native_function_invocation, native_constant_invocation are depending on #4890 / #4899 
- header_comment is off by default. this is turned on by using `Factory::forLibrary()`
- use_arrow_functions is available only for PHP7.4+ code
- void_return adds the void return typehint so this breaks signature
**Checklist:**

Define remaining rules

---

system/CodeIgniter.php

I came across the `displayPerformanceMetrics()` function in `system/CodeIgniter.php` and noticed that the `memory_usage ` tag, is not getting replaced by this function. Although the php doc describes it does.
This PR removes the `memory_usage` mention from the comment as this behaviour is intended: see issue #197.
**Checklist:**

Remove 'memory_usage' from 'displayPerformanceMetrics()' comment

---

utils/PhpCsFixer/CodeIgniter4.php

- The type of @return annotations of methods returning a reference to itself must the configured one.
- Single line @var PHPDoc should have proper spacing.
**Checklist:**

Normalize var and return annotations

---

system/Commands/Utilities/Environment.php
system/Entity/Cast/ArrayCast.php
system/Entity/Cast/BooleanCast.php
system/Entity/Cast/CSVCast.php
system/Entity/Cast/DatetimeCast.php
system/Entity/Cast/FloatCast.php
system/Entity/Cast/IntegerCast.php
system/Entity/Cast/JsonCast.php
system/Entity/Cast/ObjectCast.php
system/Entity/Cast/StringCast.php
system/Entity/Cast/TimestampCast.php
system/Entity/Cast/URICast.php
utils/PhpCsFixer/CodeIgniter4.php

- Fixes casing of PHPDoc tags.
- Forces PHPDoc tags to be either regular annotations or inline.
**Checklist:**

Fix tag casing and tag types

---

system/Entity/Entity.php
user_guide_src/source/models/entities.rst

fixes [forum link](https://forum.codeigniter.com/thread-79649-post-388554.html#pid388554)
fix the wrong Entity-Datamap usage instructions.
**Checklist:**

fix the wrong Entity-Datamap usage instructions.

---

composer.json
rector.php

- Update rector to 0.11.37
- Clean up rector skip config as already handled in latest 0.11.37 and for strict parameter skip, already handled in coding standard.
**Checklist:**

[Rector] Update rector to 0.11.37, clean up config

---

system/Validation/Validation.php
tests/system/Validation/ValidationTest.php

[Validation] Fix splitting of string rules

---

composer.json

Rector is now using pinned PHPStan:
https://github.com/rectorphp/rector/blob/fd9f6abc9e539c011613f88f1da0e8d557ef2ab5/composer.json#L10
So require-dev PHPStan with `^` should be safe already.
**Checklist:**

[PHPStan] Using PHPStan ^0.12.91

---

phpstan.neon.dist
system/Files/File.php
tests/system/Files/FileTest.php

- Proper fix for phpstan error in #4967 (explode does not accept an empty string delimiter which the code does not take into account)
- Add tests for the `File::getDestination` method where this error arises
**Checklist:**

Fix properly the phpstan error in 0.12.93

---

.github/workflows/deploy-apidocs.yml

The current apidocs workflow is largely based on the `apidoc` script. Up until now, there's a typo in the script preventing the removal of the contents of the `api/docs` folder:
> rm -rf api/docs*
As you can see, instead of deleting the contents this tries to delete files starting with `api/docs` which doesn't exist. This PR fixes that and makes the output more verbose.
**Checklist:**

Fix API repo preparation step

---

.github/workflows/deploy-apidocs.yml

Apparently, #4969 only fixed half of the problem (which is the `git reset`). However, the actual contents of `api/docs` are not removed really. Analysing the logs from the verbose `rm` and `mkdir`, it shows that:
> HEAD is now at 13c5ef1 Update README.md
> mkdir: created directory 'api'
> mkdir: created directory 'api/docs'
This means that instead of deleting the contents of `docs` in the root `api`, it instead looks at `api/docs` at the root `api`, a problem of relative paths. This attempts to fix the issue completely.
Successful run (in pull request context):
https://github.com/codeigniter4/CodeIgniter4/actions/runs/1075571421
**Checklist:**

Delete `docs` directly, not `api/docs`

---

rector.php
tests/system/Helpers/InflectorHelperTest.php
tests/system/Validation/CreditCardRulesTest.php

Remove duplicated key in defined arrays with `RemoveDuplicatedArrayKeyRector` rector rule.
**Checklist:**

[Rector] Apply Rector: RemoveDuplicatedArrayKeyRector

---

system/CLI/CLI.php
user_guide_src/source/cli/cli_library.rst

Allows the developer to prompt for a key-based selection of a value.
This requires to have https://github.com/codeigniter4/CodeIgniter4/pull/3911 merged to complete the PHPStan Task.
**Checklist:**

Feature: CLI: Select: added select prompt

---

.no-header.php-cs-fixer.dist.php

On update to v3.0.1 of php-cs-fixer the override to `false` of `no_blank_lines_after_phpdoc` is no longer needed as the bug is already fixed.
**Checklist:**

Remove override

---

system/Database/Forge.php
tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
tests/system/Database/Live/ForgeTest.php

Fix adding foreign keys with only string fields

---

.no-header.php-cs-fixer.dist.php
.php-cs-fixer.dist.php
system/BaseModel.php
system/Cache/Handlers/MemcachedHandler.php
system/Common.php
system/Database/BaseConnection.php
system/Debug/Exceptions.php
system/Entity/Entity.php
system/HTTP/Files/UploadedFile.php
system/Helpers/inflector_helper.php
system/Router/RouteCollection.php
system/Test/DOMParser.php
system/View/Parser.php
system/View/View.php
tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
tests/_support/Database/Seeds/CITestSeeder.php
tests/system/Cache/CacheFactoryTest.php
tests/system/Cache/Handlers/RedisHandlerTest.php
tests/system/Database/Live/GetTest.php
tests/system/HTTP/CLIRequestTest.php
tests/system/HTTP/RequestTest.php
tests/system/Helpers/HTMLHelperTest.php
tests/system/Router/RouteCollectionTest.php
tests/system/View/ParserTest.php
tests/system/View/ViewTest.php
utils/PhpCsFixer/Fixer/Comment/SpaceAfterCommentStartFixer.php

```diff
-//this is a comment
+// this is a comment
// this is another comment unchanged
```
**Checklist:**

Add SpaceAfterCommentStartFixer

---

system/Common.php
tests/system/Language/LanguageTest.php

After using the `lang()` function with the `$locale` parameter filled in, it overrides the default locale in the Language class, which shouldn't happen, because when using the `lang()` function with the `$locale` parameter it should be just for that call.
With this change, this override is corrected and the locale that was previously selected is restored.
**Checklist:**

Fix lang() function overriding default locale in Language class

---

system/Cookie/Cookie.php

> During inheritance of ArrayAccess: Uncaught Return type of CodeIgniter\Cookie\Cookie::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
**Checklist:**

Make Cookie compatible with ArrayAccess

---

system/Router/RouteCollection.php

Replace deprecated FILTER_SANITIZE_STRING

---

system/Database/BaseBuilder.php
system/Database/SQLSRV/Forge.php
system/Database/SQLite3/Forge.php
system/Model.php
tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
tests/_support/Database/Seeds/CITestSeeder.php
tests/system/Database/Builder/UpdateTest.php
tests/system/Database/Live/UpdateTest.php
user_guide_src/source/changelogs/index.rst
user_guide_src/source/database/query_builder.rst
user_guide_src/source/installation/upgrade_420.rst

This PR introduces some potential BC but I treat this as a bug that has to be fixed. At the end of the day calling
`$builder->set('bool', true);` and `$builder->set(['bool' => true]);` should have the same effect.
I have added additional tests for boolean values and upgrade instructions.
Fixes #4761
**Checklist:**

Fix bug with handling boolean values in set() method

---

system/Cookie/CookieStore.php

> Fatal error: During inheritance of IteratorAggregate: Uncaught Return type of CodeIgniter\Cookie\CookieStore::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
**Checklist:**

Make CookieStore compatible with IteratorAggregate::getIterator

---

app/Config/Cache.php
system/Cache/Handlers/BaseHandler.php
tests/system/Cache/Handlers/BaseHandlerTest.php
user_guide_src/source/changelogs/index.rst
user_guide_src/source/changelogs/v4.2.0.rst

Adds a new config value for reserved characters so developers may set their own restrictions.
**Checklist:**

Cache Config

---

rector.php
system/Session/Handlers/ArrayHandler.php
system/Session/Handlers/BaseHandler.php
system/Session/Handlers/DatabaseHandler.php
system/Session/Handlers/FileHandler.php
system/Session/Handlers/MemcachedHandler.php
system/Session/Handlers/RedisHandler.php

Reference for the updated signatures: https://www.php.net/manual/en/class.sessionhandlerinterface.php
I've refactored and cleaned the code a bit as I see fit.
My only concern is for the `gc` method. Our current implementation is using the pre-7.1 behavior where it returns `true` on success. Starting PHP 7.1, on success it should return the number of garbage collected sessions. My initial solution is to turn `true` to `1` for handlers where the number can't easily be determined while returning the true number on others (like the file handler).
**Checklist:**

Make the session handlers all compatible with SessionHandlerInterface

---

system/Test/Filters/CITestStreamFilter.php

> During inheritance of php_user_filter: Uncaught ErrorException: Return type of CodeIgniter\Test\Filters\CITestStreamFilter::filter($in, $out, &$consumed, $closing) should either be compatible with php_user_filter::filter($in, $out, &$consumed, bool $closing): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
**Checklist:**

Make CITestStreamFilter compatible with php_user_filter

---

system/Database/Forge.php
system/Database/SQLSRV/Forge.php
tests/system/Database/Live/ForgeTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/dbmgmt/forge.rst

Fixes #4310 
Original PR #4931 
Change the branch base to 4.2.
I edited the `addForeignKey` method and `_processForeignKeys` method of `CodeIgniter\Database\Forge` so that they can define composite foreign keys in an array.
**Checklist:**

Fix bug with DB-Forge composite foreign keys

---

user_guide_src/source/cli/cli_generators.rst

Add missing `make:validation` generator's command in userguide.
**Checklist:**

[Userguide] Add missing generator's command

---

.github/workflows/test-phpcpd.yml
system/Database/SQLSRV/Builder.php

This is a new tool I'm using at work from Sebastian Bergmann (PHPUnit author) that I thought would make a nice addition to the CS Fixer changes were are rolling out soon. The only remaining violation (ignoring **tests/** for now) is in `Database\\SQLSRV\\Builder::coompileSelect()` but refactoring that is beyond the current scope of `develop` so I have ignored the file for now.
**Checklist:**

PHP Copy-Paste Detector

---

system/Helpers/form_helper.php
tests/system/Helpers/FormHelperTest.php

Closes #4993.
This fixes the missing string casting for `$optgroupKey` in the `form_dropdown` helper.
This is an issue since strict `in_array` was introduced in #3565. Also adds a test for the casting (not pretty, but working).
I pointed this at develop as it is supposed to be a bugfix. Please correct if thats wrong 😄 
**Checklist:**

Fix key casting in form_dropdown helper.

---

rector.php
tests/system/Cache/Handlers/PredisHandlerTest.php
tests/system/Config/DotEnvTest.php

Change miss-typed case sensitivity name to correct one with `FixClassCaseSensitivityNameRector` rector rule.
**Checklist:**

[Rector] Apply Rector: FixClassCaseSensitivityNameRector

---

tests/system/API/ResponseTraitTest.php
tests/system/ControllerTest.php
tests/system/Database/Live/GetTest.php
tests/system/Database/Migrations/MigrationTest.php
tests/system/Entity/EntityTest.php
tests/system/Events/EventsTest.php
tests/system/Models/GeneralModelTest.php
tests/system/Models/InsertModelTest.php
tests/system/Models/SaveModelTest.php
tests/system/Models/UpdateModelTest.php
tests/system/View/ParserTest.php
utils/PhpCsFixer/CodeIgniter4.php

New fixers applied:
- `declare_parentheses`
- `empty_loop_body`
- removed deprecated `class_keyword_remove`
- `types_spaces`
- new option for `class_definition`
Only fixer with effect is the new option of `class_definition` adding a space before the parenthesis of anonymous class instantiation to line it with PSR12 requirement that anonymous classes should follow and behave like closures.
**Checklist:**

Bump to php-cs-fixer v3.1
