system/API/ResponseTrait.php
tests/system/API/ResponseTraitTest.php
user_guide_src/source/libraries/api_responses.rst

Created a `failServerError(string $description, string $code = null, string $message = ''): Response` method in the response trait to fail server errors.
Issue: #424

Create Response Trait Fail Server Error Method

---

system/Validation/Validation.php
tests/system/Validation/ValidationTest.php
user_guide_src/source/libraries/validation.rst

Created `Validation->getRuleGroup(string $group): array` and `Validation->setRuleGroup(string $group)` methods to get and set rule groups.
Issue: #419

Validation Get & Set Rule Groups

---

system/Language/Language.php
system/Language/en/Language.php
tests/system/Language/LanguageTest.php
tests/system/Validation/ValidationTest.php
user_guide_src/source/libraries/localization.rst

Allows a language file to contain an array of strings to make working with lists easier.
Issue: #414

Add Language File Array Support

---

system/Validation/Rules.php
tests/system/Validation/ValidationTest.php
user_guide_src/source/libraries/validation.rst

Added `alpha_space` validation rule.

Added Alpha Space Validation Rule

---

system/Database/ConnectionInterface.php

Changed return type of `QueryBuilder` to `BaseBuilder`.

Updated DB Connection Interface Table Method

---

system/API/ResponseTrait.php

Don’t require `$data` for `respondCreated()` and `respondDeleted()` methods.

Updated Respond Created & Deleted

---

system/Pager/Pager.php
tests/system/Pager/PagerTest.php

Fix  [issure#413](https://github.com/bcit-ci/CodeIgniter4/issues/413): Pagination::link() cant trans string param which retrieve from $_GET to page href

Fix issure #413: Pagination::link() cant trans string param which retrieve from $_GET

---

system/HTTP/IncomingRequest.php

class `CodeIgniter\HTTP\Request::__construct()` only has 1 required parameter.

remove 2nd parameter on parent::__construct() in IncomingRequest

---

ci.php

Fixes the following warning raised when running commands via CLI
```
PHP Notice:  Undefined variable: paths in /var/www/public/ci4/ci.php on line 33
PHP Stack trace:
PHP   1. {main}() /var/www/public/ci4/ci.php:0
PHP Notice:  Trying to get property of non-object in /var/www/public/ci4/ci.php on line 33
PHP Stack trace:
PHP   1. {main}() /var/www/public/ci4/ci.php:0
```

fix undefined variable paths on CLI

---

tests/system/Helpers/FilesystemHelperTest.php

Hey
As I've started browsing the code through Windows (I know, I'll switch to Linux once the semester is over), I noticed many unit tests would fail due to OS line ending and directory separators. 
While it is a very small fix on a single file, I thought I'd use this Pull Request to discuss the pertinence of fixing these tests.
Since I'd like to start contributing, I thought this would be a nice start to browse and understand the code. 
As reference, there are currently 14 failures under Windows with Xampp.
I'm not sure how many are passing/failing under Linux.
The fix would be to use PHP_EOL and DIRECTORY_SEPARATOR instead of '/' and a newline in the test case. It would most likely be semi-automated.

Made one unit tests OS-Agnostic: Convert all of them?

---

system/Database/MySQLi/Connection.php
user_guide_src/source/database/connecting.rst

MySQLi ping will ignore reconnect flag with the mysqlnd driver which is a standard these days. Even if the ping succeeds it is not guaranteed that the connection is working. In my experience you cannot rely on ping. The only sane way to reconnect to the database is to close it and then bring it up again.

MySQLi sane reconnect

---

.gitignore

PHP Intel is a folder created by a Sublime Text PHPIntel extension which enable PHP auto-complete for functions and objects

Updated .gitignore - add phpintel to Sublime Text

---

system/Filters/Filters.php

application/Config/Filters.php  file the globals array, when before's except is defined as a string, ci is running exceptionally.
show demo:
public $globals = [
'before' => [
'csrf' => ['except' => 'home/*']
],
'after'  => [
// 'toolbar'
]
];

Update Filters.php File.

---

system/Database/Forge.php
system/Helpers/text_helper.php
system/Helpers/url_helper.php
tests/system/Helpers/TextHelperTest.php
tests/system/Helpers/URLHelperTest.php
user_guide_src/source/database/forge.rst
user_guide_src/source/helpers/filesystem_helper.rst
user_guide_src/source/helpers/text_helper.rst
user_guide_src/source/helpers/url_helper.rst

From the code and/or docs:
- remove filesystem_helper's read_file()
- remove url_helper's url_title separator keyword
- remove Forge::addColumn()'s 'after' parameter

Remove deprecated pieces

---

.travis.yml
system/Cache/Handlers/RedisHandler.php
tests/system/Cache/Handlers/RedisHandlerTest.php

* system/Cache/Handlers/RedisHandler.php
I changed to fix to consider multiple Redis servers.
And we set the response format of ```getMetaData``` same as ``` MemcachedHandler.php```.
* tests/system/Cache/Handlers/RedisHandlerTest.php (new)
I added a test code, but it is not very good.
I think that memory capacity and access speed are not good because all are stored in Hash structure.

 Add test code for system/Cache/Handlers/RedisHandler.php

---

user_guide_src/source/libraries/incomingrequest.rst

Incomingrequest document update, the Request :: method() method does not exist and is replaced by the getMethod() method.

Incomingrequest document update

---

tests/_support/Database/MockConnection.php

Following travis error build on php nightly at #632 . When it get green, we can remove from allow_failures

Fixing build on php 7.2 env

---

system/Helpers/url_helper.php

If site_url() or base_url() functions are called before the current_url() function, it can change the expected value.

Fix for current_url() function

---

system/Database/BaseConnection.php
system/Images/Handlers/GDHandler.php

In CI3, escapeString passed false to remove_invisible_characters. CI4 doesn't. This removes characters if they fall within %0[0-8bcef] and %1[0-9a-f]. Beginning of LIKE binds start with %. Drivers should use their own _escapeString function (document?). SQLSRV doesn't necessarily need to be escaped.

Prevent remove_invisible_characters from removing url encoded characters from db drivers like statements (that don't need escaping)

---

system/Images/Handlers/BaseHandler.php
system/Images/Handlers/GDHandler.php
system/Images/Handlers/ImageMagickHandler.php
system/Images/ImageHandlerInterface.php
user_guide_src/source/libraries/images.rst

Added a function that flattens an image's transparencies (PNG > JPG) and defaults to a white background instead of black (similar to Photoshop) and fixes ImageMagick CLI in Windows (at least Win10/8/2012/2012r2) escaping.

Flattens an image's transparencies (GD/ImageMagick) & ImageMagick CLI bug fix

---

system/HTTP/URI.php

fixed issue with returning error which the segment is not the one been checked. instead returns just empty

fixed `getSegment`

---

system/Database/Postgre/Forge.php

Overridden method _processColumn($field)
$field['unsigned'] was left out for Postgre as it's not supported
#719

Fixes PostgreSql Forge trying to create UNSIGNED fields

---

system/Database/Forge.php

on line [492](https://github.com/bcit-ci/CodeIgniter4/blob/f14d09144633c61f4646320852e9c8253525cf82/system/Database/Forge.php#L492) it try to remove dbprefix from table name without checking if dbprefix is used or not. so if you didn't set  dbprefix ,  strpos()  used on that line throws error ( empty needle).

Fixed: dropTable() of forge   wouldn't work if your 'DBPrefix'  is empty  

---

system/Debug/Toolbar/Views/toolbar.js
system/View/View.php
tests/system/View/ParserPluginTest.php

This is a page when views hints is activated first time
When the Views label was clicked to hide the hints the order of nodes was modified.
When a view was loaded more then one time the hints surrounded only the last view with same filepath.
Now views hints use a number to identify the view and all are surrounded
And the order is no more modified when the hints are hidden

Views hints ordering

---

system/CLI/CLI.php

If tput cols returns 0, the default value should be returned. This caused, among other things, an error for the test "testWrap" (system / CLI / CLITest.php), since the console width can not be 0 in the normal case

CLI::getWidth return 0 for unittest testWrap

---

system/Database/Forge.php

What was happening:
```
$this->forge->addForeignKey('user_id', 'users', 'id', 'cascade', 'cascade');
```
Using slower case always was creating `RESTRICT` constraints.

FK: Recognize ON UPDATE and ON DELETE commands if is not in uppercase

---

system/CLI/CLI.php
user_guide_src/source/libraries/cli.rst

Usage example:
```php
<?php namespace App\Commands;
use CodeIgniter\CLI\CLI;
use CodeIgniter\CLI\BaseCommand;
class UsersCreate extends BaseCommand
{
protected $group       = 'Users';
protected $name        = 'users:create';
protected $description = 'Create user.';
public function run(array $params)
{
// Title
CLI::write('Users Create', 'yellow');
// Inputs
$name = CLI::prompt('Name', null, 'required|min_length[4]|max_length[32]');
$email = CLI::prompt('Email', null, 'required|valid_email');
$state = CLI::prompt('State', 'rs', 'in_list[rs,sc,pr]');
$city = CLI::prompt('City', ['Porto Alegre','Florianópolis','Curitiba'], 'required');
CLI::newLine();
// Title
CLI::write('User Data to be Registered', 'light_green');
// Outputs
CLI::write('Name: ' . $name);
CLI::write('Email: ' . $email); …
```

Add validation to prompt

---

system/API/ResponseTrait.php
tests/system/API/ResponseTraitTest.php

Avoid xml error (index 0 - Ex: <0>message</0>)
```
<?xml version="1.0"?>
<response><status>404</status><error>404</error><messages><0>Not Found</0></messages></response>
```

Add error key to API RT fail messages 

---

system/CLI/CLI.php

Avoid this error:
```
An uncaught Exception was encountered
Type:        InvalidArgumentException
Message:      is not a valid rule.
Filename:    ~/CodeIgniter4/system/Validation/Validation.php
Line Number: 238
```
It occurs if the user just press Enter on prompts like `Generate CRUD? [y, n]:`.

CLI - trim pipe to validation detect rules

---

system/Debug/Toolbar/toolbarloader.js.php

fix #834 
i guess the problem was that adding content to document.body.html will cause the browser or jquery to break some event handling
-> putting the content in a container and add it to the end of document.body

Fix toolbar loading cause event listener to not work properly

---

rewrite.php

Accessing http://localhost:8080/index.php the `$_SERVER['CI_ENVIRONMENT']` was not set.
Fix https://github.com/bcit-ci/CodeIgniter4/issues/834#issuecomment-345431577

Set CI_ENVIRONMENT before return false if REQUEST_URI is /index.php

---

system/Debug/Toolbar.php

Not sure if can fix the #834 
Before:
Now:

Let the browser know that the toolbarloader is a javascript file

---

system/Entity.php
tests/system/EntityTest.php

foo property in `Entity class` returned object type data when I write the following code
```php
$foo_entity = new class extends CodeIgniter\Entity {
protected $foo;
protected $_options = [
'casts' => ['foo' => 'array'],
'datas' => [],
'datamap' => []
];
public function setFoo($value) {
$this->foo = $value;
}
}
$foo_entity->setFoo(['foo' => 'bar']); // set no serialize array
return is_array($foo_entity->foo); // false
```
Fixed this because the type is different.
Also with this fix the following implementation also returns array.
```php
$foo_entity = new class extends CodeIgniter\Entity {
protected $foo;
protected $_options = [
'casts' => ['foo' => 'array'],
'datas' => [],
'datamap' => []
];
}
$foo_entity->foo = 'bar'; // inject string
return is_array($foo_entity->foo); // true
```

returned different type from entity class

---

system/CodeIgniter.php
system/Debug/Exceptions.php
tests/_support/Config/MockLogger.php
tests/system/API/ResponseTraitTest.php
tests/system/Autoloader/FileLocatorTest.php
tests/system/ControllerTest.php
tests/system/Database/BaseConnectionTest.php
tests/system/Database/Builder/AliasTest.php
tests/system/Database/Builder/DeleteTest.php
tests/system/Database/Builder/InsertTest.php
tests/system/Database/Builder/PrefixTest.php
tests/system/Database/Builder/WhereTest.php
tests/system/Database/Live/SelectTest.php
tests/system/EntityTest.php
tests/system/Filters/FiltersTest.php
tests/system/Helpers/FilesystemHelperTest.php
tests/system/Helpers/InflectorHelperTest.php
tests/system/Helpers/URLHelperTest.php
tests/system/Log/ChromeLoggerHandlerTest.php
tests/system/Log/FileHandlerTest.php
tests/system/Router/RouteCollectionTest.php
tests/system/Validation/ValidationTest.php

I've cleaned up some unused imports :put_litter_in_its_place: 
[`PHP-CS-Fixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer) helped me find them.

[CS] Remove unused imports

---

system/CodeIgniter.php

I was migrating for a project from CI-3 to CI-4, but I wanted to be able to switch back and forth. Ran into this method when trying to re-use the server vhost settings, which is what I'll end up doing when the project goes into production later. Thankfully that's a long way off, but yeah, I added code to the index.php that broke your app by using the CI_ENV variable as in older CodeIgniter versions. I figure other people might use other schemas, this allows you to override it without breaking the app.
It is my hope that this will free people up, especially those migrating from other platforms or earlier versions, to utilize their own internal way of determining the application environment, without breaking the way the app does it by default.

Test to make sure ENVIRONMENT isn't set by other means before attempting to set it.

---

system/API/ResponseTrait.php

Since [JSONFormatter](https://github.com/bcit-ci/CodeIgniter4/blob/6d659bb12a2af0182e6837c1f5bc781ac4481f78/system/Format/JSONFormatter.php#L54) uses the `json_encode()` it seems like it's not enough to do this twice.

Avoid json encode-decode if format is application/json

---

system/I18n/TimeDifference.php
system/Language/en/Time.php
tests/system/I18n/TimeDifferenceTest.php
tests/system/I18n/TimeTest.php

use localization in humanize
set some missing TimeZones in TimeTest.php
fix Time localization file ( correct invalidmonth string )

Forward localization TimeDifference::humanize & fix Time tests

---

system/Helpers/number_helper.php
tests/system/Helpers/NumberHelperTest.php

Use locale in number helper functions for text localization ( ignore sub part )
Set NumberHelperTest to use 'en'

Fix number_helper functions localization

---

system/Filters/Filters.php

URI multi-level directory will be prompted wrong.
err mes : preg_match(): Unknown modifier 'r'
show demo:
application/Config/Filters.php
`public filters = [
'foo' => ['before' => ['admin/foo/*']],
'bar' => ['before' => ['admin/bar/*']]
];`
If the delimiter appears often inside the pattern, it is a good idea to choose another delimiter in order to increase readability.
http://php.net/manual/en/regexp.reference.delimiters.php

Update to “Controller Filters ”

---

system/Router/RouteCollection.php
system/Router/Router.php
tests/system/Router/RouteCollectionTest.php
tests/system/Router/RouterTest.php

See: https://forum.codeigniter.com/thread-69894.html
URI: *admin/customers/groups*
```php
// Route
$routes->get('admin/customers/groups', 'Groups::index', [
'namespace'           => 'App\Controllers\Admin\Customers',
'as'                  => 'route_name_123',
'important-setting'   => 'x',
'important-setting-2' => 'y',
]);
```
```php
// Some place
var_dump(Services::router()->getMatchedRouteOptions());
```
```
APPPATH/Filters/ACL.php:21:
array (size=4)
'namespace' => string 'App\Controllers\Admin\Customers' (length=31)
'as' => string 'route_name_123' (length=14)
'important-setting' => string 'x' (length=1)
'important-setting-2' => string 'y' (length=1)
```

Enable to get all custom options set for the matched route

---

system/HTTP/ResponseInterface.php

According to [Hypertext Transfer Protocol (HTTP) Status Code Registry](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml),complement the missing HTTP status codes

complement the missing HTTP status codes

---

system/Router/RouteCollection.php
system/Router/RouteCollectionInterface.php

as there is `is_array()` check in body function which means allow both string and array.

remove string type hint for RouteCollection::addPlaceholder() for $placeholder parameter

---

system/Common.php
user_guide_src/source/general/common_functions.rst

Prevents XSS. 
Otherwise, if the developer must use `esc(old('field_name'))` I think we need to [update the docs about this function](https://bcit-ci.github.io/CodeIgniter4/general/common_functions.html#old).

Auto escape old input data

---

system/HTTP/IncomingRequest.php
user_guide_src/source/general/common_functions.rst

Fix issue 966 dot array in old() function
Signed-off-by: Gabriel P <16049869+gabpnr@users.noreply.github.com>

Fix issue 966 dot array in old() function

---

system/Config/Services.php
system/Debug/Exceptions.php
tests/system/Config/ServicesTest.php
tests/system/Debug/ExceptionsTest.php

Responding the [collectVars()](https://github.com/bcit-ci/CodeIgniter4/blob/8320ca777addbd900fd6cff032a90985d288ff19/system/Debug/Exceptions.php#L271) via the API ResponseTrait.
Maybe already [cleanPath()](https://github.com/bcit-ci/CodeIgniter4/blob/8320ca777addbd900fd6cff032a90985d288ff19/system/Debug/Exceptions.php#L330)'s in the collectVars, so we can get ready for all outputs, including the CLI. Also adjusting the `$_SERVER`, `$_SESSION`, `Request`, `Response`...

Respond Error Pages by Accept Header - Closes #863

---

system/Pager/Pager.php
tests/system/Pager/PagerTest.php
user_guide_src/source/libraries/pagination.rst

This prevent the insertion of unexpected queries into pagination links.
Usage:
**URI**: _/?search=foo&order=asc&hello=i+am+here&helloAgain=i+am+here+too_
```php
echo $pager->links();
// Page 2 link: /?search=foo&order=asc&hello=i%2Bam%2Bhere&helloAgain=i%2Bam%2Bhere%2Btoo&page=2
echo $pager->only(['search', 'order'])->links();
// Page 2 link: /?search=foo&order=asc&page=2
```
The `page` query is enabled by default.

Enables Pager to use only pre-set queries

---

system/Validation/Validation.php

```php
{
$rules = [
'new_password'         => [
'label' => 'New Password',
'rules' => [
'required',
'min_length[5]',
],
],
'confirm_new_password' => [
'label' => 'Confirm New Password',
'rules' => [					
'differs[new_password]',
//'required_without[new_password]',
//'required_with[new_password]',
//'matches[new_password]',
],
],
'confirm_new_password2' => 'required|matches[new_password]',
];
if ($this->validate($rules) === false)
{
var_dump($this->validator->getErrors());
exit;
}
echo 'Ok';
}
```

Validation - Get the label from corresponding fields - Fixes #946

---

system/Config/BaseConfig.php

While using backslash within single or double quotes in .env, its need to trim quotes. Details in #994

Clean up environment variable value

---

system/Language/en/Email.php

```
Searching 243 files for "SMYPError"
/CodeIgniter4/system/Language/en/Email.php:
25  	'noSocket'             => 'Unable to open a socket to Sendmail. Please check settings.',
26  	'noHostname'           => 'You did not specify a SMTP hostname.',
27: 	'SMYPError'            => 'The following SMTP error was encountered: {0}',
28  	'noSMTPAuth'           => 'Error: You must assign a SMTP username and password.',
29  	'failedSMTPLogin'      => 'Failed to send AUTH LOGIN command. Error: {0}',
1 match in 1 file
```
```
Searching 243 files for "SMTPError"
/CodeIgniter4/system/Email/Email.php:
2093  		if (strpos($reply, '250') !== 0)
2094  		{
2095: 			$this->setErrorMessage(lang('email.SMTPError', [$reply]));
2096  
2097  			return false;
....
2139  		if (! is_resource($this->SMTPConnect)) …
```

Fix Email lang typo

---

system/HTTP/RedirectResponse.php
system/Session/Session.php

Allow IDE's to know that is possible pass an array
```
return \redirect()->with('msg', ['type' => 'warning', 'content' => 'foo']);
```

Update PHPDoc params of redirect with setFlashdata

---

.travis.yml
phpunit.xml.dist

looking at previous travis build, the coveralls command got the following error: 
```
$ travis_retry php tests/bin/coveralls.phar
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
coverage_clover XML file is not readable                                       
coveralls:v1:jobs [-c|--config [CONFIG]] [--dry-run] [--exclude-no-stmt] [-e|--env [ENV]] [-x|--coverage_clover COVERAGE_CLOVER] [-r|--root_dir [ROOT_DIR]]
The command "php tests/bin/coveralls.phar" failed. Retrying, 2 of 3.
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
coverage_clover XML file is not readable                                       
coveralls:v1:jobs [-c|--config [CONFIG]] [--dry-run] [--exclude-no-stmt] [-e|--env [ENV]] [-x|--coverage_clover …
```

activate coverage-clover logging at phpunit config to get clover.xml which read by coveralls.phar

---

system/CLI/Exceptions/CLIException.php
system/Cache/Exceptions/CacheException.php
system/Database/Exceptions/DataException.php
system/Exceptions/ConfigException.php
system/Exceptions/FrameworkException.php
system/Exceptions/PageNotFoundException.php
system/Files/Exceptions/FileException.php
system/Files/Exceptions/FileNotFoundException.php
system/Filters/Exceptions/FilterException.php
system/Format/Exceptions/FormatException.php
system/HTTP/Exceptions/HTTPException.php
system/I18n/Exceptions/I18nException.php
system/Images/Exceptions/ImageException.php
system/Log/Exceptions/LogException.php
system/Pager/Exceptions/PagerException.php
system/Router/Exceptions/RouterException.php
system/Security/Exceptions/SecurityException.php
system/Session/Exceptions/SessionException.php
system/Validation/Exceptions/ValidationException.php
system/View/Exceptions/ViewException.php

Change "new self" to "new static", resulting in tended behavior of catching "module" exceptions rather than needing multiple catch clauses for different kinds of exceptions.

Refactor exceptions for late static binding

---

system/Autoloader/FileLocator.php
system/Common.php
system/Config/BaseService.php
system/Config/Config.php
tests/system/Config/ConfigTest.php
user_guide_src/source/general/configuration.rst

config helper implementation for #1071 

Config helper

---

system/Config/Config.php
tests/system/Config/ConfigTest.php

ConfigHelper : case-sensitive

---

system/Debug/Toolbar/Views/toolbar.tpl.php

setcookie() is arrays will cause ‘Array to string conversion’ to be wrong.
toolbar cannot be initialized correctly.
Example, Home Controller add code:
`setcookie("cookie[three]", "cookiethree");
setcookie("cookie[two]", "cookietwo");
setcookie("cookie[one]", "cookieone");`

toolbar cannot be initialized correctly.

---

system/Database/Forge.php
system/Database/MySQLi/Forge.php
system/Database/Postgre/Forge.php
tests/system/Database/Live/ForgeTest.php

Table comment could not be set like it:
```php
$this->forge->createTable('forge_test_table', false, ['COMMENT' => "Forge's Test"]);
```

Escape Forge createTable() attributes

---

system/Commands/Server/rewrite.php

I wanted to move the `public` directory, but I could not move it.
Since `rewrite.php` before modification depends on the installed directory, it is necessary to create `Serve` class in application and solve it.
This is very troublesome and if spark defines the `FCPATH` constant we thought that you do not have to define $fcpath in rewrite.php.
I think this is the experimentally implemented content at the next PR, but the current situation has arisen.
#996

Fixed a bug where you can not change the path freely

---

system/HTTP/Request.php

There is `$this->proxyIPs` check not an array, which next collected into `$proxy_ips` as an `explode()` of comma separated ip address into array.

php 7.2 fix Request::getIPAddress() error count(): Parameter must be an array or an object that implements Countable

---

system/I18n/Time.php
system/Language/en/Time.php

while it is practically valid to have day = 0 and month = 0, I think it is better to use start month and start day as 1 instead of 0 to avoid confusion to use last previous month last day.
ref: https://3v4l.org/MGrJY

update invalidDay and invalidMonth start check, use 1 instead of 0

---

application/Config/Boot/testing.php
system/Helpers/form_helper.php
tests/system/CommonFunctionsTest.php
tests/system/Config/ServicesTest.php
tests/system/HTTP/RedirectResponseTest.php
tests/system/Helpers/FormHelperTest.php
tests/system/Session/SessionTest.php

running phpunit tests in separate processes doesn't throw the error from #1106 anymore

Run session tests in separate processes - fix for #1106

---

application/Filters/DebugToolbar.php
system/Debug/Toolbar.php
system/Debug/Toolbar/Views/_config.tpl.php
system/Debug/Toolbar/Views/_database.tpl.php
system/Debug/Toolbar/Views/_events.tpl.php
system/Debug/Toolbar/Views/_files.tpl.php
system/Debug/Toolbar/Views/_history.tpl.php
system/Debug/Toolbar/Views/toolbar.css
system/Debug/Toolbar/Views/toolbar.tpl.php
system/Debug/Toolbar/toolbarloader.js.php

use csp valid style and script tags for these parts of the debug bar
to fix the rest of csp problems we need to replace all inline style and scripts, so I add them to the toolbar.css. hope this is ok because it looks not optimal
another solution would be allowing inline styles but that would lower the security and also change the whole page behavior ( related to CSP )

Fix debugbar loading while csp is enabled

---

system/Debug/Toolbar.php

Fixes #1135 : Toolbar oldest file delete and show maximum in the list as App::toolbarMaxHistory

---

system/HTTP/Header.php
tests/system/HTTP/HeaderTest.php

if the name is not mandatory, when we create a `HTTP\Header` and call it as string from `__toString()`, we will get the ": " value, which seems incorrect as message header.

make name parameter in HTTP\Header mandatory

---

system/Test/CIDatabaseTestCase.php

previously, it uses assignment which the DBPrefix concated with string "migrations", which if using truthy check, it will always evaluated as `true`, so continue always called at this case. changed `=` to `==`

comparison fix at CIDatabaseTestCase

---

system/Config/DotEnv.php

so no need to check not string of $file which set value to its default value `.env'

use string type hint in $file parameter in DotEnv::__construct()

---

system/Validation/Validation.php

as the `session()` function is calling `\Config\Services::session()` which call `start()` when `session_status() == PHP_SESSION_NONE`

remove start() call on session() function call at Validation

---

system/Model.php

adding additional if for __get method to make easier achieve sth like this:
$row->{$model->primaryKey}

allows to get table and primary key name out of the model

---

system/Validation/FormatRules.php
tests/system/Validation/FormatRulesTest.php
user_guide_src/source/libraries/validation.rst

it will return false if json is null, similar  to existing funcs , i.e. valid_url

Adds valid_json which is using json_last_error() === JSON_ERROR_NONE

---

application/Config/Logger.php
system/Log/Logger.php
tests/system/Log/LoggerTest.php

Log level threshold is adjusted to match RFC 5424.
Set threshold to 'debug' level practically show 'all' debug messages. This usually the developer wants on debugging sessions

Adjust log level to match RFC 5424

---

system/CodeIgniter.php

If buffering is null.
log filg:
CRITICAL - 2018-08-27 15:23:22 --> ob_end_clean(): failed to delete buffer. No buffer to delete
............

log file:failed to delete buffer. No buffer to delete.

---

system/Validation/FileRules.php
tests/system/Validation/FileRulesTest.php

previously, it uses `$file->getSize('kb')` which got numbered format of size, which make it invalid for big file. Updated to `$file->getSize()/1024`, ref https://3v4l.org/7MuUB . Unit test included.

Fixes FileRules::max_size() to use file->getSize() instead of number_formatted size

---

system/Validation/Validation.php

on `Validation::getErrors()`, it has handle that errors came from session with key `_ci_validation_errors`
For example, after call:
```php
return redirect('page')->withInput();
```
On error field, we are calling  at the '/page':
```php
var_dump( $validator->hasError('field'));
```
it previously won't work as the error is came from the session.

use Validation->getErrors() call instead of Valdation::errors to handle errors that came from session

---

system/Config/Services.php
system/Email/Email.php

catch exceptions that are thrown in the send mail function
-> caused by wrong/invalid mail config

Catch Email Exceptions

---

system/Validation/Validation.php
tests/system/Validation/ValidationTest.php

When writing the following rules, this program works as follows.
```php
$ this-> validate ([
    'date' => 'required|regex_match[/^[0-9]{4}[\-\.\/][0-9]{2}[\-\.\/][0-9]{2}/]|max_length[10]'
]);
```
validation rule is `regex_match[/^[0-9]{4}[\-\.\/]`.
but, expected validation rule is `regex_match[/^[0-9]{4}[\-\.\/][0-9]{2}[\-\.\/][0-9]{2}/]`.
Signed-off-by: ytetsuro <phper.0o0@gmail.com>
detail: https://github.com/bcit-ci/CodeIgniter4/pull/1202#issuecomment-418964824

Validation Class - corresponding about the escaped separator.

---

tests/system/Helpers/CookieHelperTest.php
tests/system/Helpers/DateHelperTest.php
tests/system/Helpers/HTMLHelperTest.php
tests/system/Helpers/InflectorHelperTest.php
tests/system/Helpers/NumberHelperTest.php

Fix the namespace of the helper unit tests.
Yes, this meant adding some "use" statements, but the namespaces are right :)

Correct helper tests namespace

---

system/Validation/Validation.php
tests/system/Validation/ValidationTest.php

Approach for solution to the problem reported in the comment
https://github.com/bcit-ci/CodeIgniter4/pull/1203#issuecomment-420878322
In order to solve this problem, we changed the division logic of verification so that it splits it with a pipe not in square brackets.
**Checklist:**

Improved division logic of validation rules.

---

admin/docbot
user_guide_src/source/general/filters.rst

The messed up user guide (gh-pages) was caused by a missing or misplaced .nojekyll file.
Go figure.
This should fix it :-/

Fix gh-pages deployment

---

user_guide_src/source/libraries/uri.rst

doc fix: remove unneeded call helper(url) as already bootstrapped by default

---

user_guide_src/source/tutorial/create_news_items.rst

**Checklist:**
as there is no `validation_errors()` function, and there is a `\Config\Services::validation()->listErrors()` for that.

doc fix: replace validation_errors() function with \Config\Services::validation()->listErrors()

---

tests/system/CLI/ConsoleTest.php
tests/system/CodeIgniterTest.php
tests/system/Test/FeatureTestCaseTest.php

Simple fix for open buffers ( opend by tryToRouteIt )

workaround for buffer problem

---

application/Views/errors/cli/error_404.php

Before:
-------
```bash
➜  CodeIgniter4 git:(develop) php public/index.php NotFound
PHP Fatal error:  Uncaught ErrorException: Undefined variable: heading in /Users/samsonasik/www/CodeIgniter4/application/Views/errors/cli/error_404.php:6
```
After:
------
```
➜  CodeIgniter4 git:(fix-undefined-var-heading-in-cli-404) php public/index.php NotFound
ERROR: 404
Controller or its method is not found: App\Controllers\NotFound::index
```

Fix undefined variable "heading" in cli 404

---

system/Config/AutoloadConfig.php

There is currenlty no `CodeIgniter\Loader` class, so it can be removed from `AutoloadConfig::classmap`

remove inexistent "CodeIgniter\Loader" from AutoloadConfig::classmap

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/CountTest.php
user_guide_src/source/database/query_builder.rst

Identical as is in countAllResult().

Optional parameter for resetSelect() call in Builder's countAll();

---

system/Common.php
user_guide_src/source/general/helpers.rst

All helpers of the same name across application/system/all namespaces are now loaded, allowing "extending" of a helper file.

Allows extending of helpers. Fixes #1264

---

system/CodeIgniter.php
system/Exceptions/DownloadException.php
system/Filters/Filters.php
system/HTTP/DownloadResponse.php
system/HTTP/Response.php
system/HTTP/ResponseInterface.php
system/Language/en/HTTP.php
tests/system/HTTP/DownloadResponseTest.php
tests/system/HTTP/ResponseTest.php

I think Response::download method is not testable.
because use exit and echo.
my solution is following.
1. create Download Response class.
1. to exit when Download Response class returns from Controller method.
**Checklist:**

【Unsolicited PR】I changed the download method to testable.

---

system/HTTP/IncomingRequest.php

Even after resolving the earlier problem (#1114), the if/else block wasn't al being tested.
This corrects that, without breaking the unit tests.
@puschie286 Does this still work for your case?
If not, can I have a testcase which breaks it? Thanks

Refactor script name stripping in parseRequestURI()

---

tests/system/I18n/TimeTest.php

Updated the first four test cases to use the same $time object, since they are comparing formatted results, not specific time instances.
This should eliminate most of the travis-ci failures because of a 1 second tie difference.
TimeTest::testTestNow() may still have an occasional issue, because its two time objects could still be off.

Refactor TimeTest

---

user_guide_src/source/incoming/controllers.rst

Fix doc error
show_404() doesn't exist any more

Fix doc error : show_404() doesn't exist any more

---

system/Helpers/form_helper.php

When string contains quotes i.e. json or serialized object was passed as  $hidden => form_open or as a $value => form_hidden it wasn't escaped properly.
i.e.:   form_hidden('aaa', '{"foo":"bar"}')  wasn't work

FIX   form_hidden and form_open - value escaping as is in form_input.

---

user_guide_src/source/changelog.rst

@lonnieezell What do you think? It is complete, in terms of which components were changed, but it doesn't say much about what changes were made. I think it we want that, then we need to update the changelog with each merge.
It is based on the PRs merged since alpha.1 ... anything merged directly, and not through a PR, is not included.
PR titles are not useful for automating this, and commit messages are even less useful.

Proposed changelog for alpha.2

---

application/Views/welcome_message.php
system/Debug/Toolbar/Views/toolbar.css

- Improved readability of fonts in general by ensuring they were slightly larger and a bit heavier for better contrast.
- Fixed spacing of version number on right of toolbar
- reduced padding around table rows to fit a bit more per "page"
- removed the `(in progress)` text from the Welcome page.

Toolbar Styles

---

user_guide_src/source/libraries/sessions.rst

Malformed table & mismatched underlines fixed.

Fix sphinx formatting in sessions

---

system/Router/RouteCollection.php
tests/system/Router/RouterTest.php

Only merges generic routing rules if they would not replace an HTTP verb one

Handle duplicate HTTP verb and generic rules properly

---

system/Test/CIUnitTestCase.php
tests/system/Debug/TimerTest.php
user_guide_src/source/changelog.rst
user_guide_src/source/testing/overview.rst

Tired of tweaking the long execution time tests, I have added a new assertCloseEnough assertion to CIUnitTestCase ;P

Add timing assertion to CIUnitTestCase

---

php_errors.log

The `php_errors.log` file is ignored in `.gitignore` but seems was not deleted which may caused by overlap register it to `.gitignore`. I applied `git rm --cached php_errors.log` to it to remove it completely from the repo.

rm --cached php_errors.log file

---

system/Commands/Sessions/CreateMigration.php
system/View/View.php

Update template file is not .php compatibility
If the template I am using is not a .php file and I use the default path configuration, the system will not work. 
In the `locateFile()` method, the template file path will be forced to add `.php`
So it will cause the system to not find the template file.
An exception that cannot be found in a file will be reported.
**Checklist:**

Update template file is not .php compatibility

---

system/Database/MySQLi/Forge.php

Not to quote unecessary table options when create table.
https://dev.mysql.com/doc/refman/8.0/en/create-table.html
Not all table options value need to be quoted, in fact, some table options should never be quoted otherwise will become an invalid SQL
**Checklist:**
- [ N ] Securely signed commits
- [ N/A ] Unit testing, with >80% coverage
- [ N/A ] User guide updated
- [ Y ] Conforms to style guide

Not to quote unecessary table options

---

system/Database/Forge.php
system/Database/MySQLi/Forge.php

When using Forge to create database table and create a ENUM type field, it should only use one single quote to quote the constraint.
In previous code, the `$this->db->escape($attributes['CONSTRAINT'])` had add a single quote, and the following implode add another single quote, cause an invalid SQL code.
**Checklist:**
- [ No ] Securely signed commits
- [ Maybe ] Unit testing, with >80% coverage
- [ N/A ] User guide updated
- [ Y ] Conforms to style guide

Avoid add two single quote to constratin.

---

system/Language/en/Filters.php

Update Filters language file
The filter alias was not shown. It was showing `{0}` instead.
**Checklist:**

Update Filters language file

---

system/HTTP/DownloadResponse.php
tests/system/HTTP/DownloadResponseTest.php
tests/system/HTTP/ResponseTest.php

When I created an application to download multibyte file name, the file name got corrupted.
Changed give download proccess a header conforming to "RFC6266"
The phenomenon that the file name is garbled can be confirmed with Internet Explorer 11 older.
**Checklist:**

【Unsolicited PR】Give download a header conforming to RFC 6266

---

system/Debug/Toolbar.php

Toolbar collector does not exists. log file is show they had a wrong classname.
**Checklist:**

Toolbar needs logging. Fixes #1258

---

system/Model.php
system/Validation/Rules.php
system/Validation/Validation.php

is_unique tried to connect to default database instead of defined in DBGroup.

---

application/Config/Mimes.php
system/HTTP/Files/UploadedFile.php

#1367 
guessExtension() more predictable

UploadedFile->guessExtenstion() & Config/Mimes::guessExtensionFromType() improvements.

---

system/HTTP/RedirectResponse.php
tests/system/HTTP/RedirectResponseTest.php

The following code:
```php
return redirect()->route('access');
```
was redirecting to `http://localhost:8080//access` (note the two slashes).
**Checklist:**

Redirect to named route

---

tests/system/Test/TestCaseTest.php

Fixed not to output `Hello` at test execution.
**Checklist:**

Fixed not to output "Hello" at test execution.

---

system/Entity.php
system/Model.php
tests/system/View/ParserTest.php

Turning cast for db save/update and validation inside of Model's::classToArray , will fix #1372 and probably #1359;

Turning off casting for db insert/save 

---

system/Cache/Handlers/MemcachedHandler.php
tests/system/Cache/Handlers/MemcachedHandlerTest.php

fix #1204
port from [RedisHandler](https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Cache/Handlers/RedisHandler.php)
**Checklist:**

fix TypeError in MemcachedHandler::__construct()

---

application/Config/Autoload.php

By this, the "Tests\Support" namespace won't be registered in `development` and `production` env which is not used.
**Checklist:**

only register PSR4 "Tests\Support" namespace in "testing" environment

---

system/Files/File.php
system/HTTP/Files/UploadedFile.php

Null is allowed as the return value of \Config\Mimes::guessExtensionFromType that's why should be allowed in guessExtension either.
/ fix: no extension for given mimetype,  PR#1368 (@daljit3 - thx, for pointing this out)/

optional type hinting in guessExtension

---

user_guide_src/source/cli/cli.rst
user_guide_src/source/extending/core_classes.rst
user_guide_src/source/general/configuration.rst
user_guide_src/source/incoming/controllers.rst
user_guide_src/source/incoming/incomingrequest.rst
user_guide_src/source/models/model.rst
user_guide_src/source/testing/controllers.rst
user_guide_src/source/tutorial/create_news_items.rst
user_guide_src/source/tutorial/news_section.rst
user_guide_src/source/tutorial/static_pages.rst

A sweep through the user guide, to correct class namespacing declarations.
Fixes #1401

Correct class namespacing in the user guide

---

system/Database/BaseConnection.php
user_guide_src/source/database/queries.rst

For example, we have the following SQL statement from `db->prepare()->execute()` usage:
```php
$db = \Config\Database::connect();
$pQuery = $db->prepare(function ($db) {
$sql   = 'CALL insert_test(?)';
$query = new \CodeIgniter\Database\Query($db);
return $query->setQuery($sql);
});
$pQuery->execute('test');
```
On `connID` still false, we will get the following error:
```bash
pg_prepare() expects parameter 1 to be resource, boolean given
```
I updated to call `initialize()` on `prepare()` function when connID is still not set yet:
```php
public function prepare(\Closure $func, array $options = [])
{
if (empty($this->connID))
{
$this->initialize();
}
// ...
}
```
I also updated the documentation which the `new Query()` needs parenthesis before call execute.
Explain what …

Database: add missing call initialize() check on BaseConnection->prepare() when connID is not set yet

---

system/Router/RouteCollection.php

In previous latest commit https://github.com/bcit-ci/CodeIgniter4/commit/2d0b32556198aefec7057d99fa3af8daed9a504b , the `HTTPVerb` property of `RouteCollection` changed by call `Services::request()->getMethod()` by @lonnieezell that make command:
```bash
php spark serve
```
Got output:
```bash
ERROR: 404
Controller or its method is not found: App\Controllers\Ciserve::index
```
**Checklist:**
ping @lonnieezell

Fix spark serve not working from commit  2d0b325

---

application/Views/errors/cli/error_404.php
application/Views/errors/cli/error_exception.php
application/Views/errors/html/error_404.php

It only in files in `Views/errors` directory, while it not applied in `welcome_message.php` and `form.php`. I think it was a legacy code check while we still didn't point the root directory to `public` directory yet. I removed it.
**Checklist:**

remove unneded "defined('BASEPATH') OR exit('No direct script access allowed') in Views/Errors files

---

application/Config/Autoload.php
system/Config/AutoloadConfig.php

Actually, the `Config\Autoload` class in `application\Config` directory is extends the `CodeIgniter\Config\AutoloadConfig` which in the `__construct()` already set `$this->psr4['Tests\Support']`  and it called the:
```php
parent::__construct();
```
early, so it is no longer needed to be redefined as it will be merged with:
```php
$this->psr4     = array_merge($this->psr4, $psr4);
```
which merge parent `psr4` property to its `$psr4` variable. So, I removed its definition in `Config\Autoload::__construct()`.
**Checklist:**

remove $psr4['Tests\Support'] definition in application\Config\Autoload::__construct()

---

system/View/Parser.php

The parser should only escape single values because parsePair is called recursive on each array.
Fix #1104 
**Checklist:**

fix Parser::parsePairs always escapes

---

application/Views/errors/html/error_exception.php
system/Email/Email.php

as in php manual documented at http://php.net/manual/en/function.uniqid.php#refsect1-function.uniqid-parameters
```
If set to TRUE, uniqid() will add additional entropy (using the combined linear congruential generator) at the end of the return value, which increases the likelihood that the result will be unique. 
```
**Checklist:**

set more_entropy = true in all uniqid() usage

---

system/View/View.php

On line 229. 
Before (without break on found) : 
```php
foreach (['APPPATH', 'BASEPATH', 'ROOTPATH'] as $path)
{
if (strpos($this->renderVars['file'], constant($path)) === 0)
{
$this->renderVars['file'] = str_replace(constant($path), $path . '/', $this->renderVars['file']);
}
}
```
After (with break on found):
```php
foreach (['APPPATH', 'BASEPATH', 'ROOTPATH'] as $path)
{
if (strpos($this->renderVars['file'], constant($path)) === 0)
{
$this->renderVars['file'] = str_replace(constant($path), $path . '/', $this->renderVars['file']);
break;
}
}
```
**Checklist:**

add missing break; in loop in View::render() when match the file search

---

tests/_support/_bootstrap.php
tests/system/Test/BootstrapFCPATHTest.php

Changed the method to get the FCPATH from getcwd() to realpath() to set paths relative to the bootstrap file. This allows tests to be run independently from their directories or using IDEs like PHPStorm.
This is a correction/update to pull request #1310.  It is essentially the same except there is no change to any autoloading behavior.
if you run the test without the change to _bootstrap.php, it will fail and all other tests will fail if you run them from their directory like this:
Before the fix this will fail (run from bash in linux, you may need to adjust your paths):
`/usr/bin/php /home/vagrant/Code/codeigniter4/vendor/phpunit/phpunit/phpunit --bootstrap /home/vagrant/Code/codeigniter4/tests/_support/_bootstrap.php --no-configuration FeatureTestCaseTest …

Correcting FCPATH setting in tests/_support/_bootstrap.php

---

system/Test/FeatureTestCase.php

The function is `options()`, the parameter should be `options` instead of `delete`.
**Checklist:**

Fixes "options" request call parameter in FeatureTestCase class

---

.travis.yml

since php: nightly already use php 7.4dev
**Checklist:**

add php 7.3 to travis config

---

system/Controller.php
user_guide_src/source/incoming/controllers.rst

- Fix Controller use validate bug Fixes #1419
- Fix user guide error for controller.
**Checklist:**

 Fix Controller use validate bug Fixes #1419

---

tests/system/HTTP/Files/FileMovingTest.php

HTTP\Files]FilesMovingTest was leaving a "vfs:" folder inside WRITEPATH/uploads.
That is now explicitly deleted as part of tearDown().

Fix FileMovingTest leaving cruft

---

tests/system/Log/FileHandlerTest.php

"This is a test log" entries were piling up inside log files inside writable/logs, which would then have to be manually deleted. The log files are gt ignored, but cluttering up the writeable/logs folder.

Ensure FileHandlerTest uses MockFileHandler

---

system/Database/BaseResult.php

Applied to `resultObject` and `resultArray`:
Before:
```php
if (($c = count($this->resultObject)) > 0)
{
for ($i = 0; $i < $c; $i ++ )
{
}
}
```
After:
```php
if ($this->resultObject)
{
foreach ($this->resultObject as $row)
{
}
}
```
**Checklist:**

performance improvement in Database\BaseResult to use truthy check instead of count($var) when possible

---

system/Commands/Database/CreateMigration.php
system/Commands/Database/MigrateCurrent.php
system/Commands/Database/MigrateLatest.php
system/Commands/Database/MigrateRollback.php
system/Commands/Database/MigrateStatus.php
system/Commands/Database/MigrateVersion.php
user_guide_src/source/dbmgmt/migration.rst

- can't call run() method with params from commands migrations. Fixes #1308
- update user guide for migration
**Checklist:**

can't call run() method with params from commands migrations.

---

system/CLI/CLI.php

`strlen()` does not consider certain characters. This affected the calculation of spaces between the columns of the `CLI::table()`.
**Checklist:**

Use mb_strlen to get length of columns

---

application/Views/form.php
user_guide_src/source/tutorial/create_news_items.rst

in favor of @lonnieezell comment at https://github.com/bcit-ci/CodeIgniter4/pull/1409#issuecomment-437239169
**Checklist:**

remove form view in application/View/ and form helper usage in create new items tutorial

---

tests/system/Test/BootstrapFCPATHTest.php

Fixes #1435 which the `FCPATH` constant is echoed in `system()` call.
**Checklist:**

Fixes #1435 : unit test output not captured

---

system/Model.php

Allows to get insertID after insert($insert_data, false) which returns CodeIgniter\Database\*\Result object instead of insertID.

Access to model's last inserted ID

---

system/HTTP/IncomingRequest.php

There is already `is_cli()` function at `Common.php` for it, so I think it is better to use it as it already defined.
**Checklist:**

using existing is_cli() function in HTTP\IncomingRequest::isCLI()

---

system/Validation/CreditCardRules.php

Add break in loop of `foreach` cards property to get card info, when `$card['name'] == $type`, it assign `$info` variable. 
**Checklist:**

add missing break; on loop cards to get card info at CreditCardRules::valid_cc_number()

---

system/HTTP/RedirectResponse.php

The `Services::session()` already take care of session initialization.
**Checklist:**

remove unneeded $session->start(); check on RedirectResponse::ensureSession()

---

application/Config/Mimes.php

in_array() expects parameter 2 to be array, string given
APPPATH/Config/Mimes.php at line 316

BugFix  if there extension has only one mime type (string)

---

system/Email/Email.php

On encoding set on match strpos with loop, and set `$this->encoding`, it needs `break;`.
**Checklist:**

add missing break; in loop at Email::getEncoding()

---

README.md
admin/docbot
admin/post_release
admin/release
admin/release-notes.md
composer.json
contributing.md
contributing/README.rst
contributing/guidelines.rst
contributing/workflow.rst
user_guide_src/source/changelog.rst
user_guide_src/source/extending/contributing.rst
user_guide_src/source/installation/downloads.rst
user_guide_src/source/intro/psr.rst
user_guide_src/source/tutorial/conclusion.rst

Update the github organization, in the docs only, from bcit-ci to codeigniter4.
Note: these are done as separate PRs to make sure they go all the way through,

Change github organization name in docs (1of4)

---

system/Honeypot/Honeypot.php

`! empty()` already return true on not empty, false on empty.
**Checklist:**

remove unneeded ternary check at HoneyPot::hasContent()

---

system/Database/BaseBuilder.php

Correct the PHPdoc comments for several BaseBuilder methods.
Fixes #1365

Fix phpdocs for BaseBuilder

---

application/Config/Mimes.php
system/CodeIgniter.php
system/Database/Config.php
system/Debug/Toolbar.php
system/Email/Email.php
system/Events/Events.php
system/Test/Filters/CITestStreamFilter.php

For allow late static binding
**Checklist:**

use static:: instead of self:: for protected and public properties

---

system/Test/CIUnitTestCase.php
tests/system/CLI/CLITest.php
tests/system/I18n/TimeTest.php
user_guide_src/source/testing/overview.rst

Similar to earlier assertCloseEnough, provide an assertion that two formatted time strings are close enough to eah other to be deemed the same. Allows some leeway for times that are off by a second.

Provide time testing within tolerance

---

system/Test/FeatureTestCase.php
tests/system/Test/FeatureTestCaseTest.php

fix the auto cleanup after FeatureTestCase::call -> is necessary for specific test but some require the op cache to be left open.
fix #1446
**Checklist:**

Fix FeatureTestCaseTest output buffer 

---

application/Config/Services.php
application/Views/errors/html/error_exception.php
system/ComposerScripts.php
system/Config/BaseService.php
system/Config/Services.php
system/Database/Config.php
system/Debug/Toolbar.php
system/Debug/Toolbar/Views/toolbar.tpl.php
system/Email/Email.php
system/Events/Events.php
system/HTTP/IncomingRequest.php
system/HTTP/URI.php
system/View/Filters.php
user_guide_src/source/concepts/services.rst
user_guide_src/source/extending/core_classes.rst

To allow override new defined static function, ref: https://3v4l.org/XQPT9
**Checklist:**

use static:: instead of self:: for call protected/public functions as well

---

system/HTTP/Response.php
tests/system/HTTP/ResponseSendTest.php

Succeeded in testing Response:send*
100% coverage for Response now.

Add Response send testing

---

user_guide_src/source/dbmgmt/seeds.rst

It was missing `:` after each named parameter.
**Checklist:**

doc fix: query binding fix in Seeds documentation

---

system/Database/Forge.php
system/Database/SQLite3/Forge.php
tests/system/Database/Live/ForgeTest.php
user_guide_src/source/dbmgmt/forge.rst

See #976
Testing only ENUM in MySQLi - but all constraints set as array will be escaped and imploded, works with MySQL SET Data Type too.
**Checklist:**

Allow create table with array field constraints

---

tests/system/Cache/Handlers/RedisHandlerTest.php

RedisHandler test clean up: remove unneeded 2nd parameter in __construct

---

system/Language/Language.php
tests/system/Language/LanguageTest.php

The Language class currently crash if one key name is the filename of another language file
removed the key check on file level
**Checklist:**
*Im not sure why is check was implemented*

Fix Language Key-File confusion

---

system/CLI/CLI.php
tests/system/CLI/CLITest.php

This function gets the visible length of a string.
If you have a styled text inside a table, the columns length is wrong.
And is hard to get the string length out in other places too.
**Checklist:**

Add CLI::strlen()

---

system/Common.php
system/HTTP/Response.php
tests/system/CommonFunctionsSendTest.php
tests/system/CommonFunctionsTest.php
tests/system/HTTP/ResponseSendTest.php
tests/system/HTTP/ResponseTest.php

Added tests for response->redirect() and redirect(), and both seem ok.
Closes #1393

Test RedirectResponse problem report

---

system/Database/SQLite3/Utils.php
system/HTTP/Response.php
user_guide_src/source/changelogs/index-not.rst
user_guide_src/source/changelogs/index.rst
user_guide_src/source/changelogs/next.rst
user_guide_src/source/changelogs/v4.0.0-alpha.1.rst
user_guide_src/source/changelogs/v4.0.0-alpha.2.rst
user_guide_src/source/index.rst

Restructure the changelogs, splitting the details into separate files - the changelog was getting excessive.
Also removed some todo comments in SQLite3/Utils.

Changelog(s) restructure

---

user_guide_src/source/outgoing/response.rst

In the class reference of the Response Object in the user guide, statusCode() and reason() are listed. However, it should be getStatusCode() and getReason(), as statusCode() and reason() are not methods in HTTP\Response.

Method naming

---

system/Common.php
system/HTTP/IncomingRequest.php
tests/system/CommonFunctionsTest.php
tests/system/HTTP/IncomingRequestTest.php
tests/system/Session/SessionTest.php

Fixes #1492 
Common::old() needs to check if serialized data before trying to unserialize it.

Fix Common::old()

---

system/Common.php
system/HTTP/IncomingRequest.php

In response to redirect() bug reported as a result of this.
Yes, the unit tests break - evidence of the original reported bug.

Revert to buggy oldInput

---

system/Common.php
system/HTTP/Response.php

Address issue raised in #1501 #1492

Revert RedirectResponse changes

---

system/CodeIgniter.php
system/HTTP/Response.php

Fixes #1393
CodeIgniter was exiting before send all headers when returning a RedirectResponse.
Now, it acts the same way as when returning a Response redirect.
**Checklist:**

Do not exit until all Response is completed

---

system/HTTP/URI.php

There is already `strtolower()` call inside the `setScheme()` function.
**Checklist:**

remove duplicate strtolower() call in URI::setScheme() call

---

.gitignore
tests/system/Commands/SessionsCommandsTest.php

When developer create a migration files, they can commit and share it with other developers. So, I think it should be removed from .gitignore.
**Checklist:**

WIP un-ignore application/Database/Migrations directory from .gitignore

---

system/Validation/FormatRules.php
tests/system/Validation/FormatRulesTest.php

In `Validation\FormatRules::valid_emails()`, if we passed a string: 
```php
','
```
It previously checked as valid email, while empty string is not valid email. We need to check if the string separated by comma is an empty string or not. If empty, then return `false` early.
**Checklist:**

Fix multi "empty" string separated by "," marked as valid emails

---

system/Database/Forge.php
system/Database/MySQLi/Forge.php
system/Database/MySQLi/Result.php
system/Database/Postgre/Forge.php

Previously, there are `count()` and then loop with `for()`, the foreach actually should already can handle it.
**Checklist:**

database performance improvement : use foreach() when possible

---

system/Validation/CreditCardRules.php

For `strlen()`, it already checked with compare to 0 lenght check early, even international character will be catched on it. 
Next, the `is_numeric()` already catch if any non-numeric character.
Next,  `strlen()` and `strpos()` already checked against numeric value before as `is_numeric()` check already handle before.
**Checklist:**

remove mb_* (mb string usage) in CreditCardRules

---

composer.json

ext-json in composer.json

---

system/Autoloader/Autoloader.php
system/Autoloader/FileLocator.php
system/Cache/Handlers/FileHandler.php
system/CodeIgniter.php
system/ComposerScripts.php
system/Database/SQLite3/Forge.php
system/Debug/Toolbar.php
system/Email/Email.php
system/Events/Events.php
system/Files/File.php
system/HTTP/CURLRequest.php
system/HTTP/Files/UploadedFile.php
system/Helpers/filesystem_helper.php
system/Log/Handlers/FileHandler.php
system/Router/Router.php
system/Session/Handlers/FileHandler.php
system/View/Parser.php
system/View/View.php
system/bootstrap.php
tests/system/Cache/Handlers/FileHandlerTest.php
user_guide_src/source/concepts/autoloader.rst
user_guide_src/source/tutorial/static_pages.rst

#1543
Please see following commit.
2b0af133
I think this commit change line is file should be specified.
no problem?
**Checklist:**

Change file exists to is file.

---

system/Database/BaseBuilder.php
system/Database/BaseConnection.php

To avoid create non-existente property values.
**Checklist:**

add property_exists check on BaseBuilder and BaseConnection for $this->$key set value

---

system/Autoloader/FileLocator.php

It seems it was for debugging.
**Checklist:**

remove commented CLI::newLine($tempFiles) at FileLocator class

---

system/HTTP/CURLRequest.php
tests/system/HTTP/CURLRequestTest.php

Add CURLRequest helper methods

---

system/HTTP/Message.php
system/HTTP/Response.php

RedirectException never is thrown. Added some possible throwns.
**Checklist:**

Remove unused RedirectException and add some PHPDocs

---

public/index.php

So it reduce manual change when changing `system` directory.
**Checklist:**

WIP use $paths->systemDirectory in public/index.php 

---

system/Cache/Exceptions/CacheException.php
system/Cache/Handlers/FileHandler.php
system/Language/en/Cache.php
tests/system/Cache/Handlers/FileHandlerTest.php
user_guide_src/source/libraries/caching.rst

By providing `@` in front of `fopen()` will make it always return false on failure fopen, so the catch was never reached, `try {} catch {}` is not needed.
**Checklist:**

remove unneeded try {} catch {} on @fopen at Cache FileHandler::writeFile()

---

system/Common.php
tests/system/CommonFunctionsTest.php

Increase coverage.
**Checklist:**

Test esc() with different encodings and ignore app-only helpers

---

system/Common.php

i.e. useful in autocomplete forms (it is faster to reach this field by id than by name or its position in form)

id attribute support added for csrf_field

---

system/Database/BaseBuilder.php
system/Database/BaseUtils.php
system/Database/Forge.php
system/Database/MySQLi/Connection.php
system/Database/MySQLi/PreparedQuery.php
system/Database/Postgre/Builder.php
system/Database/Postgre/PreparedQuery.php
system/Database/SQLite3/PreparedQuery.php
system/Debug/Exceptions.php
tests/system/Database/Live/DeleteTest.php
tests/system/Database/Live/UpdateTest.php
user_guide_src/source/cli/cli_library.rst
user_guide_src/source/models/model.rst
user_guide_src/source/outgoing/api_responses.rst

remove \ prefix on use statements

---

system/Helpers/form_helper.php
tests/system/Helpers/FormHelperTest.php

as for now there was no way to set empty attribute like required or autofocus

allows to set empty html attr

---

system/Entity.php
tests/system/EntityTest.php
user_guide_src/source/models/entities.rst

Adds new cast types which are casting only if value !== null
i.e. I've got an nullable col in my dbtable which stores strings (empty or not) and I'd like to have possibility to determine if string is null or '';
Now I cannot when I define casting as a string. with this PR if I define ?string in 
```
protected $_options = [
'casts' => [
'usr_id' 			=> 'integer',
'usr_usp_id' 		=> 'integer',
'usr_provider_id' 	=> 'string',
'usr_exc_id'		=> 'integer',
'usr_drs_id'		=> 'integer',
'usr_dlc_id'		=> '?string',
'usr_tzo_id'		=> 'integer',
'usr_email' 		=> 'string',
'usr_password' 		=> 'string',
'usr_first_name' 	=> 'string',
'usr_last_name' 	=> 'string',
'usr_nick_name'		=> 'string',
'usr_is_active' 	=> 'boolean',
'usr_is_blocked' 	=> 'boolean',
'usr_is_picture' 	=> 'boolean',
],
'dates'=> …
```

Adds ?integer, ?double, ?string, etc.  cast types :)

---

user_guide_src/source/tutorial/news_section.rst

Reported on forum. It looks like it once was correct, but deviated.

Fix model namespace in tutorial

---

system/ComposerScripts.php

So in case the "system" directory is renamed, the composer update will install to new renamed directory/ThirdParty directory.
**Checklist:**

remove manual define "system/" directory prefix at ComposerScripts

---

system/Language/Language.php
tests/_support/Language/MockLanguage.php
tests/system/Language/LanguageTest.php

Closes #1262 
Fixes [issue](https://github.com/codeigniter4/CodeIgniter4/issues/1433#issuecomment-437146780) of falling back to parent language.
Currently, the fallback is automatic. Is a config property needed to enable/disable it? I think no.
Test phrases from [here](https://en.wikipedia.org/wiki/Comparison_of_American_and_British_English#Idiosyncratic_differences).
**Checklist:**

Add Language fallback

---

system/Database/MigrationRunner.php

Type hint MigrationRunner methods 

---

system/Debug/Toolbar/Collectors/History.php

fix the access to the filename time part
**Checklist:**

Fix Toolbar file loading throw exception

---

application/Config/Events.php

Previously, I created PR #1510 which made coverage dropped significantly by placing `ob_start()` in  `system/Debug/Exceptions::initialize()`. 
In this PR, I am trying again this with set in in `pre_system` event.
Before patch:
After patch: 
**Checklist:**

Retry handle fatal error via pre_system

---

system/Common.php

`Config\Services` already in use statement.
**Checklist:**

clean up \Config\Services in Common.php

---

system/Session/Handlers/DatabaseHandler.php

replace the static default 'default' group name with the $defaultGroup from Database config
**Checklist:**

use $defaultGroup as default value for database session DBGroup

---

tests/system/Language/LanguageTest.php
user_guide_src/source/changelogs/next.rst

Fix Language testing, update changelog.

Alpha.4 release prep

---

user_guide_src/source/general/modules.rst

Typo. Sentence start with If, should be It.
**Checklist:**
- [N/A] Securely signed commits
- [N/A] Component(s) with PHPdocs
- [N/A] Unit testing, with >80% coverage
- [Y] User guide updated
- [Y] Conforms to style guide

Typo in documentation

---

system/Config/View.php

The original code order would replace app settings with core settings, defeating the purpose of having app settings :-/

Fix View config merge order

---

system/Entity.php

If property was defined as nullable i.e.: `?array, ?json, ?json-array` then it was not cast  .
Solution 1: add all cases with '?' at the beginning to switch.
Solution 2: change type if null was not returned at the beginning of castAs method. - i've picked this one.

Property was not cast if was defined as nullable.

---

system/Files/Exceptions/FileException.php
system/Files/File.php
system/Language/en/Files.php

Refactor the Files module:
- simplified File::getMimeType(), as fileinfo is built-in
- removed two never used exceptions in Files\Exceptions\FileExceptions
- removed the corresponding message lines in Language/en/Files
The exceptions are not thrown by any of our code, and there are equivalent exceptions for uploaded files in the HTTP module.

Refactor Files module

---

system/Filters/Filters.php

in next foreach 
`$this->filters['before'] = array_merge($this->filters['before'], $matches);`  
will be merge last `$matches`,
This may add the last "after" to this "before"
example:
In config:
```
public $filters = [
'admin' => [
'before' => [
'admin',
],
'after' =>[
'admin',
],
],
'owadmin' =>[
'after' =>[
'admin',
],
],
'api' => [
'before' => [
'api/v1/*',
]
],
];
```
`$this->filters` is:
```
Array
(
[before] => Array
(
[0] => admin
[1] => admin
[2] => owadmin
)
[after] => Array
(
[0] => toolbar
[1] => admin
[2] => admin
[3] => owadmin
)
)
```
**Checklist:**

fix. After matches is not set empty

---

user_guide_src/source/database/transactions.rst

fix #1638 #1639 
fix misspelled, change description and title from "Enabling Transactions" section
**Checklist:**

Fix transaction enabling confusing (docu)

---

app/Config/Paths.php

up to `Views` directory can be one up directory and `/Views` from current Config directory, no need to one more up.
```php
__DIR__ . '/../Views';
```
is enough.
**Checklist:**

WIP clean up Paths::$viewDirectory property

---

system/Helpers/html_helper.php

there was an issue when alt was defined in attributes array
was:
```<img src="img.jpg" alt="empty or from $src array" alt="from $attributes" />```
is:
```<img src="img.jpg" alt="from $src if exists" />```
or
```<img src="img.jpg" alt="from $attributes if there is no alt in $src array" />```
Todo:
- parse $attributes if contains string instead of array to check if there is alt attribute in
however this version is better than existing one :)
**Checklist:**
**Notes**
(e.g. fixes …

WIP img fix(?) - html_helper

---

system/Entity.php

I wrote it and works like a charm. Slightly more efficient, because I  some of  array_key_exists don't exist anymore ;). 
But... I noticed an issue when I am trying to save this entity. Property which is set to null is excluded from INSERT what should cause problem if default column value is not set to null but different value - in that case we cannot save null during insert.
In my case should be:
```
INSERT INTO `t_table_search` (`dcs_identifier`, `dcs_conditions`, `dcs_dsc_id`) VALUES ('e77d630b7be1484cb4b7b4f8dbc15c45', '{\"v-school\":[\"1\"],\"v-center\":[\"44\"]}', NULL) // dcs_dsc_id = null;
```
it is:
```
INSERT INTO `t_table_search` (`dcs_identifier`, `dcs_conditions`) VALUES ('e77d630b7be1484cb4b7b4f8dbc15c45', '{\"v-school\":[\"1\"],\"v-center\":[\"44\"]}')// no null for …
```

Nullable support for __set.

---

system/Model.php

We need it outside model if we'd like to run validation rules which are connecting to database OUTSIDE our model.
```
if($this->request->getPost('p'))
{
$post = $this->request->getPost('p');
$user_model = (new \UserModel());
$validation = \Config\Services::validation();
$validation->setRules($user_model->getValidationRules())->run($data, null, $user_model->DBGroup);
d($validation->getErrors(),$this->request->getPost());die();
}
```

DBGroup  in __get(), allows to validate "database" data outside the model.

---

.travis.yml

<strike>Let see if it will make travis build success in php 7.3 env</strike>
**Checklist:**

remove php 7.3 from "allow_failures" in travis config

---

system/Common.php
system/Database/Config.php
system/Database/MigrationRunner.php
system/Exceptions/ConfigException.php
tests/_support/Database/SupportMigrations/001_Some_migration.php
tests/system/Database/Live/ConnectTest.php
tests/system/Database/Migrations/MigrationRunnerTest.php
user_guide_src/source/database/connecting.rst

- decent coverage for MigrationRunner tests
- new `db_connect()` helper method
- Connect can now accept an existing connection, an array of details, or a group name. 
- Forge, Utils and more updated to work with updated connect method
- Fixes bugs during sequential migration running and connection-related when using custom connections.

Migrations Tests and database tweaks

---

app/Config/Modules.php
system/Autoloader/Autoloader.php
system/Autoloader/FileLocator.php
system/Config/BaseService.php
system/Router/RouteCollection.php
system/bootstrap.php
tests/system/Autoloader/AutoloaderTest.php
tests/system/Autoloader/FileLocatorTest.php
user_guide_src/source/concepts/autoloader.rst
user_guide_src/source/general/modules.rst

All PSR4 namespaces are scanned when "discovering" files for our modules by default. This feature can be turned off. 
Applies to all forms of discovery: routes, config files, views, etc.
Fixes #1662

Composer PSR4 namespaces are now part of the modules auto-discovery

---

user_guide_src/source/changelogs/index.rst
user_guide_src/source/changelogs/next.rst

As the title says. Just thought the changelog should start showing up :-/

Changelog alpha.5 so far

---

tests/system/Database/Live/AliasTest.php
tests/system/Database/Live/ConnectTest.php
tests/system/Database/Migrations/MigrationRunnerTest.php

Three of the database tests were not flagged as being in the DatabaseLive group, causing failure of the non-DB unit tests (184 errors!). Fixed this.

Add missing test group directives

---

system/Database/BaseBuilder.php
system/Database/BaseConnection.php
system/Database/Query.php
tests/_support/Database/MockConnection.php
tests/system/Database/Builder/DeleteTest.php
tests/system/Database/Builder/InsertTest.php
tests/system/Database/Builder/LikeTest.php
tests/system/Database/Builder/UpdateTest.php
tests/system/Database/Builder/WhereTest.php
tests/system/Database/Live/InsertTest.php

Add in missing don't escape feature that seemed to be missing since the original DB refactor. 
Fixes #1667

Implement Don't Escape feature for db engine

---

system/Config/Services.php
system/Debug/Exceptions.php

Default view directory name is not work in  CodeIgniter\Config\Services\parser.
**Checklist:**

Fix viewsDirectory bug Fixes #1701

---

system/Model.php

phpdoc + pk -> primaryKey +   $data->$var -> $data->{$var}

minors (Model.php)

---

system/Database/Seeder.php

Seeder adds default namespace to seeds when no namespace has been provided. Fixes #1720

Seeder adds default namespace to seeds

---

app/Config/Cache.php
system/Cache/Handlers/RedisHandler.php
user_guide_src/source/libraries/caching.rst

Update Cache RedisHandler to support select database.
As this feature already exist in Session RedisHandler
**Checklist:**
- [ Y ] Securely signed commits
- [ N/A ] Unit testing, with >80% coverage
- [ Y ] User guide updated
- [ Y ] Conforms to style guide

Update Cache RedisHandler to support select database.

---

system/Cache/Handlers/RedisHandler.php

Log an error if redis authentication is failed in Cache RedisHandler
**Checklist:**
- [ Y ] Securely signed commits
- [ N/A ] Unit testing, with >80% coverage
- [ N/A ] User guide updated
- [ Y ] Conforms to style guide

Log an error if redis authentication is failed.

---

tests/system/EntityTest.php
tests/system/I18n/TimeTest.php

Some of the travis-ci timings are a second off because of long execution times.
This addresses those by checking if two formatted time resutls are "close enough", i.e. no more than 1 second different.

Accommodate long travis execution times

---

system/View/View.php
tests/system/View/ViewTest.php
tests/system/View/Views/extend.php
tests/system/View/Views/extend_two.php
tests/system/View/Views/layout.php
user_guide_src/source/changelogs/next.rst
user_guide_src/source/outgoing/index.rst
user_guide_src/source/outgoing/view_layouts.rst

Provides the ability to use layout views that can then be extended by child views, with content sections.

New View Layout functionality for simple template functionality.

---

system/Validation/Rules.php

Fix required_with rule bug.
**Checklist:**

Fix required_with rule bug. Fixes #1728

---

system/Validation/Rules.php
user_guide_src/source/libraries/validation.rst

- Unable to get the value of the validation field correctly.
- Update validation class  document.
**Checklist:**

Fix required_without rule bug.

---

user_guide_src/source/dbmgmt/forge.rst

A paragraph was incorrectly positioned between two segments of code that should be continuous, and was missing from its proper heading under "Foreign Keys"
**Checklist:**

Guide: Moving misplaced text under correct heading

---

user_guide_src/source/installation/running.rst

The app config file no longer has an encryption key setting, which used to be required in order to use Sessions. This has caused some confusion on the forums and should probably be removed until if changes to the Session class require it.
**Checklist:**

Remove reference to Encryption Key in User Guide

---

user_guide_src/source/intro/psr.rst

The external link to the style guide under "PSR Compliance" had the underscore in the wrong place.
**Checklist:**
**Notes**

Fixed typo preventing link format

---

admin/framework/composer.json
admin/starter/composer.json
composer.json

Composer gives warnings about uppercase letters in paths. It looks like this one was missed at some point - fixing across 3 package locations.
**Checklist:**

lowercase 'vfsStream' in composer files

---

system/Language/en/View.php

There was an unneeded double-quote that I suggest to be removed.
**Checklist:**

Correct the unneeded double-quote (typo)

---

system/Helpers/date_helper.php
system/Helpers/number_helper.php
system/Helpers/security_helper.php
system/Helpers/text_helper.php
system/Helpers/url_helper.php
user_guide_src/source/helpers/number_helper.rst

There are some return types and description spelling mistakes present, which need to be corrected for a better understanding
**Checklist:**

Helper changes

---

user_guide_src/source/cli/cli_commands.rst

Without CLI\CLI the demo command `run` listed below will fail with: Class 'App\Commands\CLI' not found. Adding the `use` so others don't run into this issue following the guide
**Checklist:**

Add CLI namespace to example

---

system/Model.php

Model chunk is currently returning default return type, instead of the model-specific type. This change makes chunk() consistent with findAll() by changing getResult() to use tempReturnType.
Original discussion: https://forum.codeigniter.com/thread-72953.html
**Checklist:**

Set Model->chunk return type

---

user_guide_src/source/database/examples.rst

In the user guide database examples open line incorrectly references a DB function "getAffectedRows" which should be "affectedRows"
**Checklist:**

Replace nonexistent "getAffectedRows"

---

system/Cache/Handlers/WincacheHandler.php
tests/system/Cache/CacheFactoryTest.php
tests/system/Cache/Handlers/FileHandlerTest.php

Test: Improve Cache coverage

---

system/Common.php
user_guide_src/source/general/common_functions.rst

Some corrections in common functions w.r.t,
- Spelling
- Function argument datatype and return type
- Consistency with entire documentation like, do not show datatype and return type with the function definition.
**Checklist:**

Common function correction

---

system/Validation/Rules.php
tests/system/Validation/RulesTest.php

Previously, there is a `! is_numeric()` check with return false early, so the `numeric` check is no need mbstring check with `mb_strlen()`, the `strlen()` is enough.
**Checklist:**

replace mb_strlen() to strlen() in various rules as already return early in ! is_numeric

---

system/Validation/FormatRules.php
tests/system/Validation/FormatRulesTest.php

decimal rule
integers are subset of decimals / floats. so i think  decimal validation rule should pass if value contains decimal OR integer.

decimal rule. shouldn't it accept integers?

---

system/CodeIgniter.php

This allow overriding Closures to have messages for its parameter:
`
$routes->set404Override(function($message)
{
$data['message'] = $message;
echo view('errors/html/error_404_cs.php',$data);
});
`
I also update the docs

Enhance 404Override

---

user_guide_src/source/libraries/pagination.rst

Per conversation https://github.com/codeigniter4/CodeIgniter4/pull/1816
Bootstrap 4 now requires additional class identifiers on the nav items. Rather than adding these classes and "committing" to Bootstrap this updates the User Guide to remove references to Bootstrap support, and users may write their own views to support navigation styling.
**Checklist:**

Remove legacy Bootstrap references in Pagination class

---

system/Exceptions/PageNotFoundException.php

The function is designed to check for a default message but since a parameter is required it will fail with "missing parameter" unless explicitly passed null. Add a default value of null allows it to be appropriately overloaded.
This change brings it in line with what the User Guide already expects: https://codeigniter4.github.io/CodeIgniter4/general/errors.html#pagenotfoundexception
**Checklist:**

Exception 'forPageNotFound' missing default value

---

contributing.md
contributing/README.rst

A handful of links in contributing.md were pointed at a GitHub.io site that's not there. I updated them to the internal .rst equivalents. In contributing/ there were another few as well.
**Checklist:**

Fix contributing links

---

user_guide_src/source/libraries/sessions.rst

The Session Library class had recommendations for alternatives to some old CI3 Session methods but was actually referencing another CI3 method as well.
**Checklist:**

Replace CI3 $this->input reference

---

admin/starter/.gitignore

The .gitignore coming through Composer AppStarter appears to be an old CI3 version - copying the root CI4 version here @jim-parry's recommendation
https://github.com/codeigniter4/appstarter/pull/3
**Checklist:**

Replace old CI3 .gitignore with root CI4 version

---

system/Test/ControllerResponse.php
system/Test/ControllerTester.php
system/Test/DOMParser.php
tests/_support/Controllers/Popcorn.php
tests/system/HTTP/ContentSecurityPolicyTest.php
tests/system/Test/ControllerTesterTest.php
tests/system/Test/DOMParserTest.php
user_guide_src/source/testing/controllers.rst

Minor fixes for DOMParser & ControllerTester
Unit testing for these
DOMParser: 
- blocked two exceptions from code coverage - one because it will never happen in travis-ci, and the other because I don't see a way of inducing it, given how forgiving the DOMDocument is in building a DOM from a string
- fixed the attribute xpath testing
ControllerTester:
- added logger to the mix, since the Controller class expects is
- fixed handling of a controller method returning a string instead of echoing stuff

Test: fix & test Test/ControllerTest, tested

---

system/Router/Router.php

Fixes #1838 
Remove the replacement of `/` with `\` in the `$to` part of routes. This ensures that routes like `$routes->add('blog/joe', 'Blogs::users/34');` will work.
**Checklist:**

Dont replace slashes with backslashes in the to route

---

system/Test/ControllerTester.php
tests/_support/Controllers/Popcorn.php
tests/system/Test/ControllerTesterTest.php

The response body was not set properly, if the result was JSON.

Fix: ControllerTester::execute. Fixes #1834

---

system/Commands/Utilities/Routes.php

The CLI command Routes iterates routes from system & app to display them as a table, but ends up trying to display callbacks. This change ignores any `$to` destinations that aren't strings.
**Checklist:**

Ignore callbacks in routes list

---

system/Autoloader/FileLocator.php
system/Database/MigrationRunner.php
user_guide_src/source/dbmgmt/migration.rst

Currently MigrationRunner searches app/Config/Autoload.php for specified namespaces to include in migrations when a namespace is specified (or with "all"). This change uses the Autoloader service to search all discovered namespaces, so will include appropriately-namespaced migrations loaded from other sources (e.g. Composer).
**Checklist:**

Migrationrunner use autoloader

---

app/Controllers/BaseController.php
app/Controllers/Home.php
system/Config/Routes.php
user_guide_src/source/extending/basecontroller.rst
user_guide_src/source/extending/core_classes.rst

Create a default extended controller at app/Controllers/BaseController.php and updates Home controller and the User Guide to recommend using this for new Controllers. From a development standpoint, it makes sense to start with this extension even if it doesn't have any modifications since making the change down the road involves going back and editing every controller.
There was a fair amount of discussion on this idea in the forums already. See: https://forum.codeigniter.com/thread-73095.html
**Checklist:**

Extend Controller to BaseController by default

---

system/Validation/Rules.php
user_guide_src/source/libraries/validation.rst

w.r.t #1747, the functionality of required_with and required_without works as expected.
But the method definition is quite confusing. So according to functional implementation, I have changed the same.
**Checklist:**

required_with and required_without definition changes

---

system/Debug/Toolbar/Collectors/History.php

History::SetFiles check #1778
As per the issue raised, In case one of the files in WRITEPATH.'debugger/debugbar_*.json is empty the method setFiles will crash. The reason for the crash is that History::setFiles does not check if the local variable $contents contain an object before using it in the assignment.
I have added a check whether the JSON is valid or not. If not then it will skip the iteration else proceed with it.
**Checklist:**

History::SetFiles check #1778

---

system/Database/MigrationRunner.php
tests/system/Database/Migrations/MigrationRunnerTest.php
user_guide_src/source/dbmgmt/migration.rst

MigrationRunner issue with definition resolved #1766
**Checklist:**

MigrationRunner issue with definition resolved

---

system/Config/Routes.php
system/Controller.php
tests/system/ControllerTest.php

Fix for https://github.com/codeigniter4/CodeIgniter4/issues/1849 - changes system/Controller.php methods to `protected` and adds a 404 route for initController method
**Checklist:**

Secure routable controller methods

---

system/Commands/Server/Serve.php

- Fixed issue #1880 - Error when running `php spark serve` (spaces in folder names)
- Fixed a few typos 
- Updated code style
**Checklist:**

Fixed issue #1880, fixed a few typos and updated code style

---

system/CLI/CLI.php

Null column values in `table()` currently throw a type error because it uses `strlen()` to determine column spacing and `strlen()` accepts strictly strings. Allowing `strlen()` to process `null` values as length 0 lets CLI commands pass otherwise-untouched data from Builder, since other types (e.g. int) are already cast as strings.
This also mimics the behavior of PHP's `strlen()` which returns 0 for `null`.
**Checklist:**

Allow CLI::strlen null parameter

---

user_guide_src/source/cli/cli_library.rst

Note which colors may be used for backgrounds
**Checklist:**

Add CLI background color list to the user guide

---

system/Commands/Server/Serve.php

When php, host, and port variable has `escapeshellarg()` check, the `??` will use the value result of `escapeshellarg()` that can has result empty single quote string : "''"
**Before**
**After**
**Checklist:**

Fix spark serve with remove escapeshellarg() on php,host, and port

---

system/Database/BaseConnection.php
system/Database/Forge.php
system/Database/MySQLi/Forge.php
system/Database/Postgre/Forge.php
system/Database/SQLite3/Forge.php
user_guide_src/source/dbmgmt/forge.rst

Database Forge correction.
At the time of loading Forge file, getting IDE error of "cannot use [] for reading".
Attaching the screenshot of IDE here.
**Checklist:**

Database Forge correction

---

public/.htaccess

Update .htaccess for better security and caching
Added a few points like,
- Disable directory access
- CORS setting
- Disable image hotlinking
- Disable server signature
- mod expires for caching
- Added GZip and DEFLATE types
**Checklist:**

Update .htaccess for better security and caching

---

system/Database/Exceptions/DataException.php
system/Language/en/Database.php
system/Model.php
tests/system/Database/Live/ModelTest.php
user_guide_src/source/models/model.rst

W.r.t #1619, correction in the codes and introduced test cases as well
Its a shorthand query.
**Checklist:**

New method Find Column w.r.t. #1619

---

system/Database/MySQLi/Connection.php

Mysql connection issue with MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT #1219
**Checklist:**

Mysql connection issue with MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT #1219

---

user_guide_src/source/incoming/routing.rst

Reorganizes and adds information on route filtering, including supplemental information on filter parameters that was previously missing.
**Checklist:**

Add filter parameters to User Guide

---

system/Cache/Handlers/FileHandler.php
system/Cache/Handlers/MemcachedHandler.php
system/Cache/Handlers/PredisHandler.php
system/Cache/Handlers/RedisHandler.php
system/Cache/Handlers/WincacheHandler.php
tests/system/Cache/Handlers/FileHandlerTest.php
tests/system/Cache/Handlers/MemcachedHandlerTest.php
tests/system/Cache/Handlers/RedisHandlerTest.php
user_guide_src/source/general/common_functions.rst
user_guide_src/source/libraries/caching.rst

Currently there is no way to distinguish between returns of a cached value `false` and "no matching key". This changes each handler to return `null` when a key isn't found.
Fixes https://github.com/codeigniter4/CodeIgniter4/issues/1870
**Checklist:**

Unmatched Cache Library `get()` return null

---

system/CLI/CLI.php
tests/system/CLI/CLITest.php
user_guide_src/source/cli/cli_library.rst

Added print method to CLI library so you can print multiple times on same line.

Added print method to CLI library so you can print multiple times on same line

---

tests/system/Router/RouteCollectionTest.php

Add a battery of tests proving correctness of reverse routing with subdomains, per the docs.
Closes #1697 
If different behavior is expected, that should be raised as a feature request, probably on the forum.

Additional RouteCollectionTests

---

system/Entity.php
tests/system/EntityTest.php

W.r.t #512 Adding test scenarios to increase the coverage of Cast Exception
WIP JSON Cast exception test cases.
**Checklist:**

JSON Cast exception test cases

---

system/Database/BaseBuilder.php

missing return

---

user_guide_src/source/testing/overview.rst

Suggestions from the slack channel

Docs: improve app testing writeup

---

system/Database/BaseBuilder.php

Is it breaks anything or will repair having('MAX(sth)', null, false)
before:
```
SELECT `aht_cur_id_2` `cur_id_2`, `aht_cur_id_1` `cur_id_1`, `aht_rate` `rate`
FROM `t_api_trading_trades`
GROUP BY `aht_cur_id_2`, `aht_cur_id_1`
HAVING MAX(aht_api_trade_id) IS NULL
```
now:
```
SELECT `aht_cur_id_2` `cur_id_2`, `aht_cur_id_1` `cur_id_1`, `aht_rate` `rate`
FROM `t_api_trading_trades`
GROUP BY `aht_cur_id_2`, `aht_cur_id_1`
HAVING MAX(aht_api_trade_id)
```

having (Is NULL deletion)

---

system/Debug/Toolbar/Views/toolbarloader.js.php

I fixed the Toolbar JS Code for IE Browsers. 
The Internet Explorer Browsers including IE11 doesn't with `window.XMLHttpRequest`, these Browsers need an ActiveXObject like this `new ActiveXObject('Microsoft.XMLHTTP')`.
Fixes #1905 
**Checklist:**

Toolbar IE11 fix

---

system/Model.php
tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
tests/system/Database/Live/ModelTest.php

In the stated issue #1773, he is trying to save the null value in the database which expected to throw an error of required field.
But when data is passed from the insert method to classToArray, it expects to return only changed values.
The previous and current value of the property is null, hence it is not returning the property as changed value.
Hence error is not getting triggered.
So some required changes made here like,
1. Made allowed null for description column of job table in migration
2. Removed if condition from save() method as again update() or save() method performs same operation in the classToArray() method.
3. Introduced $onlyChanged parameter to classToArray() function. So we can escape the only changed value check in case of insert the data but it will return only …

Model Changes w.r.t. #1773

---

system/Commands/Server/rewrite.php

no need to set $_SERVER['CI_ENVIRONMENT'] variable in rewrite.php.
removed $_SERVER['CI_ENVIRONMENT'] in rewrite.php
file path : appstarter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php
Line : 20
**Reason :**
$_SERVER['CI_ENVIRONMENT'] = 'development'; defined in rewrite. php
it is replacing CI_ENVIRONMENT variable value.
#1268
**Checklist:**

removed $_SERVER['CI_ENVIRONMENT']

---

system/Entity.php
system/Exceptions/EntityException.php
system/Language/en/Entity.php

As for now if code calls non existed property of entity causing ErrorException with no info at all.
This PR is changing ErrorException to EntityException with translated information like this:
"Trying to access non existent property fle_amount_fromss of App\Entities\Fee\FeeLevel"

Entity exception for non existed props.

---

public/.htaccess

The rewrite rule required a hard-coded domain which developers would need to update or their assets would give 403 errors. Better to allow developers to add this themselves than supply an .htaccess file that doesn't work out-of-the-box.
**Checklist:**

Remove section that prevents hotlinking

---

system/Database/BaseBuilder.php
system/Database/BaseConnection.php
system/Database/BasePreparedQuery.php
system/Database/BaseResult.php
system/Database/BaseUtils.php
system/Database/Config.php
system/Database/ConnectionInterface.php
system/Database/Exceptions/DataException.php
system/Database/Migration.php
system/Database/MigrationRunner.php
system/Database/MySQLi/Connection.php
system/Database/MySQLi/PreparedQuery.php
system/Database/MySQLi/Result.php
system/Database/MySQLi/Utils.php
system/Database/Postgre/Builder.php
system/Database/Postgre/Connection.php
system/Database/Postgre/PreparedQuery.php
system/Database/Postgre/Result.php
system/Database/Postgre/Utils.php
system/Database/QueryInterface.php
system/Database/ResultInterface.php
system/Database/SQLite3/Connection.php
system/Database/SQLite3/PreparedQuery.php
system/Database/SQLite3/Result.php
system/Database/SQLite3/Table.php
system/Database/SQLite3/Utils.php
tests/_support/Database/MockConnection.php
tests/_support/Database/MockResult.php

Database typos fixes
**Checklist:**

Database typos changes

---

system/Config/BaseConfig.php
tests/system/Config/BaseConfigTest.php

In origional `BaseConfig.php` file, in `registrProperties` function, it use `locator` to find all `Config/Registrar.php` files in known namespace, and it returned all file path as an array.
In following code, it use the file path as a callable object, to check if registrars exists (by using method_exists) for current config file, which didn't work in my case.
I'm not sure if method_exists works with file path, but I updated this function to load all registrars files first before future usage.
**Checklist:**

Fix BaseConfig didn't load Registrar files properly

---

system/Debug/Toolbar/Collectors/History.php

[https://github.com/codeigniter4/CodeIgniter4/issues/1944](url)
When the full path of debugbar file contains some digits, the first group of digits was extracted as timestamp and the datetime displayed in the Hisory toolbar was wrong.
Changed how the time is extracted from bedugbar filename by getting the las group of digits founded by preg_match_all function.
**Checklist:**

Fix datetime extraction from debugbar file

---

system/Entity.php
system/Model.php
tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
tests/_support/Models/EntityModel.php
tests/_support/Models/EventModel.php
tests/_support/Models/JobModel.php
tests/_support/Models/SecondaryModel.php
tests/_support/Models/SimpleEntity.php
tests/_support/Models/UserModel.php
tests/_support/Models/ValidErrorsModel.php
tests/_support/Models/ValidModel.php
tests/system/Database/Live/DbUtilsTest.php
tests/system/Database/Live/GetTest.php
tests/system/Database/Live/ModelTest.php
tests/system/Database/Migrations/MigrationTest.php

Model, Entity, Exception & Migration Test Cases to improve code coverage.
**Checklist:**

Model, Entity, Exception & Migration test cases

---

system/Database/BaseBuilder.php
system/Database/BaseConnection.php
system/Entity.php

Fix some side issue
**Checklist:**

Fix some side issue

---

system/Filters/Filters.php

A previous commit (https://github.com/codeigniter4/CodeIgniter4/commit/ceae97469c01bc96d58e439697ec6bd584bea728#diff-63f8289a599089d6c44102ec8149bec1) accidentally overwrote the changes to allow filters to pass arguments to their targets. This restores the functionality.
Someone should probably also look into why `testEnableFilterWithArguments()` has been passing with arguments disabled.
**Checklist:**

Add back filter arguments

---

system/Debug/Toolbar/Collectors/BaseCollector.php
system/Debug/Toolbar/Views/toolbar.tpl.php

Custom collectors fail because toolbar.tpl.php tries to parse their view file from `SYSTEMPATH . 'Debug/Toolbar/Views/'`. See #1971 for complete description of the issue.
This change allows `Collector->display()` to return a string (as stated in the User Guide) and then, when detected in the view template, displays it directly instead of looking for a separate template to parse.
*There's probably a better way to handle this by checking for a namespaced view template for the collector.*
**Checklist:**

Toolbar fix for custom collectors

---

system/Router/Router.php

fixes #1965 
Rebuild array index of uri segments from array_filter(), solve $segments[0] index undefined error
**Checklist:**

Fixed pathinfo mode 404 error, rebuild array index of uri segments from array_filter()

---

system/Model.php

String type primary key should also wrap into an array during db update
Following `$builder->whereIn()` expect it to be an array.
**Checklist:**

String type primary key should also wrap into an array during db update

---

system/Debug/Toolbar/Views/toolbarloader.js.php
system/Helpers/url_helper.php

In `toolbarloader.js.php`, the tail slash in `url` is trimmed, so when build a request url in xhttp.open, it should add one tail slash (Otherwise server will do a 301 redirection to the one with tail slash first)
**Checklist:**

Fix Debugbar url tail slash issue

---

app/Config/App.php
app/Config/Migrations.php
public/.htaccess
system/Debug/Toolbar/Collectors/Config.php
system/Debug/Toolbar/Views/_config.tpl.php
user_guide_src/source/dbmgmt/migration.rst

- Remove salt from app config since it was only there for encryption anyway and isn't used anywhere.
- Migrations should be enabled by default to remove a frustration of getting started.
- Simplify the provided htaccess file with only a couple of security items and the rewrite functionality.

Defaultfixes

---

system/Session/Handlers/RedisHandler.php

Was previously a boolean value, but specs call for a string being returned.

Corrected return value for Session/RedisHandler::read to string, per PHP specs

---

system/Filters/Filters.php
tests/system/Filters/FiltersTest.php

Reworked & refactored innards of Filters, specifically processGlobals and processFilters.
They had a few issues.
**Checklist:**
- [-] Component(s) with PHPdocs
- [-] User guide updated

Fix filter processing. Fixes #1907

---

system/Entity.php
tests/system/EntityTest.php
user_guide_src/source/models/entities.rst

Overload Entity `hasChanged()` to support a check if any attributes have been changed.
**Checklist:**

Allow hasChanged() without parameter

---

system/Router/RouteCollection.php
tests/system/Router/RouteCollectionTest.php

`reverseRoute` searches loaded routes for a string match, but will throw an exception on unmatched routes when it tries to `trim` any routes whose definitions are closures. This ignores non-string destinations in the secondary search phase.
Fix for https://github.com/codeigniter4/CodeIgniter4/issues/1953
**Checklist:**

Prevent reverseRoute from searching closures

---

system/Database/BaseBuilder.php

set should accept at least NULL | int | string
UPDATE x SET a = NULL ...
UPDATE x SET a = 100
UPDATE x SET a = 'aaa'

argument set() must by type of string - cannot agree

---

system/Commands/Utilities/Routes.php

`$routes->resource()` includes the `patch` method as a supported route but the routes CLI command doesn't list it because it is missing from the $methods property - this includes it.
**Checklist:**

Add `patch` method to command "routes"

---

system/CodeIgniter.php
system/Router/RouteCollection.php
tests/system/Router/RouteCollectionTest.php

By default the loaded route collection uses REQUEST_METHOD directly from $_SERVER:
$this->HTTPVerb = strtolower($_SERVER['REQUEST_METHOD'] ?? 'cli');
This means when Router->checkRoutes() matches its collection it uses the actual request method instead of the spoofed method from the Request object. This PR injects the proper HTTP verb prior using `$request->getMethod()`
To recreate the bug, create a resource route to a non-autorouted controller:
$routes->resource('foo', ['controller' =>'MyNamespace\Controllers\Foo']); And then try to access one of the non-POST supported methods by spoofing: Routing ignores the PUT routes and attempts to autoroute:Controller or its method is not found: App\Controllers\Foo`
**Checklist:**

Use request->method for HTTP verb

---

user_guide_src/source/installation/installing_composer.rst

As discussed on the community forums, the appstarter doesn't work out of the box after a fresh installation. This was determined to be due to the composer.lock file being out of date, running composer update installs the up to date version of the framework.
Updated the installation via Composer documentation to direct users to follow the steps in the "Upgrading" section even after a fresh installation. This ensures the framework is up to date.
**Checklist:**

Direct user to follow the upgrade steps after installation

---

system/Database/MySQLi/Result.php
system/Database/Postgre/Result.php
system/Database/SQLite3/Result.php
system/Entity.php

When we create, for example, the password hashing method Entity::setPassword(), this method is also called when the value from the database is filled.
As a result, we get a hash of the hash in $entity->password
This PR sets the value of the $attribute property to the unchanged values from the database.
**Checklist:**

Set the raw data array without any mutations for the Entity

---

system/CodeIgniter.php
system/Config/Services.php
system/HTTP/CLIRequest.php
system/HTTP/Request.php
system/Router/RouteCollection.php
system/Router/Router.php
system/Router/RouterInterface.php
tests/system/CLI/ConsoleTest.php
tests/system/CodeIgniterTest.php
tests/system/HTTP/CLIRequestTest.php
tests/system/Router/RouteCollectionTest.php
tests/system/Router/RouterTest.php

Refactor the way the router and route collection determine the curren…t HTTP Verb. 
Closes #2022 
Fixes #2021

Refactor the way the router and route collection determine the current HTTP verb.

---

system/Router/Router.php

The updated router sets the routes `HTTPVerb` based off the request method, and currently falls back to `get`. This changes the fallback to be the default value from `$_SERVER['REQUEST_METHOD']`.
**Checklist:**

Fallback to server request for default method

---

system/Common.php

`force_https()` is calling `exit()` before applying the header set by `$response->redirect()`, so the browser treats it as a clean exit, no errors (i.e. blank page). Fix for #2033 
**Checklist:**

Make `force_https()` send headers before exit

---

system/Filters/Filters.php

Restrict filter matching of uris so they require an exact match. Fixes #2038

Restrict filter matching of uris so they require an exact match. Fixes #2038

---

system/Router/Router.php
system/Test/FeatureTestCase.php
tests/system/Router/RouterTest.php
tests/system/Test/FeatureTestCaseTest.php

Zero params should be passed through when routing. Fixes #2032

Zero params should be passed through when routing. Fixes #2032

---

system/Database/BaseConnection.php
system/Database/Forge.php
system/Database/MySQLi/Connection.php
system/Database/Postgre/Connection.php
system/Database/SQLite3/Connection.php
system/Database/SQLite3/Forge.php
system/Database/SQLite3/Table.php
tests/system/Database/Live/ForgeTest.php
tests/system/Database/Live/SQLite/AlterTableTest.php
user_guide_src/source/dbmgmt/forge.rst
user_guide_src/source/dbmgmt/migration.rst

SQLite3 now supports dropping foreign keys. Fixes #1982

SQLite3 now supports dropping foreign keys. Fixes #1982

---

system/Model.php

If any afterInsert events call their own database insert then `db->insertID()` will return that key instead of the desired version. This change grabs the insert ID before triggering the event so it can be returned (if requested) after.
**Checklist:**

Stash insert ID before event trigger

---

tests/system/Database/Live/WhereTest.php

While working on implementing `deleted_at` I noticed there aren't good explicit tests for `IS NULL` and `IS NOT NULL`. This change provides these tests (hopefully in the right place).
**Checklist:**

Add various tests for (not) null

---

system/Model.php
tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
tests/_support/Models/EntityModel.php
tests/_support/Models/EventModel.php
tests/_support/Models/UserModel.php
tests/system/Database/Live/DbUtilsTest.php
tests/system/Database/Live/ModelTest.php
user_guide_src/source/models/model.rst
user_guide_src/source/testing/database.rst

First attempt. Change all references to `deleted` to use `deleted_at` instead. Direct references to these fields now use dates, and tests check `IS NULL` and `IS NOT NULL` instead of binary values.
**Checklist:**

Soft deletes use deleted_at

---

system/Exceptions/ModelException.php
system/Language/en/Database.php
system/Model.php
tests/system/Database/Live/ModelTest.php
user_guide_src/source/models/model.rst

Currently if `useTimeStamps` or `useSoftDeletes` is true but `dateFormat` is empty or not one of (int, datetime, date) then database changes will continue quietly but with `NULL` date fields. This PR creates a new ModelException to be thrown whenever setDate fails to determine a valid date from (int, datetime, date).
**Checklist:**

Add model exceptions for missing/invalid dateFormat

---

system/Autoloader/FileLocator.php

Currently `locateFile()` flattens namespace paths to a single path per namespace (see https://github.com/codeigniter4/CodeIgniter4/issues/1866). This fix searches all namespace paths for the first matching file.
This change also removes the auto-capitalize of namespaces as this is not a namespace requirement and could cause `locateFile` to fail to match valid file namespaces.
**Checklist:**

Add multi-path support to `locateFile()`

---

system/HTTP/IncomingRequest.php

Ensure query vars are part of request->uri. Fixes #2062

Ensure query vars are part of request->uri. Fixes #2062

---

system/Autoloader/FileLocator.php

https://github.com/codeigniter4/CodeIgniter4/pull/2059 introduced a scenario where the combination of `$path` and `$folder` could fail to have a separating slash. This PR moves the trailing slash safety check prior to the folder test.
**Checklist:**

Bugfix file locator slash error

---

system/Config/Config.php

Calling `config($classname)` with an un-namespaced class passes the string to `$locator->locateFile()` which causes it to use `legacyLocate()`, which searches App and System only. This change leaves the default behavior but falls back to `$locator->search()` instead of failing immediately, allowing calls like `config('Auth')` to check first in **App** and **System** and then in any autoloaded namespaces.
**Checklist:**

Update config() to check all namespaces

---

system/Throttle/Throttler.php
tests/_support/Cache/Handlers/MockHandler.php
tests/system/Throttle/ThrottleTest.php

I was encountering an issue with the rate limiting which was causing it not to behave as expected.
If i set a rate limit of 1 request a minute, I would be able to make much more than 1 request a minute provided that the requests are a few seconds apart.
This is because the original "bucket"'s life time gets updated to the time between the 1st and 2nd request, meaning the 3rd request typically creates a new "bucket".
**Edit**
Added an additional commit to resolve an additional issue regarding calculating how many seconds must pass before a new token is available. (https://github.com/codeigniter4/CodeIgniter4/pull/2074/commits/8e0ab844be5889a8703b23fcd9dc9caea6cddb70)
Added an additional commit to update ThrottleTest to getTokenTime() to have a value greater than 1 …

Throttler can access bucket for bucket life time

---

system/Cache/CacheFactory.php
system/Cache/Handlers/MemcachedHandler.php
system/Cache/Handlers/PredisHandler.php
system/Cache/Handlers/RedisHandler.php

If our application is unable to connect to Redis, a CriticalError exception is now thrown.
CacheFactory catches the CriticalError exceptions that are thrown when Redis, Memcache and Predis fail to connect, it logs the exception and then attempts to initialize the backup cache driver (and if that fails it initializes dummy).
**Checklist:**

Cache Drive Backups 

---

system/Pager/Pager.php
user_guide_src/source/libraries/pagination.rst

Allows to specify a group name in a makeLinks method - implicated i.e. allowance to set custom path for pagination.

Extension Pager::makeLinks (optional grup name)

---

system/Files/File.php
user_guide_src/source/libraries/uploaded_files.rst

Correct `File` library in a few instances where it assumes an extension. (#2103)
Update User Guide for correct method names. (#2102)
**Checklist:**

File & UploadFile Fixes

---

user_guide_src/source/changelogs/next.rst
user_guide_src/source/libraries/pagination.rst

Update the changelog for beta.4
Correct an error in the pagination page of the user guide.

Prep for beta.4

---

system/Common.php

There was typo in checking procedure if exists db_connect(), typo was making fatal error when was made custom function because double declaration.
**Checklist:**

Fix typo in checking if exists db_connect()

---

system/Images/Handlers/BaseHandler.php
system/Images/ImageHandlerInterface.php
tests/system/Images/GDHandlerTest.php
user_guide_src/source/libraries/images.rst

Currently there is no way to indicate to GD the image file type to create. `GD->save()` uses `image->imageType` to determine the method, regardless of extension.
`convert()` acts as a setter for `image->imageType` which will later be read by `save()` to modify the file output type.
**Note** ImageMagick already saves the format based on the indicated extension, and will not be affected by this addition.
**Checklist:**

Add Image->convert()

---

system/Debug/Toolbar.php
system/Filters/DebugToolbar.php

Fix for #2117. This change injects `$response` from the filter to the toolbar and checks for a DownloadResponse. If found, the toolbar quits.
**Checklist:**

Disabled Toolbar on downloads

---

system/Session/Handlers/RedisHandler.php

Fixes #2121 
Updated RedisHandler to support redis 5.0.x and php 7.3.x by removing deprecated calls and updating ping() handling. This while maintaining backward compatibility with redis 4.1.x and php 7.2.x
**Checklist:**

Updated redis session handler to support redis 5.0.x

---

user_guide_src/source/dbmgmt/migration.rst

One small change on a missed section, `current()` no longer exists.
**Checklist:**

Update migration User Guide

---

system/Database/BaseBuilder.php

Update BaseBuilder `limit` function, since `$offset` is nullable.
**Checklist:**

Update limit function since $offset is nullable

---

system/HTTP/DownloadResponse.php
tests/system/HTTP/DownloadResponseTest.php
user_guide_src/source/outgoing/response.rst

Currently an HTTP Response created with download() can take either a path or data with a filename, but when the path option is used the filename is set to the actual local file. This adds a setter to the DownloadResponse so a developer can supply a new name for the file on download.
**Checklist:**

Add setFileName() to DownloadResponse

---

system/HTTP/Files/UploadedFile.php

Currently **UploadedFile.php** has `getExtension()` returning a string (not nullable) but `Mimes::guessExtensionFromType()` can return null, effectively causing an exception anytime a file is uploaded whose extension does not match the current Mime config list. This change causes `getExtension()` to return the client file's extension if Mime returns null.
I suspect this was the original intent for passing `$this->getClientExtension()` as the second parameter to `Mimes::guessExtensionFromType()`, but that acts as an arbitrator for duplicates rather than a fallback.
**Checklist:**

guessExtension fallback to clientExtension

---

app/Controllers/BaseController.php
composer.json

clean base controller code 

---

system/API/ResponseTrait.php
tests/system/API/ResponseTraitTest.php
user_guide_src/source/outgoing/api_responses.rst

Added a method in API\ResponseTrait to generate No Content (204) response to an API request that doesn't provide any meaningful response to the client but the client still needs status 204 back.
NOTE: I hope I got the commit signed properly this time.
**Checklist:**

Added No Content response to API\ResponseTrait

---

system/Cache/Handlers/RedisHandler.php

From https://github.com/phpredis/phpredis:
"Note: delete is an alias for del and will be removed in future versions of phpredis."
This PR changes the call to `delete()` to be `del()` instead.
**Checklist:**

Update Redis legacy function

---

system/Autoloader/Autoloader.php
system/Autoloader/FileLocator.php

The Autoloader merges Composer namespace paths directly from Composer's autoloader, which doesn't include a trailing slash. This means files coming from `autoloader->getNamespace()` may or may not have a trailing slash, which sometimes causes `FileLocator->listNamespaceFiles()` to miss files it should otherwise find.
This change ensures that the namespace path coming from autoloader will always have the trailing slash.
**Checklist:**

listNamespaceFiles: Ensure trailing slash 

---

system/Images/Handlers/BaseHandler.php

Current `fit()` isn't working as expected - it does the correct crop location and resize but it is taking a much smaller-than-necessary crop from large images. This iteration starts with the premise that the crop should be the entire width or height of the image, calculates the other axis based on the desired aspect, takes the much larger crop then resizes to the desired output.
Tests are hard for image handlers but I have run this through a handful of scenarios.
**Checklist:**

New logic for Image->fit()

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/GetTest.php

Fixes #2141 where the builder was reset when returning the SQL.
**Checklist:**

Fixing BuilderBase resetting when getting the SQL

---

system/Database/BaseBuilder.php
system/Model.php
tests/system/Database/Live/ModelTest.php

There's a bug, or at least a confuse behaviour, when you use soft-delete and execute $model->delete() method with empty value as parameter (0, NULL, FALSE, or simple no parameter).
When soft-delete is false, CI throw a DatabaseException warning about delete() method cannot execute without where or like condition, but, when soft-delete is true no exception nor warning is thrown because CI internally call update() method.
I modified the code in order to throw DatabaseException when soft-delete is true and $id parameter is empty and either a where condition was set.
In order to maintain consistance between both behaviour (hard and soft delete) I needed to add a getter to QBWhere property so that I be able to eval in Model if there's a condition set.
Additionally, I think that …

Fix prevent soft delete all without conditions set

---

admin/release-appstarter
admin/release-framework

devstarter and appstarter both have very old versions of .gitignore - it isn't getting updated when new deployments are made. This PR adds .gitignore to the list of files copied out during a release.
**Checklist:**

Include .gitignore in starters

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/SelectTest.php
tests/system/Database/Live/GroupTest.php
tests/system/Database/Live/SelectTest.php
user_guide_src/source/database/query_builder.rst

Currently there are no ways to return counted group results (see https://github.com/codeigniter4/CodeIgniter4/issues/2159). This provides the first of the discussed methods, `selectCount()`.
**Checklist:**

Add BaseBuilder SelectCount

---

system/Database/BaseBuilder.php

Unsets the LIMIT clause when running countAllResults() to avoid getting zero count.
Fixes #2152 
**Checklist:**

Bug fix countAllResults with LIMIT

---

app/Common.php
system/bootstrap.php

A commit that will hopefully help with this topic: #2101. This is a re-submit due to lack of GPG signing in the previous PR: https://github.com/codeigniter4/CodeIgniter4/pull/2105
**Checklist:**
**Notes**

Added app/Common.php

---

system/Test/FeatureTestCase.php

FeatureTestCase extended CIDatabaseTestCase, even though there were no data calls.
This prevented testing features if the database tests weren't also being run.

Base FeatureTestCase on CIUnitTestCase

---

system/HTTP/Message.php
tests/system/HTTP/MessageTest.php

Using `setHeader()` with duplicate values of different case currently creates duplicate headers. There's also something wrong with the current `setHeader()` logic (see https://github.com/codeigniter4/CodeIgniter4/issues/2170). This PR reworks the method to be what I think it was intending to do.
**Checklist:**

Setheader dupes

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/WhereTest.php
user_guide_src/source/database/query_builder.rst

Added subqueries via anonymous function in Query Builder for BaseBuilder::where() and BaseBuilder::whereIn() methods
**Checklist:**

Subqueries in BaseBuilder

---

system/Security/Security.php

For CSRF hash regeneration, $this->CSRFHash must be set to NULL when user set 
$this->CSRFRegenerate to TRUE, because in CSRFSetHash() you compare it with NULL, but 
$this->CSRFHash !== NULL after request. I guess you need to create new method in Security class, such as CSRFHashReset() and check my commit.

Fix CSRF hash regeneration

---

system/Files/File.php

I've just encountered my second sizable hosting company that doesn't have the fileinfo extension available. This causes `File->getMimeType()` to fail:
```
CRITICAL - 2019-09-01 21:32:28 --> Call to undefined function CodeIgniter\Files\finfo_open()
```
Given that this is a "standard" setup it probably isn't safe to rely on this function. This PR checks for the function, and failing to find it reverts to the client's reported MIME type.
**Checklist:**

Add fallback for missing finfo_open

---

system/Database/BaseBuilder.php

i.e.:
```
$sub_query[] = $this->type === self::API_TRADING_TRADES ? $this->prefix . 'api_trade_id' : $this->prefix . 'api_id';
$this->select('MAX(' . $subselect[0] . ')', false);
if($cur_id_from === null)
{
$this->groupBy($this->prefix . 'cur_id_1');
}
if($cur_id_to === null)
{
$this->groupBy($this->prefix . 'cur_id_2');
}
if ($type !== null)
{
$this->where($this->prefix . 'type', $type);
}
$sub_query[] = $this->getCompiledSelect(true);
$this->whereIn($sub_query[0],'(' . $sub_query[1]  . ')', false);
```
should produce sth like this:
```
SELECT *
FROM `t_api_trading_trades`
WHERE aht_api_trade_id IN (SELECT MAX(aht_api_trade_id)
FROM `t_api_trading_trades`
WHERE `aht_type` = 'B'
GROUP BY `aht_cur_id_2`)
```
(tested, working as excepted)

whereIn  $value do not have to be an array

---

user_guide_src/source/database/query_builder.rst

Fix sphinx formatting errors in the query builder page of the user guide.

Fix query builder user guide page

---

app/Config/Paths.php

Just a small error of text that appears to be pasted from above.
**Checklist:**

Remove copy-paste extraneous text

---

system/Test/CIDatabaseTestCase.php

If both a test seed file and a directory are passed the Seeder will set the path right to that file, but it incorrectly uses a lower-case directory "seeds" instead of "Seeds". This PR fixes the case.
**Checklist:**

Fix case on "Seeds/" directory

---

app/Config/Constants.php

Currently the `APP_NAMESPACE` and `COMPOSER_PATH` define right out, without checking for `defined()`. This prevents using an alternative bootstrap to load from different locations, e.g. a modular test bootstrapper.
This PR adds checks for existing constants before defining them.
**Checklist:**

Check `defined` for constants

---

system/Database/MigrationRunner.php
user_guide_src/source/dbmgmt/migration.rst

Per: https://github.com/codeigniter4/CodeIgniter4/issues/2147#issuecomment-528278342
Migration rollbacks are currently rolling back batch-by-batch in the correct order, but within the batch migrations are being downgrading in ascending order. This reverses the migrations within a batch so they are downgraded appropriately.
**Checklist:**

Migration rollback reverse

---

user_guide_src/source/dbmgmt/migration.rst

Docs have the wrong names for foreign key methods.
I think I was supposed to use [ci skip] on the commit but trying it here anyways...
**Checklist:**

[ci skip] Fix name of ForeignKeyChecks

---

user_guide_src/source/database/metadata.rst

User Guide was missing any mention of getForeignKeyData, this adds it.
**Checklist:**

Add getForeignKeyData to User Guide

---

system/Common.php

Because `dd()` is calling `Kint::dump` directly, Kint will always display the translated parameter `reset($vars)` as variable name and `dd()`'s source as call location:
```
Called from .../codeigniter4/codeigniter4/system/Common.php:1082 [dd()]
```
This change has `dd()` add itself to Kint's alias list prior to the call so Kint correctly looks back to the originating call. Since the script will always `exit` there's not need to check `Kint::aliases` for duplicates or anything.
**Note**: This is the Kint-approved way to wrap `d()`
**Checklist:**

Notify Kint of dd alias

---

system/Database/MySQLi/Connection.php
system/Database/Postgre/Connection.php
system/Database/SQLite3/Connection.php
tests/system/Database/Live/ForgeTest.php
user_guide_src/source/database/metadata.rst

Currently `getForeignKeys()` only returns information on the related tables. While helpful, this doesn't allow any interactions based on those keys as it lacks the column name. This PR adds the locals and foreign column names to the returned object.
Note that SQLite3 does not have this information available, but does have an additional field `sequence` (also added) which is handy for composite keys. The updated User Guide makes this clear.
**Checklist:**

Foreign key columns

---

system/Database/BaseConnection.php
user_guide_src/source/database/queries.rst

Requesting a getter method for DBPrefix so it doesn't have to be hacked out of `prefixTable()` when all you want is the prefix itself.
**Checklist:**

Add $db->getPrefix()

---

user_guide_src/source/concepts/structure.rst
user_guide_src/source/extending/contributing.rst
user_guide_src/source/general/errors.rst
user_guide_src/source/incoming/routing.rst
user_guide_src/source/libraries/encryption.rst
user_guide_src/source/libraries/time.rst
user_guide_src/source/testing/controllers.rst
user_guide_src/source/testing/debugging.rst
user_guide_src/source/testing/feature.rst
user_guide_src/source/testing/overview.rst
user_guide_src/source/tutorial/news_section.rst
user_guide_src/source/tutorial/static_pages.rst

Documentation Updates
- Fixed all 404 links in the documentation.
- Fixed code sample formatting on tutorial/static_pages
- Fixed bad Exception class in code sample on tutorial/news_section
- Removed duplicated paragraph Message Length on /libraries/sessions
- Fixed example for TimeDifference humanize() method on libraries/time
- Fixed Description of assertHeaderNotEmitted() method testing/overview
- Fixed Code sample of assertSee() method on testing/feature
- Changed text on how to change the environment config on /general/errors

Documentation fixes

---

system/Database/Config.php

Change `new \Config\Database()` to `config('Database')` in `\CodeIgniter\Database\Config::connect()`.
**Checklist:**

change new \Config\Database() to config('Database')

---

system/Common.php
user_guide_src/source/testing/debugging.rst

We advertise `trace()` in the User Guide as a debug tool wrapping `Kint::trace()` but it isn't actually there. This PR adds it to **Common.php**.
**Checklist:**

Add trace()

---

system/Database/BaseConnection.php

Currently if the database `datacache` has a copy of the tables it will return the whole set regardless of `$constrainPrefix`. This change checks for `$constrainPrefix` and filters the returned array accordingly.
**Checklist:**

Filter listTables cache response on constrainPrefix

---

system/Database/Forge.php
system/Test/CIDatabaseTestCase.php

When Forge runs `dropTable()` it will check for and strip the DBPrefix from a table name if found. It does this check via `(! empty($this->db->DBPrefix) ...` but since `DBPrefix` is acquired through **BaseConnection**'s magic `__get` without a corresponding `__isset()` `empty()` returns false even when it isn't empty. Because of the magic getter and the initial property we can be sure `DBPrefix` will always be there so it is fine to test `($this->db->DBPrefix` directly. Might consider adding `__isset()` to **BaseConnection** at some point.
**Checklist:**

Fix empty() bug on DBPrefix

---

system/Database/SQLite3/Connection.php
user_guide_src/source/database/metadata.rst

SQLite will ad-hoc add various tables prefixed "sqlite_" that function similar to MySQL's `information_schema`. See for example these metadata test results (https://travis-ci.org/codeigniter4/CodeIgniter4/jobs/586068130):
```
1) CodeIgniter\Database\Live\MetadataTest::testListTables
585Failed asserting that two arrays are equal.
586--- Expected
587+++ Actual
588@@ @@
589 Array (
590     0 => 'db_migrations'
591-    1 => 'db_user'
592-    2 => 'db_job'
593-    3 => 'db_misc'
594-    4 => 'db_empty'
595-    5 => 'db_secondary'
596+    1 => 'sqlite_sequence'
597+    2 => 'db_user'
598+    3 => 'db_job'
599+    4 => 'db_misc'
600+    5 => 'db_empty'
601+    6 => 'db_secondary'
602 )
```
... where `sqlite_sequence` is being returned as a table. I think these tables should be …

Exclude `sqlite_%` from listTables()

---

system/Database/SQLite3/Connection.php

Properly escape the SQLite `_listTables()` filter, per https://github.com/codeigniter4/CodeIgniter4/pull/2228#discussion_r325263010
**Checklist:**

Add escape to SQLite _listTables()

---

system/Database/MySQLi/Connection.php
tests/system/Database/BaseConnectionTest.php
tests/system/Database/Live/EscapeTest.php

As @michalsn points out, some MySQL commands (e.g. "SHOW ____") don't support custom escape characters supplied via "ESCAPE x". Currently `listTables()` is the only framework function suffering from this limitation, but it causes `listTables()` with `$constrainPrefix` to fail to constrain correctly.
This PR defines a new platform-specific function `escapeLikeStringDirect()` that can be used for those rare instances when both "SHOW" and "LIKE" are retried in the same query. This new function applies the default escape character `\` directly the the "LIKE" string for any wildcards. This also has the MySQLi driver's `_listTables()` function use this new method instead to the generic one designed for "SELECT" statements.
Refs:
* …

MySQLi escapeLikeStringDirect()

---

tests/system/Database/Live/ForgeTest.php
tests/system/Database/Live/MetadataTest.php

Currently there are no tests for the database metadata methods. There are a lot more that should be added but this creates the file and adds tests for `listTables()` that exhibits the error described in https://github.com/codeigniter4/CodeIgniter4/issues/2210.
Someone who knows what's up with the weird `!` escape character business take a look?
**Checklist:**

Add listTable() tests

---

system/CLI/BaseCommand.php
system/Database/BaseConnection.php
system/Encryption/Encryption.php
system/Encryption/Handlers/BaseHandler.php
system/I18n/Time.php
system/I18n/TimeDifference.php
system/Model.php
system/Session/Session.php
tests/system/Commands/CommandClassTest.php
tests/system/Database/BaseConnectionTest.php
tests/system/Database/Live/ModelTest.php
tests/system/Encryption/EncryptionTest.php
tests/system/I18n/TimeDifferenceTest.php
tests/system/I18n/TimeTest.php
tests/system/Session/SessionTest.php

See https://github.com/codeigniter4/CodeIgniter4/issues/2219
This PR adds `isset()` methods to the following classes, modeled after each class's `__get()` method:
* CodeIgniter4/system/Database/BaseConnection.php
* CodeIgniter4/system/Model.php
* CodeIgniter4/system/Session/Session.php
* CodeIgniter4/system/I18n/Time.php
* CodeIgniter4/system/CLI/BaseCommand.php
* CodeIgniter4/system/I18n/TimeDifference.php
* CodeIgniter4/system/Encryption/Encryption.php
* CodeIgniter4/system/Encryption/Handlers/BaseHandler.php
**Checklist:**

Add magic __isset to classes with __get

---

app/Config/Boot/development.php
app/Config/Boot/production.php
app/Config/Boot/testing.php

init_set expects second parameter to be string.
This is a sample PR, John-Betong, addressing #2234, #2235 and #2236.
One PR, as these are related.
Note: the branch name is misleading, as I thought all your suggestions were for strict typing.

Fix ini_set parameter type

---

system/Images/Handlers/BaseHandler.php

Prevent Images\Handlers\BaseHandler from blowing up on GIF.

EXIF not supported for GIF

---

system/Pager/PagerRenderer.php
tests/system/HTTP/URITest.php
tests/system/Helpers/URLHelperTest.php
tests/system/Pager/PagerTest.php
user_guide_src/source/helpers/url_helper.rst

Additional tests to explore URI and url_helper; investigating #2016 
Corrected url_helper writeup while at it.

Add URI & url_helper tests

---

system/Database/BaseBuilder.php
system/Database/MySQLi/Builder.php

When there are JOINs and more than one table exists, the FROM clause must be enclosed in parentheses, otherwise an error occurs if a JOIN does not refer to the last table.
**Checklist:**

Fix _fromTables()

---

system/Common.php

lang() indeed returns a string or array of them.
Fixes #2075

Fix lang() signature

---

user_guide_src/source/installation/troubleshooting.rst

Explain the whoops page

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/GetTest.php
user_guide_src/source/database/query_builder.rst

Fixes #2143 - `getWhere()` bug with offset.
**Checklist:**

Fixes BaseBuilder getWhere() bug

---

system/View/Parser.php
tests/system/View/ParserTest.php
tests/system/View/Views/Simpler.html
user_guide_src/source/outgoing/view_parser.rst

- Fix bug from #2086. reference `CodeIgniter/View/View::render ` 
**Checklist:**

fix. Parser allow other extension

---

system/Security/Security.php

Important change to handle JSON POSTS in CSRF.
I wanted to send JSONS instead on normal POST but CSRF filter did not allow me to to this even if token existed in my JSON.
```
{"usr_id":1322189,"ctn":"3a111012714a58b53260ede89380d412","token":"ctn","parent":17031,"mode":{"main":"test","additional":"exam"},"time":{"start":1568992305,"end":1568993826},"result":{"2103":["T"]}}
```
my token name is: ctn
I think this is important, without this we are limiting a lot.

Handle JSON POSTs in CSRF

---

system/Validation/Validation.php

Modify Validation::getErrors so it doesn't create a session if one isn't in use already

Validation session use only if exists

---

system/RESTful/ResourcePresenter.php
tests/system/RESTful/ResourcePresenterTest.php

When we use the `setModel()` function for the first time everything is fine but as we allow you to change the model you have to reset the property that is not updated otherwise you risk having a different name of the created model as we can see in the tests created.
**Checklist:**

fix ResourcePresenter::setModel()

---

system/Database/BaseBuilder.php
system/Database/Postgre/Builder.php
tests/system/Database/Builder/CountTest.php
tests/system/Database/Builder/DeleteTest.php
tests/system/Database/Builder/EmptyTest.php
tests/system/Database/Builder/GetTest.php
tests/system/Database/Builder/InsertTest.php
tests/system/Database/Builder/ReplaceTest.php
tests/system/Database/Builder/TruncateTest.php
tests/system/Database/Builder/UpdateTest.php
user_guide_src/source/database/query_builder.rst

This PR introduces a new `testMode` variable that is meant to be used in the testing environment. It replaces all occurrences of `$returnSQL`, `$test` and `$testing` - reducing the number of parameters in a couple of methods.
**Important**
This should be considered as a BC change since some parameters from methods are removed. Those parameters weren't well documented but there is still a chance that somebody was using them.
**Checklist:**

testMode() method for BaseBuilder

---

system/Database/BaseBuilder.php

Since we have now `groupStart()` and `havingGroupStart()` it's a good moment to refactor the code responsible for those methods a bit.
In this PR I want to introduce two new protected methods: `groupStartPrepare()` and `groupEndPrepare()`. These will take over the responsibility for handling all other `group*` methods.
**Checklist:**

groupStart() refactorization

---

system/Database/BaseBuilder.php

*FIX Batch Update WHERE condition behaves inconsistently due to WHERE being cleared after the first batch. Save and restore WHERE conditions for each batch.
This fixes an issued raised 8 years ago here: https://stackoverflow.com/a/58043102/6211703
**Checklist:**

QUICKFIX Batch Update Where Reset

---

user_guide_src/source/incoming/message.rst

This PR fixes some method names in the user guide for Message class.
**Checklist:**

Fix user guide for Message class

---

app/Config/App.php
system/Security/Security.php
tests/_support/Config/MockAppConfig.php

According to your comments, I have to agree: it could be useful and should be characterized by better performance than parsing php://input jsons everytime when $_POST token is not set.
@michalsn @jim-parry @lonnieezell 
Order:
1. $_POST
2. HTTP HEADER
3. php://input - trying to parse posted JSON  (last because of performance)

Handle X-CSRF-TOKEN - CSRF

---

system/Debug/Exceptions.php

Code is not showing with a line number.
Currently produced output when an error occurs:
```
/span>  */
/span> 
/span> class FrameworkException extends \RuntimeException implements ExceptionInterface
/span> {
/span> 
/span>     public static function forInvalidFile(string $path)
/span>     {
/span>         return new static(lang('Core.invalidFile', [$path]));
/span>     }
/span> 
/span>     public static function forCopyError(string $path)
/span>     {
/span>         return new static(lang('Core.copyError', [$path]));
/span>     }
/span> 
```
**Checklist:**

Fix line numbering in Debug/Exceptions class

---

system/HTTP/CURLRequest.php
tests/system/HTTP/CURLRequestTest.php

When we don't specify any header for the cURL request, headers will be populated from $_SERVER.
This will cause an error when calling the URL outside of our server.
This PR check if headers for cURL request have been defined and if not - it populates the headers as usual but removes `Host` header.
Ref: #2250
**Checklist:**

Fix error with Host header for CURLRequest class

---

system/Common.php
system/Security/Security.php
tests/system/CommonFunctionsTest.php
tests/system/Security/SecurityTest.php
user_guide_src/source/general/common_functions.rst
user_guide_src/source/libraries/security.rst

CSRF variable is not being removed after verification. We unset POST parameter but we should also update Request object.
The same thing with JSON data - we forgot to clean it up at all.
These tests are failing right now but they will not - after merging #2272.
**Checklist:**

Bug in CSRF parameter cleanup

---

user_guide_src/source/general/modules.rst

We must use $psr4 variable into __construct() method because public $psr4 will be overwrite after parent::__construct() method. That's why we can't use current documentation.
**Checklist:**

Fix Code Modules documentation for psr4 namespace configuration

---

system/Validation/Validation.php

When performing redirect `_ci validation_errors` session variable is not passed correctly.
Sadly this one is hard to test since we check `! is_cli()` a couple of lines before.
**Checklist:**

Fix getErrors() for validation with redirect

---

system/Helpers/inflector_helper.php
tests/system/Helpers/InflectorHelperTest.php
user_guide_src/source/helpers/inflector_helper.rst

This adds another inflector function to make easy counted words (e.g. from database results):
```
$users = $userModel->findAll();
echo counted(count($users), 'users'); // "5 users" or "1 user"
```
**Checklist:**

Add counted() to Inflector Helper

---

system/Session/Handlers/DatabaseHandler.php
system/Session/Handlers/FileHandler.php
system/Session/Handlers/MemcachedHandler.php
system/Session/Handlers/RedisHandler.php

There is a problem when doing session_regenerate(), because when we call read() it always affect $this->sessionID = $sessionID which means that in write() function you can't detect a $sessionID regenerate, because when we get there the $this->sessionID is always equal to $sessionID.
This happen because when session_regenerate() is call, this function executes internally and in the following order:
- write() (with the initial session;
- close();
- open();
- read() (already with the new session) .
**Checklist:**

fix issue on session_regenerate.

---

system/Debug/Toolbar/Collectors/Routes.php

Routes collector for toolbar should not die when a method name is calculated through _remap. 
I'm not in love with the way it outputs to the toolbar currently, but not sure of a better way to handle this. 
Fixes #2277

[ci skip] Routes collector for toolbar should not die when a method name is calculated through _remap

---

system/Database/MySQLi/Builder.php

When there are JOINs and more than one table exists, the FROM clause must be enclosed in parentheses, otherwise an error occurs if a JOIN does not refer to the last table.
**Checklist:**

Fix MySql _fromTables()

---

system/Database/Migration.php
system/Database/MigrationRunner.php

This PR fixes issue #2087,  as described by @lonnieezell, how this should work:
* A migration that has a group specified will always use that group when doing it's migrations
* If no group is specified it uses the default group
* If a group is specified on the cli, then it acts like a filter and only migrations that use that db group are ran. Only applies to up since rollbacks simply rollback the last set of migrations that were ran, no matter how they were filtered.
**Checklist:**

Use DBGroup variable from migration class if defined

---

system/Router/Router.php

When controller and method are both empty and there is no explicit default route (i.e. `$routes->get('/', ...`) then **Router** will call `validateRequest()` with two blank entries in `$segments`, which in turn calls `setDirectory('')` twice resulting in a directory of `//`. This causes `autoroute()` to fail to locate existing controllers.
This PR has `setDirectory()` ignore empty requests, since `$this->directory` of `null` is already equivalent to `/`.
Fix for https://github.com/codeigniter4/CodeIgniter4/issues/2301
**Checklist:**

Bugfix extra autoroute slashes

---

system/Database/BaseBuilder.php

Changed `$this->delete` call second parameter from empty string to `null`.
In `delete` method declaration second param is type of integer or null.
IMHO it is better not to rely on type juggling where it is not necessary.
**Checklist:**

BaseBuilder variable type fix

---

system/HTTP/CURLRequest.php
user_guide_src/source/libraries/curlrequest.rst

This PR replaces the use of `php://output` with `php://stderr`.
Ref: #2202
Tested on machines/environments:
* Win7  - spark with php 7.3.9 and xampp (apache 2.4.41 + php 7.3.9)
* MacOS - spark with php 7.3.9
* Ubuntu - nginx 1.13.3 + php 7.2.11
**Checklist:**

Fix curl debug bug

---

system/Debug/Toolbar.php

Added type hinting for $startTIme, and (float) casting for $row values.
This should fix #2034 as reported, although it doesn't address the potential deeper issue of a timer not started (per the discussion).

Enhance Toolbar::renderTimeline

---

system/Language/en/Encryption.php
system/Language/en/RESTful.php
system/Language/en/Session.php

`lang()` requires single quotes in order to parse bracketed indexes. Mostly this is all correct but there are a few files still using double quotes. This PR converts these.
**Checklist:**

Convert all language returns to single quote

---

user_guide_src/source/incoming/restful.rst

I find myself frequently flipping back and forth to the routes expansion for ResourceController and ResourcePresenter. Presenter is currently misaligned, making it hard to read, and the two code sections are not in the same order.
This PR aligns the code and reorganizes both sections to be in the same general order (CRUD-ish). Additionally I added a comparison table to make it easier to view the routes, methods, and functions all at once.
*Note: The reorg and table are two different commits, in case anyone hates my table*
**Checklist:**

[ci skip] Update RESTful User Guide

---

system/View/View.php

**View/View** uses `CIDEBUG` directly to determine whether to inject toolbar collector data, despite already having `$this->debug` which defaults to `CIDEBUG`. Using the constant directly makes it near impossible to exclude collector injections during testing.
This PR has `render()` check `$this->debug` instead, which should have the same behavior in all current cases but will allow direct overriding of the injection for test cases.
**Checklist:**

Renderer Toolbar Debug Toggle

---

user_guide_src/source/incoming/restful.rst

A few formatting improvements for the RESTful table.
**Checklist:**

[ci skip] Guide: RESTful table formatting

---

system/Autoloader/FileLocator.php

When grabbing the list of namespaces it would remove DIRECTORY_SEPARATOR and then add it back, just to make sure the end was clean. Unfortunately, that wasn't working on Windows.

Correct cleaning of namespaces in FileLocater for better Windows compatibility. See #2203

---

user_guide_src/source/dbmgmt/migration.rst
user_guide_src/source/outgoing/table.rst

Fixed form of past participles in a couple of places

[ci skip] Guide: Minor grammar corrections

---

system/Model.php
user_guide_src/source/models/model.rst

Currently model events `afterInsert` and `afterUpdate` pass on the original data they were called with. This severely limits what event triggers can do, not knowing the data that actually reached the database. This PR triggers events with the inserted/updated data instead. Additionally, `afterInsert` now passes the ID of the newly-inserted row (similar to other events), or 0 on failure.
**Checklist:**

Change after methods to use actual data

---

system/Session/Session.php
tests/system/Session/SessionTest.php

Issue #2334
The code in question is from Session.php starting at line #499 
````
if (! empty($key) && $value = dot_array_search($key, $_SESSION))
{
return $value;
}
````
When `dot_array_search()` returns a value of 0 (zero) then `$value` is evaluated as `false` so `$value` is not returned eventhough it should be.
Proposed fix: change the conditional to
if (! empty($key) && ! is_null($value = dot_array_search($key, $_SESSION)))
A unit test added to confirm this works.

Fix Session::get('key') returns null when value is (int) 0

---

system/Validation/Validation.php

No need to use session helper if both `$_SESSION`  and `$_SESSION['_ci_validation_errors']` are proven set.  Using `isset($var1,  $var2) ` is easier on eyes than a compound conditional - part of which is an assignment.
Change:
````
if (isset($_SESSION) && $errors  =  session('_ci_validation_errors'))
````
To:
````
if (isset($_SESSION, $_SESSION['_ci_validation_errors']))
````

Simplify Validation::getErrors()

---

system/HTTP/Files/UploadedFile.php

fix store() default value creation'index. html'file path error,like '20190810index.html'
**Checklist:**
**Notes**

WIP fix store() default value bug

---

user_guide_src/source/concepts/structure.rst
user_guide_src/source/general/errors.rst
user_guide_src/source/general/helpers.rst
user_guide_src/source/general/modules.rst
user_guide_src/source/installation/installing_composer.rst
user_guide_src/source/installation/installing_git.rst
user_guide_src/source/installation/installing_manual.rst
user_guide_src/source/installation/running.rst
user_guide_src/source/installation/troubleshooting.rst
user_guide_src/source/libraries/pagination.rst
user_guide_src/source/libraries/throttler.rst
user_guide_src/source/libraries/validation.rst
user_guide_src/source/models/model.rst
user_guide_src/source/outgoing/localization.rst
user_guide_src/source/outgoing/views.rst
user_guide_src/source/testing/benchmark.rst
user_guide_src/source/testing/database.rst
user_guide_src/source/testing/overview.rst
user_guide_src/source/tutorial/create_news_items.rst
user_guide_src/source/tutorial/news_section.rst

setup is a noun
set up is a verb
Thought maybe we should set up the User's Guide to succeed.

Setup vs Set Up

---

user_guide_src/source/cli/cli_commands.rst
user_guide_src/source/database/query_builder.rst
user_guide_src/source/database/results.rst
user_guide_src/source/dbmgmt/forge.rst
user_guide_src/source/dbmgmt/migration.rst
user_guide_src/source/models/entities.rst

Updated class names like [this](https://codeigniter4.github.io/userguide/cli/cli_commands.html#basecommand) (missing the backslashes).
**Checklist:**

User guide minor fixes. Fix class names and code area.

---

tests/system/Log/FileHandlerTest.php

All test methods would fail when this class was run by itself.
setUp() method needed call the parent::setUp()

Fix FilerHandlerTest.php wierdness

---

user_guide_src/source/changelogs/next.rst
user_guide_src/source/incoming/routing.rst

Changelog updated; ready to start rc.3 build

Prep changelog for RC.3 [ci skip]

---

user_guide_src/source/libraries/time.rst

Fix issue #2351 
Update user guide
**Checklist:**

Fix method name to 'toDateString()' in Date and Times user guide

---

system/Config/Services.php

Corrected 'igration runner' to read 'Migration runner'.
Typographical error in comments only, no functional code changes.
**Checklist:**
**Notes**

Fix typo in comments of Services.php

---

app/Config/Logger.php
system/Log/Handlers/FileHandler.php
tests/system/Log/FileHandlerTest.php

Correct the Config/Logger
- remove second path setting
- change default extension to 'log'
- improve PHPdocs
Closes #2286

Fix Logger config

---

system/Model.php

I messed up on https://github.com/codeigniter4/CodeIgniter4/pull/2332 and used `$data` for the after trigger not remembering that the before triggers return a nested version of the data.
This PR fixes the issue by passing the `data` *property* instead of array, and renames all uses of event-related data to `$eventData` to differentiate it from the actual `$data`/`$row`.
**Checklist:**

Bugfix Model after event data

---

system/Email/Email.php

The practice of logging a "Some Class Initialized" message is a remnant of earlier versions of CI. 
It's not being done in V4.

Remove log_message from Email::__construct

---

app/Config/Email.php

A line in .env such as 
email.SMTPPort = 587
Would not be incorporated into the Email configuration
Caused by Config\Email not extending  CodeIgniter\Config\BaseConfig

Email config doesn't incorporate .env items

---

system/Log/Handlers/FileHandler.php

The recent Logger change to default to `.log` added a null check for `config->fileExtension`, but since this is defined in **app/Config/Logger.php** it won't normally be null, just empty.
This PR checks for an empty value (could also use `?:` but this covers cases where it isn't set at all).
**Checklist:**

Replace null log file extension check

---

system/Database/MigrationRunner.php
tests/system/Database/Migrations/MigrationRunnerTest.php

See #2386 - this PR changes MigrationRunner to use only digits when ordering migrations.
**Checklist:**

Use only digits for migrations order

---

system/Database/Seeder.php

Seeds can call other seeds (https://codeigniter4.github.io/userguide/dbmgmt/seeds.html#nesting-seeders) but since seeds are extensions of the seeder themselves the new seeds will start with their own `silent` value. This means any tests using nesting seeders will start displaying seed results for every test call, very undesirable. 
This PR has the parent seeder pass its `silent` value to the child before running it.
**Checklist:**

Confer silent status to nested seeders

---

system/CLI/CommandRunner.php
system/Controller.php
system/Debug/Toolbar/Collectors/Events.php
system/Debug/Toolbar/Collectors/Logs.php
system/Debug/Toolbar/Collectors/Routes.php
system/Debug/Toolbar/Collectors/Timers.php
system/Debug/Toolbar/Collectors/Views.php
system/Encryption/Encryption.php
system/HTTP/IncomingRequest.php
system/Language/Language.php
system/Log/Handlers/ChromeLoggerHandler.php

Fixes #2376
The following statement is used by multiple "core" classes
use CodeIgniter\Config\Services;
This results in `App\Config\Services` being bypassed which prevents `Service` overrides from being recognized.
All namespace use statements for `Services` in the core classes changed to ` use Config\Services;` so the overrides can be accomplished.
Note: There are a lot of test files that explicitly use `CodeIgniter\Config\Services` that were not changed in the PR. They probably don't need to be and/or should not be changed, but I wanted to point that out.

Fix: Use of CodeIgniter\Config\Services prevents Service overriding

---

app/Config/App.php
system/HTTP/IncomingRequest.php
system/Helpers/url_helper.php
tests/system/Helpers/URLHelperTest.php

- base_url fixed to ensure a trailing slash when it needs it to property resolve relative URIs
- current_url fixed to merge any folders in the request URI's path. 
Fixes #2365 
Fixes #2347

Fix url helper functions to work when site hosted in subfolders. 

---

system/CodeIgniter.php

Fixes #2391 
``CodeIgniter::display404errors`` calls ``CodeIgniter::gatherOutput()`` where a TypeError exception occurs when ``$this->cachePage($cacheConfig);`` is called and ``$cacheConfig`` === null.
Fixed by instantiating a Cache config object in ``display404errors()`` and passing it to ``gatherOutput()``

Fix issue #2391 CodeIgniter::display404errors()

---

user_guide_src/source/incoming/controllers.rst

Primarily adds details to the "Hello World" demo. In particular, it addresses file naming and uses a ``Helloworld`` class instead of ``Blog``.
Revise "Defining a Default Controller" to include commenting out ``$routes->get('/', 'Home::index');`` so the demo will work.
Some general word-crafting too.

Revise Controllers Documentation  [ci skip]

---

system/Entity.php

Because `empty()` is essentially the concise equivalent to `!isset($var) || $var == false` using both `isset() && !empty()` in a conditional serves no purpose.
The `isset()` check has been removed.
(OK, I know this is trivial. It's just my OCD kicking in.)

Remove redundant check in conditionals

---

system/HTTP/Files/FileCollection.php

Because the argument `$index` has a type declaration of 'array' there is no point in using `is_array($index)` in the conditional. If `$index` is not an array an exception will have been thrown before we get to the `if()` statement.

Remove pointless check from conditional

---

system/Router/RouteCollection.php

Using `isset($someVar) && ! empty($someVar)` in a conditional is redundant.
Removed `isset()` from the `if` statement.

Removed pointless isset() check

---

system/CodeIgniter.php

When storing previous url we should use current_url() to ensure we ge…t baseURL paths and any query vars. 
Fixes #2378

Ensure previous_url() gets accurate URI.

---

system/Debug/Toolbar/Views/toolbarloader.js.php

The toolbar does not display properly. After testing, a file was redirected incorrectly and an attempt was made to fix the problem. (Translate from Google)

fix. toolbar file 301

---

user_guide_src/source/libraries/encryption.rst

Started by adding detail to passing a $config to ``Services``. Wound up polishing it all.

Revise Encryption Service Documentation [ci skip]

---

system/Database/MySQLi/Connection.php

SQLite has a handy property on field data `nullable`. This PR adds the equivalent to MySQLi.
**Checklist:**

Add 'nullable' to MySQL field data

---

system/Helpers/url_helper.php

Presently `current_url()` returns a reference to the shared Request service's URI property, making it possible to use the returned object to modify the global Request object to undesirable effect.
This PR makes `current_url()` return a cloned version of the URI object so it can be manipulated freely. One word - I added one word for a bug that took over an hour to track down. ONE. WORD.
**Checklist:**

Change current_url() to use cloned URI

---

system/HTTP/Response.php

PHP's own server adds in a Date header to the response Automatically. 
It's possible that other servers might do so also, but it shouldn't really hurt anything if they do.

Don't show duplicate Date headers when running under PHPs server. Fixes #2375

---

app/Config/Email.php

Needed so that a ``recipient`` can be defined in .env and will be picked up in BaseConfig.
Most useful for automated testing situations.

Add $recipients property to Config\Email

---

system/Language/en/Validation.php
system/Validation/FormatRules.php
tests/system/Validation/FormatRulesTest.php
user_guide_src/source/libraries/validation.rst

Defines a validation rule for hexadecimal digits similar to alpha_numeric, etc.
**Checklist:**

Add hex validation rule, test, Guide

---

system/Router/RouteCollection.php
tests/system/Router/RouteCollectionTest.php

fix #2423 
in userguide
**Checklist:**

fix: Router setDefaultNameSpace can't worker

---

system/View/Parser.php
tests/system/View/ParserTest.php

Fix bug #2318 
Replace **str_getcsv()** function by regexp.
**Checklist:**

#2318 - fix parse params of plugin

---

system/Entity.php

Fix issue #2430
The array and string offset access syntax using curly braces has been deprecated in PHP 7.4
**Checklist:**

Fix curly brace deprecation in php 7.4

---

system/Model.php
tests/_support/Models/ValidModel.php
tests/system/Database/Live/ModelTest.php

Inserting through a model should respect all validation rules. Fixes #2384

---

system/Config/Services.php
system/Email/Email.php

I would like this considered because the `Email` class creates a `Logger` instance when it's instantiated. I'm trying to devise an `EmailHandler` for the `Logger` class which would require an instance of the `Email` class. I sure you can see the endless loop that is formed.
It doesn't seem like removing the `LoggerAwareTrait` would affect `Email` much. It only makes one call to the resulting `logger` object.  Switching that call to using the common function `log_message` seems a good substitute for `$this->logger->log...`
If this PR is merged I've got a working `EmailHandler` ready to go.

Remove LoggerAwareTrait from Email class

---

system/HTTP/Response.php
tests/system/Test/FeatureResponseTest.php

JSON was incorrectly formatted in case we providing a string (with no " "  around) to setJSON() method.
Of course, this is not the final solution but I am pointing out the place where the issue occurs. 
```
$this->response
->setJSON('my test string without closing " sings around')
->send();
```

Inccorectly formated JSON response , if body is string

---

user_guide_src/source/database/query_builder.rst

In the User Guide there was an error in the code example related to the selectCount() method, where the method called was selectSum().
**Checklist:**

User Guide: Query Builder selectCount - error correction in example

---

system/Database/Postgre/Connection.php

`$insertId = $model->insert()`
always give
`$insertId = 0`
on my system when
`pg_version($connID)['server'] = '10.10 (Ubuntu 10.10-0ubuntu0.18.04.1)'`
to get the correct server version, I explode the $v['server'] by space then get the first index of array.

quick fix postgresql insert id

---

system/Validation/FileRules.php

max_size, max_dim, is_image, ext_in, mime_in should be checked only if file is uploaded, in other case... rules require file to be available - it is not necessary as long as we have `uploaded` rule.

WIP Checking file rules for existing files

---

user_guide_src/source/outgoing/localization.rst

Corrected a typo as described in #2457.
**Checklist:**
- **None of the above, it's just a typo**

Replace `composer install` by `composer require`

---

system/Database/MigrationRunner.php

id column is too long.
https://dev.mysql.com/doc/refman/5.6/en/integer-types.html
**Checklist:**
**Notes**

 Fix impossible length for migration table id.

---

system/Session/Session.php

newest version.
CRITICAL - 2019-12-10 19:17:06 --> Argument 2 passed to dot_array_search() must be of the type array, null given, called in /home/zdamy/site/system/Session/Session.php on line 500
#0 /home/zdamy/site/system/Session/Session.php(500): dot_array_search('ausItem', NULL)
#1 /home/zdamy/site/system/Common.php(347): CodeIgniter\Session\Session->get('ausItem')
#2 /home/zdamy/site/app/Models/AdminUserModel.php(87): session('ausItem')
BTW/ I am not sure if that method should not look like:
```
public function get(string $key = null)
{
if (! empty($key))
{
if(! is_null($value = dot_array_search($key, $_SESSION??[])))
{
return $value;
}
return null;
}
elseif (empty($_SESSION))
{
return [];
}
$userdata = [];
$_exclude = array_merge(
['__ci_vars'], $this->getFlashKeys(), …
```

CRITICAL when $_SESSION is null / Argument 2 passed to dot_array_search() must be []

---

system/CodeIgniter.php
system/Router/RouteCollection.php
system/Router/Router.php
tests/system/Router/RouteCollectionTest.php

fix #2479.
redirect routes is array.

Fix #2479. Priority Redirection.

---

system/Config/Services.php
user_guide_src/source/extending/core_classes.rst

URI Core System extending
Services::request function changed.
static::uri() was used instead of the new URI() library.
The reason is;
If we want to extend the 'URI' library, we need to extend the 'request' service.
**Checklist:**

Services request add URI Core System extend support

---

user_guide_src/source/cli/cli.rst

There are a typo in the user guide for CI4 reported by the user snjlpro.
https://forum.codeigniter.com/thread-75205.html
**Checklist:**

Typo in user guide "Running via the Command Line"

---

user_guide_src/source/outgoing/view_parser.rst

Updated the View Parser docs to show the correct plugins for current_url and previous_url.

Update current_url and previous_url in the docs for View Parser. Fixes #2460

---

system/Debug/Toolbar/Collectors/Events.php
user_guide_src/source/testing/debugging.rst

fix #2464. `Services::renderer` parameter passing error.

fix. Toolbar init view Error

---

system/Debug/Toolbar.php

- There is an issue with Debugbar-Time not being set correctly XHR response when integer value is set. This fixes the toolbar to pick up changes on Ajax request
- Debug toolbar scripts should be rendered immediately the beginning of <head> in order to pick up Ajax requests which happens on document load.
**Checklist:**

Debug Toolbar - Fix Debugbar-Time header, Render in <head>

---

system/View/Parser.php
tests/system/View/ParserFilterTest.php

Fixes using filters on properties in arrays
Problem is related to the use of | character in filters as | character is handled as OR in regex. This makes replace singe get multiple matches which in the end leads to multiplied data by number of | characters.
Additionally I have added test case testParsePairWithAbs in ParserFilterTest. Initially I was thinking to modify the existing tests to check for nested array elements as well. But this will require changing almost all the test methods. So I've added the new test method based on testAbs() which checks that abs filter works in various nested array properties
I've noticed some style issue. CodeSniffer replaced
```
if (count($keyVal) == 2)
```
to
```
if (count($keyVal) === 2)
```
So I also included this change in the commit …

View Parser - Fix ParsePair() with filter

---

system/View/View.php

Sections array is left populated after generating output. This creates issues when the same shared View rendered instance is called for the second time.
Fixes #2491
**Checklist:**

View Renderer - Reset sections after generating the ouput

---

system/Database/BaseConnection.php

Make the method allowed to return null value so that Debug Toolbar does not crash if there were no queries executed on connection.
Ref #2158
**Checklist:**

BaseConnection - Nullable return type in getConnectStart()

---

app/Config/Database.php
system/HTTP/RedirectResponse.php
system/HTTP/Response.php
tests/system/HTTP/RedirectResponseTest.php
tests/system/HTTP/ResponseTest.php
tests/system/Helpers/FormHelperTest.php
tests/system/Helpers/URLHelperTest.php

Redo of https://github.com/codeigniter4/CodeIgniter4/pull/2196

Use site_url for RedirectResponse. Fixes #2119

---

system/HTTP/URI.php

Bug:
redirect()->to('/?param') returns url without param
If param has not value, it removes
/?param=1 => /?param=1
/?param => /
In php if you open page with ?param in $_GET array you will see this:
array (
[param] => '',
)

Fix splitQueryPart()

---

system/HTTP/Response.php
tests/system/HTTP/ContentSecurityPolicyTest.php

If CSP is disabled property $CSP in HTTP/Response is not initialized.
If we try to access the CSP methods on the request object anywhere in code with CSP disabled it will crash the framework with "Call to a member function …. on null "
In order to avoid this CSP object can be initiated regardless of CSP config.
I’m aware that this is not the most efficient way to bypass the issue but some mechanism for disabling CSP should exist without having to do modifications everywhere in code.
Maybe better idea will be to create mock class to be loaded instead which will respond with catchall  magic methods like __call __set __get ….. But I don’t know if it is worth doing it as it will require adding additional class in framework.
Fixes #2456 
**Checklist:**

Proposal: HTTP Response - Fix crash on CSP methods CSP is disabled

---

system/View/View.php

This reverts commit 8c7d874136d86a9d989e8f3574fd5dd44d08666e.
Resetting the sections is causing views nested in layout sections not to return their output. My mistake for merging this without testing, also probably shows that we need some more tests in this area. Reverting for now and I will reopen the related issue.
**Checklist:**

Revert Renderer section reset

---

system/Helpers/html_helper.php

This is correct way to fix #2473. There was already a PR #2488 but it's not proper solution as it does not cover all possible type
**Checklist:**

HTML Helper - Fix attribute type for lists

---

system/View/View.php
tests/system/View/ViewTest.php

Another take on #2491. This is done in proper way with unit test added first then working on fixing the issue.
The View class does not reset this->sections after completing the rendering. If multiple views are rendered using the same section name those sections are concatenated and displayed multiple times.
The first idea was to reset section in the render method which was not appropriate as this method works if there is only one section but fails to render other section when multiple sections are used. This is because render method is recessively called to render section so rendering the first section will cause other sections not to be rendered at all. 
A different approach is used here. Instead of reseting the section array completely each section is unset separately …

Layout Renderer Fix

---

user_guide_src/source/installation/upgrade_4xx.rst

According to issue #2521 , this commit adds information about replacing Hooks with Events in the 'Upgrading from 3.x to 4.x' section of the official documentation.
**Checklist:**

Adding Events information in the 'Upgrading from 3.x to 4.x' section

---

user_guide_src/source/concepts/http.rst
user_guide_src/source/general/ajax.rst
user_guide_src/source/incoming/incomingrequest.rst

After the conversations on issue #2454 , I created a page in the documentation, within the "General Topics" section to explain the issue of using `isAJAX()`, giving examples of how to force the `X-Requested-With` header to be sent both with the Fetch API as well as with jQuery, VueJS and React, thus facilitating the understanding and use of the resource by CI4 users.
**Checklist:**

Page in the official documentation on ajax requests with iSAJAX() fixes #2454

---

system/Email/Email.php

The Email class was ported from CI3 and still contains a legacy constant, which will cause errors in CI4. This PR replaces the constant with its intended definition.
**Checklist:**

Replace legacy CI3 constant. Fixes #2512

---

system/Database/MigrationRunner.php

`MigrationRunner::regress()` wipes the current namespace so `findMigrations()` will load ALL migration files. This has the unintended side effect of causing subsequent runs to lack an assumed preset namespace.
This PR stashes the namespace and restores it post-regression.
**Checklist:**

Restore namespace after regress. Fixes #2474

---

system/HTTP/Message.php

There is a discrepancy between the inline docs and actual use, such that `Message::$body` can contain non-string values (e.g. arrays). This PR changes the comment to "mixed".
**Checklist:**

Remove incorrect inline doc type

---

system/Database/BaseBuilder.php
system/Database/BaseConnection.php
tests/system/Database/Builder/PrefixTest.php

Fix issue #2532 
Encountered more errors to fix this issue.
Code is not optimized, but couldn't find any better solution. Any help will be much appreciated
**Checklist:**
- [x ] Securely signed commits
- [ x] Unit testing, with >80% coverage

Fix multi-column WHERE not prefixed with DBPrefix

---

user_guide_src/source/libraries/validation.rst

Fixes issue #2535:
Documentation / Library Reference / Validation missed the part about reset() method and running multiple validations after one another.
Added description and emphasized significance of reset() in section Working With Validation.
**Checklist:**
- [x ] Securely signed commits

explanation of reset() method in section Working With Validation fixes #2535

---

system/Commands/Server/Serve.php

When I create the server with the command sss, if my port 8080 is already in use, it will fail.
I want to add retries to use a different port if the command fails
```
CodeIgniter development server started on http://localhost:8080
Press Control-C to stop.
[Thu Feb 13 09:27:20 2020] Failed to listen on localhost:8080 (reason: Address already in use)
CodeIgniter development server started on http://localhost:8081
Press Control-C to stop.
```
**Checklist:**

Add retry creation server when the port is used

---

system/Database/MySQLi/Connection.php

I found this inconsistency in MySQLi connection class. It reference `$this->db->debug`. 
**Checklist:**

MySQLi: Incorrect DBDebug flag used for connection charset

---

user_guide_src/source/general/index.rst

Because it wasn't on index the new "ajax" page wasn't included in the build.

Fix - Add ajax to docs "General " page [ci skip]

---

system/Language/en/Validation.php
system/Validation/FormatRules.php
tests/system/Validation/FormatRulesTest.php
user_guide_src/source/helpers/text_helper.rst
user_guide_src/source/libraries/validation.rst

As discussed in issue #2549   
Fails if the field contains anything characters other than alphanumeric, space and this set of punctuation   ~ ! # $ % & * - _ + = | : .  (that last, the period, is in the set and not just the end of the sentence.)
Other Things:
- Removed ``//---------------`` from between functions as the docblocks visually set them apart just fine.
- Also fixed spelling of alphanumeric. It is not a hyphenated compound word. Affected several files.
- Added rule description to docs.
- Created unit tests for ``alpha_numeric_punct``rule

Added rule "alpha_numeric_punct"

---

app/Config/Events.php

To clean up the buffer notice in "testing" environment which previously shows:
```bash
There were 3 risky tests:
1) CodeIgniter\CodeIgniterTest::testRunClosureRoute
Test code or tested code did not (only) close its own output buffers
2) CodeIgniter\CodeIgniterTest::testRun404OverrideByClosure
Test code or tested code did not (only) close its own output buffers
3) FeatureTestCaseTest::testEchoes
Test code or tested code did not (only) close its own output buffers
```
**Checklist:**

disable buffer check on "testing" environment

---

app/Config/App.php
system/Autoloader/Autoloader.php
system/CodeIgniter.php
system/Config/AutoloadConfig.php

Here's another way of loading Kint. This makes it use composer version if it's available and only loads Kint from ThirdParty folder if there is no composer version already loaded. This makes it possible to properly update Kint to latest version from composer when when ComposerScripts.php is not being executed fo example when composer's been added after getting zipped framework files and script is left out.
Additionally I've added some configurations for Kint to be obtained from Config\App. We might  add additional Kint configurations there as well.
One important config to be set is 
```
\Kint\Renderer\RichRenderer::$folder = false;
```
This make Kint to be displayed in place where it's called. Otherwise it goes to bottom as toolbar which creates conflicts with debug …

Updates To Kint Loading

---

user_guide_src/source/general/errors.rst

The last few code references in **general/errors.rst** were not formatted as code, causing them to be displayed incorrectly. This PR applies the "code" style, fixing #2530 
**Checklist:**

Apply User Guide code style to Errors

---

system/Debug/Toolbar.php

The JavaScript code for the toolbar is injected before the `<head>` tag. This PR moves it after, fixing #2545 
**Checklist:**

Move debug toolbar after head tag. Fixes #2545

---

system/Config/BaseService.php

Shared and mocked instance names are all stored in lowercase, but not necessarily looked up by the same. This PR forces the lowercase version to be used during `getSharedInstance()` as well.
Fixes #2534 
**Checklist:**

Use lowercase service names

---

system/Validation/Validation.php
tests/system/Validation/ValidationTest.php
user_guide_src/source/libraries/validation.rst

Was experiencing issue where i wanted to display the supplied value within the validation error message. So I've updated the validation class to pass the value through to the error message generation and to replace {value} with the supplied value.
**Checklist:**

WIP Update Validation.php

---

system/HTTP/Response.php

As noted in #2383 new protocols check the class property `$protocolVersion`, which will be empty. This PR changes it to use the `getProtocolVersion()` method which specifies a fallback.
Shoutout to @hcbd for the fix!
**Checklist:**

Use default protocol if unspecified

---

system/Images/Exceptions/ImageException.php
system/Images/Handlers/BaseHandler.php
system/Images/Handlers/GDHandler.php
system/Images/Handlers/ImageMagickHandler.php
system/Images/Image.php
system/Language/en/Images.php
tests/system/Images/BaseHandlerTest.php

Currently the framework fails with unhelpful messages if any of the Image handler functions are used without first calling `withFile()` on a valid image file path. This PR adds some checks that `withFile()` has been invoked and its source is an actual image.
Fixes #2421.
**Checklist:**

Image verification

---

system/CodeIgniter.php

Currently CLI segments are pushed together with a "/" and run through the router as though it were an actual route. This works most of the time, but fails in cases like #2148 where one of the parameters already contains a "/" (e.g. `spark import:file /tmp/files/myfile.csv`).
This PR changes the framework to use the actual segments as parameters, instead of the smushed router version. It will probably also do some general CLI cleanup.
**Checklist:**

Retain CLI segments

---

system/Cache/Handlers/FileHandler.php

Currently the cache `FileHandler` checks for the existence of the file, reads its contents, then if the TTL has expired it removes the file. Because of the disk operation to read the file and unserialize its contents it is conceivable (and has happened to me a few times) that concurrent calls actually interlace the removal of the file between its check and the second removal attempt, leading to an exception when it tries to `unlink` the non-existent file. This PR adds a second check to confirm the file still exists, which should ensure no two calls attempt to remove the same file.
**Checklist:**

Cache FileHandler unlink exception

---

system/Database/Forge.php
system/Database/SQLite3/Table.php
tests/system/Database/Live/ForgeTest.php
user_guide_src/source/dbmgmt/forge.rst

Fix issue #2576  
**Checklist:**

Fix drop column with array

---

system/Helpers/url_helper.php
tests/system/Helpers/URLHelperTest.php

Currently when providing a URI parameter to `base_url()` if it has a preceding slash it will cause the resulting URL to be relative to the root domain, rather than a subfolder defined in `app.baseUrl`. This PR trims preceding and trailing slashes in the helper to ensure the result from `HTTP\URI` is still relative to the base URL.
May fix some of #2445, hard to say without being able to replicate.
**Checklist:**

Subfolder base_url() with parameter

---

system/Model.php

I think someone adds casting here by mistake

Model's set method should accept not only string

---

system/Config/DotEnv.php

Currently `DotEnv` handles all its functionality in one go, using `load()`. This splits out the function so `parse()` returns the `key =>value` array and then `load()` still handles setting the variables. This allows external parsing of `.env` files (particularly for testing purposes). All tests and usage should remain consistent.
**Checklist:**

Add DotEnv::parse()

---

user_guide_src/source/concepts/http.rst
user_guide_src/source/incoming/filters.rst
user_guide_src/source/incoming/incomingrequest.rst

I fixed the links that should lead to the page with more information about AJAX requests.
**Checklist:**

Fixed links to the AJAX Requests details page

---

user_guide_src/source/extending/contributing.rst

Add Slack to the "Support" section of the documentation
**Checklist:**

Add Slack to the "Support" section of the documentation

---

tests/system/Database/Live/GroupTest.php

Fixed bug reported in issue # 2584
**Checklist:**

Fixed Bug: testOrHavingBy() requires a select | #2584

---

admin/starter/builds
user_guide_src/source/installation/installing_composer.rst
user_guide_src/source/installation/repositories.rst

With the official release around the corner the **devstarter** repo and installation method are now deprecated. This PR updates the docs to reflect that, including instead instructions on how to modify an AppStarter installation to similar effect. To assist with the toggle between release & development I've included a new `builds` script in the starter repo as well, which will update paths as needed in the following: composer.json, phpunit.xml.dist, phpunit.xml, Paths.php. At some point it would be good to figure out how to add tests for `builds` but at the moment I don't have any ideas.
**Checklist:**

Deprecate Devstarter, add `builds`

---

user_guide_src/source/concepts/http.rst
user_guide_src/source/incoming/filters.rst
user_guide_src/source/incoming/incomingrequest.rst
user_guide_src/source/libraries/caching.rst
user_guide_src/source/testing/overview.rst

Commits fixing all Sphinx warnings when generating the documentation.
_Only one left: "/CodeIgniter4/user_guide_src/source/changelogs/v4.0.0.rst: WARNING: document isn't included in any toctree". Because it is not a warning, it is a "consistency issue", and I don't know if it is on purpose._
**Checklist:**

[UG] Fix all Sphinx warnings

---

app/Config/Mimes.php

Simplified the condition as both clauses returning same output
**Checklist:**

Simplified the condition as both clauses returning same output

---

system/Database/MigrationRunner.php

Right now running command: `php spark migrate -all` triggers migrations for the test group too. This pull request fixes that. So now, to call migrations for tests group you have to be explicit and call `php spark migrate -g tests`
**Checklist:**

Skip running migrations for tests group by default - fix #2627

---

system/Debug/Toolbar/Views/toolbarloader.js.php

Sometimes (when using VueJS for instance) dom elements can not be found by the debugbar because the elements are not ready yet. Results in JS errors like:
```
Uncaught TypeError: Cannot set property 'innerHTML' of null
at XMLHttpRequest.<anonymous> (index.php?debugbar:77)
```
Coming from toolbarloader.js.php:
```
var h2 = document.querySelector('#ci-history > h2');
h2.innerHTML = 'History <small>You have new debug data.</small> <button onclick="loadDoc(' + debugbarTime + ')">Update</button>';
```
`#ci-history > h2` was not ready yet. Problem can be solved by making sure the debugbar is loaded right before the closing body tag.
**Checklist:**

Load debugbar script before closing body tag

---

system/Router/Router.php
system/Test/FeatureTestCase.php

This change allows you to reset `$this->directory` variable in the Router class -  to use with FeatureTestCase.
**Checklist:**

Reset dir for FeatureTestCase - fixes #2393

---

system/Controller.php

Every time a controller loads it logs 
INFO - {date time} --> Controller "App\Controllers\{class} loaded. 
Every other instance of logging a class being loaded has been removed from v4. This one should be too.

Remove logging of controller loaded

---

user_guide_src/source/intro/requirements.rst

Installation Requirements has been missing a tick and it has been driving me crazy for a while. Finally taking the time to submit a PR for what must be the smallest possible single-character change ever...
**Checklist:**

Add missing tick to Requirements

---

system/Helpers/number_helper.php
system/View/Filters.php
tests/system/Helpers/NumberHelperTest.php
tests/system/View/ParserFilterTest.php
user_guide_src/source/helpers/number_helper.rst

Added option to specify fraction in currency formatter.  
PHP intl currency number formatter for some reason does not handle the number decimals per locale. https://www.php.net/manual/en/numberformatter.formatcurrency.php
I've added additional parameter to the method to allow specifying fraction. 
The already existing unit test was failing in my environment for the same reason so I've updated those tests to use fraction parameter as well. Additionally, I've added test case which uses locale where currency symbol should be located after the value.
Ref #2634 
**Checklist:**

Number Helper - Added Fraction parameter in number_to_currency method

---

user_guide_src/source/general/logging.rst

If the level is 5 or less, debug message will also be ignored, thus there should be warning(level 5)，any levels higher than 5 would be ignored.

Updateing logging level restriction for logging.rst

---

system/Commands/Server/Serve.php

To avoid path problems, we should use `escapeshellarg` function for PHP_BINARY.
See: #2367
**Checklist:**

Escape php binary - fixes #2367

---

system/Common.php

When CI was installed in a subfolder, the redirection to https did not include this folder.
See: #2633
**Checklist:**

fix forceHTTPS bug #2633

---

system/CLI/CommandRunner.php
tests/system/CLI/CommandRunnerTest.php

Update default CLI command to run `list` instead of `help`.
See: #2645
**Checklist:**

Fix default CLI command #2645

---

user_guide_src/source/models/model.rst

The third update example is missing a parentisis.
**Checklist:**

Fix documentation bug. Modeling data / Using Codeigniter's model

---

user_guide_src/source/libraries/time.rst

Correction in the documentation of the library "Dates and Times" for the `today()`, `yesterday()` and `tomorrow()` methods that had wrong information about the parameters.
**Checklist:**

Correction to the 'Dates and Times' library documentation #2657

---

system/HTTP/IncomingRequest.php

I noticed this when looking at `IncomingRequest` class. It seems like this method call does nothing here and can be safely removed.
**Checklist:**

Remove call to resolveRelativeURI in detectURI method

---

system/Commands/Database/MigrateRefresh.php
system/Commands/Database/MigrateRollback.php
system/Language/en/Migrations.php
user_guide_src/source/dbmgmt/migration.rst

This pull request adds confirmation for rollback and refresh in a production environment. Confirmation can be bypassed via `-f` (force) option.
Ref: #2385
**Checklist:**

Confirmation for rollback and refresh in a production environment

---

system/I18n/Time.php
tests/system/I18n/TimeTest.php

Fix #2663 `CodeIgniter\I18n\Time` default format is `yyyy-MM-dd HH:mm:ss`, but `getYear` use `Y`,
the method return based week year. Last days of the some year, the method reutn current year +1.It's confusing 
**Checklist:**

fix. getYear can't week based year

---

system/Commands/Database/CreateMigration.php
system/Commands/Database/MigrateStatus.php

This pull request fixes  #2664. 
Also, to stay consistent I had to make some changes to the `migrate:status` command as well. Otherwise, the status command would display information about each namespace.
**Checklist:**

Force migrations to take into account the namespaces defined in composer

---

system/Format/JSONFormatter.php

Bugs:
https://github.com/codeigniter4/CodeIgniter4/issues/2434 and https://github.com/codeigniter4/CodeIgniter4/issues/2586
_! $result &&_ needs because json_encode generating result, all is ok, but json_last_error() anyway eqally error "Type not supported"

Fix JSON error on recursion in data

---

system/Database/BaseBuilder.php

We found some performance regressions while doing a large `insertBatch()` function call in an app ported over from CI2. On closer inspection using xdebug profiles, the performance bottleneck was found to be in the `BaseBuilder::setBind()` function. Specifically the while loop within the function used to identify the next key counter for the binding array. This causes the function to run in O(n^2) time.
Instead I've added a simple array lookup that keeps the function in O(n) time while marginally increasing the memory footprint.
**Checklist:**

Fix batch insert performance issue found in BaseBuilder::setBinding()

---

user_guide_src/source/testing/overview.rst

`\CIUnitTestCase` can't autoload. use namesapce `CodeIgniter\Test\CIUnitTestCase`

[ci skip] fix. add namespace for CIUnitTestCase

---

user_guide_src/source/incoming/filters.rst

`app\Filters\Throttle.php` is not exits,  userguide libraries/throttler have example code.
**Checklist:**

[ci skip] app\Filters\Throttle.php is not exits

---

system/Encryption/Handlers/OpenSSLHandler.php
user_guide_src/source/libraries/encryption.rst

Fix #2680
- Fixed exception path
- Called correct method when no encryption key provided
**Checklist:**

Fix exceptions for OpenSSLHandler

---

system/View/Parser.php
tests/system/View/ParserFilterTest.php

Extended regexp patterns in parseSingle and parsePair function with dot character and slashes. This solves the issue when expression like {timestamp|date(d.m.Y)} was not working correctly (issue raised here: https://forum.codeigniter.com/thread-75571.html). Also unified regexp patterns in Parser: now they both rely on \w macro that covers [A-Za-z0-9_] range.
This is a new PR, now with signature.
**Checklist:**

Parser regexp extended with dot and slash. Tests added to date filter.

---

system/Entity.php

If field in database stored as integer timestamp (as created_at, updated_at ...) and we want Datetime object, we get error
> DateTime::__construct(): Failed to parse time string (1583761346) at position 8 (4): Unexpected character
created_at, updated_at, deleted_at - work under mutateDate(), and so don't get errors

Fix cast integer timestamp to Datetime in Entity

---

system/Database/BaseBuilder.php

- When using WhereIn if the variable being passed in is not an array or closure it is simply returned with no user feedback. 
- However we have logic in place which allows regular values.
**Checklist:**

WhereIn() not supporting non array variables 🐛

---

system/API/ResponseTrait.php
system/RESTful/ResourceController.php
tests/system/RESTful/ResourceControllerTest.php

This is an alternative way to fix #2617 
I found that variable `$format` should be moved to `ResponseTrait` , so that it can be used inside `format` method.
I have add two unit testing for this change
**Checklist:**

Fix ResourceController Issue, including Test Unit

---

system/Session/Session.php
tests/system/Session/SessionTest.php

When the session is initialized during ajax request and we use `get(null)` or `get(key)` with an empty $_SESSION variable, we always get the empty array as a result.
This pull request fixes it, so now we receive accordingly:
* empty array for `get(null)` call
* null for `get(key)` call
This is a very rare use case scenario.
**Checklist:**

Fix session bug when the request is ajax call

---

system/Model.php
tests/system/Database/Live/ModelTest.php

`first` and `countAllResult` didn't recover `tempUseSoftDeletes`. 
**Checklist:**

fix. first and countAllResult recover tempUseSoftDeletes

---

admin/module/tests/database/ExampleDatabaseTest.php
admin/starter/tests/database/ExampleDatabaseTest.php

In `find` `findAll` `first` ... , use `tempUseSoftDeletes` to repalce `useSoftDeletes`.
befor `setPrivateProperty`, the model already initialization.
**Checklist:**

fix. testSoftDeleteLeavesRow can't worker

---

user_guide_src/source/libraries/caching.rst

`Multiple Memcached` not support, and `app/Config/redis.php` not exist
**Checklist:**

[ci skip] add caching's redis and memcached options list

---

phpunit.xml.dist

system/Test/bootstrap.php no need to be included in coverage test.
**Checklist:**

exclude system/Test/bootstrap.php from coverage test

---

system/CodeIgniter.php
system/Common.php
system/Database/MigrationRunner.php
system/Debug/Toolbar.php
system/Session/Session.php

If the code never hit by testing environment, it need to be ignored from coverage test.
**Checklist:**

add // @codeCoverageIgnoreStart and // @codeCoverageIgnoreEnd on conditional non testing environment

---

system/HTTP/IncomingRequest.php

@MGatner Based on your comment at https://github.com/codeigniter4/CodeIgniter4/commit/8127cb2ffe577c1382aaed77121a437b313d61ad#commitcomment-37901776
**Checklist:**

revert outdated $this->uri->resolveRelativeURI() call at IncomingRequest class

---

admin/starter/composer.json
system/Test/bootstrap.php
tests/_support/Config/Routes.php
tests/_support/Controllers/Popcorn.php
tests/system/Router/RouteCollectionTest.php
tests/system/Test/ControllerTesterTest.php
tests/system/Test/FeatureTestCaseTest.php

Fixes #2676 to add ability to test redirect()->route() in test bootstrap so the existing route both in `app` and `tests` will be discovered.
**Checklist:**

Fix #2676 : add ability to test redirect()->route() via ControllerTester

---

system/Helpers/form_helper.php
tests/system/Helpers/FormHelperTest.php

Fix issue set_radio when value is 0

---

system/Commands/Database/MigrateRefresh.php

This minor modification fix an issue when using `php spark migrate:refresh`:
```console
maz@Maz-Laptop:~/www/project$ php spark migrate:refresh
CodeIgniter CLI Tool - Version 4.0.2 - Server-Time: 2020-03-21 13:57:57pm
An uncaught Exception was encountered
Type:        Error
Message:     Class 'CodeIgniter\Commands\Database\CLI' not found
Filename:    /media/maz/Windows/Users/maz-/Desktop/www/project/system/Commands/Database/MigrateRefresh.php
Line Number: 113
```

Fix Class Database\CLI not found

---

system/Validation/FormatRules.php
tests/system/Validation/FormatRulesTest.php

Fix #2740 to allow  number `.25` as a valid number.
**Checklist:**

Fix #2740 regex decimal format rules

---

system/Log/Logger.php

Fixes #2738 
``CodeIgniter\Log;Logger::logPath`` property never set and is never used by the Logger or any other class.

Remove unused property

---

system/Test/CIDatabaseTestCase.php

Previously the rollback process was only "delete all tables" statement, using `$forge`.
The problem with this process is the foreign key in Postgre (and probably other SQL standards databases system): droping table without the ` CASCADE` at the end of `DROP TABLE` statement throw an error:
```console
pg_query(): Query failed: ERROR:  cannot drop table db_users because other objects depend on it
DETAIL:  constraint db_cities_user_uuid_fkey on table db_cities depends on table table db_users
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```
Without this modification, the previous error was thrown and we couldn't test the database without refreshing it.
Using the `$this->migrations` process ensure that the user's migration's `down` requests are followed, such mine in this …

Modify database tests refresh process to use migration on rollback

---

system/Model.php

Model::findAll() always returns array based on `ResultInterface::getResult()`
**Checklist:**

docblock @return fix: Model::findAll() never returns null

---

system/HTTP/Message.php

appendHeader should call setHeader for non existing header. This is especially useful for HTTP2 push when it's not possible to alway know the exact order in which assets will be set to Link header so it's not very easy to call the setHeader method first.
Fix #2730 
**Checklist:**

CodeIgniter\HTTP\Message - Fix appendHeader

---

system/Helpers/array_helper.php
tests/system/Validation/ValidationTest.php

Fix #2714 
In function `_array_search_dot` empty check for `$currentIndex` was failing for index 0 in array.
`empty()` will return `true` for value `0`. 
Details: https://www.php.net/manual/en/function.empty.php
**Checklist:**

Fix validation for array input fields

---

system/Database/BaseResult.php

BaseResult sets data on Entity object using setAttributes method. syncOriginal is called from setAttributes method so there is no need to call it again from the BaseResult.
I don't know if there is even a good reason to call it from BaseResult. I might be useful if there is a need for data processing after it's been loaded from DB but in such case syncOriginal might not be a good name for the method.
**Checklist:**

BaseBuilder - syncOriginal called twice on data fetch for Entity Class

---

system/Entity.php

Use strpos instead of substr when possible
**Checklist:**

performance improvement: use strpos instead of substr when possible

---

system/Entity.php
tests/system/EntityTest.php

Allow json_encode() to be called on an Entity class, to have its attributes returned, json_encoded. This is not just a nice to have but also solves an issue for the ResourceController (#2617).
**Checklist:**
PS. I created a PR for this contribution before but it was messy so I closed it and did it again. First contribution, hope it meets your standards. Congrats on version 4.0!

Implement JsonSerializable on Entity class

---

system/Router/Router.php
tests/_support/Controllers/Product.php
tests/system/Router/RouteCollectionTest.php

Fixes #2520 : ensure service(router)->controllername() returns fqcn
**Checklist:**

Fixes #2520 : ensure service(router)->controllername() returns fqcn

---

system/Pager/Pager.php
tests/system/Pager/PagerTest.php
user_guide_src/source/libraries/pagination.rst

If $group=null then group name and query string param name is made of timestamp (change every call) making it useless. Setting default $group to "default" string literal solves the problem and generates default "page" query param name.
**Checklist:**

Pager makeLinks param fix

---

system/Session/Session.php
tests/system/Session/SessionTest.php

Session key is `test.1`,`Session::get` use `dot_array_search` handle, return `null`. 
**Checklist:**

fix. session::get just use dot_array_search handle session key

---

user_guide_src/source/general/modules.rst

Trying to make the explanation of auto-discovery as it pertains to the acme/blog example more clear.

Revise modules documentation page [ci skip]

---

system/Database/BaseUtils.php

Since it is non functional ( seems borrowed from ci3) but doesn't bring the `CI_Zip` library. So, the supported format will only be "gzip" or "txt".
**Checklist:**

remove "zip" format in Database\BaseUtils

---

admin/starter/builds

@MGatner This is to handle composer update try to catch all "dev" version of dependencies in `vendor` directory when running composer update after : 
```bash
php builds development
composer update
```
With make `"prefer-stable" => true`, it will only get dev version when required, eg: in : 
```
"codeigniter4/codeigniter4": "dev-develop"
```
Other packages will try get stable version. The result of composer.json will have: 
```json
"minimum-stability": "dev",
"prefer-stable": true,
```
**Checklist:**

add "prefer-stable" => true to admin/starter/builds when ./builds development called

---

system/Test/CIDatabaseTestCase.php

Because it extends `CIUnitTestCase` that extends `PHPUnit\Framework\TestCase` that uses `protected` modifier for `tearDown()` method. I applied "parent::tearDown()` call first as well.
**Checklist:**

 using "protected" modifier for CIUnitTestCase::tearDown() 

---

user_guide_src/source/models/entities.rst

[ci skip] doc typo fix in entity, using "," instead of ";" in array attributes definition

---

system/View/Parser.php

Change type hint for ``$logger`` argument of ``Parser::__construct()`` to use `Psr\Log\LoggerInterface` instead of `CodeIgniter\Log\Logger` which will allow alternative PSR-3 loggers to be used in ``Parser``.
This brings ``Parser`` in line with the other core classes that have a "logger" dependency.

Parser use LoggerInterface

---

system/Validation/Validation.php
tests/system/Validation/ValidationTest.php
user_guide_src/source/libraries/validation.rst

Fix validation for multi select

---

tests/system/Validation/ValidationTest.php

Uncommented data provider in tests. Made a mistake in my [last PR](https://github.com/codeigniter4/CodeIgniter4/pull/2765)
@samsonasik Here is the fix. Again thank you for pointing this
**Checklist:**

Uncommented tests, mistake in my previous PR :(

---

system/Config/Services.php
system/Model.php
system/Pager/Pager.php
tests/system/Database/Live/ModelTest.php
tests/system/Pager/PagerTest.php

Currently, the `$perPage` is default to `20` in `Model::paginate()` function. I think it should read from `config('Pager')->perPage` instead. I apply make default to null, and check if it is not passed, it will use the default `config('Pager')->perPage`
**Checklist:**

make Model::paginate() use default perPage from Config\Pager->perPage if $perPage parameter not passed

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/CountTest.php
tests/system/Database/Live/ModelTest.php

Fixes #2776 with add `! empty($this->QBGroupBy)` after distinct check in `Database\BaseBuilder::countAllResults()`so the result query of count is a count of the query with group by.
**Checklist:**

Fix #2776 add ability to paginate() query with group by

---

user_guide_src/source/installation/installing_git.rst
user_guide_src/source/installation/repositories.rst
user_guide_src/source/installation/upgrade_4xx.rst

- Found some errors in the rendering of the userguide.
- Removed a part from the git installation referencing a command, but there where no command.
**Checklist:**

Fixed some styling in "Installation" chapter [ci skip]

---

tests/system/Autoloader/AutoloaderTest.php

By this, `CodeIgniter\Autoloader\Autoloader` will have 100% test coverage.
**Checklist:**

test Autoloader::initialize() with composer path not found

---

README.md

Previously, it only shows "4.4k", while it already "24.73k" downloads, seems because of path url location to `codeigniter4/codeigniter4` instead of `codeigniter4/framework`. 
I updated the badge to use `poser.pugx.org` as the `img.shields.io` only shows 0 downloads.
**Checklist:**

[ci skip] Fix download badge total shows

---

system/Model.php

On Model->Update, the dataset may empty after object convert to array.
So do an extra check on empty dataset before do real update.
**Checklist:**

Check if dataset is empty before Model update.

---

README.md
admin/framework/composer.json
composer.json
system/Autoloader/Autoloader.php
tests/system/Autoloader/AutoloaderTest.php
user_guide_src/source/intro/requirements.rst

Like in my comment at https://github.com/codeigniter4/CodeIgniter4/issues/2784#issuecomment-609515200 , that in other forum in facebook, I got people ask about `php spark serve` error as well, and solved by install mbstring extension. I also updated regex that sanitize file name.
**Checklist:**

add ext-mbstring to required and update regex that sanitize file name

---

system/Controller.php
tests/system/ControllerTest.php

By this, `CodeIgniter\Controller` class will have 100% test coverage. I updated manual instantiation of `Config\Validation` with `config('Validation)` which make it testable.
**Checklist:**

test Controller::validate() with string rules

---

system/Test/FeatureTestCase.php
tests/system/Test/FeatureTestCaseTest.php

Mostly, for testing 404 pages. By move the `ob_get_level()` check in the beginning of method `FeatureTestCase::call()`. 
> For note: there is still `ob_start()` in the test case for `testEchoes()` which currently required as content already echoed.
**Checklist:**

clean up buffer tweak in FeatureTestCaseTest 

---

public/index.php

Other places that define `../` in paths, using `realpath()` to ensure location, like in `system/bootstrap.php`. 
I updated as well for `$pathsPath` in `public/index.php`.
**Checklist:**

using realpath() for define $pathsPath in index.php

---

system/Exceptions/CastException.php
system/Exceptions/ConfigException.php

As the callers already call `throw` and most other exception classes uses `return`.
**Checklist:**

make named constructor in Exception classes consistent: use return instead of throw

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/FromTest.php

The `QBFrom` part is not resetting. That can lead to unexpected results when combined with a call to `from` method. This pull request makes sure that only first table from QBFrom array is saved after the query is executed.
Ref: #2800 
**Checklist:**

Add resetting QBFrom part

---

tests/system/EntityTest.php

Added more test to `CodeIgniter\Entity` class, by this, `CodeIgniter\Entity` class will have 100% test coverage. It test the following methods conditions:
- test toArray() skip attributes with '_' in first character.
- test hasChanged() returns false when key not exists
- test __get() for nullable type with has value, at `castAs($value, string $type)` function.
**Checklist:**

add more test for Entity : 100% tested

---

system/Test/Mock/MockEmail.php
tests/system/Email/EmailTest.php

Based on @MGatner comment at https://github.com/codeigniter4/CodeIgniter4/pull/2785#issuecomment-607180488
**Checklist:**

add MockEmail class

---

tests/system/Log/LoggerTest.php

By this, `CodeIgniter\Log\Logger` will have 100% test coverage.
**Checklist:**

test Logger::determineFile() for no stack trace

---

system/Helpers/filesystem_helper.php
tests/system/Helpers/FilesystemHelperTest.php
user_guide_src/source/helpers/filesystem_helper.rst

https://forum.codeigniter.com/thread-75898.html
`get_filenames()` current has two different return types, contingent on its second parameter. The first (default) is a flat list of all files in all subdirectories:
> document.txt
> cat.jpg
> rainbow.exe
And the second is the same files by their absolute paths:
> /var/www/html/mysite/document.txt
> /var/www/html/mysite/assets/cat.jpg
> /var/www/html/mysite/downloads/cached/rainbow.exe
I am of the opinion that the first is pretty much useless, and that a relative listing of file paths would be much more helpful. See the forum discussion for more details.
This PR changes the function significantly to allow for the new return types: relative to source, and full path. It also no longer uses `realpath()` since that makes the …

Rework get_filenames

---

system/HTTP/IncomingRequest.php

When doing spark serve, `$_SERVER['SCRIPT_NAME']` has a bug that leads to URI like `/uploads/avatar/1.jpg` being treated as `/`. This solves the problem by making sure that `$_SERVER['SCRIPT_NAME']` is indeed a PHP file, otherwise don't process it futher.
This solves issue #2194 
**Checklist:**

Ensure $_SERVER['SCRIPT_NAME'] ends with PHP

---

system/CodeIgniter.php
system/Database/BaseBuilder.php
system/Database/Postgre/Builder.php
system/Model.php

Ignore coverage when CI_DEBUG is false as never hit in tests.
**Checklist:**

ignore coverage on !CI_DEBUG

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/WhereTest.php

Fix missing "\\" prefix in throw InvalidArgumentException.
**Checklist:**

Fix missing InvalidArgumentException in Database\BaseBuilder

---

system/API/ResponseTrait.php
tests/system/API/ResponseTraitTest.php

Added method `respondUpdated()` for `Used after a resource has been successfully updated.`. The status code is 200 based on https://restfulapi.net/http-methods/#put
**Checklist:**

add respondUpdated() method into API\ResponseTrait

---

system/Helpers/form_helper.php
tests/system/Helpers/FormHelperTest.php
user_guide_src/source/helpers/form_helper.rst

So no need to manually add locale from variable when call `form_open()` in view.
**Checklist:**

add ability to replace {locale} to request->getLocale() in form_open('action')

---

tests/system/API/ResponseTraitTest.php

By this, `CodeIgniter\API\ResponseTrait` will have 100% test coverage.
**Checklist:**

test for API\ResponseTrait::format() with format is not json or xml

---

system/Pager/Pager.php
tests/system/Pager/PagerTest.php

So, when we have a data, for example: 10 records, and per-page is 1. We next want to pass `?page=11`, we will get latest page displayed page 10.
**Checklist:**

Pagination: open page > pageCount get last page

---

system/Autoloader/FileLocator.php

Fix Issue #2840 for `FileLocator::findQualifiedNameFromPath()` method
The method returns the $className even if the class does not exist, resulting in console commands not to be discovered.
**Checklist:**

Fixed Issue #2840 on discovery of classes by FileLocator

---

user_guide_src/source/_static/css/citheme.css
user_guide_src/source/_templates/layout.html
user_guide_src/source/conf.py

sphinx_rtd_theme v0.4.3 have [flash of unstyled content](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) (FOUC) problems.
- Removed + next to the navigation to mitigate left to right jumping in navigation
- Changed rendering depth to 2, like userguide v3
- Included a complete replacement of layout.html to be able to mitigate FOUC, by moving CSS above JS.
We still have problems with top to bottom jumping in navigation, due to the length of our navigation. That's not something that can be easily fixed as that's bundled JS with the theme. As per v3 userguide you need to scroll down to the current menu item. In v4 it jumps down to the selected one, giving better UX. That's what causing that jump.
This FOUC are included in the development branch of sphinx_rtd_theme, but as per …

Improve flash of unstyled content in userguide

---

system/Language/en/Validation.php

This replaces "Validation.string" message with a more meaningful one.
**Checklist:**

Add English message for "string" validation rule

---

system/HTTP/Response.php
tests/system/Helpers/CookieHelperTest.php

Fix #2700.
`Response::deleteCookie` can't delete already set Cookie.
**Checklist:**

fix. delete_cookite can't delete alreday set Cookie

---

user_guide_src/source/_static/css/citheme.css
user_guide_src/source/outgoing/localization.rst

- I have now made the userguide fixed to 900px, as we previously had it extended all the way, making it harder for people to read.
- The CI flame are now positioned to the bottom right corner in the "content" box. It made it harder to read, specifically on mobile devices.
- Making tables responsive again, but with "pre" rendering instead of the default nowrap. Rendering as we see it in .rst, real "enter" in templates results in enter in the userguide itself. Or we will end up with "endless" scrolling in [Validation - Available Rules](https://codeigniter.johaneklund.com/userguide/master/libraries/validation.html#available-rules).
- Fixed incorrect rendering in "Localization". 
**Checklist:**

Improve readability in the userguide with a fixed size

---

system/Database/MySQLi/Connection.php
system/Database/Postgre/Connection.php
system/Database/SQLite3/Connection.php
tests/system/Database/Live/DEBugTest.php

DBDebug set false, but the error is show.
**Checklist:**

fix. MYSQLI::DBDebug can't woker

---

system/Database/BaseBuilder.php
system/Database/Postgre/Builder.php

#2780 
_limit() is called inside delete(), no need to call it again in _delete();

#2780 - LIMIT.

---

system/Debug/Exceptions.php
system/Test/bootstrap.php
system/bootstrap.php
tests/system/Debug/ExceptionsTest.php

Change the directory separator in cleaning paths to the platform-specific DIRECTORY_SEPARATOR for nicer look, especially for Windows. Also added new paths to clean.
**Checklist:**

Normalize dir separator of Exceptions::cleanPath and added more paths to clean

---

user_guide_src/source/installation/running.rst

Documentation fix: environment "develop" should be "development"
**Checklist:**

[ci skip] typo fix Initial Configuration & Set Up

---

admin/pre-commit

The pre-commit hook fails parsing files when the file paths contained spaces. My solution is to enclose the file path `$PROJECT/$FILE` in double quotes. This solution works with PHP's built-in linter. For Code Sniffer, I can't make it read the enclosed file path as a single file. It still breaks them at the spaces. *Perhaps a bug in Code Sniffer? I don't know.*
As a workaround, I only passed the relative file paths of the files to `phpcbf`. Tested locally, and phpcbf can still check the files.
**Checklist:**

Enclose file paths in double quotes to capture spaces

---

system/HTTP/IncomingRequest.php
tests/system/HTTP/IncomingRequestTest.php

fix. getGetPost and getPostGet can't work in index empty

---

user_guide_src/source/incoming/message.rst

`getHeader` return a header object, not string or array of string
`headerLine` not exists, have a `getHeaderLine`
**Checklist:**

[ci skip]fix. getHeader return header object

---

system/Database/Seeder.php

This PR solves the problem of loading the Forge class into the Seed class, thus allowing the use of the Forge class functionalities in a seed.
**Checklist:**

Initialize $forge property in Seeder Class - fixes #2825

---

system/Model.php

i don't know why the $segment parameter is not present when the Pager library is call by the Model paginate function
add the $segment option when the Pager library is call by the Model paginate function

add $segment parameter in pager call by Model.php

---

system/Validation/Validation.php
tests/_support/Language/en/Foo.php
tests/system/Validation/ValidationTest.php
user_guide_src/source/libraries/validation.rst

This pull request allows the easy localization of labels in form validation rules.
Using a "dot notation" for a label in validation rules, like: `Foo.bar` will search for file `en/Foo.php` and line `bar`. If the file or line doesn't exist the usual text will be returned.
Ref: #2845
**Checklist:**

Localized label in validation rules

---

user_guide_src/source/incoming/routing.rst

The URI Routing code examples were above their descriptions.  Shifted them down.

Shifted basic URI Routing examples down

---

user_guide_src/source/incoming/restful.rst
user_guide_src/source/incoming/routing.rst

fix : #2889  #2888
```
/**
* Defined placeholders that can be used
* within the
*
* @var array
*/
protected $placeholders = [
'any'      => '.*',
'segment'  => '[^/]+',
'alphanum' => '[a-zA-Z0-9]+',
'num'      => '[0-9]+',
'alpha'    => '[a-zA-Z]+',
'hash'     => '[^/]+',
];
```

[ci skip] route placeholders 'id' to 'num'

---

user_guide_src/source/libraries/validation.rst

Fixes 9 warnings emitted by `make html` when compiling the user guide. Error is found in the syntax of `validation.rst`
Warnings thrown are as follows:
* user_guide_src\source\libraries\validation.rst:497: WARNING: Unexpected indentation.
* user_guide_src\source\libraries\validation.rst:498: WARNING: Block quote ends without a blank line; unexpected unindent.
* user_guide_src\source\libraries\validation.rst:499: WARNING: Definition list ends without a blank line; unexpected unindent.
* user_guide_src\source\libraries\validation.rst:501: WARNING: Unexpected indentation.       
* user_guide_src\source\libraries\validation.rst:504: WARNING: Unexpected indentation.       
* user_guide_src\source\libraries\validation.rst:505: WARNING: Block quote ends without a blank line; …

[ci skip] fix warnings on compiling user guide

---

user_guide_src/source/concepts/autoloader.rst
user_guide_src/source/general/ajax.rst
user_guide_src/source/general/common_functions.rst
user_guide_src/source/general/errors.rst
user_guide_src/source/general/helpers.rst
user_guide_src/source/general/logging.rst
user_guide_src/source/general/managing_apps.rst

I have now gone thru "General Topics", and this this are the inconsistencies I found.
**Checklist:**

Added more Common functions and improved rendering in userguide

---

system/Common.php
tests/system/CodeIgniterTest.php
tests/system/CommonFunctionsTest.php

- Fixes session active detection on force_https function
- Add more test CodeIgniter::forceSecureAccess() run force_https() when `$config->forceGlobalSecureRequests` is true.
**Checklist:**

Fixes session active detection on force_https function and add more test CodeIgniter::forceSecureAccess() run force_https()

---

user_guide_src/make.bat

Enable Windows users to run `make html` without having to install [GnuWin32's make](https://sourceforge.net/projects/gnuwin32/files/make/).
This batch file is auto-generated by `sphinx-quickstart` and I think should be committed for the benefit of contributors using Windows.
**Checklist:**

[ci skip] Add `make.bat` for Windows users

---

system/Model.php
tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
tests/_support/Database/Seeds/CITestSeeder.php
tests/_support/Models/StringifyPkeyModel.php
tests/system/Database/Live/MetadataTest.php
tests/system/Database/Live/ModelTest.php

To make enable  to delete row with string primary key via Model::delete($id) 
**Checklist:**

Added ability to delete row with string primary key via Model::delete($id)

---

system/Pager/Views/default_full.php

This PR corrects the following problems:
- issue #2875, where the next and previous links did not use language information, always maintaining a standard format
**Checklist:**

Update of the pagination template to make the correct use of the locale

---

system/API/ResponseTrait.php
tests/system/API/ResponseTraitTest.php
user_guide_src/source/outgoing/api_responses.rst

Allow bypassing content negotiation during API responses by specifically setting the value of the controller's `$format` to either `json` or `xml`. It will default to `json` just like it always has. 
If `$format` is `null`, it will be automatically determined through content negotiation.

Allow bypassing content negotiation during API responses.

---

system/Pager/PagerRenderer.php
tests/system/Pager/PagerRendererTest.php

The new features comprise a set of methods that will allow the user to build a pagination structure following the traditional way, where "next" and "prev" advance or return to a page and not to a group of pagination links as is the default.
Added methods:
- `hasPreviousPage:` checks if there is a page before the current page
- `getPreviousPage:` retrieves the URI of the page prior to the current page
- `hasNextPage:` checks if there is a page after the current page
- `getNextPage:` retrieves the page's URI after the current page
**Checklist:**

New features for pagination

---

system/Database/BaseBuilder.php
system/Model.php
tests/system/Database/Live/ModelTest.php

This fix the condition, eg: in Postgresql when we can supply sql like:
```sql
SELECT SUM(id) as total FROM "user" WHERE 1 = 1 LIMIT 1 ;
```
without group by, and followed order by. So, make order by only when there is a group by.
**Checklist:**

Fix Model::first() only use orderBy() when group by is not empty

---

user_guide_src/source/helpers/url_helper.rst

- From `url_title($title, 'underscore');` into  `url_title($title, '_');`
- Fixed some rendering of class names in params and return types. Requires \\.
- Tabs to spaces etc.
https://forum.codeigniter.com/thread-76292.html
**Checklist:**

url_title() used CI3 style in user guide

---

user_guide_src/source/cli/cli_commands.rst

forgot import the class
**Checklist:**

fix undefined class 'CodeIgniter'

---

user_guide_src/source/incoming/content_negotiation.rst
user_guide_src/source/incoming/controllers.rst
user_guide_src/source/incoming/filters.rst
user_guide_src/source/incoming/incomingrequest.rst
user_guide_src/source/incoming/message.rst
user_guide_src/source/incoming/methodspoofing.rst
user_guide_src/source/incoming/request.rst
user_guide_src/source/incoming/restful.rst
user_guide_src/source/incoming/routing.rst

Another day, another chapter. Now I went over "Controllers and Routing" chapter of the user guide.
- Tabs to space. Added tables. etc
- Added additional information to Controllers about PSR-4
- IncomingRequest Class - Class Reference from parent where incorrect
- HTTP Messages - Methods where incorrect and incomplete
- Request Class - Methods where incomplete
- URI Routing - "Method" referenced as "function"
- getVar referenced as it only got two parameters, there are a third one.
What is left to do:
```
IncomingRequest Class
php:method (missing functions, and checking current ones)
Content Negotiation
php:class
php:method (all, as it non existing)
```
Demo at:
https://codeigniter.johaneklund.com/userguide/master/incoming/controllers.html
**Checklist:**

Improved subjects in Controller and Routing chapter

---

system/Model.php
system/Validation/Validation.php
tests/system/Validation/UniqueRulesTest.php
user_guide_src/source/libraries/validation.rst
user_guide_src/source/models/model.rst

Same as #2882 but without rebase... this are based on develop instead.
**Checklist:**

Make validation placeholders always available

---

user_guide_src/source/libraries/curlrequest.rst

Correction of the name of the baseURI parameter in the documentation for the CURLRequest library.
This error reported in commit #2922.
**Checklist:**

[ci skip] Correction of the name of the baseURI parameter in the docs

---

system/Language/Language.php
tests/system/Language/LanguageTest.php

Fixes #2932 : Fix Translation key may separated by dot.
**Checklist:**

Fixes #2932 : Fix Translation key separated by dot

---

user_guide_src/source/changelogs/index.rst
user_guide_src/source/incoming/incomingrequest.rst
user_guide_src/source/incoming/message.rst
user_guide_src/source/libraries/curlrequest.rst
user_guide_src/source/libraries/email.rst

Sphinx outputted error messages when trying to rebuild the userguide from scratch. Some parts did not render (like the baseURL) table, rendering quality and the rest about duplicated functions.
**Checklist:**

Correct misc build errors in user guide

---

system/Model.php
tests/system/Database/Live/ModelTest.php
user_guide_src/source/models/model.rst

This PR adds the ability to set validation rules for model dynamically via methods: `$model->setValidationRules($rules)` or `$model->setValidationRule($field, $rules)`. This can be very useful when working on applications that have many configuration options.
**Checklist:**

Set validation rules for model dynamically

---

app/Config/Exceptions.php

Allow `Config\Exceptions` to extend the `BaseConfig` so that user-defined modules or external modules may supply their own registrars to populate the properties to their specific needs. Or users may use `.env` for the same purpose.
**Checklist:**

Allow Exceptions config to extend BaseConfig

---

system/Router/RouteCollection.php
tests/system/Router/RouteCollectionTest.php

The `CodeIgniter\Router\RouteCollection::localizeRoute` method was in error in the routine that adjusts the URL for the isioma selected by the user through `locale`.
The bug was reported in issue #2921.
**Checklist:**

Localization bug fix in localizeRoute method

---

user_guide_src/source/tutorial/news_section.rst

[ci skip] Fix the location of the note

---

system/Entity.php
tests/system/EntityTest.php

I fixed a bug (or what I think is one) in the Entity class that caused entity attributes cast as 'array', 'json' and 'json-array' not to be automatically serialized or encoded when the `fill` (and, by consequence, the constructor) is used.
I also modified the anonymous class returned by getCastEntity in EntityTests to allow for constructor arguments to be passed to it.
**Checklist:**
**Reproduction and other notes:**
Consider this entity
```php
<?php
namespace App\Entities;
use CodeIgniter\Entity;
class CastFillBug extends Entity
{
protected $casts =[
'field1' => 'array',
'field2' => 'json',
'field3' => 'json-array',
];
}
```
and this piece of code
```php
$entity = new \App\Entities\CastFillBug();
$data = [
'field1' => [1,2,3],
'field2' => [4,5,6],
'field3' => [7,8,9]
]; …
```

Fixes Entity::fill() not autoserializing/encoding

---

system/Pager/Pager.php
tests/system/Pager/PagerTest.php

Handle when segment parameter out of bound fallback set current page = 1 at https://github.com/codeigniter4/CodeIgniter4/blob/a063f14e62b36531f52afa0bf71b8e54c00f6399/system/Pager/Pager.php#L536-L543
**Checklist:**
By this, the `Pager` also will have 100% test coverage.

Bug fix Pager Segment parameter out of bound fallback set current page = 1

---

system/Images/Handlers/BaseHandler.php
system/Images/Handlers/GDHandler.php
system/Images/Handlers/ImageMagickHandler.php
tests/system/Images/GDHandlerTest.php
user_guide_src/source/libraries/images.rst

If you tried to re-compress an image with GD it failed as it where required to have an image resource, and that's only set when you for e.g. flip an image. I have copied the code from ImageMagick, so that it will just copy your image to the new location.
```php
$image = \Config\Services::image()
->withFile('/path/to/image/mypic.jpg')
->save('/path/to/image/my_low_quality_pic.jpg', 10);
```
Implemented a `withResource()` so that you can use method chaning instead of using the provided `getResource()` (used in tests). To just compress your image.
```php
$image = \Config\Services::image()
->withFile('/path/to/image/mypic.jpg')
->withResource()
->save('/path/to/image/my_low_quality_pic.jpg', 10);
```
Made `ensureResource()` an abstract function and copied the original code into GDHandlar, as …

Improvements to Image Manipulation Class

---

system/Validation/Validation.php
tests/system/Validation/RulesTest.php

Validation - Handle required_with and required_without on permit_empty

---

system/Debug/Timer.php

Trivial PR to adjust the Doc Block of `Debug\Timer`.
**Checklist:**

Fix PHP Docblock of Debug\Timer

---

system/Debug/Toolbar/Collectors/BaseCollector.php

Since the method signature of `BaseCollector::cleanPath()` is essentially the same with `Exceptions::cleanPath()`, and both are doing the same thing, *i.e.* creating nicer looking paths for the error output, I think one should use the other for the code to be DRY.
**Checklist:**

Replace BaseCollector::cleanPath with Exceptions::cleanPath

---

app/Config/Services.php
tests/system/Config/ServicesTest.php

It is unneded since the Autoloading already handle it in `system/bootstrap.php`. 
**Checklist:**

clean up: remove unneeded require_once in app/Config/Services.php

---

system/Config/Services.php

Minor change. Fixed a case in which getIPAddress is called with inconsistent capitalization. Makes code more easily searchable.
**Checklist:**

Fix inconsistent capitalization for request->getIPAddress()

---

app/Config/Events.php
system/Exceptions/FrameworkException.php
system/Language/en/Core.php

This answers issue #2980 and is related to #2182. 
In the 'pre-system' event, added a check if `zlib.output_compression` ini is turned on. If it does, pages will be blank so this check warns devs for this scenario. The exception thrown will be managed by the exception_handler, resulting to these snippets:
// browser
// terminal
**Checklist:**

Force devs to turn off zlib.output_compression ini in 'pre-system' event

---

system/Database/BaseBuilder.php
system/Database/Postgre/Builder.php
tests/system/Database/Builder/JoinTest.php

The postgresql support full outer join. I think it can be added to postgresql query builder.
**Checklist:**

add full outer join support for postgresql

---

system/Router/Router.php
tests/system/Router/RouterTest.php

Fix. the parsing method is empty

---

user_guide_src/source/testing/feature.rst

Fix #2993 
The example of "The Test Class“ is not working in Documets
The example code is not working anymore with v4.0.3.
**Checklist:**

Fix: Example code is not working #2993

---

system/Database/Postgre/Forge.php
tests/system/Database/Live/ForgeTest.php

Previously, On calling Forge at PostgreSQL, like the following:
```php
<?php
$this->forge->addField([
'id'     => [
'type'           => 'BIGINT',
'unsigned'       => true,
'auto_increment' => true,
],
]);
```
It previously converted to integer instead of bigint. By this chage, it ensure correctly make bigint when we define "BIGINT".
**Checklist:**

bug fix: ensure "BIGINT" to correctly applied to Postgresql Forge

---

system/I18n/Time.php
tests/system/I18n/TimeTest.php
user_guide_src/source/libraries/time.rst

Fix #2989
`Time::setTimezone` shuold same `DateTime::setTimezone`
**Checklist:**

fix. Time::setTimezone can't work

---

system/HTTP/URI.php
tests/system/HTTP/URITest.php
user_guide_src/source/libraries/uri.rst

Using `$uri->setSilent()` method will disable throwing exceptions. May be handy for using with methods like `$uri->getSegment()`.
Ref: #2952, #2949
**Checklist:**

Add setSilent() method to URI class

---

system/Config/DotEnv.php

Nested variables are now parsed correctedly, the previous version called the setVariable() function in a loop after all the parsing happened, returning always null for nested vars.
**Checklist:**

Bug fixing related to PR #2987 on DotEnv.php

---

system/HTTP/IncomingRequest.php
system/Test/FeatureTestCase.php
tests/_support/Controllers/Popcorn.php
tests/system/HTTP/IncomingRequestTest.php
tests/system/Test/FeatureTestCaseTest.php

`$params` from GET and POST requests were being passed as the body to the `IncomingRequest`, which doesn't match up with how things actually work. Since `$params` were already being set in the globals correctly,this tweaks it all to work better and work with `$params` for GET requests in either `$params` or in the URI itself (i.e. `/home?foo=bar`).

Don't add params to IncomingRequest in FeatureTestCase, per discussion in #2946

---

composer.json
system/Language/en/Fabricator.php
system/Test/Fabricator.php
tests/_support/Models/FabricatorModel.php
tests/system/Database/Live/FabricatorLiveTest.php
tests/system/Test/FabricatorTest.php
user_guide_src/source/testing/fabricator.rst
user_guide_src/source/testing/index.rst

*This is something I keep needing and finally set out to write a module for it, then realized it might be appropriate for the core framework.*
**Fabricator** is a test utility used to create faked data based on Model definitions. Similar to Laravel's "factories" it creates instances of `$model->returnType` with random data generated by Faker.
**Checklist:**

Fabricator class

---

system/HTTP/IncomingRequest.php
tests/system/HTTP/IncomingRequestTest.php

Fix: index not exists, getPostGet and getGetPost should return null
