codeigniter4/CodeIgniter4

user_guide_src/source/changelogs/v4.1.4.rst

Extracted from #4883
**Checklist:**

Add entry to changelog for initial PHP 8.1 changes

---

.no-header.php-cs-fixer.dist.php
.php-cs-fixer.dist.php

Apply NoCodeSeparatorCommentFixer

---

system/Session/Handlers/RedisHandler.php

Fix variable variable `$$id` in RedisHandler

---

system/BaseModel.php
system/Database/Postgre/Builder.php
system/Database/SQLSRV/Builder.php
tests/system/Models/ReplaceModelTest.php

Fixes #4624 
Supersedes and closes #4662 
**Checklist:**

Update 'updated_at' when enabled in replace()

---

.github/workflows/deploy-apidocs.yml

To prevent parsing errors from `nikic/php-parser` (fix in v4.12 present in v3.1.1)
**Checklist:**

Update to phpdocumentor v3.1.1

---

user_guide_src/source/installation/upgrade_414.rst

docs: fix upgrade_414 format

---

.github/workflows/test-phpunit.yml
admin/framework/composer.json
composer.json

In latest laminas-escaper 2.9.0, `laminas/laminas-zendframework-bridge` no longer required, so no need to tweak test github action.
https://github.com/laminas/laminas-escaper/compare/2.8.0...2.9.0
**Checklist:**

Update to latest laminas-escaper 2.9.0

---

user_guide_src/source/models/entities.rst

- use `::class` keyword
**Checklist:**

docs: small fixes for entities

---

user_guide_src/source/changelogs/index.rst
user_guide_src/source/changelogs/v4.1.5.rst
user_guide_src/source/installation/upgrade_415.rst
user_guide_src/source/installation/upgrading.rst

The next version will be 4.1.5.
See https://github.com/codeigniter4/CodeIgniter4/pull/5021#issuecomment-917624179
**Checklist:**

docs: rename v4.2.0 to v4.1.5

---

rector.php

Rector 0.11.53 already handle skip `RecastingRemovalRector` on class that has __get() and __set().
**Checklist:**

[Rector] Clean up rector skip config

---

user_guide_src/source/database/query_builder.rst

- fix query_builder RST format
Before:
After:
**Checklist:**

docs: fix query_builder RST format

---

user_guide_src/source/testing/controllers.rst
user_guide_src/source/testing/feature.rst
user_guide_src/source/testing/overview.rst
user_guide_src/source/testing/response.rst

docs: fix indentation for testing 

---

user_guide_src/source/outgoing/api_responses.rst

- fix indentation
- improve method list
- fix description
before:
after:
**Checklist:**

docs: fix api responses

---

admin/pre-commit

`php-cs-fixer fix --using-cache=no` takes long time to commit.
I don't know why we must use `--using-cache=no`.
**Checklist:**

Remove --using-cache=no from php-cs-fixer in pre-commit

---

system/CodeIgniter.php
tests/system/CodeIgniterTest.php

`storePreviousURL()` allows `redirect()->back()` to return to the "previous page"; however, there are a few instances where this can create an un-routable situation when a `DownloadResponse` is returned, or (very rarely) a loop when a `RedirectResponse` is encountered. This PR adds exemptions for those cases.
**Checklist:**

Previous Responses

---

user_guide_src/source/cli/cli_library.rst

- fix sample code and its output
before:
after:
**Checklist:**

docs: fix cli library

---

rector.php
system/View/Cell.php

Simplify `is_array` and `empty` functions combination into a simple identical check for an empty array with `SimplifyEmptyArrayCheckRector` rector rule.
**Checklist:**

[Rector] Apply Rector: SimplifyEmptyArrayCheckRector

---

system/Router/Router.php
tests/system/Router/RouterTest.php

If trailing slash is forced via apache or nginx the router will be unable to find the appropriate route. The router will try to match path from request uri with trailing slash but it is impossible to define such route in the route collection since slash is used as separator. 
This changes the way request uri is handled so that trailing slash is removed at the end which enables the router to handle the url in both cases with or without trailing slash 
**Checklist:**

IncomingRequest - Trim trailing slash

---

system/Database/Query.php
tests/system/Database/BaseQueryTest.php

Fix query binding with two colons in query

---

system/Database/Forge.php
tests/system/Database/Forge/CreateTableTest.php

Fixed the problem that `_createTable` does not take into account that it returns true.
If `_createTable` returns true, then `createTable` will return true.
This occurs only when the `createTableIfStr` property is false in the Forge class.
I had trouble with this behavior when I was creating the OCI8 driver.
see: https://github.com/codeigniter4/CodeIgniter4/pull/2487#discussion_r716022511
**Checklist:**

Fixed the problem that _createTable does not take into account that it returns true.

---

admin/css/debug-toolbar/_theme-dark.scss
admin/css/debug-toolbar/_theme-light.scss
system/Debug/Toolbar/Views/toolbar.css

Change shade of orange, from matt orange (#FDC894) to glossy orange (#DD8615), as the current color doesn't have enough contrast with background. Before and after:
I made the same change to dark theme, as I think it's also prettier, and because currently both light and dark themes use the same shades of *-orange at the same places, so better keep this consistency. Before and after:
I made this PR because on Pale Moon browser these texts are less bold, and see how the current color is barely readable:

Adjust orange color in debug toolbar

---

user_guide_src/README.rst
user_guide_src/source/helpers/test_helper.rst
user_guide_src/source/helpers/url_helper.rst
user_guide_src/source/incoming/request.rst
user_guide_src/source/incoming/routing.rst
user_guide_src/source/installation/upgrade_412.rst
user_guide_src/source/libraries/throttler.rst

- replace tabs with spaces
Finally, tabs are gone from the RST file.
```sh-session
$ find user_guide_src/ -name '*.rst' | xargs grep "\t"
$ 
```
**Checklist:**

docs: replace tabs with spaces

---

tests/system/Cache/Handlers/MemcachedHandlerTest.php

- fix `MemcachedHandlerTest::testGetMetaData()` rarely fails
```
1) CodeIgniter\Cache\Handlers\MemcachedHandlerTest::testGetMetaData
Failed asserting that 61 is equal to 60 or is less than 60.
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Cache/Handlers/MemcachedHandlerTest.php:194
```
https://github.com/kenjis/CodeIgniter4/runs/3726773162?check_suite_focus=true
**Checklist:**

Fix MemcachedHandlerTest::testGetMetaData()

---

CONTRIBUTING.md

Fix borken link styleguide.md in CONTRIBUTING.md
Fixed broken link, file extension changed from .rst to .md, styleguide.md in CONTRIBUTING.md.
**Checklist:**

docs: fix link styleguide.md in CONTRIBUTING.md

---

user_guide_src/source/tutorial/index.rst

Fix Google.com to DuckDuckGo.com
Fix Google.com to DuckDuckGo.com, how is the code running. https://github.com/codeigniter4/CodeIgniter4/blob/7b7d251f898ddb8afcf3fcf0c7d498d448844c19/app/Views/errors/html/error_exception.php#L25
**Checklist:**

docs: fix Google.com to DuckDuckGo.com

---

system/Debug/Toolbar/Views/toolbar.css

Follow-up to #5136.
I didn't notice the color was present at several places of the precompiled CSS…
(we have the regular mode, the Windows dark theme, and the light/dark switch button, for a total of 4 occurrences of the color)

Fix color not updated in several places of the precompiled CSS

---

system/Model.php
tests/system/Models/AffectedRowsTest.php

Fixes #5137.
An error occurs when a method of the Database\Connection class returns a falsy value.
**Checklist:**

Fix `Model::__call` throwing `BadMethodCallException` on empty results

---

system/Validation/Validation.php
tests/_support/Validation/TestRules.php
tests/system/Validation/ValidationTest.php

For example:
```json
{
"configuration" :
{
"consumerKey1" : "aa",
"consumerSecret" : "bb",
"oauthToken" : "cc",
"oauthTokenSecret" : "dd"
}
}
```
**Checklist:**

Error when value is an object - validating api data

---

system/Debug/Toolbar.php
system/Debug/Toolbar/Views/toolbar.tpl.php
system/Debug/Toolbar/Views/toolbarloader.js.php

Fixes #5097 
The truncated styles would actually not pose a problem because in `toolbarloader.js.php` the styles and scripts from `toolbarContainer` is dynamically copied to the style and script in the `head`. After dynamically copying, those should be supposedly removed from `toolbarContainer` thru `responseText.substr`. This works well until the last copying of the last style where the removal was "misdirected".
To check that those styles would be redundant if we let it stay is to see that the timeline bars still got styled (in orange bars of varying lengths). Right-clicking on 'Inspect element' you would be that those bars have the class `.debug-bar-timeline-**` styles with the definition at the bottom.
If any of @rramsey or @kenjis can test this ?
**Checklist:**

Fix debugbar styles printing

---

system/BaseModel.php
system/Database/BaseBuilder.php
system/Model.php
tests/system/Database/Builder/InsertTest.php
tests/system/Database/Builder/UpdateTest.php
user_guide_src/source/changelogs/v4.1.5.rst
user_guide_src/source/database/query_builder.rst

Fixed a problem where identifiers were not escaped in the set, setUpdateBatch, and insertBatch methods. 
I decided that there was no case where the column name in the set clause did not need to be escaped, so I turned off the unescaping process.
The same goes for the table name when inserting.
see: https://github.com/codeigniter4/CodeIgniter4/pull/2487#discussion_r716012806
**Checklist:**

Always escape identifiers in the set(), setUpdateBatch(), and insertBatch()

---

system/Database/Query.php

Highlighting wasn't working for multiple-word terms, as they were searched in the SQL string with nbsp entities instead of regular spaces.
This code could be optimized, though it's not crucial as it's a debug function.

Fix highlighting in database debug toolbar

---

phpstan.neon.dist
system/Database/Forge.php
tests/system/Database/Forge/DropForeignKeyTest.php

Fixed an issue where the dropForeginKey method would execute an empty query when the dropConstraintStr property was empty.
https://github.com/codeigniter4/CodeIgniter4/blob/56add793a949c5021a56b81f6ff7019ac1719f69/system/Database/Forge.php#L424-L430
`sprintf` returns an empty string even if the first argument is null, but it verifies that it is false now.
Fixed, as it is an IF that will never be reached.
**Checklist:**

Fixed an issue where the dropForeginKey method would execute an empty query when the dropConstraintStr property was empty.

---

app/Config/Feature.php
phpstan.neon.dist
system/CodeIgniter.php
system/Filters/Filters.php
system/Router/RouteCollection.php
system/Router/RouteCollectionInterface.php
system/Router/Router.php
tests/system/CodeIgniterTest.php
tests/system/Router/RouterTest.php
user_guide_src/source/incoming/routing.rst
user_guide_src/source/installation/upgrade_415.rst

Supersedes #5108
- add multiple filters for a route (disabled by default)
- add `Config\Feature` class for enabling *multiple filters*
- add classname filter
- fix doc comments
CI4 follows semantic versioning, so changes that break backward compatibility are not allowed without major version up.
The *multiple filters* feature breaks backward compatibility, because it uses new methods.
Therefore, it is disabled by default and users can enable it in the configuration class if they want to use it.
Users who want to use the new features will be able to set themselves up for disruptive changes.
Users of existing CI4 applications will be backward compatible through updates.
The code will be more complex, but I think it will be less complex than adding code that forces the API to …

Multiple filters for a route and classname filter

---

system/BaseModel.php
tests/system/Models/PaginateModelTest.php

An invalid page lead to an exception when using the model paginate function.
page::store validates the page but it doesnt update the page used in the model.
So we need to read the page value again after calling pager::store in paginate

(Paging) Ensure page validity

---

system/Debug/Toolbar/Collectors/Database.php

Fixes #5160 
The debug toolbar's database tab showed X queries 0 connections - the count of used connections was not reported.
The change counts the unique (name) connections while iterating through the queries, and saves them in a new static variable. Then this variable is used to display the count.
**Checklist:**

Fix debug toolbar db connection count

---

system/Database/BaseConnection.php
system/Database/Postgre/Connection.php

The process of getting the prefix of the db access function was extracted to the method.
It is incorrect that this is in the parent class, BaseConnection.
This is because the parent class will behave as if it knows the implementation of the child class.
With this code, there will be a lack of coverage when trying to add a new driver as shown below.
https://github.com/codeigniter4/CodeIgniter4/pull/2487#discussion_r720942310
**Checklist:**

Extract method to get prefix for DB access function

---

system/Config/BaseConfig.php
tests/system/Config/BaseConfigTest.php
tests/system/Config/DotEnvTest.php
tests/system/Config/fixtures/.env
tests/system/Config/fixtures/SimpleConfig.php
user_guide_src/source/general/configuration.rst

You can use both as environment variable name:
- `database.default.hostname` (now) - looking for it first
- `database_default_hostname` (new) - if not found, looking for it
See #4026
**Checklist:**

feat: `_` can be used as separators in environment variable names

---

contributing/guidelines.rst
contributing/internals.rst

-  fix 404 links to sytle guide
**Checklist:**

docs: fix 404 links to sytle guide

---

.no-header.php-cs-fixer.dist.php
.php-cs-fixer.dist.php

Since `coding-standard` v1.2.0, these overrides are no longer needed
**Checklist:**

Cleanup php-cs-fixer config files

---

.no-header.php-cs-fixer.dist.php
admin/starter/builds

Optimize `builds`

---

tests/system/CodeIgniterTest.php
tests/system/CommonHelperTest.php
tests/system/Config/ServicesTest.php
tests/system/Filters/FiltersTest.php
tests/system/HTTP/CURLRequestTest.php
tests/system/HTTP/URITest.php
tests/system/RESTful/ResourceControllerTest.php
tests/system/RESTful/ResourcePresenterTest.php

...with `CIUnitTestCase`'s `resetServices()` method
**Checklist:**

Replace explicit calls to `Services::reset()` in tests

---

system/Database/BaseBuilder.php
system/Database/BaseConnection.php

- make PHP 8.1 compatible
- see https://github.com/codeigniter4/CodeIgniter4/pull/4883#issuecomment-955622746
See "Usage of static Variables in Inherited Methods"
https://www.php.net/manual/en/migration81.incompatible.php
**Checklist:**

Remove static variables for PHP 8.1

---

system/HTTP/CURLRequest.php
tests/system/HTTP/CURLRequestTest.php

Fixes #4826
- reset unneeded headers
- reset unneeded configs
**Checklist:**

Fix CURLRequest extra headers

---

tests/system/CommonSingleServiceTest.php

Speed up `CommonSingleServiceTest`

---

system/HTTP/CLIRequest.php
system/HTTP/CURLRequest.php
system/Router/RouteCollection.php

Related to #4883 and follow-up to #5005
**Checklist:**

Replace usage of `FILTER_SANITIZE_STRING`

---

.no-header.php-cs-fixer.dist.php
.php-cs-fixer.dist.php
tests/_support/Publishers/TestPublisher.php
tests/system/Cache/Handlers/FileHandlerTest.php
tests/system/Cache/Handlers/MemcachedHandlerTest.php
tests/system/Cache/Handlers/PredisHandlerTest.php
tests/system/Cache/Handlers/RedisHandlerTest.php

Enables the rule to be consistent in ordering the class's properties and methods.
```console
$ vendor/bin/php-cs-fixer describe ordered_class_elements
Description of ordered_class_elements rule.
Orders the elements of classes/interfaces/traits.
* order (a subset of ['use_trait', 'public', 'protected', 'private', 'constant', 'constant_public', 'constant_protected', 'constant_private', 'property', 'property_static', 'property_public', 'property_protected', 'property_private', 'property_public_readonly', 'property_protected_readonly', 'property_private_readonly', 'property_public_static', 'property_protected_static', 'property_private_static', 'method', 'method_abstract', 'method_static', 'method_public', 'method_protected', …
```

Enable `ordered_class_elements` rule

---

system/Helpers/number_helper.php

The logic currently is too difficult to digest.
**Checklist:**

Simplify logic of `number_to_roman` function

---

composer.json
rector.php
utils/Rector/UnderscoreToCamelCaseVariableNameRector.php

Cherry-picked from https://github.com/codeigniter4/CodeIgniter4/pull/5269
**Checklist:**

[Rector] Refactor UnderscoreToCamelCaseVariableNameRector so no longer require symplify/package-builder

---

tests/system/Filters/FiltersTest.php

Refactor FiltersTest.php

---

user_guide_src/source/helpers/html_helper.rst

docs: fix html_helper.rst

---

user_guide_src/source/libraries/security.rst

This is a basic config item, so it is better to have it at the beginning.
**Checklist:**

docs: move CSRF Protection Methods section up

---

system/Database/BasePreparedQuery.php
tests/system/Database/Live/PreparedQueryTest.php

In PHP 8.1, Postgres' result is now a `PgSql\Result` object which is a [fully opaque class](https://www.php.net/manual/en/class.pgsql-result.php). This class has no methods so calling on `BasePreparedQuery::close()` will now fail because it calls the `close` method on the object result. Also, this refactors the `PreparedQueryTest` to call the close method on tearDown.
Related: #4883 
**Checklist:**

Fix compatibility of `PgSql\Result` on closing the result instance

---

system/Database/BaseResult.php
system/Database/Postgre/Result.php

As of PHP 8.1, the result resource in Postgres is now a `PgSql\Result` object, so calling `is_resource` will naturally fail now. The 8.1 migration guide suggests using a check against false.
https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.resource2object
Related: #4883 
**Checklist:**

Fix compatibility of Postgres result for PHP 8.1

---

system/Validation/FormatRules.php
tests/system/Validation/FormatRulesTest.php
user_guide_src/source/libraries/validation.rst

Supersedes #4658 
Fixes #3156
The current `valid_url` is too loose.
I referred to https://github.com/codeigniter4/CodeIgniter4/pull/4658#issuecomment-838524347
**Checklist:**

feat: add valid_url_strict rule

---

system/CodeIgniter.php
system/Filters/Filters.php
tests/system/Filters/FiltersTest.php

fix: module filters are not discovered when using route filters

---

user_guide_src/source/libraries/caching.rst

- fix RST format 
Before:
After:
**Checklist:**

docs: fix RST format in caching.rst

---

system/CodeIgniter.php
user_guide_src/source/changelogs/v4.1.5.rst
user_guide_src/source/changelogs/v4.1.6.rst
user_guide_src/source/conf.py
user_guide_src/source/installation/upgrade_405.rst
user_guide_src/source/installation/upgrade_412.rst
user_guide_src/source/installation/upgrade_415.rst
user_guide_src/source/installation/upgrading.rst

Updates changelog and version references for 4.1.5.

Prep for 4.1.5 release

---

app/Config/Toolbar.php
system/Debug/Toolbar.php

When there are a lot of vars being passed to the view for example array of entities with lots of parameters in each entity, var data can get very big and will consume a lot of memory.  A new parameter in toolbar config is introduced here to that collection of var data can be disabled.
**Checklist:**

Toolbar - Make it possible to turn off var data collection

---

.github/release.yml
admin/RELEASE.md
contributing/pull_request.md
contributing/workflow.md

I propose that labeling PRs and use GitHub auto-generated release note for generating `CHANGELOG.md`.
See https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
**Checklist:**

chore: add .github/release.yml

---

user_guide_src/source/dbmgmt/migration.rst

- param type is not correct
**Checklist:**

docs: fix MigrationRunner::regress() Class Reference

---

system/Autoloader/FileLocator.php
tests/system/Autoloader/FileLocatorTest.php

`FileLocator` cannot find files in sub-namespaces of the same vendor.
For example, when you have `CodeIgniter` and `CodeIgniter\Devkit`.
**Checklist:**

fix: FileLocator cannot find files in sub-namespaces of the same vendor

---

user_guide_src/source/incoming/routing.rst

- There is no `$collection` in `app/Config/Routes.php`.
**Checklist:**

docs: fix sample code variable names in routing.rst 

---

system/Debug/Exceptions.php

Follow-up: #4550
If upgraded users do not update `Config\Exceptions`, the following error occurs:
Uncaught ErrorException: Undefined property: Config\Exceptions::$sensitiveDataInTrace
See https://forum.codeigniter.com/thread-80522.html
**Checklist:**

fix: add a workaround for upgraded users who do not update Config\Exceptions

---

tests/system/Cache/Handlers/MemcachedHandlerTest.php
tests/system/Cache/Handlers/RedisHandlerTest.php
tests/system/Images/BaseHandlerTest.php
tests/system/Images/GDHandlerTest.php
tests/system/Images/ImageMagickHandlerTest.php

- add `$this->markTestSkipped()` when extension not loaded
- If extension is not loaded, you see Error surely
- remove unneeded `return` after `$this->markTestSkipped()`
**Checklist:**

test: add $this->markTestSkipped() when extension not loaded

---

user_guide_src/source/testing/debugging.rst

- tthe way to enable Kint seems out-of-dated
**Checklist:**

docs: fix debugging.rst

---

rector.php
tests/system/API/ResponseTraitTest.php
tests/system/CLI/ConsoleTest.php
tests/system/CommonSingleServiceTest.php
tests/system/Config/ConfigTest.php
tests/system/Config/ServicesTest.php
tests/system/Cookie/CookieTest.php
tests/system/Database/Live/ConnectTest.php
tests/system/Database/Live/DbUtilsTest.php
tests/system/Database/Live/GetTest.php
tests/system/Database/Live/PretendTest.php
tests/system/Database/Live/SQLite/AlterTableTest.php
tests/system/Filters/FiltersTest.php
tests/system/HTTP/IncomingRequestTest.php
tests/system/HTTP/ResponseTest.php
tests/system/I18n/TimeTest.php
tests/system/Images/BaseHandlerTest.php
tests/system/Images/ImageMagickHandlerTest.php
tests/system/Language/LanguageTest.php
tests/system/Log/LoggerTest.php
tests/system/Models/InsertModelTest.php
tests/system/Models/MiscellaneousModelTest.php
tests/system/Models/UpdateModelTest.php
tests/system/Models/ValidationModelTest.php
tests/system/Test/FeatureTestTraitTest.php
tests/system/Test/TestResponseTest.php
tests/system/View/ViewTest.php

- to fix assertion method like [AssertCompareToSpecificMethodRector](https://github.com/rectorphp/rector-phpunit/blob/main/docs/rector_rules_overview.md#assertcomparetospecificmethodrector)
See https://github.com/rectorphp/rector-phpunit#rector-rules-for-phpunit
**Checklist:**

[Rector] add PHPUnitSetList::PHPUNIT_SPECIFIC_METHOD

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/WhereTest.php

Prerequisite for #5138.
The main fix is commit https://github.com/vlakoff/CodeIgniter4/commit/223ca28400a95594490052b032e1a921237138fb.

Do not inappropriately register bind when the value is a closure

---

tests/system/Entity/EntityTest.php
tests/system/Session/SessionTest.php

- refactor `isset()` tests
- fix `assert*()` argument order
- separete Arrange, Act, and Assert
- to remove skip of `AssertIssetToSpecificMethodRector::class` https://github.com/codeigniter4/CodeIgniter4/pull/5320#discussion_r748949988
**Checklist:**

test: refactor Entity and Session test

---

user_guide_src/source/concepts/structure.rst

- there is no `docs` directory
- See https://forum.codeigniter.com/thread-79365-post-387929.html#pid387929
**Checklist:**

docs: fix structure.rst

---

system/Debug/Toolbar/Collectors/Database.php
system/Debug/Toolbar/Views/_database.tpl
system/Debug/Toolbar/Views/toolbar.css
system/Debug/Toolbar/Views/toolbar.js
user_guide_src/source/changelogs/v4.1.6.rst

Added backtrace information and the file:line of each query into the Database pane of the debug toolbar. The backtrace is hidden by default but opens by clicking on the row.

Display file:line and trace information to database queries in debug toolbar

---

user_guide_src/source/testing/controllers.rst
user_guide_src/source/testing/response.rst

docs: fix testing controllers

---

.github/scripts/deploy-framework

chore: fix deploy-framework script to copy `tests` directory

---

.github/ISSUE_TEMPLATE/bug_report.yml

- add search example
- add codeigniter installation
**Checklist:**

chore: improve Issue Form

---

system/HTTP/IncomingRequest.php
user_guide_src/source/concepts/http.rst
user_guide_src/source/incoming/incomingrequest.rst

- don't use `IncomingRequest::$uri` in the user guide. See #5344
**Checklist:**

docs: don't use `IncomingRequest::$uri`

---

app/Views/errors/html/error_exception.php
system/Common.php
tests/system/HTTP/IncomingRequestTest.php
tests/system/HTTP/URITest.php

See #5344
There is no `withUri()` method in the Request, can't replace the code like:
```php
$request->uri = new URI('http://example.com/assets/image.jpg');
```
**Checklist:**

refactor: replace $request->uri with $request->getUri()

---

system/Database/BaseConnection.php
tests/system/Database/BaseQueryTest.php
tests/system/Database/Live/EscapeTest.php

Fix db escape negative integers

---

user_guide_src/source/general/helpers.rst

- fix incorrect namespace in sample code
**Checklist:**

docs: fix helpers.rst 

---

system/HTTP/CLIRequest.php
tests/system/HTTP/CLIRequestTest.php

Fix: remove incorrect processing of CLI params

---

user_guide_src/source/concepts/security.rst
user_guide_src/source/concepts/structure.rst
user_guide_src/source/incoming/routing.rst
user_guide_src/source/installation/installing_manual.rst
user_guide_src/source/installation/upgrade_415.rst
user_guide_src/source/libraries/curlrequest.rst
user_guide_src/source/testing/controllers.rst
user_guide_src/source/testing/feature.rst
user_guide_src/source/testing/overview.rst
user_guide_src/source/testing/response.rst

- fix page links
- update external URLs
**Checklist:**

docs: fix links

---

system/Database/BaseConnection.php
tests/system/Database/Builder/AliasTest.php

fix: table alias is prefixed when LIKE clause

---

system/Helpers/array_helper.php
tests/system/Helpers/ArrayHelperTest.php

fix: `dot_array_search()` unexpected array structure causes Type Error

---

user_guide_src/source/outgoing/views.rst

docs: fix views.rst

---

system/HTTP/Files/UploadedFile.php
tests/system/HTTP/Files/FileMovingTest.php

Supersedes and closes #5290
- if `move_uploaded_file()` returns `false` without warning, `move()` and `hasMoved()` returns `true`
> https://www.php.net/manual/en/function.move-uploaded-file.php#refsect1-function.move-uploaded-file-returnvalues
> Return Values ¶
>
> Returns true on success.
>
> **If from is not a valid upload file, then no action will occur, and move_uploaded_file() will return false.**
>
> If from is a valid upload file, but cannot be moved for some reason, no action will occur, and move_uploaded_file() will return false. **Additionally, a warning will be issued.**
**Checklist:**

fix: UploadedFile::move() may return incorrect value

---

system/Database/Query.php
tests/system/Database/BaseQueryTest.php

To determine if binds are simple or named, rather than trying to deduce it from the SQL string, which is the source of many errors (for example see #5114, and all the issues it links to), simply look at the `$binds` array. If it's an indexed array, the binds are simple, if it's an associative array, the binds are named.
Note that if #5127 is merged before, this PR will need a slight rebasing before merging.

Determine if binds are simple or named by looking at the $binds array

---

app/Config/Filters.php
system/Filters/InvalidChars.php
system/Security/Exceptions/SecurityException.php
tests/system/Filters/InvalidCharsTest.php
user_guide_src/source/incoming/filters.rst

- add a filter to prevent attacks with malformed character encodings and control characters (null byte)
**Checklist:**

feat: add filter to check invalid chars in user input

---

system/Images/Handlers/GDHandler.php

Related to #4883
**Checklist:**

Fix precision loss deprecation on float to int conversion

---

system/Database/Query.php

As discussed on https://github.com/codeigniter4/CodeIgniter4/pull/5138#issuecomment-976864356 onwards, `$this->binds` is not expected to be something else than an array.
The only possibility for the protected property `$this->binds` to be something else than an array, would be that the user extends the Query class and assigns to `$this->binds` from a new method. Such non-array value is not expected nor supported, and would probably trigger errors at other places of the code.

Remove unneeded cast to array

---

user_guide_src/source/concepts/autoloader.rst
user_guide_src/source/general/logging.rst
user_guide_src/source/general/modules.rst
user_guide_src/source/installation/upgrade_4xx.rst

- unify notation
**Checklist:**

docs: replace `PSR*` with `PSR-*`

---

user_guide_src/source/outgoing/localization.rst

- update sample lang file names and lang keys
- remove note
**Checklist:**

docs: fix localization.rst

---

user_guide_src/source/concepts/factories.rst
user_guide_src/source/general/modules.rst

See  [#5356](https://github.com/codeigniter4/CodeIgniter4/issues/5356#issuecomment-974646662)
- add about `config()` `preferApp` and `Registrars`
**Checklist:**

docs: add about Config in Modules

---

app/Config/Mimes.php
system/CLI/CLI.php
system/Database/BaseUtils.php
system/Database/Forge.php
system/Database/Postgre/Connection.php
system/Filters/Filters.php
system/HTTP/CLIRequest.php
system/HTTP/CURLRequest.php
system/HTTP/ResponseTrait.php
system/I18n/Time.php
system/Security/Security.php
system/Validation/FormatRules.php
system/Validation/Rules.php
system/Validation/Validation.php
tests/system/I18n/TimeTest.php

Related to #4883
**Checklist:**

Fix deprecated usage of `null` on `string` params of internal functions

---

user_guide_src/source/database/query_builder.rst

- fix incorrect explanation on `getCompiledInsert()`
**Checklist:**

docs: fix getCompiledInsert() explanation in query_builder.rst

---

rector.php
tests/system/HTTP/ResponseTest.php
tests/system/View/ViewTest.php

Follow-up: #5320
- use `assertStringContainsString` instead of `strpos()`
**Checklist:**

[Rector] add PHPUnitSetList::PHPUNIT_80

---

user_guide_src/source/general/modules.rst
user_guide_src/source/incoming/routing.rst

- add reference from Module Routes to Route processing queue
**Checklist:**

docs: improve Module Routes

---

system/HTTP/IncomingRequest.php
system/Validation/FormatRules.php
system/Validation/Rules.php

#4883 
After merge of latest changes, there seems to be new deprecations detected. So fixing again.
**Checklist:**

Additional fix for deprecated `null` usage

---

.github/workflows/test-phpunit.yml

**Description:**
PHP 8.1 will be released in a few months and we should ensure the framework is compatible by then.
**Detected issues:**
**Checklist:**

Add support for PHP 8.1

---

system/Debug/Toolbar/Collectors/Database.php

fix: undefined constant `VENDORPATH` in `Debug\Toolbar\Collectors\Database`

---

system/Database/BaseBuilder.php
system/Database/BaseConnection.php
user_guide_src/source/changelogs/v4.1.6.rst

Fixes #4457
- make sure `$this->tableName` is string
`$this->tableName` is used only in `BaseBuilder::getTable()`.
`BaseBuilder::getTable()` is used only in `Model::builder()`:
https://github.com/codeigniter4/CodeIgniter4/blob/b8fe16d2ff708971693a5e3325b74447ffb93fdd/system/Model.php#L524
`$table` or `$this->table` in the `Model` is a single table name without an alias.
So the above code is just to make sure that `$table` and the Builder's table name are the same or not.
If these are the same table, it returns existing `$this->builder`.
In other words, if the Builder's table name is not a single table, these are always not the same.
Therefore `BaseBuilder::getTable()` does not have to return array or multiple table string like `'tableA, tableB'`.
Returning empty string is …

fix: Incorrect type `BaseBuilder::$tableName`

---

system/HTTP/IncomingRequest.php
tests/system/HTTP/IncomingRequestTest.php

fix: `IncomingRequest::getJsonVar()` may cause TypeError

---

user_guide_src/source/general/managing_apps.rst

- fix application folder name
- decorate file paths with **
**Checklist:**

docs: fix managing_apps.rst

---

user_guide_src/source/installation/installing_composer.rst
user_guide_src/source/libraries/caching.rst
user_guide_src/source/tutorial/index.rst

- add command prompt `>` before `composer`
**Checklist:**

docs: add command prompt `>` before `composer`

---

user_guide_src/source/cli/cli_generators.rst
user_guide_src/source/dbmgmt/forge.rst
user_guide_src/source/installation/running.rst
user_guide_src/source/installation/troubleshooting.rst
user_guide_src/source/tutorial/index.rst
user_guide_src/source/tutorial/static_pages.rst

- add command prompt `>` before `php spark`
**Checklist:**

docs: add command prompt `>` before `php spark`

---

admin/module/tests/database/ExampleDatabaseTest.php
admin/module/tests/session/ExampleSessionTest.php
admin/starter/tests/database/ExampleDatabaseTest.php
admin/starter/tests/session/ExampleSessionTest.php

- fix example test code for starter and module
Right after installing CI4, tests fail:
```
$ composer create-project codeigniter4/appstarter ci4
$ cd ci4
$ composer test
> phpunit
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.
FEE..                                                               5 / 5 (100%)
Time: 00:00.584, Memory: 26.00 MB
There were 2 errors:
1) ExampleDatabaseTest::testSoftDeleteLeavesRow
ErrorException: Attempt to read property "id" on null
/Users/kenji/tmp/ci4/tests/database/ExampleDatabaseTest.php:32
2) ExampleSessionTest::testSessionSimple
Error: Call to a member function set() on array
/Users/kenji/tmp/ci4/tests/session/ExampleSessionTest.php:12
--
1) ExampleDatabaseTest::testModelFindAll
Failed asserting that actual …
```

chore: fix example test code for appstarter and module

---

user_guide_src/source/general/ajax.rst
user_guide_src/source/general/caching.rst
user_guide_src/source/general/environments.rst
user_guide_src/source/general/managing_apps.rst
user_guide_src/source/general/urls.rst

docs: add TOC to general pages

---

user_guide_src/source/installation/upgrade_migrations.rst
user_guide_src/source/installation/upgrade_models.rst
user_guide_src/source/installation/upgrade_pagination.rst
user_guide_src/source/installation/upgrade_view_parser.rst
user_guide_src/source/installation/upgrade_views.rst
user_guide_src/source/libraries/pagination.rst
user_guide_src/source/libraries/validation.rst
user_guide_src/source/outgoing/alternative_php.rst
user_guide_src/source/tutorial/news_section.rst

- remove unneeded `;`
- remove space before `:`
- align `=` position
**Checklist:**

docs: fix coding style

---

user_guide_src/source/libraries/files.rst

docs: improve files.rst

---

user_guide_src/source/libraries/uploaded_files.rst
user_guide_src/source/libraries/validation.rst

- add file upload sample code like CI3
- fix coding style of sample code
- add note about Validation rules
- decoration
**Checklist:**

docs: improve uploaded_files.rst

---

user_guide_src/source/incoming/restful.rst

- decorate keywords in source code with ` `` `
- improve explanation for `except` option
**Checklist:**

docs: improve restful.rst

---

CHANGELOG.md

- auto-generate GitHub release note
- remove unneeded PR (coding style, rector/phpstan, github workflow) from it
I don't know why `.github/release.yml` does not work.
**Checklist:**

docs: changelog 4.1.4

---

user_guide_src/source/installation/upgrade_emails.rst
user_guide_src/source/libraries/email.rst

docs: fix 404 link in upgrade_emails.rst

---

user_guide_src/source/dbmgmt/forge.rst

-  add space after `,` in sample code
**Checklist:**

docs: fix coding style in dbmgmt/forge.rst

---

system/Model.php

When `useAutoIncrement` is disabled, `countAllResults()` is called, even if `$data` does not have id value.
You'll see the query like the following:
```sql
SELECT COUNT(*) AS `numrows` FROM `news` WHERE `id` IS NULL
```
```php
<?php
function f1() {
return false && false ? true : 'a';
}
function f2() {
return false && (false ? true : 'a');
}
var_dump(f1()); // "a"
var_dump(f2()); // false
```
**Checklist:**

fix: Model::save() may call unneeded countAllResults()

---

user_guide_src/source/changelogs/v4.1.5.rst
user_guide_src/source/dbmgmt/forge.rst
user_guide_src/source/incoming/routing.rst
user_guide_src/source/installation/upgrade_415.rst
user_guide_src/source/libraries/security.rst

- The current user guide lacks links to relevant information.
- The only way to know what's new in the new version is to look at Changelog, but it doesn't show specific usage.
- This PR shows you how to add links to related information.
See https://forum.codeigniter.com/thread-80701-post-392042.html#pid392042
**Checklist:**

docs: add or improve links to other sections

---

system/Validation/Validation.php
tests/system/Validation/FormatRulesTest.php
tests/system/Validation/ValidationTest.php
user_guide_src/source/changelogs/v4.1.6.rst
user_guide_src/source/installation/upgrade_416.rst
user_guide_src/source/installation/upgrading.rst

Supersedes #5402
Fixes #5368
- separate validation process of multiple field and single field
**Checklist:**

fix: Validation cannot handle array item

---

system/Database/MySQLi/Connection.php

Fixes #5423
> A string is a sequence of bytes or characters, enclosed within either single quote (') or double quote (") characters. 
> ...
> If the ANSI_QUOTES SQL mode is enabled, string literals can be quoted only within single quotation marks because a string quoted within double quotation marks is interpreted as an identifier. 
https://dev.mysql.com/doc/refman/8.0/en/string-literals.html
> ANSI_QUOTES
> Treat " as an identifier quote character (like the `` ` `` quote character) and not as a string quote character. You can still use ` to quote identifiers with this mode enabled. With ANSI_QUOTES enabled, you cannot use double quotation marks to quote literal strings because they are interpreted as identifiers. …

fix: errors when MariaDB/MySQL has `ANSI_QUOTES` enabled

---

app/Config/Filters.php
system/Filters/SecureHeaders.php
tests/system/Filters/SecureHeadersTest.php
user_guide_src/source/incoming/filters.rst

- add filter that add common security related filters to response object
**Checklist:**

feat: add SecureHeaders filter

---

user_guide_src/source/libraries/sessions.rst

- `$session->destroy()` will destroy the session and log out the user. 
See https://forum.codeigniter.com/thread-80718.html
**Checklist:**

docs: fix wrong sample code in sessions.rst

---

system/Common.php

fix: `is_cli()` returns `true` when `$_SERVER['HTTP_USER_AGENT']` is missing

---

system/Database/MySQLi/Connection.php

fix: `MySQLi\Connection::_foreignKeyData()` may return duplicated rows

---

system/Helpers/number_helper.php
tests/system/Helpers/NumberHelperTest.php
user_guide_src/source/helpers/number_helper.rst

Fixes #5452
Follow-up #4883
**Checklist:**

fix: `number_to_currency()` error on PHP 8.1

---

system/Common.php
user_guide_src/source/general/common_functions.rst

`null` is not `$context`
see:
https://github.com/codeigniter4/CodeIgniter4/blob/b5478b352bc6dc4b993651c41c7e157509d797cd/system/Common.php#L406-L410
**Checklist:**

update docs about `esc()`

---

system/Test/bootstrap.php
system/bootstrap.php
user_guide_src/source/general/managing_apps.rst

- When using multiple apps, `vendor/` is not `ROOTPATH/vendor/`.
See https://forum.codeigniter.com/thread-80732.html
**Checklist:**

fix: VENDORPATH definition

---

user_guide_src/source/incoming/content_negotiation.rst

- decorate variable name with ` `` `
**Checklist:**

docs: improve text decoration in content_negotiation.rst

---

user_guide_src/source/general/common_functions.rst
user_guide_src/source/testing/debugging.rst

- fix incorrect explanation for `saveData`
- https://github.com/codeigniter4/CodeIgniter4/blob/c6dbfb4953f7b16360bda58ff44c2c39b265d1c3/system/Common.php#L1087
- https://github.com/codeigniter4/CodeIgniter4/blob/c6dbfb4953f7b16360bda58ff44c2c39b265d1c3/app/Config/View.php#L19 
- add missing `debug`
**Checklist:**

docs: fix view() $options explanation

---

system/Throttle/Throttler.php
tests/system/Throttle/ThrottleTest.php

Fixes #5444
- remove time dependency from the test
**Checklist:**

refactor: fix `ThrottleTest::testFlooding`

---

user_guide_src/source/concepts/http.rst

- fix `$request->getMethod()` return value sample
**Checklist:**

docs: fix http.rst

---

user_guide_src/source/models/entities.rst

- fix directory inconsistency
See https://forum.codeigniter.com/thread-80786.html
**Checklist:**

docs: fix entities.rst

---

system/Throttle/Throttler.php
tests/system/Throttle/ThrottleTest.php

Need to rebase after merging #5463.
Fixes #5458
**Checklist:**

fix: Throttler does not show correct token time

---

user_guide_src/source/incoming/filters.rst
user_guide_src/source/libraries/security.rst

- add InvalidChars filter explanation
- add links to other pages
**Checklist:**

docs: improve filters.rst

---

user_guide_src/source/general/environments.rst

- remove environment-specific configuration files 
It seems there is no such a thing in CI4.
**Checklist:**

docs: fix environments.rst

---

system/Database/Seeder.php
tests/system/Database/DatabaseSeederTest.php
user_guide_src/source/changelogs/v4.1.6.rst
user_guide_src/source/dbmgmt/seeds.rst

docs: deprecate Seeder::faker()

---

composer.json
rector.php

@kenjis by update rector to 0.12.9, we can clean up unneeded skip `AssertIssetToSpecificMethodRector` in config definition as already handled in latest rector 0.12.9.
**Checklist:**

Update rector to 0.12.9 and clean up skip config

---

system/Helpers/filesystem_helper.php
tests/system/Helpers/FilesystemHelperTest.php

Fixes #5478
- do nothing if destination directory exists
- I don't see the reason to raise error when destination directory exists
**Checklist:**

fix: directory_mirror() throws an error if destination directory exists

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/WhereTest.php
user_guide_src/source/changelogs/v4.1.6.rst
user_guide_src/source/database/query_builder.rst

Adding a BaseBuilder instance as a subquery.
* BaseBuilder::cleanClone() method is marked deprecated
* Adding BaseBuilder::isSubquery()
* Adding BaseBuilder::buildSubquery()
```php
$subquery = $db->table('table')->select('id');
$builder->whereIn('id', $subquery);
```
**Checklist:**

Feature: BaseBuilder instance as subquery.

---

user_guide_src/source/general/common_functions.rst

- fix type
- fix comment
- decorate method
**Checklist:**

docs: improve common_functions.rst

---

user_guide_src/source/incoming/incomingrequest.rst
user_guide_src/source/libraries/uploaded_files.rst

- add note about UploadedFile instance when no file was uploaded
- small fixes
**Checklist:**

docs: improve File Uploading

---

system/Database/Forge.php

Removed unnecessary semicolons.
The reason is the following.
* In [oci_parse](https://www.php.net/manual/en/function.oci-parse.php#refsect1-function.oci-parse-parameters), if there is a semicolon, it is treated as PL/SQL.
* There is no semicolon at the end of the SQL except for the one fixed here.
**Checklist:**

Remove semicolons from SQL statements.

---

rector.php
system/CodeIgniter.php
system/Debug/Kint/RichRenderer.php
tests/system/CommonFunctionsTest.php

Supersede #5482
Fixes #5475
- overrides `RichRenderer::preRender()`
**Checklist:**

fix: KINT visual error when activating CSP

---

LICENSE
user_guide_src/source/conf.py
user_guide_src/source/license.rst

Update year 2022
**Checklist:**

update year 2022

---

.github/ISSUE_TEMPLATE/config.yml

- make the URL of the support forum more specific
**Checklist:**

chore: make the URL of the support forum more specific

---

rector.php
tests/system/Commands/BaseCommandTest.php
tests/system/Files/FileCollectionTest.php
tests/system/Publisher/PublisherInputTest.php
tests/system/Publisher/PublisherOutputTest.php
tests/system/Publisher/PublisherRestrictionsTest.php
tests/system/Publisher/PublisherSupportTest.php

Rector 0.12.10 has new `Option::PARALLEL` to speed up process, It now require `Psr4` to be applied in tests to avoid ` Class was not found` notice, ref https://github.com/rectorphp/rector/issues/6903
**Checklist:**

[Rector] Apply Option::PARALLEL to speed up analyze

---

CHANGELOG.md
admin/RELEASE.md
system/CodeIgniter.php
user_guide_src/source/changelogs/v4.1.6.rst
user_guide_src/source/conf.py
user_guide_src/source/installation/upgrade_416.rst

Updates changelog and version references for `4.1.6`.
**Checklist:**

Prep for 4.1.6 release

---

.github/workflows/test-phpunit.yml

Fixed in v2.5.2
**Checklist:**

Revert workaround for php-coveralls

---

.github/workflows/test-phpunit.yml

PHP 8.1 is now stable
**Checklist:**

Remove experimental flag for PHP 8.1

---

CHANGELOG.md

- add Security advisory in CHANGELOG.md
**Checklist:**

docs: add Security advisory in CHANGELOG.md

---

admin/framework/composer.json

- update Kint to `^4.0`
- fixes the error `Access to undeclared static property Kint\Kint::$depth_limit` in appstarter 4.1.6
**Checklist:**

chore: update admin/framework/composer.json Kint

---

system/ThirdParty/Kint/Renderer/CliRenderer.php
system/ThirdParty/Kint/Renderer/RichRenderer.php

It seems kint 4.1.1 has modifications which are not added to our `ThirdParty` copy.
Changes obtained by running `composer update`
**Checklist:**

Update modified Kint files in `ThirdParty`

---

system/Database/BaseConnection.php
tests/system/Database/BaseConnectionTest.php

Fixes #5535
I've confirmed this error when only connecting db but not running any queries.
The bug reporter confirmed this fix: https://github.com/codeigniter4/CodeIgniter4/issues/5535#issuecomment-1004537979
**Checklist:**

fix: BaseConnection::getConnectDuration() number_format(): Passing null to parameter

---

system/Debug/Toolbar/Views/toolbar.js

https://github.com/codeigniter4/CodeIgniter4/issues/5541
Selectors are not unique, and elements are searched throughout the document, so there might be a conflict.
``Document`` object replaced with ``toobar`` fragment
**Checklist:**

Fix: Debug toolbar selectors

---

user_guide_src/source/installation/installing_composer.rst
user_guide_src/source/installation/installing_manual.rst
user_guide_src/source/installation/upgrade_416.rst

I re-read the documentation and found that it did not explain the complete upgrade process. This PR fixes it so that the procedure is complete, including references to other pages.
- add links
- add text decoration
- fix upgrade instrctions
See https://forum.codeigniter.com/thread-80935.html
**Checklist:**

docs: improve upgrade instructions

---

.github/workflows/test-autoreview.yml
.github/workflows/test-phpunit.yml
composer.json
phpunit.xml.dist
tests/AutoReview/ComposerJsonTest.php

This introduces "auto-review tests". Automate the boring task of self-reviewing your own code through GHA.
In this first iteration, this tests the composer.json in root against in `admin/framework` to check if the "require" sections are the same.
This needs #5531 to go green.
**Checklist:**

Auto-review required dependency matching in composer.json

---

user_guide_src/source/installation/upgrade_416.rst

- add upgrade instruction when validating an array without `*`
From https://forum.codeigniter.com/thread-80942.html
**Checklist:**

docs: add upgrade instruction in upgrade_416.rst

---

user_guide_src/source/helpers/cookie_helper.rst

- fix variable name
**Checklist:**

docs: fix variable name in get_cookie()

---

system/Debug/Toolbar/Views/toolbar.js

Follow-up #5544
Calling the showTab method changes the context if the method is not called directly, but as an "internal call".
Rollback of previous changes.
**Checklist:**

Fix: Toolbar. ciDebugBar.showTab() context.

---

system/Debug/Toolbar/Collectors/Database.php
system/Debug/Toolbar/Views/_database.tpl
tests/system/Debug/Toolbar/Collectors/DatabaseTest.php

Fixes #5539 
Supersedes and closes #5543 
**Checklist:**

Refactor Database Collector display

---

system/Helpers/cookie_helper.php
user_guide_src/source/changelogs/index.rst
user_guide_src/source/changelogs/v4.1.7.rst
user_guide_src/source/helpers/cookie_helper.rst
user_guide_src/source/incoming/incomingrequest.rst
user_guide_src/source/installation/upgrade_417.rst
user_guide_src/source/installation/upgrading.rst

This PR goes into `hotfix-4.1.7 `.
Supersedes #5540
Follow-up #5005
- replace `FILTER_SANITIZE_STRING` with `FILTER_SANITIZE_FULL_SPECIAL_CHARS` in `get_cookie()`
- add warning on `get_cookie()` xxsClean
**Checklist:**

fix: replace deprecated FILTER_SANITIZE_STRING

---

system/Common.php
system/Config/Factories.php

Follow-up: #5186
- add Factories::models() to suppress PHPStan error
**Checklist:**

refactor: add Factories::models() to suppress PHPStan error

---

system/Commands/Database/Migrate.php
system/Language/en/Migrations.php
tests/system/Commands/DatabaseCommandsTest.php

- add missing Migration lang item
```
$ php spark migrate
CodeIgniter v4.1.6 Command Line Tool - Server Time: 2022-01-08 20:30:40 UTC-06:00
すべての新しいマイグレーションを実行しています...
Done migrations.
```
**Checklist:**

fix: add missing Migration lang item

---

README.md
Vagrantfile.dist
admin/framework/README.md
admin/module/composer.json
admin/starter/.github/workflows/phpunit.yml
admin/starter/README.md
admin/userguide/composer.json
contributing/pull_request.md
user_guide_src/source/installation/upgrade_4xx.rst
user_guide_src/source/intro/requirements.rst

Follow up #5558
- replace `7.3` with `7.4`
**Checklist:**

Update version references to PHP 7.4

---

tests/system/Models/MiscellaneousModelTest.php

The following code is not good usage of the Model:
```php
$this->model->where('name', 'Senior Developer')->get()->getFirstRow();
```
**Checklist:**

test: refactor MiscellaneousModelTest::testCanCreateAndSaveEntityClasses()

---

system/Exceptions/ModelException.php
system/Language/en/Database.php
system/Model.php
tests/_support/Models/GetCompiledModelTest.php

Alternative to #5561
Related to #5549
- throws Exception when `getCompiled*()` is called in the Model
Reasons:
- `CodeIgniter\Model` and Query Builder should not be expected to return the same data. They are separate classes with different purposes.
- If you need to get the compiled Insert or Update you should do so directly on the Query Builder instance.
**Checklist:**

Throws Exception when getCompiled*() is called in the Model

---

system/Database/BaseBuilder.php
system/Database/BaseConnection.php
system/Database/SQLSRV/Builder.php
tests/system/Database/Builder/FromTest.php
user_guide_src/source/database/query_builder.rst

This PR makes it possible to use subqueries created using the QueryBuilder instead of the table in the FROM section.
This is where we add a subquery to an existing table.::
```php
$subquery = $db->table('users');
$builder  = $db->table('jobs')->fromSubquery($subquery, 'alias');
$query = $builder->get();
// Produces: SELECT * FROM `jobs`, (SELECT * FROM `users`) AS alias
```
Use the ``$db->newQuery()`` method to make a subquery the main table.::
```php
$subquery = $db->table('users')->select('id, name');
$builder  = $db->newQuery()->fromSubquery($subquery, 't');
$query = $builder->get();
// Produces: SELECT * FROM (SELECT `id`, `name` FROM users) AS t
```
---
**The following is the first interface. It has been modified along the way.**
A subquery can be passed either …

Feature: Subqueries in the FROM section

---

composer.json

- intersection type is converted to union type
- see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6238
**Checklist:**

chore: workaround for php-cs-fixer bug in v3.5.0

---

phpstan-baseline.neon.dist
system/Test/FeatureTestCase.php
system/Test/FeatureTestTrait.php
tests/system/HTTP/URITest.php

Follow-up #5346
- refactor: $request->uri → $request->getUri()
**Checklist:**

test: replace `$request->uri` with `$request->getUri()`

---

system/Validation/Validation.php
tests/system/Validation/ValidationTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/libraries/validation.rst

Supersedes and closes #3910 
Fixes #3774
I tried cherry-picking @element-code 's commit but ended up with merge conflicts instead, so the original authorship was lost.
The breaking change with this is the signature change of `setRule`.
**Checklist:**

Validation: support placeholders for anything

---

user_guide_src/source/changelogs/v4.2.0.rst

The develop branch is now uses php 7.4, next version 4.2 should mention minimal php to 7.4 to changelog.
**Checklist:**

Update changelog 4.2 for update minimal php to 7.4

---

system/Autoloader/FileLocator.php
system/BaseModel.php
tests/system/I18n/TimeTest.php

- fix typos in comments
**Checklist:**

docs: fix typos in comments

---

system/Autoloader/Autoloader.php
tests/system/Autoloader/AutoloaderTest.php
tests/system/Database/DatabaseTestCase/DatabaseTestCaseMigrationOnce1Test.php
tests/system/Database/DatabaseTestCase/DatabaseTestCaseMigrationOnce2Test.php
tests/system/Database/DatabaseTestCaseTest.php
tests/system/Database/Migrations/MigrationRunnerTest.php

- reset the state when `initialize()` is called
```
$ ./phpunit --exclude-group DatabaseLive,CacheLive 
Memory: 188.00 MB <- before
Memory: 186.00 MB <- after
```
**Checklist:**

Fix Autoloader::initialize()

---

system/I18n/Time.php
tests/system/I18n/TimeTest.php

previously not updating date even though time zone has been set
**Checklist:**

fix: `Time::createFromTimestamp()` sets incorrect time when specifying timezone

---

system/Entity/Entity.php
tests/system/Entity/EntityTest.php
user_guide_src/source/models/entities.rst

- fixes #5495
- fixes `isset()`may work on db column name in some cases
**Checklist:**

fix: Entity's isset() and unset()

---

system/Model.php
tests/system/Models/DeleteModelTest.php

Related #5576
If the model provides for soft deletion of records and an attempt is made to re-delete, then timestamps are changed in the record marked as deleted.
This PR adds a condition under which the update will only occur if the deletion timestamp has not yet been set.
**Checklist:**

Fix: Deletion timestamp of the Model is updated when a record that has been soft-deleted is deleted again

---

phpstan-baseline.neon.dist
system/HTTP/CURLRequest.php
tests/system/HTTP/CURLRequestDoNotShareOptionsTest.php
tests/system/HTTP/CURLRequestTest.php

To improve test speed.
- CURLReqest
- `sleep()` -> `usleep()`
- Tests
- `delay` 1000 -> 100
**Checklist:**

refactor: CURLRequest and the slow tests

---

user_guide_src/source/incoming/routing.rst

- fix descriptions. The default namespace is `App\Controllers`.
- fix words
- change text decoration
**Checklist:**

docs: fix routing.rst

---

.github/workflows/test-phpunit.yml

- To reduce test time
- add `--no-coverage` option to PHPUnit other than on PHP 8.0
**Checklist:**

chore: generate coverage report by PHPUnit only on PHP 8.0

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/FromTest.php
user_guide_src/source/database/query_builder.rst

Follow-up #5510
Added alias escaping in subquery 
**Checklist:**

Fix: Added alias escaping in subquery

---

system/Commands/Database/MigrateStatus.php
tests/system/Commands/Database/MigrateStatusTest.php

fix: spark migrate:status does not show status with different namespaces

---

system/Config/BaseService.php
tests/system/Config/ServicesTest.php

Since injectMock converts key to lowercase we need to use lowercase key as well in resetSingle method 
Fixes #5595
**Checklist:**

BaseService - Use lowercase key in resetSingle

---

system/Helpers/array_helper.php
tests/system/Helpers/ArrayHelperTest.php

Fix `array_flatten_with_dots` ignores empty array values

---

user_guide_src/source/libraries/throttler.rst

fix small typo

---

user_guide_src/source/installation/index.rst
user_guide_src/source/installation/upgrading.rst

- add missing upgrade_418 in TOC
- move "Change Logs" up 
**Checklist:**

docs: small fix for installation

---

.github/workflows/test-phpunit.yml
system/Database/OCI8/Builder.php
system/Database/OCI8/Connection.php
system/Database/OCI8/Forge.php
system/Database/OCI8/PreparedQuery.php
system/Database/OCI8/Result.php
tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
tests/system/Commands/CreateDatabaseTest.php
tests/system/Database/Live/GroupTest.php
tests/system/Database/Live/OCI8/CallStoredProcedureTest.php
tests/system/Database/Live/OCI8/LastInsertIDTest.php
tests/system/Database/Live/PreparedQueryTest.php
tests/system/Database/Live/WhereTest.php
tests/system/Models/FindModelTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/database/helpers.rst
user_guide_src/source/database/queries.rst
user_guide_src/source/database/query_builder.rst

I wanted to use CodeIgniter4 in an Oracle environment.
Also, it was determined that support would be provided because ORACLE was described in the document.
**Checklist:**
The design of the program to get the insertId of this `PR` is not so good.
Please good solution.

Feature Add Oracle driver

---

system/Commands/Utilities/Routes.php
system/Commands/Utilities/Routes/AutoRouteCollector.php
system/Commands/Utilities/Routes/ControllerFinder.php
system/Commands/Utilities/Routes/ControllerMethodReader.php
tests/_support/Controllers/Hello.php
tests/_support/Controllers/Remap.php
tests/system/Commands/Utilities/Routes/AutoRouteCollectorTest.php
tests/system/Commands/Utilities/Routes/ControllerFinderTest.php
tests/system/Commands/Utilities/Routes/ControllerMethodReaderTest.php

- add listing of auto routes in `spark routes`
- auto routes are not listed and users may expose unexpected methods
**Note:**
If you have `Controllers\Home::index`, on macOS you can access it by:
- http://localhost:8080/home/index
- http://localhost:8080/Home/Index
- http://localhost:8080/hOme/iNdex
- ...
- http://localhost:8080/HOME/INDEX
But this command shows only `home/index[/...]`.
**Checklist:**

feat: auto routes listing

---

system/Filters/Filters.php
system/Router/Router.php

- initialize property
- renumber the array keys
**Checklist:**

refactor: small changes in Filters and Router

---

system/CodeIgniter.php
system/HTTP/DownloadResponse.php

fix: DownloadResponse memory leak

---

system/Router/RouteCollection.php
system/Test/FilterTestTrait.php
tests/system/Router/RouteCollectionTest.php

- replace deprecated `getFilterForRoute()`
**Checklist:**

refactor: replace deprecated `getFilterForRoute()`

---

.github/workflows/test-phpstan.yml
phpstan-baseline.neon.dist

Fix PHPStan notice after PHPStan updated to 1.4.4:
```bash
Note: Using configuration file /Users/samsonasik/www/CodeIgniter4/phpstan.neon.dist.
423/423 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
------ ------------------------------- 
Line   system/Cache/CacheFactory.php  
------ ------------------------------- 
45     Result of || is always false.  
49     Result of || is always false.  
------ ------------------------------- 
------ ------------------------------- 
Line   system/Filters/Filters.php     
------ ------------------------------- 
396    Result of || is always false.  
436    Result of || is always false.  
------ ------------------------------- 
------ ----------------------------------------------------------------------------------------------------------------------------------- …
```

Fix PHPStan notice on 1.4.4

---

app/Controllers/BaseController.php
phpstan-baseline.neon.dist
system/Config/Routes.php

- no need to instantiate
**Checklist:**

refactor: make BaseController abstract

---

system/Config/Routes.php
system/Router/Router.php
tests/system/Router/RouterTest.php

- it should prevent when auto routing
**Checklist:**

refactor: move logic to prevent access to initController

---

system/Database/BaseConnection.php
system/Database/SQLSRV/Connection.php
user_guide_src/source/changelogs/v4.2.0.rst

- The method is a duplicate of `error()`.
- `BaseConnection` does not have `getError()`
**Checklist:**

deprecate Database\SQLSRV\Connection::getError()

---

system/Commands/Utilities/Routes.php
tests/_support/Config/Routes.php
tests/system/Commands/CommandTest.php

The "spark routes" command shows routes with a closure. 
```
+--------+----------------------------+------------------------------------------------+
| Method | Route                      | Handler                                        |
+--------+----------------------------+------------------------------------------------+
| GET    | /                          | \App\Controllers\Home::index                   |
| GET    | closure                    | Closure                                        |
```
**Checklist:**

Feature: "spark routes" command shows routes with closure.

---

contributing/internals.md
system/Config/Routes.php

- `Commands\MigrationsCommand` was removed in 2016 49ec1083e508c8839f845f69b415b1739e9a7ed7
**Checklist:**

refactor: remove migrations routes

---

user_guide_src/source/dbmgmt/migration.rst

Fixes #5611
- update Migration filename and classname
- add note on Migration classname uniqueness
- fix tablename
**Checklist:**

docs: fix dbmgmt/migration.rst

---

system/CodeIgniter.php
system/Commands/Utilities/Routes.php
system/Commands/Utilities/Routes/FilterCollector.php
system/Commands/Utilities/Routes/FilterFinder.php
system/Commands/Utilities/Routes/SampleURIGenerator.php
system/Filters/Filters.php
system/Router/RouteCollection.php
system/Router/Router.php
tests/system/Commands/Utilities/Routes/FilterCollectorTest.php
tests/system/Commands/Utilities/Routes/FilterFinderTest.php
tests/system/Commands/Utilities/Routes/SampleURIGeneratorTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/incoming/filters.rst
user_guide_src/source/incoming/routing.rst

Related #5590
- add filters to `spark routes` command
```
$ php spark routes
CodeIgniter v4.1.8 Command Line Tool - Server Time: 2022-01-28 19:29:51 UTC-06:00
+--------+------------------+------------------------------------------+----------------+-----------------------+
| Method | Route            | Handler                                  | Before Filters | After Filters         |
+--------+------------------+------------------------------------------+----------------+-----------------------+
| GET    | /                | \App\Controllers\Home::index             | invalidchars   | secureheaders toolbar |
| GET    | feed             | (Closure)                                | invalidchars   | secureheaders toolbar |
| CLI    | ci(.*)           | …
```

feat: `spark routes` shows filters

---

user_guide_src/source/incoming/routing.rst

- add about "auto routes"
**Checklist:**

docs: add about "auto routes"

---

app/Config/App.php
app/Config/Security.php
phpstan-baseline.neon.dist
system/Security/Security.php

- fix Config CSRF $redirect does not work
- update PHPDocs
**Checklist:**

fix: Config CSRF $redirect does not work

---

system/Commands/Utilities/Routes/AutoRouteCollector.php
system/Commands/Utilities/Routes/ControllerFinder.php
system/Commands/Utilities/Routes/ControllerMethodReader.php

Extensions in Visual Studio Code do not have access yet to advanced doc blocks like `class-string`, `list`, `T`, causing type error hints when files are opened. I suggest changing them into the conventional formats.
However, for SA, phpstan uderstands them so I just swapped them to the compatible tags (like `@phpstan-return`).
**Checklist:**

Rename docblocks in Routes utilities classes

---

app/Views/errors/html/error_exception.php
system/Debug/Exceptions.php
system/Debug/Toolbar/Collectors/BaseCollector.php
system/Debug/Toolbar/Collectors/Files.php
system/Log/Logger.php
system/Test/TestLogger.php
tests/system/Debug/ExceptionsTest.php
tests/system/Log/LoggerTest.php
user_guide_src/source/changelogs/v4.2.0.rst

Use the `clean_path()` function instead.
**Checklist:**

Deprecate object implementations of `clean_path()` function

---

system/Debug/Exceptions.php

Fixes #5679
Before:
After:
**Checklist:**

fix: do not call header() if headers have already been sent

---

app/Config/Filters.php
user_guide_src/source/incoming/filters.rst
user_guide_src/source/installation/upgrade_415.rst
user_guide_src/source/libraries/security.rst
user_guide_src/source/libraries/throttler.rst
user_guide_src/source/tutorial/create_news_items.rst

docs: add warning about $method filters

---

depfile.yaml
system/Session/Session.php
user_guide_src/source/changelogs/v4.2.0.rst

- The Response should send all cookies.
**Checklist:**

refactor: Session does not use cookies()

---

system/Router/Router.php
tests/system/Router/RouterTest.php
user_guide_src/source/changelogs/v4.2.0.rst

- `$routes->setDefaultMethod()` does not work when you go to `/`
See https://forum.codeigniter.com/thread-81269.html
**Checklist:**

fix: $routes->setDefaultMethod() does not work

---

user_guide_src/source/incoming/routing.rst

The `add()` method is not secure, so it is not recommended to use.
The current description is:
1.  Uses `add()` first 
2. After that explains a little that it is not secure
This PR is:
1.  Uses `get()` and other HTTP verb method
2. After that explains `add()` a little
**Checklist:**

docs: use `get()` not `add()` from the beginning in routing.rst

---

system/Validation/Validation.php
tests/system/Validation/StrictRules/ValidationTest.php
tests/system/Validation/ValidationTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/libraries/validation.rst

Now, when validating a multidimensional array using a wildcard, only the last error is saved. Therefore, it is impossible to determine which field the error belongs to.
```php
// data
[
'users' => [
'friends' => [
['name' => 'Jim'],
['name' => 'James'],
['name' => ''],
]
]
]
// rules
['users.*.name' => 'required|min_length[4]']
// errors
['users.*.name' => 'The users.*.name field is required.']
```
This PR changes behavior. Errors have a corresponding key.
```php
[
'users.friends.0.name' => 'The users.*.name field must be at least 4 characters in length.',
'users.friends.2.name' => 'The users.*.name field is required.',
]
```
**Checklist:**

Fix: Validation. Error key for field with asterisk

---

system/Database/Query.php
tests/system/Database/BaseQueryTest.php
user_guide_src/source/database/queries.rst

Main fix:
- `getQuery()` can now be called multiple times without trouble, `compileBinds()` will be called only on original SQL string. Previously, calling `getQuery()` additional times was executing `compileBinds()` again and again, and on the already compiled SQL string…
Additional improvements and notes:
- [Performances] If `getQuery()` is called multiple times, `compileBinds()` is executed only the first time.
- Calling `setQuery()` or `setBinds()` discard `finalQueryString`, so they can be called multiple times with new data, and the SQL will be generated with this new data.
- `swapPrefix()` will always be executed on the original SQL string (with the bind placeholders), which is a bit safer than on the final SQL string (as the search/replace just operates on the whole SQL string).
- …

Allow calling getQuery() multiple times, and other improvements

---

user_guide_src/source/concepts/autoloader.rst

- Legacy Support was removed.
**Checklist:**

docs: fix out of dated description in autoloader.rst

---

app/Views/errors/html/error_exception.php
system/HTTP/ResponseTrait.php
tests/system/HTTP/DownloadResponseTest.php

- update deprecated method
**Checklist:**

refactor: replace deprecated Response::getReason() with getReasonPhrase()

---

system/HTTP/CLIRequest.php
system/HTTP/IncomingRequest.php
tests/system/HTTP/IncomingRequestTest.php

From  #5649
- no need to depend on `is_cli()`
**Checklist:**

refactor: isCLI() in CLIRequest and IncomingRequest

---

system/Debug/Exceptions.php
tests/system/Debug/ExceptionsTest.php
user_guide_src/source/changelogs/v4.2.0.rst

Improve exception logging

---

system/Controller.php
tests/system/ControllerTest.php
user_guide_src/source/incoming/controllers.rst
user_guide_src/source/libraries/validation.rst

- `$this->validate()` can't validate arbitrary data
- e.g. method parameters, trimmed data
- This method can validate any user supplied data
**Checklist:**

feat: add Controller::validateData()

---

system/CodeIgniter.php
tests/_support/Controllers/Popcorn.php
tests/system/CodeIgniterTest.php

fix: 404 override controller does not output Response object body

---

system/Commands/Utilities/Routes.php
tests/system/Commands/CommandTest.php
tests/system/Commands/RoutesTest.php
tests/system/Commands/Utilities/Routes/FilterCollectorTest.php

Follow-up  #5628
- auto routes incorrectly display route filters with GET method
```diff
@@ -31,7 +31,7 @@ $routes->setAutoRoute(true);
// We get a performance increase by specifying the default
// route since we don't have to scan directories.
-$routes->get('/', 'Home::index');
+$routes->get('/', 'Home::index', ['filter' => 'csrf'] );
/*
* --------------------------------------------------------------------
```
Before:
```
+--------+------------------+------------------------------------------+----------------+---------------+
| Method | Route            | Handler                                  | Before Filters | After Filters |
+--------+------------------+------------------------------------------+---------------- …
```

fix: auto routes incorrectly display route filters with GET method

---

system/HTTP/Files/FileCollection.php

- `RecursiveIteratorIterator::hasChildren()` is not documented in PHP manual, and PhpStorm tells not defined.
**Checklist:**

docs: add comment in HTTP/Files/FileCollection.php

---

user_guide_src/source/changelogs/v4.2.0.rst

Follow up:  #5650, #5628
**Checklist:**

docs: update changelogs/v4.2.0.rst

---

phpstan-baseline.neon.dist
system/CodeIgniter.php
system/HTTP/CLIRequest.php
tests/system/CLI/CommandRunnerTest.php
tests/system/HTTP/CLIRequestTest.php

Fixes #3400
When you run the following command:
```
$ php spark test param1 param2 -opt1 opt1val
```
`$params` of the `Test` command would be:
```
Array
(
[0] => param1
[1] => param2
[opt1] => opt1val
)
```
**Checklist:**

Fix options are not passed to Command $params

---

user_guide_src/source/libraries/sessions.rst
user_guide_src/source/libraries/uploaded_files.rst

- difficult to understand what s "previous version".
**Checklist:**

docs: change "previous version" to a specific version

---

system/Database/BaseBuilder.php
system/Database/BasePreparedQuery.php
system/Database/BaseUtils.php
system/Database/Forge.php
system/Database/Query.php
system/Database/SQLSRV/Utils.php
system/Database/Seeder.php
system/Model.php

- `$db` is an object. We don't need to use reference. 
- see https://www.php.net/manual/en/language.oop5.references.php
**Checklist:**

refactor: remove `&` before $db

---

system/HTTP/ContentSecurityPolicy.php

- `$response` is an object. We don't need to use reference.
- see https://www.php.net/manual/en/language.oop5.references.php
**Checklist:**

refactor: remove unneeded `&` references in ContentSecurityPolicy.php

---

system/HTTP/URI.php
tests/system/HTTP/URITest.php

fix: forceGlobalSecureRequests break URI schemes other than HTTP

---

system/Filters/CSRF.php

-  fix `@return` type
**Checklist:**

docs: fix `@return` in CSRF.php

---

system/Security/Security.php
tests/system/Security/SecurityCSRFSessionRandomizeTokenTest.php

fix: TypeError when `$tokenRandomize = true` and no token posted

---

system/HTTP/ContentSecurityPolicy.php
tests/system/HTTP/ContentSecurityPolicyTest.php

Code optimization for replacing style and script placeholders with nonces.
**Checklist:**

Nonce replacement optimization.

---

system/Router/RouteCollection.php
tests/system/Router/RouteCollectionTest.php
user_guide_src/source/incoming/routing.rst
user_guide_src/source/incoming/routing/004_1.php
user_guide_src/source/incoming/routing/004_2.php
user_guide_src/source/incoming/routing/004_3.php
user_guide_src/source/incoming/routing/004_4.php

- You can jump to the controller method with IDE.
E.g.:
```php
$routes->get('home', [Hello::class, 'index']);
$routes->get('product/(:num)/(:num)', [[Hello::class, 'index'], '$1/$2']);
```
**Checklist:**

feat: can add route handler as callable

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/BaseTest.php

To prevent possible unpredictable behavior, a check has been added for using the same object for the subrequry as the main query.
**Checklist:**

Checking if the subquery uses the same object as the main query

---

user_guide_src/source/general/urls.rst
user_guide_src/source/incoming/controllers.rst
user_guide_src/source/incoming/index.rst
user_guide_src/source/incoming/routing.rst

Rework docs to disable auto-routing by default.
- explain defined routes first, auto-routes last
**Checklist:**

docs: rework about auto-routing

---

user_guide_src/source/incoming/controllers.rst

- Extending the controller is common practice. It should be stated iin the "Controllers" page.
**Checklist:**

docs: add section to link to "Extending the Controller" in incoming/controllers.rst

---

user_guide_src/source/installation/upgrading.rst

- remove unneeded page titles
**Checklist:**

docs: remove unneeded page titles in upgrading.rst

---

system/Database/BaseBuilder.php
system/Test/Mock/MockBuilder.php
tests/system/Database/Builder/InsertTest.php

fix: $builder->ignore()->insertBatch() only ignores on first iteration

---

composer.json
phpstan-baseline.neon.dist
tests/system/Database/Live/FabricatorLiveTest.php
tests/system/Database/Live/ForgeTest.php
tests/system/Filters/HoneypotTest.php
tests/system/HTTP/URITest.php
tests/system/Honeypot/HoneypotTest.php
tests/system/I18n/TimeTest.php

- Update Rector to 0.12.17
- Re-run it to apply more removal on unneded variable in assign
- Apply typed property on final class protected property.
- Ignore phpstan 1.4.7 notice on `Binary operation "/" between string and 8 results in an error.` on system/Encryption/Handlers/OpenSSLHandler.php
**Checklist:**

[Rector] Update to Rector 0.12.17 and Re-run it

---

user_guide_src/source/concepts/factories.rst
user_guide_src/source/concepts/factories/005.php

- fix incorrect config filename
**Checklist:**

docs: fix incorrect config filename in factories.rst

---

system/Router/RouteCollection.php

Fixes #2203
See https://github.com/codeigniter4/CodeIgniter4/issues/2203#issuecomment-1059961885
- fix `app/Config/Routes.php` is loaded twice on Windows
- fix `sysmte/Config/Routes.php` is loaded twice
**Checklist:**

fix: app/Config/Routes.php is loaded twice on Windows

---

admin/framework/composer.json
composer.json

Workaround for #5784
**Checklist:**

chore: fix php-cs-fixer version to 3.6

---

system/Database/BaseBuilder.php
system/Database/BaseConnection.php
tests/system/Database/Builder/LikeTest.php

fix: table name is double prefixed when LIKE clause

---

.github/workflows/test-coding-standards.yml
.user-guide.php-cs-fixer.dist.php
admin/pre-commit
composer.json

- add `.user-guide.php-cs-fixer.dist.php`
- add user guide cs check in git pre-commit hook
- add user guide cs check in GitHub Action
- update `composer cs-fix`
I propose the following before fixing sample code:
- move CI3 sample code in Upgrading into the folder `ci3sample/`
- we need exclude the CI3 sample code
- #5771
- use `/* ... */` style comment for explanation of the code result
- The comments are not normal comments, so it is better not to use `//`
- #5770
**Checklist:**

chore: add .user-guide.php-cs-fixer.dist.php for sample code in docs

---

.github/scripts/deploy-userguide
.github/workflows/deploy-userguide.yml

This PR adds a GitHub Action to automate building and deploying the User Guide to the User Guide repo whenever there is a new release. I tested by setting up parallel repos under my user org, the results are viewable here:
* Action logs: https://github.com/MGatner/CodeIgniter4/runs/5457928233?check_suite_focus=true
* Resulting release: https://github.com/MGatner/userguide/releases
**Checklist:**

User Guide Deploy Action

---

app/Config/Validation.php

The Config\Validation file was not extending BaseConfig. This prevents Registrars from being able to add rules or rulesets.

Extend Validation from BaseConfig so Registrars can add rules.

---

app/Config/Publisher.php
tests/system/Publisher/PublisherRestrictionsTest.php

- fix regex
Related: #5792
**Checklist:**

fix: Publisher $restrictions regex to FCPATH

---

system/Debug/Timer.php
tests/system/Debug/TimerTest.php

fix: Timer::getElapsedTime() returns incorrect value

---

app/Config/Publisher.php

Fixes the intended font extension `ttf` - no idea what `tff` is.
**Checklist:**

bug: Publisher typo

---

tests/system/HTTP/UserAgentTest.php
tests/system/Helpers/HTMLHelperTest.php
tests/system/Helpers/URLHelper/CurrentUrlTest.php
tests/system/Helpers/URLHelper/MiscUrlTest.php
tests/system/Helpers/URLHelper/SiteUrlTest.php
tests/system/Pager/PagerTest.php
tests/system/View/ParserPluginTest.php

URL Helper is automatically loaded.
**Checklist:**

test: remove `helper('url')`

---

system/Validation/FormatRules.php
tests/system/Validation/FormatRulesTest.php

From https://forum.codeigniter.com/thread-81505-post-394652.html
```
DateTime::createFromFormat(): Passing null to parameter #2 ($datetime) of type string is deprecated
```
**Checklist:**

fix: [Validation] valid_date ErrorException when the field is not sent

---

system/Pager/Pager.php
tests/system/Pager/PagerTest.php

From https://forum.codeigniter.com/thread-81531.html
- `setSegment()` recalculates the current page
- `calculateCurrentPage()` can be called more than once
**Checklist:**

fix: [Pager] can't get correct current page from segment

---

user_guide_src/source/models/entities.rst

docs: add note about `attributes` in Entity

---

system/Helpers/url_helper.php
user_guide_src/source/helpers/url_helper.rst

docs: clarify that current_url() returns URL based on Config\App

---

system/Language/en/Router.php
system/Router/Exceptions/RouterException.php
system/Router/Router.php
tests/system/Router/RouterTest.php

Dynamic controllers are not allowed for security reasons. See https://github.com/codeigniter4/CodeIgniter4/issues/2787#issuecomment-608198225
But there is a bug that allows dynamic controllers.
- add check for dynamic controllers
- refactor
**Checklist:**

fix: bug that allows dynamic controllers to be used

---

user_guide_src/source/incoming/incomingrequest.rst

strtoupper is a PHP method for uppercase strings. (https://www.php.net/manual/en/function.strtoupper.php)
**Checklist:**

(User guide) Referenced wrong method

---

phpstan-baseline.neon.dist
system/Config/Services.php
system/Database/BaseConnection.php
system/Session/Handlers/BaseHandler.php
system/Session/Handlers/Database/MySQLiHandler.php
system/Session/Handlers/Database/PostgreHandler.php
system/Session/Handlers/DatabaseHandler.php
tests/system/Session/Handlers/Database/AbstactHandlerTestCase.php
tests/system/Session/Handlers/Database/MySQLiHandlerTest.php
tests/system/Session/Handlers/Database/PostgreHandlerTest.php

- make database specific handlers
**Checklist:**

refactor: DB Session Handler

---

user_guide_src/source/changelogs/v4.1.6.rst

It is not clear that PHP 8.1 is fully supported.
See https://forum.codeigniter.com/thread-81591.html
**Checklist:**

docs: add full support for PHP 8.1 in changelogs/v4.1.6.rst

---

admin/starter/composer.json
system/CLI/Commands.php

Revert #3423
Fixes #5818
Why
- The `autoload.psr-4` causes problems:
- Cannot change `app` folder name. Because the composer's path overwrite the config in `Config\Autoload`. See https://forum.codeigniter.com/thread-81153.html
- Causes error when defining new namespace under `app/`. See https://github.com/codeigniter4/CodeIgniter4/issues/5818
- These are very difficult to debug.
- Only app starter has the configs. So it is not consistent.
If there is a user who wants to use Composer autoloader optimization (`dump-autoload -o`) for `App` namespace class files, they could add it in `autoload.psr-4` by themself.
**Checklist:**
- [] Conforms to …

config: remove App\ and Config\ in autoload.psr-4 in app starter composer.json

---

system/Database/BaseConnection.php
tests/system/Database/BaseConnectionTest.php
tests/system/Database/Live/ConnectTest.php

fix: failover's DBPrefix not working

---

user_guide_src/requirements.txt
user_guide_src/source/changelogs/v4.2.0.rst

- add index.php/spark changes in changelog
- fix ImportError on GitHub Actions. See https://github.com/codeigniter4/CodeIgniter4/runs/5714296426?check_suite_focus=true
- > ImportError: cannot import name 'environmentfilter' from 'jinja2' (/usr/local/lib/python3.10/site-packages/jinja2/__init__.py)
make: *** [Makefile:20: html] Error 1
**Checklist:**

docs: add index.php/spark changes in changelog

---

system/CLI/CommandRunner.php
system/CodeIgniter.php
tests/system/CLI/CommandRunnerTest.php
tests/system/SparkTest.php
user_guide_src/source/changelogs/v4.2.0.rst

Fixes #5835
Follow-up #5206
**Checklist:**

fix: spark can't use options on PHP 7.4

---

app/Config/Routes.php
system/Router/RouteCollection.php
tests/system/CodeIgniterTest.php
tests/system/Commands/RoutesTest.php
tests/system/Commands/Utilities/Routes/FilterCollectorTest.php
tests/system/Router/RouterTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/cli/cli.rst
user_guide_src/source/incoming/controllers.rst
user_guide_src/source/incoming/routing.rst
user_guide_src/source/installation/upgrade_420.rst
user_guide_src/source/tutorial/create_news_items.rst
user_guide_src/source/tutorial/create_news_items/004.php
user_guide_src/source/tutorial/news_section.rst
user_guide_src/source/tutorial/news_section/008.php
user_guide_src/source/tutorial/static_pages.rst
user_guide_src/source/tutorial/static_pages/003.php
user_guide_src/source/tutorial/static_pages/004.php

- To make the default config more secure, disable  auto-routing by default.
**Checklist:**

config: disable auto-routing by default

---

user_guide_src/source/database/query_builder.rst

Needs to be orWhere(). There is no or_where in CI 4.
given function name was wrong and cost me some time. I wanted to change it to the correct one so othere won't lose time.

wrong function name `or_where()`

---

system/Validation/Validation.php

Fixes #5839
- remove session _ci_validation_errors before running validation
**Checklist:**

fix: Validation returns incorrect errors after Redirect with Input

---

user_guide_src/source/tutorial/create_news_items/002.php
user_guide_src/source/tutorial/news_section/004.php
user_guide_src/source/tutorial/news_section/006.php
user_guide_src/source/tutorial/static_pages.rst
user_guide_src/source/tutorial/static_pages/002.php

- use `return` in a controller method, instead of `echo`
- `echo` has side effects, so `return` is better.
**Checklist:**

docs: improve tutorial

---

system/View/Parser.php
tests/system/View/ParserTest.php
user_guide_src/source/outgoing/view_parser.rst
user_guide_src/source/outgoing/view_parser/027.php

Fixes #5831
- add properties `$leftConditionalDelimiter` and `$rightConditionalDelimiter`
- add method `setConditionalDelimiters()`
**Checklist:**

feat: [Parser] add configs to change conditional delimiters

---

system/Autoloader/Autoloader.php
tests/system/Autoloader/AutoloaderTest.php
user_guide_src/source/changelogs/v4.2.0.rst

The current implementation uses Composer classmap  only when `$modules->discoverInComposer` is true.
`discoverInComposer` is the setting for Auto-Discovery within Composer Packages.
It has nothing to do with classmap usage.
This PR makes it use always if Composer is available.
Related: #5834
**Checklist:**

fix: [Autoloader] Composer classmap usage

---

user_guide_src/source/installation/upgrade_view_parser/001.php
user_guide_src/source/outgoing/view_parser.rst
user_guide_src/source/outgoing/view_parser/003.php
user_guide_src/source/outgoing/view_parser/006.php
user_guide_src/source/outgoing/view_parser/007.php
user_guide_src/source/outgoing/view_parser/008.php
user_guide_src/source/outgoing/view_parser/018.php
user_guide_src/source/outgoing/view_parser/019.php
user_guide_src/source/outgoing/view_parser/020.php
user_guide_src/source/outgoing/view_parser/021.php
user_guide_src/source/outgoing/view_parser/024.php
user_guide_src/source/outgoing/view_parser/025.php
user_guide_src/source/outgoing/view_parser/026.php

- change coding style
- add Class reference
- small fixes of description
The documented options `leftDelimiter` and `rightDelimiter` are not implemented.
And I think they are not needed as options. So remove them.
**Checklist:**

docs: fix parser.rst

---

system/Autoloader/FileLocator.php
system/CLI/Commands.php
tests/system/Autoloader/FileLocatorTest.php

Fixes #5818
Supersedes #5834
- fix: FileLocator::listFiles() returns directories
- fix: discoverCommands() loads incorrect classname
Cannot write a unit test for `Cannot declare class ..., because the name is already in use`. 
To check manually using this repo:
1. Add `"App\\": "app/"` in the `autoload.psr4` section in the root composer.json
2. Run `composer dump -o` to regenerate the class map.
3. Add `'MyNameSpace' => APPPATH . 'ThirdParty/MyFolder'` in `Config\Autoload::$psr4` array.
4. Run `php spark make:command TeseCommand --namespace MyNameSpace`
5. Run `php spark`. This will now error.
6. Check out this PR branch (`fix-discoverCommands`).
7. Run `php spark`. No errors should appear.
**Checklist:**

fix: Commands::discoverCommands() loads incorrect classname

---

.github/workflows/test-coding-standards.yml
.php-cs-fixer.dist.php
.php-cs-fixer.no-header.php
.php-cs-fixer.user-guide.php
admin/pre-commit

The php-cs-fixer configuration files are all in one place and easy to find.
**Checklist:**

chore: rename php-cs-fixer config files

---

system/Publisher/Publisher.php

Related  #5849
Cannot write a unit test for `Cannot declare class ..., because the name is already in use`. 
To check manually using this repo:
1. Add `"App\\": "app/"` in the `autoload.psr4` section in the root `composer.json`.
2. Run `composer dump -o` to regenerate the class map.
3. Add `'MyNameSpace' => APPPATH . 'ThirdParty/MyFolder'` in `Config\Autoload::$psr4` array.
4. Create `app/ThirdParty/MyFolder/Publishers/BootstrapPublisher.php`:
```php
<?php
namespace MyNameSpace\Publishers;
use CodeIgniter\Publisher\Publisher;
class BootstrapPublisher extends Publisher
{
}
```
5. Run `php spark publish`. 
```
CodeIgniter v4.1.9 Command Line Tool - Server Time: 2022-04-04 06:39:07 UTC-05:00
PHP Fatal error:  Cannot declare class MyNameSpace\Publishers\BootstrapPublisher, …
```

fix: Publisher::discover() loads incorrect classname

---

system/HTTP/RedirectResponse.php

See https://github.com/codeigniter4/CodeIgniter4/issues/5839#issuecomment-1086624600
Saving validation errors in the Session has nothing to do with saving input data in the Session.
They are different things and saving validation errors should be another method.
But the change is a breaking change. 
This PR just extract a private method to prepare to the future breaking change.
**Checklist:**

refactor: extract RedirectResponse::withErrors() method

---

phpstan-baseline.neon.dist
system/BaseModel.php
tests/system/Models/ValidationModelTest.php

fix: validation errors in Model are not cleared when running validation again

---

composer.json

Follow-up #5866
- update composer scripts
**Checklist:**

chore: update composer scripts

---

user_guide_src/source/concepts/factories.rst
user_guide_src/source/concepts/factories/002.php
user_guide_src/source/concepts/factories/003.php
user_guide_src/source/concepts/factories/008.php
user_guide_src/source/concepts/factories/009.php
user_guide_src/source/concepts/factories/010.php

- add Differences from Services
- add Convenience Functions
- add preferApp behavior in Example
**Checklist:**

docs: improve Factories

---

system/Helpers/filesystem_helper.php
tests/system/Helpers/FilesystemHelperTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/helpers/filesystem_helper.rst

- add option to exclude directories
See https://github.com/codeigniter4/CodeIgniter4/pull/5849#discussion_r841375909 and
https://github.com/codeigniter4/CodeIgniter4/blob/8f1ed45f1bb3d2df34665e80767d171bd4cef167/tests/system/Helpers/FilesystemHelperTest.php#L290-L291
**Checklist:**

feat: add `$includeDir` option to `get_filenames()`

---

user_guide_src/source/dbmgmt/migration.rst
user_guide_src/source/libraries/sessions.rst

- update out of dated descriptions
**Checklist:**

docs: update migration

---

user_guide_src/source/outgoing/view_parser.rst
user_guide_src/source/outgoing/views.rst
user_guide_src/source/outgoing/views/010.php

- `saveData` is `true` by default, but the explanation is the opposite.
See
https://github.com/codeigniter4/CodeIgniter4/blob/a9b086a06ead631e5cdc3bb2966960a8b6bb177e/app/Config/View.php#L20
https://github.com/codeigniter4/CodeIgniter4/blob/a9b086a06ead631e5cdc3bb2966960a8b6bb177e/system/View/Parser.php#L97
https://github.com/codeigniter4/CodeIgniter4/blob/a9b086a06ead631e5cdc3bb2966960a8b6bb177e/system/View/View.php#L166
https://github.com/codeigniter4/CodeIgniter4/blob/a9b086a06ead631e5cdc3bb2966960a8b6bb177e/system/Common.php#L1105
**Checklist:**

docs: fix View/Parser saveData description

---

user_guide_src/source/models/model.rst

Inform the $useAutoIncrement default value (which is 'true'), so developers would be aware of that option if they don't use auto-incremented INT's on primary keys, especially when triggering an 'afterInsert' event which will eventually cause the $data['id'] value to be 0 instead of the actual primary key (see 'system/Model.php' line 254 : https://github.com/codeigniter4/CodeIgniter4/blob/622d50aa2976b85f7cb1479faec7558cd9ec2341/system/Model.php#L254).
I had an issue with this before and spent a bit long time figuring out what went wrong and it turned out to be a missing information in the user guide.

clarify Models user guide

---

user_guide_src/source/outgoing/api_responses.rst

docs: fix parameters display for API response > `setResponseFormat($format)` method

---

user_guide_src/source/outgoing/api_responses.rst

docs: fix heading level in api_responses.rst

---

system/Language/en/Router.php
system/Router/Exceptions/RouterException.php
system/Router/Router.php
tests/system/Router/RouterTest.php

- Throws Exception when a routes has invalid controller name like `'Admin/AdminGlavni::cam_edit_show/$1'`
It is better users know it should be `\` than replacing `/` with `\` without notice.
Because `Admin/AdminGlavni` is a wrong classname.
See https://forum.codeigniter.com/showthread.php?tid=81681&pid=395315#pid395315
**Checklist:**

feat: throws exception when controller name in routes contains `/`

---

system/Config/BaseConfig.php
tests/system/Config/BaseConfigTest.php
tests/system/Config/fixtures/.env
tests/system/Config/fixtures/SimpleConfig.php

Fixes #5688
Supersede #5704,  #5691 and #5690
**Checklist:**

fix: [BaseConfig] string value is set from environment variable even if it should be int/float

---

system/Config/AutoloadConfig.php

fix: add Escaper Exception classes in $coreClassmap

---

user_guide_src/source/cli/cli_commands.rst
user_guide_src/source/concepts/autoloader.rst
user_guide_src/source/concepts/mvc.rst
user_guide_src/source/general/configuration.rst
user_guide_src/source/incoming/controllers.rst
user_guide_src/source/libraries/throttler.rst
user_guide_src/source/libraries/validation.rst

- Because there are more places written as `app/`.
- `/` at first implies root directory of the file system.
**Checklist:**

docs: replace `/app/` with `app/`

---

composer.json
phpstan.neon.dist

PHPStan 1.6.0 will remove `parent`, `next`, `previous` attribute from node on `bleedingEdge` feature toggles, while it only disable when `bleedingEdge` enabled, it may possibly be removed in the future, so I think it is better to prepare early. 
We used the `previous` attribute check on `CheckUseStatementsAfterLicenseRule` for it:
https://github.com/codeigniter4/CodeIgniter4/blob/622d50aa2976b85f7cb1479faec7558cd9ec2341/utils/PHPStan/CheckUseStatementsAfterLicenseRule.php#L60
This PR is for draft and can be updated to use ^1.6 when PHPStan 1.6 released.
References:
- https://github.com/rectorphp/rector/issues/7088
- https://github.com/rectorphp/rector-src/pull/2014
**Checklist:**

[PHPStan] Prepare for PHPStan 1.6.x-dev

---

system/Autoloader/Autoloader.php
tests/system/Autoloader/AutoloaderTest.php

The user guide says:
> If the same namespace is defined in both CodeIgniter and Composer, CodeIgniter’s autoloader will be the first one to get a chance to locate the file.
https://codeigniter4.github.io/CodeIgniter4/concepts/autoloader.html#composer-support
But if you move the `app/` folder, the autoloader can't find `Config\App.php` only when Composer is enabled.
See https://forum.codeigniter.com/showthread.php?tid=81690
It is because the Composer's namespace paths overwrite the `Config\Autoload::$psr4` settings.
https://github.com/codeigniter4/CodeIgniter4/blob/faff1f8b151686283af67ea7dac5e45da629298e/system/Autoloader/Autoloader.php#L331
> If the input arrays have the same string keys, then the later value for that key will overwrite the previous one. …

fix: Composer PSR-4 overwrites Config\Autoload::$psr4

---

tests/README.md

Hi,it looks like correction was needed.
Referral link to **xdebug** was not valid.

docs: Correction link ``xdebug`` due to 404 Not Found

---

system/CLI/CLI.php
tests/system/CLI/CLITest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/cli/cli_library.rst

fix: using multiple CLI::color() in CLI::write() outputs strings with wrong color

---

rector.php

Ref https://github.com/codeigniter4/devkit/pull/23, it was removed at https://github.com/codeigniter4/CodeIgniter4/pull/5908 which I think because service removed instead of moved to `FunctionLike` namespace.
Thank you @kenjis for re-check.
**Checklist:**

[Rector] Add back SimplifyUselessVariableRector

---

phpstan-baseline.neon.dist
system/CodeIgniter.php
system/Router/AutoRouter.php
system/Router/RouteCollection.php
system/Router/RouteCollectionInterface.php
system/Router/Router.php
system/Router/RouterInterface.php
tests/system/Database/Migrations/MigrationRunnerTest.php
tests/system/Router/RouteCollectionTest.php
tests/system/Router/RouterTest.php
tests/system/Test/FeatureTestTraitTest.php
user_guide_src/source/changelogs/v4.2.0.rst

- extract class `AutoRouter` for auto-routing
- add `RouteCollection::getRegisteredControllers()`
- [BC] fix https://github.com/codeigniter4/CodeIgniter4/issues/2704#issuecomment-1094569051
- If a controller is added to cli routes, all methods of that controller are not accessible via auto routing
- fix failed tests
- tests/system/Database/Migrations/MigrationRunnerTest.php
- tests/system/Test/FeatureTestTraitTest.php
I want to introduce a new, more secure auto-routing. 
In this PR, I extract the AutoRouter class from the Router class in order to be able to easily replace the functionality.
Thoughts:
- ~~I wanted to avoid instantiating AutoRouter when auto routing is off. But the current implementation mixes the processing of defined routes and auto routes. So it was …

refactor: [Router] extract a class for auto-routing

---

env
user_guide_src/source/changelogs/v4.1.5.rst
user_guide_src/source/general/configuration.rst

A user did not know the functionality.
- fix heading level
- improve description for namespace separator `_`
- add comment in `env`
**Checklist:**

docs: improve configuration.rst

---

system/Database/MigrationRunner.php
system/Test/CIUnitTestCase.php
user_guide_src/source/dbmgmt/migration.rst
user_guide_src/source/testing/database.rst
user_guide_src/source/testing/database/003.php

Setting `null` in `$namespace` means all namespaces. It is not intuitive.
So we better explain it in all relevant places.
- add explanation for `null` in `$namespace`
- improve testing/database.rst format
- improve dbmgmt/migration.rst format
**Checklist:**

docs: improve migration namespace descriptions

---

phpstan-baseline.neon.dist
system/CodeIgniter.php

to allow remove ignored unreachable phpstan notice as the property is not filled on __construct.
**Checklist:**

[PHPStan] Allow null type for request property in CodeIgniter class

---

system/Router/Router.php
tests/system/Router/RouterTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/incoming/routing/022.php

PR adds the ability to use placeholders for route redirects.
```php
$routes->get('post/(:num)/comment/(:num)', 'PostsComments::index', ['as' => 'post.comment']);
// Redirect to a URI
$routes->addRedirect('article/(:num)/(:num)', 'post/$1/comment/$2');
// Redirect to a named route
$routes->addRedirect('article/(:num)/(:num)', 'post.comment');
```
**Checklist:**

Redirecting Routes. Placeholders.

---

system/Helpers/html_helper.php
tests/system/Helpers/HTMLHelperTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/helpers/html_helper.rst
user_guide_src/source/helpers/html_helper/011.php

For `<script />` elements, some attributes are usually written without values, for example :
`<script defer async src="..." />`
This is purely cosmetic as boolean attributes should also be accepted with an empty
value or a value identical to the attribute's name :
https://dev.w3.org/html5/pf-summary/infrastructure.html#boolean-attribute
**Checklist:**

script_tag: cosmetic for value-less attributes

---

user_guide_src/source/models/model.rst

Fixes #5377
I noticed there's a `getInsertID()` method in the `BaseModel` class (see https://github.com/codeigniter4/CodeIgniter4/blob/88e71c957730d9277ea14b6b2cae577fa305b36c/system/BaseModel.php#L684) and it hasn't been exposed to the user guide yet (if I'm not mistaken).
This will help so much in the case of automatically generated primary keys (like using auto-increment or automatically generated ID's via callbacks).

[docs/models] expose getInsertID() method

---

phpstan-baseline.neon.dist
system/Autoloader/FileLocator.php
system/CLI/BaseCommand.php

Fixes #5926
- fix types in doc comments
- update phpstan-baseline.neon.dist 
I got the following errors, so I also fixed them.
```
Run vendor/bin/phpstan analyse
Note: Using configuration file /home/runner/work/CodeIgniter4/CodeIgniter4/phpstan.neon.dist.
0/428 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
360/428 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░]  84%
428/428 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
------ ------------------------------------------------------- 
Line   system/Autoloader/FileLocator.php                      
------ ------------------------------------------------------- 
269    Offset 'prefix' does not exist on array{path: mixed}.  
------ ------------------------------------------------------- 
------ ----------------------------------------------------------------------- …
```

docs: fix BaseCommand $params @param

---

user_guide_src/source/libraries/pagination.rst

docs: improve pagination.rst

---

system/Helpers/url_helper.php
system/Router/RouteCollection.php
tests/system/Router/RouteCollectionTest.php
user_guide_src/source/general/common_functions.rst
user_guide_src/source/helpers/url_helper.rst
user_guide_src/source/incoming/routing/029.php

Fixes https://github.com/codeigniter4/CodeIgniter4/issues/5042#issuecomment-1112957814
Fixes #5934
The following code does not work now.
```php
$routes->get('users/(:num)/gallery(:any)', 'Galleries::showUserGallery/$1/$2');
$match = $routes->reverseRoute('Galleries::showUserGallery', 15, 12);
```
**Checklist:**

fix: Reverse Routing does not take into account the default namespace

---

tests/README.md

Explain about the activation `coverage ` that is required to run the **unit test**.

docs: enable code coverage.

---

composer.json
rector.php

Rector 0.12.23 resolve slowdown performance at version 0.12.22, ref issue and PR to fix it:
- https://github.com/rectorphp/rector/issues/7144
- https://github.com/rectorphp/rector-src/pull/2209
so parallel timeout increase settings is no longer needed.
**Checklist:**

[Rector] Update Rector to 0.12.23, clean up parallel timeout setting

---

system/Validation/Validation.php
tests/system/Validation/ValidationTest.php

Fixes #5922
Supersede #5925
**Checklist:**

fix:  [Validation] Fields with an asterisk throws exception

---

app/Config/Feature.php
phpstan-baseline.neon.dist
system/Router/AutoRouter.php
system/Router/AutoRouterImproved.php
system/Router/AutoRouterInterface.php
system/Router/Router.php
tests/system/Router/AutoRouterImprovedTest.php
tests/system/Router/Controllers/Dash_folder/Dash_controller.php
tests/system/Router/Controllers/Dash_folder/Home.php
tests/system/Router/Controllers/Dash_folder/MyController.php
tests/system/Router/Controllers/Dash_folder/Mycontroller.php
tests/system/Router/Controllers/Home.php
tests/system/Router/Controllers/Index.php
tests/system/Router/Controllers/MyController.php
tests/system/Router/Controllers/Mycontroller.php
tests/system/Router/Controllers/Remap.php
tests/system/Router/Controllers/Subfolder/MyController.php
tests/system/Router/Controllers/Subfolder/Mycontroller.php
tests/system/Router/Controllers/Test.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/incoming/controllers.rst
user_guide_src/source/incoming/controllers/020.php
user_guide_src/source/incoming/controllers/021.php
user_guide_src/source/incoming/controllers/022.php
user_guide_src/source/incoming/routing.rst

~~Needs to rebase after merging #5877~~
An optional new more secure auto router.
- add `AutoRouterImproved` class and `AutoRouterInterface`
- add `Config\Feature::$autoRoutesImproved` (`false` by default)
- use `AutoRouterImproved` in `Router` if enabled
`AutoRouterImproved` changes:
- A controller method needs HTTP verb prefix like `getIndex()`, `postCreate()`.
- Developers always know HTTP method, so requests by unexpected HTTP method does not happen.
- The Default Controller (`home` by default) and the Default Method (`index` by default) must be omitted in the URI.
- Restrict one-to-one correspondence between controller methods and URIs.
- By default, you can access `/`, but `/home` and `/home/index` are 404.
- It checks method parameter count.
- If there are more …

feat: new improved auto router

---

system/Database/BaseBuilder.php
system/Database/RawSql.php
tests/system/Database/Builder/LikeTest.php
tests/system/Database/Builder/SelectTest.php
tests/system/Database/Builder/WhereTest.php
tests/system/Database/RawSqlTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/database/query_builder.rst
user_guide_src/source/database/query_builder/099.php
user_guide_src/source/database/query_builder/100.php
user_guide_src/source/database/query_builder/101.php

Related: #4355, #3970, #5810
See https://forum.codeigniter.com/showthread.php?tid=80720
- add `RawSql` class
- `select()` supports `RawSql`
- `where()` supports `RawSql`
- `like()` supports `RawSql`
**Checklist:**

feat: QueryBuilder raw SQL string support

---

user_guide_src/source/testing/fabricator.rst
user_guide_src/source/testing/fabricator/005.php

- make titles linkable
- add example to return "return type object"
**Checklist:**

docs: improve fabricator.rst

---

user_guide_src/source/database/transactions.rst
user_guide_src/source/database/transactions/007.php

There's an explanation that a nested transaction is possible in CodeIgniter 4 by keeping track of the transaction depth (see https://github.com/codeigniter4/CodeIgniter4/blob/febc03a555b222a7a5617f04d7ba2058700cfdb1/system/Database/BaseConnection.php#L766).
I want it to be clearly documented so developers can save their time instead of figuring out by examining the system/ folder.
This implies that every start (transStart/transBegin) command should behave the same as others (pushing the transaction depth) and complete (transComplete/transCommit/transRollback) command should also behave the same as the others (popping the transaction depth) as a requirement. I've examined the code and they actually behave like that so I think it's safe to document this feature.

[docs] add DB nested transaction

---

user_guide_src/source/libraries/validation.rst

- add missing `'`
**Checklist:**

docs: small fix in validation.rst

---

app/Views/errors/html/error_exception.php
system/CodeIgniter.php
system/Debug/Toolbar.php
system/Router/Router.php
system/Validation/Validation.php

Supersedes #5766
The `$upper` functionality will be removed.
**Checklist:**

refactor: add strtolower() to Request::getMethod()

---

admin/css/debug-toolbar/toolbar.scss
system/Debug/Toolbar.php
system/Debug/Toolbar/Collectors/History.php
system/Debug/Toolbar/Views/_history.tpl
system/Debug/Toolbar/Views/toolbar.css
tests/system/Debug/Toolbar/Collectors/HistoryTest.php
user_guide_src/source/changelogs/v4.2.0.rst

Supersedes #5643
I was not able to rebase #5643 because of too many conflicts.
**Checklist:**

feat: Debugbar request microtime

---

system/Images/Handlers/GDHandler.php
tests/system/Images/GDHandlerTest.php

fix: Images\Handlers\GDHandler Implicit conversion from float to int loses precision

---

system/Images/Handlers/GDHandler.php

Fixes  #4178
**How to Test:**
Prepare `sample.png` with transparency.
```php
<?php
{
{
\Config\Services::image('gd')
->withFile(WRITEPATH . 'sample.png')
->reorient()
->save(WRITEPATH . 'new.png', 70);
}
}
```
Run the controller, and see `new.png`.
**Checklist:**

fix: GDHandler::save() removes transparency

---

app/Config/Routes.php
system/Commands/Utilities/Routes.php
system/Commands/Utilities/Routes/AutoRouterImproved/AutoRouteCollector.php
system/Commands/Utilities/Routes/AutoRouterImproved/ControllerMethodReader.php
system/Commands/Utilities/Routes/FilterCollector.php
tests/_support/Controllers/Newautorouting.php
tests/system/Commands/Utilities/Routes/AutoRouteCollectorTest.php
tests/system/Commands/Utilities/Routes/AutoRouterImproved/AutoRouteCollectorTest.php
tests/system/Commands/Utilities/Routes/AutoRouterImproved/ControllerMethodReaderTest.php
tests/system/Commands/Utilities/Routes/ControllerFinderTest.php
user_guide_src/source/incoming/routing.rst

Follow-up #5889
- `spark routes` update
**Checklist:**

feat: new improved auto router `spark routes` command

---

system/Router/RouteCollection.php
tests/system/Router/RouteCollectionTest.php

Fixes  #5959
```php
// Limit to any sub-domain
$routes->add('from', 'to', ['subdomain' => '*']); // not work
```
**Checklist:**

fix: route limit to subdomains does not work

---

phpstan-baseline.neon.dist
system/Model.php
tests/system/Models/FindModelTest.php

Fixes #4509
- remove `@mixin BaseBuilder`, add `@method`
**Checklist:**

fix: Model::_call() static analysis

---

tests/system/Router/RouteCollectionTest.php

Follow-up #5962
I don't know why #5962 tests passed, but the current `develop` tests fail.
**Checklist:**

test: RouteCollectionTest

---

user_guide_src/source/testing/debugging.rst

docs: make method names linkable in debugging.rst

---

user_guide_src/source/database/results.rst

docs: improve database/results.rst

---

user_guide_src/source/testing/debugging.rst

dies() may be linguistically more correct, but I would write die() here

change dies() to php's function name die()

---

user_guide_src/source/models/model.rst

docs: add that `deleted_at` column must be nullable

---

user_guide_src/source/testing/response.rst

- fix text decration
**Checklist:**

docs: improve testing/response.rst

---

.github/workflows/deploy-userguide-latest.yml
user_guide_src/add-edit-this-page

- add "Edit this page" button to https://codeigniter4.github.io/CodeIgniter4/
**Checklist:**

chore: add "Edit this page" to the userguide latest

---

user_guide_src/source/testing/controllers.rst

docs: make method names linkable in testing/controllers.rst

---

user_guide_src/source/libraries/files.rst

docs: make method names linkable in files.rst

---

system/Commands/Database/ShowTableInfo.php
tests/system/Commands/Database/ShowTableInfoTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/database/examples.rst
user_guide_src/source/database/metadata.rst
user_guide_src/source/dbmgmt/db_commands.rst
user_guide_src/source/dbmgmt/index.rst

Supersedes and closes #5895
```
Usage:
db:table [<table_name>] [options]
Description:
Retrieves information on the selected table.
Arguments:
table_name  The table name to show info
Options:
--show               Lists the names of all database tables.
--metadata           Retrieves list containing field information.
--desc               Sorts the table rows in DESC order.
--limit-rows         Limits the number of rows. Default: 10.
--limit-field-value  Limits the length of field values. Default: 15.
```
**Checklist:**

feat: `db:table` command

---

contributing/documentation.rst

- update contributing/documentation.rst
**Checklist:**

docs: add how to link in contributing/documentation.rst

---

public/index.php
spark
system/bootstrap.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/installation/upgrade_420.rst

When we want to use [Preloading](https://www.php.net/manual/en/opcache.preloading.php), we need CI4 Autoloader.
But it is not easy to make the Autoloader work fine.
If you use this `system/bootstrap.php`, you can make it a bit easily.
- move `CodeIgniter` instantiation and `DotEnv` loading from `system/bootstrap.php`
- tweak `index.php` and `spark.php`
**Checklist:**

refactor: `system/bootstrap.php` only loads files and registers autoloader

---

app/Config/Constants.php
system/Events/Events.php
tests/system/Events/EventsTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/extending/events.rst
user_guide_src/source/extending/events/004.php
user_guide_src/source/installation/upgrade_420.rst

Fixes #5977
- deprecated `EVENT_PRIORITY_*`
- add `Events::PRIORITY_*`
**Checklist:**

refactor: deprecate const `EVENT_PRIORITY_*`

---

system/Events/Events.php

Follow-up  #6000
EVENT_PRIORITY_NORMAL still remained.
**Checklist:**

fix: replace EVENT_PRIORITY_NORMAL with Events::PRIORITY_NORMAL

---

system/Router/Router.php
tests/system/Router/RouterTest.php

Fixes https://github.com/codeigniter4/CodeIgniter4/issues/5997
The locale was determined incorrectly if the placeholder `(:any)` was specified in the route.
Search for `{locale}` by splitting path segments into an array has been replaced with a search through a regular expression using a named group.
**Checklist:**

Fix: Route placeholder (:any) with {locale}

---

user_guide_src/source/changelogs/v4.2.0.rst

An improvement has been added for the BaseBuilder::buildSubquery() method, but there is no information about it in the changelog about it.
**Checklist:**

The changelog is missing info about the change.

---

system/Helpers/array_helper.php
tests/system/Helpers/ArrayHelperTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/helpers/array_helper.rst

fix: `dot_array_search()` unexpected behavior

---

tests/system/Images/ImageMagickHandlerTest.php

When there is no `/usr/bin/convert`, the errors occurs.
**Checklist:**

test: change Config\Images::$libraryPath only when the file exists

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/FromTest.php
tests/system/Database/Builder/SelectTest.php
user_guide_src/source/database/query_builder/015.php
user_guide_src/source/database/query_builder/017.php
user_guide_src/source/database/query_builder/018.php

Because Oracle does not support using the ``AS`` keyword for table aliases. 
This PR removes the ``AS`` keyword when building subqueries.
**Checklist:**

Changing the subquery builder for the Oracle

---

composer.json

Temporary pin PHPStan to 1.6.9 as updating to PHPStan 1.7.0 seems cause infinite loop when used along with Rector somewhere.
**Checklist:**

[PHPStan] Pin PHPStan to v1.6.9

---

system/Database/BaseBuilder.php
system/Database/Postgre/Builder.php
system/Database/SQLSRV/Builder.php
tests/system/Database/Builder/JoinTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/database/query_builder.rst
user_guide_src/source/database/query_builder/102.php
user_guide_src/source/installation/upgrade_420.rst

~~Needs to rebase after merging #5817~~
Related #3832
- `join()` supports `RawSql`
**Checklist:**

feat: QueryBuilder join() raw SQL string support

---

composer.json
phpstan-baseline.neon.dist
tests/system/Filters/FiltersTest.php

@paulbalandan @kenjis @MGatner update to PHPStan 1.7.1 seems fix infinite loop issue on 1.7.0 on https://github.com/codeigniter4/CodeIgniter4/pull/6019
- Also re-run rector to apply `PrivatizeFinalClassPropertyRector` on `FilterTest.php`
- Also Clean up ignored PHPStan errors.
**Checklist:**

[PHPStan] Update to PHPStan ^1.7.1

---

app/Config/Routes.php
system/CodeIgniter.php
system/Commands/Encryption/GenerateKey.php
system/Test/bootstrap.php
tests/system/Commands/CommandGeneratorTest.php
tests/system/Commands/ControllerGeneratorTest.php
tests/system/Commands/CreateDatabaseTest.php
tests/system/Commands/GenerateKeyTest.php
tests/system/Commands/MigrationGeneratorTest.php
tests/system/Commands/ScaffoldGeneratorTest.php
tests/system/Commands/SeederGeneratorTest.php
tests/system/HTTP/Files/FileMovingTest.php
tests/system/Test/BootstrapFCPATHTest.php

`file_exists()` will confirm hit on any system object (e.g. directory) as well as being less efficient. This switches to `is_file()` wherever relevant.
**Checklist:**

Prefer `is_file()`

---

system/Config/BaseService.php
system/Test/CIUnitTestCase.php

`BaseService::reset(false)` makes the autoloader's namespaces empty.
Such use cases are rare and will prevent `lang()` from working. See https://github.com/codeigniter4/shield/issues/88#issuecomment-1134594714
- change `BaseService::reset()` default parameter value to `true`
- change `CIUnitTestCase::resetServices()` default parameter value to `true`
**Checklist:**

fix: change BaseService::reset() $initAutoloader to true by default

---

system/Database/Forge.php
tests/system/Database/Forge/CreateTableTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/dbmgmt/forge.rst
user_guide_src/source/dbmgmt/forge/027.php

~~Needs to rebase after merging #5875~~
Fixes #4174 
Supersedes #4222
- `DBForge::addField()` default support `RawSql`
```php
$fields = [
'id' => [
'type'           => 'INT',
'constraint'     => 5,
'unsigned'       => true,
'auto_increment' => true,
],
'ts' => [
'type'    => 'TIMESTAMP',
'default' => new RawSql('CURRENT_TIMESTAMP'),
],
];
$forge->addField($fields);
```
**Checklist:**

feat: DBForge::addField() `default` value raw SQL string support

---

user_guide_src/source/changelogs/v4.2.0.rst

Follow-up #6020
**Checklist:**

docs: add changelog about Service::reset()

---

system/Autoloader/FileLocator.php

- use get_filenames() 4th param
**Checklist:**

refactor: use get_filenames() 4th param in FileLocator

---

system/HTTP/CURLRequest.php
tests/system/HTTP/CURLRequestDoNotShareOptionsTest.php
user_guide_src/source/libraries/curlrequest.rst

fix: CURLRequest request body is not reset on the next request

---

preload.php
user_guide_src/source/changelogs/v4.2.0.rst

~~Needs to rebase after merging #5972~~
Ref #6000
- add sample file for [Preloading](https://www.php.net/manual/en/opcache.preloading.php)
In the Welcome Page benchmark in my local, the values improved as follows:
```
280 rps --> 330
```
**Checklist:**

Add sample file for preloading

---

rector.php
tests/system/Database/Forge/CreateTableTest.php
tests/system/Debug/Toolbar/Collectors/DatabaseTest.php

Apply PHPUnitSetList::REMOVE_MOCKS to remove unnecessary mock calls.
**Checklist:**

[Rector] Apply PHPUnitSetList::REMOVE_MOCKS

---

system/Database/SQLSRV/Connection.php
user_guide_src/source/changelogs/v4.2.0.rst

Fixes https://github.com/codeigniter4/CodeIgniter4/issues/6032
The SQLSRV driver ignores the port value from the config.
This PR fixes a bug.
Also, if a port is already specified in the hostname, the port from the configuration will be ignored.
It seems to me that the default tests are enough, because the database connection settings for the tests use the default port, which was ignored when configuring the connection.
**Checklist:**

Bug: The SQLSRV driver ignores the port value from the config.

---

user_guide_src/source/concepts/security.rst
user_guide_src/source/helpers/form_helper.rst
user_guide_src/source/libraries/validation.rst

- Form validation is a library name in CI3
**Checklist:**

docs: replace "form validation" with "validation"

---

system/Database/BaseBuilder.php
system/Database/SQLSRV/Builder.php
tests/system/Database/Builder/UnionTest.php
tests/system/Database/Live/UnionTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/database/query_builder.rst
user_guide_src/source/database/query_builder/103.php
user_guide_src/source/database/query_builder/104.php

This is the second attempt to add a query union to QueryBuilder.
Ref #4291
The implementation provides two methods:
-  `BaseBuilder::union(BaseBuilder|Closure $union)`
-  `BaseBuilder::unionAll(BaseBuilder|Closure $union)`
The union() method can be called in any order relative to the main query, but the union query will always be appended to the end. That is, the ``LIMIT`` or ``ORDER BY`` clauses will be relative to the main query.
```php
$builder->union($union)->limit(1)->orderBy('id');
// SELECT * FROM table LIMIT 1 ORDER BY id UNION query
```
Since DBMSs (MSSQL and Oracle) are demanding on queries using ``LIMIT`` and ``ORDER BY``, when generating SQL, all queries are wrapped in a ``SELECT * FROM(....) alias`` query.
The alias uwrp0 is used for the main query. Each …

Feature. QueryBuilder. Query union.

---

system/Helpers/form_helper.php
tests/system/Helpers/FormHelperTest.php
user_guide_src/source/helpers/form_helper.rst

fix: `set_radio()` not working as expected

---

.editorconfig
app/Views/errors/html/debug.css
app/Views/errors/html/debug.js
app/Views/errors/html/error_404.php
app/Views/errors/html/error_exception.php
app/Views/errors/html/production.php
app/Views/welcome_message.php
app/index.html
system/Debug/Toolbar/Views/_config.tpl
system/Debug/Toolbar/Views/toolbar.js
system/Debug/Toolbar/Views/toolbar.tpl.php

Supersedes #6010
Indent the View files with 4 spaces.
The only one exception is `system/Debug/Toolbar/Views/toolbar.css`.
It is generated by scss and it uses space 2 indentation.
- update editorconfig
- fix indentation in View files
**Checklist:**

chore: update editorconfig and fix indent in views

---

system/CodeIgniter.php

If a user updates CI on production server, `assert()` may not work.
**Checklist:**

refactor: CodeIgniter $context check

---

user_guide_src/source/database/configuration.rst
user_guide_src/source/database/configuration/001.php
user_guide_src/source/database/configuration/002.php
user_guide_src/source/database/configuration/003.php
user_guide_src/source/database/configuration/004.php
user_guide_src/source/database/configuration/009.php

- updates and improvements
**Checklist:**

docs: improve database/configuration.rst

---

system/Database/SQLite3/Connection.php
user_guide_src/source/database/configuration.rst

~~Need to rebase after merging #6049~~
Fixes #6008
- add DB config `foreignKeys` for SQLite3 (disabled by default)
```php
<?php
use Config\Database;
{
{
$group = [
'database'    => 'sqlite3.db',
'DBDriver'    => 'SQLite3',
'DBPrefix'    => 'db_',
'DBDebug'     => (ENVIRONMENT !== 'production'),
'foreignKeys' => true, // Add the config
];
$db = \Config\Database::connect($group);
$this->forge = Database::forge($group);
$this->createTableAuthUsers();
$this->createTableAuthIdentities();
$prefix = $db->getPrefix();
$sql = "INSERT INTO {$prefix}auth_identities"
. ' (user_id, type, secret, created_at)'
. " VALUES (2, 'email_2fa', '479123', '2022-05-18 23:01:46')"; …
```

fix: add config for SQLite3 Foreign Keys

---

system/CodeIgniter.php
tests/system/CodeIgniterTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/installation/upgrade_420.rst

In this PR, I added an exclusion condition for `storePreviousURL`: "Response Content-Type is not text/html".
**Background**
In our application, some images are composited in the CodeIgnitor controller and returned.
The request URL for such case is saved as `_ci_previous_url` because it does not meet any of the exclusion conditions of the existing `storePreviousURL` implementation, and when redirecting back, etc., there is a case where the request is redirected to the URL of the image.
The URL to store as `previous_url` is usually considered to be an HTML (`text/html`) case, so I have added that as a condition.
**Checklist:**

fix: Ignore non-HTML responses in storePreviousURL

---

system/Database/Postgre/Connection.php
tests/system/Database/Live/ForgeTest.php

- support nullable on postgre
**Checklist:**

feat: `getFieldData()` returns nullable data on PostgreSQL

---

system/Database/BaseConnection.php
system/Database/SQLite3/Table.php
tests/system/Database/Live/SQLite/AlterTableTest.php

Fixes #5946
- fix `SQLite3\Table::copyData()`
- fix SQLite3 test assertion that raises a hidden error
**Checklist:**

fix: SQLite3\Table::copyData() does not escape column names

---

contributing/workflow.md

The step after pushing PR is missing.
**Checklist:**

docs: add "Updating Your Branch" in contributing/workflow.md

---

system/Language/en/Validation.php

There is a missing language string for the valid_url_strict rule.
**Checklist:**

add missing valid_url_strict language string

---

system/Common.php
tests/system/CommonFunctionsTest.php

Supersedes and closes #5973 
Fixes #5967 
**Checklist:**

Fix `slash_item()` erroring when property fetched does not exist on `Config\App`

---

user_guide_src/source/installation/repositories.rst

- update repositories.rst
**Checklist:**

docs: update repositories.rst

---

contributing/documentation.rst

- add how to link to a function
I don't know why, but the following does not work.
```
:php:meth:`Response::setCookie() <CodeIgniter\\HTTP\\Response::setCookie>`
```
See https://github.com/markstory/sphinxcontrib-phpdomain#quick-sample
**Checklist:**

docs: add how to link to a function in contributing/documentation.rst

---

CHANGELOG.md
admin/RELEASE.md
system/CodeIgniter.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/conf.py
user_guide_src/source/installation/upgrade_420.rst

Updates changelog and version references for 4.2.0.
**Checklist:**

Prep for 4.2.0 release

---

user_guide_src/source/database/query_builder.rst

Adds information that ignore() can be used in insertBatch, update and delete (when database supports it).
Not really clear on the docs at the moment.
State that ignore() can be used in insertBatch(), update() and delete(), not only insert().
**Checklist:**

Adds information that ignore() is not unique to insert

---

user_guide_src/source/installation/upgrade_4xx.rst
user_guide_src/source/installation/upgrade_routing.rst

- update Routing for v4.2
**Checklist:**

docs: update "Upgrading from 3.x to 4.x" Routing for v4.2

---

user_guide_src/source/extending/authentication.rst
user_guide_src/source/libraries/official_packages.rst

- add about Shield
**Checklist:**

docs: update authentication.rst

---

system/Helpers/cookie_helper.php

fix: get_cookie() does not take Config\Cookie::$prefix

---

user_guide_src/source/cli/cli_controllers.rst

docs: fix typo in cli_controllers.rst

---

system/HTTP/ResponseTrait.php
system/Helpers/cookie_helper.php
user_guide_src/source/helpers/cookie_helper.rst
user_guide_src/source/libraries/cookies/002.php
user_guide_src/source/outgoing/response.rst

- update `set_cookie()`
- update `Response::setCookie()`
Ref https://github.com/codeigniter4/CodeIgniter4/issues/6009#issuecomment-1136003776
**Checklist:**

docs: add about setCookie() prefix details

---

system/Cookie/Cookie.php
system/Session/Session.php
tests/system/Cookie/CookieTest.php

- fix Session Cookie name may have Cookie Config prefix
- it must be ignored. 
- "Additionally, the Config\Cookie::$prefix setting is completely ignored." https://codeigniter.com/user_guide/libraries/sessions.html#session-preferences
- fix Cookie class option prefix bug
- if option prefix is `'0'`, it is not set. Ref, https://github.com/codeigniter4/CodeIgniter4/pull/6083#issuecomment-1148176438
**Checklist:**

fix: session cookie name bug

---

system/Session/Handlers/BaseHandler.php

- fix Session Handlers do not take `Config\Cookie`
Related:  #6080
**Checklist:**

fix: Session Handlers do not take Config\Cookie

---

system/View/ViewDecoratorTrait.php
user_guide_src/source/outgoing/view_decorators.rst
user_guide_src/source/outgoing/view_decorators/001.php

Fixed a typo for View Decorators documentation. Also, the current code, while passing tests, wasn't working
for me in a real-word test. Modified to better check the class implements the ViewDecoratorInterface.
**Checklist:**

Fix decorators

---

system/Cache/Handlers/MemcachedHandler.php

It is useless to catch the exception then rethrow it without doing anything on it.
**Checklist:**

Remove useless catch

---

system/Debug/Toolbar/Views/toolbar.css

It seems the latest sass changed the output.
`sass --no-source-map admin/css/debug-toolbar/toolbar.scss system/Debug/Toolbar/Views/toolbar.css`
**Checklist:**

style: compile sass

---

app/Config/Mimes.php
system/Files/File.php
tests/system/Files/FileTest.php
tests/system/HTTP/Files/FileCollectionTest.php
user_guide_src/source/changelogs/index.rst
user_guide_src/source/changelogs/v4.2.1.rst
user_guide_src/source/installation/upgrade_421.rst
user_guide_src/source/installation/upgrading.rst

Fixes #6046 by relying on the path extension as the `$proposedExtension` argument to `Config\Mimes::guessExtensionFromType()`. The extension is derived using `pathinfo()`
However, this fix also changes the behavior of the guessing if a proposed extension is given. Previously, if the proposal is invalid, the guessing ends and returns `null`. Now, this early termination is removed and the guessing is continued using the array mapping of extension to MIME types.
**Checklist:**

Fix MIME guessing of extension from type

---

system/Router/RouteCollection.php
tests/system/Router/RouteCollectionReverseRouteTest.php
tests/system/Router/RouteCollectionTest.php

Reported in https://forum.codeigniter.com/showthread.php?tid=82070&pid=396927#pid396927
Follow-up  #5936
- fix handlder starting with `\` does not work
- E.g., `url_to('\App\Controllers\backend\Dashboard::index')`
- refactor
**Checklist:**

fix: reverse routing does not work with full classname starting with `\`

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/InsertTest.php

- fix error message
**Checklist:**

fix: insert error message in QueryBuilder

---

system/Commands/Utilities/Routes/AutoRouterImproved/AutoRouteCollector.php

Whe you enable Auto Route Improved,
By adding the method `Home::getTest`, the command `php spark routes` gives the result:
```
ERROR: 404
Cannot access the default controller "Home" with the controller name URI path.
```
Reported in #6097
```diff
diff --git a/app/Config/Feature.php b/app/Config/Feature.php
index 4c5ec90cd..480697b61 100644
--- a/app/Config/Feature.php
+++ b/app/Config/Feature.php
@@ -28,5 +28,5 @@ class Feature extends BaseConfig
/**
* Use improved new auto routing instead of the default legacy version.
*/
-    public bool $autoRoutesImproved = false;
+    public bool $autoRoutesImproved = true;
}
```
```diff
diff --git a/app/Config/Routes.php b/app/Config/Routes.php
index ff2ac645c..78a76bc5c 100644
+++ …
```

fix: `spark routes` shows "ERROR: 404"

---

tests/system/Models/InsertModelTest.php

testInsertResultFail is set DBdebug in false.
so that means a lost error message when after a testInsertResultFail run.
The test developer can not understand the failure reason.
**Checklist:**

Fix lost error message by test when after testInsertResultFail.

---

user_guide_src/source/libraries/files.rst

- fix section title level
```
/github/workspace/user_guide_src/source/libraries/files.rst:142: CRITICAL: Title level inconsistent:
add(string[]|string $paths, bool $recursive = true)
---------------------------------------------------
```
**Checklist:**

docs: fix syntax error in files.rst

---

system/I18n/Time.php
tests/system/I18n/TimeTest.php

fix: Time::setTestNow() does not work with fa Locale

---

user_guide_src/source/libraries/time.rst
user_guide_src/source/libraries/time/015.php
user_guide_src/source/libraries/time/016.php
user_guide_src/source/libraries/time/017.php
user_guide_src/source/libraries/time/018.php

- improve explanation of `toDateTimeString()` `toDateString()` `toTimeString()`
Related #6116
**Checklist:**

docs: improve time.rst

---

system/Database/MigrationRunner.php

Fixes https://github.com/codeigniter4/shield/issues/240
See https://github.com/codeigniter4/shield/issues/240#issuecomment-1153594113
- skip `Tests\Support` namespace in not `testing` environments
**`Tests\Support` namespace is not defined in `codeigniter4/CodeIgniter4`.**
Install appstarter. 
```
$ composer create-project codeigniter4/appstarter ci4app
```
Configure default database.
Change tests database driver.
```diff
--- a/app/Config/Database.php
+++ b/app/Config/Database.php
@@ -62,7 +62,7 @@ class Database extends Config
'username'    => '',
'password'    => '',
'database'    => ':memory:',
-        'DBDriver'    => 'SQLite3',
+        'DBDriver'    => 'xSQLite3',
'DBPrefix'    => 'db_',  // Needed to ensure we're working correctly with prefixes …
```

fix: `migrate --all` causes `Class "SQLite3" not found` error

---

system/Test/DatabaseTestTrait.php
tests/system/Database/Live/BadQueryTest.php
tests/system/Database/Live/DbDebugTest.php
tests/system/Database/Live/DbUtilsTest.php
tests/system/Models/DeleteModelTest.php
tests/system/Models/InsertModelTest.php
tests/system/Models/SaveModelTest.php
tests/system/Models/UpdateModelTest.php

- add `disableDBDebug()` and `enableDBDebug()` in `DatabaseTestTrait`
- add missing `enableDBDebug()`
- refactor
Related #6113
**Checklist:**

test: fix forgetting to restore DBDebug value

---

system/Exceptions/PageNotFoundException.php
system/Language/en/HTTP.php
system/Router/RouteCollection.php
system/Router/RouteCollectionInterface.php
system/Router/Router.php
tests/system/Router/RouteCollectionTest.php
user_guide_src/source/outgoing/localization.rst
user_guide_src/source/outgoing/localization/018.php

Adds a control flag so that the ``Router`` only validates the locales ​​that are defined in ``App::$supportedLocales``, returning an ``CodeIgniter\Exceptions\PageNotFoundException::forLocaleNotSupported()`` if the locale introduced is not supported.
**Checklist:**

feat: add routes useSupportedLocalesOnly property

---

phpstan-baseline.neon.dist
system/Database/BaseConnection.php
user_guide_src/source/extending/events.rst

> DBQuery
This event is triggered whenever a new query has been run, whether successful or not.
https://codeigniter4.github.io/CodeIgniter4/database/events.html#the-events
But the event `DBQuery` is not fired on failed query when `DBDebug` is true.
- fix BaseConnection
- fix user guide
```diff
--- a/app/Config/Events.php
+++ b/app/Config/Events.php
@@ -46,3 +46,8 @@ Events::on('pre_system', static function () {
Services::toolbar()->respond();
}
});
+
+Events::on(
+    'DBQuery',
+    static function (\CodeIgniter\Database\Query $query) { log_message('alert', (string) $query); }
+);
diff --git a/app/Controllers/Home.php b/app/Controllers/Home.php
index 7f867e95f..492606d92 100644
--- a/app/Controllers/Home.php
+++ b/app/Controllers/Home.php
@@ -6,6 +6,8 @@ …
```

fix: event DBQuery is not fired on failed query when DBDebug is true

---

system/I18n/Time.php
tests/system/I18n/TimeTest.php

Need to rebase after merging #6116
Fixes #4708
Related #6116
**Checklist:**

fix: `Time::humanize()` causes error with ar locale

---

system/CodeIgniter.php

docs: fix PHPDoc in CodeIgniter

---

contributing/pull_request.md

- update about Changelog
- add about Upgrading Guide
**Checklist:**

docs: update about mainly Changelog in contributing/pull_request.md

---

user_guide_src/source/models/model.rst
user_guide_src/source/models/model/021.php

Updated Model example with `$returnType` to use `::class` instead of string literal.
https://forum.codeigniter.com/showthread.php?tid=82127&pid=397352#pid397352
**Checklist:**

Updated to use ::class in $returnType example

---

system/Helpers/cookie_helper.php
tests/system/Helpers/CookieHelperTest.php
user_guide_src/source/changelogs/v4.2.1.rst
user_guide_src/source/helpers/cookie_helper.rst
user_guide_src/source/installation/upgrade_421.rst

~~Needs to rebase after merging #6080~~
Fixes #6009
Supersede #6024
The current `get_cookie()` behavior is strange. See **Behavior Changes** below.
This PR changes it the following:
- `get_cookie($index)` always use the cookie prefix in Config file
- `get_cookie($index, $xssClean, null)` never uses the cookie prefix
**Behavior Changes**
When the cookie prefix is `prefix_` and
```php
$_COOKIES = [
'prefix_test' => 'CI cookie',
'test'        => 'Non CI cookie',
];
```
Before:
```php
get_cookie('test');        // Non CI cookie
get_cookie('prefix_test'); // CI cookie
```
After:
```php
get_cookie('test');              // CI cookie
get_cookie('prefix_test');       // null
get_cookie('test', false, null); // Non CI cookie
```
**Checklist:**

fix: get_cookie() may not use the cookie prefix

---

admin/starter/app/Config/Paths.php
app/Config/App.php
app/Config/Logger.php
app/Config/Paths.php
system/HTTP/IncomingRequest.php
system/HTTP/MessageInterface.php
system/HTTP/MessageTrait.php
system/HTTP/Negotiate.php
system/HTTP/Response.php
system/HTTP/ResponseInterface.php
system/Test/Mock/MockLogger.php

- fix comments
See https://github.com/codeigniter4/CodeIgniter4/commit/f524c25cb04301b00f06905321d26628909a6e3e
**Checklist:**

docs: replace getServer with server in comments

---

system/Commands/Utilities/Namespaces.php
tests/system/Commands/Utilities/NamespacesTest.php

- improve output of `namespaces` command
- add options
- `-c`:  show CodeIgniter namespace only
- `-r`: show raw path strings
- `-m`: specify max length of the path strings
```console
$ php spark namespaces -c
CodeIgniter v4.2.1 Command Line Tool - Server Time: 2022-06-17 02:43:54 UTC-05:00
+-------------+-----------------+--------+
| Namespace   | Path            | Found? |
+-------------+-----------------+--------+
| CodeIgniter | ROOTPATH/system | Yes    |
| App         | ROOTPATH/app    | Yes    |
| Config      | APPPATH/Config  | Yes    |
+-------------+-----------------+--------+
```
```console
$ php spark namespaces 
CodeIgniter v4.2.1 Command Line Tool - Server Time: 2022-06-17 02:44:09 UTC-05:00
+-----------------+----------------------------------------+--------+ …
```

feat: improve namespaces command

---

system/Database/BaseBuilder.php
system/Database/Postgre/Builder.php
system/Database/SQLSRV/Builder.php
tests/system/Database/Live/IncrementTest.php
user_guide_src/source/changelogs/v4.2.2.rst

https://github.com/codeigniter4/CodeIgniter4/issues/6145
**Checklist:**

Fixed: BaseBuilder increment/decrement do not reset state after a query

---

user_guide_src/source/incoming/routing.rst

- It is recommended to use Spark command
**Checklist:**

docs: `$routes->cli()` method is no longer recommended

---

system/Database/SQLite3/Connection.php

Fixes #6151
- add missing DB initialization
**Checklist:**

fix: SQLite3\Connection\getIndexData() error

---

system/Validation/FileRules.php
tests/system/Validation/FileRulesTest.php
tests/system/Validation/StrictRules/FileRulesTest.php

Fixes #6155
Fixes #6156
**Checklist:**

fix: `is_image` causes PHP 8.1 deprecated error

---

system/BaseModel.php
system/Model.php
system/Validation/FileRules.php
tests/system/Models/InsertModelTest.php
tests/system/Validation/FileRulesTest.php
tests/system/Validation/StrictRules/FileRulesTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/models/model.rst
user_guide_src/source/models/model/056.php

- add `Model::allowEmptyInserts()` to insert empty data
**Checklist:**

feat: add method to insert empty data in Model

---

user_guide_src/source/general/errors/005.php
user_guide_src/source/general/errors/006.php
user_guide_src/source/incoming/routing/043.php

- not `App\Config`, but `Config`
**Checklist:**

docs: fix wrong namespace `App\Config`

---

app/Config/Database.php
system/Database/BaseConnection.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/database/configuration.rst
user_guide_src/source/database/connecting/006.php

See  #6132
- change the default config to always throw an exception when DB error occurs
**Checklist:**

config: DB Error always throws Exception

---

system/I18n/Time.php
tests/system/I18n/TimeTest.php

- fix `Time::getAge()` calculation
- fix test case
> Returns the age, in years, of between the Time’s instance and the current time. **Perfect for checking the age of someone based on their birthday**:
https://codeigniter4.github.io/CodeIgniter4/libraries/time.html#getage
There are a few ways to calculate human age.
However, the current implementation does not seem to be common.
E.g.:
- birthdate: December 31, 2020
- now: January 1, 2022
- age: 2
**Checklist:**

fix: Time::getAge() calculation

---

user_guide_src/source/testing/controllers/006.php

There is a mistake in the example code in the documentation for testing controllers using an instance of the IncomingRequest class. The $userAgent argument was not specified.
Although the $userAgent parameter in the constructor of the IncomingRequest class can be null, this will cause an exception to be thrown.
https://github.com/codeigniter4/CodeIgniter4/blob/01804793734610951b4eb4a3e8b1cbfc7826cfc6/system/HTTP/IncomingRequest.php#L150-L154
**Checklist:**

Doc: Incorrect example of creating an IncomingRequest instance.

---

system/Test/ControllerTestTrait.php

Replacing the return type in the ControllerTestTrait methods in the docBlock section from mixed to $this.
This allows the IDE to use hints in the chain call.
**Checklist:**

Change: PHPDoc return type in ControllerTestTrait methods

---

tests/system/Database/Builder/WhereTest.php

- check behavior for various type values
- this is security checking
- some ORMs have unexpected feature to devs, and easily results in SQL injection
- it seems there is no problem
**Checklist:**

test: add tests for various types of values to where() in QueryBuilder

---

admin/framework/.github/workflows/close-pull-request.yml
admin/starter/.github/workflows/close-pull-request.yml
admin/userguide/.github/workflows/close-pull-request.yml

Adding a close PR action to automatically close PRs in the splits (framework, starter, userguide) and direct them to submit the PR to this repo.
**Checklist:**

Add close PR action for repo splits

---

admin/RELEASE.md

- the step to update local 4.x branch was missing
**Checklist:**

docs: fix how to update next minor upgrade branch

---

user_guide_src/source/extending/core_classes.rst

- improve extending/core_classes.rst
**Checklist:**

docs: improve extending/core_classes.rst

---

tests/system/Validation/RulesTest.php

- fix tests for permit_empty
**Checklist:**

test: fix tests for permit_empty

---

system/Database/BaseBuilder.php
system/Database/BaseConnection.php
tests/system/Database/BaseConnectionTest.php
tests/system/Database/Builder/SelectTest.php

fixes #4311
fixes #4355
I'm not sure correct behavior of `protectIdentifiers()`. See [tests](https://github.com/codeigniter4/CodeIgniter4/pull/5118/files#diff-65d39fd097198820866d41c227f1afbb8db3498670ad049d13f87ad6df2cc97e).
**Checklist:**

fix: QueryBuilder breaks select when escape is false

---

system/API/ResponseTrait.php
system/CodeIgniter.php
system/Config/BaseService.php
system/Config/Services.php
system/Debug/Exceptions.php
system/HTTP/CLIRequest.php
system/HTTP/IncomingRequest.php
tests/system/CommonSingleServiceTest.php
tests/system/HTTP/IncomingRequestTest.php
user_guide_src/source/changelogs/index.rst
user_guide_src/source/changelogs/v4.2.2.rst

Fixes https://github.com/codeigniter4/CodeIgniter4/issues/6086
The current implementation has two Request objects (`IncommingRequest` and `CLIRequest`) when running on CLI.
Because some classes call `Services::request()` inside and it always returns `IncommingRequest`.
When `CLIRequest` is used in `CodeIgniter`, developers assume that the `CLIRequest` object is used system-wide.
This PR makes that so.
**Checklist:**

fix: when running on CLI, two Request objects were used in the system

---

system/CLI/CLI.php
system/CLI/GeneratorTrait.php
system/Cache/CacheFactory.php
system/Cache/Handlers/FileHandler.php
system/Cookie/CookieStore.php
system/Database/BaseConnection.php
system/Database/MySQLi/Connection.php
system/Database/OCI8/Connection.php
system/Database/Postgre/Connection.php
system/Database/SQLite3/Connection.php
system/Email/Email.php
system/HTTP/ResponseTrait.php

Depending on exception classes, but generally `(string) $e` has more info than `$e->getMessage()`.
<s>If this is not BC, then I would change the base branch to `develop`. </s>
`$e->getMessage()`:
```
ERROR - 2022-06-23 19:09:15 --> Cookie object with name "unknown" and prefix "" was not found in the collection.
```
`$e`:
```
ERROR - 2022-06-23 19:09:31 --> CodeIgniter\Cookie\Exceptions\CookieException: Cookie object with name "unknown" and prefix "" was not found in the collection. in /Users/kenji/work/codeigniter/CodeIgniter4/system/Cookie/CookieStore.php:114
Stack trace:
#0 /Users/kenji/work/codeigniter/CodeIgniter4/system/Cookie/CookieStore.php(114): CodeIgniter\Cookie\Exceptions\CookieException::forUnknownCookieInstance(Array)
#1 …
```

refactor: replace $e->getMessage() with $e in log_message()

---

system/Router/RouteCollection.php
tests/system/Router/RouteCollectionTest.php

```php
$routes->group('admin', static function ($routes) {
$routes->group('/', static function ($routes) {
$routes->get('list', 'Admin\Users::list');
});
});
```
creates
```
+--------+--------------+------------------------------------------+----------------+---------------+
| Method | Route        | Handler                                  | Before Filters | After Filters |
+--------+--------------+------------------------------------------+----------------+---------------+
| GET    | admin///list | \App\Controllers\Admin\Users::list       |                | toolbar       |
+--------+--------------+------------------------------------------+----------------+---------------+
```
This PR fixes the route:
```
+--------+------------+------------------------------------------+- …
```

fix: `$routes->group('/', ...)` creates the route `foo///bar`

---

system/Database/BaseBuilder.php
system/Database/BaseConnection.php
system/Database/Postgre/Builder.php
system/Database/SQLSRV/Builder.php
user_guide_src/source/changelogs/v4.3.0.rst

Follow-up #6140
- use `$DBDebug` instead of `CI_DEBUG`
- change the `BaseConnection::$DBDebug` default value to `true`
- `InvalidArgumentException` in `BaseBuilder::_whereIn()` is never suppressed by config
**Checklist:**

config: DB Error always throws Exception CI_DBUG

---

user_guide_src/source/installation/installing_composer.rst
user_guide_src/source/installation/installing_manual.rst

Fixes  #6190
- add note about special characters in paths
**Checklist:**

docs: add note about special characters in paths

---

user_guide_src/source/testing/response/012.php

Tiny Typo on `assertSessionMissing` docs (Currently `assertSessionMissin( .. )` 
[https://www.codeigniter.com/user_guide/testing/response.html#assertsessionmissing-string-key](https://www.codeigniter.com/user_guide/testing/response.html#assertsessionmissing-string-key)

docs: Typo on assertSessionMissing method

---

tests/system/Validation/ValidationTest.php
user_guide_src/source/libraries/validation/006.php
user_guide_src/source/libraries/validation/007.php

- add test cases
**Checklist:**

docs: add sample code for array validation rules

---

rector.php
tests/system/CLI/ConsoleTest.php
tests/system/CommonFunctionsTest.php
tests/system/Config/DotEnvTest.php
tests/system/ControllerTest.php
tests/system/Database/Live/MetadataTest.php
tests/system/Events/EventsTest.php
tests/system/HTTP/CURLRequestDoNotShareOptionsTest.php
tests/system/HTTP/CURLRequestTest.php
tests/system/HTTP/ContentSecurityPolicyTest.php
tests/system/HTTP/Files/FileMovingTest.php
tests/system/Helpers/CookieHelperTest.php
tests/system/Helpers/FilesystemHelperTest.php
tests/system/Images/BaseHandlerTest.php
tests/system/Images/GDHandlerTest.php
tests/system/Images/ImageMagickHandlerTest.php
tests/system/Images/ImageTest.php
tests/system/Log/Handlers/FileHandlerTest.php
tests/system/Pager/PagerRendererTest.php
tests/system/Test/TestCaseTest.php
tests/system/Throttle/ThrottleTest.php
tests/system/View/TableTest.php

- add `CompleteDynamicPropertiesRector`
- fix visibility for test class properties
See https://github.com/codeigniter4/CodeIgniter4/pull/6172#issuecomment-1162665215
**Checklist:**

refactor: add CompleteDynamicPropertiesRector

---

user_guide_src/source/general/configuration/010.php
user_guide_src/source/general/configuration/011.php

See #6162
- it will be deprecated in PHP 8.2
**Checklist:**

docs: remove dynamic property injection sample code

---

system/CodeIgniter.php

before:
```
404 - File Not Found
Sorry! Cannot seem to find the page you were looking for. 
```
after:
```
404 - File Not Found
ページが見つかりません。
```
**Checklist:**

fix: use lang('HTTP.pageNotFound') on production 404 page

---

user_guide_src/source/outgoing/response.rst
user_guide_src/source/outgoing/response/004.php
user_guide_src/source/outgoing/response/005.php
user_guide_src/source/outgoing/response/006.php
user_guide_src/source/outgoing/response/007.php
user_guide_src/source/outgoing/response/008.php
user_guide_src/source/outgoing/response/009.php
user_guide_src/source/outgoing/response/012.php
user_guide_src/source/outgoing/response/013.php

The Response object is used mainly in controllers and the user guide explains that "It can be accessed through $this->response."
**Checklist:**

docs: replace $response with $this->response in response.rst

---

system/Database/BaseConnection.php
system/Database/Postgre/Connection.php
system/Test/Mock/MockConnection.php

See https://github.com/codeigniter4/CodeIgniter4/issues/6162#issuecomment-1168005433
- do not create dynamic property in BaseConnection
The current database `tests` group is for SQLite3 that has `foreignKeys` property.
https://github.com/codeigniter4/CodeIgniter4/blob/24f67ea95aa463771360eb38f627675af2fda3d6/app/Config/Database.php#L77
If a user overrides `DBDriver`, the dynamic property `foreignKeys` will be created.
**Checklist:**

fix: BaseConnection may create dynamic property

---

rector.php
system/Email/Email.php
tests/system/Email/EmailTest.php

fix: Email SMTP may throw Uncaught ErrorException

---

system/HTTP/ContentSecurityPolicy.php
tests/system/HTTP/ContentSecurityPolicyTest.php

If we set `$reportOnly = true`, `Content-Security-Policy` header has some items.
**How to Reproduce**
```diff
diff --git a/app/Config/App.php b/app/Config/App.php
index 1a5e562dd..03e8eb649 100644
@@ -461,5 +461,5 @@ class App extends BaseConfig
*
* @var bool
*/
-    public $CSPEnabled = false;
+    public $CSPEnabled = true;
}
diff --git a/app/Config/ContentSecurityPolicy.php b/app/Config/ContentSecurityPolicy.php
index aa18ba9f1..d4a0d0817 100644
--- a/app/Config/ContentSecurityPolicy.php
+++ b/app/Config/ContentSecurityPolicy.php
@@ -24,7 +24,7 @@ class ContentSecurityPolicy extends BaseConfig
*
* @var bool
*/
-    public $reportOnly = false;
+    public $reportOnly = true;
/**
* Specifies a URL where a browser will send …
```

fix: CSP reportOnly behavior

---

system/Config/Services.php
tests/system/CommonFunctionsTest.php

Supersedes #6200
**Checklist:**

fix: lang() causes Error on CLI

---

system/BaseModel.php
tests/system/Models/PaginateModelTest.php

Fixes  #6204
I am not sure if there is something wrong with sharing Pager.
But without sharing the Pager, multiple pagers never work.
See https://codeigniter4.github.io/CodeIgniter4/libraries/pagination.html#paginating-multiple-results
**Checklist:**

fix: multiple pagers with models do not work

---

system/Commands/Database/ShowTableInfo.php

before:
```console
$ php spark db:table ci_sessions
CodeIgniter v4.2.1 Command Line Tool - Server Time: 2022-07-01 03:53:00 UTC-05:00
Data of Table "ci_sessions":
+--------------------+------------+--------------------+--------------------+
| id                 | ip_address | timestamp          | data               |
+--------------------+------------+--------------------+--------------------+
| 1f5o06b43phsnnf... | 127.0.0.1  | 2021-06-25 21:5... | __ci_last_regen... |
+--------------------+------------+--------------------+--------------------+
```
after:
```console
$ php spark db:table ci_sessions
CodeIgniter v4.2.1 Command Line Tool - Server Time: 2022-07-01 03:52:34 UTC-05:00
Data of Table "ci_sessions":
+--------------------+------------+--------------------+--------- …
```

fix: tweak empty line output of `spark db:table`

---

rector.php
utils/PHPStan/CheckFrameworkExceptionInstantiationViaNamedConstructorRule.php
utils/PHPStan/CheckUseStatementsAfterLicenseRule.php
utils/check_tabs_in_rst.php

Apply Rector run on `utils/` directory, not only `/utils/Rector` so other files (PHPStan rules, check_tabs_in_rst.php), will be checked as well.
**Checklist:**

[Rector] Apply Rector run on utils/ directory

---

rector.php
system/Autoloader/Autoloader.php
tests/system/Autoloader/AutoloaderTest.php

Generally Sanitization is bad practice.
before:
```console
$ php spark
```
> PHP Fatal error:  Uncaught Error: Class "Config\App" not found in /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Config/Factories.php:126
after:
```console
$ php spark 
```
> PHP Fatal error:  Uncaught InvalidArgumentException: The file path contains special character that is not allowed: "/Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Autoloader/FileLocator.php" in /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php:315
Related #6192
**Checklist:**

feat: Autoloader::sanitizeFilename() throws Exception

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/InsertTest.php
tests/system/Database/Builder/UpdateTest.php
user_guide_src/source/changelogs/v4.2.2.rst

fix: Builder insert()/update() does not accept an object

---

app/Views/errors/html/production.php
system/Language/en/Errors.php

replaces #6197
With this pull request the error message in the file app/Views/errors/html/production.php can be translated.
Translation for error_404.php and error_exception.php will follow with a other PR

 Language: Make production error message translatable (replaces #6197)

---

system/Validation/Validation.php
tests/system/Validation/StrictRules/ValidationTest.php
tests/system/Validation/ValidationTest.php

fix:  custom validation error is cleared when calling setRule() twice

---

system/Validation/Validation.php
tests/system/Validation/ValidationTest.php
user_guide_src/source/changelogs/v4.2.2.rst

https://forum.codeigniter.com/showthread.php?tid=82391&pid=398147#pid398147
Fixed: Validation of fields with a leading asterisk (wildcard).
Also fixed getting an error by field name with a leading asterisk.
**Checklist:**

Fix: Validation of fields with a leading asterisk.

---

system/Pager/Pager.php

Fixes #6230
The `$pager` (PagerRenderer) in the rendering of the pager overrides the variable `$pager` (Pager) in the view.
How to Test: https://github.com/codeigniter4/CodeIgniter4/issues/6230#issuecomment-1174641005
**Checklist:**

fix: Call to undefined method CodeIgniter\Pager\PagerRenderer::getDetails()

---

system/Publisher/ContentReplacer.php
system/Publisher/Publisher.php
tests/system/Publisher/ContentReplacerTest.php
tests/system/Publisher/PublisherContentReplaceTest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/libraries/publisher.rst
user_guide_src/source/libraries/publisher/010.php
user_guide_src/source/libraries/publisher/013.php
user_guide_src/source/libraries/publisher/014.php
user_guide_src/source/libraries/publisher/015.php

To modify config files during setup.
- add `Publisher::replace()`
- add `Publisher::addLineAfter()`
- add `Publisher::addLineBefore()`
**Checklist:**

feat: add methods to modify files in Publisher

---

app/Config/Constants.php
system/Debug/Exceptions.php

fix: exceptionHandler may cause HTTPException: Unknown HTTP status code

---

system/Database/SQLite3/Connection.php
system/Database/SQLite3/Table.php
tests/system/Database/Live/ForgeTest.php
tests/system/Database/Live/SQLite/AlterTableTest.php
tests/system/Database/Live/SQLite/GetIndexDataTest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/database/metadata.rst

Supersedes https://github.com/codeigniter4/CodeIgniter4/pull/6207
This is a rewrite of `system/Database/SQLite3/Connection::_indexData()`.
SQLite doesn't show indexes on tables created with `INTEGER PRIMARY KEY AUTO_INCREMENT`. This PR looks for primary keys that don't appear in the normal index lookup and adds it to the return of the method. It also adds the key type: Primary, Unique, or Index.
In the test database creation of the users table the current implementation won't return any index.
```php
$this->forge->addField([
'id'         => ['type' => 'INTEGER', 'constraint' => 3, 'auto_increment' => true],
'name'       => ['type' => 'VARCHAR', 'constraint' => 80],
'email'      => ['type' => 'VARCHAR', 'constraint' => 100],
'country'    => ['type' => 'VARCHAR', 'constraint' => 40], …
```

SQLite3 Connection getIndexData()

---

system/Database/BaseBuilder.php
tests/system/Database/Builder/DeleteTest.php
tests/system/Database/Builder/InsertTest.php

Fixes #5365
- remove alias from *FROM string* when INSERT/DELETE
**Checklist:**

fix: invalid INSERT/DELETE query when Query Builder uses table alias

---

phpstan-baseline.neon.dist
system/Database/Forge.php
system/Database/OCI8/Forge.php
system/Database/SQLSRV/Forge.php
system/Database/SQLite3/Forge.php
user_guide_src/source/dbmgmt/forge.rst
user_guide_src/source/dbmgmt/forge/015.php
user_guide_src/source/installation/upgrade_422.rst

This fixes https://github.com/codeigniter4/CodeIgniter4/issues/6248
This removes all code for CREATE TABLE table `IF NOT EXISTS`. Because all platforms do not support this statement the current implementation queries  the database first to determine if the table exists. If it does then it doesn't execute the create table statement. The problem occurs when the create indexes statements are executed after the create table statement and the indexes already exists. Rather then try and apply CREATE INDEX index IF NOT EXISTS and carry through the logic, this PR removes completely the IF NOT EXISTS regime and instead relies on the query table lookup. If the table exists then there is need to execute anything. This way the code is simpler and all the problems of index creation is averted. 
All …

Fix create table if not exists when indexes already exist

---

system/CodeIgniter.php
system/Helpers/number_helper.php

`format_number()` depends on `IncommingRequest::getLocale()`, and causes Error `Call to undefined method CodeIgniter\HTTP\CLIRequest::getLocale()`.
**Checklist:**

fix: format_number() can't be used on CLI

---

system/Validation/FileRules.php
tests/system/Validation/FileRulesTest.php
tests/system/Validation/StrictRules/FileRulesTest.php

Fixes  #6255
- add parameter checking
Before:
> ErrorException: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead from SYSTEMPATH\HTTP\Files\FileCollection.php
After:
> InvalidArgumentException: Invalid max_size parameter: "userfile.100"
**Checklist:**

fix: add parameter checking for max_size

---

user_guide_src/source/dbmgmt/migration.rst

- make section title linkable
- fix link to Spark commands page
**Checklist:**

docs: improve migration.rst

---

tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
tests/system/Database/Live/UpdateTest.php
tests/system/Models/InsertModelTest.php

Added a unique index 'email' and a non unique index 'country' to the user table that is created for tests.
This will allow for use with tests involving indexes and constraints. 
**Checklist:**

Add indexes to test user table

---

system/HTTP/RedirectResponse.php
system/Language/en/HTTP.php
tests/system/HTTP/RedirectResponseTest.php

- fix exception message
This PR changes the lang file:
```diff
-    'invalidRoute' => '{0} route cannot be found while reverse-routing.',
+    'invalidRoute' => 'The route for "{0}" cannot be found.',
```
**Checklist:**

fix: route name is not displayed in Exception message

---

admin/module/tests/README.md
admin/starter/tests/README.md
tests/README.md

- update Markdown format
- update contents
- add link to the forum thread `Any tutorials on Unit testing in CI4?`
**Checklist:**

docs: update tests/README.md

---

system/Commands/Utilities/Routes.php
system/Commands/Utilities/Routes/FilterFinder.php

Fixes #6276
```php
$routes->get('detail/([a-z0-9]{40})', 'User::detail/$1');
```
Before:
```console
ERROR: 404
Can't find a route for 'get: detail/([a-z0-9]{40})'.
```
After:
```console
+--------+-----------------------+------------------------------------------+----------------+---------------+
| Method | Route                 | Handler                                  | Before Filters | After Filters |
+--------+-----------------------+------------------------------------------+----------------+---------------+
| GET    | /                     | \App\Controllers\Home::index             |                | toolbar       |
| GET    | detail/([a-z0-9]{40}) | \App\Controllers\User::detail/$1         | <unknown>      | <unknown>     |
| CLI    | ci(.*) …
```

fix: `spark routes` shows 404 error when using regex

---

system/Commands/Utilities/FilterCheck.php
tests/system/Commands/FilterCheckTest.php
user_guide_src/source/changelogs/v4.2.0.rst
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/incoming/filters.rst
user_guide_src/source/incoming/routing.rst

- add ``spark filter:check`` command to check filters for a route.
**Checklist:**

feat: `spark filter:check` command

---

system/Database/Exceptions/DatabaseException.php
system/Entity/Exceptions/CastException.php
system/Exceptions/CastException.php
system/Exceptions/ConfigException.php
system/Exceptions/PageNotFoundException.php
system/Router/Exceptions/RedirectException.php
tests/system/Debug/ExceptionsTest.php

- replace magic numbers with constants
- add test cases
**Checklist:**

refactor: Exception exit code

---

system/Commands/Utilities/Routes.php

Follow-up #6110
- add loading of `Conig/Routes.php`
Before:
```
+--------+-------+---------+----------------+---------------+
| Method | Route | Handler | Before Filters | After Filters |
+--------+-------+---------+----------------+---------------+
```
After:
```
+--------+-------+------------------------------+----------------+---------------+
| Method | Route | Handler                      | Before Filters | After Filters |
+--------+-------+------------------------------+----------------+---------------+
| GET    | /     | \App\Controllers\Home::index |                | toolbar       |
+--------+-------+------------------------------+----------------+---------------+
```
**Checklist:**

fix: `spark routes` does not show routes at all

---

system/Entity/Cast/BaseCast.php
system/Entity/Cast/CastInterface.php
system/Entity/Cast/DatetimeCast.php
system/Entity/Entity.php
tests/system/Entity/EntityTest.php
user_guide_src/source/models/entities.rst
user_guide_src/source/models/entities/009.php

- fix `Entity::hasChanged()` returns wrong result to mapped property 
**Checklist:**

fix: Entity::hasChanged() returns wrong result to mapped property 

---

system/Files/FileCollection.php
tests/system/Files/FileCollectionTest.php

fix: unable to add more than one file to FileCollection constructor

---

system/Security/Security.php
tests/system/Security/SecurityCSRFSessionRandomizeTokenTest.php

From https://forum.codeigniter.com/showthread.php?tid=82544
`Security::derandomize()` may throw `ErrorException` "hex2bin(): Hexadecimal input string must have an even length".
**Checklist:**

fix: Security::derandomize() may cause hex2bin() error

---

app/Views/errors/html/error_exception.php

Per HTML5 spec, typically there is no need to specify a type when including CSS and JavaScript files as text/css and text/javascript are their respective defaults.

remove unnecessary type tag

---

system/CodeIgniter.php
system/HTTP/DownloadResponse.php
tests/system/CodeIgniterTest.php
user_guide_src/source/changelogs/v4.2.2.rst
user_guide_src/source/incoming/filters.rst
user_guide_src/source/installation/upgrade_422.rst
user_guide_src/source/installation/upgrading.rst

Fixes #6281
The page cache saves Response data before running after filters.
So response headers added by after filters and response body changes by after filters will be lost.
**Checklist:**

fix:  page cache saves Response data before running after filters

---

system/Images/Handlers/ImageMagickHandler.php
user_guide_src/source/libraries/images.rst

Fixes #6297
- update comment and the user guide
**Checklist:**

docs: update docs on imagick extentsion

---

system/CodeIgniter.php

Update CodeIgniter.php to use getenv() instead of $_SERVER in detectEnvironment. The outcome of environment variables loading in either  $_SERVER or $_ENV depends on the operating system and web server. For instance, in a Docker environment the `.env` file loads variables in $_ENV, resulting in detectEnvironment() not seeing CI_ENVIRONMENT when defined. Using getenv() instead of directly reading from $_SERVER solves this issue.
**Checklist:**

fix: use getenv() instead of $_SERVER in detectEnvironment()

---

system/CodeIgniter.php
system/Commands/Utilities/FilterCheck.php
system/Commands/Utilities/Routes.php
system/Router/RouteCollection.php
system/Test/FeatureTestCase.php
system/Test/FeatureTestTrait.php
system/Test/FilterTestTrait.php
system/Test/bootstrap.php
user_guide_src/source/changelogs/v4.3.0.rst

The current way is difficult to use.
- add `RouteCollection::loadRoutes()`
**Checklist:**

refactor: loading app/Config/routes.php

---

system/Database/OCI8/Result.php

fix: OCI8 uses deprecated Entity

---

system/Security/Security.php
tests/system/Security/SecurityCSRFCookieRandomizeTokenTest.php
tests/system/Security/SecurityTest.php

- remove `$_COOKIE`
- `generateHash()` always creates new hash
**Checklist:**

refactor: CSRF protection

---

user_guide_src/source/changelogs/v4.0.4.rst

- fix link to wrong page
**Checklist:**

docs: fix link to wrong page in changelogs/v4.0.4.rst

---

user_guide_src/source/installation/installing_composer.rst
user_guide_src/source/installation/installing_manual.rst
user_guide_src/source/installation/running.rst

- add initial configuration in Installation pages
- add note about baseURL and debug toolbar
- small fixes
**Checklist:**

docs: improve installation

---

public/index.php
spark
system/CodeIgniter.php

fix: Parse error occurs before PHP version check

---

user_guide_src/source/database/query_builder.rst

- improve explanations
**Checklist:**

docs: improve explanations of getCompiledUpdate/getCompiledInsert

---

app/Views/errors/html/error_404.php
phpstan-baseline.neon.dist
system/Debug/Exceptions.php

fix:  404 page might display Exception message in production environment

---

system/Helpers/text_helper.php
tests/system/Helpers/TextHelperTest.php
user_guide_src/source/changelogs/v4.2.2.rst
user_guide_src/source/helpers/text_helper.rst
user_guide_src/source/installation/upgrade_422.rst

fix: random_string('crypto') may return string less than $len or ErrorException

---

system/RESTful/ResourceController.php
system/RESTful/ResourcePresenter.php

docs: fix types in PHPDocs in RESTful controllers

---

system/CLI/CLI.php
system/Test/PhpStreamWrapper.php
tests/system/CLI/CLITest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/cli/cli_library.rst
user_guide_src/source/testing/overview.rst
user_guide_src/source/testing/overview/019.php

Fixes #6076
- add `PhpStreamWrapper`
- modify `CLI::input()` for testing
**Checklist:**

feat: make `CLI::input()` testable

---

system/BaseModel.php
system/Database/BaseBuilder.php
system/Model.php

- fix PHPDocs related to Model::insert()
**Checklist:**

docs: fix PHPDocs related to Model::insert()

---

composer.json

- add extentions for `suggest`
**Checklist:**

chore: add extensions for `suggest` in composer.json

---

CHANGELOG.md
system/CodeIgniter.php
user_guide_src/source/changelogs/index.rst
user_guide_src/source/changelogs/v4.2.2.rst
user_guide_src/source/changelogs/v4.2.3.rst
user_guide_src/source/conf.py
user_guide_src/source/installation/upgrade_422.rst

Updates changelog and version references for `4.2.2`.
**Checklist:**

Prep for 4.2.2 release

---

system/Database/Exceptions/DatabaseException.php
system/Debug/Exceptions.php
system/Entity/Exceptions/CastException.php
system/Exceptions/CastException.php
system/Exceptions/ConfigException.php
system/Exceptions/ExitExceptionInterface.php
system/Exceptions/HTTPExceptionInterface.php
system/Exceptions/HasExitCodeInterface.php
system/Exceptions/PageNotFoundException.php
system/Router/Exceptions/RedirectException.php
tests/system/Debug/ExceptionsTest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/general/errors.rst
user_guide_src/source/installation/upgrade_430.rst

The current implementation has undocumented behavior that use **Exception code** as **HTTP status code**,
and determine **Exit code** from Exception code.
But Exception code has nothing to do with HTTP status code or Exit code.
This PR introduces interfaces that explicitly show the Exception code is  HTTP status code or Exit code
- add `HTTPExceptionInterface` and `HasExitCodeInterface`
- fix `Exceptions::determineCodes()`
**Breaking Changes:**
- If you expect Exception code as HTTP status code, the HTTP status code will be changed.
In that case, you need to implements `HTTPExceptionInterface` in the Exception.
- If you expect Exit code based on Exception code, the Exit code will be changed.
In that case, you need to implements `HasExitCodeInterface` in the Exception. …

fix: exceptionHandler may return invalid HTTP status code

---

user_guide_src/source/libraries/sessions.rst

Description
Fixes https://github.com/codeigniter4/CodeIgniter4/issues/5586
Checklist:

docs: the session_id acquisition method that is not described #5586

---

CHANGELOG.md
admin/RELEASE.md
system/CodeIgniter.php
user_guide_src/source/changelogs/index.rst
user_guide_src/source/changelogs/v4.2.4.rst
user_guide_src/source/conf.py
user_guide_src/source/installation/upgrade_423.rst

Updates changelog and version references for `4.2.3`.
**Checklist:**

Prep for 4.2.3 release

---

user_guide_src/source/installation/installing_composer.rst
user_guide_src/source/installation/installing_manual.rst

- fix installing_composer.rst
- fix installing_manual.rst
**Checklist:**

docs: fix installing

---

.github/workflows/test-userguide.yml
user_guide_src/source/database/utilities/001.php

- convert warning into error
- refactor sample code
**Checklist:**

chore: Sphinx convert warning into error

---

system/Email/Email.php

Fixes #6350
Before:
no log
After:
```
ERROR - 2022-08-08 23:13:22 --> Email: Unable to send email using PHP SMTP. Your server might not be configured to send mail using this method.
ERROR - 2022-08-08 23:13:22 --> 220 smtp.googlemail.com ESMTP s1-20020a17090a2f0100b001f04479017fsm9022783pjd.29 - gsmtp
hello: 250-smtp.googlemail.com at your service, [133.149.85.47]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
starttls: 220 2.0.0 Ready to start TLS
hello: 250-smtp.googlemail.com at your service, [133.149.85.47]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
Failed to authenticate password. Error: …
```

fix: Email class may not log an error when it fails to send

---

system/Entity/Cast/IntBoolCast.php
system/Entity/Entity.php
tests/system/Entity/EntityTest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/models/entities.rst

- add `IntBoolCast` (`'int-bool'`) for Entity
From https://github.com/codeigniter4/shield/pull/339
**Checklist:**

feat: add IntBoolCast for Entity

---

user_guide_src/source/database/query_builder.rst
user_guide_src/source/incoming/incomingrequest.rst
user_guide_src/source/libraries/caching.rst
user_guide_src/source/libraries/cookies.rst
user_guide_src/source/libraries/email.rst

- fix Sphinx errors
**Checklist:**

docs: fix Sphinx errors

---

user_guide_src/source/incoming/controllers.rst
user_guide_src/source/incoming/controllers/023.php

- add about constructor
- update private methods
**Checklist:**

docs: improve controllers.rst

---

system/CodeIgniter.php

Fixes  #6358
- never cache DownloadResponse/RedirectResponse
- add null check for $this->response->getBody()
```php
<?php
{
{
return $this->response->download('some.txt', 'some text', true);
}
}
```
**Checklist:**

fix: Response::download() causes TypeError

---

contributing/workflow.md

- add "If you sent to the wrong branch"
- add optional step to back up the PR branch
**Checklist:**

docs: improve PR workflow

---

system/CodeIgniter.php
tests/_support/Filters/Customfilter.php
tests/system/CodeIgniterTest.php
tests/system/Filters/FiltersTest.php
tests/system/Router/RouterTest.php
tests/system/Test/FilterTestTraitTest.php

Follow-up #6361
- add hack for testing in CodeIgniter.php
- add test for DownloadResponse
- fix tests with dynamic property
**Checklist:**

refactor: add test for DownloadResponse

---

system/Database/BaseConnection.php
system/Database/Forge.php
system/Database/MySQLi/Connection.php
system/Database/OCI8/Connection.php
system/Database/Postgre/Connection.php
system/Database/SQLSRV/Connection.php
system/Database/SQLite3/Connection.php
system/Test/Mock/MockConnection.php
tests/system/Database/Forge/CreateTableTest.php
tests/system/Database/Live/ForgeTest.php
user_guide_src/source/changelogs/v4.2.5.rst

Follow-up #6249
This PR fixes https://github.com/codeigniter4/CodeIgniter4/issues/6351
In `Forge::createTable()`
```php
// If table exists lets stop here
if ($ifNotExists === true && $this->db->tableExists($table, false)) {
$this->reset();
return true;
}
```
This PR forces to check if table exists rather than relying on cache.
We add $tableName param to `Connection::_listTables()`. This allows us to lookup only one table rather than return a full list of tables.
**Checklist:**

Add $cached param to BaseConnection::tableExists()

---

user_guide_src/source/general/managing_apps.rst
user_guide_src/source/general/managing_apps/002.php
user_guide_src/source/general/managing_apps/003.php

`$pathsConfig` line number changed after #6327
**Checklist:**

docs: fix `$pathsConfig` line number

---

system/CLI/BaseCommand.php
system/CLI/Commands.php
system/CLI/Console.php

Ref #6310
- add/fix `@return`
**Checklist:**

docs: add/fix @return types in CLI

---

user_guide_src/source/incoming/routing.rst
user_guide_src/source/incoming/routing/043.php

Add route priority as it was not clearly stated.
**Checklist:**

docs: add about route priority

---

phpstan-baseline.neon.dist
system/CLI/Console.php
tests/system/CLI/ConsoleTest.php
user_guide_src/source/changelogs/v4.3.0.rst

Allow calling help info using `spark --help`

---

admin/framework/composer.json
tests/AutoReview/ComposerJsonTest.php

Follow-up #6322
- update framework/composer json suggest
- update tests/AutoReview/ComposerJsonTest.php
**Checklist:**

chore: update framework/composer json suggest

---

system/Database/BaseBuilder.php
system/Database/BaseConnection.php
tests/system/Database/Builder/PrefixTest.php
user_guide_src/source/changelogs/v4.2.5.rst

https://forum.codeigniter.com/showthread.php?tid=82741&pid=399285#pid399285
When creating a query, table aliases are registered. This prevents the prefix being added to the alias.
Due to the fact that aliases are stored in the property of the BaseConnection class, after compiling the subquery using the ``BaseBuilder::geCompiledSelect()`` method, the list of aliases is cleared, which leads to the fact that when compiling the main query, the alias is recognized as a table name and to the alias prefix is added.
This PR prevents resetting alias values.
**Checklist:**

Fix: The subquery adds a prefix for the table alias.

---

phpstan-baseline.neon.dist
system/HTTP/RedirectResponse.php
system/Helpers/form_helper.php
system/Validation/Validation.php
tests/system/Helpers/FormHelperTest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/helpers/form_helper.rst
user_guide_src/source/incoming/routing.rst
user_guide_src/source/installation/upgrade_430.rst
user_guide_src/source/installation/upgrade_validations.rst
user_guide_src/source/installation/upgrade_validations/002.php
user_guide_src/source/libraries/validation.rst
user_guide_src/source/libraries/validation/001.php

Fixes [#6380](https://github.com/codeigniter4/CodeIgniter4/issues/6380#issuecomment-1216212822)
Supersedes  #6381
About the bug:
- The Validation class reads/writes the validation errors in the session for redirect.
- This behavior is undocumented.
- But `Validation::run()` must reset the validation errors in the session.
- So if a validation runs before the errors output in the form, the validation errors in the session will be deleted.
Changes:
- add new Form helper functions to get **Validation Errors in the Session** or **shared Validation object**
- `validation_errors()`  to get the validation errors array
- `validation_list_errors()`  to get the rendered HTML of the validation errors
- `validation_show_error()` to get the rendered HTML of the single validation error …

feat: add Form helpers for Validation Errors

---

system/Validation/Validation.php
tests/system/Validation/ValidationTest.php
user_guide_src/source/changelogs/v4.2.5.rst

Fixes #6245 
Supersedes #6352 
**Checklist:**

Fix validation custom error asterisk field

---

system/Security/Exceptions/SecurityException.php
tests/system/Filters/CSRFTest.php

Follow-up  #6228
- fix SecurityException's HTTP status code
```diff
diff --git a/app/Config/Filters.php b/app/Config/Filters.php
index 7b70c4fb3..06e0b9941 100644
--- a/app/Config/Filters.php
+++ b/app/Config/Filters.php
@@ -30,7 +30,7 @@ class Filters extends BaseConfig
public array $globals = [
'before' => [
// 'honeypot',
-            // 'csrf',
+            'csrf',
// 'invalidchars',
],
'after' => [
diff --git a/app/Config/Routes.php b/app/Config/Routes.php
index 71b7a86de..b41442a41 100644
@@ -30,6 +30,7 @@ $routes->set404Override();
// We get a performance increase by specifying the default
// route since we don't have to scan directories.
+$routes->post('/', …
```

fix: SecurityException's HTTP status code

---

.github/workflows/test-rector.yml
rector.php

PHP version compare no longer exists in CodeIgniter.php so skip UnwrapFutureCompatibleIfPhpVersionRector no longer needed.
**Checklist:**

[Rector] Clean up skip UnwrapFutureCompatibleIfPhpVersionRector

---

user_guide_src/source/installation/backward_compatibility_notes.rst
user_guide_src/source/installation/upgrading.rst

- add Backward Compatibility Notes. See https://github.com/codeigniter4/CodeIgniter4/pull/6414#issuecomment-1223897237
**Checklist:**

docs: add Backward Compatibility Notes

---

tests/README.md

There seems no reason to use `phpunit.xml`.
**Checklist:**

docs: update about test database setup

---

system/Database/SQLite3/Table.php
tests/system/Database/Live/SQLite/AlterTableTest.php

This PR fixes https://github.com/codeigniter4/CodeIgniter4/issues/6205
The indexes need to be checked for missing fields on composite keys.
**Checklist:**

Fix Sqlite Table::createTable()

---

contributing/workflow.md

- 4.3 branch may not exist if a contributor forked upstream long ago.
**Checklist:**

docs: fix git command example

---

app/Config/App.php
app/Config/Security.php
env
system/Security/Security.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/libraries/security.rst
user_guide_src/source/libraries/security/005.php

It is difficult to know what happened for (beginner) devs. See https://github.com/codeigniter4/CodeIgniter4/issues/6404#issuecomment-1221598762
**Checklist:**

config: change Security::$redirect to false

---

system/Database/BaseBuilder.php

refactor: remove unused `_parent_name` in BaseBuilder::objectToArray()

---

system/Model.php

From https://forum.codeigniter.com/showthread.php?tid=82742
**Checklist:**

docs: add `@method` groupBy() in Model

---

system/Common.php
system/Filters/CSRF.php
system/Filters/Honeypot.php
system/Filters/InvalidChars.php
system/HTTP/CLIRequest.php
system/HTTP/Negotiate.php
system/HTTP/RequestInterface.php
system/Honeypot/Honeypot.php
system/Security/Security.php
system/Validation/FileRules.php
tests/system/HTTP/CLIRequestTest.php
tests/system/HTTP/NegotiateTest.php

Ref #6089
- remove `@mixin` in `RequestInterface`
- add missing `get*()` methods in `CLIRequest`
- getGet()
- getPost()
- getPostGet()
- getGetPost()
- fix filters
- CSRF
- Honeypot: fixes #6419
- InvalidChars
**Checklist:**

fix: CLIRequest Erros in CLI

---

system/Log/Handlers/BaseHandler.php

The abstract `handle()` in the abstract class is unneeded because the its interface is already defining that method. It's redundant.
**Checklist:**

Remove unneeded abstract `handle()` method

---

system/I18n/Time.php
tests/system/I18n/TimeTest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/libraries/time.rst
user_guide_src/source/libraries/time/042.php

Closes #6124
- add `Time::toDatabase()`
**Checklist:**

feat: add Time::toDatabase()

---

contributing/pull_request.md
contributing/signing.md
contributing/workflow.md

Big commits and/or inappropriate commit messages make the reviews difficult.
**Checklist:**

docs: add about PR commits

---

system/HTTP/CLIRequest.php
tests/system/HTTP/CLIRequestTest.php

Fixes https://github.com/codeigniter4/CodeIgniter4/issues/6377
Follow-up #6421
- add `CLIRequest::getLocale()`
**Checklist:**

fix: Call to undefined method CodeIgniter\HTTP\CLIRequest::getLocale()

---

user_guide_src/source/incoming/routing.rst

docs: fix incorrect links to the spark page

---

CHANGELOG.md
system/CodeIgniter.php
user_guide_src/source/changelogs/index.rst
user_guide_src/source/changelogs/v4.2.5.rst
user_guide_src/source/changelogs/v4.2.6.rst
user_guide_src/source/conf.py
user_guide_src/source/installation/upgrade_425.rst
user_guide_src/source/installation/upgrading.rst

Updates changelog and version references for `4.2.5`.
**Checklist:**

Prep for 4.2.5 release

---

contributing/workflow.md

- add *Changing a Commit Message*. See https://github.com/codeigniter4/CodeIgniter4/pull/6437#issuecomment-1229440888
**Checklist:**

docs: update contributing/workflow.md

---

system/Common.php
system/Router/RouteCollection.php
tests/system/CommonFunctionsTest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/general/common_functions.rst
user_guide_src/source/general/common_functions/011.php

Supersedes #6379
- Now you can set locale as the last parameter.
```php
// for route 
$routes->add('{locale}/path/(:any)/to/(:num)', 'myController::goto/$1/$2', ['as' => 'path-to']);
// the helper should be called like this.
route_to('path-to', 'string', 13, 'en'); // /en/path/string/to/13
```
**Checklist:**

feat: add locale param to `route_to()`

---

system/Test/Filters/CITestStreamFilter.php
system/Test/StreamFilterTrait.php
tests/system/CodeIgniterTest.php
tests/system/Commands/Utilities/NamespacesTest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/installation/upgrade_430.rst
user_guide_src/source/testing/overview.rst
user_guide_src/source/testing/overview/020.php

Tests failed due to changed stream filter initialization.
- Filter additions to STDOUT and STDERR streams moved from trait to filter class.
- CITestStreamFilter::addErrorFilter()
- CITestStreamFilter::addOutputFilter()
- CITestStreamFilter::removeErrorFilter()
- CITestStreamFilter::removeOutputFilter()
- Fixed failed tests.
**Checklist:**

[4.3] Fix tests. Changed StreamFilterTrait and CITestStreamFilter.

---

system/Validation/FileRules.php

at SYSTEMPATH\Validation\FileRules.php:42
Backtrace:
1    [internal function]
CodeIgniter\Debug\Exceptions()->errorHandler(2, 'assert(): assert($request instanceof IncomingRequest) failed', 'C:\\laragon\\www\\test\\vendor\\codeigniter4\\framework\\system\\Validation\\FileRules.php', 42, [...])
**Checklist:**

fix: AssertionError occurs when using Validation in CLI

---

user_guide_src/source/incoming/routing.rst
user_guide_src/source/incoming/routing/063.php
user_guide_src/source/incoming/routing/064.php

- add about controllers namespace in routing
**Checklist:**

docs: add about controllers namespace in routing

---

system/Entity/Entity.php

- update PHPDoc
**Checklist:**

docs: update PHPDoc in Entity

---

tests/system/I18n/TimeDifferenceTest.php
tests/system/I18n/TimeTest.php

A test class should not change the global state.
**Checklist:**

test: restore changed locale in Time tests

---

admin/framework/composer.json
composer.json
system/CodeIgniter.php
system/Common.php
system/ComposerScripts.php
system/Helpers/kint_helper.php

Kint is not needed on production environment.
**Checklist:**

chore: move Kint to `require-dev`

---

phpstan-baseline.neon.dist
system/Model.php

PHPStan new version 1.8.3 reports new errors.
**Checklist:**

refactor: fix PHPStan errors

---

system/Cookie/CloneableCookieInterface.php
system/Cookie/Cookie.php
user_guide_src/source/changelogs/v4.2.6.rst
user_guide_src/source/libraries/cookies.rst

See [#6413](https://github.com/codeigniter4/CodeIgniter4/pull/6413#issuecomment-1227060599)
Supersedes #6413
**Checklist:**

docs: deprecate Cookie::withNeverExpiring()

---

system/Validation/Validation.php
tests/_support/Validation/TestRules.php
tests/system/Validation/ValidationTest.php

fix: [Validation] JSON data may cause "Array to string conversion" error

---

system/Debug/Exceptions.php

Fix fatal error gets turned to `0` severity on shutdown handler

---

user_guide_src/source/installation/upgrade_420.rst

- add about composer.json autoload.psr-4
The config makes `spark migrate:status` output duplicated.
The same explanation is already here: https://codeigniter4.github.io/CodeIgniter4/general/managing_apps.html
But it is better to have it in Upgrading Guide.
The following is the result of installing v4.1.5 and updated to v4.2.5:
```console
$ php spark migrate:status
CodeIgniter v4.2.5 Command Line Tool - Server Time: 2022-09-02 18:25:16 UTC-05:00
+-----------+-------------------+----------+-------+-------------+-------+
| Namespace | Version           | Filename | Group | Migrated On | Batch |
+-----------+-------------------+----------+-------+-------------+-------+
| App       | 2022-09-02-231945 | Test     | ---   | ---         | ---   |
| App       | 2022-09-02-231945 | …
```

docs: add composer.json in Mandatory File Changes in upgrade_420.rst

---

system/CodeIgniter.php
tests/system/CodeIgniterTest.php

New clean PR of #6410 after rebase
Discussion available here:
https://github.com/codeigniter4/CodeIgniter4/pull/6410
**Checklist:**

 Fix broken caching system when array of allowed parameters used

---

user_guide_src/source/models/model.rst

From https://forum.codeigniter.com/showthread.php?tid=82814
- add note to Model Validation
- some tweaks
**Checklist:**

docs: update Model validation

---

.php-cs-fixer.dist.php
.php-cs-fixer.no-header.php
.php-cs-fixer.user-guide.php

```console
$ vendor/bin/php-cs-fixer describe blank_line_between_import_groups
Description of blank_line_between_import_groups rule.
Putting blank lines between `use` statement groups.
* Example #1.
--- Original
+++ New
@@ -1,5 +1,7 @@
<?php
use function AAC;
+
use const AAB;
+
use AAA;
* Example #2.
--- Original
+++ New
@@ -1,8 +1,10 @@
<?php
use const AAAA;
use const BBB;
+
use Bar;
use AAC;
use Acme;
+
use function CCC\AA;
use function DDD;
* Example #3.
--- Original
+++ New
@@ -1,8 +1,10 @@
<?php
use const BBB;
use const AAAA;
+
use Acme;
use AAC;
use Bar;
+
use function DDD;
use function …
```

Enable `blank_line_between_import_groups`

---

.php-cs-fixer.dist.php
.php-cs-fixer.no-header.php
.php-cs-fixer.user-guide.php

```console
$ vendor/bin/php-cs-fixer describe control_structure_braces        
Description of control_structure_braces rule.
The body of each control structure MUST be enclosed within braces.
* Example #1.
--- Original
+++ New
@@ -1,2 +1,2 @@
<?php
-if (foo()) echo 'Hello!';
+if (foo()) { echo 'Hello!'; }
```
**Checklist:**

Enable `control_structure_braces`

---

.php-cs-fixer.dist.php
.php-cs-fixer.no-header.php
.php-cs-fixer.user-guide.php

```console
$ vendor/bin/php-cs-fixer describe no_multiple_statements_per_line  
Description of no_multiple_statements_per_line rule.
There must not be more than one statement per line.
* Example #1.
--- Original
+++ New
@@ -1,2 +1,3 @@
<?php
-foo(); bar();
+foo();
+bar();
```
**Checklist:**

Enable `no_multiple_statements_per_line`

---

.php-cs-fixer.dist.php
.php-cs-fixer.no-header.php
.php-cs-fixer.user-guide.php

```console
$ vendor/bin/php-cs-fixer describe no_useless_nullsafe_operator   
Description of no_useless_nullsafe_operator rule.
There should not be useless `null-safe-operators` `?->` used.
* Example #1.
--- Original
+++ New
@@ -1,7 +1,7 @@
<?php
class Foo extends Bar
{
public function test() {
-        echo $this?->parentMethod();
+        echo $this->parentMethod();
}
}
```
**Checklist:**

Enable `no_useless_nullsafe_operator`

---

.php-cs-fixer.dist.php
.php-cs-fixer.no-header.php
.php-cs-fixer.user-guide.php

```console
$ vendor/bin/php-cs-fixer describe statement_indentation      
Description of statement_indentation rule.
Each statement must be indented.
* Example #1.
--- Original
+++ New
@@ -1,7 +1,7 @@
<?php
if ($baz == true) {
-  echo "foo";
+    echo "foo";
}
else {
-      echo "bar";
+    echo "bar";
}
```
**Checklist:**

Enable `statement_indentation`

---

.php-cs-fixer.dist.php
.php-cs-fixer.no-header.php
.php-cs-fixer.user-guide.php

```console
$ vendor/bin/php-cs-fixer describe class_definition     
Description of class_definition rule.
Whitespace around the keywords of a class, trait, enum or interfaces definition should be one space.
* multi_line_extends_each_single_line (bool): whether definitions should be multiline; defaults to false
* single_item_single_line (bool): whether definitions should be single line when including a single item; defaults to false
* single_line (bool): whether definitions should be single line; defaults to false
* space_before_parenthesis (bool): whether there should be a single space after the parenthesis of anonymous class (PSR12) or not; defaults to false
* inline_constructor_arguments (bool): whether constructor argument …
```

Add `inline_constructor_arguments` option to `class_definition`

---

.php-cs-fixer.dist.php
.php-cs-fixer.no-header.php
.php-cs-fixer.user-guide.php
user_guide_src/source/database/call_function/002.php

```console
$ vendor/bin/php-cs-fixer describe no_trailing_comma_in_singleline
Description of no_trailing_comma_in_singleline rule.
If a list of values separated by a comma is contained on a single line, then the last item MUST NOT have a trailing comma.
Fixer is configurable using following option:
* elements (a subset of ['arguments', 'array_destructuring', 'array', 'group_import']): which elements to fix; defaults to ['arguments', 'array_destructuring', 'array', 'group_import']
--- Original
+++ New
@@ -1,5 +1,5 @@
<?php
-foo($a,);
-$foo = array(1,);
-[$foo, $bar,] = $array;
-use a\{ClassA, ClassB,};
+foo($a);
+$foo = array(1);
+[$foo, $bar] = $array;
+use a\{ClassA, …
```

Enable `no_trailing_comma_in_singleline`

---

CHANGELOG.md
system/CodeIgniter.php
user_guide_src/source/changelogs/index.rst
user_guide_src/source/changelogs/v4.2.7.rst
user_guide_src/source/conf.py
user_guide_src/source/installation/upgrade_426.rst
user_guide_src/source/installation/upgrading.rst

Updates changelog and version references for `4.2.6`.
**Checklist:**

Prep for 4.2.6 release

---

admin/RELEASE.md

The actual deployment of new releases is getting delayed significantly by all the workflow Actions that queued before it. This proposes a new order to the process that will prioritize the actual release and then handle other clean-up actions that trigger workflows for later.
**Checklist:**

Release Process

---

contributing/workflow.md

Adding how to signing gpg to old commit.
**Checklist:**

docs: added about signing gpg to old commit

---

contributing/workflow.md

Follow-up to #6497 
**Checklist:**

Fix grammatical inaccuracies

---

system/CodeIgniter.php

Optimizing the code for getting the URL in the ``CodeIgniter::generateCacheName()`` method.
The change uses cloning the URL object and modifying the properties, instead of calling ``URI::createURIString()`` directly with arguments.
The code is more compact.
**Checklist:**

Refactor: CodeIgniter::generateCacheName()

---

system/I18n/Time.php
tests/system/I18n/TimeTest.php
user_guide_src/source/changelogs/v4.2.7.rst
user_guide_src/source/installation/upgrade_427.rst
user_guide_src/source/installation/upgrading.rst
user_guide_src/source/libraries/time.rst

Closes #6439
Supersedes #6456
In this PR, `Time::__toString()` no longer depends on locale.
It always returns database-compatible string like `'2016-03-09 12:00:00'`.
In the current implementation, the `__toString()` output will be changed by the locale.
(But it seems it is not documented in the User Guide.)
It causes database query error in a few locale.
Time is localized class, but `__toString()` does not need to return localized value.
If a dev needs localized string, they can call [toDateTimeString()](https://codeigniter4.github.io/CodeIgniter4/libraries/time.html#todatetimestring).
Implicitly changing behavior depending on locale is a bad practice because it confuses developers.
`__toString()` is a standard PHP method, not a localized helper method. 
The  return value …

fix: make Time::__toString() database-compatible on any locale

---

system/Database/BaseConnection.php
system/Database/ConnectionInterface.php
system/Database/Postgre/Connection.php

See #6310
- fix doc comments
**Checklist:**

docs: replace mixed in Database doc comments

---

phpstan-baseline.neon.dist
system/BaseModel.php
system/Config/BaseService.php
system/Config/Services.php
system/Controller.php
system/Validation/Validation.php
system/Validation/ValidationInterface.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/installation/upgrade_430.rst

Fixes #6224
Alternative #6247
- fix `ValidationInterface::run()` param
- add missing
- `ValidationInterface::setRule()` 
- `ValidationInterface::getRules()`
- `ValidationInterface::getRuleGroup()`  
- `ValidationInterface::setRuleGroup()`
- `ValidationInterface::loadRuleGroup()`
- `ValidationInterface::hasError()`
- `ValidationInterface::listErrors()`
- `ValidationInterface::showError()`
- fix `Validation::loadRuleGroup()`
**Checklist:**

fix: ValidationInterface

---

tests/system/I18n/TimeTest.php

See https://github.com/codeigniter4/CodeIgniter4/pull/6461
```diff
1) CodeIgniter\I18n\TimeTest::testToDatabase
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'۲۰۱۷-۰۱-۱۲ ۰۰:۰۰:۰۰'
+'2017-01-12 00:00:00'
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/I18n/TimeTest.php:1169
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:97
```
https://github.com/codeigniter4/CodeIgniter4/runs/8238507830?check_suite_focus=true
**Checklist:**

test: update TimeTest::testToDatabase()

---

.php-cs-fixer.dist.php
.php-cs-fixer.no-header.php
.php-cs-fixer.user-guide.php

```console
$ vendor/bin/php-cs-fixer describe curly_braces_position
Description of curly_braces_position rule.
Curly braces must be placed as configured.
* control_structures_opening_brace ('next_line_unless_newline_at_signature_end', 'same_line'): the position of the opening brace of control structures body; defaults to 'same_line'
* functions_opening_brace ('next_line_unless_newline_at_signature_end', 'same_line'): the position of the opening brace of functions body; defaults to 'next_line_unless_newline_at_signature_end'
* anonymous_functions_opening_brace ('next_line_unless_newline_at_signature_end', 'same_line'): the position of the opening brace of anonymous functions body; defaults to 'same_line'
* classes_opening_brace …
```

Enable `curly_braces_position`

---

system/I18n/Time.php
tests/system/I18n/TimeTest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/libraries/time.rst
user_guide_src/source/libraries/time/042.php

Remove `Time::toDatabase()` #6431 because the method is now exactly the same as `__toString()`.
See https://github.com/codeigniter4/CodeIgniter4/pull/6461
**Checklist:**

Remove unreleased `Time::toDatabase()`

---

.php-cs-fixer.dist.php
.php-cs-fixer.no-header.php
.php-cs-fixer.user-guide.php

```console
$ vendor/bin/php-cs-fixer describe function_declaration
Description of function_declaration rule.
Spaces should be properly placed in a function declaration.
* closure_function_spacing ('none', 'one'): spacing to use before open parenthesis for closures; defaults to 'one'
* trailing_comma_single_line (bool): whether trailing commas are allowed in single line signatures; defaults to false
...
```
**Checklist:**

Add the `trailing_comma_single_line` option to `function_declaration`

---

system/Language/en/HTTP.php
system/Language/en/Session.php

Follow-up #6474
- replace `` ` ``
**Checklist:**

fix: replace "`" in lang strings

---

.php-cs-fixer.dist.php
.php-cs-fixer.no-header.php
.php-cs-fixer.user-guide.php

```console
$ vendor/bin/php-cs-fixer describe new_with_braces     
Description of new_with_braces rule.
All instances created with `new` keyword must (not) be followed by braces.
* named_class (bool): whether named classes should be followed by parentheses; defaults to true
* anonymous_class (bool): whether anonymous classes should be followed by parentheses; defaults to true
--- Original
+++ New
@@ -1,4 +1,4 @@
<?php
-$x = new X;
-$y = new class {};
+$x = new X();
+$y = new class() {};
* Example #2. Fixing with configuration: ['anonymous_class' => false].
--- …
```

Add options to `new_with_braces`

---

.php-cs-fixer.dist.php
.php-cs-fixer.no-header.php
.php-cs-fixer.user-guide.php

This might need discussion.
```console
$ vendor/bin/php-cs-fixer describe date_time_create_from_format_call
Description of date_time_create_from_format_call rule.
The first argument of `DateTime::createFromFormat` method must start with `!`.
Consider this code:
`DateTime::createFromFormat('Y-m-d', '2022-02-11')`.
What value will be returned? '2022-01-11 00:00:00.0'? No, actual return value has 'H:i:s' section like '2022-02-11 16:55:37.0'.        
Change 'Y-m-d' to '!Y-m-d', return value will be '2022-01-11 00:00:00.0'.
So, adding `!` to format string will make return value more intuitive.
Fixer applying this rule is risky.
Risky when depending on the actual timings being used even when not explicit set in format.
* Example #1.
---------- begin diff …
```

Disable `date_time_create_from_format_call`

---

tests/system/Test/TestCaseTest.php

Testing: fix failure of `testStreamFilter` function.

---

.github/workflows/test-phpcpd.yml
system/Database/BaseBuilder.php
system/Database/MySQLi/Builder.php
system/Database/OCI8/Builder.php
system/Database/Postgre/Builder.php
system/Database/SQLSRV/Builder.php
system/Database/SQLite3/Builder.php
tests/system/Database/Builder/UpdateTest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/database/query_builder.rst
user_guide_src/source/database/query_builder/092.php

This PR redesigns the SQL queries generated in `_batchUpdate()`.
This implementation provides more elegant and smaller queries. This method selects the data into a psudo in memory table which provides more flexibility and availability to do more things with.
Because it treats the dataset as a table, a query or a table can be substituted for the dataset. This will be helpful in future ambitions.
Here is a sample of the difference in MySQL:
Old way - 982 Characters - This gets really hard to read when 100 rows long and 15 columns wide:
```SQL
UPDATE `db_update_batch` SET `column1` = CASE 
WHEN `primary_key` = 1 THEN 'test data string T'
WHEN `primary_key` = 2 THEN 'test data string T'
WHEN `primary_key` = 3 THEN 'test data string T'
ELSE `column1` END, `column2` = CASE 
WHEN `primary_key` = …
```

Improve `BaseBuilder::updateBatch()` SQL

---

system/Database/Forge.php
system/Database/MySQLi/Forge.php
system/Database/SQLSRV/Forge.php
system/Database/SQLite3/Forge.php
tests/system/Database/Live/ForgeTest.php
tests/system/Database/Live/SQLite/AlterTableTest.php
tests/system/Database/Live/SQLite/GetIndexDataTest.php
user_guide_src/source/changelogs/v4.3.0.rst

This PR fixes https://github.com/codeigniter4/CodeIgniter4/issues/4494
Ultimately the better option is to allow setting the name manually but so long as we are automatically setting the name it needs to be unique.
I would like to get this change committed before working on some other changes.
**Checklist:**

Make Unique Index Name Unique

---

.php-cs-fixer.dist.php
.php-cs-fixer.no-header.php
.php-cs-fixer.user-guide.php

```console
$ vendor/bin/php-cs-fixer describe single_import_per_statement
Description of single_import_per_statement rule.
There MUST be one use keyword per declaration.
Fixer is configurable using following option:
* group_to_single_imports (bool): whether to change group imports into single imports; defaults to true
--- Original
+++ New
@@ -1,2 +1,4 @@
<?php
-use Foo, Sample, Sample\Sample as Sample2;
+use Foo;
+use Sample;
+use Sample\Sample as Sample2;
* Example #2. Fixing with configuration: ['group_to_single_imports' => true].
--- Original
+++ New
@@ -1,6 +1,4 @@
<?php
-use Space\Models\ {
- …
```

Add `group_to_single_imports` option to `single_import_per_statement`

---

user_guide_src/source/outgoing/response/022.php

There are no microseconds in the Last-Modified header:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified
See https://github.com/codeigniter4/CodeIgniter4/pull/6480#discussion_r967081572
**Checklist:**

docs: fix inappropriate sample code in Response

---

system/Common.php
tests/system/CommonFunctionsTest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/general/common_functions.rst

- add common functions
**Checklist:**

feat: add request() and response()

---

system/Debug/Toolbar.php

Modified #6523.
**Checklist:**

refactor: replace `global $app` with Services

---

psalm.xml

I don't know why, but when we installed Psalm, there was 100 and more errors.
But I ran today, there are more than 10,000 errors with level 1.
level 8:
```
------------------------------
129 errors found
------------------------------
9614 other issues found.
You can display them with --show-info=true
------------------------------
Psalm can automatically fix 3995 of these issues.
Run Psalm again with 
--alter --issues=MissingReturnType,InvalidReturnType,InvalidNullableReturnType,InvalidFalsableReturnType,MissingClosureReturnType,MissingParamType --dry-run
to see what it can fix.
------------------------------
```
level 1:
```
------------------------------
17813 errors found
------------------------------
Psalm can automatically fix 4067 of these issues.
Run Psalm again …
```

chore: change Psalm errorLevel to 8

---

.php-cs-fixer.dist.php
.php-cs-fixer.no-header.php
.php-cs-fixer.user-guide.php

```console
$ vendor/bin/php-cs-fixer describe types_spaces
Description of types_spaces rule.
A single space or none should be around union type and intersection type operators.
* space ('none', 'single'): spacing to apply around union type and intersection type operators; defaults to 'none'
* space_multiple_catch ('none', 'single', null): spacing to apply around type operator when catching exceptions of multiple types, use `null` to follow the value configured for `space`; defaults to null
--- Original
+++ New
@@ -1,6 +1,6 @@
<?php
try
{
new Foo();
-} catch (ErrorA | ErrorB $e) {
+} catch (ErrorA|ErrorB $e) {
echo'error';} …
```

Use the `space_multiple_catch` option of `types_spaces`

---

.php-cs-fixer.dist.php
.php-cs-fixer.no-header.php
.php-cs-fixer.user-guide.php
system/Helpers/text_helper.php
tests/system/Database/BaseConnectionTest.php
user_guide_src/source/outgoing/table/002.php

```console
$ vendor/bin/php-cs-fixer describe whitespace_after_comma_in_array
Description of whitespace_after_comma_in_array rule.
In array declaration, there MUST be a whitespace after each comma.
Fixer is configurable using following option:
* ensure_single_space (bool): if there are only horizontal whitespaces after the comma then ensure it is a single space; defaults to false 
--- Original
+++ New
@@ -1,2 +1,2 @@
<?php
-$sample = array(1,'a',$b,);
+$sample = array(1, 'a', $b, );
* Example #2. Fixing with configuration: ['ensure_single_space' => true].
--- Original
+++ New
@@ -1,2 +1,2 @@
<?php
-$sample …
```

Enable `ensure_single_space` option of `whitespace_after_comma_in_array`

---

app/Config/Modules.php
system/Autoloader/Autoloader.php
tests/system/Autoloader/AutoloaderTest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/general/modules.rst
user_guide_src/source/general/modules/013.php
user_guide_src/source/general/modules/014.php

See https://forum.codeigniter.com/showthread.php?tid=82772
Problems:
- Currently, auto-discovery searches the namespaces of all Composer packages. However, some packages may accidentally have files in the same directory as CI4, and loading the file may cause an error.
- It is useless to search files in Composer packages that are not CI4 modules.
This PR allows you to specify the packages to be searched by configuration.
- add optional config in `Config\Modules`
- `$composerPackages['only']`: If you set this, only listed packages are searched for auto-discovery
- `$composerPackages['exclude']`: If you set this, these packages are excluded for auto-discovery
**Checklist:**

feat: add manual config for Composer package auto-discovery

---

system/Commands/Server/rewrite.php

Fixed #6232 
Add `$_SERVER["SCRIPT_NAME"] = 'index.php'` to route the request to handle by `index.php`, then no more the scenario that always `welcome page` with any request.
**Checklist:**

add: set up "script_name" to handle every request by index.php file.

---

user_guide_src/source/changelogs/v4.0.0.rst
user_guide_src/source/concepts/factories.rst
user_guide_src/source/general/common_functions.rst
user_guide_src/source/installation/upgrade_models.rst
user_guide_src/source/models/model.rst
user_guide_src/source/tutorial/news_section.rst

- improve `model()` explanation
**Checklist:**

docs: improve `model()` explanation

---

system/View/Table.php

docs: replace PHPDoc mixed in view table

---

system/Database/Forge.php
system/Database/MySQLi/Forge.php
system/Database/SQLSRV/Forge.php
system/Database/SQLite3/Forge.php
tests/system/Database/Live/ForgeTest.php
tests/system/Database/Live/SQLite/AlterTableTest.php
tests/system/Database/Live/SQLite/GetIndexDataTest.php
user_guide_src/source/changelogs/v4.3.0.rst

Reverts #6516
This reverts commit 22f9797390be4e883bd37ec3e03b8b55f05dbd96, reversing changes made to 6561bd709f8b7960ec858afa1b2a0723e683b73f.
Conflicts:
user_guide_src/source/changelogs/v4.3.0.rst
**Checklist:**

Revert "Make Unique Index Name Unique #6516"

---

system/HTTP/ResponseTrait.php
system/Helpers/cookie_helper.php
tests/system/HTTP/ResponseCookieTest.php
tests/system/Helpers/CookieHelperTest.php
user_guide_src/source/changelogs/v4.2.7.rst
user_guide_src/source/helpers/cookie_helper.rst
user_guide_src/source/installation/upgrade_427.rst
user_guide_src/source/outgoing/response.rst

fix: set_cookie() does not use Config\Cookie values

---

tests/system/Validation/RulesTest.php

To confirm the current behavior.
**Checklist:**

test: add tests for required_without

---

system/View/Filters.php
system/View/Parser.php
tests/system/View/ParserTest.php

docs: replace types in `View\Parser` and `View\Filters`

---

user_guide_src/source/libraries/validation.rst

- fix incorrect description for `required_without`
- https://github.com/codeigniter4/CodeIgniter4/pull/6559#issuecomment-1253585725
- https://github.com/codeigniter4/CodeIgniter4/issues/5942#issuecomment-1238512986
**Checklist:**

docs: fix validation.rst

---

system/Log/Handlers/ChromeLoggerHandler.php

See #6170
See https://php.watch/versions/8.2/utf8_encode-utf8_decode-deprecated
**Checklist:**

refactor: replace utf8_encode() with mb_convert_encoding()

---

system/Helpers/url_helper.php

docs: replace `mixed` in site_url()

---

system/View/Filters.php
tests/system/View/ParserFilterTest.php

The second parameter of PHP function `round()` should be int.
**Checklist:**

refactor: make $precision int in View Filter round

---

system/HTTP/ContentSecurityPolicy.php
tests/system/HTTP/ContentSecurityPolicyTest.php
user_guide_src/source/changelogs/v4.2.7.rst

From https://forum.codeigniter.com/showthread.php?tid=83041
**Manual Testing**
```php
<?php
{
{
return "<html><script>alert('XSS');</script></html>";
}
}
```
```diff
diff --git a/app/Config/App.php b/app/Config/App.php
index 79e5741b4..7b56cf601 100644
@@ -462,5 +462,5 @@ class App extends BaseConfig
*
* @var bool
*/
-    public $CSPEnabled = false;
+    public $CSPEnabled = true;
}
diff --git a/app/Config/ContentSecurityPolicy.php b/app/Config/ContentSecurityPolicy.php
index 0be616301..ff1361ffe 100644
--- a/app/Config/ContentSecurityPolicy.php
+++ b/app/Config/ContentSecurityPolicy.php
@@ -184,5 +184,5 @@ class ContentSecurityPolicy …
```

fix: CSP autoNonce = false

---

tests/system/Helpers/DateHelperTest.php

Added tests for `timezone_select()` in Date Helper.
**Checklist:**

tests: added test for `timezone_select` function in Date Helper

---

system/Router/RouteCollection.php
tests/system/Router/RouteCollectionTest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/incoming/routing.rst
user_guide_src/source/incoming/routing/065.php
user_guide_src/source/incoming/routing/066.php

#6525 again.
Added a new method to simplify rendering out views directly through routes. While you could do this with a closure, this is tidier and easier to read when using many of these.
This supports static info pages in sites, like About, Privacy, Terms, etc. It also supports a more view-first workflow, where the view is primary object, and View Cells are used to display the dynamic content.
**Checklist:**

Added view() method to route collections

---

system/CodeIgniter.php
system/HTTP/MessageInterface.php
system/HTTP/Response.php
system/HTTP/ResponseInterface.php
system/HTTP/ResponseTrait.php
tests/system/CodeIgniterTest.php
tests/system/RESTful/ResourceControllerTest.php
tests/system/RESTful/ResourcePresenterTest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/installation/upgrade_430.rst

Ref #4356
Fixes #5351
- fix `ResponseInterface`
- fix `MessageInterface`
- deprecate
- `CodeIgniter::$useSafeOutput`
- `CodeIgniter::useSafeOutput()`
**Checklist:**

fix: ResponseInterface (1)

---

.github/PULL_REQUEST_TEMPLATE.md

I think make this comment only, if everyone who made PR didn't show this info.
**Checklist:**

fix: make note PR branch to comment only

---

system/ThirdParty/Kint/Parser/Parser.php

https://github.com/kint-php/kint/releases/tag/4.2.1
**Checklist:**

fix: update ThirdParty Kint to 4.2.1

---

tests/system/Helpers/TextHelperTest.php

Increase coverage in text helper.
**Checklist:**

tests: adding case `word_censor` and ascii entities in text helper

---

system/Helpers/date_helper.php
tests/system/Helpers/DateHelperTest.php

By [comment](https://github.com/codeigniter4/CodeIgniter4/pull/6575#issuecomment-1256792923), other helper like form & html using `\n` to view newline.
**Checklist:**

fix: inconsistent new line view in `date_helper`

---

tests/_support/Config/TestRegistrar.php
tests/system/Config/BaseConfigTest.php

- remove tests for dynamic property
See #6162
**Checklist:**

test: remove Registrar tests for dynamic property

---

user_guide_src/source/installation/installing_composer.rst

Fixes #6560
There is not `--no-dev` option in `require`
https://getcomposer.org/doc/03-cli.md#require-r
**Checklist:**

docs: remove incorrect `--no-dev` option

---

user_guide_src/source/installation/backward_compatibility_notes.rst

[Named arguments](https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments) are not covered by backwards compatibility (BC) promise.
**Checklist:**

docs: add about named arguments in Backward Compatibility Notes

---

user_guide_src/source/cli/cli_generators.rst
user_guide_src/source/extending/events.rst
user_guide_src/source/incoming/request.rst
user_guide_src/source/libraries/cookies.rst

To be consistent.
**Checklist:**

docs: change note type for deprecation to `important`

---

user_guide_src/source/database/query_builder.rst

Follow-up #6536
**Checklist:**

docs: update QueryBuilder *Batch methods

---

.php-cs-fixer.dist.php
.php-cs-fixer.no-header.php
.php-cs-fixer.user-guide.php
admin/framework/composer.json
composer.json
user_guide_src/source/database/results/013.php
user_guide_src/source/outgoing/response/022.php

Update coding-standards version

---

system/Pager/Pager.php
system/Pager/PagerInterface.php
tests/system/Pager/PagerTest.php

docs: replace type in `Pager`

---

user_guide_src/source/libraries/sessions.rst

Small improvements or fixes.
If we agree, I would like to remve all sample code that uses `$_SESSION` directly.
**Checklist:**

docs: improve session

---

system/Helpers/url_helper.php
tests/system/Helpers/URLHelper/MiscUrlTest.php

fix: safe_mailto() does not work with CSP

---

user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/cli/cli_library.rst
user_guide_src/source/dbmgmt/forge.rst
user_guide_src/source/helpers/form_helper.rst
user_guide_src/source/incoming/filters.rst
user_guide_src/source/incoming/routing.rst
user_guide_src/source/libraries/publisher.rst
user_guide_src/source/models/entities.rst
user_guide_src/source/models/model.rst
user_guide_src/source/testing/overview.rst

So that users of older versions will not be confused when they see the latest docs.
- add that new feature can be used from v4.3.0
- add links to detail pages
- small fixes
**Checklist:**

docs: add `.. versionadded:: 4.3.0`, etc.

---

phpstan-baseline.neon.dist
system/View/Cell.php
tests/_support/Cells/StarterCell.php
tests/system/View/CellTest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/outgoing/view_cells.rst

Currently, when calling a View Cell you must enter the fully qualified class name. This change uses the ~~`FileLocator`~~ `Factories` class to search for the class within `*/Cells` directories, allowing a simpler naming in views and a more standardized location for them. 
So now we could do: 
```php
<?= view_cell('Blog::recent', 'limit=5') ?>
```
instead of 
```php
<?= view_cell('App\Modules\Blog\Cells\Blog::recent', 'limit=5') ?>
```
and it could be found in `app/Cells`, `App/Modules/Blog/Cells`, or any other namespace's `Cells` folder.

Allow Cells to be auto-located within */Cells directories

---

system/Helpers/html_helper.php
tests/system/Helpers/HTMLHelperTest.php

Related #6604
- add nonce when CSP is enabled
**Checklist:**

fix: script_tag() does not work with CSP

---

tests/system/Database/Migrations/MigrationRunnerTest.php

I don't know why GA check does not fail, but on my local environment the following test always fails.
```console
1) CodeIgniter\Database\Migrations\MigrationRunnerTest::testLoadsDefaultDatabaseWhenNoneSpecified Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'.../CodeIgniter4/writable/:memory:'
+':memory:'
.../CodeIgniter4/tests/system/Database/Migrations/MigrationRunnerTest.php:84
```
**Checklist:**

test: fix failed MigrationRunnerTest

---

system/Validation/Rules.php
system/Validation/StrictRules/Rules.php
system/Validation/Validation.php
tests/system/Validation/ValidationTest.php
user_guide_src/source/changelogs/v4.2.7.rst
user_guide_src/source/installation/upgrade_427.rst

Fixed the logic to support #5922 and #5942.
**Checklist:**

fix: `required_without` rule logic in `Validation` class.

---

user_guide_src/source/incoming/routing.rst

- The `map()` method is not recommended as well as `add()` because it calls `add()` internally.
**Checklist:**

docs: add Warning to `$routes->map()`

---

system/BaseModel.php
tests/system/Models/ValidationModelTest.php
user_guide_src/source/models/model.rst

Fixes #6577
When you update data, the validation in the model class only validates provided fields.
Model has the property `$this->cleanValidationRules` but it is not able to be used. (Probably a bug)
This PR makes that you can use `$this->cleanValidationRules` and you can change it with `cleanRules()` at runtime.
1. Validation in `insert()`/`insertBatch()` always uses entire rules (force to set `$this->cleanValidationRules = false`).
2. Validation in `update()`/`updateBatch()`/`replace()` uses `$this->cleanValidationRules` value.
3. You can change `$this->cleanValidationRules` value with `cleanRules()`.
4. If `$this->cleanValidationRules = false`, get all data (`$onlyChanged = false`) from the Entity.
Related: #6459
**Checklist:**

fix: `$cleanValidationRules` does not work in Model updates

---

system/API/ResponseTrait.php

docs: replace type `API\ResponseTrait`

---

system/Helpers/inflector_helper.php
tests/system/Helpers/InflectorHelperTest.php
user_guide_src/source/changelogs/v4.3.0.rst
user_guide_src/source/helpers/inflector_helper.rst
user_guide_src/source/helpers/inflector_helper/014.php

New inflector helper function, `decamelize`. 
Converts strings form camelCase or PascalCase into snake_case. 
```php
echo decamelize('MyDogSpot');    // echoes my_dog_spot
```

Decamelize function

---

system/Validation/FormatRules.php
tests/system/Validation/StrictRules/FormatRulesTest.php

The Is_valid_url rule is considered valid when the URL contains a newline at the end.
I think it is invalid.
**Checklist:**

Fixed a bug that URLs with trailing newlines do not become invalid in validation.

---

user_guide_src/source/incoming/routing.rst

- fix RST link to a method reference
**Checklist:**

docs: fix incorrect link to a method in routing.rst

---

user_guide_src/source/libraries/validation.rst

The mime type for jpg, jpeg was erroneously written as `image/jpg` instead of `image/jpeg` as stated in `app/Config/Mimes.php`.
**Checklist:**

docs: fix: update the validation mime type

---

tests/system/Helpers/ArrayHelperTest.php
tests/system/Helpers/FormHelperTest.php
tests/system/Helpers/URLHelper/CurrentUrlTest.php
tests/system/Helpers/URLHelper/MiscUrlTest.php
tests/system/Helpers/URLHelper/SiteUrlTest.php

`IncomingRequest::$uri` will be protected.
- fix incorrect assertions https://github.com/codeigniter4/CodeIgniter4/commit/c42b1bfc2670d598c6431e217fc0176efcf4ace9
- refactor
**Confirm the output of `uri_string()`**
```diff
diff --git a/app/Config/Routes.php b/app/Config/Routes.php
index 0bfdce972..8650842af 100644
@@ -35,7 +35,7 @@ $routes->set404Override();
// We get a performance increase by specifying the default
// route since we don't have to scan directories.
-$routes->get('/', 'Home::index');
+$routes->get('assets/(:any)', 'Home::index');
/*
* --------------------------------------------------------------------
diff --git a/app/Controllers/Home.php b/app/Controllers/Home.php
index 7f867e95f..b8cd3af74 100644 …
```

test:  remove $request->uri

---

system/Language/en/Validation.php
tests/system/Language/LanguageTest.php
user_guide_src/source/changelogs/v4.2.7.rst

fix: missing `valid_json` in Validation Language

---

system/HTTP/Message.php
tests/system/CodeIgniterTest.php
user_guide_src/source/changelogs/v4.3.0.rst

Currently, CodeIgniter blocks HTTP/3 and doesn't consider it a valid version. Chrome, Edge, Firefox, and Safari all support this, though Safari has support turned off by default. 
While this doesn't add any specific feature support, it does it from being ignored as a valid protocol.

Allow HTTP/3 to work and not be blocked.

---

phpstan-baseline.neon.dist

See https://github.com/codeigniter4/CodeIgniter4/actions/runs/3186033011
It seems the error message has been changed:
```
------ ----------------------------------------------------------------------------------------------------
Line   system/CLI/Console.php
------ ----------------------------------------------------------------------------------------------------
71     Strict comparison using === between array<mixed, mixed> and array{} will always evaluate to false.
------ ----------------------------------------------------------------------------------------------------
```
But the `$params` may be empty array, so it still seems false positive.
**Checklist:**
- …

chore: update phpstan-baseline.neon.dist for PHPStan 1.8.7

---

user_guide_src/source/changelogs/v4.2.2.rst
user_guide_src/source/changelogs/v4.2.7.rst

- add Message Changes in changelogs
**Checklist:**

docs: add Message Changes in changelogs

---

system/Session/Handlers/RedisHandler.php
tests/system/Session/Handlers/Database/RedisHandlerTest.php

Fixes  #6512
Make the same as Cache Redis config.
https://github.com/codeigniter4/CodeIgniter4/blob/ed0cdd00eaf20f7d6efb373af991111ead4fece8/app/Config/Cache.php#L155-L161
Ref, https://github.com/phpredis/phpredis#php-session-handler
**Checklist:**

fix: default values for Session Redis Handler

---

tests/system/Helpers/FormHelperTest.php

See https://github.com/codeigniter4/CodeIgniter4/actions/runs/3186033007/jobs/5196234573#step:14:264
```
1) CodeIgniter\Helpers\FormHelperTest::testValidationErrorsFromSession
ErrorException: ini_set(): Session ini settings cannot be changed after headers have already been sent
/.../CodeIgniter4/system/Session/Handlers/FileHandler.php:71
/.../CodeIgniter4/system/Config/Services.php:659
/.../CodeIgniter4/system/Config/BaseService.php:253
/.../CodeIgniter4/system/Config/BaseService.php:194
/.../CodeIgniter4/system/Config/Services.php:638
/.../CodeIgniter4/system/Config/BaseService.php:253
/.../CodeIgniter4/system/Common.php:945
/.../CodeIgniter4/system/Helpers/form_helper.php:701
/.../CodeIgniter4/tests/system/Helpers/FormHelperTest.php:917
```
**Checklist:**
- [] …

test: fix Error ini_set(): Session ini settings cannot be changed

---

CHANGELOG.md
system/CodeIgniter.php
user_guide_src/source/changelogs/index.rst
user_guide_src/source/changelogs/v4.2.7.rst
user_guide_src/source/changelogs/v4.2.8.rst
user_guide_src/source/conf.py
user_guide_src/source/installation/upgrade_427.rst

Updates changelog and version references for 4.2.7.
**Checklist:**

Prep for 4.2.7 release

---

system/Autoloader/Autoloader.php

Follow-up #6503
Upgrade users will see "PHP Warning:  Undefined property: Config\Modules::$composerPackages".
**Checklist:**

fix: error when Config\Modules::$composerPackages is missing

---

system/Config/DotEnv.php
tests/system/Config/DotEnvTest.php
tests/system/Config/fixtures/.env

Fixes #6621 
I think the bug is on the incorrect sanitization of exported env variables with the syntax `export varname=value`.
**Checklist:**

Fix DotEnv class turning `export` to empty string

---

user_guide_src/source/changelogs/v4.2.6.rst
user_guide_src/source/changelogs/v4.2.7.rst

- add SECURITY section in 4.2.7 changelog
- fix link to PR in 4.2.6 changelog
**Checklist:**

docs: improve changelogs

---

tests/system/HTTP/DownloadResponseTest.php
tests/system/HTTP/ResponseTest.php

Fixes #5486
- fix tests that depend on time
**Checklist:**

test: fix ResponseTest::testSetDateRemembersDateInUTC

---

system/Helpers/array_helper.php

See https://github.com/codeigniter4/CodeIgniter4/pull/6637/files#r989477123
**Checklist:**

refactor: _array_search_dot() if conditions

---

system/Session/Session.php

`Session` already imports the `$logger` property through the use of `LoggerAwareTrait`. So this declaration is redundant.
Moreover, if a user accidentally uses `v2` or `v3` of `psr/log`, like [here](https://forum.codeigniter.com/showthread.php?tid=83487) which I think what happened, this will cause an incompatible declaration error.
**Checklist:**

Remove unneeded `$logger` property in `Session`

---

system/HTTP/CLIRequest.php
tests/system/HTTP/CLIRequestTest.php

This PR fixes https://github.com/codeigniter4/CodeIgniter4/issues/6642
It adds the `getCookie()` method to `CLIRequest`. This method may be called by `cookie_helper get_cookie()` where a script is used by both CLI and http.
**Checklist:**

Add CLIRequest::getCookie()

---

system/HTTP/CLIRequest.php

Follow-up #6421
Related #6646
- fix `@return` types
**Checklist:**

docs: fix `@return` types in CLIRequest

---

system/Router/RouteCollection.php
tests/system/HTTP/RedirectResponseTest.php
tests/system/Router/RouteCollectionTest.php

If there are two routes having the same `from` but with the different name,
the first route is not registered correctly.
- fix RouteCollection
- fix incorrect tests
**How to Reproduce the Bug**
```php
$routes->get('/', static fn () => 'Hello World!', ['as' => 'RouteName']);
```
Before:
```
+--------+--------+------------------------------------------+----------------+---------------+
| Method | Route  | Handler                                  | Before Filters | After Filters |
+--------+--------+------------------------------------------+----------------+---------------+
| GET    | /      | \App\Controllers\Home::index             |                | toolbar       |
| CLI    | ci(.*) | \CodeIgniter\CLI\CommandRunner::index/$1 | …
```

fix: routes registration bug
