- composer.json
- Add composer scripts for coding style
- `composer cs`
- `composer cs-fix`
- Add scripts-descriptions in composer.json
**Checklist:**
> Add composer scripts for coding style

- user_guide_src/source/extending/basecontroller.rst
- user_guide_src/source/extending/core_classes.rst
- user_guide_src/source/helpers/cookie_helper.rst
- user_guide_src/source/helpers/xml_helper.rst
- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/libraries/curlrequest.rst
- user_guide_src/source/outgoing/alternative_php.rst
> docs: replace tab with space

- user_guide_src/ghpages.rst
- user_guide_src/source/database/query_builder.rst
- user_guide_src/source/helpers/form_helper.rst
- replace tabs with spaces
**Checklist:**
> docs: replace tabs with spaces

- user_guide_src/source/extending/core_classes.rst
- It was a bit difficult to understand how to add a service
**Checklist:**
> docs: describe in detail how to add a service

- user_guide_src/source/testing/debugging.rst
- add note
- fix style
**Checklist:**
> docs: update debugging

- user_guide_src/source/installation/upgrade_models.rst
- Fix 404 link. See https://codeigniter4.github.io/CodeIgniter4/installation/upgrade_models.html#upgrade-guide
**Checklist:**
> docs: fix 404 link

- user_guide_src/source/installation/upgrade_sessions.rst
- fix indentation of list
**Checklist:**
> docs: fix indentation of list

- admin/pre-commit
> Remove unintended dead code in pre-commit

- user_guide_src/source/installation/upgrade_4xx.rst
- add about CI3 Input and Output
**Checklist:**
> docs: small improvement Upgrading from 3.x to 4.x

- system/Database/Forge.php
- tests/system/Database/Forge/CreateTableTest.php
- refactor test
- fix PHPdoc
**Checklist:**
> Fix Forge test

- user_guide_src/source/libraries/user_agent.rst
From: https://forum.codeigniter.com/thread-80191-post-390316.html#pid390316
**Checklist:**
> docs: fix sample code in user_agent.rst

- tests/README.md
- fix PHPUnit command example
```sh-session
$ vendor/bin/phpunit tests/system/HTTP/RequestTest.php 
PHPUnit 9.5.9 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.0.10
Configuration: /Users/kenji/work/codeigniter/CodeIgniter4/phpunit.xml.dist
......................................                            38 / 38 (100%)
Time: 00:00.166, Memory: 12.00 MB
OK (38 tests, 46 assertions)
```
**Checklist:**
> docs: fix tests/README

- user_guide_src/source/installation/upgrade_412.rst
- user_guide_src/source/testing/feature.rst
- fix classname for testing
**Checklist:**
> docs: fix classname for testing

- user_guide_src/source/libraries/uploaded_files.rst
- fix coding style in user guide
**Checklist:**
> docs: fix coding style in uploaded_files.rst

- .github/PULL_REQUEST_TEMPLATE.md
...so as to skip on deleting them.
**Checklist:**
> Enclose the PR template's notes as comments

- contributing/pull_request.md
- add how to fix code with Rector
**Checklist:**
> docs: add how to fix code with Rector

- system/Exceptions/PageNotFoundException.php
> Fix Localization not working/being ignored for 404 page

- rector.php
Removed in latest rector dev-main 
https://github.com/rectorphp/rector-src/pull/1160
**Checklist:**
- [×] Securely signed commits
> [Rector] Remove FixClassCaseSensitivityNameRector

- user_guide_src/source/general/modules.rst
- add sample code for `Acme\Blog namespace` definition
- add about Filter file, related #4572
**Checklist:**
> docs: improve modules.rst

- user_guide_src/source/incoming/routing.rst
- add warning about CSRF protection
**Checklist:**
> docs: improve routing.rst

- composer.json
- phpstan.neon.dist
- rector.php
- system/View/Table.php
- utils/Rector/UnderscoreToCamelCaseVariableNameRector.php
Upgrading to PHPStan 1.0, Apply rector `dev-main` before next release.
**Checklist:**
> [PHPStan] Upgrade to PHPStan 1.0

- CHANGELOG.md
- Changelog for v4.1.5
- based on GitHub auto-generated relase note
- manual editing
**Checklist:**
> Changelog 4.1.5

- user_guide_src/source/changelogs/v4.1.5.rst
> docs: update changelogs/v4.1.5.rst

- .github/workflows/deploy-framework.yml
- replace `github.repos.` with `github.rest.repos.`
See https://github.com/codeigniter4/CodeIgniter4/pull/5294#issuecomment-963919466
**Checklist:**
> chore: update .github/workflows/deploy-framework.yml

- user_guide_src/source/database/query_builder.rst
- make `warning` security related explanation
**Checklist:**
> docs: improve query_builder.rst

- user_guide_src/source/database/connecting.rst
- improve database/connecting.rst
**Checklist:**
> docs: improve database/connecting.rst

- .github/ISSUE_TEMPLATE/bug_report.yml
- improve ISSUE_TEMPLATE/bug_report.yml
- `Database` was mistaken for the database name or database group
**Checklist:**
> chore: improve ISSUE_TEMPLATE/bug_report.yml

- contributing/pull_request.md
- add git command examples
**Checklist:**
> docs: improve "Sending a Pull Request"

- user_guide_src/source/changelogs/v4.1.2.rst
- user_guide_src/source/installation/upgrade_configuration.rst
- user_guide_src/source/installation/upgrade_controllers.rst
- user_guide_src/source/installation/upgrade_database.rst
- user_guide_src/source/installation/upgrade_emails.rst
- user_guide_src/source/installation/upgrade_encryption.rst
- user_guide_src/source/installation/upgrade_file_upload.rst
- user_guide_src/source/installation/upgrade_html_tables.rst
- user_guide_src/source/installation/upgrade_localization.rst
- user_guide_src/source/installation/upgrade_migrations.rst
- user_guide_src/source/installation/upgrade_models.rst
- user_guide_src/source/installation/upgrade_pagination.rst
- user_guide_src/source/installation/upgrade_responses.rst
- user_guide_src/source/installation/upgrade_routing.rst
- user_guide_src/source/installation/upgrade_security.rst
- user_guide_src/source/installation/upgrade_sessions.rst
- user_guide_src/source/installation/upgrade_validations.rst
- user_guide_src/source/installation/upgrade_view_parser.rst
- user_guide_src/source/installation/upgrade_views.rst
- replace Code**i**gniter with Code**I**gniter
**Checklist:**
> docs: replace Codeigniter with CodeIgniter

- user_guide_src/source/installation/upgrade_4xx.rst
- `redirect()` is significantly changed.
**Checklist:**
> docs: add about redirect() change

- user_guide_src/source/outgoing/view_layouts.rst
- it was a bit difficult to understand
**Checklist:**
> docs: improve view_layouts.rst

- user_guide_src/source/libraries/publisher.rst
- fix RST
- improve method signatures
**Checklist:**
> docs: fix publisher.rst

- user_guide_src/source/testing/controllers.rst
- fix namespaced classnames
**Checklist:**
> docs: fix controllers.rst

- user_guide_src/source/concepts/services.rst
- fix coding style in sample code
**Checklist:**
> docs: fix services.rst

- user_guide_src/source/testing/feature.rst
- decorate variables and methods with ` `` `
**Checklist:**
> docs: improve testing/feature.rst

- user_guide_src/source/outgoing/view_parser.rst
- add space to method signatures
- decorate variables and filename
**Checklist:**
> docs: improve view_parser.rst

- user_guide_src/source/libraries/security.rst
- add Section "Config for CSRF"
**Checklist:**
> docs: improve security.rst

- user_guide_src/source/models/model.rst
- decorate variable names, method names, etc
- small fixes
**Checklist:**
> docs: impove model.rst

- tests/system/Helpers/FilesystemHelperTest.php
> test: fix FilesystemHelperTest

- user_guide_src/source/tutorial/create_news_items.rst
- user_guide_src/source/tutorial/static_pages.rst
- use `BaseController` instead of `Controller`
- See https://forum.codeigniter.com/thread-79365-post-387929.html#pid387929
- add CSRF error display
**Checklist:**
> docs: improve Tutorial

- user_guide_src/source/incoming/routing.rst
- fix incorrect method name
**Checklist:**
> docs: fix routing.rst

- user_guide_src/source/general/configuration.rst
- change *important* to *warning*
**Checklist:**
> docs: small fixes on configuration.rst

- user_guide_src/source/general/managing_apps.rst
update Docs about line number of Paths.php
see:
https://github.com/codeigniter4/CodeIgniter4/blob/2413c8c765dea02e6ea2f8ebd4c150b911fd82b5/spark#L35
https://github.com/codeigniter4/CodeIgniter4/blob/2413c8c765dea02e6ea2f8ebd4c150b911fd82b5/app/Config/Paths.php#L44
**Checklist:**
> update line numbers about Paths.php

- user_guide_src/source/general/modules.rst
- improve explanation. See https://github.com/codeigniter4/CodeIgniter4/pull/5383#discussion_r756543407
**Checklist:**
> docs: improve modules.rst 

- user_guide_src/source/incoming/incomingrequest.rst
- add space after `//` in sample code
**Checklist:**
> docs: fix coding style in incomingrequest.rst 

- user_guide_src/source/installation/upgrade_4xx.rst
- fix about class loading
- decorate file paths with `**`
**Checklist:**
> docs: fix upgrade_4xx.rst

- user_guide_src/source/installation/repositories.rst
- add new repositories of codeigniter4
- update codeigniter.com repository name
**Checklist:**
> docs: update installation/repositories.rst

- .github/workflows/test-phpunit.yml
See https://github.com/codeigniter4/CodeIgniter4/pull/5392#issuecomment-984204067
https://github.com/php-coveralls/php-coveralls/issues/327
**Checklist:**
> chore: temporary fix for PhpCoveralls error

- user_guide_src/source/installation/upgrade_controllers.rst
- user_guide_src/source/installation/upgrade_database.rst
- user_guide_src/source/installation/upgrade_encryption.rst
- user_guide_src/source/installation/upgrade_file_upload.rst
- user_guide_src/source/installation/upgrade_localization.rst
- user_guide_src/source/installation/upgrade_migrations.rst
- user_guide_src/source/installation/upgrade_models.rst
- user_guide_src/source/installation/upgrade_security.rst
- user_guide_src/source/installation/upgrade_validations.rst
- user_guide_src/source/installation/upgrade_views.rst
> docs: change text decoration for installation/upgrade_*

- user_guide_src/source/libraries/time.rst
Fixes #5430
- fix sample code that uses non-existent methods
**Checklist:**
> docs: fix time.rst

- user_guide_src/source/installation/upgrade_routing.rst
> docs: fix upgrade_routing.rst

- user_guide_src/source/installation/upgrade_configuration.rst
- remove deprecated `CodeIgniter\Config\Config::get()` usage
- decorate file paths with **
**Checklist:**
> docs: fix upgrade_configuration.rst

- user_guide_src/source/installation/index.rst
- user_guide_src/source/intro/index.rst
- add "License Agreement" and "Change Logs" in the TOC
**Checklist:**
> docs: add "License Agreement" and "Change Logs" in the TOC

- contributing/documentation.rst
- remove out-of-dated explanation
- add how to make references
**Checklist:**
> docs: update contributing/documentation.rst

- user_guide_src/ghpages.rst
- update the user guide URL
**Checklist:**
> docs: update user_guide_src/ghpages.rst

- system/Helpers/array_helper.php
- The regex is difficult to understand.
**Checklist:**
> refactor: dot_array_search() regex

- system/I18n/Time.php
- failed test on local PHP 8.1
- https://bugs.php.net/bug.php?id=81660
**Checklist:**
> refactor: Time::getDst()

- user_guide_src/source/general/helpers.rst
- improve text decoration
**Checklist:**
> docs: improve text decoration in helpers.rst

- user_guide_src/source/dbmgmt/migration.rst
- update command option `--all`
- improve command sample
**Checklist:**
> docs: improve migration.rst

- user_guide_src/source/incoming/filters.rst
- add warning about the possibility of bypassing the filter
**Checklist:**
> docs: improve filters.rst

- system/View/View.php
Optimizing duplicate code in the View class.
**Checklist:**
> The View class. Optimizing duplicate code.

- user_guide_src/source/helpers/html_helper.rst
- remove out of dated raw html
**Checklist:**
> docs: remove out of dated raw html in html_helper.rst 

- user_guide_src/source/models/entities.rst
- fix incorrect variable name and classname
- improve text decoration
**Checklist:**
> docs: fix entities.rst

- user_guide_src/source/tutorial/news_section.rst
- use BaseController instead of Controller
**Checklist:**
> docs: update tutorial code

- user_guide_src/source/incoming/routing.rst
> docs: add sample code in routing.rst

- system/Entity/Cast/DatetimeCast.php
- update deprecated method
**Checklist:**
> refactor: update deprecated method in DatetimeCast

- user_guide_src/source/outgoing/api_responses.rst
- fix JSONFormatter namespace
**Checklist:**
> docs: fix api_responses.rst

- user_guide_src/source/libraries/validation.rst
- add warning about XSS risk
- fix note
**Checklist:**
> docs: improve validation.rst

- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/outgoing/views.rst
- add `views()`'s option `cache`
**Checklist:**
> docs: fix view() in common_functions.rst 

- user_guide_src/source/general/logging.rst
- fix incorrect sample code
**Checklist:**
> docs: fix incorrect sample code in logging.rst 

- tests/system/API/ResponseTraitTest.php
- fix doc comment
**Checklist:**
> test: fix doc comment in ResponseTraitTest

- user_guide_src/source/extending/core_classes.rst
> docs: fix sample code in extending/core_classes.rst

- user_guide_src/source/dbmgmt/forge.rst
- change text decoration or so
**Checklist:**
> docs: improve dbmgmt/forge.rst

- system/ComposerScripts.php
- system/ThirdParty/Escaper/LICENSE.md
- system/ThirdParty/Kint/LICENSE
- system/ThirdParty/PSR/Log/LICENSE
- there is no license files in CI4 Zip file
**Checklist:**
> chore: add third party license files

- user_guide_src/source/changelogs/v4.1.6.rst
- user_guide_src/source/installation/upgrade_416.rst
- minor addition
**Checklist:**
> docs: minor addition to changelogs/v4.1.6.rst and upgrade_416.rst

- user_guide_src/source/installation/running.rst
Resolution of issue #4471
**Checklist:**
> Add information for apache mod_userdir

- admin/RELEASE.md
Adds instructions for running a simple test to the release process.
**Checklist:**
- n/a Component(s) with PHPDoc blocks, only if necessary or adds value
> Post-Release Test

- tests/system/CommonFunctionsTest.php
- improve slow test testTrace()
**Checklist:**
> test: improve slow testTrace()

- user_guide_src/source/database/query_builder.rst
Follow-up #5510
Subquery documentation fix
**Checklist:**
> Fix: QueryBuilder doc

- admin/starter/builds
Because PR to develop branch causes errors due to style
**Checklist:**
> Fixed style for PHP7.4

- user_guide_src/source/changelogs/v4.2.0.rst
- user_guide_src/source/database/query_builder.rst
- improve query_builder.rst
- add changelogs/v4.2.0.rst
**Checklist:**
> docs: improve query_builder.rst and add changelogs/v4.2.0.rst

- phpstan-baseline.neon.dist
- phpstan.neon.dist
- system/Helpers/text_helper.php
- system/View/ViewDecoratorTrait.php
- tests/_support/Autoloader/FatalLocator.php
- tests/_support/Commands/LanguageCommand.php
Just cleaning up phpstan and style errors I was getting locally.
> Fixing phpstan and style errors

- user_guide_src/source/libraries/pagination.rst
Topics related to pagination periodically appear on the forum. Some developers do not understand how it works.
Therefore, I want to suggest a clarification in the documentation for the Pagination library when using the ``Model::paginate()`` method
**Checklist:**
> docs: Clarification when working with model pagination.

- system/Validation/Validation.php
Current logic uses `array_reduce` and iterates over the entire flattened data looking for matches. This PR refactors this by breaking early once it found a match, potentially improving resources over large arrays.
**Checklist:**
> Refactor `if_exist` validation with dot notation

- user_guide_src/source/installation/upgrade_configuration.rst
- user_guide_src/source/installation/upgrade_controllers.rst
- user_guide_src/source/installation/upgrade_database.rst
- user_guide_src/source/installation/upgrade_emails.rst
- user_guide_src/source/installation/upgrade_encryption.rst
- user_guide_src/source/installation/upgrade_file_upload.rst
- user_guide_src/source/installation/upgrade_html_tables.rst
- user_guide_src/source/installation/upgrade_localization.rst
- user_guide_src/source/installation/upgrade_migrations.rst
- user_guide_src/source/installation/upgrade_models.rst
- user_guide_src/source/installation/upgrade_pagination.rst
- user_guide_src/source/installation/upgrade_responses.rst
- user_guide_src/source/installation/upgrade_routing.rst
- user_guide_src/source/installation/upgrade_security.rst
- user_guide_src/source/installation/upgrade_sessions.rst
- user_guide_src/source/installation/upgrade_validations.rst
- user_guide_src/source/installation/upgrade_view_parser.rst
- user_guide_src/source/installation/upgrade_views.rst
- replace `3.11` with `3.x` 
- add explanations to upgrade_views.rst
**Checklist:**
> docs: fix Upgrading from 3.x to 4.x

- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/incoming/routing.rst
- change text decoration
- add note
- add more specific link
- fix typos
**Checklist:**
> docs: improve controllers.rst

- system/Debug/Toolbar/Collectors/Routes.php
Before:
After:
```php
<?php
{
public function index($a = '', $b = '')
{
return view('welcome_message');
}
}
```
**Checklist:**
> fix: debug toolbar Routes Params output

- system/Test/ConfigFromArrayTrait.php
- tests/system/Filters/FiltersTest.php
- tests/system/Router/RouteCollectionTest.php
- add `Test/ConfigFromArrayTrait.php`
- fix typos
**Checklist:**
> test: refactor: extract createConfigFromArray()

- admin/RELEASE.md
- add about PHP Security Advisories Database
**Checklist:**
> chore: update admin/RELEASE.md

- user_guide_src/source/testing/fabricator.rst
- update Faker URL
**Checklist:**
> docs: update Faker URL

- user_guide_src/source/changelogs/v4.1.6.rst
- It is better to be documented
- https://github.com/codeigniter4/framework/commit/557705a45a0358f162cc0fa620c22428149f70b8
**Checklist:**
> docs: add version up of Kint in changelog

- user_guide_src/source/incoming/message.rst
- user_guide_src/source/incoming/request.rst
- user_guide_src/source/libraries/curlrequest.rst
- user_guide_src/source/outgoing/response.rst
- fix search and replace errors
**Checklist:**
> docs: replace getServer with server

- user_guide_src/source/libraries/validation.rst
- fix format
Before:
After:
**Checklist:**
> docs: fix validation.rst format

- system/CodeIgniter.php
> fix: spark does not show Exception

- user_guide_src/source/general/errors.rst
- change text decoration, etc.
**Checklist:**
> docs: small fix general/errors.rst

- user_guide_src/source/database/queries.rst
- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/helpers/filesystem_helper.rst
- user_guide_src/source/incoming/request.rst
- user_guide_src/source/installation/upgrade_file_upload.rst
- user_guide_src/source/installation/upgrade_validations.rst
- user_guide_src/source/libraries/email.rst
- user_guide_src/source/libraries/publisher.rst
- update coding style of `if`
**Checklist:**
> docs: update coding style of `if`

- user_guide_src/source/testing/mocking.rst
> docs: fix sample code in mocking.rst

- user_guide_src/source/extending/basecontroller.rst
Follow-up #5647
**Checklist:**
> docs: remove out of dated explanation in basecontroller.rst 

- user_guide_src/source/outgoing/view_renderer.rst
- fix RST format error
- add spaces in method signatures
- change the body text to a warning
- change text decoration
**Checklist:**
> docs: improve view_renderer.rst

- contributing/internals.md
> docs: update internals.md

- .no-header.php-cs-fixer.dist.php
- .php-cs-fixer.dist.php
- admin/framework/composer.json
- composer.json
- spark
- system/Test/Mock/MockSecurityConfig.php
- tests/system/Config/ServicesTest.php
- tests/system/Cookie/CookieStoreTest.php
- tests/system/Helpers/SecurityHelperTest.php
- tests/system/Log/Handlers/ErrorlogHandlerTest.php
> Permit use of lates php-cs-fixer v3.6

- tests/AutoReview/ComposerJsonTest.php
From https://github.com/codeigniter4/CodeIgniter4/pull/5668#discussion_r803202876
**Checklist:**
> Auto-review `require-dev` matching

- user_guide_src/source/models/model.rst
Closes #5549
- add about Model and Query Builder
**Checklist:**
> docs: add about Model and Query Builder in model.rst

- user_guide_src/source/models/entities.rst
- add note about $attributes
**Checklist:**
> docs: improve entities.rst

- system/Debug/Toolbar.php
- system/Debug/Toolbar/Views/toolbar.tpl.php
update debug toolbar vars response header
update debug toolbar vars response header no repeat request header
**Checklist:**
> fix: debug toolbar vars response headers includes request headers

- user_guide_src/source/incoming/incomingrequest.rst
- user_guide_src/source/libraries/uploaded_files.rst
> docs: fix incorrect description about Uploaded Files in incomingrequest.rst

- user_guide_src/source/installation/upgrading.rst
See https://forum.codeigniter.com/thread-81199.html
**Checklist:**
> docs: add note about how you can check what version of CodeIgniter you are currently running

- user_guide_src/source/cli/cli.rst
- user_guide_src/source/incoming/routing.rst
- improve link
- add warning about auto-routng
**Checklist:**
> docs: improve CLI only routing

- system/Common.php
- system/View/Cell.php
> docs: fix @param of view cell

- admin/css/debug-toolbar/_theme-dark.scss
- admin/css/debug-toolbar/_theme-light.scss
- admin/css/debug-toolbar/toolbar.scss
- system/Debug/Toolbar/Views/toolbar.css
I don't know if this was a design choice or not. But it's looks bit broken with few alignment issues. So I have fixed that and made little cosmetic color changes to make those elements go align with CI4 color theme.
Before...
After...
Thanks.
> Fix alignment on few buttons in debug toobar and change color

- .github/workflows/test-scss.yml
- contributing/css.md
- system/Debug/Toolbar/Views/toolbar.css
Follow up to #5715 
Adds a workflow to test whether changes to SCSS files are considered in the CSS, and vice versa.
**Checklist:**
> Sass workflow

- .github/workflows/test-deptrac.yml
- .github/workflows/test-phpcpd.yml
- .github/workflows/test-phpstan.yml
- .github/workflows/test-phpunit.yml
- .github/workflows/test-rector.yml
Some of our workflow run even though the changes are not PHP related hence wasting time and resources.
**Checklist:**
> Limit running PHP workflows to related PHP files

- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/libraries/validation/028.2.php
This is now cherry-picked and standalone.
[x] Extract new validation examples.
> [Docs] Extract new examples from validation.

- user_guide_src/source/installation/upgrade_420.rst
Latest version is 4.1.9, so the note should be from 4.1.9
**Checklist:**
> [Doc] Upgrading to 4.2.0 from 4.1.9

- system/Test/CIUnitTestCase.php
- add parameter to initialize autoloader
**Checklist:**
> test: add parameter to initialize autoloader in $this->resetService()

- user_guide_src/source/tutorial/create_news_items.rst
- user_guide_src/source/tutorial/index.rst
- user_guide_src/source/tutorial/news_section.rst
- user_guide_src/source/tutorial/static_pages.rst
- fix section titles
**Checklist:**
> docs: small fixes in tutorial

- user_guide_src/source/libraries/security.rst
from [Security advisory](https://github.com/codeigniter4/CodeIgniter4/security/advisories/GHSA-4v37-24gm-h554).
**Checklist:**
> docs: add how to code to prevent CSRF

- user_guide_src/source/outgoing/localization/005.php
- user_guide_src/source/testing/database/002.php
> docs: fix sample code

- user_guide_src/source/extending/basecontroller.rst
- user_guide_src/source/extending/core_classes.rst
- user_guide_src/source/extending/events.rst
- add TOC
- update core system class list
**Checklist:**
> docs: small fixes in extending

- user_guide_src/source/extending/common.rst
- user_guide_src/source/extending/events.rst
- user_guide_src/source/extending/events/001.php
- user_guide_src/source/extending/events/002.php
- fix events.rst
**Checklist:**
> docs: fix events.rst

- user_guide_src/source/libraries/publisher.rst
- small improve description
**Checklist:**
> docs: fix RST format in publisher.rst

- system/ThirdParty/Escaper/Escaper.php
- Upgrading laminas/laminas-escaper (2.9.0 => 2.10.0)
**Checklist:**
> Update Laminas Escaper to v2.10

- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/helpers/url_helper.rst
See https://github.com/codeigniter4/CodeIgniter4/issues/5811#issuecomment-1073010731
**Checklist:**
> docs: add redirect()->back() explanation

- tests/system/Session/Handlers/Database/AbstractHandlerTestCase.php
- tests/system/Session/Handlers/Database/MySQLiHandlerTest.php
- tests/system/Session/Handlers/Database/PostgreHandlerTest.php
> Rename `Abstact` to `Abstract`

- app/Views/welcome_message.php
https://codeigniter.com/en/contribute not found
**Checklist:**
> update contribute link in Welcome page

- app/Config/Mimes.php
- user_guide_src/source/changelogs/v4.2.0.rst
- add mime type for webp
From https://forum.codeigniter.com/showthread.php?tid=81619
**Checklist:**
> config: add mime type for webp

- user_guide_src/source/models/model/055.php
- remove unneeded & in sample code
**Checklist:**
> docs: remove unneeded & in sample code in model.rst

- user_guide_src/source/helpers/filesystem_helper.rst
- fix function reference, mainly variable names.
**Checklist:**
> docs: fix filesystem_helper.rst

- contributing/bug_report.md
- remove out of dated description and add a link
**Checklist:**
> docs: update contributing/bug_report.md Security

- user_guide_src/source/concepts/services.rst
- user_guide_src/source/concepts/services/003.php
- user_guide_src/source/concepts/services/004.php
- user_guide_src/source/concepts/services/005.php
- user_guide_src/source/concepts/services/009.php
- user_guide_src/source/concepts/services/012.php
- user_guide_src/source/concepts/services/013.php
- user_guide_src/source/concepts/services/014.php
> docs: improve Services

- user_guide_src/source/general/managing_apps.rst
ref:
https://github.com/codeigniter4/CodeIgniter4/blob/957656faf0875e8ecf0771e977c1f2d35a4d8961/spark#L49
**Checklist:**
> doc: fix `$pathsConfig` for spark

- user_guide_src/source/libraries/curlrequest.rst
- user_guide_src/source/libraries/curlrequest/020.php
- user_guide_src/source/libraries/curlrequest/021.php
- user_guide_src/source/libraries/curlrequest/022.php
- user_guide_src/source/libraries/curlrequest/023.php
- user_guide_src/source/libraries/curlrequest/030.php
- user_guide_src/source/libraries/curlrequest/031.php
- user_guide_src/source/libraries/curlrequest/034.php
> docs: add `literalinclude` for curlrequest -> debug

- user_guide_src/source/installation/upgrade_4xx.rst
> docs: add TOC in  upgrade_4xx.rst

- user_guide_src/source/changelogs/v4.2.0.rst
> docs: add link to the detailed page in changelogs/v4.2.0.rst

- user_guide_src/source/libraries/email.rst
> docs: mailPath Alright!

- user_guide_src/source/general/managing_apps.rst
- user_guide_src/source/general/managing_apps/001.php
- user_guide_src/source/general/managing_apps/005.php
From https://forum.codeigniter.com/showthread.php?tid=81690
- add note for composer.json autoload.psr-4
- change example from Zip install to Composer install
If you want to see running sample, see https://github.com/kenjis/codeigniter4-multiple-apps-sample
**Checklist:**
> docs: improve Managing your Applications

- user_guide_src/source/concepts/autoloader.rst
- add TOC
- update/fix descriptions
**Checklist:**
> docs: fix autoloader.rst

- user_guide_src/source/intro/requirements.rst
> docs: small improvements in requirements.rst

- user_guide_src/source/models/model.rst
- fix heading underlines
- change `**property/method**` to headings
- You can link to the properties and methods
**Checklist:**
> docs: improve model.rst

- user_guide_src/source/changelogs/v4.1.0.rst
- user_guide_src/source/installation/upgrade_404.rst
- user_guide_src/source/installation/upgrade_405.rst
- user_guide_src/source/installation/upgrade_410.rst
- user_guide_src/source/installation/upgrade_412.rst
- user_guide_src/source/installation/upgrade_413.rst
- user_guide_src/source/installation/upgrade_414.rst
- user_guide_src/source/installation/upgrade_415.rst
- add links to upgrade instructions in Upgrading pages
- improve changelog v4.1.0
- improve upgrade_410
**Checklist:**
> docs: improve  past upgrade (v4.1.0)

- admin/starter/tests/README.md
- tests/README.md
- update and improvement
**Checklist:**
> docs: update tests/README

- user_guide_src/source/testing/overview.rst
- update PHPUnit link
**Checklist:**
> docs: improve testing/overview.rst

- user_guide_src/source/incoming/routing.rst
- make titles linkable
**Checklist:**
> docs: small improvements in routing.rst

- app/Views/errors/html/error_404.php
Fixes  #5976
See https://developer.mozilla.org/en-US/docs/web/CSS/letter-spacing
**Checklist:**
> fix: invalid css in error_404.php

- user_guide_src/source/cli/cli_request.rst
- user_guide_src/source/cli/cli_request/004.php
- user_guide_src/source/cli/cli_request/006.php
- align comment indentation
**Checklist:**
> docs: improve cli_request.rst

- system/Router/Router.php
- tests/system/Router/RouterTest.php
- add HTTP verb
**Checklist:**
> improve Router Exception message

- user_guide_src/source/database/utilities.rst
- user_guide_src/source/database/utilities/001.php
- make method name linkable
**Checklist:**
> docs: improve database/utilities.rst

- user_guide_src/source/database/queries.rst
> docs: small improvements in database/queries.rst

- user_guide_src/source/helpers/cookie_helper.rst
- user_guide_src/source/incoming/incomingrequest.rst
- user_guide_src/source/libraries/sessions.rst
- update deprecated `$cookiePrefix`
**Checklist:**
> docs: update deprecated `$cookiePrefix`

- user_guide_src/source/database/helpers.rst
> docs: make method names linkable in database/helpers.rst

- user_guide_src/source/helpers/cookie_helper.rst
- user_guide_src/source/outgoing/response.rst
- add text decoration
- update config filename
- add a note for confusing behavior
**Checklist:**
> docs: improve cookies

- user_guide_src/source/libraries/sessions.rst
> docs: add note for Session::get()

- user_guide_src/source/concepts/autoloader.rst
- user_guide_src/source/concepts/factories.rst
- user_guide_src/source/concepts/http.rst
- user_guide_src/source/concepts/mvc.rst
- user_guide_src/source/concepts/security.rst
- user_guide_src/source/concepts/services.rst
- user_guide_src/source/concepts/structure.rst
- fix title level
- small fixes
**Checklist:**
> docs: small improvements in concepts

- system/Autoloader/FileLocator.php
- system/Database/MigrationRunner.php
- No need to return directories
Ref #6026
**Checklist:**
> refactor: use get_filenames() 4th param

- user_guide_src/source/testing/overview.rst
- user_guide_src/source/testing/overview/003.php
- user_guide_src/source/testing/overview/004.php
- user_guide_src/source/testing/overview/016.php
- user_guide_src/source/testing/overview/017.php
- user_guide_src/source/testing/overview/018.php
I wanted to add info for testing beginners like the following in the *Build Your First Application*:
> If you are not familiar with PHP, we recommend that you check out the [W3Schools PHP Tutorial](https://www.w3schools.com/php/default.asp) before continuing.
But I can't find good proper URLs.
**Checklist:**
> docs: small improvements in testing/overview.rst

- user_guide_src/source/installation/upgrade_420.rst
- add an important note to make it stand out
**Checklist:**
> docs: add upgrade procedure example for v4.2.0

- user_guide_src/source/changelogs/v4.2.0.rst
- user_guide_src/source/incoming/routing.rst
- categorize items
- remove duplicated items
- add link
**Checklist:**
> docs: improve changelog v4.2.0

- system/Validation/FormatRules.php
Small change to improve the reading and understanding of the code, for not type conflict.
**Checklist:**
> Small change to improve code reading

- tests/system/Throttle/ThrottleTest.php
> Fix ThrottleTest failing occasionally

- user_guide_src/source/models/model.rst
> docs: add note to $allowedFields

- user_guide_src/requirements.txt
- update sphinx, sphinxcontrib-phpdomain
**Checklist:**
> chore: update Sphinx version

- admin/starter/preload.php
@kenjis per our discussion on slack.
**Checklist:**
> Move preload.php example to starter app

- system/Router/AutoRouterImproved.php
Apply ``AutoRouterImproved::translateURIDashes()`` in code
**Checklist:**
> Apply AutoRouterImproved::translateURIDashes()

- .github/workflows/test-deptrac.yml
- .github/workflows/test-phpcpd.yml
- .github/workflows/test-phpstan.yml
- .github/workflows/test-phpunit.yml
- .github/workflows/test-rector.yml
- .github/workflows/test-scss.yml
Now we use `4.3` branch for the next minor version development.
**Checklist:**
> chore: update workflow for 4.3 branch

- user_guide_src/source/changelogs/v4.2.0.rst
- add Highlights in changelog v4.2.0
**Checklist:**
> docs: add highlights for v4.2.0

- .github/PULL_REQUEST_TEMPLATE.md
- contributing/pull_request.md
We have change the branch model.
**Checklist:**
> docs: update pull_request.md and PULL_REQUEST_TEMPLATE.md

- system/BaseModel.php
- tests/_support/Models/EventModel.php
- tests/system/Models/EventsModelTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/models/model.rst
Add before and after events for ``BaseModel::insertBatch()`` and ``BaseModel::updateBatch()`` methods as 
[mentioned in the forum](https://forum.codeigniter.com/showthread.php?tid=80989)
**Checklist:**
> Feat add events for insertBatch()/updateBatch()

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.2.1.rst
- user_guide_src/source/conf.py
Updates changelog and version references for 4.2.1.
**Checklist:**
> Prep for 4.2.1 release

- admin/starter/preload.php
Follow-up #6088
- update classname
**Checklist:**
> docs: update classname in preload.php

- contributing/pull_request.md
- contributing/workflow.md
- update for branch model change
**Checklist:**
> docs: update for branch model change

- admin/RELEASE.md
- add step to update the next minor upgrade branch
- update format
**Checklist:**
> docs: update RELEASE.md

- system/Session/Session.php
Fixes #6166
See https://github.com/codeigniter4/CodeIgniter4/issues/6166#issuecomment-1161381092
**Checklist:**
> fix: Session cookies are sent twice with Ajax

- system/CLI/CLI.php
- system/Common.php
- system/Config/Factories.php
- system/Database/BaseBuilder.php
- system/Filters/Filters.php
- system/HTTP/Files/UploadedFile.php
- system/HTTP/RequestTrait.php
- system/HTTP/ResponseTrait.php
- fix/add PHPDocs
**Checklist:**
> docs: fix/add PHPDocs

- user_guide_src/source/libraries/pagination.rst
- user_guide_src/source/libraries/pagination/015.php
- user_guide_src/source/models/model.rst
> docs: improve pagination.rst

- user_guide_src/source/database/metadata.rst
- user_guide_src/source/libraries/publisher.rst
- user_guide_src/source/libraries/security.rst
- user_guide_src/source/libraries/uploaded_files.rst
- make methods linkable
**Checklist:**
> docs: make methods linkable

- system/Database/BaseConnection.php
- system/Database/BasePreparedQuery.php
- system/Database/MySQLi/Connection.php
- system/Database/MySQLi/PreparedQuery.php
- system/Database/OCI8/Connection.php
- system/Database/OCI8/PreparedQuery.php
- system/Database/Postgre/Connection.php
- system/Database/Postgre/PreparedQuery.php
- system/Database/SQLSRV/Connection.php
- system/Database/SQLSRV/PreparedQuery.php
- system/Database/SQLite3/Connection.php
- system/Database/SQLite3/PreparedQuery.php
- tests/system/Database/Live/BadQueryTest.php
- tests/system/Database/Live/DbDebugTest.php
- tests/system/Database/Live/PreparedQueryTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/installation/upgrade_430.rst
> fix: throws DatabaseException in DB connections

- user_guide_src/source/cli/cli_generators.rst
- user_guide_src/source/incoming/controllers.rst
- improve cli_generators.rst
- add note about controller --suffix
**Checklist:**
> docs: improve cli_generators.rst

- .github/workflows/test-rector.yml
Continue of https://github.com/codeigniter4/CodeIgniter4/pull/6225
**Checklist:**
> Apply github workflow to run rector on utils/ directory

- contributing/pull_request.md
- contributing/workflow.md
- add explanations when creating branch from next-minor-version-branch
- change Markdown command style
**Checklist:**
> docs: improve contributing Pull Request

- user_guide_src/source/incoming/routing.rst
> docs: add note about the status code for set404Override()

- user_guide_src/source/testing/benchmark.rst
- user_guide_src/source/testing/benchmark/007.php
- user_guide_src/source/testing/benchmark/008.php
- user_guide_src/source/testing/benchmark/009.php
- fix and improve benchmark.rst
**Checklist:**
> docs: fix benchmark.rst

- user_guide_src/source/libraries/uploaded_files.rst
- user_guide_src/source/libraries/uploaded_files/021.php
- fix sample code (does not work without legacy auto routing)
- decorate text
**Checklist:**
> docs: fix uploaded_files.rst

- user_guide_src/source/libraries/caching.rst
- add spark commands
- make section title linkable
**Checklist:**
> docs: improve caching.rst

- user_guide_src/source/general/environments.rst
- text decoration
- add note on `spark env` command
**Checklist:**
> docs: improve environments.rst

- user_guide_src/source/concepts/autoloader.rst
- add note on `spark namespaces`
**Checklist:**
> docs: add note on `spark namespaces`

- system/Entity/Entity.php
- system/Format/FormatterInterface.php
- system/Format/JSONFormatter.php
- system/HTTP/Message.php
- system/HTTP/MessageTrait.php
- system/HTTP/ResponseTrait.php
- system/Helpers/array_helper.php
> docs: fix PHPDocs

- contributing/pull_request.md
- add link to the forum thread for Unit Testing
**Checklist:**
> docs: update contributing/pull_request.md

- system/Debug/Toolbar.php
- remove unnecessary getBody()
**Checklist:**
> refactor: debug toolbar

- admin/module/phpunit.xml.dist
- admin/starter/phpunit.xml.dist
- phpunit.xml.dist
- update indentation
- remove unnecessary env XDEBUG_MODE
**Checklist:**
> config: update phpunit.xml.dist

- app/Config/Encryption.php
- phpstan-baseline.neon.dist
- system/Encryption/Handlers/OpenSSLHandler.php
- tests/system/Encryption/EncryptionTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/installation/upgrade_encryption.rst
- user_guide_src/source/libraries/encryption.rst
- user_guide_src/source/libraries/encryption/013.php
See https://forum.codeigniter.com/showthread.php?tid=82494
- can decrypt encrypted data by CI3
- add *Supported HMAC Authentication Algorithms* from CI3
Related  #5769
Fixes #5769
**Checklist:**
> feat: Encryption CI3 compatibility

- user_guide_src/source/general/environments.rst
- user_guide_src/source/general/urls.rst
- user_guide_src/source/installation/index.rst
- user_guide_src/source/installation/running.rst
- user_guide_src/source/installation/troubleshooting.rst
You can find all server configurations at https://codeigniter4.github.io/CodeIgniter4/installation/running.html.
**Checklist:**
> docs: improve Web server config page

- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/libraries/validation/001.php
- user_guide_src/source/libraries/validation/002.php
- user_guide_src/source/libraries/validation/039.php
- make view filenames lowercase
- add routes
- use BaseController instead of Controller
- do not show validation errors when showing the form for the first time
- show input data when validation errors show
- use $helpers
- remove loading URL helper
**Checklist:**
> docs: improve Form Validation Tutorial

- user_guide_src/source/tutorial/static_pages.rst
See https://forum.codeigniter.com/showthread.php?tid=82587
**Checklist:**
> docs: fix wrong URL explanation in Tutorial

- user_guide_src/source/general/common_functions.rst
- add note for redirect()
**Checklist:**
> docs: add note for redirect()

- user_guide_src/source/database/metadata/001.php
- user_guide_src/source/database/metadata/002.php
- user_guide_src/source/database/metadata/003.php
- user_guide_src/source/database/metadata/004.php
- user_guide_src/source/database/metadata/005.php
- user_guide_src/source/database/metadata/006.php
- user_guide_src/source/database/metadata/007.php
- user_guide_src/source/database/metadata/008.php
- user_guide_src/source/database/metadata/009.php
See https://forum.codeigniter.com/showthread.php?tid=82600
**Checklist:**
> docs: improve database/metadata.rst

- user_guide_src/source/general/environments.rst
- user_guide_src/source/installation/running.rst
- user_guide_src/source/installation/troubleshooting.rst
- user_guide_src/source/tutorial/index.rst
- improve Whoops page explanation
- improve Initial Configuration
**Checklist:**
> docs: improve Whoops page explanation and Initial Configuration

- app/Views/errors/html/error_404.php
- system/Language/en/Errors.php
language strings for error_404.php added and style updated to the same as production.php
**Checklist:**
> error_404.php translation and design

- system/ThirdParty/Kint/Utils.php
> chore: update Kint to 4.1.4 in ThirdParty

- user_guide_src/source/installation/upgrade_422.rst
> docs: fix upgrade_422.rst Content Changes

- system/Session/Session.php
> docs: add `@property` to Session

- user_guide_src/source/installation/upgrade_423.rst
- user_guide_src/source/installation/upgrading.rst
- add Prefious and Next button
- add upgrade_423 in upgrading.rst
Before:
After:
**Checklist:**
> docs: fix upgrade 423.rst

- user_guide_src/source/changelogs/v4.2.2.rst
- user_guide_src/source/installation/upgrade_422.rst
See https://github.com/codeigniter4/shield/pull/347#issuecomment-1208903283
**Checklist:**
> docs:  improve Forge::createTable() change description

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.2.4.rst
- user_guide_src/source/changelogs/v4.2.5.rst
- user_guide_src/source/conf.py
Updates changelog and version references for 4.2.4.
**Checklist:**
> Prep for 4.2.4 hotfix

- user_guide_src/source/general/managing_apps/002.php
- user_guide_src/source/general/managing_apps/003.php
see: https://github.com/codeigniter4/CodeIgniter4/pull/6386#pullrequestreview-1076631735
**Checklist:**
> docs: remove comments code sample about Paths

- contributing/documentation.rst
- user_guide_src/source/changelogs/v4.2.0.rst
- user_guide_src/source/changelogs/v4.2.2.rst
- user_guide_src/source/cli/cli_commands.rst
- user_guide_src/source/database/results.rst
- user_guide_src/source/dbmgmt/forge.rst
- user_guide_src/source/dbmgmt/migration.rst
- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/helpers/cookie_helper.rst
- user_guide_src/source/incoming/message.rst
- user_guide_src/source/incoming/request.rst
- user_guide_src/source/installation/upgrade_422.rst
- user_guide_src/source/libraries/cookies.rst
- user_guide_src/source/libraries/encryption.rst
- user_guide_src/source/libraries/user_agent.rst
- user_guide_src/source/outgoing/response.rst
- user_guide_src/source/outgoing/table.rst
- user_guide_src/source/outgoing/view_parser.rst
- user_guide_src/source/outgoing/view_renderer.rst
Fix links to function or method.
**Checklist:**
> docs: fix links to function/method

- user_guide_src/source/database/metadata.rst
Description
Ref https://github.com/codeigniter4/CodeIgniter4/issues/6308
See https://github.com/codeigniter4/CodeIgniter4/issues/6308#issuecomment-1221330934
Checklist:
> docs: $db->getFieldData() data explanation is not complete

- system/Commands/Cache/ClearCache.php
- system/Commands/Help.php
- tests/system/CLI/CommandRunnerTest.php
- fix command usages
**Checklist:**
> fix: command usages

- user_guide_src/source/general/managing_apps.rst
fix typo in "General Topics » Managing your Applications"
**Checklist:**
> docs : fix typo in "General Topics » Managing your Applications"

- app/Config/Autoload.php
- system/Autoloader/Autoloader.php
- system/bootstrap.php
- tests/system/Autoloader/AutoloaderTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/general/helpers.rst
- user_guide_src/source/installation/upgrade_4xx.rst
- add functionality to autoload helpers
**Checklist:**
> feat: autoload helpers

- .php-cs-fixer.dist.php
- .php-cs-fixer.no-header.php
See https://github.com/codeigniter4/CodeIgniter4/pull/6252#issuecomment-1219308598
**Checklist:**
> Exclude non-monolithic files from CS

- env
- user_guide_src/source/testing/database.rst
- fix `.env` sample
**Checklist:**
> docs: small fix for test database

- tests/system/Database/Live/ForgeTest.php
- refactor tests for getFieldData()
Ref #6308
**Checklist:**
> test: refactor tests for getFieldData()

- user_guide_src/source/concepts/services.rst
- user_guide_src/source/concepts/services/015.php
- add explanation about a shared instance and parameters
**Checklist:**
> docs: improve services.rst

- system/Database/BaseConnection.php
- system/Database/Forge.php
- system/Database/MySQLi/Connection.php
- system/Database/MySQLi/Forge.php
- system/Database/OCI8/Connection.php
- system/Database/OCI8/Forge.php
- system/Database/Postgre/Connection.php
- system/Database/Postgre/Forge.php
- system/Database/SQLSRV/Connection.php
- system/Database/SQLSRV/Forge.php
- system/Database/SQLite3/Connection.php
- system/Database/SQLite3/Forge.php
- system/Test/Mock/MockConnection.php
> docs: replace mixed in Database doc comments

- user_guide_src/source/helpers/date_helper.rst
- user_guide_src/source/helpers/date_helper/002.php
- fix explanation of `now()`
**Checklist:**
> docs: update date helper

- composer.json
- contributing/pull_request.md
See https://github.com/codeigniter4/CodeIgniter4/pull/6437#discussion_r956712424
- update `composer analyze` command
- add command aliases
Reference https://github.com/codeigniter4/devkit/blob/1cdd2788a64c92e53a90060aedaa2e73f6cf1b3e/composer.json#L50
**Checklist:**
> chore: update composer scripts

- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/database/metadata.rst
- user_guide_src/source/dbmgmt/forge.rst
- user_guide_src/source/testing/benchmark.rst
- categorize Enhancements
- add links to pages
**Checklist:**
> docs: improve changelogs/v4.3.0.rst

- system/Cache/Handlers/RedisHandler.php
- tests/system/Cache/Handlers/RedisHandlerTest.php
> Fix redis cache increment/decrement methods

- tests/system/CodeIgniterTest.php
> Fix overlooked coding style violations

- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/dbmgmt/forge.rst
Follow-up #6488
**Checklist:**
> docs: add link from changelog to detail page

- system/Helpers/url_helper.php
Fixed: Typo in url helper comment
**Checklist:**
> Fixed: Typo

- system/Database/BaseBuilder.php
- system/Database/BaseConnection.php
- system/Database/BaseUtils.php
- system/Database/Config.php
- system/Database/Database.php
- tests/system/Database/Live/DbUtilsTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/installation/upgrade_430.rst
> fix: types in database classes

- system/CodeIgniter.php
- tests/system/ControllerTest.php
- tests/system/Entity/EntityTest.php
Ref #6534
- To fix psalm errors
**Checklist:**
> refactor: to fix psalm errors

- app/Common.php
fixed typo: "frameworks" to "framework's"
**Checklist:**
> fixed typo

- system/View/Table.php
- tests/system/View/TableTest.php
Fixed #6507
Supersedes #6511
**Checklist:**
> fix: table attribute cannot applied on td element

- user_guide_src/source/installation/troubleshooting.rst
> docs: add about "No input file specified"

- system/Common.php
- add interim variable for Config to jump to the Config class on IDE
- update doc comments
**Checklist:**
> refactor: small refactoring in view()

- contributing/pull_request.md
Update rector repository link.
**Checklist:**
> update rector link

- system/Router/RouteCollection.php
- tests/system/Router/RouteCollectionTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/incoming/routing/065.php
- user_guide_src/source/incoming/routing/066.php
Reverts codeigniter4/CodeIgniter4#6525
- We cannot see the diff, so the PR should be reverted once.
- The docs in the PR seems to be something wrong.
> Revert "Added view() method to route collections."

- tests/system/Helpers/URLHelper/SiteUrlTest.php
To confirm the current behavior.
Ref #6561
**Checklist:**
> test: add test cases in SiteUrlTest

- tests/system/View/TableTest.php
Implement table test for `preg_replace` attribute on body row.
**Checklist:**
> tests: increase coverage `TableTest`

- system/ThirdParty/Kint/Kint.php
https://github.com/kint-php/kint/releases/tag/4.2.2
**Checklist:**
> chore: update ThirdParty Kint to 4.2.2

- user_guide_src/source/libraries/validation.rst
"require_with" should be "required_with" with a "d".
**Checklist:**
> Fix spelling in validation.rst

- user_guide_src/source/outgoing/response.rst
- user_guide_src/source/outgoing/response/018.php
See https://github.com/codeigniter4/CodeIgniter4/pull/6537#discussion_r979519105
**Checklist:**
> Remove outgoing/response/018.php

- system/Validation/Rules.php
- system/Validation/Validation.php
- system/Validation/ValidationInterface.php
> docs: replace types in `Validation\Rule`, `Validation\Validation` and `Validation\ValidationInterface`

- tests/system/Pager/PagerTest.php
- remove duplicate statement
**Checklist:**
> test: remove duplicate statement in PagerTest

- user_guide_src/source/database/queries.rst
- user_guide_src/source/database/query_builder.rst
- add explanation
**Checklist:**
> docs: add SQL Injection Protection in QueryBuilder

- user_guide_src/source/outgoing/view_cells.rst
- add TOC
- fix section level
After:
**Checklist:**
> docs: small fixes in view_cells.rst

- tests/system/Helpers/FormHelperTest.php
Follow-up #6619
**Checklist:**
> test: remove uneeded code in FormHelperTest

- user_guide_src/source/incoming/routing.rst
HTTP verbs is an important topic.
**Checklist:**
> docs: add "HTTP verbs" section title

- user_guide_src/source/incoming/incomingrequest/021.php
- fix sample code and incorrect results
**Checklist:**
> docs: fix sample code in incomingrequest

- user_guide_src/source/helpers/form_helper.rst
- user_guide_src/source/helpers/form_helper/013.php
- user_guide_src/source/helpers/form_helper/014.php
- user_guide_src/source/helpers/form_helper/015.php
- user_guide_src/source/helpers/form_helper/016.php
- user_guide_src/source/helpers/form_helper/035.php
- add description about boolean attributes
- See https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes
- add generated HTML
- text decoration
Follow-up  #1548
**Checklist:**
> docs: improve form_helper.rst

- tests/system/Filters/FiltersTest.php
- tests/system/Filters/fixtures/GoogleMe.php
- tests/system/Filters/fixtures/GoogleYou.php
- tests/system/Filters/fixtures/Multiple1.php
- tests/system/Filters/fixtures/Multiple2.php
See #6170, #6172
**Checklist:**
> test: fix dynamic properties in FiltersTest

- tests/system/Database/Migrations/MigrationRunnerTest.php
See #6170, #6172
**Checklist:**
> test: remove dynamic properties in MigrationRunnerTest

- tests/_support/View/SampleClassWithInitController.php
- tests/system/Models/GeneralModelTest.php
- tests/system/Models/ValidationModelTest.php
- tests/system/View/CellTest.php
See https://github.com/codeigniter4/CodeIgniter4/issues/6170, https://github.com/codeigniter4/CodeIgniter4/pull/6172
**Checklist:**
> test: fix dynamic properties

- system/HTTP/CURLRequest.php
- tests/system/HTTP/CURLRequestTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/libraries/curlrequest.rst
Added option for version HTTP2 to CURLRequest.
**Checklist:**
> feat: implementation option http2 in `CURLRequest`

- .php-cs-fixer.no-header.php
- app/Config/Logger.php
- fix .php-cs-fixer.no-header.php
**Checklist:**
> style: fix php-cs-fixer.no-header.php

- .github/workflows/test-autoreview.yml
- .github/workflows/test-coding-standards.yml
- .github/workflows/test-deptrac.yml
- .github/workflows/test-phpstan.yml
- .github/workflows/test-phpunit.yml
- .github/workflows/test-rector.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
**Checklist:**
> Use environment variables instead of `set-output`

- system/Database/PreparedQueryInterface.php
- user_guide_src/source/changelogs/v4.3.0.rst
Follow-up to #6665 
**Checklist:**
> Match signature of `PreparedQueryInterface::close()` to `BasePreparedQuery::close()`

- system/Database/BaseBuilder.php
- tests/system/Database/Live/UpsertTest.php
Fixes https://github.com/codeigniter4/CodeIgniter4/issues/6687
Follow-up #6600
**Checklist:**
> Fix testMode() with upsert() and getCompiledUpsert()

- user_guide_src/source/general/ajax.rst
- add how to add X-Requested-With header with htmx
**Checklist:**
> docs: add how to add X-Requested-With header with htmx

- admin/framework/composer.json
- composer.json
- add extensions in suggest
**Checklist:**
> chore: add extensions in suggest in composer.json

- user_guide_src/source/incoming/request/005.php
- user_guide_src/source/incoming/request/007.php
Fix some typos in request class example (documentation).
**Checklist:**
> Fix some typos in request class example

- .github/workflows/test-phpunit.yml
> Use SQL Server 2022 in mssql image

- user_guide_src/source/testing/database.rst
put grabFromDatabase() code in the right place in doc
> docs: put grabFromDatabase() code in the right place in database.rst

- system/Database/OCI8/Connection.php
- system/Database/OCI8/PreparedQuery.php
- system/Database/OCI8/Result.php
The abstract class already implements the interface.
**Checklist:**
> Remove unneeded `implements`

- system/Database/BaseBuilder.php
- add PHPDoc comments
**Checklist:**
> docs: add PHPDoc to BaseBuilder

- system/Common.php
- system/Format/XMLFormatter.php
- system/Images/Handlers/ImageMagickHandler.php
- system/Test/DOMParser.php
- system/Test/FeatureTestCase.php
- system/Test/FeatureTestTrait.php
If the path of coverage covers only one line, then we can use `@codeCoverageIgnore` instead of the pair.
**Checklist:**
> Simplify `@codeCoverageIgnore*` tags

- .github/workflows/test-phpunit.yml
- tests/_support/Database/Seeds/CITestSeeder.php
In order to skip the 2 to 4 mins build time of Oracle Instant Client
**Checklist:**
> Streamline Oracle docker image

- tests/system/Commands/CreateDatabaseTest.php
- tests/system/Commands/Database/MigrateStatusTest.php
- tests/system/Commands/Database/ShowTableInfoTest.php
- tests/system/Commands/DatabaseCommandsTest.php
- tests/system/Commands/MigrationIntegrationTest.php
- tests/system/Database/Live/GetNumRowsTest.php
- tests/system/Database/Migrations/MigrationTest.php
- tests/system/Database/ModelFactoryTest.php
- tests/system/Models/AffectedRowsTest.php
- tests/system/Models/CountAllModelTest.php
- tests/system/Models/DeleteModelTest.php
- tests/system/Models/EventsModelTest.php
- tests/system/Models/FindModelTest.php
- tests/system/Models/InsertModelTest.php
- tests/system/Models/MiscellaneousModelTest.php
- tests/system/Models/PaginateModelTest.php
- tests/system/Models/ReplaceModelTest.php
- tests/system/Models/SaveModelTest.php
- tests/system/Models/UpdateModelTest.php
- tests/system/Models/ValidationModelTest.php
- tests/system/Session/Handlers/Database/MySQLiHandlerTest.php
- tests/system/Session/Handlers/Database/PostgreHandlerTest.php
- tests/system/Session/Handlers/Database/RedisHandlerTest.php
Add `@group DatabaseLive` to tests that needs database connection.
**Checklist:**
> test: add `@group DatabaseLive`

- user_guide_src/source/tutorial/news_section.rst
- user_guide_src/source/tutorial/news_section/002.php
- user_guide_src/source/tutorial/news_section/004.php
- user_guide_src/source/tutorial/news_section/006.php
From https://forum.codeigniter.com/showthread.php?tid=84627
**Checklist:**
> docs: improve tutorial news section

- admin/framework/.gitattributes
Restores previously deleted .gitattributes on #4205 by excluding the .github folder.
The .github folder should not be included
**Checklist:**
> Add .gitattributes to framework

- system/CodeIgniter.php
- system/Common.php
- system/Debug/Toolbar/Collectors/Config.php
- system/HTTP/CURLRequest.php
- system/HTTP/IncomingRequest.php
- system/HTTP/URI.php
- system/Helpers/cookie_helper.php
- system/Helpers/form_helper.php
- system/Helpers/url_helper.php
- system/Pager/PagerRenderer.php
- system/Test/FeatureTestCase.php
- system/Test/FeatureTestTrait.php
- tests/system/HTTP/URITest.php
- small refactoring
- replace `config(App::class)` with `config('App')` for consistency
**Checklist:**
> refactor: around URI

- system/Test/Fabricator.php
- tests/_support/Models/FabricatorModel.php
- tests/system/Test/FabricatorTest.php
Fixes #6764 
Related: #6773 
**Checklist:**
> Fix faker access deprecations

- tests/system/Autoloader/AutoloaderTest.php
Follow-up to #6788
**Checklist:**
> CS fix for AutoloaderTest

- phpunit.xml.dist
- system/Test/CIUnitTestCase.php
Reverts codeigniter4/CodeIgniter4#6761
> Revert Tachycardia Expeditable

- CHANGELOG.md
- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.2.9.rst
- add missing changelog
**Checklist:**
> docs: add v4.2.9 changelog

- system/Session/Session.php
See https://github.com/codeigniter4/shield/pull/492
**Checklist:**
> docs: fix PHPDoc types in Session

- .github/workflows/test-deptrac.yml
See https://github.com/codeigniter4/CodeIgniter4/actions/runs/3370667198/jobs/5591858773
**Checklist:**
> Fix deptrac requires ^8.1

- admin/framework/composer.json
- composer.json
- add ext-xdebug
**Checklist:**
> chore: add ext-xdebug to composer.json suggest

- user_guide_src/source/dbmgmt/forge.rst
- user_guide_src/source/dbmgmt/forge/013.php
- improve addForeignKey() explanation
**Checklist:**
> docs: improve addForeignKey() explanation

- app/Config/App.php
- tests/system/CommonFunctionsTest.php
- tests/system/Debug/TimerTest.php
- tests/system/I18n/TimeLegacyTest.php
- tests/system/I18n/TimeTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
To avoid being affected by Daylight Saving Time.
See https://github.com/codeigniter4/CodeIgniter4/issues/6818#issuecomment-1304753541 and #6823
**Checklist:**
> config: change default timezone to UTC

- admin/framework/composer.json
- admin/starter/composer.json
- admin/userguide/composer.json
- composer.json
Use https on support link in composer.json
**Checklist:**
> use `https` on support link in `composer.json`

- .php-cs-fixer.dist.php
- .php-cs-fixer.no-header.php
- .php-cs-fixer.user-guide.php
> chore: Remove previous CS overrides

- contributing/signing.md
> docs: fix github links for `GPG` key

- tests/system/Commands/FilterCheckTest.php
- tests/system/Commands/GenerateKeyTest.php
- tests/system/Commands/Utilities/NamespacesTest.php
- tests/system/Database/Builder/WhenTest.php
- tests/system/HTTP/OutgoingRequestTest.php
- tests/system/I18n/TimeLegacyTest.php
- tests/system/Publisher/ContentReplacerTest.php
- tests/system/Publisher/PublisherContentReplaceTest.php
- tests/system/Test/TestLoggerTest.php
- tests/system/View/ControlledCellTest.php
> fix: 4.3 failed tests

- .github/workflows/test-phpstan.yml
- admin/pre-commit
- composer.json
See below image
**Checklist:**
> fix: turn off `Xdebug` note when running phpstan

- tests/system/Database/Live/SQLite/AlterTableTest.php
- Run tests only in SQLite3
- Use in-memory database so that stray database file is not left
**Checklist:**
> Refactor AlterTableTest

- tests/README.md
> Update README for tests

- tests/system/Commands/Database/MigrateStatusTest.php
> Fix MigrateStatusTest for Windows

- psalm-baseline.xml
- psalm.xml
- psalm_autoload.php
- system/Log/Logger.php
See #6534
- add baseline
**Checklist:**
> chore: psalm config

- system/Commands/Generators/CellGenerator.php
- system/Language/en/CLI.php
- system/View/Cells/Cell.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/cli/cli_generators.rst
- user_guide_src/source/outgoing/view_cells.rst
Follow-up: #6620, #6864
**Checklist:**
> fix: View Cells

- user_guide_src/source/changelogs/v4.3.0.rst
- improve readablity
**Checklist:**
> docs: improve changelogs v4.3.0

- system/Database/BaseBuilder.php
> docs: add PHPDoc param in BaseBuilder

- .github/workflows/test-psalm.yml
- README.md
- psalm.xml
See #6534
- add test-psalm.yml
**Checklist:**
> chore: add test-psalm.yml

- user_guide_src/source/installation/upgrade_430.rst
- improve readability
**Checklist:**
> docs: improve upgrade_430.rst

- app/Config/App.php
- app/Config/Autoload.php
- app/Config/Logger.php
update app/Config/ code replace tabs to spaces 
**Checklist:**
> fix: replace tabs to spaces 

- user_guide_src/source/database/queries.rst
Simple typo fix.
**Checklist:**
> Fix typo in database/queries.rst

- user_guide_src/source/general/helpers.rst
- user_guide_src/source/incoming/controllers.rst
- add about `$helpers` in Controller
**Checklist:**
> docs: improve helpers

- user_guide_src/source/changelogs/v4.2.0.rst
- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/incoming/controllers/006.php
- user_guide_src/source/incoming/incomingrequest.rst
- user_guide_src/source/libraries/validation.rst
- add warning to $this->validate()
- add note for Validation::withRequest()
**Checklist:**
> docs: improve controller validate()

- user_guide_src/source/database/configuration.rst
- user_guide_src/source/intro/requirements.rst
- user_guide_src/source/tutorial/news_section.rst
> docs: add references to supported databases

- user_guide_src/source/database/query_builder/103.php
- user_guide_src/source/database/query_builder/104.php
> docs: fix query_builder sample code

- deptrac.yaml
- phpstan-baseline.neon.dist
- system/Cache/Handlers/FileHandler.php
- system/Database/MigrationRunner.php
- system/Test/Fabricator.php
- system/Test/Mock/MockCache.php
- system/Test/Mock/MockSession.php
- system/Test/TestResponse.php
> refactor: replace `time()` with Time into `Cache`, `Database` and `Test` class.

- user_guide_src/source/changelogs/v4.2.0.rst
Follow-up #6050
**Checklist:**
> docs: add SQLite3 $foreignKeys to changelog v4.2.0

- user_guide_src/source/cli/cli_generators.rst
> docs: small fixes in cli_generators.rst

- user_guide_src/source/cli/cli_controllers.rst
- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/incoming/filters.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/installation/upgrade_415.rst
- user_guide_src/source/installation/upgrade_4xx.rst
- user_guide_src/source/installation/upgrade_routing.rst
- user_guide_src/source/libraries/security.rst
- user_guide_src/source/libraries/throttler.rst
- user_guide_src/source/tutorial/create_news_items.rst
- update `:ref:` names
- update "auto-routing" with "Auto Routing (Legacy)"
**Checklist:**
> docs: update auto routing notes

- user_guide_src/source/models/model.rst
- fix: merge mistake
**Checklist:**
> [4.3] fix: merge mistake model.rst

- system/Session/Handlers/RedisHandler.php
- user_guide_src/source/changelogs/v4.2.11.rst
> fix: socket connection in RedisHandler class

- user_guide_src/source/concepts/factories.rst
- user_guide_src/source/general/helpers.rst
- user_guide_src/source/general/modules.rst
- user_guide_src/source/general/modules/006.php
- fix incorrect sample code
- add related topics
**Checklist:**
> docs: fix modules.rst

- system/HTTP/IncomingRequest.php
Fixes #6246
- add the conditions not to get the body from `php://input`
**Checklist:**
> fix: large HTTP input crashes framework

- user_guide_src/source/libraries/uploaded_files.rst
- user_guide_src/source/libraries/uploaded_files/002.php
- refactor sample code
**Checklist:**
> docs: improve uploaded_files.rst

- system/RESTful/ResourceController.php
PHPDOC `$id` without space in `ResourceController::update($id = null)` and added phpdoc `$format` in `ResourceController::setFormat(string $format = 'json')`
**Checklist:**
> docs: fix PHPDOC ResourceController

- user_guide_src/source/changelogs/v4.2.0.rst
- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/incoming/routing.rst
> docs: add note for Auto Routing (Improved) changes

- CHANGELOG.md
> docs: add SECURITY in CHANGELOG.md

- app/Config/Session.php
- system/Config/Services.php
Follow-up #6989
- use Config\Session in `Services::session()`
- fix class-string class
**Checklist:**
> fix: Config\Session

- user_guide_src/source/incoming/incomingrequest.rst
- fix incorrect method name
**Checklist:**
> docs: fix incomingrequest.rst

- user_guide_src/source/database/query_builder.rst
- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/helpers/form_helper.rst
- user_guide_src/source/libraries/cookies.rst
- add deprecated directives
- change versionadded positions
**Checklist:**
> docs: add deprecated directives

- user_guide_src/source/libraries/uploaded_files.rst
- user_guide_src/source/libraries/uploaded_files/002.php
Fixes #7008 
Following the PR #6983 to fix this document typo.
**Checklist:**
> docs: improve uploaded_files.rst into develop branch.

- user_guide_src/source/installation/upgrade_404.rst
- user_guide_src/source/installation/upgrade_405.rst
- user_guide_src/source/installation/upgrade_410.rst
- user_guide_src/source/installation/upgrade_412.rst
- user_guide_src/source/installation/upgrade_413.rst
- user_guide_src/source/installation/upgrade_414.rst
- user_guide_src/source/installation/upgrade_415.rst
- user_guide_src/source/installation/upgrade_416.rst
- user_guide_src/source/installation/upgrade_418.rst
- add section titles or so
**Checklist:**
> docs: improve past upgrade

- system/Debug/Toolbar/Views/toolbar.css
See https://github.com/codeigniter4/CodeIgniter4/pull/7018#issuecomment-1364613376
```
$ sass --no-source-map admin/css/debug-toolbar/toolbar.scss system/Debug/Toolbar/Views/toolbar.css
```
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/css.md
**Checklist:**
> refactor: update sass output

- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/installation/upgrade_4xx.rst
- user_guide_src/source/installation/upgrade_controllers.rst
- user_guide_src/source/installation/upgrade_controllers/ci3sample/001.php
- user_guide_src/source/installation/upgrade_models.rst
- user_guide_src/source/installation/upgrade_views.rst
- user_guide_src/source/installation/upgrade_views/ci3sample/001.php
- user_guide_src/source/outgoing/response.rst
- add links to other pages
**Checklist:**
> docs: update Upgrading from 3.x to 4.x and MVC

- user_guide_src/source/installation/upgrade_configuration.rst
- user_guide_src/source/installation/upgrade_configuration/001.php
- user_guide_src/source/installation/upgrade_database.rst
- user_guide_src/source/installation/upgrade_file_upload/001.php
- user_guide_src/source/installation/upgrade_responses.rst
- user_guide_src/source/installation/upgrade_security.rst
- user_guide_src/source/installation/upgrade_security/001.php
- user_guide_src/source/installation/upgrade_sessions/001.php
- user_guide_src/source/installation/upgrade_validations.rst
- user_guide_src/source/installation/upgrade_validations/002.php
- user_guide_src/source/libraries/validation.rst
- add links to other pages
**Checklist:**
> docs: update Upgrading from 3.x to 4.x Libraries

- user_guide_src/source/incoming/request.rst
- user_guide_src/source/incoming/request/003.php
- fix incorrect descriptions
- add a missing method
- some improvements
Ref, https://github.com/codeigniter4/CodeIgniter4/commit/7162fa72
**Checklist:**
> docs: fix request.rst

- system/HTTP/RequestTrait.php
- user_guide_src/source/incoming/request.rst
> fix: Request::getIPaddress() causes error on CLI

- rector.php
`RemoveUselessReturnTagRector` already cover `@return true`
**Checklist:**
> [Rector] Enable skipped RemoveUselessReturnTagRector

- app/Config/Migrations.php
See https://forum.codeigniter.com/showthread.php?tid=85981
**Checklist:**
> docs: fix comment for Migrations Timestamp Format

- .github/ISSUE_TEMPLATE/bug_report.yml
- add 8.2 and remove 7.3
**Checklist:**
> chore: update PHP versions in bug_report.yml

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.2.12.rst
- user_guide_src/source/installation/upgrade_4212.rst
- user_guide_src/source/installation/upgrade_423.rst
- user_guide_src/source/installation/upgrading.rst
- add docs for 4.2.12
**Checklist:**
> docs: add changelog 4.2.12

- user_guide_src/source/incoming/controllers/007.php
Typo: Changed the controller name "Products" to "Helloworld" as described in explanation.
**Checklist:**
> Typo: Products to Helloworld

- LICENSE
- user_guide_src/source/conf.py
- user_guide_src/source/license.rst
> New Year 2023

- user_guide_src/source/general/urls.rst
- user_guide_src/source/installation/troubleshooting.rst
> docs: improve troubleshooting.rst

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.2.12.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_4212.rst
Updates changelog and version references for 4.2.12.
Ref #7001
**Checklist:**
> Prep for 4.2.12 release

- admin/RELEASE.md
- update RELEASE.md
**Checklist:**
> docs: update RELEASE.md for minor version release

- user_guide_src/source/installation/upgrade_430.rst
- add about "Call to undefined method ComposerInstalledVersions::getAllRawData()"
See
- https://forum.codeigniter.com/showthread.php?tid=86096&pid=405146#pid405146
- https://forum.codeigniter.com/showthread.php?tid=86096&pid=405169#pid405169
**Checklist:**
> docs: add about Composer error in upgrade_430.rst

- user_guide_src/source/libraries/sessions.rst
- user_guide_src/source/libraries/sessions/039.php
- user_guide_src/source/libraries/sessions/041.php
- user_guide_src/source/libraries/sessions/042.php
Improvements and a small fix.
**Checklist:**
> docs: fix sessions.rst

- user_guide_src/source/concepts/http.rst
- user_guide_src/source/concepts/http/001.php
- user_guide_src/source/concepts/http/002.php
> docs: update http.rst

- user_guide_src/source/changelogs/v4.0.5.rst
- improvements and small fixes
**Checklist:**
> docs: fix changelogs v4.0.5

- admin/framework/.github/workflows/close-pull-request.yml
- admin/starter/.github/workflows/close-pull-request.yml
- admin/userguide/.github/workflows/close-pull-request.yml
cont: #7146 
Sorry, previous the backticks not work.
https://github.com/totoprayogo1916/github-playground/pull/3
https://github.com/totoprayogo1916/github-playground/pull/6
**Checklist:**
> add tag `code` in close-pull-request.yml

- system/Validation/Validation.php
- tests/system/Validation/ValidationTest.php
> fix: ordering `Validation` show error by call `setRule()`

- system/Database/Database.php
- user_guide_src/source/database/configuration.rst
- add explanation for DBDriver
**Checklist:**
> docs: improve database/configuration.rst

- user_guide_src/source/changelogs/v4.0.3.rst
- user_guide_src/source/changelogs/v4.0.4.rst
- user_guide_src/source/changelogs/v4.0.5.rst
- user_guide_src/source/changelogs/v4.1.0.rst
- user_guide_src/source/changelogs/v4.1.1.rst
- user_guide_src/source/changelogs/v4.1.2.rst
- user_guide_src/source/changelogs/v4.1.3.rst
- user_guide_src/source/changelogs/v4.1.4.rst
- user_guide_src/source/changelogs/v4.1.5.rst
- user_guide_src/source/changelogs/v4.1.6.rst
- user_guide_src/source/changelogs/v4.1.7.rst
- update for consistency
- add/update links to repo's CHANGELOG
**Checklist:**
> docs: improve changelogs 4.0.x and 4.1.x

- user_guide_src/source/database/query_builder.rst
- user_guide_src/source/dbmgmt/forge.rst
- user_guide_src/source/general/errors.rst
- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/incoming/incomingrequest.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/libraries/encryption.rst
- add `versionadded`
Ref #5128
**Checklist:**
> docs: add versionadded

- system/View/Filters.php
- tests/system/View/ParserFilterTest.php
- user_guide_src/source/outgoing/view_parser.rst
> fix: [Parser] local_currency causes "Passing null to parameter"

- user_guide_src/source/database/queries.rst
- user_guide_src/source/database/queries/011.php
> docs: improve database/queries.rst

- system/HTTP/URI.php
> refactor: URI::parseStr()

- user_guide_src/source/outgoing/views.rst
- user_guide_src/source/outgoing/views/002.php
- user_guide_src/source/outgoing/views/009.php
- user_guide_src/source/outgoing/views/011.php
- user_guide_src/source/outgoing/views/012.php
- user_guide_src/source/outgoing/views/013.php
- update the content
**Checklist:**
> docs: update views.rst

- user_guide_src/source/installation/index.rst
- user_guide_src/source/installation/installing_composer.rst
- add note about deployment and `--no-dev`
See https://forum.codeigniter.com/showthread.php?tid=84728&pid=405756#pid405756
After:
**Checklist:**
> docs: improve installing_composer.rst

- app/Views/errors/html/error_exception.php
See https://github.com/codeigniter4/CodeIgniter4/pull/7169/files#r1084270854
- remove unneeded code
**Checklist:**
> refactor: error_exception.php

- phpdoc.dist.xml
- update version number
**Checklist:**
> chore: update version in API docs

- changelogs/CHANGELOG_4.2.md
> docs: fix link in changelogs/CHANGELOG_4.2.md

- system/Router/RouteCollection.php
- system/Router/RouteCollectionInterface.php
- system/Router/Router.php
Minor fixes in some phpdocs: typos and grammatical errors.
**Checklist:**
> docs: fix typos and grammatical errors

- system/Session/Handlers/RedisHandler.php
- tests/system/Session/Handlers/Database/RedisHandlerTest.php
- user_guide_src/source/changelogs/v4.3.2.rst
- user_guide_src/source/libraries/sessions.rst
Fixed #7178
Ref https://3v4l.org/kM3JD
**Checklist:**
> fix: [Session] `Redis` connect to protocol `TLS`

- user_guide_src/source/installation/upgrade_4xx.rst
- user_guide_src/source/installation/upgrade_controllers.rst
- user_guide_src/source/installation/upgrade_migrations.rst
- user_guide_src/source/installation/upgrade_views.rst
See https://forum.codeigniter.com/showthread.php?tid=86275
- add about `defined('BASEPATH') OR exit('No direct script access allowed')`
**Checklist:**
> docs: improve Upgrading from 3.x to 4.x

- user_guide_src/source/incoming/controllers.rst
- add missing things
**Checklist:**
> docs: improve "Auto Routing (Improved)" in controllers.rst

- user_guide_src/source/changelogs/v4.3.2.rst
> docs: add Bugs Fixed items in changelogs/v4.3.2

- user_guide_src/source/helpers/url_helper.rst
- improve text decoration
- add more explanation for `url_is()`
**Checklist:**
> docs: improve url_helper.rst

- user_guide_src/source/installation/installing_composer.rst
- user_guide_src/source/installation/installing_manual.rst
- improvements
- fix typos
**Checklist:**
> docs: improve installation

- user_guide_src/source/concepts/factories.rst
- user_guide_src/source/concepts/factories/003.php
- user_guide_src/source/concepts/factories/004.php
- user_guide_src/source/concepts/factories/007.php
- user_guide_src/source/concepts/factories/010.php
- user_guide_src/source/concepts/factories/011.php
- user_guide_src/source/concepts/factories/012.php
- add another example
**Checklist:**
> docs: improve factories.rst

- system/Common.php
- system/HTTP/RedirectResponse.php
- system/Router/RouteCollection.php
- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/general/common_functions/005.php
- user_guide_src/source/general/common_functions/006.php
- user_guide_src/source/general/common_functions/013.php
- user_guide_src/source/general/common_functions/014.php
- user_guide_src/source/installation/upgrade_4xx.rst
See https://forum.codeigniter.com/showthread.php?tid=85226&pid=406230#pid406230
**Checklist:**
> docs: improve `redirect()` explanation

- user_guide_src/source/concepts/factories.rst
- user_guide_src/source/concepts/factories/013.php
- add "Loading a Class in Sub-directories"
See https://github.com/codeigniter4/CodeIgniter4/pull/7182#issuecomment-1407363029
**Checklist:**
> docs: add "Loading a Class in Sub-directories" in factories.rst

- user_guide_src/source/installation/upgrade_4xx.rst
- add about Factories
**Checklist:**
> docs: add about Factories in upgrade_4xx

- admin/framework/composer.json
- composer.json
- system/ThirdParty/Kint/Utils.php
https://github.com/kint-php/kint/releases/tag/5.0.3
**Checklist:**
> chore: update Kint to 5.0.3

- user_guide_src/source/installation/index.rst
- add explanation
**Checklist:**
> docs: add how to download previous version user guide

- contributing/signing.md
- add section "GPG-Signing Old Commits"
**Checklist:**
> docs: improve contributing/signing.md

- user_guide_src/source/libraries/uri.rst
- user_guide_src/source/libraries/uri/016.php
- fix incorrect sample output
- add sub section titles
- change text decoration
**Checklist:**
> docs: fix uri.rst

- system/Common.php
See #7224
- make the PHPDoc type more accurate
**Checklist:**
> docs: improve PHPDoc for model()

- user_guide_src/source/incoming/filters.rst
- improve explanation
**Checklist:**
> docs: improve before filters explanation

- admin/RELEASE.md
- break long lines
**Checklist:**
> docs: small update release.md

- user_guide_src/source/incoming/content_negotiation.rst
- user_guide_src/source/incoming/message.rst
- remove incorrect description in message.rst. See https://github.com/codeigniter4/CodeIgniter4/commit/c983a65a
**Checklist:**
> docs: fix message.rst and improve content_negotiation.rst

- app/Config/Encryption.php
- tests/system/Encryption/EncryptionTest.php
- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.3.3.rst
- user_guide_src/source/installation/upgrade_433.rst
- user_guide_src/source/installation/upgrading.rst
- user_guide_src/source/libraries/encryption.rst
- user_guide_src/source/libraries/encryption/010.php
- user_guide_src/source/libraries/encryption/013.php
From https://forum.codeigniter.com/showthread.php?tid=86796
**Checklist:**
> fix: Encryption CI3 compatibility

- user_guide_src/source/concepts/autoloader.rst
- user_guide_src/source/installation/running.rst
- user_guide_src/source/installation/troubleshooting.rst
- user_guide_src/source/tutorial/static_pages.rst
- add note for case-sensitive file systems
**Checklist:**
> docs: add note for case-sensitive file systems

- user_guide_src/source/incoming/filters.rst
- fix conflict in https://github.com/codeigniter4/CodeIgniter4/commit/29068a90#diff-64841ee8af09e2c0cdef686758378d7894b48c82770ef6c18e7c145ad9a4ab19
**Checklist:**
> docs: fix merge mistake in filters.rst

- tests/system/HTTP/URITest.php
> test: add tests in URITest

- system/HTTP/DownloadResponse.php
- system/HTTP/ResponseTrait.php
- tests/system/HTTP/CURLRequestDoNotShareOptionsTest.php
- tests/system/HTTP/CURLRequestTest.php
- user_guide_src/source/concepts/http/002.php
- consistent header name case
**Checklist:**
> refactor: consistent header name case

- user_guide_src/source/incoming/request.rst
> docs: small improvements in request.rst

- system/Cache/Handlers/RedisHandler.php
- tests/system/Cache/Handlers/AbstractHandlerTest.php
- tests/system/Cache/Handlers/RedisHandlerTest.php
> fix: incorrect metadata querying of Redis cache

- system/Email/Email.php
- user_guide_src/source/changelogs/v4.3.3.rst
> fix: [Email] add missing TLS 1.3 support

- user_guide_src/source/outgoing/response.rst
See https://forum.codeigniter.com/showthread.php?tid=86907
- add note for CSP and Debug Toolbar
**Checklist:**
> docs: add note for CSP and Debug Toolbar

- system/HTTP/RequestTrait.php
Same with PR:
- https://github.com/codeigniter4/CodeIgniter4/pull/7322
This PR fix `@param null` on RequestTrait.
**Checklist:**
> Fix @param null on RequestTrait

- user_guide_src/source/helpers/text_helper.rst
> docs: add warning to random_string()

- user_guide_src/source/dbmgmt/forge.rst
> docs: add note for addColumn() and NULL

- system/ThirdParty/Kint/Zval/Representation/SplFileInfoRepresentation.php
https://github.com/kint-php/kint/releases/tag/5.0.5
Ref #7318
**Checklist:**
> chore: update Kint to 5.0.5

- app/Common.php
> docs: add UG common link for more info

- user_guide_src/source/dbmgmt/migration.rst
- user_guide_src/source/general/modules.rst
- add sample command for Windows
**Checklist:**
> docs: add sample command with namespace for Windows

- tests/system/I18n/TimeLegacyTest.php
- tests/system/I18n/TimeTest.php
Temporary solution for PHP 8.2.4 SIGSEGV #7362
**Checklist:**
> test: Temporary solution for PHP 8.2.4 SIGSEGV

- user_guide_src/source/database/index.rst
- user_guide_src/source/database/results.rst
- add sub sections in `getResult()`
**Checklist:**
> docs: improve getResult() in database/results.rst

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.3.4.rst
- user_guide_src/source/installation/upgrade_433.rst
- user_guide_src/source/installation/upgrade_434.rst
- user_guide_src/source/installation/upgrading.rst
- add new changelog and upgrade for v4.3.4
- remove uneeded section titles in upgrade_433.rst. Follow-up #7382
**Checklist:**
> docs: add new changelog and upgrade for v4.3.4

- admin/RELEASE.md
- change the step to create a new changelog
- add a few instructions
- improve Markdown format
**Checklist:**
> docs: update admin/RELEASE.md

- system/HTTP/Exceptions/HTTPException.php
- system/HTTP/MessageTrait.php
- system/Language/en/HTTP.php
- user_guide_src/source/changelogs/v4.4.0.rst
See https://forum.codeigniter.com/showthread.php?tid=81584&pid=408038#pid408038
- Valid versions are obvious, so not needed.
**Checklist:**
> refactor: improve error message for HTTP.invalidHTTPProtocol

- user_guide_src/source/tutorial/static_pages.rst
> docs: fix the copyright year and integrity with the image

- user_guide_src/source/libraries/email.rst
- improve structure
**Checklist:**
> docs: improve email.rst

- app/Config/App.php
Add find the complete list of timezones supported by PHP.
**Checklist:**
> docs: add link list of timezones php.net

- .github/workflows/reusable-phpunit-test.yml
- .github/workflows/test-phpunit.yml
> fix imagemagick tests

- system/HTTP/RequestTrait.php
See https://github.com/codeigniter4/CodeIgniter4/pull/7355#discussion_r1155268275
**Checklist:**
> docs: fix @return type of fetchGlobal()

- user_guide_src/source/general/configuration.rst
- user_guide_src/source/general/environments.rst
- add sections
Before:
After:
**Checklist:**
> docs: improve environments

- contributing/documentation.rst
- update content
- fix RST
**Checklist:**
> docs: update documentation.rst

- user_guide_src/source/libraries/security.rst
Follow-up #6406
See https://forum.codeigniter.com/showthread.php?tid=87278&pid=408389#pid408389
**Checklist:**
> docs: add note for CSRF redirect

- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/libraries/validation/024.php
- user_guide_src/source/libraries/validation/025.php
- user_guide_src/source/libraries/validation/036.php
- user_guide_src/source/libraries/validation/041.php
- user_guide_src/source/libraries/validation/043.php
- fix incorrect ref label positions
- add sections and reorganize the page
- change coding style: reduce indentation
**Checklist:**
> docs: fix validation.rst

- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/incoming/controllers/004.php
- user_guide_src/source/incoming/controllers/005.php
- user_guide_src/source/installation/upgrade_440.rst
- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/libraries/validation/001.php
- user_guide_src/source/libraries/validation/008.php
- user_guide_src/source/libraries/validation/043.php
- user_guide_src/source/libraries/validation/044.php
- user_guide_src/source/libraries/validation/045.php
Follow-up #7420
**Checklist:**
> docs: update the description associated with $this->validate()

- public/index.php
> docs: fix PhpStorm spelling errors

- system/Session/Handlers/BaseHandler.php
- system/Session/Handlers/Database/PostgreHandler.php
- system/Session/Handlers/DatabaseHandler.php
- system/Session/SessionInterface.php
> docs: replace type `mixed` at remaining Session class.

- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/general/urls.rst
The term "route" is ambiguous. It may mean an entry of the route collection.
- change "Route" to "Route path" 
- add description
**Checklist:**
> docs: define new term "Route path"

- system/I18n/TimeDifference.php
> docs: replace type `mixed` at I18n class.

- user_guide_src/source/general/common_functions.rst
See https://forum.codeigniter.com/showthread.php?tid=87427.
**Checklist:**
> docs: Add the notice to `redirect()->to()` function in user guide.

- system/Format/JSONFormatter.php
- system/Format/XMLFormatter.php
> docs: fix PHPDoc types in `Format` class.

- user_guide_src/source/outgoing/view_cells.rst
See https://github.com/codeigniter4/CodeIgniter4/issues/7459#issuecomment-1525245729
**Checklist:**
> docs: improve View Cells Computed Properties sample

- admin/RELEASE.md
- admin/next-upgrading-guide.rst
- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.3.5.rst
- user_guide_src/source/installation/upgrade_434.rst
- user_guide_src/source/installation/upgrade_435.rst
- user_guide_src/source/installation/upgrading.rst
> docs: add changelog for v4.3.5

- .github/workflows/test-phpunit.yml
PHP 8.2 is now stable.
**Checklist:**
> Remove composer compatibility option for PHP 8.2

- user_guide_src/source/general/configuration.rst
- user_guide_src/source/installation/running.rst
> docs: improve dotenv file explanation

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.3.5.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_435.rst
~~Needs #7511~~
Updates changelog and version references for 4.3.5.
Ref #7456
**Checklist:**
> Prep for 4.3.5 release

- .php-cs-fixer.dist.php
- system/Exceptions/FrameworkException.php
- update `.php-cs-fixer.dist.php`
**Checklist:**
> style: fix coding style for v3.17.0

- user_guide_src/source/cli/cli_commands.rst
- user_guide_src/source/cli/cli_commands/002.php
- user_guide_src/source/cli/cli_commands/007.php
- user_guide_src/source/cli/cli_controllers.rst
- add setPad() method
**Checklist:**
> docs: update CLI

- system/View/View.php
- break long lines for better readability
- add/remove variables
**Checklist:**
> refactor: View

- user_guide_src/source/database/configuration.rst
- user_guide_src/source/database/configuration/001.php
- user_guide_src/source/database/configuration/002.php
- user_guide_src/source/database/configuration/003.php
- user_guide_src/source/database/configuration/005.php
- user_guide_src/source/database/configuration/006.php
- user_guide_src/source/database/configuration/007.php
- user_guide_src/source/database/configuration/010.php
- fix incorrect description
- add/fix section titles
- text decoration
**Checklist:**
> docs: fix database/configuration.rst

- system/Database/Config.php
- system/Database/Database.php
- do not reassign
- improve doc comments
**Checklist:**
> refactor: Database::initDriver()

- system/Config/Factories.php
It seems the PHPStan error is now gone.
Follows #5358 
**Checklist:**
> refactor: remove Factories::models()

- user_guide_src/source/incoming/routing.rst
See #7546 
https://forum.codeigniter.com/showthread.php?tid=87864
https://forum.codeigniter.com/showthread.php?tid=87549
**Checklist:**
> docs: improve Array Callable Syntax explanation in routing.rst

- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/libraries/validation/038.php
- improve description for `if_exist`, `required_with`, and `required_without`
- text decoration
- fix incorrect *Parameter* values
- add explanation to `valid_url`
- add explanation to `valid_date`. See  #7561
**Checklist:**
> docs: improve libraries/validation.rst

- system/Validation/Rules.php
- system/Validation/StrictRules/Rules.php
- system/Validation/Validation.php
- tests/system/Validation/RulesTest.php
Supersedes #7562
- add tests
- extract methods
**Checklist:**
> refactor: Validation::processRules()

- system/Router/AutoRouterImproved.php
- tests/system/Router/AutoRouterImprovedTest.php
4.4 is broken now. See https://github.com/codeigniter4/CodeIgniter4/commit/eac3edac305c82b8688ba80b07b9e3ae48d817c3
- fix merge conflicts by #7543
**Checklist:**
> fix: [4.4] AutoRouterImproved merge conflicts

- system/Encryption/Encryption.php
- system/Encryption/Handlers/BaseHandler.php
> docs: replace mixed type at `Encryption` class.

- system/Config/BaseConfig.php
> docs: replace mixed type at `Config` class.

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.3.6.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_436.rst
Updates changelog and version references for 4.3.6
Ref #7510
**Checklist:**
> Prep for 4.3.6 release

- system/Encryption/Handlers/BaseHandler.php
- remove unused property
**Checklist:**
> refactor: remove unused property in Encryption\Handlers\BaseHandler

- user_guide_src/source/cli/cli_library/001.php
- Spark command is recommended.
**Checklist:**
> docs: update sample code in cli_library

- user_guide_src/source/helpers/inflector_helper.rst
- fix sample code. See https://codeigniter4.github.io/CodeIgniter4/helpers/inflector_helper.html#decamelize
**Checklist:**
> docs: fix incorrect sample code in inflector_helper.rst

- user_guide_src/source/changelogs/v4.1.1.rst
- user_guide_src/source/installation/upgrade_4210.rst
- user_guide_src/source/installation/upgrade_4211.rst
- user_guide_src/source/installation/upgrade_4212.rst
- user_guide_src/source/installation/upgrade_423.rst
- user_guide_src/source/installation/upgrade_425.rst
- user_guide_src/source/installation/upgrade_427.rst
For consistency.
**Checklist:**
> docs: change version number notation

- admin/RELEASE.md
> docs: small updates in RELEASE.md

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.3.7.rst
- user_guide_src/source/installation/upgrade_437.rst
- user_guide_src/source/installation/upgrading.rst
- add changelog/upgrade guide
**Checklist:**
> docs: add changelog/upgrade guide for v4.3.7

- user_guide_src/source/libraries/sessions.rst
- user_guide_src/source/libraries/sessions/040.php
Related: #7585
- add sub section titles
- update desciption
**Checklist:**
> docs: improve "Configure DatabaseHandler" for Session

- user_guide_src/source/incoming/message.rst
- fix descriptions
**Checklist:**
> docs: fix message.rst

- user_guide_src/source/concepts/security.rst
- user_guide_src/source/concepts/structure.rst
- user_guide_src/source/database/configuration.rst
- user_guide_src/source/incoming/filters.rst
- user_guide_src/source/incoming/incomingrequest.rst
- user_guide_src/source/libraries/sessions.rst
- add links
- add items
- remove a item that dose not make sense
**Checklist:**
> docs: improve concepts/security.rst

- system/Config/Services.php
- system/HotReloader/DirectoryHasher.php
- system/HotReloader/IteratorFilter.php
- system/Security/Security.php
> [4.4] refactor: use ::class to config() param

- system/ThirdParty/Kint/Parser/Parser.php
https://github.com/kint-php/kint/releases/tag/5.0.7
**Checklist:**
> chore: update Kint to 5.0.7

- user_guide_src/source/changelogs/v4.4.0.rst
> docs: fix changelogs v4.4.0 RST format

- user_guide_src/source/general/errors.rst
Follow-up  #7545
**Checklist:**
> docs: add note for RedirectException namespace

- app/Config/App.php
> docs: fix comment header for $forceGlobalSecureRequests

- phpstan-baseline.neon.dist
- system/Helpers/array_helper.php
- system/Helpers/cookie_helper.php
- system/Helpers/filesystem_helper.php
- system/Helpers/number_helper.php
- system/Helpers/text_helper.php
> docs: Replace type `mixed` in all helper files.

- system/CLI/CLI.php
- system/Database/OCI8/Connection.php
- system/Filters/FilterInterface.php
- system/HTTP/CLIRequest.php
- system/HTTP/CURLRequest.php
- system/HTTP/Files/FileCollection.php
- system/HTTP/MessageInterface.php
- system/HTTP/MessageTrait.php
- system/HTTP/ResponseTrait.php
- system/HTTP/URI.php
- system/HTTP/UserAgent.php
- system/Model.php
- system/Router/RouteCollection.php
- system/Validation/Validation.php
- fix doc comment types
- fix typo
See #6310
**Checklist:**
> docs: fix doc comments

- user_guide_src/source/outgoing/view_cells.rst
- user_guide_src/source/outgoing/view_cells/001.php
- user_guide_src/source/outgoing/view_cells/002.php
- user_guide_src/source/outgoing/view_cells/003.php
- user_guide_src/source/outgoing/view_cells/004.php
- user_guide_src/source/outgoing/view_cells/005.php
- user_guide_src/source/outgoing/view_cells/006.php
- user_guide_src/source/outgoing/view_cells/007.php
- user_guide_src/source/outgoing/view_cells/008.php
- user_guide_src/source/outgoing/view_cells/009.php
- user_guide_src/source/outgoing/view_cells/010.php
- user_guide_src/source/outgoing/view_cells/011.php
- user_guide_src/source/outgoing/view_cells/012.php
- user_guide_src/source/outgoing/view_cells/013.php
- user_guide_src/source/outgoing/view_cells/014.php
- user_guide_src/source/outgoing/view_cells/015.php
- user_guide_src/source/outgoing/view_cells/016.php
- user_guide_src/source/outgoing/view_cells/017.php
- user_guide_src/source/outgoing/view_cells/018.php
- user_guide_src/source/outgoing/view_cells/019.php
- user_guide_src/source/outgoing/view_cells/020.php
- user_guide_src/source/outgoing/view_cells/021.php
- user_guide_src/source/outgoing/view_cells/022.php
- extract source code
- small fixes
**Checklist:**
> docs: extract source code to files in ViewCells

- phpstan-baseline.neon.dist
- system/Cache/Handlers/FileHandler.php
- tests/system/Cache/Handlers/FileHandlerTest.php
Ensure safety nets to `$data['ttl']` and `$data['time']`
**Checklist:**
> refactor: [Cache] simplify code of `FileHandler::getItem()`

- user_guide_src/source/concepts/factories.rst
- user_guide_src/source/concepts/factories/002.php
- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/general/configuration.rst
- user_guide_src/source/general/modules.rst
- user_guide_src/source/models/model.rst
- improve Factories and config()
**Checklist:**
> docs: improve Factories and Config

- user_guide_src/source/installation/upgrade_435.rst
- user_guide_src/source/libraries/validation/002.php
- user_guide_src/source/libraries/validation/005.php
- user_guide_src/source/libraries/validation/006.php
- user_guide_src/source/libraries/validation/007.php
- user_guide_src/source/libraries/validation/009.php
- user_guide_src/source/libraries/validation/010.php
- user_guide_src/source/libraries/validation/011.php
- user_guide_src/source/libraries/validation/013.php
- user_guide_src/source/libraries/validation/015.php
- user_guide_src/source/libraries/validation/016.php
- user_guide_src/source/libraries/validation/020.php
- user_guide_src/source/libraries/validation/022.php
- user_guide_src/source/libraries/validation/023.php
- user_guide_src/source/libraries/validation/024.php
- user_guide_src/source/libraries/validation/025.php
- user_guide_src/source/libraries/validation/036.php
- user_guide_src/source/libraries/validation/038.php
- add `max_length` to sample code
- add example for upgrading Validation Placeholder code. Ref #7664
**Checklist:**
> docs: improve Validation

- user_guide_src/source/general/configuration.rst
- user_guide_src/source/general/configuration/007.php
- user_guide_src/source/general/configuration/008.php
- user_guide_src/source/general/configuration/009.php
- user_guide_src/source/general/configuration/010.php
- user_guide_src/source/general/modules.rst
> docs: improve about Registrars

- utils/Rector/RemoveErrorSuppressInTryCatchStmtsRector.php
Prepare for next Rector release, as `findParentType()` removed on rector/rector:dev-main.
**Checklist:**
> [Rector] Remove findParentType() on RemoveErrorSuppressInTryCatchStmtsRector

- phpstan-baseline.neon.dist
- system/Cache/Handlers/RedisHandler.php
Fix the phpstan baseline error.
**Checklist:**
> refactor: [Redis Cache] fix phpstan baseline error

- user_guide_src/source/testing/overview.rst
> docs: update 404 links in testing/overview.rst

- system/Cache/Handlers/FileHandler.php
- system/Cache/Handlers/MemcachedHandler.php
- system/Cache/Handlers/PredisHandler.php
- system/Cache/Handlers/RedisHandler.php
- system/Cache/Handlers/WincacheHandler.php
See https://github.com/codeigniter4/CodeIgniter4/pull/7683#pullrequestreview-1520890381
**Checklist:**
> docs: add comments to Cache Handler constructors

- user_guide_src/source/general/configuration.rst
- user_guide_src/source/general/errors.rst
> docs: improve description on dotenv and credentials

- app/Config/Cache.php
For use by PHPStan.
**Checklist:**
> Fix PHPDoc of `Config\Cache::$validHandlers`

- .github/workflows/test-phpstan.yml
Follow-up #7713
**Checklist:**
> chore: update test-phpstan.yml

- .php-cs-fixer.user-guide.php
Follow-up #7712
**Checklist:**
> chore: fix php-cs-fixer cache file

- system/Common.php
> refactor: services function actually returns `object|null`

- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/installation/upgrade_440.rst
> docs:  small improvements in changelog v4.4.0

- system/Router/DefinedRouteCollector.php
Fix due to changes in the coding standard.
Related #7729
**Checklist:**
> style: [4.4] remove emtpy line

- phpstan-baseline.php
- system/Autoloader/Autoloader.php
> Add types to Autoloader

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.3.8.rst
- user_guide_src/source/installation/upgrade_438.rst
- user_guide_src/source/installation/upgrading.rst
- add changelog/upgrade guide
**Checklist:**
> docs: add changelog/upgrade guide for v4.3.8

- phpstan-baseline.php
- system/BaseModel.php
- system/Model.php
> docs: PHPStan `Model` no type specified

- tests/system/HTTP/SiteURITest.php
- tests/system/Helpers/ArrayHelperTest.php
> test: fix data provider method names

- contributing/pull_request.md
> docs: remove `>` in console command

- tests/system/I18n/TimeLegacyTest.php
- tests/system/I18n/TimeTest.php
Closes #7362
See https://github.com/codeigniter4/CodeIgniter4/issues/7362#issuecomment-1666742204
**Checklist:**
> test: restore TimeTest::testUnserializeTimeObject()

- system/Session/Handlers/RedisHandler.php
`\Config\Session` and `\Config\App` is typed `int`, so no need re-cast:
https://github.com/codeigniter4/CodeIgniter4/blob/46a1e5ef5cfd5bc23cade33215734dc8fdd20a6b/app/Config/Session.php#L43
https://github.com/codeigniter4/CodeIgniter4/blob/46a1e5ef5cfd5bc23cade33215734dc8fdd20a6b/app/Config/App.php#L175
**Checklist:**
> Remove unused cast on RedisHandler

- user_guide_src/source/changelogs/v4.4.0.rst
- cosmetic improvements
**Checklist:**
> docs: improve changelogs v4.4.0

- phpstan-baseline.php
- system/Controller.php
- system/Format/Exceptions/FormatException.php
- system/Format/XMLFormatter.php
- system/Log/Exceptions/LogException.php
- system/Log/Handlers/ChromeLoggerHandler.php
**Description** 
See #7731
**Checklist:**
> Fix: Remove the  `Format`, `Log` and `Controller` ignore errors.

- user_guide_src/source/outgoing/view_cells/018.php
- user_guide_src/source/outgoing/view_cells/019.php
Improved view cell docs by making use of default query builder/model methods, instead of the custom method `getRecent()`. 
See https://forum.codeigniter.com/showthread.php?tid=88190
**Checklist:**
> docs: used default methods for view cell

- user_guide_src/source/testing/response.rst
- user_guide_src/source/testing/response/018.php
- user_guide_src/source/testing/response/019.php
- user_guide_src/source/testing/response/020.php
- user_guide_src/source/testing/response/021.php
- user_guide_src/source/testing/response/022.php
- user_guide_src/source/testing/response/023.php
- user_guide_src/source/testing/response/024.php
- user_guide_src/source/testing/response/025.php
- user_guide_src/source/testing/response/026.php
- user_guide_src/source/testing/response/027.php
- user_guide_src/source/testing/response/028.php
- user_guide_src/source/testing/response/029.php
> docs: improve testing/response.rst

- system/Common.php
- system/Database/OCI8/Forge.php
- system/HTTP/IncomingRequest.php
- system/Helpers/number_helper.php
- system/Helpers/text_helper.php
- system/Test/TestResponse.php
- user_guide_src/source/outgoing/response/003.php
- because of php-cs-fixer update. See https://github.com/codeigniter4/CodeIgniter4/actions/runs/5860496777/job/15888685230?pr=7818
**Checklist:**
> style: update cs

- user_guide_src/source/helpers/form_helper.rst
Fixes the sample code.
**Checklist:**
> docs: fix sample code for `set_checkbox()`

- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/installation/upgrade_440.rst
See https://forum.codeigniter.com/showthread.php?tid=87335&pid=411906#pid411906
**Checklist:**
> [4.4] docs: improve description for Factories BC

- tests/system/Database/Migrations/MigrationRunnerTest.php
Applied using rector dev-main
**Checklist:**
> Apply ::class class constant on MigrationRunnerTest

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.4.1.rst
- user_guide_src/source/installation/upgrade_441.rst
- user_guide_src/source/installation/upgrading.rst
- add changelog and upgrade for v4.4.1
**Checklist:**
> docs: changelog and upgrade for v4.4.1

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.4.2.rst
- user_guide_src/source/installation/upgrade_442.rst
- user_guide_src/source/installation/upgrading.rst
- add changelog and upgrade for v4.4.2
**Checklist:**
> docs: add changelog and upgrade for v4.4.2

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/installation/upgrade_450.rst
- user_guide_src/source/installation/upgrading.rst
- add changelog and upgrading for v4.5.0
**Checklist:**
> docs: add changelog and upgrading for v4.5.0

- system/Common.php
(`null`, `true`) are the default values
**Checklist:**
> refactor: remove unneeded arguments to session

- phpstan.neon.dist
> chore: update phpstan exclude list

- admin/framework/.gitignore
- admin/starter/.gitignore
`.gitkeep` ignored in framework and appstarter. 
This should not be ignored in `writable/debugbar`.
**Checklist:**
> don't ignore `.gitkeep` in `writable/debugbar`

- phpstan.neon.dist
We already follows the rule.
Ref  #7916
**Checklist:**
> chore: [PHPStan] enable disallowedLooseComparison

- .gitattributes
Remove `export-ignore`
**Checklist:**
> Remove duplicate `export-ignore`

- user_guide_src/source/libraries/validation/007.php
Rules given as array do not need separator ('|').
**Checklist:**
> Small typo in validation.html

- user_guide_src/source/changelogs/v4.4.0.rst
- add missing message change
**Checklist:**
> docs: add missing message change to changelog v4.4.0

- user_guide_src/source/libraries/email.rst
Small typo ('your' changed to 'you') in email.rst.
**Checklist:**
> Small typo in email.rst

- phpstan-baseline.php
- system/Database/OCI8/Connection.php
To fix PHPStan error.
See https://github.com/codeigniter4/CodeIgniter4/actions/runs/6358613550/job/17271052582
**Checklist:**
> refactor: if condition in OCI8/Connection.php

- system/Commands/Translation/LocalizationFinder/ArrayHelper.php
- tests/system/Commands/Translation/LocalizationFinder/ArrayHelperTest.php
- fix namespace
**Checklist:**
> test: fix namespace in ArrayHelperTest

- system/Model.php
> [4.5] refactor: remove unused `use` in Model

- user_guide_src/source/installation/upgrade_file_upload.rst
- fix anchor text
**Checklist:**
> docs: fix anchor text in installation/upgrade_file_upload.rst

- phpstan-baseline.php
- system/BaseModel.php
Added in `develop`. See https://github.com/codeigniter4/CodeIgniter4/pull/7951/files#diff-ba12fbd742529128a8b09aba62089ee5eb3eee77f00fa250853f52a85690f92dR1659
**Checklist:**
> [4.5] refactor: remove BaseModel assert()

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.4.3.rst
- user_guide_src/source/installation/upgrade_443.rst
- user_guide_src/source/installation/upgrading.rst
- add changelog and upgrade for v4.4.3
**Checklist:**
> docs: add changelog and upgrade for v4.4.3

- phpstan.neon.dist
[See](https://github.com/codeigniter4/CodeIgniter4/actions/runs/6600280819/job/17930115039)
**Checklist:**
> phpstan: remove unneeded ignoreErrors

- system/Exceptions/FrameworkException.php
Updates to changes in latest php-cs-fixer
**Checklist:**
> style: run cs-fix

- phpstan-baseline.php
- system/CodeIgniter.php
> docs: add Closure signature for CodeIgniter::$controller

- env
The default value is false now.
**Checklist:**
> config: update curlrequest.shareOptions in env

- user_guide_src/source/outgoing/view_cells.rst
- user_guide_src/source/outgoing/view_cells/001.php
- user_guide_src/source/outgoing/view_cells/014.php
- user_guide_src/source/outgoing/view_cells/016.php
- user_guide_src/source/outgoing/view_cells/018.php
- user_guide_src/source/outgoing/view_cells/019.php
> docs: improve view_cells.rst

- system/Commands/Generators/CellGenerator.php
See #8121
- clarify that this command creates a Controlled Cell
**Checklist:**
> fix: make:cell help message

- system/View/Plugins.php
> docs: fix @return in View/Plugins.php

- phpstan-baseline.php
https://github.com/CodeIgniter/phpstan-codeigniter/releases/tag/v1.4.2
**Checklist:**
> Update to phpstan-codeigniter v1.4.2

- env
- delete items that are not expected to change with the environment
**Checklist:**
> [4.5] config: update env

- rector.php
- system/HTTP/Response.php
- system/HTTP/ResponseTrait.php
- user_guide_src/source/changelogs/v4.5.0.rst
- remove deprecated properties in Response
**Checklist:**
> refactor: remove deprecated properties in Response

- system/HTTP/SiteURI.php
We don't know what is invalid in the current error message.
**Checklist:**
> fix: improve error message in SiteURI::normalizeBaseURL()

- system/Test/ControllerTestTrait.php
> docs: fix @param in ControllerTestTrait

- phpstan-baseline.php
- system/BaseModel.php
- system/Model.php
- user_guide_src/source/models/model.rst
- refactor
Related  #8192
**Checklist:**
> refactor: replace non-boolean if conditions in Model

- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/incoming/routing.rst
It is not recommended.
**Checklist:**
> docs: add note to not recommended "Auto Routing (Legacy)"

- user_guide_src/source/helpers/filesystem_helper/010.php
- user_guide_src/source/helpers/filesystem_helper/011.php
> docs: update outdated sample code in filesystem_helper

- phpstan-baseline.php
- system/View/Cell.php
- system/View/RendererInterface.php
> refactor: View classes to fix PHPStan errors

- user_guide_src/source/libraries/validation.rst
See https://forum.codeigniter.com/showthread.php?tid=88817
**Checklist:**
> docs: make note for "Rules for File Uploads" stand out

- .github/workflows/test-phpunit.yml
> chore: use MySQL 8.0 by default

- app/Config/Publisher.php
- system/Config/Publisher.php
- system/Config/Routing.php
- update the default config values.
**Checklist:**
> config: update system/Config/Routing.php

- user_guide_src/source/database/results/003.php
- user_guide_src/source/database/results/007.php
- user_guide_src/source/database/results/013.php
- user_guide_src/source/database/results/014.php
- user_guide_src/source/database/results/015.php
- user_guide_src/source/database/results/016.php
- fix and update sample code
**Checklist:**
> docs: update sample code for Database Custom Result Objects

- user_guide_src/source/database/events.rst
- user_guide_src/source/database/events/001.php
- change sample code to be more practical
**Checklist:**
> docs: change sample code in DB Events

- tests/system/Models/GetCompiledModelTest.php
- move GetCompiledModelTest
**Checklist:**
> test: move GetCompiledModelTest that was in wrong place

- app/Config/Email.php
- system/Email/Email.php
- user_guide_src/source/installation/upgrade_emails.rst
- user_guide_src/source/libraries/email.rst
See https://forum.codeigniter.com/showthread.php?tid=88950
- add missing change
**Checklist:**
> docs: improve "Upgrade Emails"

- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/installation/upgrade_routing.rst
- user_guide_src/source/installation/upgrade_routing/001.php
- improve description
**Checklist:**
> docs: improve upgrade_routing

- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/incoming/routing/047.php
- user_guide_src/source/incoming/routing/048.php
- update sample code (config)
**Checklist:**
> docs: update sample code in Auto Routing

- .github/workflows/reusable-coveralls.yml
- admin/framework/composer.json
- composer.json
- system/ThirdParty/PSR/Log/LoggerAwareInterface.php
- system/ThirdParty/PSR/Log/LoggerAwareTrait.php
- system/ThirdParty/PSR/Log/LoggerInterface.php
- system/ThirdParty/PSR/Log/LoggerTrait.php
- system/ThirdParty/PSR/Log/NullLogger.php
- user_guide_src/source/changelogs/v4.5.0.rst
Closes #4936
- update psr/logto v3
**Checklist:**
> chore: update psr/log to v3

- user_guide_src/source/installation/repositories.rst
- add codeigniter4/queue repository
**Checklist:**
> docs: add codeigniter4/queue repository

- .github/workflows/deploy-userguide-latest.yml
- .github/workflows/reusable-coveralls.yml
- .github/workflows/reusable-phpunit-test.yml
- .github/workflows/reusable-serviceless-phpunit-test.yml
Reverts codeigniter4/CodeIgniter4#8336
> Revert "chore(deps): bump actions/upload-artifact from 3 to 4"

- composer.json
This allows when a package requires `codeigniter4/framework` and this repo is already available, composer will not install `codeigniter4/framework`.
This fixes https://github.com/CodeIgniter/phpstan-codeigniter/commit/530b659576ba5b9e1036407a4b70df3a622b6335#r135480594
**Checklist:**
> Add `replace` to composer.json

- admin/RELEASE.md
- admin/prepare-release.php
- add code to update version number in "phpdoc.dist.xml"
**Checklist:**
> chore: add code to update version number in "phpdoc.dist.xml"

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.4.5.rst
- user_guide_src/source/installation/upgrade_445.rst
- user_guide_src/source/installation/upgrading.rst
- add changelog and upgrade for v4.4.5
**Checklist:**
> docs: add changelog and upgrade for v4.4.5

- .php-cs-fixer.dist.php
- admin/framework/composer.json
- composer.json
- system/Debug/Toolbar/Views/toolbar.tpl.php
- system/Exceptions/FrameworkException.php
- tests/system/Router/AutoRouterImprovedTest.php
- user_guide_src/source/models/entities/018.php
Follow-up #8368
- update php-cs-fixer
**Checklist:**
> style: update coding style by php-cs-fixer v3.43.0

- user_guide_src/source/helpers/array_helper/014.php
In `array_group_by()`, $includeEmpty is not set to true
see: https://codeigniter4.github.io/CodeIgniter4/helpers/array_helper.html
**Checklist:**
> docs: include empty values on `array_group_by()`

- .github/PULL_REQUEST_TEMPLATE.md
Update note title PR and example next minor.
**Checklist:**
> docs: update `PULL_REQUEST_TEMPLATE`

- tests/system/Router/RouteCollectionTest.php
Follow-up #8422
**Checklist:**
> [4.5] test: fix incorrect case classname

- tests/_support/Database/Seeds/CITestSeeder.php
- remove duplicate assignment
**Checklist:**
> test: remove duplicate assignment in CITestSeeder

- tests/system/Database/Live/InsertTest.php
> test: update testInsertBatch() to use various data types

- tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
- fix merge mistake
- https://github.com/codeigniter4/CodeIgniter4/commit/81b8f644399ba112a0b34f73c66b518192874e91#diff-605d8cb21a0607cefb04c35548d31ef960877bd99458a67aa57f3bc573f78eca
**Checklist:**
> [4.5] test: fix 20160428212500_Create_test_tables.php

- tests/system/Database/Live/Postgre/GetFieldDataTest.php
~~Needs #8433~~
- add test
**Checklist:**
> test: add test for Postgre getFieldData()

- tests/system/Database/Live/SQLSRV/GetFieldDataTest.php
> test: add test for SQLSRV getFieldData()

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.4.6.rst
- user_guide_src/source/installation/upgrade_446.rst
- user_guide_src/source/installation/upgrading.rst
- add changelog and upgrade for v4.4.6 
**Checklist:**
> docs: add changelog and upgrade for v4.4.6

- user_guide_src/source/database/metadata.rst
See https://github.com/codeigniter4/CodeIgniter4/pull/8482#issuecomment-1916327892
- add note to `$query->getFieldData()`
**Checklist:**
> docs: fix $query->getFieldData() description

- tests/system/Database/Live/AbstractGetFieldDataTest.php
- tests/system/Database/Live/MySQLi/GetFieldDataTest.php
- tests/system/Database/Live/OCI8/GetFieldDataTest.php
- tests/system/Database/Live/Postgre/GetFieldDataTest.php
- tests/system/Database/Live/SQLSRV/GetFieldDataTest.php
- tests/system/Database/Live/SQLite3/GetFieldDataTest.php
~~Needs #8481~~
- refactor to add another test
**Checklist:**
> test: refactor GetFieldDataTest

- user_guide_src/source/helpers/array_helper.rst
> docs: improve array_helper.rst

- rector.php
@kenjis let's try this to solve timeout error.
**Checklist:**
> chore: Reduce jobsize on rector config

- user_guide_src/source/general/configuration.rst
See https://forum.codeigniter.com/showthread.php?tid=89299&pid=415385#pid415385
**Checklist:**
> docs: improve description for Environment Variables

- user_guide_src/source/installation/deployment.rst
- user_guide_src/source/installation/index.rst
- add about Optimization
**Checklist:**
> docs: add installation/deployment.rst

- app/Config/App.php
- update `@var` type
- update comments
**Checklist:**
> docs: update Config\App comments

- user_guide_src/source/installation/running.rst
- add link to detailed page
**Checklist:**
> docs: add link to detailed page in installation/running.rst

- rector.php
See https://github.com/codeigniter4/CodeIgniter4/actions/runs/7792475299
**Checklist:**
> chore: skip PHPUnit 10 rector rules

- .php-cs-fixer.dist.php
- phpstan-baseline.php
- system/Database/BaseConnection.php
- system/Database/ConnectionInterface.php
See https://github.com/codeigniter4/CodeIgniter4/issues/6814#issuecomment-1928596803
- add PHPDocs
- override php-cs-fixer config
**Checklist:**
> docs: add/update PHPDocs for DB connetion

- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/helpers/url_helper.rst
> docs: fix config filename routes.php

- system/BaseModel.php
- fix `@phpstan-type`. See https://github.com/codeigniter4/shield/pull/1027#issuecomment-1942970837
**Checklist:**
> docs: fix `@phpstan-type` in Model

- README.md
- admin/framework/README.md
- admin/starter/README.md
- admin/starter/tests/README.md
- tests/README.md
- minor updates
**Checklist:**
> docs: update README

- admin/prepare-release.php
It was added by mistake.
**Checklist:**
> chore: update admin/prepare-release.php

- .php-cs-fixer.dist.php
- .php-cs-fixer.no-header.php
- .php-cs-fixer.user-guide.php
- app/Config/View.php
- system/BaseModel.php
- system/Config/View.php
- system/Database/BaseConnection.php
- system/Database/BasePreparedQuery.php
- system/Database/BaseResult.php
- system/View/Parser.php
Aligns `@phpstan-var` with `@var`, and series of `@phpstan-type`.
**Checklist:**
> style: also align `@phpstan-type` and `@phpstan-var`

- user_guide_src/source/installation/upgrade_450.rst
> docs: improve upgrade_450.rst

- user_guide_src/source/changelogs/v4.5.0.rst
- move the section "Enhancements" up
**Checklist:**
> docs: improve changelogs v4.5.0

- tests/_support/Log/Handlers/TestHandler.php
- tests/system/HTTP/RedirectExceptionTest.php
- tests/system/Log/LoggerTest.php
> test: LoggerTest depends on time

- system/BaseModel.php
- tests/system/Models/SaveModelTest.php
> fix: Model::shouldUpdate() logic

- .github/workflows/test-deptrac.yml
Follow-up #8627
**Checklist:**
> chore: update test-deptrac.yml

- phpstan-baseline.php
- phpstan.neon.dist
If left false, this error will continue to increase.
**Checklist:**
> chore: enable PHPStan checkMissingIterableValueType

- user_guide_src/source/tutorial/news_section.rst
Small docs typo in news_section.rst file, Create news/index View file Note section.
**Checklist:**
> docs: Small docs typo in news_section.rst file.

- user_guide_src/source/tutorial/static_pages.rst
Small typo in static_pages.rst file URL-Will show table
**Checklist:**
> docs: small typo in static_pages.rst

- contributing/workflow.md
Added how to signing only commit in PR.
**Checklist:**
> docs: update workflow.md

- user_guide_src/source/tutorial/news_section.rst
- user_guide_src/source/tutorial/news_section/002.php
- user_guide_src/source/tutorial/news_section/003.php
- user_guide_src/source/tutorial/news_section/004.php
- user_guide_src/source/tutorial/news_section/005.php
- user_guide_src/source/tutorial/news_section/006.php
- user_guide_src/source/tutorial/static_pages.rst
- user_guide_src/source/tutorial/static_pages/001.php
- user_guide_src/source/tutorial/static_pages/002.php
- replace `empty()`
- rename variable name
- add typehints to controller methods
**Checklist:**
> docs: improve News Tutorial code

- phpstan-baseline.php
- phpstan.neon.dist
> chore: add PHPStan checking to tests/

- phpstan-baseline.php
Follow-up #8658
Currently, the PHPStan check is failing.
**Checklist:**
> [4.5] chore: update PHPStan baseline

- LICENSE
- user_guide_src/source/license.rst
> docs: update 2024 for copyright

- system/HTTP/Exceptions/BadRequestException.php
- add declare(strict_types=1)
**Checklist:**
> [4.5] refactor: add declare(strict_types=1) in BadRequestException

- user_guide_src/source/libraries/images.rst
- minor improvements
**Checklist:**
> docs: minor improvements in images.rst

- user_guide_src/source/installation/upgrade_447.rst
added this line to changed files upgrade
- app/Config/App.php
**Checklist:**
> docs: add missing app/Config/App.php in upgrade_447.rst

- .gitattributes
- Adds more paths to export-ignore in .gitattributes
- Visually align elements to see better the pathnames of export-ignored files
- Alphabetize the files per their respective categories
**Checklist:**
> chore: realign contents of .gitattributes

- user_guide_src/source/installation/running.rst
The settings may redirect to URI with `/public/`.
E.g., `http://localhost/ci4/users/` -> `http://localhost/ci4/public/users`
**Checklist:**
> docs: fix sample .htaccess code in running.rst

- user_guide_src/source/database/metadata.rst
> docs: fix layout in Database Metadata

- user_guide_src/source/concepts/security.rst
- user_guide_src/source/database/queries.rst
> docs: update Security Guidelines

- user_guide_src/source/outgoing/localization.rst
- update descriptions
**Checklist:**
> docs: update "Setting the Current Locale"

- user_guide_src/source/changelogs/v4.5.0.rst
- restructure the document
**Checklist:**
> docs: restructure Change Logs 4.5.0

- app/.htaccess
- public/.htaccess
- tests/.htaccess
- user_guide_src/.htaccess
- writable/.htaccess
- change indentations for consistency
**Checklist:**
> style: change indentations in htaccess

- .gitignore
- admin/starter/tests/.htaccess
- admin/starter/tests/index.html
- writable/debugbar/index.html
See https://forum.codeigniter.com/showthread.php?tid=90598
**Checklist:**
> chore: add .htaccess and index.html for consistency

- user_guide_src/source/installation/upgrade_448.rst
See https://forum.codeigniter.com/showthread.php?tid=90598
See https://github.com/codeigniter4/appstarter/commit/f4b08c2e9b8d4efdffd95e3a36abc58a13474abf
The change in `composer.json` was rector version up.
**Checklist:**
> docs: fix files in "All Changes" in Project Files in upgrade_448.rst

- user_guide_src/source/installation/upgrade_450.rst
Change the description to a more appropriate wording.
**Checklist:**
> docs: change description to more appropriate in upgrade_450

- user_guide_src/source/incoming/routing.rst
Updated the explanation under "Array Callable Syntax" header.
**Checklist:**
> docs: update "Array Callable Syntax" description in routing.rst

- phpstan-baseline.php
- system/Debug/Toolbar/Collectors/Routes.php
See #8732 
- add types
**Checklist:**
> refactor: system/Debug/Toolbar/Collectors/Routes.php

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.5.2.rst
- user_guide_src/source/installation/upgrade_452.rst
- user_guide_src/source/installation/upgrading.rst
- add changelog and upgrade for v4.5.2
**Checklist:**
> docs: add changelog and upgrade for v4.5.2

- admin/starter/phpunit.xml.dist
Follow-up #8773
- fix phpunit.xml.dist for appstarter
**Checklist:**
> chore: fix phpunit.xml.dist for appstarter

- user_guide_src/source/incoming/incomingrequest.rst
Change "a HTTP" to "an HTTP", "an lowercase" to "a lowercase" an "lower-case" to "lowercase".
**Checklist:**
> docs: Small typos in incomingrequest.rst

- user_guide_src/source/outgoing/view_parser.rst
Fix typo view_parser.rst.
**Checklist:**
> docs: Fix typo view_parser.rst

- phpstan-baseline.php
- system/Database/BaseConnection.php
- system/Database/MySQLi/Connection.php
- system/Database/Postgre/Connection.php
- system/Database/SQLSRV/Connection.php
- system/Database/SQLite3/Connection.php
- system/Test/Mock/MockConnection.php
> docs: fix/add @return types in DB Connection

- .php-cs-fixer.dist.php
- .php-cs-fixer.no-header.php
- .php-cs-fixer.tests.php
- .php-cs-fixer.user-guide.php
- spark
- user_guide_src/source/libraries/curlrequest/012.php
Part of modernising the coding standard to PHP 8.1+ features.
**Checklist:**
> style: enable modernize_strpos

- user_guide_src/source/outgoing/table.rst
Fix typo in table.rst, clear function description.
**Checklist:**
> docs: Fix typo in table.rst

- user_guide_src/source/outgoing/response.rst
Small change in Class Reference description in response.rst.
**Checklist:**
> docs: Small change in Class Reference description in response.rst

- user_guide_src/source/outgoing/response.rst
Fix typo in response.rst: "This are" to "This is"
**Checklist:**
> docs: Fix typo in response.rst

- tests/_support/Entity/UserWithCasts.php
- tests/_support/Models/UserEntityWithCastsModel.php
- tests/system/Models/FindModelTest.php
> test: add test for Model returns Entity with Casts

- system/ThirdParty/Kint/Parser/FsPathPlugin.php
- system/ThirdParty/Kint/Parser/MysqliPlugin.php
- system/ThirdParty/Kint/Zval/BlobValue.php
- system/ThirdParty/Kint/Zval/Representation/SplFileInfoRepresentation.php
- system/ThirdParty/Kint/init.php
See https://github.com/kint-php/kint/releases/tag/5.1.1
**Checklist:**
> chore: update Kint to 5.1.1

- user_guide_src/source/models/entities.rst
Fix typo in models/entities.rst
**Checklist:**
> docs: Fix typo in models/entities.rst

- phpstan-baseline.php
- system/CLI/GeneratorTrait.php
- system/Commands/Encryption/GenerateKey.php
> docs: fix PHPDoc types for `Commands`

- user_guide_src/source/database/utilities.rst
Change page header to be consistent with the menu in database/utilities.rst
**Checklist:**
> docs: Change page header in database/utilities.rst

- user_guide_src/source/database/index.rst
- user_guide_src/source/database/metadata.rst
Fix some small typos in database/metadata.rst
**Checklist:**
> docs: Small typos in database/metadata.rst

- user_guide_src/source/models/model.rst
Fix typo in models/model.rst
**Checklist:**
> docs: Fix typo in models/model.rst

- user_guide_src/source/dbmgmt/migration.rst
Fix typo in dbtgmt/migration.rst
**Checklist:**
> docs: Fix typo in dbtgmt/migration.rst

- user_guide_src/source/dbmgmt/forge.rst
- user_guide_src/source/dbmgmt/index.rst
Fix typo in dbmgmt/forge.rst
**Checklist:**
> docs: Fix typo in dbmgmt/forge.rst

- user_guide_src/source/libraries/cookies.rst
Fix typos in libraries/cookies.rst
**Checklist:**
> docs: Fix typos in libraries/cookies.rst

- .github/workflows/test-phpunit.yml
- .github/workflows/test-psalm.yml
- remove sqlsrv ext version
- add db extentions for Psalm. See https://github.com/codeigniter4/CodeIgniter4/pull/8864#issuecomment-2099495926
**Checklist:**
> chore: update workflows php exts

- user_guide_src/source/concepts/factories.rst
- user_guide_src/source/installation/deployment.rst
See https://forum.codeigniter.com/showthread.php?tid=90802
**Checklist:**
> docs: add notes for Config Caching

- user_guide_src/source/libraries/sessions.rst
Small typos and modifications in libraries/sessions.rst
**Checklist:**
> docs: Small typos and modifications in libraries/sessions.rst

- user_guide_src/source/libraries/file_collections.rst
Small typo in libraries/file_collections.rst
**Checklist:**
> docs: Small typo in libraries/file_collections.rst

- user_guide_src/source/libraries/honeypot.rst
> docs: Small typos in libraries/honeypot.rst

- user_guide_src/source/libraries/file_collections.rst
- user_guide_src/source/libraries/files/012.php
- user_guide_src/source/libraries/files/014.php
> docs: improve file_collections.rst

- tests/README.md
Follow-up #8821
- replace `@group` with `Group` attribute
**Checklist:**
> docs: update tests README

- user_guide_src/source/testing/overview.rst
> docs: update notes for `@runInSeparateProcess`

- README.md
- admin/framework/README.md
- admin/starter/README.md
- user_guide_src/source/intro/requirements.rst
Updates PHP 8.1 EOL dates. 
See https://www.php.net/supported-versions.php and https://wiki.php.net/rfc/release_cycle_update
**Checklist:**
> docs: update PHP 8.1 EOL dates

- user_guide_src/source/concepts/structure.rst
- improve concepts/structure.rst
**Checklist:**
> docs: improve concepts/structure.rst

- user_guide_src/source/general/managing_apps.rst
- remove outdated note
**Checklist:**
> docs: remove outdated note in managing_apps.rst

- user_guide_src/source/libraries/uri.rst
Some typos and small modifications in libraries/uri.rst
**Checklist:**
> docs: Some typos and modifications in libraries/uri.rst

- admin/userguide/.github/scripts/deploy
- improve script
**Checklist:**
> chore: improve user guide deploy script

- contributing/pull_request.md
- contributing/workflow.md
- some improvements
**Checklist:**
> docs: imporve contributing

- user_guide_src/source/concepts/factories.rst
- user_guide_src/source/general/modules.rst
- user_guide_src/source/outgoing/views.rst
- update and improvements
**Checklist:**
> docs: update modules.rst

- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/libraries/validation/037.php
Small typos in libraries/validation.rst
**Checklist:**
> docs: Small typos in libraries/validation.rst

- user_guide_src/source/libraries/uploaded_files.rst
- simplify explanation
**Checklist:**
> docs: simplify explanation in uploaded_files.rst

- user_guide_src/source/libraries/time.rst
Some small typos and modifications in libraries/time.rst
**Checklist:**
> docs: Some small typos and modifications in libraries/time.rst

- rector.php
as no longer part of sets
**Checklist:**
> chore: remove JsonThrowOnErrorRector and FinalizePublicClassConstantRector from skip() config

- user_guide_src/source/testing/benchmark.rst
Small typo in testing/benchmark.rst
**Checklist:**
> docs: Small typo in testing/benchmark.rst

- user_guide_src/source/testing/debugging.rst
Small typo in testing/debugging.rst
**Checklist:**
> docs: Small typo in testing/debugging.rst

- system/Model.php
- tests/system/Models/DataConverterModelTest.php
See https://forum.codeigniter.com/showthread.php?tid=91006
**Checklist:**
> fix: Model::find() returns incorrect data with casting

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.5.3.rst
- user_guide_src/source/installation/upgrade_453.rst
- user_guide_src/source/installation/upgrading.rst
- add changelog and upgrade for v4.5.3
**Checklist:**
> docs: add changelog and upgrade for v4.5.3

- system/CLI/GeneratorTrait.php
- system/CodeIgniter.php
Fix CS brought by coding-standard v1.8.0
**Checklist:**
> style: fix cs

- .github/scripts/deploy-userguide
> chore: add checks for RELEASE and VERSION variables

- system/Database/BaseBuilder.php
> refactor: BaseBuilder::orderBy()

- user_guide_src/source/changelogs/v4.6.0.rst
- to improve readability
**Checklist:**
> docs: add categories to Enhancements > Libraries

- phpstan-baseline.php
- system/Database/OCI8/Connection.php
See https://github.com/codeigniter4/CodeIgniter4/issues/8984#issuecomment-2183766946
**Checklist:**
> fix: [OCI8] if conditions to build DSN

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.5.4.rst
- user_guide_src/source/installation/upgrade_454.rst
- user_guide_src/source/installation/upgrading.rst
- add changelog and upgrade for v4.5.4
**Checklist:**
> docs: add changelog and upgrade for v4.5.4

- user_guide_src/source/incoming/filters.rst
- user_guide_src/source/incoming/routing.rst
> docs: improve descriptions to Filters

- system/Filters/Filters.php
- refactor by Rector
**Checklist:**
> [4.6] refactor: add `: void`

- rector.php
- system/Test/DatabaseTestTrait.php
Since we require phpunit 10 and we require php 8.1 already, rector attribute rules can be enabled.
**Checklist:**
> refactor: Enable phpunit 10 attribute Rector rules

- .php-cs-fixer.dist.php
- .php-cs-fixer.no-header.php
- .php-cs-fixer.tests.php
- .php-cs-fixer.user-guide.php
> chore: make php-cs-fixer configs DRY

- system/Config/BaseService.php
- system/Config/Services.php
- tests/system/Config/ServicesTest.php
Fixes #9024 
Prevent cases where invalid session handler is provided.
**Checklist:**
> fix: Prevent invalid session handlers

- app/Views/errors/html/error_400.php
- system/Language/en/Errors.php
- user_guide_src/source/changelogs/v4.6.0.rst
- add 400 page
Before:
production
After:
production
development
**Checklist:**
> feat: add "400 Bad Request" page for end users

- user_guide_src/source/libraries/user_agent/005.php
`referrer` is undefined, but `getReferrer` available
see: 
https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/HTTP/UserAgent.php
https://codeigniter4.github.io/userguide/libraries/user_agent.html#CodeIgniter\HTTP\UserAgent::getReferrer
**Checklist:**
> docs: `referrer` is undefined

- system/Database/Postgre/Connection.php
- system/Database/Postgre/PreparedQuery.php
PHP 8.1 introduces the `PgSql` classes as replacement for pgsql's resources.
**Checklist:**
> refactor: use `PgSql` classes

- user_guide_src/source/database/query_builder.rst
- make the description more accurate
**Checklist:**
> docs: update QueryBuilder descriptions for join()

- user_guide_src/source/general/configuration.rst
> docs: add note for Registrars

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.5.5.rst
- user_guide_src/source/installation/upgrade_455.rst
- user_guide_src/source/installation/upgrading.rst
- add changelog and upgrade for v4.5.5
**Checklist:**
> docs: add changelog and upgrade for v4.5.5

- contributing/workflow.md
- add step to update Composer packages
**Checklist:**
> docs: update contributing/workflow.md

- user_guide_src/source/models/model/057.php
> docs: add missing property types

- preload.php
> fix: update preload.php

- system/ThirdParty/PSR/Log/LoggerAwareInterface.php
- system/ThirdParty/PSR/Log/LoggerAwareTrait.php
- system/ThirdParty/PSR/Log/LoggerInterface.php
- system/ThirdParty/PSR/Log/LoggerTrait.php
- system/ThirdParty/PSR/Log/NullLogger.php
- update psr/log to 3.0.1
**Checklist:**
> docs: update psr/log to 3.0.1

- user_guide_src/source/helpers/html_helper.rst
Change tags to elements and fix some typos helpers/html_helper.rst.
**Checklist:**
> docs: Change tags to elements and fix some typos helpers/html_helper.rst

- .github/workflows/label-add-conflict-all-pr.yml
This workflow comments to PRs with conflicts. So it is better to link to "Updating Your Branch".
- https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#pushing-your-branch
- https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#updating-your-branch
**Checklist:**
> chore: fix link in fix-label-add-conflict-all-pr.yml

- system/Database/BaseBuilder.php
Follow-up #9156
- remove uneeded if condition 
**Checklist:**
> refactor: BaseBuilder

- system/Database/BaseConnection.php
Just a typo I stumbled across, nothing more.
**Checklist:**
> refactor: fix typo in BaseConnection.php

- user_guide_src/source/libraries/validation.rst
Insert 'are' after 'that' to add missing auxilliary verb.
**Checklist:**
> docs: correct grammar in validation.rst

- user_guide_src/source/helpers/html_helper.rst
Fix some function definitions in helpers/html_helper.rst
**Checklist:**
> docs: Fix some function definitions in helpers/html_helper.rst

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.5.6.rst
- user_guide_src/source/installation/upgrade_456.rst
- user_guide_src/source/installation/upgrading.rst
-  add changelog and upgrade for v4.5.6
**Checklist:**
> docs: add changelog and upgrade for v4.5.6

- rector.php
- system/Database/OCI8/Builder.php
- system/Database/OCI8/PreparedQuery.php
- system/Database/Postgre/Builder.php
- system/Database/Postgre/PreparedQuery.php
- system/Database/SQLSRV/Builder.php
- system/Database/SQLite3/Builder.php
- system/Debug/Toolbar/Collectors/Database.php
- system/Events/Events.php
- system/HTTP/ContentSecurityPolicy.php
- system/HTTP/Negotiate.php
- system/Helpers/Array/ArrayHelper.php
- system/Router/Router.php
- system/View/Parser.php
- tests/system/Commands/Utilities/NamespacesTest.php
- tests/system/DataConverter/DataConverterTest.php
- tests/system/Debug/TimerTest.php
- tests/system/Events/EventsTest.php
- tests/system/Test/FeatureTestTraitTest.php
- tests/system/Validation/ValidationTest.php
- tests/system/View/ParserTest.php
Add closure return type should be safe, this PR adds it via  `ClosureReturnTypeRector`
**Checklist:**
> refactor: enable ClosureReturnTypeRector

- user_guide_src/source/general/ajax.rst
Reference : 
- https://codeigniter4.github.io/CodeIgniter4/general/ajax.html#htmx
- https://extensions.htmx.org/
**Checklist:**
> docs: broken link htmx ajax-header

- user_guide_src/source/installation/upgrade_455.rst
See https://forum.codeigniter.com/showthread.php?tid=91656&pid=421265#pid421265
**Checklist:**
> docs: fix Project Files changes in upgrade_455.rst

- user_guide_src/source/concepts/factories.rst
improve the description for `Factories`.
Related to #9181 #8914
**Checklist:**
> docs: improve Factories

- system/Commands/Utilities/Routes/AutoRouterImproved/AutoRouteCollector.php
- system/HTTP/SiteURI.php
With manually run latest rector dev-main for feature
- https://github.com/rectorphp/rector-src/pull/6331
**Checklist:**
> refactor: add more readonly property definitions on AutoRouteCollector and SiteURI

- rector.php
- system/Config/Services.php
- system/Images/Handlers/ImageMagickHandler.php
Apply SimplifyDeMorganBinaryRector for Simplify negated conditions with de Morgan theorem
**Checklist:**
> refactor: enable rector code quality level 14

- rector.php
- system/HTTP/CLIRequest.php
Applied `SimplifyUselessVariableRector` to removes useless variable assigns
**Checklist:**
> refactor: enable rector code quality level 15

- admin/framework/composer.json
- composer.json
PR laminas/laminas-escaper#56 already release in https://github.com/laminas/laminas-escaper/releases/tag/2.14.0.
**Checklist:**
> refactor: bump `laminas/laminas-escaper` to `v2.14` minimum required

- app/Views/errors/html/debug.css
Consistent used color primary brand Codeigniter, and change position to `fixed`.
Before :
After :
**Checklist:**
> feat: design info environment top in `error_exception`

- user_guide_src/source/models/model/006.php
- user_guide_src/source/models/model/008.php
- user_guide_src/source/models/model/046.php
> docs: variable naming adjustments

- system/Controller.php
- utils/phpstan-baseline/catch.neverThrown.neon
- utils/phpstan-baseline/loader.neon
The underlying `force_https` may throw `RedirectException`
**Checklist:**
> refactor: add `@throws RedirectException` in `Controller::initController`

- system/ThirdParty/Escaper/Escaper.php
> chore: bump to laminas-escaper v2.15

- tests/_support/Entity/CustomUser.php
- utils/phpstan-baseline/loader.neon
- utils/phpstan-baseline/new.static.neon
As it is just a test fixture, I think it's safe to turn it final.
**Checklist:**
> refactor: fix warning on new static usage

- composer.json
See CI failures in #9345 . Hope this fixes it.
**Checklist:**
> chore: add branch-alias for `master` branch

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.5.7.rst
- user_guide_src/source/installation/upgrade_457.rst
- user_guide_src/source/installation/upgrading.rst
> docs: add changelog and upgrade for v4.5.7

- .github/ISSUE_TEMPLATE/bug_report.yml
> chore: add PHP 8.4 to issue template

- user_guide_src/source/database/queries/016.php
- user_guide_src/source/database/queries/019.php
Update to latest php-cs-fixer
**Checklist:**
> style: bump to php-cs-fixer v3.66

- user_guide_src/source/changelogs/v4.5.7.rst
see PR:
- https://github.com/codeigniter4/CodeIgniter4/pull/9354
/cc @michalsn 
**Checklist:**
> chore: add changelog for bug fix helper() throw FileNotFoundException on valid namespaced helper

- CHANGELOG.md
- phpdoc.dist.xml
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.5.7.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_457.rst
Updates changelog and version references for 4.5.7.
Previous version: #9344 
**Checklist:**
> Prep for 4.5.7 release

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.5.8.rst
- user_guide_src/source/installation/upgrade_458.rst
- user_guide_src/source/installation/upgrading.rst
> docs: add changelog and upgrade for v4.5.8

- tests/system/Database/Builder/SelectTest.php
- utils/phpstan-baseline/generator.returnType.neon
- utils/phpstan-baseline/loader.neon
Nothing special. 
**Checklist:**
> refactor: Fix phpstan generator.returnType

- composer.json
@neznaika0 tomorrow should be another release for more support phpstan 2.1.1, but this ensure less noise for latest release, see for BC break 2.1.1
- https://github.com/rectorphp/rector-src/pull/6649
**Checklist:**
> chore: Bump to PHPStan 2.0.5

- composer.json
immediate bump to latest 2.0.6 to support latest PHPStan 2.1.1
**Checklist:**
> chore: Bump to Rector 2.0.6

- LICENSE
- user_guide_src/source/license.rst
> chore: update 2025 for copyright

- .github/mergeable.yml
I somehow missed that it is CodeIgniter4 and not CodeIgniter in the bug template. Sorry for that.
**Checklist:**
> chore: fix wrong constraint in mergeable.yml

- CHANGELOG.md
- phpdoc.dist.xml
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.5.8.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_458.rst
Updates changelog and version references for 4.5.8.
Previous version: #9357 
**Checklist:**
> Prep for 4.5.8 release

- admin/RELEASE.md
Updates the release guide
**Checklist:**
> chore: update release process

- admin/framework/.gitignore
- admin/starter/.gitignore
Ensure that the NetBeans IDE-related entries in the framework/admin/starter/.gitignore and framework/admin/framework/.gitignore files apply exclusively to their respective root directories.
Fixes #9423
**Checklist:**
> chore: Fix Netbeans IDE related entries in two gitignore files under framework admin dir

- composer.json
For the sake of fixing dependabot updates
**Checklist:**
> chore: try a universal branch alias

- composer.json
Ref https://github.com/CodeIgniter/phpstan-codeigniter/pull/34#issuecomment-2613299827
**Checklist:**
> chore: try using codeigniter/phpstan-codeigniter:1.x-dev

- .github/mergeable.yml
Replaces and closes #8885 
Test run 1: https://github.com/paulbalandan/b40d520f57f086f2e58d1f21d093935d/pull/6
Test run 2: https://github.com/paulbalandan/b40d520f57f086f2e58d1f21d093935d/pull/7
API Ref: https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=opened#pull_request
**Checklist:**
> chore: greet new PR contributors using mergeable

- app/Config/Cache.php
Update Cache.php to fix some formatting.
Update Cache.php to fix some formatting.
**Checklist:**
> style: Update Cache to fix some formatting

- .github/mergeable.yml
The filter conditions were executed as OR, so if any filter passes it starts commenting PRs as if they are coming from first time contributors.
Tested: https://github.com/paulbalandan/b40d520f57f086f2e58d1f21d093935d/pull/9
**Checklist:**
> chore: remove draft condition in mergeable

- system/Email/Email.php
> refactor: get upper first protocol only one call in Email

- system/Events/Events.php
No needed lowercase event name for logger.
**Checklist:**
> refactor: remove lowercase event name for logging

- phpstan.neon.dist
- system/Test/Filters/CITestStreamFilter.php
Makes the file analysed by phpstan now.
**Checklist:**
> refactor: add `CITestStreamFilter` to phpstan-analysed list and fix errors

- admin/starter/tests/_support/Libraries/ConfigReader.php
- preload.php
- public/index.php
- spark
- system/Debug/Toolbar/Views/toolbar.tpl.php
- tests/system/Config/fixtures/RegistrarConfig.php
- tests/system/Config/fixtures/SimpleConfig.php
Import them in `use` statements.
**Checklist:**
> refactor: import FQCNs

- tests/system/Database/Builder/SelectTest.php
- utils/phpstan-baseline/generator.valueType.neon
- utils/phpstan-baseline/loader.neon
Fixing the return of the data provider.
**Checklist:**
> test: fix `generator.valueType` error

- tests/system/Session/SessionTest.php
Ref:
- https://github.com/codeigniter4/CodeIgniter4/pull/9535#discussion_r2052022296
- https://github.com/codeigniter4/CodeIgniter4/pull/9536#discussion_r2051798869
**Checklist:**
> test: add tests showing `Session::markAs(Flash|Temp)data()` invalidates all keys when not all in session

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.6.2.rst
- user_guide_src/source/installation/upgrade_462.rst
- user_guide_src/source/installation/upgrading.rst
Adds the 4.6.2 changelog and upgrade guide.
**Checklist:**
> docs: add changelog and upgrade for v4.6.2

- system/CLI/Console.php
...instead of two calls
**Checklist:**
> refactor: `Console::showHeader()` call `date()` only once

- composer.json
Avoid crash on phpstan 2.1.18
**Checklist:**
> chore: bump to rector 2.1.2

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.6.3.rst
- user_guide_src/source/installation/upgrade_463.rst
- user_guide_src/source/installation/upgrading.rst
Adds changelog for v4.6.3
**Checklist:**
> docs: add changelog and upgrade for v4.6.3

- user_guide_src/source/extending/events/006.php
Fixed a typo in event docs, where it should be `some_event` instead of `some_events`
**Checklist:**
> docs: Fixed typo

- composer.json
- rector.php
- tests/system/Config/FactoriesTest.php
- Bump Rector to 2.1.5
- Re-run it
**Checklist:**
> chore: Bump to Rector 2.1.5 and apply it

- rector.php
- system/CLI/CLI.php
Apply `ForeachItemsAssignToEmptyArrayToAssignRector` to change foreach() items assign to empty array to direct assign.
**Checklist:**
> refactor: apply code quality level 41 for Rector

- rector.php
- system/Filters/PageCache.php
Apply `SimplifyIfNullableReturnRector` to direct return on if nullable check before return
**Checklist:**
> refactor: apply code quality level 54 for Rector
