- system/API/ResponseTrait.php
- system/Common.php
- system/Config/BaseService.php
- system/Config/Services.php
- system/Debug/Exceptions.php
- system/Debug/Toolbar.php
- system/HTTP/CURLRequest.php
- system/HTTP/ContentSecurityPolicy.php
- system/HTTP/ResponseInterface.php
- system/HTTP/ResponseTrait.php
- system/RESTful/ResourceController.php
- system/RESTful/ResourcePresenter.php
- system/Security/Security.php
- system/Session/Session.php
- system/Test/ControllerTestTrait.php
- system/Test/ControllerTester.php
- tests/system/HTTP/ContentSecurityPolicyTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
~~Needs to rebase after merging #6556~~
Ref #4356
Now the framework depends on ResponseInterface, not Response.
Add
- `Response::getCSP()`
- `ResponseInterface::getCSP()`
- `ResponseInterface::getReasonPhrase()`
- `ResponseInterface::getCookieStore()`
Change APIs
- `API\ResponseTrait::failServerError()`
- `Services::exceptions()`
- `Debug\Exceptions::__construct()`
Deprecate
- `Response::$CSP`.  It is now `public`, but should be protected.
**Checklist:**
> fix: ResponseInterface (2)

- system/Filters/Filters.php
`$response` is an object, so it is passed as an object id.
https://www.php.net/manual/en/language.oop5.references.php
**Checklist:**
> refactor: remove unnecessary "&" in Filters

- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.3.0.rst
They are no longer used, because of the refactoring for Spark processing in 4.3.
**Checklist:**
> docs: deprecated CodeIgniter::$path and CodeIgniter::setPath()

- system/CLI/BaseCommand.php
Fix #6656
When you :
- change the location of the views used to generate errors,
- provide a new path in \Config\Exceptions::$errorViewPath,
- and then run a CLI command generating an exception :
the error message is complaining about the location of the error_exception.php file... because the view path is hardcoded.
So instead of using a hardcoded directory for the error_exception.php file,
we should use the provided errorViewPath from \Config\Exceptions::$errorViewPath
**Checklist:**
> Bug: showError in CLI/BaseCommand use hardcoded error view path

- system/Database/Forge.php
- system/Database/MySQLi/Forge.php
- system/Database/OCI8/Forge.php
- system/Database/Postgre/Forge.php
- system/Database/SQLSRV/Forge.php
- system/Database/SQLite3/Forge.php
- system/Database/SQLite3/Table.php
- tests/system/Database/Live/ForgeTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/dbmgmt/forge.rst
- user_guide_src/source/dbmgmt/forge/010.php
- user_guide_src/source/dbmgmt/forge/011.php
- user_guide_src/source/dbmgmt/forge/020.php
Closes #5075
This PR allows setting the index name.
While testing dropping by the same name I discovered that `dropKey()` was generating errors when dropping a unique index be several of the DBMS. The reason is that some DBMS require `DROP CONSTRAINT` command rather than `DROP INDEX`. I did some extra work to get `dropKey()` to work properly.
MySql and SQLite don't really require a name for Primary Key - though Mysql allows setting the name. When dropping its as simple as `DROP PRIMARY KEY`.
**Checklist:**
> Add ability to set index names

- system/Log/Logger.php
Follow-up #6638
**Checklist:**
> refactor: move print_r to interpolate and use clean_path

- system/Common.php
- system/Log/Handlers/ChromeLoggerHandler.php
- system/Log/Logger.php
- See #6310
- Supersedes #6633
**Checklist:**
> docs: replace types in `Logger`

- system/Validation/StrictRules/Rules.php
See #6310 
If there is `if (! is_string($value))` judgement, I chagned the type `mixed` to `array|bool|float|int|object|string|null`.
If there isn't the judgement of non-string, I changed the type `string|null`.
**Checklist:**
> docs: replace types `mixed` at `Validation\StrictRules\Rule`.

- contributing/workflow.md
- use `git rebase --onto`
**Checklist:**
> docs: improve "If You Sent to the Wrong Branch"

- system/HTTP/IncomingRequest.php
- system/HTTP/Negotiate.php
- tests/system/HTTP/IncomingRequestTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
See #5344
Deprecate
- IncomingRequest::$uri
- IncomingRequest::$config
**Checklist:**
> Deprecate public properties in IncomingRequest

- system/Validation/StrictRules/CreditCardRules.php
- system/Validation/StrictRules/FormatRules.php
All class in validation have been changed typed `mixed` to `array|bool|float|int|object|string|null`.
**Checklist:**
> docs: replace types `mixed` at Vaildation rule classes.

- system/Validation/FormatRules.php
See #6170
See https://github.com/codeigniter4/CodeIgniter4/pull/6172#issuecomment-1275496541
```console
bash-3.2$ ./phpunit tests/system/Validation/FormatRulesTest.php
PHPUnit 9.5.25 #StandWithUkraine
Runtime:       PHP 8.2.0-dev
Configuration: /Users/kenji/work/codeigniter/official/CodeIgniter4/phpunit.xml
...............................................................  63 / 193 ( 32%)
............................................................... 126 / 193 ( 65%)
............................................................... 189 / 193 ( 97%)
....                                                            193 / 193 (100%)
Time: 00:00.325, Memory: 14.00 MB
OK (193 tests, 193 assertions)
```
**Checklist:**
- [] Component(s) with PHPDoc blocks, only if necessary or adds …
> refactor: valid_date does not work in PHP 8.2

- admin/framework/composer.json
- composer.json
There are two extensions used in `TestResponse`.
**Checklist:**
> chore: add `suggest` extensions in composer.json

- system/CodeIgniter.php
- tests/system/CodeIgniterTest.php
- add method to disable controller filters
**Checklist:**
> feat: add method to disable controller filters

- system/HTTP/IncomingRequest.php
- tests/system/HTTP/IncomingRequestTest.php
- user_guide_src/source/changelogs/v4.2.8.rst
- user_guide_src/source/incoming/incomingrequest.rst
This PR fixes the problem below:
```php
$_GET['foo'] = 'bar';
d(service('request')->getPostGet());
// returns an empty array
```
Basically, we return only one stream:
* for `getPostGet()` method - `POST` array
* and for `getGetPost()` method - `GET` array
And that's fine when the `index` is specified. 
But not when `index` is `null`. We should check both streams for values and return them all with priority for `GET` or `POST` values - depending on the used method.
**Checklist:**
> fix: getGetPost() and getPostGet() when index is null

- .php-cs-fixer.dist.php
- .php-cs-fixer.no-header.php
- .php-cs-fixer.user-guide.php
- system/Database/BaseBuilder.php
- system/Database/MySQLi/Connection.php
- system/Debug/Toolbar.php
- system/Helpers/form_helper.php
- system/View/Parser.php
- tests/system/HTTP/MessageTest.php
- tests/system/Images/GDHandlerTest.php
- tests/system/Images/ImageMagickHandlerTest.php
- user_guide_src/source/testing/benchmark/007.php
Depends on #6674 
```console
$ vendor/bin/php-cs-fixer describe no_useless_concat_operator
Description of no_useless_concat_operator rule.
There should not be useless concat operations.
Fixer is configurable using following option:
* juggle_simple_strings (bool): allow for simple string quote juggling if it results in more concat-operations merges; defaults to false
--- Original
+++ New
@@ -1,2 +1,2 @@
<?php
-$a = 'a'.'b';
+$a = 'ab';
* Example #2. Fixing with configuration: ['juggle_simple_strings' => true].
--- Original
+++ New
@@ -1,2 +1,2 @@
<?php
-$a = 'a'."b";
+$a = "ab";
----------- end diff …
```
> Enable `no_useless_concat_operator`

- tests/system/Database/Live/UpsertTest.php
SQLite was using GMT time and not timezone set on OS.
**Checklist:**
> Fix UpsertTest::testUpsertWithMultipleSet

- tests/system/HTTP/MessageTest.php
- adding string `\n` does  not make sense
**Checklist:**
> test: make test case in MessageTest a bit more realistic

- system/Database/BaseBuilder.php
- system/Database/MySQLi/Builder.php
- system/Database/OCI8/Builder.php
- system/Database/Postgre/Builder.php
- system/Database/SQLSRV/Builder.php
- system/Database/SQLite3/Builder.php
See #6678
- run `composer cs-fix`.
**Checklist:**
> [4.3] style: update coding style

- tests/system/HTTP/ResponseTest.php
Fixes #5428
In the `testSetLastModifiedWithDateTimeObject()` method, there are two `DateTime::createFromFormat` calls
When they are performed close to the beginning of a new second, the difference between the two dates is (sometimes) one second
To reproduce, just add a delay between the two date calls
```diff
@@ -244,6 +244,7 @@ final class ResponseTest extends CIUnitTestCase
$response = new Response(new App());
$response->setLastModified(DateTime::createFromFormat('Y-m-d', '2000-03-10'));
+        sleep(1);
$date = DateTime::createFromFormat('Y-m-d', '2000-03-10');
$date->setTimezone(new DateTimeZone('UTC'));
```
The fix, attached in this PR, is to use the same date object
**Checklist:**
> Bug: ResponseTest::testSetLastModifiedWithDateTimeObject depends on time

- tests/system/HTTP/URITest.php
- tests/system/Pager/PagerTest.php
See #5344
- `IncomingRequest::$uri` will be protected.
- `$request->getUri()->getPath()` does not start with `/`. `IncomingRequest::$uri` is a bit different from a normal URI object.
https://github.com/codeigniter4/CodeIgniter4/blob/a3eedf4055c1a2895051b654c49311641dd2975f/system/HTTP/IncomingRequest.php#L60-L71
**Checklist:**
> test: remove $request->uri and fix incorrect assertions

- .github/workflows/test-phpstan.yml
- phpstan-baseline.neon.dist
- phpstan.neon.dist
PHP 8.1 is the most used version with Composer.
**Checklist:**
> chore: update PHPStan PHP version to 8.1

- system/HTTP/Request.php
- system/HTTP/RequestInterface.php
- system/HTTP/Response.php
- user_guide_src/source/changelogs/v4.3.0.rst
A parallel change to https://github.com/codeigniter4/CodeIgniter4/pull/6556 this gives our HTTP Request objects their expected methods.
Ref #6573
**Checklist:**
> fix: MessageInterface inheritance

- app/Views/errors/html/error_exception.php
- system/HTTP/ResponseTrait.php
- user_guide_src/source/libraries/curlrequest/006.php
- user_guide_src/source/libraries/curlrequest/010.php
- user_guide_src/source/libraries/curlrequest/012.php
- replace deprecated getHeaders() with headers()
- replace deprecated getHeader() with header()
**Checklist:**
> refactor: replace deprecated getHeaders() with headers()

- system/View/Cells/Cell.php
- tests/_support/View/Cells/RenderedExtraDataNotice.php
- tests/system/View/ControlledCellTest.php
Follow-up #6620
This is related to the Controlled Cells.
According to the user guide, we should be able to assign extra variables to the `view()` method. But this function doesn't seem to be implemented. This PR fixes it.
Ref: https://github.com/codeigniter4/CodeIgniter4/blob/4.3/user_guide_src/source/outgoing/view_cells.rst#customize-the-rendering
**Checklist:**
> fix: support for assigning extra data for the view() method in controlled cells

- phpstan-baseline.neon.dist
- system/Database/BasePreparedQuery.php
- system/Database/MySQLi/PreparedQuery.php
- system/Database/OCI8/PreparedQuery.php
- system/Database/Postgre/PreparedQuery.php
- system/Database/SQLSRV/PreparedQuery.php
- system/Database/SQLite3/PreparedQuery.php
- tests/system/Database/Live/PreparedQueryTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/database/queries.rst
- user_guide_src/source/database/queries/020.php
Fixes #1256
Implement a common method in each database connector to destroy the prepared query when we're done with it
Cf Issue codeigniter4/CodeIgniter4#1256 : TODO Deallocate prepared statements
To closes a prepared statement :
- MySQLi have mysqli_stmt_close()
https://www.php.net/manual/en/mysqli-stmt.close.php
- OCI8 have oci_free_statement()
https://www.php.net/manual/en/function.oci-free-statement.php
- Postgre does not have a specific PHP function for deleting a prepared statement,
the SQL DEALLOCATE statement can be used for that purpose :
https://www.php.net/manual/en/function.pg-prepare.php
https://www.postgresql.org/docs/8.1/sql-deallocate.html
- SQLite3 have SQLite3Stmt::close()
https://www.php.net/manual/en/sqlite3stmt.close.php
- SQLSRV have …
> Deallocate prepared statements

- system/HTTP/MessageInterface.php
- user_guide_src/source/changelogs/v4.3.0.rst
- add missing getProtocolVersion()
- PSR-7 has the method
**Checklist:**
> fix: add missing getProtocolVersion() in MessageInterface

- tests/system/Test/TestCaseTest.php
Code uses `PHP_EOL` but test uses `"\n"`, so it fails on Windows.
**Checklist:**
> fix: `TestCaseTest::testStreamFilter` fails on Windows

- phpstan-baseline.neon.dist
- system/Database/BaseConnection.php
- system/Test/Mock/MockConnection.php
- add missing methods `_disableForeignKeyChecks()` and `_ebleForeignKeyChecks()`
- fix a bug that `Forge::dropTable()` causes an error if an extended connection class does not have these methods
**Checklist:**
> fix: add missing methods to BaseConnection

- system/Database/BaseConnection.php
These are already defined by `ConnectionInterface`.
**Checklist:**
> refactor: remove unneeded abstract public methods

- system/Test/CIUnitTestCase.php
- system/Test/TestLogger.php
- tests/system/Test/TestCaseTest.php
- tests/system/Test/TestLoggerTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/testing/overview.rst
- user_guide_src/source/testing/overview/007.php
Currently, `CIUnitTestCase::assertLogged()` matches the logged message verbatim. For simple messages this is no problem but for complex, hard-to-build, or volatile messages, it may be hard to come up with the exact message. This PR adds the capability for the `assertLogged` method to compare only parts of the message instead of the whole.
**Checklist:**
> feat: Check logs against parts of the message only

- system/Common.php
- tests/system/CommonFunctionsTest.php
- fix a bug that `esc()` accepts invalid context `'0'`
See https://github.com/codeigniter4/CodeIgniter4/pull/6715#discussion_r1000030058
**Checklist:**
> fix: bug that esc() accepts invalid context '0'

- phpstan-baseline.neon.dist
- system/Common.php
- system/Helpers/form_helper.php
- fix PHPDoc types. See #6310
- remove unneeded code
**Checklist:**
> refactor: remove unneeded code in form_helper

- system/BaseModel.php
- system/Common.php
- system/Database/BaseBuilder.php
- system/Format/XMLFormatter.php
- system/HTTP/IncomingRequest.php
- system/HTTP/ResponseInterface.php
- system/HTTP/ResponseTrait.php
- system/Model.php
- system/Session/Session.php
- system/Test/CIUnitTestCase.php
- system/Test/TestResponse.php
- system/View/Filters.php
- system/View/View.php
~~Needs #6722~~
See #6310
- ~~remove unneeded empty check~~
**Checklist:**
> docs: fix PHPDoc type mixed

- system/Database/Forge.php
- system/Database/MySQLi/Forge.php
- system/Database/SQLSRV/Forge.php
- system/Database/SQLite3/Forge.php
- system/Database/SQLite3/Table.php
- tests/system/Database/Live/ForgeTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/dbmgmt/forge.rst
- user_guide_src/source/dbmgmt/forge/029.php
Closes #4814
This PR allows creating indexes on an existing table. 
It is used following ``addKey()``, ``addPrimaryKey()``, ``addUniqueKey()``, and ``addForeignKey()`` to add indexes to an existing table. It is used instead of or in place of  ``createTable()``.
This is the last part of https://github.com/codeigniter4/CodeIgniter4/pull/6430
Fixes #6453
**Checklist:**
> Add Forge::processIndexes() to create indexes on existing table

- system/Format/FormatterInterface.php
- fix `@return` type
**Checklist:**
> docs: fix `@return` type in FormatterInterface

- system/HTTP/ResponseTrait.php
This is merge mistake. When `$body` is false, it will be null in the end.
**Checklist:**
> docs: fix ResponseTrait::getJSON() `@return` type

- phpstan-baseline.neon.dist
- system/Database/BaseConnection.php
- system/Database/BasePreparedQuery.php
- system/Database/ConnectionInterface.php
- system/Database/MySQLi/Connection.php
- system/Database/MySQLi/PreparedQuery.php
- system/Database/OCI8/Connection.php
- system/Database/OCI8/PreparedQuery.php
- system/Database/Postgre/Connection.php
- system/Database/Postgre/PreparedQuery.php
- system/Database/PreparedQueryInterface.php
- system/Database/SQLSRV/Connection.php
- system/Database/SQLSRV/PreparedQuery.php
- system/Database/SQLite3/Connection.php
- system/Database/SQLite3/PreparedQuery.php
Making `BaseConnection` a generic type, thus extensions need to specify the type of the connection.
**Checklist:**
> Add template types to `Connection`

- app/Config/Exceptions.php
- system/Debug/Exceptions.php
- tests/system/Debug/ExceptionsTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/general/errors.rst
- user_guide_src/source/general/errors/012.php
- user_guide_src/source/general/errors/013.php
- user_guide_src/source/general/errors/014.php
~Depends on #6704~
Alternative to #6703 
Opt-in feature to log deprecations (both internal and user-supplied) instead of thrown by the error handler.
**Checklist:**
> feat: Opt-in logging of deprecations

- user_guide_src/source/changelogs/v4.1.0.rst
- user_guide_src/source/helpers/url_helper.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/installation/upgrade_410.rst
- Since v4.x.x, ...
- Prior to v4.x.x, ...
**Checklist:**
> docs: make version notation consistent

- system/Database/Postgre/Builder.php
- tests/system/Database/Live/InsertTest.php
- user_guide_src/source/changelogs/v4.2.8.rst
Fixes #6726
Code provided by kenjis. Thanks!
**Checklist:**
> fix: [Postgres] reset binds when replace() method is called multiple times in the context

- user_guide_src/source/changelogs/v4.3.0.rst
Reorganize the changelog.
**Checklist:**
> docs: improve changelog 4.3.0

- system/Test/PhpStreamWrapper.php
- add missing property $context
See https://www.php.net/manual/en/class.streamwrapper.php#streamwrapper.props
In PHP 8.2, the following error ocurrs:
> ErrorException: Creation of dynamic property CodeIgniter\Test\PhpStreamWrapper::$context is deprecated
**Checklist:**
> fix: add missing property $context in PhpStreamWrapper

- user_guide_src/README.rst
- user_guide_src/source/_static/js/citheme.js
- user_guide_src/source/changelogs/v4.0.0-beta.3.rst
- user_guide_src/source/dbmgmt/db_commands.rst
- user_guide_src/source/general/configuration.rst
- user_guide_src/source/helpers/html_helper.rst
- user_guide_src/source/incoming/content_negotiation.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/installation/repositories.rst
- user_guide_src/source/installation/upgrade_sessions.rst
- user_guide_src/source/libraries/official_packages.rst
- user_guide_src/source/libraries/pagination.rst
- user_guide_src/source/libraries/throttler.rst
- user_guide_src/source/libraries/uploaded_files.rst
- user_guide_src/source/libraries/uri.rst
- user_guide_src/source/models/model.rst
- user_guide_src/source/models/model/001.php
- user_guide_src/source/outgoing/api_responses.rst
- user_guide_src/source/testing/benchmark.rst
- user_guide_src/source/testing/fabricator.rst
- user_guide_src/source/testing/feature.rst
- user_guide_src/source/testing/response/018.php
- user_guide_src/source/testing/response/024.php
- user_guide_src/source/tutorial/index.rst
I found some grammar errors and typos in the documentation and have fixed them. Maintaining documentation is something that's important to me :-)
**Checklist:**
> Fixed several grammar errors and typos

- system/Database/SQLSRV/PreparedQuery.php
- tests/system/Database/Live/PreparedQueryTest.php
- user_guide_src/source/changelogs/v4.2.8.rst
This PR fixes the result object for `CodeIgniter\Database\SQLSRV\PreparedQuery::_getResult()`.
**Checklist:**
> fix: [SQLSRV] _getResult() return object for preparedQuery class

- .github/workflows/test-autoreview.yml
- .github/workflows/test-coding-standards.yml
- .github/workflows/test-deptrac.yml
- .github/workflows/test-phpcpd.yml
- .github/workflows/test-phpstan.yml
- .github/workflows/test-phpunit.yml
- .github/workflows/test-rector.yml
- .github/workflows/test-scss.yml
- .github/workflows/test-userguide.yml
Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
See: https://github.com/nodejs/node/pull/42017
**Checklist:**
> Cancel running CI jobs when a PR is updated

- system/Debug/Exceptions.php
- user_guide_src/source/changelogs/v4.2.8.rst
The callback to `set_error_handler` expects to return a `bool`:
https://www.php.net/manual/en/function.set-error-handler.php
**Checklist:**
> Fix error handler callback

- .github/workflows/test-phpunit.yml
- composer.json
Supersedes and closes #6696
The new workflow:
- Each parallel job generates a PHP coverage report in the format `build/cov/coverage-php-v${PHP_VERSION}-${DB}.cov`
- Each `.cov` file is uploaded via `@actions/upload-artifact` (No submission to coveralls yet at this point)
- The uploaded files are to be retained for only 5 days to save on resources (can be much shorter if requested here)
- After all covered jobs are done, all `.cov` files are downloaded
- The `.cov` files are merged together by using `phpunit/phpcov`
- The merged `.cov` files are generated into a clover.xml file
- The clover.xml (containing the consolidated coverage) is submitted to coveralls.io via `php-coveralls/php-coveralls`
**Checklist:**
> refactor: Coverage uploading to coveralls.io

- system/BaseModel.php
- system/Database/Config.php
- system/Database/Seeder.php
- system/Test/CIUnitTestCase.php
Reduce the complexity of the method.
- refactor
- remove `&`
- fix PHPDoc
```console
$ phploc system/Database/Config.php
```
Before:
```
Cyclomatic Complexity
Average Complexity per LLOC                     0.52
Average Complexity per Class                   13.00
Minimum Class Complexity                     13.00
Maximum Class Complexity                     13.00
Average Complexity per Method                   3.00
Minimum Method Complexity                     1.00
Maximum Method Complexity                    11.00
```
After:
```
Cyclomatic Complexity
Average Complexity per LLOC                     0.38
Average Complexity per Class                   10.00
Minimum Class Complexity                     10.00
Maximum Class Complexity                     10.00
Average …
```
> refactor: Database connect()

- .github/workflows/deploy-apidocs.yml
- .github/workflows/test-autoreview.yml
- .github/workflows/test-coding-standards.yml
- .github/workflows/test-deptrac.yml
- .github/workflows/test-phpcpd.yml
- .github/workflows/test-phpstan.yml
- .github/workflows/test-phpunit.yml
- .github/workflows/test-rector.yml
- .github/workflows/test-scss.yml
- .github/workflows/test-userguide.yml
- rector.php
The runner image for Ubuntu 22.04 LTS has been out for a while now.
**Checklist:**
> Raise runner version to ubuntu-22.04

- system/Test/TestResponse.php
PHPStan is complaining about DOMParser methods that pass through. E.g.:
https://github.com/lonnieezell/myth-auth/actions/runs/3321152878/jobs/5488411025#step:9:82
**Checklist:**
> bug: Supply mixin for TestResponse

- system/Test/DOMParser.php
- tests/system/Test/DOMParserTest.php
See #6170
See https://php.watch/versions/8.2/mbstring-qprint-base64-uuencode-html-entities-deprecated
- `mb_convert_encoding($str, 'HTML-Entities')` is deprecated in PHP 8.2.
**Checklist:**
> refactor: DOMParser::withString() for PHP 8.2

- tests/system/Database/Live/GetTest.php
See  #6170
```
1) CodeIgniter\Database\Live\GetTest::testGetRowWithCustomReturnType
ErrorException: Creation of dynamic property class@anonymous::$id is deprecated
/Users/kenji/work/codeigniter/official/CodeIgniter4/system/Database/SQLite3/Result.php:143
/Users/kenji/work/codeigniter/official/CodeIgniter4/system/Database/SQLite3/Result.php:147
/Users/kenji/work/codeigniter/official/CodeIgniter4/system/Database/BaseResult.php:149
/Users/kenji/work/codeigniter/official/CodeIgniter4/system/Database/BaseResult.php:286
/Users/kenji/work/codeigniter/official/CodeIgniter4/system/Database/BaseResult.php:273
/Users/kenji/work/codeigniter/official/CodeIgniter4/tests/system/Database/Live/GetTest.php:234
```
**Checklist:**
- [] Component(s) with PHPDoc blocks, only if necessary or …
> test: fix Creation of dynamic property error in PHP 8.2

- system/CodeIgniter.php
- tests/system/CodeIgniterTest.php
- user_guide_src/source/changelogs/v4.2.8.rst
> fix: CodeIgniter::run() doesn't respect $returnResponse

- system/Database/BaseBuilder.php
- system/Database/MySQLi/Builder.php
- system/Database/OCI8/Builder.php
- system/Database/Postgre/Builder.php
- system/Database/SQLSRV/Builder.php
- system/Database/SQLite3/Builder.php
- tests/system/Database/Live/UpdateTest.php
This fixes an issue when using an alias with setAlias() method. When using escape identifiers it was adding database prefix to alias. This was fixed.
Also, a small change to use of RawSql in constraints for updateBatch() and upsertBatch(). RawSql can be used for the entire expression or used as a key value pair. This is how I originally intended it but somehow it didn't get in correctly.
Can we expedite merging this? These fixes are needed for my other PRs.
**Checklist:**
> Fix BaseBuilder setAlias() and RawSql use with key value pairs

- phpunit.xml.dist
- system/Test/CIUnitTestCase.php
To test this, use the `--testdox` option in `phpunit` and compare PHPUnit's reported time vs. the slow time reported. This should be lesser.
Ref: https://github.com/NexusPHP/tachycardia/blob/1.x/docs/limiting_test_times.md
**Checklist:**
> Leverage Tachycardia's Expeditable trait to obtain slim execution times

- system/Debug/Exceptions.php
See #6170 
Suppress the following error in PHP 8.2.
This error prevents our app and library developments to support 8.2. See https://github.com/codeigniter4/CodeIgniter4/pull/6172#issuecomment-1288302674
```
1) CodeIgniter\Test\FabricatorTest::testMakeArrayReturnsArray
ErrorException: Use of "static" in callables is deprecated
/Users/kenji/work/codeigniter/official/CodeIgniter4/vendor/fakerphp/faker/src/Faker/Provider/Base.php:374
/Users/kenji/work/codeigniter/official/CodeIgniter4/vendor/fakerphp/faker/src/Faker/Provider/Base.php:432
/Users/kenji/work/codeigniter/official/CodeIgniter4/vendor/fakerphp/faker/src/Faker/Provider/Base.php:449
/Users/kenji/work/codeigniter/official/CodeIgniter4/vendor/fakerphp/faker/src/Faker/Provider/Internet.php:118 …
```
> fix: workaround for Faker deprecation errors in PHP 8.2

- user_guide_src/source/general/errors.rst
"Custom Exceptions" feels a little different.
**Checklist:**
> docs: change "Custom Exceptions" to "Framework Exceptions"

- system/Helpers/html_helper.php
- system/Helpers/url_helper.php
See #6310
- fix `@param` types
**Checklist:**
> docs: fix `@param` types in html/url helper

- user_guide_src/source/installation/upgrade_430.rst
Follow-up to #6705
**Checklist:**
> Add config changes to upgrade guide

- system/Database/ResultInterface.php
- user_guide_src/source/changelogs/v4.3.0.rst
Fixes #6776
See #4356
**Checklist:**
> fix: add missing ResultInterface::getNumRows()

- app/Controllers/BaseController.php
- phpstan-baseline.neon.dist
- system/HTTP/CURLRequest.php
- system/HTTP/Message.php
- system/HTTP/OutgoingRequest.php
- system/HTTP/OutgoingRequestInterface.php
- system/HTTP/Request.php
- system/HTTP/RequestInterface.php
- tests/system/HTTP/OutgoingRequestTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
See #6573, #4356
- add `OutgoingRequest`
- add `OutgoingRequestInterface`
- `CURLRequest` extends `OutgoingRequest`
- `Request` extends `OutgoingRequest`
- `RequestInterface` extends `OutgoingRequestInterface`
http://www.plantuml.com/plantuml/uml/ZP1TQWCX58NVNSKX2-XJ5n38IuMKbf0kGEoTGUhFLAzGADrxnQOIbCpaRPXpplUf-yGgSdPMB4f_g9cmEyZ77Ru501ZF52Ub2S-KKadb_uykViay1-Fd4trcIjnge2yc_vwszhTsDy6Y0hHLgR5Xt6B9aUTHrze3iPb6oYWVQJsbcrpJrguWlGvkE5JRrAOFJE2m84nzl-Q0yZ2N0F52caB4q_dy-b0x1Levr-x3KTwhRTKjOock2DzEnurtwyrrCwZ3twYfE-MFs9VlxEml
```puml
@startuml
package "CI4" {
interface MessageInterface
interface OutgoingRequestInterface extends MessageInterface
interface RequestInterface extends OutgoingRequestInterface
class Message implements MessageInterface
class OutgoingRequest extends …
```
> feat: add OutgoingRequestInterface

- tests/system/Cookie/CookieStoreTest.php
Found in #6773 
Since the deprecated methods have `@codeCoverageIgnore` already, no testing is needed to cover those methods.
**Checklist:**
> Remove testing of deprecated methods in CookieStore

- user_guide_src/source/libraries/caching.rst
> docs: fix sub section level in caching.rst

- tests/system/Commands/GenerateKeyTest.php
- tests/system/CommonFunctionsSendTest.php
- tests/system/CommonFunctionsTest.php
- tests/system/Config/BaseConfigTest.php
- tests/system/Config/ConfigTest.php
- tests/system/Config/DotEnvTest.php
- tests/system/Config/ServicesTest.php
- tests/system/Events/EventsTest.php
- tests/system/Filters/HoneypotTest.php
- tests/system/HTTP/ContentSecurityPolicyTest.php
- tests/system/HTTP/DownloadResponseTest.php
- tests/system/HTTP/IncomingRequestTest.php
- tests/system/HTTP/RedirectResponseTest.php
- tests/system/HTTP/ResponseSendTest.php
- tests/system/Helpers/FormHelperTest.php
- tests/system/Test/TestCaseEmissionsTest.php
Closes #6783 
The relevant php-cs-fixer rule will be adjusted in `coding-standard` (https://github.com/CodeIgniter/coding-standard/commit/644b3edd1dc5ad21849c4aded4a3c6e39d0e2eaf)
**Checklist:**
> Group `runInSeparateProcess` and `preserveGlobalState`

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.2.8.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_428.rst
- user_guide_src/source/installation/upgrading.rst
Updates changelog and version references for `4.2.8`.
**Checklist:**
> Prep for 4.2.8 release

- system/Config/Factories.php
> docs: fix PHPDoc types in Factories

- system/Database/BasePreparedQuery.php
- system/Database/MySQLi/PreparedQuery.php
- system/Database/OCI8/PreparedQuery.php
- system/Database/Postgre/PreparedQuery.php
- system/Database/PreparedQueryInterface.php
- system/Database/SQLSRV/PreparedQuery.php
- system/Database/SQLite3/PreparedQuery.php
- tests/system/Database/Live/PreparedQueryTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/database/queries.rst
Fixes #4342
This PR fixes the behavior of Prepared Queries, which always return a `Result` object.
Some time ago, we fixed the regular query: #4176, but somehow Prepared Queries were forgotten.
Desired behavior is the same as for regular queries, return:
* `Result` object for "read" queries
* `bool` value for "write" queries
Potentially this is a breaking change, but we should treat it as a bug fix.
**Checklist:**
> fix: BasePreparedQuery class to return boolean values for write-type queries

- user_guide_src/source/libraries/images/002.php
- user_guide_src/source/testing/controllers/005.php
- add missing `\`
**Checklist:**
> docs: add missing `\` for consistency

- .github/workflows/test-phpunit.yml
> Add PHP 8.2 to Unit Tests GHA

- app/Config/Exceptions.php
- app/Config/Logger.php
- phpunit.xml.dist
- system/Debug/Exceptions.php
- tests/system/Debug/ExceptionsTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/general/errors.rst
- user_guide_src/source/general/errors/012.php
- user_guide_src/source/installation/upgrade_430.rst
Following up on #6705 , this turns on the feature by default.
Deprecation notices should not halt execution. These notices are here to _notify_ the users that something will not work in the _future_. They should not be forced to fix it now.
This PR changes the following:
- Turns on deprecation logging
- Raise logger reporting threshold to `5`
- Use the env variable `CODEIGNITER_SCREAM_DEPRECATIONS` to temporarily throw deprecations in tests (for convenience rather than changing the config).
Related: #6764
**Checklist:**
> Turn on logging for deprecation notices by default

- phpstan-baseline.neon.dist
- system/Database/BaseConnection.php
- system/Database/BasePreparedQuery.php
- system/Database/BaseResult.php
- system/Database/ConnectionInterface.php
- system/Database/MySQLi/Connection.php
- system/Database/MySQLi/PreparedQuery.php
- system/Database/MySQLi/Result.php
- system/Database/OCI8/Connection.php
- system/Database/OCI8/PreparedQuery.php
- system/Database/OCI8/Result.php
- system/Database/Postgre/Connection.php
- system/Database/Postgre/PreparedQuery.php
- system/Database/Postgre/Result.php
- system/Database/PreparedQueryInterface.php
- system/Database/ResultInterface.php
- system/Database/SQLSRV/Connection.php
- system/Database/SQLSRV/PreparedQuery.php
- system/Database/SQLSRV/Result.php
- system/Database/SQLite3/Connection.php
- system/Database/SQLite3/PreparedQuery.php
- system/Database/SQLite3/Result.php
Make ResultInterface a generic type.
**Checklist:**
> Add template types to Result

- system/Debug/Toolbar.php
The following controller outputs `0` if you enable debug toolbar.
`<script  id="debugbar_loader" data-time="1667373293.313775" src="[http://localhost:8080/index.php?debugbar](view-source:http://localhost:8080/index.php?debugbar)"></script><script  id="debugbar_dynamic_script"></script><style type="text/css"  id="debugbar_dynamic_style"></style>0`
```php
<?php
use Kint;
{
{
Kint::$enabled_mode = false;
return '';
}
}
```
**Checklist:**
> fix: output "0" at the end of toolbar js when Kint::$enabled_mode is false

- system/Test/CIUnitTestCase.php
Reuse existing utility method
**Checklist:**
> Refactor assertHeaderEmitted and assertHeaderNotEmitted

- system/Database/SQLSRV/Connection.php
- system/HTTP/CURLRequest.php
- system/Helpers/text_helper.php
- system/Session/Handlers/MemcachedHandler.php
- PHPStan 1.9.0 reported errors.
**Checklist:**
> fix: variable types for PHPStan 1.9.0

- phpstan-baseline.neon.dist
~~Needs #6810~~
- PHPStan 1.9.0 reported errors.
**Checklist:**
> fix: [4.3] remove ignoreErrors item for PHPStan 1.9.0

- system/Model.php
- fix typos in comments
**Checklist:**
> docs: fix typos in comments in Model

- system/I18n/TimeTrait.php
- tests/system/I18n/TimeTest.php
> fix: Time::now() does not respect timezone when using setTestNow()

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.2.10.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_4210.rst
- user_guide_src/source/installation/upgrading.rst
Updates changelog and version references for `4.2.10`.
**Checklist:**
> Prep for 4.2.10 release

- system/Helpers/date_helper.php
- tests/system/Helpers/DateHelperTest.php
~~Needs #6752~~
Fixes #5492 
Supersedes #6684
- refactor `now()`
- fix test code
**Checklist:**
> refactor: make now() testable

- app/Config/Toolbar.php
Thanks `codespell` for finding spelling mistakes.
**Checklist:**
> docs: Fix typo in Toolbar.php

- .github/workflows/test-phpunit.yml
- system/BaseModel.php
- system/Model.php
- replace  type mixed. See #6310
- fix comments
**Checklist:**
> docs: fix PHPDoc and comments in Models

- system/BaseModel.php
- tests/system/I18n/TimeTest.php
> refactor: replace time() with Time in BaseModel

- system/Model.php
- tests/_support/Models/WithoutAutoIncrementModel.php
From https://forum.codeigniter.com/showthread.php?tid=84733
- The `$primaryKey` field should never be an allowed field.
**Checklist:**
> fix: Model cannot insert when $useAutoIncrement is false

- README.md
- admin/framework/README.md
- admin/starter/README.md
- update README.md
**Checklist:**
> docs: update README.md

- system/View/Parser.php
- tests/system/View/ParserPluginTest.php
From https://forum.codeigniter.com/showthread.php?tid=84773
**Checklist:**
> fix: View Parser regexp does not support UTF-8

- system/Commands/Encryption/GenerateKey.php
- tests/system/Commands/GenerateKeyTest.php
> Handle key generation when key is not present in .env

- app/Config/App.php
- system/HTTP/IncomingRequest.php
- system/HTTP/URI.php
- system/Helpers/url_helper.php
- system/Test/Mock/MockIncomingRequest.php
- tests/system/HTTP/RedirectResponseTest.php
- tests/system/HTTP/ResponseTest.php
- tests/system/Helpers/URLHelper/CurrentUrlTest.php
- tests/system/Helpers/URLHelper/SiteUrlTest.php
- tests/system/Pager/PagerTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/helpers/url_helper.rst
- user_guide_src/source/installation/upgrade_430.rst
Supersedes #6759
Fixes #5807
Related #6746
- add `Config\App::$allowedHostnames`
- add `URI::$baseURL`, `URI::setBaseURL()` and `URI::getBaseURL()`
- `IncomingRequest::__construct()` sets `URI::$baseURL`
- use `HTTP_HOST` when it is an allowed hostname 
- refactor
**Changes:**
- `current_url()`, `base_url()`, `site_url()` will return the URL with allowed `HTTP_HOST`
- `previous_url()` will return the site URL with allowed `HTTP_HOST` when cannot get it from session nor `HTTP_REFERER`
The following functions/methods are affected (There may be others):
- Using `site_url()`
- form_open()
- audio()
- embed()
- img()
- link_tag()
- object()
- script_tag()
- source()
- video()
- RedirectResponse::route()
- RedirectResponse::to()
- Toolbar::prepare()
- Toolbar::respond()
- …
> feat: add $allowedHostnames for multiple domain support

- .github/workflows/test-autoreview.yml
- .github/workflows/test-phpunit.yml
- composer.json
- phpunit.xml.dist
- tests/system/AutoReview/ComposerJsonTest.php
- tests/system/AutoReview/FrameworkCodeTest.php
- tests/system/Database/BaseConnectionTest.php
- tests/system/Database/BaseQueryTest.php
- tests/system/Database/Builder/LikeTest.php
- tests/system/Database/Live/DeleteTest.php
- tests/system/Database/Live/UpdateTest.php
- tests/system/Database/Live/WhereTest.php
- tests/system/HTTP/Files/FileCollectionTest.php
- tests/system/HTTP/NegotiateTest.php
- tests/system/HTTP/URITest.php
- tests/system/Helpers/NumberHelperTest.php
- tests/system/Session/SessionTest.php
- tests/system/Throttle/ThrottleTest.php
- tests/system/View/ParserTest.php
Needs #6770 for tests to pass.
Code based on my private repo.
**Checklist:**
> Auto-review tests to enforce `@group` annotations

- system/Test/ControllerTestTrait.php
- tests/system/Test/ControllerTestTraitTest.php
The `ControllerTestTrait` "with___" methods use local property references to apply their changes before execution. This doesn't work for `$body` however because it is a string and not passed by reference, so using `withBody()` has no effect.
This PR moves the application of the body to the `execute()` method so it is properly applied to the request prior to execution.
**Checklist:**
> Fix: Controller Test withBody()

- user_guide_src/source/models/model.rst
This behavior can be confusing for many users. It should be clearly described in the user guide.
Ref, #4617
> docs: add a note about setting the null value for the primary key in Model::update()

- deptrac.yaml
- system/Session/Session.php
> refactor: replace time() with Time in `Session.php`

- deptrac.yaml
- system/Email/Email.php
- system/Helpers/date_helper.php
> refactor: replace time() with Time into `date_helper` and `Email` class

- tests/system/Database/Migrations/MigrationRunnerTest.php
The different directory separators mess up local testing
**Checklist:**
> Fix MigrationRunnerTest for Windows

- system/HTTP/CURLRequest.php
- tests/system/HTTP/CURLRequestDoNotShareOptionsTest.php
- tests/system/HTTP/CURLRequestTest.php
> fix: body assigned via options array in CURLRequest class

- deptrac.yaml
- system/Cache/Handlers/FileHandler.php
- system/Cache/Handlers/MemcachedHandler.php
- system/Cache/Handlers/PredisHandler.php
- system/Cache/Handlers/RedisHandler.php
- system/Cache/Handlers/WincacheHandler.php
- tests/system/Cache/Handlers/AbstractHandlerTest.php
- tests/system/Cache/Handlers/FileHandlerTest.php
- tests/system/Cache/Handlers/MemcachedHandlerTest.php
- tests/system/Cache/Handlers/PredisHandlerTest.php
- tests/system/Cache/Handlers/RedisHandlerTest.php
> refactor: make `time()` to class `Time` in `Cache`

- system/Commands/Database/CreateDatabase.php
When running `vendor/bin/phpunit --group DatabaseLive` either on GA or local, MigrationRunnerTest fails:
On GA:
```console
PHPUnit 9.5.26 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.4.32
Configuration: /home/runner/work/CodeIgniter4/CodeIgniter4/phpunit.xml.dist
..S............................................................  63 / 516 ( 12%)
............S.S...S...........S................................ 126 / 516 ( 24%)
...................................................SSSSSSS..... 189 / 516 ( 36%)
............................................................... 252 / 516 ( 48%)
.............F................................................. 315 / 516 ( 61%)
............................................................... 378 / 516 ( 73%) …
```
> Fix CreateDatabase leaving altered database config in connection

- tests/system/Commands/Database/ShowTableInfoTest.php
> Fix ShowTableInfoTest to pass on Windows

- system/Session/Handlers/FileHandler.php
- system/Session/Handlers/MemcachedHandler.php
- system/Session/Handlers/RedisHandler.php
> refactor: replace time() with Time into whole `Session` class.

- deptrac.yaml
- system/Cookie/Cookie.php
- system/Debug/Toolbar.php
- system/Debug/Toolbar/Collectors/Database.php
> refactor: replace `time()` with Time into `Debug` and `Cookie` class.

- system/HTTP/Header.php
- tests/system/HTTP/HeaderTest.php
Fixes: #6842
I think that casting will be a better option than throwing an exception in this case.
**Checklist:**
> fix: cast to string all values except arrays in Header class

- system/Model.php
- user_guide_src/source/changelogs/v4.3.0.rst
It is not good if the behavior changes only in the production environment.
It is impossible to write tests for the production environment (CI_DEBUG is false).
**Checklist:**
> fix: remove CI_DEBUG check in Model

- tests/system/Commands/Database/ShowTableInfoTest.php
When the migrations table has already recorded numerous migrations, there's a tendency that the id would be longer. The existing expected pattern only anticipates migrations run for the first time. However, repeated testing on local would accumulate the migration records. This PR instead resorted to regex matching.
Example failing message:
```console
3) CodeIgniter\Commands\Database\ShowTableInfoTest::testDbTable
Failed asserting that 'Data of Table "db_migrations":\n
\n
+-----+----------------+--------------------+-------+---------------+------------+-------+\n
| id  | version        | class              | group | namespace     | time       | batch |\n
+-----+----------------+--------------------+-------+---------------+------------+-------+\n
| 209 | 20160428212500 | …
```
> Fix ShowTableInfoTest when migration records are numerous

- deptrac.yaml
- system/Files/File.php
- system/HTTP/ResponseTrait.php
- system/Images/Handlers/ImageMagickHandler.php
- system/Security/Security.php
- system/Throttle/Throttler.php
> refactor: changes `time()` to `Time` class in `Throttle`, `ResponseTrait`, `Security` and `ImageMagickHandler`

- system/Database/BaseBuilder.php
- tests/system/Models/DeleteModelTest.php
- fix broken test
- add test case
**Checklist:**
> test: fix DeleteModelTest

- admin/starter/tests/database/ExampleDatabaseTest.php
To prevent PHPStan from reporting errors.
**Checklist:**
> test: add `@var` in ExampleDatabaseTest

- system/Database/BaseConnection.php
- tests/system/Database/Live/MetadataTest.php
> Improve testing for `MetadataTest`

- system/CLI/GeneratorTrait.php
- system/Commands/Generators/CellGenerator.php
- system/Commands/Generators/Views/cell.tpl.php
- system/Commands/Generators/Views/cell_view.tpl.php
- tests/system/Commands/CellGeneratorTest.php
- user_guide_src/source/outgoing/view_cells.rst
Provides a new `make:cell` command to generate a controlled cell and its accompanying view. 
This includes a refactor on the GeneratorTrait to split out file creation to `generateClass` and `generateView`. The first working much like the existing `execute()` method which has been refactored to use the `generateClass` method.
> new make:cell command 

- tests/system/Commands/CreateDatabaseTest.php
The last test would leave the `foobar` database not dropped.
Follow up to #6856 and #6858 
**Checklist:**
> Fix CreateDatabaseTest to not leave database

- system/Database/BaseBuilder.php
- tests/system/Database/Live/UpdateTest.php
- user_guide_src/source/database/query_builder.rst
- user_guide_src/source/database/query_builder/092.php
- user_guide_src/source/database/query_builder/110.php
Since there is not yet a consensus to make this method a public API, it will be disabled when v4.3.0 is released.
See https://github.com/codeigniter4/CodeIgniter4/pull/6734#discussion_r1013700177
**Checklist:**
> feat: disable BaseBuilder::setAlias()

- system/ComposerScripts.php
Fixes #6832
Exit the function recursiveDelete() if the folder to delete didn't exist.
Fixes #6832 
**Checklist:**
- [?] Component(s) with PHPDoc blocks, only if necessary or adds value
- [?] Unit testing, with >80% coverage
- [?] User guide updated
- [?] Conforms to style guide
> fix: `composer update` might cause error "Failed to open directory"

- .github/workflows/test-phpcpd.yml
- system/Database/BaseBuilder.php
- system/Database/OCI8/Builder.php
- system/Database/Postgre/Builder.php
- system/Database/SQLite3/Builder.php
- tests/system/Database/Live/DeleteTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/database/query_builder.rst
- user_guide_src/source/database/query_builder/118.php
~~Needs #6741~~
The *Batch() saga continues..
This adds deleteBatch() to Builder. This allows using a set of data to selectively delete items from a table.
```php
$data = [
['userid' => 1, 'username' => 'Derek Does Not Match', 'unused' => 'You can have fields you dont use'],
['userid' => 2, 'username' => 'Ahmadinejad', 'unused' => 'You can have fields you dont use'],
];
$this->db->table('user')
->setData($data)
->onConstraint(['id' => 'userid', 'name' => 'username'])
->deleteBatch();
$this->seeInDatabase('user', ['email' => 'derek@world.com', 'name' => 'Derek Jones']);
$this->dontSeeInDatabase('user', ['email' => 'ahmadinejad@world.com', 'name' => 'Ahmadinejad']);
```
You can also use where() for additional conditions except with SQLite.
**Checklist:**
> Add BaseBuilder::deleteBatch()

- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/testing/controllers.rst
- fix Config file paths
**Checklist:**
> docs: fix Config file paths

- user_guide_src/source/incoming/incomingrequest.rst
- user_guide_src/source/incoming/incomingrequest/022.php
- add notes
- add text decoration
**Checklist:**
> docs: improve incomingrequest.rst

- README.md
- add PHPStan badge
Related: #6828
**Checklist:**
> docs: add PHPStan badge in README

- README.md
- admin/framework/README.md
- admin/framework/composer.json
- admin/starter/README.md
- composer.json
- system/CodeIgniter.php
- user_guide_src/source/intro/requirements.rst
- update the docs
- remove `curl` and `xml` from required PHP extension check in `CodeIgniter`
**Checklist:**
> fix: required PHP extentions

- system/CLI/CLI.php
- system/Common.php
- tests/system/CLI/CLITest.php
- tests/system/Commands/GeneratorsTest.php
- tests/system/CommonFunctionsTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/general/common_functions/012.php
- Adds `is_windows()` global function, for uniform detection of Windows platform
- Deprecate `CLI::isWindows()`, as platform detection is not limited to console
- Normalize platform detection
Related: #6882 
**Checklist:**
> Add `is_windows()` global function

- contributing/pull_request.md
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/installation/upgrade_430.rst
- add Config content changes in upgrade_430
**Checklist:**
> docs: improve upgrade_430 and changelog

- app/Views/welcome_message.php
- system/Debug/Toolbar.php
- system/Debug/Toolbar/Views/toolbar.tpl.php
- system/Email/Email.php
- system/Typography/Typography.php
- system/View/Filters.php
- tests/system/Helpers/URLHelper/MiscUrlTest.php
- tests/system/Typography/TypographyTest.php
- tests/system/View/ParserFilterTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- remove trailing slash on void elements
- remove unnecessary type attributes
- `Typography` uses `Config\DocTypes::$html5` for `<br>` tag
Ref: #6298, #6789
**Checklist:**
> fix: HTML output

- .github/workflows/reusable-coveralls.yml
- .github/workflows/reusable-phpunit-test.yml
- .github/workflows/reusable-serviceless-phpunit-test.yml
- .github/workflows/test-autoreview.yml
- .github/workflows/test-phpunit.yml
Ref:
- https://docs.github.com/en/actions/using-workflows/reusing-workflows
- https://docs.github.com/en/actions/learn-github-actions/expressions
Noted limitations:
- Service containers cannot be extracted to caller workflows
- Environment variables (`env` context) cannot be propagated from caller workflow to callee workflow
- `env` context is not available as part of inputs in `with:`
**Checklist:**
> Convert PHPUnit tests to use reusable workflows

- user_guide_src/source/general/logging.rst
- user_guide_src/source/installation/troubleshooting.rst
- user_guide_src/source/installation/troubleshooting/002.php
> docs: improve troubleshooting.rst

- app/Config/Validation.php
- user_guide_src/source/installation/upgrade_430.rst
- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/libraries/validation/003.php
Change the default Validation rules.
- The Traditional Rules cannot validate some non-string data correctly, or raise TypeError  #6489
- The controller `validate()` method validates JSON data automatically if a JSON request comes.
- This Config change is opt-in. The existing apps do not change.
**Checklist:**
> config: use Strict Validation Rules by default

- user_guide_src/source/database/transactions.rst
Fixes #6916
- fix old wrong description
- improve "Managing Errors" explanation 
Related: #6917, #6886, #6912
**Checklist:**
> docs: fix transactions.rst

- system/HTTP/Header.php
- tests/system/HTTP/HeaderTest.php
Follow-up: #6870
- fix PHPDoc in Header
**Checklist:**
> docs: fix PHPDoc in Header

- user_guide_src/source/concepts/mvc.rst
Use lower case for view file path example. It is our convention.
**Checklist:**
> docs: use lower case for view file path

- user_guide_src/source/installation/installing_composer.rst
- user_guide_src/source/installation/installing_manual.rst
It is not only the configuration files that are changed.
**Checklist:**
> docs: fix Cons in installing

- composer.json
- system/Cookie/Cookie.php
- system/Database/BaseConnection.php
- system/Database/Postgre/Connection.php
- system/Files/FileCollection.php
- system/Test/Mock/MockConnection.php
- system/Test/Mock/MockResult.php
- update psalm
https://github.com/vimeo/psalm/releases/tag/5.0.0
**Checklist:**
> chore: update psalm to 5.0

- user_guide_src/source/tutorial/create_news_items/004.php
- user_guide_src/source/tutorial/news_section.rst
- user_guide_src/source/tutorial/news_section/004.php
- user_guide_src/source/tutorial/news_section/006.php
- user_guide_src/source/tutorial/news_section/008.php
- user_guide_src/source/tutorial/static_pages.rst
- user_guide_src/source/tutorial/static_pages/002.php
- user_guide_src/source/tutorial/static_pages/004.php
Follow-up: #6900
- update the code
**Checklist:**
> docs: refactor Tutorial code

- user_guide_src/source/database/configuration.rst
strictOn is MySQLi only.
**Checklist:**
> docs: DB Config `strictOn` is MySQLi only

- tests/system/Database/Live/TransactionTest.php
This is tests for v4.2.
Related #6919, #6886
See https://github.com/codeigniter4/CodeIgniter4/actions/runs/3555886311/jobs/5972871727 to see Exception classes.
The current behaviors:
- All the current DB drivers throw an exception when a query error occurs.
- MySQLi driver sets `mysqli_report(MYSQLI_REPORT_ALL & ~MYSQLI_REPORT_INDEX)` that throws `mysqli_sql_exception`.
- SQLite3, Postgres and OCI8 drivers throw `ErrorException` because of Error Handler. 
- SQLSRV driver has different implementaion. It throws `Exception` when the query return value is false.
**Checklist:**
> test: add DB transaction tests

- user_guide_src/source/changelogs/v4.2.0.rst
Follow-up #6940
`foreignKeys` is not a property but an array key.
**Checklist:**
> docs: fix about foreignKeys in changelog

- app/Config/Database.php
- system/Database/SQLite3/Connection.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/database/configuration.rst
See #6930
- add a new Config `busyTimeout`
**Checklist:**
> feat: add SQLite3 Config busyTimeout

- user_guide_src/source/installation/upgrade_security/ci3sample/002.php
- user_guide_src/source/libraries/caching/001.php
- user_guide_src/source/libraries/email/022.php
- user_guide_src/source/libraries/uploaded_files/001.php
HTML5 compatible.
**Checklist:**
> docs: remove `/` before right `>` in void HTML elements

- user_guide_src/source/tutorial/create_news_items/004.php
- user_guide_src/source/tutorial/news_section/008.php
- user_guide_src/source/tutorial/static_pages.rst
- user_guide_src/source/tutorial/static_pages/004.php
See #6957
- replace `(:any)` with `(:segment)`
**Checklist:**
> docs: fix tutorial placeholder `(:any)`

- system/API/ResponseTrait.php
- system/Common.php
- system/Config/Factories.php
- system/Database/Database.php
- system/Debug/Timer.php
- system/Email/Email.php
- system/HTTP/IncomingRequest.php
- system/HTTP/Request.php
- system/HTTP/URI.php
- system/Helpers/url_helper.php
- system/Model.php
- tests/system/CommonSingleServiceTest.php
> docs: fix phpdoc types

- system/Test/FeatureTestTrait.php
Replaces #6958 
When using a custom extension of the IncomingRequest class, running Feature tests would fail with a TypeError. The problem is that FeatureTestTrait would directly create an instance of the framework's IncomingRequest instead of grabbing it from the Services class.
This changes that to use it from the Service class instead.
> Use Services for the FeatureTestTrait request.

- system/BaseModel.php
- system/Config/Services.php
- system/Model.php
- tests/system/Models/DeleteModelTest.php
- tests/system/Models/UpdateModelTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/installation/upgrade_430.rst
- user_guide_src/source/models/model.rst
It is not necessary that the `update()` method be able to update all records without WHERE clause. Updating all records is a risky operation and should not be mixed with update method with id(s). 
The current API is not good design because it is easily to create a vulnerability that allows all records to be updated if you accidentally forget to validate the `$id`. See https://forum.codeigniter.com/showthread.php?tid=84833
- [BC] disallow `Model::update()` without WHERE clause (throws Exception).
- disallow `$id` as bool for `update()`/`delete()` (throws Exception).
- ~~add `Model::updateAll($data)` for UPDATE without WHERE clause.~~
- add tests for `Model::detete()`. DELETE without WHERE clause is already not allowed.
**Checklist:**
> feat: disallow `Model::update()` without WHERE clause

- tests/system/Database/Live/TransactionTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/database/transactions.rst
- user_guide_src/source/database/transactions/001.php
- user_guide_src/source/database/transactions/003.php
- user_guide_src/source/database/transactions/006.php
- user_guide_src/source/database/transactions/008.php
~~Needs #6919~~
- update docs
- ~~fix out of dated description. See https://github.com/bcit-ci/CodeIgniter/issues/4032~~
- add tests
**Checklist:**
> docs: update DB transactions

- tests/system/Database/Live/TransactionTest.php
This PR fixes a `TransactionTest::testTransStartDBDebugTrue()`.
**Checklist:**
> fix: transaction exception test

- system/Autoloader/FileLocator.php
- tests/system/Autoloader/FileLocatorTest.php
- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.2.11.rst
There is a bug in `FileLocator::locateFile()` when two namespaces are very similar.
Example:
```php
// app/Config/Autoload.php
public $psr4 = [
APP_NAMESPACE => APPPATH, // For custom app namespace
'Config'      => APPPATH . 'Config',
'Acme\ProjectNameDemo' => APPPATH . 'Modules/project-name-demo',
'Acme\ProjectName' => APPPATH . 'Modules/project-name',
];
// app/Config/Routes.php
$routes->get('demo', static function () {
return view('Acme\ProjectNameDemo\Views\home');
});
```
In this scenario, the `FileLocator` will try to load a file from the namespace `Acme\ProjectName`.
If we switch the order of the `Acme` namespace in `Autoload.php`, then everything will work fine.
Bug proof of concept: https://github.com/michalsn/ci-filelocator-bug/commit/183d087ab36839ffb0cc8950e5a22 …
> fix: FileLocator::locateFile() bug with a similar namespace name

- system/HTTP/IncomingRequest.php
- tests/system/HTTP/IncomingRequestTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/incoming/incomingrequest.rst
- user_guide_src/source/incoming/incomingrequest/039.php
Working with raw input data should be as easy as in other cases. `getRawInputVar()` adds missing features that are available for other methods, like retrieving specified indexes and filtering data.
**Checklist:**
> feat: add IncomingRequest::getRawInputVar() method

- system/HTTP/IncomingRequest.php
- tests/system/HTTP/IncomingRequestTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
Fixes #6878
Current behavior is inconsistence.
1. `getVar(null)` will call `getJSON()` which will return all the data without filtering.
2. `getVar('index')` will be filtered, but... it seems like `getJsonVar()` doesn't perform filtering on nested values (arrays, objects), only on single variables.
This is very problematic:
* some variables may not be filtered at all (arrays etc.), even if we set a proper flag - it will be ignored
* if we call a single variable, it will be converted to a string due to the nature of the `filter_var()` function
* basically, we can get different variable types depending on how we ask for them
I targeted this PR to 4.3 because I'm changing the parameter signature in one method. This will make the code more consistent, and the functionality …
> fix: don't change the variable type and filter all values in JSON request

- system/Validation/Validation.php
- tests/system/Validation/ValidationTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/libraries/validation/003.php
- user_guide_src/source/libraries/validation/033.php
- user_guide_src/source/libraries/validation/040.php
- user_guide_src/source/libraries/validation/041.php
- add closure validation rule
1.
```php
$this->validation->setRules(
[
'foo' => ['required', static fn ($value) => $value === 'abc'],
],
[
// Errors
'foo' => [
// Specify the array key for the closure rule.
1 => 'The value is not "abc"',
],
],
);
```
2.
```php
$this->validation->setRules([
'foo' => [
'required',
static function ($value, $data, &$error, $field) {
if ($value !== 'abc') {
$error = 'The ' . $field . ' value is not "abc"';
return false;
}
return true;
},
],
]);
```
**Checklist:**
> feat: add closure validation rule

- user_guide_src/source/database/query_builder.rst
> docs: fix typos in query_builder.rst

- tests/system/Models/InsertModelTest.php
Fixes https://github.com/codeigniter4/CodeIgniter4/issues/6915
**Checklist:**
> Fix testInsertWithSetAndEscape to make not time dependent

- system/Commands/Server/rewrite.php
- remove unnecessary global variables
**Checklist:**
> fix: remove unnecessary global variables in rewrite.php

- system/CLI/CLI.php
Fix PHPStan notice on PHPStan 1.9.3:
```bash
Run vendor/bin/phpstan analyse
Note: Using configuration file /home/runner/work/CodeIgniter4/CodeIgniter4/phpstan.neon.dist.
0/434 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
360/434 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░]  82%
434/434 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
Error: Variable $cols in isset() always exists and is not nullable.
------ -------------------------------------------------------------- 
Line   system/CLI/CLI.php                                            
------ -------------------------------------------------------------- 
985    Variable $cols in isset() always exists and is not nullable.  
```
Ref https://github.com/codeigniter4/CodeIgniter4/actions/runs/3686745072/jobs/6239400007#step:11:15
**Checklist:**
> [PHPStan] Fix PHPStan notice on PHPStan 1.9.3

- app/Config/Autoload.php
- phpstan-baseline.neon.dist
- system/Autoloader/Autoloader.php
- system/Commands/Utilities/Namespaces.php
- system/Config/AutoloadConfig.php
Autoloader supports a psr4 namespace with multiple paths.
See https://github.com/codeigniter4/CodeIgniter4/blob/ce64c72c06fe5a45c2ba56dfcbae2f7837447901/tests/system/Autoloader/AutoloaderTest.php#L149
But `spark namespaces` cannot show it.
```diff
--- a/app/Config/Autoload.php
+++ b/app/Config/Autoload.php
@@ -43,6 +43,7 @@ class Autoload extends AutoloadConfig
public $psr4 = [
APP_NAMESPACE => APPPATH, // For custom app namespace
'Config'      => APPPATH . 'Config',
+        'Test'        => [ROOTPATH . 'modules/Test/src', ROOTPATH . 'modules/Test/tests'],
];
/**
```
Before:
```
[TypeError]
realpath(): Argument #1 ($path) must be of type string, array given
at SYSTEMPATH/Commands/Utilities/Namespaces.php:78
Backtrace:
1    SYSTEMPATH/Commands/Utilities/Namespaces.php:78 …
```
> fix: `spark namespaces` cannot show a namespace with mutilple paths

- composer.json
- rector.php
- tests/system/ControllerTest.php
- tests/system/View/DecoratorsTest.php
@kenjis @paulbalandan Rector 0.15.1 just released and we can re-enable `TypedPropertyFromAssignsRector` that was buggy on `union mixed type, new class extends SomeClass marked as object in union, and false replaced with bool in Union` which currently resolved.
**Checklist:**
> [Rector] Update to Rector 0.15.1 and re-enable TypedPropertyFromAssignsRector

- rector.php
~~I forgot to add it when merging.~~
Remove the line that was removed in `develop`.
It should be removed when merging, but maybe I did something wrong when resolving conflicts.
**Checklist:**
> [4.3] fix: merge mistake for rector.php

- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/installation/upgrade_430.rst
- add highlights
- add missing items
**Checklist:**
> docs: update changelogs 4.3.0

- system/Debug/Exceptions.php
Reported at https://forum.codeigniter.com/showthread.php?tid=85882
- `VENDORPATH` may not defined.
**Checklist:**
> fix: Undefined constant "CodeIgniter\Debug\VENDORPATH"

- system/Debug/Exceptions.php
See #6758
See https://github.com/FakerPHP/Faker/releases/tag/v1.21.0
**Checklist:**
> refactor: remove Workaround for Faker deprecation errors in PHP 8.2

- system/CLI/CLI.php
```
------ --------------------------------------
Line   system\CLI\CLI.php
------ --------------------------------------
:987   Variable $cols might not be defined.
------ --------------------------------------
```
**Checklist:**
> fix: `PHPStan` $cols not defined in `CLI`

- system/Commands/Server/rewrite.php
This PR fixes an issue where an url has an empty path segment and a non-trailing slash ending. 
```
Deprecated: urldecode(): Passing null to parameter #1 ($string) of type string is deprecated in P:\Bug\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php on line 28
```
Instead, what we'll do is pass an empty string if that happens. Since the url couldn't be parsed, we give an empty string, which is an url that will definitely not exist (root is /) and it will properly show the **404 page**.
**PHP: 8.1.5**
see: http://localhost:8080//any
**Checklist:**
> fix: empty paths for `rewrite.php`

- app/Config/App.php
- app/Config/Session.php
- env
- system/Commands/Generators/MigrationGenerator.php
- system/Session/Handlers/BaseHandler.php
- system/Session/Handlers/DatabaseHandler.php
- system/Session/Handlers/FileHandler.php
- system/Session/Handlers/MemcachedHandler.php
- system/Session/Handlers/RedisHandler.php
- system/Session/Session.php
- tests/system/Session/Handlers/Database/AbstractHandlerTestCase.php
- tests/system/Session/Handlers/Database/MySQLiHandlerTest.php
- tests/system/Session/Handlers/Database/PostgreHandlerTest.php
- tests/system/Session/Handlers/Database/RedisHandlerTest.php
- tests/system/Session/SessionTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/installation/upgrade_430.rst
- user_guide_src/source/libraries/sessions.rst
- user_guide_src/source/libraries/sessions/039.php
- user_guide_src/source/libraries/sessions/040.php
- user_guide_src/source/libraries/sessions/041.php
- user_guide_src/source/libraries/sessions/042.php
- user_guide_src/source/libraries/sessions/043.php
- add Config\Session
Related: https://github.com/codeigniter4/CodeIgniter4/issues/4297#issuecomment-813110373
**Checklist:**
> refactor: add Config\Session

- system/Database/BaseBuilder.php
- tests/system/Database/Builder/WhereTest.php
Fixes #4347
- no longer use `getOperator()` in `where()`
**Checklist:**
> fix: BaseBuilder::getOperator() doesn't recognize LIKE operator in array expression

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.2.11.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_4211.rst
- user_guide_src/source/installation/upgrading.rst
Updates changelog and version references for 4.2.11.
**Checklist:**
> Prep for 4.2.11 release

- admin/framework/composer.json
- composer.json
This is a temporary situation.
See https://github.com/codeigniter4/CodeIgniter4/pull/6990#issuecomment-1359261950
**Checklist:**
> chore: fix php-cs-fixer version to 3.13.0

- system/Language/Language.php
```
ERROR: TooFewArguments - system/Language/Language.php:255:24 - Too few arguments for array_replace_recursive - expecting array to be passed (see https://psalm.dev/025)
$strings = array_replace_recursive(...$strings);
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/3745997494/jobs/6360957133
See https://www.php.net/manual/en/function.array-replace-recursive.php
**Checklist:**
> refactor: to fix psalm error

- system/HTTP/RequestTrait.php
```diff
1 file with changes
===================
1) system/HTTP/RequestTrait.php:63
@@ @@
*/
// @phpstan-ignore-next-line
$proxyIPs = $this->proxyIPs ?? config('App')->proxyIPs;
-        if (! empty($proxyIPs)) {
-            // @phpstan-ignore-next-line
-            if (! is_array($proxyIPs) || is_int(array_key_first($proxyIPs))) {
-                throw new ConfigException(
-                    'You must set an array with Proxy IP address key and HTTP header name value in Config\App::$proxyIPs.'
-                );
-            }
+        // @phpstan-ignore-next-line
+        if (! empty($proxyIPs) && (! is_array($proxyIPs) || is_int(array_key_first($proxyIPs)))) {
+            throw new ConfigException(
+                'You must set an …
```
> refactor: RequestTrait by rector

- tests/_support/Database/Seeds/CITestSeeder.php
- tests/system/Session/Handlers/Database/AbstractHandlerTestCase.php
```
There was 1 error:
1) CodeIgniter\Session\Handlers\Database\MySQLiHandlerTest::testWriteInsert
ErrorException: Trying to get property 'timestamp' of non-object
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Session/Handlers/Database/AbstractHandlerTestCase.php:82
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:97
--
There were 2 failures:
1) CodeIgniter\Session\Handlers\Database\MySQLiHandlerTest::testReadSuccess
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'__ci_last_regenerate|i:1624650854;_ci_previous_url|s:40:\"http://localhost/index.php/home/index\";'
+''
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Session/Handlers/Database/AbstractHandlerTestCase.php:52 …
```
> test: update failed DB session tests

- app/Config/App.php
- system/Test/Mock/MockAppConfig.php
- system/Test/Mock/MockCLIConfig.php
- tests/system/HTTP/IncomingRequestTest.php
- user_guide_src/source/installation/troubleshooting/001.php
- user_guide_src/source/installation/troubleshooting/002.php
- user_guide_src/source/installation/upgrade_localization/001.php
- user_guide_src/source/outgoing/localization/001.php
- user_guide_src/source/outgoing/localization/002.php
- user_guide_src/source/outgoing/localization/003.php
- user_guide_src/source/outgoing/response/011.php
All atomic type properties in Config classes have been typed in 4.3.
**Checklist:**
> fix: Config property type

- app/Controllers/BaseController.php
Declared session property in the BaseController to avoid the depreciation of dynamic properties in PHP 8.2
> Declared session in BaseController to avoid Creation of dynamic property in php 8.2

- system/HTTP/CLIRequest.php
- system/HTTP/IncomingRequest.php
- tests/system/HTTP/CLIRequestTest.php
- tests/system/HTTP/IncomingRequestTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/incoming/incomingrequest.rst
- user_guide_src/source/incoming/incomingrequest/040.php
Writing code like `strtolower($this->request->getMethod()) !== 'post'` is a pain.
- add `IncomingRequest::is()`
```php
$request->is('get')
$request->is('post')
$request->is('put')
$request->is('delete')
$request->is('head')
$request->is('patch')
$request->is('options')
$request->is('json')
$request->is('ajax')
```
**Checklist:**
> feat: add IncomingRequest::is() method

- user_guide_src/source/installation/upgrade_405.rst
> docs: fix upgrade_405.rst

- .github/workflows/test-deptrac.yml
I'm not sure this really works.
- set GITHUB_AUTH_TOKEN for phive. See https://github.com/phar-io/phive/issues/127#issuecomment-354552572
```
Run sudo phive --no-progress install --global qossmic/deptrac --trust-gpg-keys B8F640134AB1782E
Phive 0.15.2 - Copyright (C) 2015-2022 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/rate_limit
Warning:  Github API Rate Limit exceeded - cannot resolve "qossmic/deptrac"
Downloading https://gitlab.com/api/v4/projects/qossmic%2Fdeptrac/releases/
Fetching repository list
Downloading https://phar.io/data/repositories.xml
Error:    Could not resolve requested PHAR qossmic/deptrac
Error: Process completed with exit code 4.
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/3768833313/jobs/640 …
> chore: update test-deptrac.yml (Github API Rate Limit)

- user_guide_src/source/tutorial/create_news_items.rst
- user_guide_src/source/tutorial/create_news_items/002.php
- refactor the sample code
**Checklist:**
> docs: update tutorial

- system/Cache/CacheInterface.php
- system/Cache/Handlers/BaseHandler.php
See #6310 
It seems the return types of `increment` and `decrement` functions is int or bool, so I only leave the `bool|int` at that two functions.
And wish you all a merry Christmas!
**Checklist:**
> docs: replace types `mixed` in `CacheInterface` and `BaseHandler` file.

- user_guide_src/source/_static/css/citheme.css
- add background color for versionadded and deprecated
**Checklist:**
> docs: add background color for versionadded and deprecated

- system/Helpers/html_helper.php
- tests/system/Helpers/HTMLHelperTest.php
Follow-up #3247
From https://forum.codeigniter.com/showthread.php?tid=85954
```php
link_tag('feed', 'alternate', 'application/rss+xml', 'My RSS Feed');
```
```
Expected :'<link href="http://example.com/feed" rel="alternate" type="application/rss+xml" title="My RSS Feed" />'
Actual   :'<link href="http://example.com/feed" rel="alternate" title="My RSS Feed" />'
```
`alternate` may use `type` attribute.
See https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types
**Checklist:**
> fix: `link_tag()` missing `type="application/rss+xml"`

- user_guide_src/source/general/helpers.rst
- add note for case sensitive file system and namespace
See https://forum.codeigniter.com/showthread.php?tid=85977
**Checklist:**
> docs: improve helpers.rst

- user_guide_src/source/cli/cli_commands.rst
- user_guide_src/source/cli/cli_commands/001.php
- user_guide_src/source/cli/cli_generators.rst
`migrate:create` is deprecated.
**Checklist:**
> docs: update deprecated `migrate:create` examples

- user_guide_src/source/installation/upgrade_database.rst
- add about DB caching. 
CI4 does not have DB caching. See #3608
**Checklist:**
> docs: fix upgrade_database.rst

- system/Database/MigrationRunner.php
- tests/system/Database/Migrations/MigrationRunnerTest.php
See https://github.com/codeigniter4/CodeIgniter4/pull/7033#discussion_r1058721974
```console
+-----------+-------------------+-------------------------+-------+-------------+-------+
| Namespace | Version           | Filename                | Group | Migrated On | Batch |
+-----------+-------------------+-------------------------+-------+-------------+-------+
| App       | 2022_12_29_050744 | 12_29_050744_KenjisTest | ---   | ---         | ---   |
| App       | 2022_12_29_050800 | 12_29_050800_PooyaTest  | ---   | ---         | ---   |
+-----------+-------------------+-------------------------+-------+-------------+-------+
```
**Checklist:**
> fix: `spark migrate:status` shows incorrect filename when format is `Y_m_d_His_`

- system/Model.php
- tests/system/Models/SaveModelTest.php
> fix: save object when useAutoIncrement is disabled

- .github/workflows/deploy-apidocs.yml
- .github/workflows/deploy-distributables.yml
- .github/workflows/deploy-userguide-latest.yml
- .github/workflows/test-autoreview.yml
- .github/workflows/test-coding-standards.yml
- .github/workflows/test-deptrac.yml
- .github/workflows/test-phpcpd.yml
- .github/workflows/test-phpstan.yml
- .github/workflows/test-phpunit.yml
- .github/workflows/test-rector.yml
- .github/workflows/test-scss.yml
- .github/workflows/test-userguide.yml
Ref: twbs/bootstrap#36325 PHP-CS-Fixer/PHP-CS-Fixer#6644
**Checklist:**
> chore: secure workflows permission

- app/Config/Honeypot.php
- system/Honeypot/Honeypot.php
- tests/system/Honeypot/HoneypotTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/installation/upgrade_430.rst
- user_guide_src/source/libraries/honeypot.rst
- user_guide_src/source/libraries/honeypot/001.php
From https://forum.codeigniter.com/showthread.php?tid=85960
- fix bug
- add `Config\Honeypot::$containerId`
```diff
diff --git a/app/Config/App.php b/app/Config/App.php
index 0a23462b6..e8f314371 100644
@@ -446,5 +446,5 @@ class App extends BaseConfig
* @see http://www.html5rocks.com/en/tutorials/security/content-security-policy/
* @see http://www.w3.org/TR/CSP/
*/
-    public bool $CSPEnabled = false;
+    public bool $CSPEnabled = true;
}
diff --git a/app/Config/Filters.php b/app/Config/Filters.php
index 7b70c4fb3..12bb9619c 100644
--- a/app/Config/Filters.php
+++ b/app/Config/Filters.php
@@ -29,13 +29,13 @@ class Filters extends BaseConfig
*/
public array $globals = [
'before' => [
-            // 'honeypot',
+ …
```
> fix: Honeypot field appears when CSP is enabled

- app/Config/Cache.php
- system/Encryption/Encryption.php
- system/Test/Interfaces/FabricatorModel.php
I fix another file use `boolean` too.
Fixed #7048
**Checklist:**
> docs: fix boolean type to follow PSR-5

- system/CLI/CLI.php
In development and also in production environment where composer dependencies are installed without `--no-dev` composer flag we can have an issue with running commands from Controller with `command()` helper. 
Issue is there because of **Psalm** required package `amphp/byte-stream` in 
[functions.php](https://github.com/amphp/byte-stream/blob/b5a09a3abd7a638ca4cadcf0876ce0ccd8d911d3/src/functions.php#L15-L17)
Psalm is often installed with [devkit](https://github.com/codeigniter4/devkit), so we need to check if `STDOUT` is already defined.
Fixes #7047
**Checklist:**
> fix: define of STDOUT in CLI init() method

- system/Events/Events.php
- tests/system/Events/EventsTest.php
Fixes #7045
But I have a question is does the `$this->manager` still be needed in the test case of `test\system\Events\EventsTest.php` file?
Because all the functions in Event class are static, does it mean that this class no longer needs to be constructed?
**Checklist:**
> fix: change `getFile()` function of \CodeIgniter\Events\Events to static.

- system/ThirdParty/Kint/Parser/XmlPlugin.php
- system/ThirdParty/Kint/Zval/BlobValue.php
- system/ThirdParty/Kint/Zval/Representation/SplFileInfoRepresentation.php
- system/ThirdParty/Kint/init.php
- user_guide_src/source/changelogs/v4.3.0.rst
See https://github.com/kint-php/kint/releases/tag/5.0.2
- update Kint
**Checklist:**
> chore: update Kint to 5.0.2

- system/Email/Email.php
`[127.0.0.1]` is not valid domain parameter.
127.0.0.1 is a loopback address.
See https://forum.codeigniter.com/showthread.php?tid=84852
**Checklist:**
> fix: [Email] add fallback to use gethostname()

- user_guide_src/source/conf.py
> chore: update User Guide copyright year

- system/Router/Router.php
When legacy autoRoute is used in case of using controller that sits in sub directory, that directory is determined and stored in `$this->directory` and new AutoRouter class. But if we subsequently try to load controller without that is not in a directory, then codeigniter can't find it because the `$this->directory` var in AutoRoute instance is still holding reference to previous directory. This only happens when we load several controllers from console. In my case after upgrading to 4.2.11 my tests fail because of it.
I suggest to remove this return; statement to reset directory in AutoRoute instance also.
**Checklist:**
> Fixing bug with legacy autoRoute when testing

- system/Commands/Utilities/Routes.php
- tests/system/Commands/RoutesTest.php
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/incoming/routing.rst
Supersedes #6415
- add option `-h` to sort by handler
```console
$ php spark routes
CodeIgniter v4.2.11 Command Line Tool - Server Time: 2022-12-24 02:10:28 UTC+00:00
+--------+------------------------------+------+---------------------------------------------+----------------+---------------+
| Method | Route                        | Name | Handler                                     | Before Filters | After Filters |
+--------+------------------------------+------+---------------------------------------------+----------------+---------------+
| GET    | /                            | »    | \App\Controllers\Home::index                |                | toolbar       |
| GET    | bbs/index                    | »    | \App\Controllers\Bbs::index                 | …
```
> feat: `spark routes` option to sort by handler

- user_guide_src/source/libraries/validation.rst
Fix the expression of the validation rule "is_unique". There was a grammar error.
**Checklist:**
> docs: fix the expression of the validation rule "is_unique"

- app/Config/Email.php
- system/Email/Email.php
> fix: Email config in the .env doesn't appear as expected

- admin/next-changelog-minor.rst
- admin/next-changelog-patch.rst
- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.2.3.rst
- user_guide_src/source/changelogs/v4.2.5.rst
- user_guide_src/source/changelogs/v4.2.6.rst
- user_guide_src/source/changelogs/v4.2.7.rst
- user_guide_src/source/changelogs/v4.2.8.rst
- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/changelogs/v4.3.1.rst
- user_guide_src/source/installation/upgrade_430.rst
- add missing link to CHANGELOG.md
- add changelog v4.3.1
- remove empty secitons in the past changelog
**Checklist:**
> docs: update changelogs

- system/Validation/Rules.php
- system/Validation/StrictRules/Rules.php
- tests/system/Validation/DatabaseRelatedRulesTest.php
- tests/system/Validation/StrictRules/DatabaseRelatedRulesTest.php
See https://forum.codeigniter.com/showthread.php?tid=86107
- fix TypeError in `Rules::is_unique()` and `is_not_unique()` in Strict Rules
- refactor tests
- move the test logic to `StrictRules\DatabaseRelatedRulesTest` because Strict Rules are now default
**Checklist:**
> fix: TypeError in Validation is_unique/is_not_unique

- system/Database/BaseBuilder.php
- tests/system/Database/Builder/SelectTest.php
From https://forum.codeigniter.com/showthread.php?tid=86096&pid=405141#pid405141
**Checklist:**
> fix: revert method name changed accidentally

- phpstan-baseline.neon.dist
- update phpstan-baseline
```
Error: Ignored error pattern #^Variable \$data might not be defined\.$# in path /home/runner/work/CodeIgniter4/CodeIgniter4/system/Cache/Handlers/MemcachedHandler.php was not matched in reported errors.
------ ----------------------------------------------------------------------- 
Line   system/Cache/Handlers/MemcachedHandler.php                             
------ ----------------------------------------------------------------------- 
Ignored error pattern #^Variable \$data might not be defined\.$# in    
path                                                                   
/home/runner/work/CodeIgniter4/CodeIgniter4/system/Cache/Handlers/Mem  
cachedHandler.php was not matched in reported errors.                  
------ …
```
> chore: update phpstan-baseline for PHPStan 1.9.9

- tests/system/CommonFunctionsTest.php
- tests/system/Helpers/URLHelper/MiscUrlTest.php
- tests/system/Router/RouteCollectionReverseRouteTest.php
- tests/system/Router/RouteCollectionTest.php
- tests/system/View/ParserPluginTest.php
These tests are a misuse of (:any). They are not appropriate test code.
**Checklist:**
> test: add `@TODO` to incorrect `(:any)` usages

- system/Debug/Exceptions.php
- user_guide_src/source/installation/upgrade_430.rst
> docs: add missing instruction for Config/Exceptions in PHP 8.2

- user_guide_src/source/installation/upgrade_430.rst
Follow-up #7101
- we need to escape `\` withh `\`. See https://codeigniter4.github.io/CodeIgniter4/installation/upgrade_430.html#call-to-undefined-method-composerinstalledversions-getallrawdata
**Checklist:**
> docs: add missing backslashes

- phpstan-baseline.neon.dist
- rector.php
- system/Cache/Handlers/MemcachedHandler.php
- system/Commands/Generators/MigrationGenerator.php
- system/Commands/Generators/SessionMigrationGenerator.php
- system/Commands/Utilities/FilterCheck.php
- system/Database/BaseBuilder.php
- system/Database/SQLSRV/Connection.php
- system/Debug/Toolbar.php
- system/Debug/Toolbar/Collectors/Database.php
- system/Helpers/html_helper.php
- system/Helpers/url_helper.php
- system/Images/Handlers/ImageMagickHandler.php
- system/Model.php
- tests/system/Database/Live/MetadataTest.php
- tests/system/Validation/ValidationTest.php
`AddDefaultValueForUndefinedVariableRector` now already cover isset variable check, so I think it can be enabled.
**Checklist:**
> [Rector] Enable AddDefaultValueForUndefinedVariableRector

- user_guide_src/source/helpers/cookie_helper.rst
- user_guide_src/source/outgoing/response.rst
- 0 has a special meaning
**Checklist:**
> docs: add explanation for Cookie $expire is `0`

- user_guide_src/source/libraries/validation/030.php
check for empty $errors
now with the same content as 
https://github.com/codeigniter4/CodeIgniter4/blob/develop/user_guide_src/source/models/model/033.php
or is it better if we include the code-snippet here?
`.. literalinclude:: model/033.php`
> docs: update errors_list template

- system/Autoloader/Autoloader.php
- user_guide_src/source/installation/installing_composer.rst
- user_guide_src/source/installation/upgrade_430.rst
Fixes #7106
The depreacted `getRawData()` is not reliable. See https://github.com/composer/composer/commit/f5e6cc89cd8d45c99cff77ee80d0f324ada45686#diff-817f0ad18cf006ca7b25f23ddd362c0c8b5cdcbea91c4b92be8d86ba59af223aR210
So using it does not make sense.
**Checklist:**
> fix: Call to undefined method Composer\InstalledVersions::getAllRawData() error

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.3.1.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_431.rst
- user_guide_src/source/installation/upgrading.rst
Updates changelog and version references for 4.3.1.
**Checklist:**
> Prep for 4.3.1 release

- user_guide_src/source/libraries/official_packages.rst
This just changes the link in the user guide to Shield to link to the HTML docs instead of the GitHub repo.
> feat: link Shield to the HTML docs. [ci-skip]

- user_guide_src/source/outgoing/view_parser.rst
- user_guide_src/source/outgoing/view_parser/008.php
- user_guide_src/source/outgoing/view_parser/009.php
- user_guide_src/source/outgoing/view_parser/010.php
> docs: fix incorrect sample code in view_parser

- user_guide_src/source/changelogs/v4.3.0.rst
- user_guide_src/source/installation/upgrade_430.rst
Follow-up #7072
- add missing items
**Checklist:**
> docs: add missing items in upgrade_430.rst/v4.3.0.rst

- user_guide_src/source/general/modules.rst
- fix out of dated sample command
**Checklist:**
> docs: fix out of date sample command in modules.rst

- user_guide_src/source/libraries/security.rst
- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/libraries/validation/001.php
Follow-up #6995
- use Request::is() instead of getMethod()
**Checklist:**
> docs: use Request::is() instead of getMethod()

- user_guide_src/source/helpers/form_helper.rst
- fix XHTML void element tags
**Checklist:**
> docs: fix form_helper.rst

- public/.htaccess
Options All -Indexes causes a 500 Internal Server Error. (Apache on hostpoint.ch / interxion).
Without the -All it works fine.
I'm not sure about all the effects, but I think the -All is already handled in the Apache directive and has not to be in .htaccess
> fix: remove `All` from `Options All -Indexes` in .htaccess

- system/Test/FeatureTestTrait.php
Supersedes #7079
When I use FeatureTestTrait if I use `withBodyFormat('json')` function on one request all subsequent requests are sent with `content-type: application/json` even if their body format is not 'json'.
This bug started when I upgraded CI from 4.0.x to 4.2.11. After long investigation I think I found the source of the problem. On line 289 initialization of request has been changed to `Services::request($config, true)` so for each subsequent test request same instance is used. That's why if content-type on one request is set then all other requests are sent with this header. We need some reset mechanism.
**Checklist:**
> fix: bug on stuck content-type header in Feature Testing

- user_guide_src/source/changelogs/v4.0.4.rst
- add BREAKING section
- improvements for readability
**Checklist:**
> docs: fix changelogs v4.0.4

- user_guide_src/source/changelogs/v4.2.11.rst
- add support for PHP 8.2
See https://github.com/codeigniter4/CodeIgniter4/issues/6170#issuecomment-1312929443
The issue was closed on Nov 23, 2022, and PHP 8.2 was released on [08 Dec 2022](https://www.php.net/ChangeLog-8.php#PHP_8_2).
So I add this in v4.2.11 (December 21, 2022).
**Checklist:**
> docs: add support for PHP 8.2 in changelog

- admin/framework/.github/workflows/close-pull-request.yml
- admin/starter/.github/workflows/close-pull-request.yml
- admin/userguide/.github/workflows/close-pull-request.yml
fix #7141 
- Add permission
- use GitHub CLI
Tested: https://github.com/totoprayogo1916/github-playground/pull/3
**Checklist:**
> fix close-pull-request.yml failed

- system/Helpers/url_helper.php
- tests/system/Helpers/URLHelper/CurrentUrlTest.php
- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.3.2.rst
- user_guide_src/source/helpers/url_helper.rst
Fixes #7124
- remove the parameter `$relative` which does not work
**Checklist:**
> fix: remove parameter $relative in `uri_string()`

- system/Database/BaseBuilder.php
- tests/system/Database/Builder/WhereTest.php
This fixes some of the problems noted ~~here https://github.com/codeigniter4/CodeIgniter4/issues/7117~~ and here https://github.com/codeigniter4/CodeIgniter4/issues/7143
The following was failing before this fix:
```php
$sql = $this->db->table('auth_bearer')
->select('*')
->where('expires', new RawSql('DATE_ADD(NOW(), INTERVAL 2 HOUR)'))
->getCompiledSelect(true);
$expected = <<<'SQL'
SELECT *
FROM "auth_bearer"
WHERE "expires" = DATE_ADD(NOW(), INTERVAL 2 HOUR)
SQL;
$this->assertSame($expected, $sql);
```
Generated:
```
'SELECT *
FROM "auth_bearer"
WHERE DATE_ADD(NOW(), INTERVAL 2 HOUR)'
```
**Checklist:**
> Bug Fix: [QueryBuilder] where() generates incorrect SQL when using RawSql

- system/Database/BaseBuilder.php
- tests/system/Database/Builder/InsertTest.php
Fixes the issue https://github.com/codeigniter4/CodeIgniter4/issues/7143#issuecomment-1385258336
- Throws an exception
**Checklist:**
> fix: [QueryBuilder] RawSql passed to set() disappears without error

- system/Router/RouteCollection.php
- add PHPDoc types
- fix PHPDoc comment
- refactor
**Checklist:**
> refactor: add PHPDoc types in RouteCollection

- app/Config/Mimes.php
When using File Libraries,
`$file->getMimeType();` returns `null` in files with extension `.exe`
**Checklist:**
> add `application/vnd.microsoft.portable-executable` and `application/x-dosexec`

- system/View/Parser.php
- tests/system/View/ParserTest.php
From https://forum.codeigniter.com/showthread.php?tid=86155
- fix `!` does not work if delimiters are changed
**Checklist:**
> fix: [Parser] `!` does not work if delimiters are changed

- app/Views/errors/html/error_exception.php
- rector.php
Apply Rector run into `app/Views` as well.
**Checklist:**
> [Rector] Apply Rector to app/Views

- system/Common.php
- system/HTTP/IncomingRequest.php
- system/HTTP/URI.php
- system/Helpers/url_helper.php
- system/Router/RouteCollection.php
- system/Router/RouteCollectionInterface.php
- tests/system/Helpers/URLHelper/MiscUrlTest.php
- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/general/common_functions/009.php
- user_guide_src/source/general/common_functions/010.php
- user_guide_src/source/general/common_functions/011.php
- user_guide_src/source/general/urls.rst
- user_guide_src/source/helpers/url_helper.rst
- user_guide_src/source/helpers/url_helper/025.php
- user_guide_src/source/incoming/incomingrequest.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/incoming/routing/029.php
- user_guide_src/source/incoming/routing/030.php
- update PHPDoc
- update User Guide
- add test
**Checklist:**
> docs: improve route_to() and url_to()

- user_guide_src/source/libraries/sessions.rst
> docs: fix wrong header configure `MemcachedHandler` in `Session`

- system/Throttle/Throttler.php
- tests/system/Throttle/ThrottleTest.php
In one of my applications where I use `Throttler` I detected the `getTokenTime()` is already at the minimum of 1 seconds even if the token refresh rate is far from reached:
Example: 1 capacity, 3600 seconds -> After 10 minutes I expected 50 minutes to be left, but I was already at "1 second". Waiting another minute and executing the check, I was still at "1 second left".
This made me clear that the calculation for `Throttler::getTokenTime()` is still off, but the token value is calculated correctly after all, return `false` if `$token < 1`. This PR should fix that.
**Checklist:**
> Fix: Throttler token time calculation

- system/Database/BaseBuilder.php
- tests/system/Database/Builder/WhereTest.php
Follow-up #6986
Ref #7151, #7117
- fix `BaseBuilder::getOperatorFromWhereKey()` misses `EXISTS` or `BETWEEN`
**Checklist:**
> fix: [QueryBuilder] getOperatorFromWhereKey() misses EXISTS, BETWEEN

- admin/framework/composer.json
- admin/starter/composer.json
- tests/system/AutoReview/ComposerJsonTest.php
Both appstarter and framework are for CodeIgniter projects, and the configuration itmes to be added in this PR should be the same.
- add `config`
- remove `suggest` in appstarter
**Checklist:**
> chore: update admin/*/composer.json

- system/Commands/Utilities/Routes/AutoRouterImproved/ControllerMethodReader.php
- system/Router/AutoRouterImproved.php
- system/Router/Exceptions/MethodNotFoundException.php
- tests/_support/Controllers/Newautorouting.php
- tests/system/Commands/RoutesTest.php
- tests/system/Commands/Utilities/Routes/AutoRouterImproved/AutoRouteCollectorTest.php
- tests/system/Commands/Utilities/Routes/AutoRouterImproved/ControllerMethodReaderTest.php
- tests/system/Router/AutoRouterImprovedTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/incoming/controllers/024.php
If there is no method in the controller for the request URI, fallback to the default method.
E.g.:
`GET /product/15`
→ `Product::get15()` Method not found
→ `Product::getIndex($id = '')` Method found and run `getIndex('15')`
**Checklist:**
> feat: [Auto Routing Improved] fallback to default method

- user_guide_src/source/installation/upgrade_405.rst
- user_guide_src/source/installation/upgrade_412.rst
- user_guide_src/source/installation/upgrade_431.rst
Documentation problems
https://codeigniter.com/user_guide/installation/upgrade_405.html#message-getheader-s
In the line `Request[Interface]::getMethod(): The $upper parameter will be removed, use str_to_upper()`
The correct PHP function is `strtoupper()`
https://codeigniter.com/user_guide/installation/upgrade_412.html#baseconnection-query-return-values
In the line `Review any use of query() method and be assess whether the value might be boolean instead of Result object.`
The word "be" does not belong in the sentence.
https://codeigniter.com/user_guide/installation/upgrade_431.html#config
Based on the description below it `app/Config/Encryption.php` should be `app/Config/Email.php`
**Checklist:**
> Correcting documentation mistakes in upgrading from one version to another

- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/models/model.rst
- user_guide_src/source/models/model/001.php
- fix descriptions
- add descriptions
**Checklist:**
> docs: fix model() descriptions

- app/Config/App.php
CI4 doesn't guess the baseURL.
https://github.com/codeigniter4/CodeIgniter4/blob/ecef7f748df25a20f65bd2e2df26070fc3ebffdd/system/HTTP/IncomingRequest.php#L485
**Checklist:**
> docs: remove out-of-dated comment on Config\App::$baseURL

- user_guide_src/source/cli/spark_commands.rst
- add about `--help`
- add sub sections
- fix invalid command sample
**Checklist:**
> docs: improve spark_commands.rst

- system/Autoloader/Autoloader.php
Fixes https://github.com/codeigniter4/shield/issues/610
PHPStan invokes phar (`require 'phar://phpstan.phar/bin/phpstan';`).
In that case, `InstalledVersions::getAllRawData()[0]['versions']` does not contain correct data.
When I see `getInstalledPackages()`:
https://github.com/composer/composer/blob/50cded331ced9acb4e926be3dda1f74b86af2a3b/src/Composer/InstalledVersions.php#L46-L64
it seems better to use all items in the returned array.
**Checklist:**
> fix: Autoloader may not add Composer package's namespaces

- system/Common.php
From Slack and https://forum.codeigniter.com/showthread.php?tid=86511
If `real_path()` throws Exception, we cannot see the true backtrace. 
Before:
After:
Before:
```
CRITICAL - 2023-01-28 12:32:16 --> Uncaught ValueError: realpath(): Argument #1 ($path) must not contain any null bytes in /Users/kenji/work/codeigniter/official/CodeIgniter4/system/Common.php:94
Stack trace:
#0 /Users/kenji/work/codeigniter/official/CodeIgniter4/system/Common.php(94): realpath('\x13\x00#\xB6\t\xC5\xE6\xC9/C\xB4\xB5')
#1 /Users/kenji/work/codeigniter/official/CodeIgniter4/system/Debug/Exceptions.php(524): clean_path('\x13\x00#\xB6\t\xC5\xE6\xC9/C\xB4\xB5')
#2 [internal function]: CodeIgniter\Debug\Exceptions::CodeIgniter\Debug\{closure}('\x13\x00#\xB6\t\xC5\xE6\xC9/C\xB4\xB5')
#3 …
```
> fix: add try/catch to real_path() in clean_path()

- phpstan-baseline.neon.dist
- system/Debug/Toolbar/Collectors/Events.php
- system/Debug/Toolbar/Collectors/Views.php
- (1) fix: DebugBar initializes shared renderer instance
- (2) fix: Event collector does not collect Timeline data
(1) 
DebugBar initializes shared `renderer` instance.
The following code in a controller does not create a new instance with the view path.
```php
\Config\Services::renderer(__DIR__ . '/../Views');
```
(2)
After:
**Checklist:**
> fix: cannot create shared View instance when using debugbar

- system/Router/RouteCollection.php
- tests/system/Router/RouteCollectionTest.php
- fix logic
Before this PR, the following test fails. Because `array_merge()` overwrites handlers.
```php
public function testGetRegisteredControllersReturnsAllControllers()
{
$collection = $this->getCollector();
$collection->get('test', '\App\Controllers\HelloGet::get');
$collection->post('test', '\App\Controllers\HelloPost::post');
$collection->post('hello', '\App\Controllers\TestPost::hello');
$routes = $collection->getRegisteredControllers('*');
$expects = [
'\App\Controllers\HelloGet',
'\App\Controllers\HelloPost',
'\App\Controllers\TestPost',
];
$this->assertSame($expects, $routes);
}
```
**Checklist:**
> fix: RouteCollection::getRegisteredControllers() may not return all controllers

- system/Cache/Handlers/FileHandler.php
> docs: replace type mixed in the remaining cache class.

- system/Router/RouteCollection.php
From https://forum.codeigniter.com/showthread.php?tid=86264
HTTP_HOST do not exist in CLI, so routes for hostnames cannot currently be displayed by `spark routes`.
It is strange that `another.domain` is shown as preferred.
```php
$routes->get('/', 'Controller::default');
$routes->get('/', 'Controller::another', ['hostname' => 'another.domain']);
$routes->get('/', 'Controller::subdomain', ['subdomain' => 'subdomain']);
```
Before:
```
+--------+-------+------+--------------------------------------+----------------+---------------+
| Method | Route | Name | Handler                              | Before Filters | After Filters |
+--------+-------+------+--------------------------------------+----------------+---------------+
| GET    | /     | »    | …
```
> fix: `spark routes` shows incorrect hostname routes

- system/Helpers/url_helper.php
- tests/system/Helpers/URLHelper/SiteUrlTest.php
- user_guide_src/source/changelogs/v4.3.2.rst
- user_guide_src/source/helpers/url_helper.rst
- user_guide_src/source/installation/upgrade_432.rst
- user_guide_src/source/installation/upgrading.rst
Fixes #7184
`base_url()` without arguments returns `http://localhost:8080`, not `http://localhost:8080/`.
The baseURL should have trailing slash, and there is no reason to remove it.
CI3's `base_url()` returns the URL with trailing slash.
**Checklist:**
> fix: base_url() removes trailing slash in baseURL

- admin/framework/composer.json
- user_guide_src/source/installation/upgrade_432.rst
If a dev has installed the Composer packages, they will be used. There is no need to update the source code in the `system/ThirdParty/` folder.
See https://github.com/codeigniter4/CodeIgniter4/pull/7170#issuecomment-1407811493
**Checklist:**
> chore: remove post-update-cmd in framework composer.json

- user_guide_src/source/installation/backward_compatibility_notes.rst
Supersedes #7021
See https://github.com/codeigniter4/CodeIgniter4/pull/7000#issuecomment-1364524729
- update `backward_compatibility_notes.rst`
**Checklist:**
> docs: add about removal of deprecated Config items

- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/libraries/validation/034.php
- user_guide_src/source/libraries/validation/035.php
- user_guide_src/source/libraries/validation/037.php
- the value to be validated is not necessarily a string.
**Checklist:**
> docs: update validation.rst

- user_guide_src/source/installation/upgrade_4xx.rst
- user_guide_src/source/outgoing/localization.rst
- user_guide_src/source/outgoing/localization/001.php
- user_guide_src/source/outgoing/localization/002.php
- user_guide_src/source/outgoing/localization/003.php
- add note for namespaces in lang files
**Checklist:**
> docs: improve localization.rst

- tests/system/Entity/EntityTest.php
```
1) CodeIgniter\Entity\EntityTest::testCastTimestampException
Expecting E_ERROR and E_USER_ERROR is deprecated and will no longer be possible in PHPUnit 10.
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:97
2) CodeIgniter\Entity\EntityTest::testCustomCastException
Expecting E_ERROR and E_USER_ERROR is deprecated and will no longer be possible in PHPUnit 10.
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:97
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/4082500823/jobs/7036936331
**Checklist:**
> test: replace deprecated expectErrorMessage()

- system/HTTP/DownloadResponse.php
- tests/system/HTTP/DownloadResponseTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/outgoing/response.rst
- user_guide_src/source/outgoing/response/028.php
There is currently no way to change the ``Content-Disposition`` header when downloading a file, as this header will be overwritten when generating headers in the ``DownloadResponse`` class.
This PR prevents the ``Content-Disposition`` header from being changed when generating headers if that header has already been set.
It also adds a ``DownloadRespone::inline()`` helper method that sets the ``Content-Disposition: inline`` header.
**Checklist:**
> Feature: New method DownloadResponse::inline()

- psalm-baseline.xml
- rector.php
- tests/system/Commands/BaseCommandTest.php
- tests/system/Config/BaseConfigTest.php
- tests/system/Entity/EntityTest.php
- tests/system/Log/Handlers/ChromeLoggerHandlerTest.php
- tests/system/Test/FabricatorTest.php
See https://github.com/sebastianbergmann/phpunit/issues/4601
- replace deprecated `assertObjectHasAttribute()`
- skip `AssertPropertyExistsRector`
- update `psalm-baseline.xml`
```
1) CodeIgniter\Commands\BaseCommandTest::testMagicIssetTrue
assertObjectHasAttribute() is deprecated and will be removed in PHPUnit 10.
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:97
2) CodeIgniter\Commands\BaseCommandTest::testMagicIssetFalse
assertObjectNotHasAttribute() is deprecated and will be removed in PHPUnit 10.
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:97
3) CodeIgniter\Entity\EntityTest::testFill
assertObjectNotHasAttribute() is deprecated and will be removed in PHPUnit 10. …
```
> test: replace deprecated assertObjectHasAttribute()

- user_guide_src/source/models/model.rst
I have changed the word 'sing' for 'using' in the documentation: 
Using CodeIgniter's Model -> In-Model Validation -> Specifying Callbacks To Run
**Checklist:**
> A spelling correction in model.html

- psalm-baseline.xml
- system/Commands/Utilities/Routes.php
- tests/_support/Config/Routes.php
- tests/system/Commands/RoutesTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/incoming/routing.rst
- add option to specify host in the request URL
```diff
@@ -31,6 +31,9 @@ $routes->set404Override();
// route since we don't have to scan directories.
+$routes->get('/', 'Account::index', ['hostname' => 'account.example.com']);
+$routes->get('/', 'Media::index', ['subdomain' => 'media']);
+
/*
* --------------------------------------------------------------------
* Additional Routing
```
```console
$ php spark routes
CodeIgniter v4.3.1 Command Line Tool - Server Time: 2023-02-02 05:25:26 UTC+00:00
+--------+-------+------+------------------------------+----------------+---------------+
| Method | Route | Name | Handler                      | Before Filters | After Filters | …
```
> feat: add `--host` option to `spark routes`

- system/Debug/Exceptions.php
See https://forum.codeigniter.com/showthread.php?tid=86536&pid=406349#pid406349
If "Allowed memory size of xxx bytes exhausted" error occurs in the Exception handler,
the true Exception does not show in the debug stack trace.
This PR is not perfect, but DX would be improved.
Before:
After:
**Checklist:**
> fix: stack trace displayed when Exception handler runs out of memory is useless

- system/Helpers/form_helper.php
- tests/system/Helpers/FormHelperTest.php
The `validation_show_error()` form helper does not support the use of wildcards (*) like the `getError()` validation method. 
For example, if I have a rule like this:
```php
$rules = [
'users.*.name' => "required"
];
```
I expect that I should be able to display the error in the view using `validation_show_error('users.*.name')` just the same way I would if I use `$validation->getError('users.*.name')`.
This PR fixes that.
**Checklist:**
> fix: support for display of error message using wildcard (*)

- phpstan-baseline.neon.dist
- system/HTTP/IncomingRequest.php
- system/Router/Router.php
- system/Router/RouterInterface.php
- tests/system/HTTP/IncomingRequestDetectingTest.php
- tests/system/Router/RouterTest.php
From https://forum.codeigniter.com/showthread.php?tid=86284&pid=406192#pid406192
When `Config\App::$uriProtocol` is `QUERY_STRING` and accessing baseURL:
- (1) Fix: the defined route `/` is ignored, and routed to the default controller
- (2) Fix: `Debug/Toolbar/Collectors/Routes.php` throws "ReflectionException: Class "Home" does not exist" 
**How to Reproduce**
```diff
@@ -59,7 +59,7 @@ class App extends BaseConfig
*
* WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
-    public string $uriProtocol = 'REQUEST_URI';
+    public string $uriProtocol = 'QUERY_STRING';
/**
* --------------------------------------------------------------------------
diff --git a/app/Config/Routes.php …
```
> fix: routing behavior when $uriProtocol is QUERY_STRING

- system/Database/MySQLi/Result.php
- system/Database/OCI8/Result.php
- system/Database/Postgre/Result.php
- system/Database/SQLSRV/Result.php
- system/Database/SQLite3/Result.php
- system/Entity/Entity.php
- tests/system/Entity/EntityTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
Supersedes #5763, #5781
Fixes #5762
- add `Entity::injectRawData()`
- deprecate `Entity::setAttributes()`
- ~~require setter/getter methods must be public. See https://github.com/codeigniter4/CodeIgniter4/issues/5762#issuecomment-1179519591~~
**Checklist:**
> feat: add `Entity::injectRawData()` to avoid name collision

- system/Common.php
The `@template` annotation relates to a concept called Generics, which does not currently exist in PHP, but are a way of dynamically describing the contents of a parameter or return type that would be unknown until a class is instantiated or method called.
**Checklist:**
> refactor: Update PHPDoc Common::config

- system/Model.php
add missing @method having() in Model
> add missing @method having() in Model

- system/HTTP/URI.php
- tests/system/HTTP/URITest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/installation/upgrade_440.rst
- user_guide_src/source/installation/upgrade_440/002.php
Fixes #7250
Related #7249
**Checklist:**
> fix: URI::setSegment() accepts the last +2 segment without Exception

- rector.php
- system/Config/Services.php
- system/Debug/Exceptions.php
- tests/system/Helpers/FormHelperTest.php
This PR is required for #7239.
When registering Exception Handler, `Request` object was generated. 
But it was too early, and difficult to understand.
Before:
```
Services.php:535, CodeIgniter\Config\Services::incomingrequest()
Services.php:501, CodeIgniter\Config\Services::request()
BaseService.php:252, CodeIgniter\Config\BaseService::__callStatic()
BaseService.php:193, CodeIgniter\Config\BaseService::request()
BaseService.php:193, CodeIgniter\Config\BaseService::getSharedInstance()
Services.php:497, CodeIgniter\Config\Services::request()
BaseService.php:252, CodeIgniter\Config\BaseService::__callStatic()
Services.php:265, CodeIgniter\Config\BaseService::request()
Services.php:265, CodeIgniter\Config\Services::exceptions()
BaseService.php:252, …
```
> refactor: deprecate $request and $response in Exceptions::__construct()

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.3.2.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_432.rst
Updates changelog and version references for 4.3.2.
**Checklist:**
Ref #7115
> Prep for 4.3.2 release

- user_guide_src/source/installation/upgrade_432.rst
- remove incorrect "Project Files". See https://github.com/codeigniter4/appstarter/commit/2f3d1531b449337217524e47baa7d680003829ea
Cloning a repository is time consuming, so I used the previous release repository. However, I seem to have forgotten to update `master`.
**Checklist:**
> docs: fix upgrade_432.rst

- user_guide_src/source/installation/upgrade_430.rst
- remove duplicated `for`
**Checklist:**
> docs: remove duplicated `for` in upgrade_430.rst

- user_guide_src/source/installation/installing_composer.rst
In [Adding CodeIgniter4 to an Existing Project](https://codeigniter.com/user_guide/installation/installing_composer.html#adding-codeigniter4-to-an-existing-project) docs is an incorrectly defined how to adjust the `$systemDirectory` property. 
`$systemDirectory` should be defined as in [appstarter project](https://github.com/codeigniter4/appstarter/blob/2f3d1531b449337217524e47baa7d680003829ea/app/Config/Paths.php#L26).
`ROOTPATH` constant causes an error with `php spark serve` like:
```sh
PHP Fatal error:  Uncaught Error: Undefined constant "Config\ROOTPATH" in /Users/jrebjak/CodeIgniter4/test-existing-project/spark:72
Stack trace:
#0 {main} thrown in /Users/jrebjak/CodeIgniter4/test-existing-project/spark on line 72
```
**Checklist:**
> docs: fix $systemDirectory path in existing project.

- user_guide_src/source/dbmgmt/forge.rst
The documentation for forge states that the parameters for cascading foreign keys produce an "on update" and "on update" SQL statement, wherein the produce an "on delete" and "on update" SQL statement when specified.
> docs: Typographic correction in forge.rst

- tests/system/CodeIgniterTest.php
If I run the test method only, it causes Error.
- fix out-of-dated test code
**Checklist:**
> test: fix out-of-dated test code in CodeIgniterTest

- phpstan-baseline.neon.dist
- system/Commands/Utilities/Routes/ControllerFinder.php
- resolove PHPStan 1.10.1 errors
**Checklist:**
> refactor: resolove PHPStan 1.10.1 errors

- system/Database/BaseBuilder.php
This detected on run `RemoveAlwaysTrueIfConditionRector` on dependabot PR:
- https://github.com/codeigniter4/CodeIgniter4/pull/7294
https://github.com/codeigniter4/CodeIgniter4/actions/runs/4244147097/jobs/7377846287#step:9:21
Because it not part of `@param` doc
**Checklist:**
> Add RawSql[] on @param on Basebuilder::updateFields()

- user_guide_src/source/libraries/uri.rst
- add note for URI Segments
baseURL: http://localhost:8888/ci431/public/
```php
<?php
{
{
var_dump($this->request->getUri()->getSegments());
var_dump($this->request->getUri()->getSegment(1));
}
}
```
Navigate to http://localhost:8888/ci431/public/one/two/three
```
/Applications/MAMP/htdocs/ci431/app/Controllers/Home.php:9:
array (size=3)
0 => string 'one' (length=3)
1 => string 'two' (length=3)
2 => string 'three' (length=5)
/Applications/MAMP/htdocs/ci431/app/Controllers/Home.php:10:string 'one' (length=3)
```
**Checklist:**
> docs: add note for URI Segments

- system/HTTP/URI.php
Supersedes #7249
- fix incorrect segment number in `URI::getSegment()` exception message
- throw an exception for an impossible segment number
**Checklist:**
> fix: incorrect segment number in URI::getSegment() exception message

- system/Database/BaseBuilder.php
- tests/system/Database/Live/LikeTest.php
> fix: [QueryBuilder] RawSql causes error when using like() and countAllResults()

- user_guide_src/source/incoming/restful.rst
> docs: fix section title marks in restful.rst

- system/CodeIgniter.php
- tests/system/CodeIgniterTest.php
- refactor CodeIgniter
- improve test
**Checklist:**
> refactor: use config(Cache::class) in CodeIgniter

- system/Debug/Exceptions.php
Fixes #7262.
The `clean_path()` function should not be there to begin with.
**Checklist:**
> Fix handling of null bytes in `Exceptions::renderBacktrace()`

- user_guide_src/source/libraries/uri.rst
Closes #7246
- add note for URI::getSegment()
**Checklist:**
> docs: add note for URI::getSegment()

- system/Entity/Entity.php
- tests/system/Entity/EntityTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/models/entities.rst
~~Needs  #7208~~
Add special getter/setter to Entity to avoid method name conflicts.
- add new special setter method "`_set` + key" for a attribute
- add new special getter method "`_get` + key" for a attribute
**Checklist:**
> feat: add new setter/getter for Entity

- system/Autoloader/Autoloader.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/installation/installing_composer.rst
- user_guide_src/source/installation/installing_manual.rst
Closes #7055
- remove Autoloader::sanitizeFilename() checking
- deprecate Autoloader::sanitizeFilename()
**Checklist:**
> Remove Autoloader::sanitizeFilename() checking

- system/Filters/FilterInterface.php
I think `@param null $arguments` should be used `@param array|null $arguments` on `FilterInterface`
**Checklist:**
> Fix @param null $arguments on FilterInterface

- system/HTTP/RequestInterface.php
Looking at the usage, the `$filter` can be null or integer, eg: 
```php
$referer = $_SESSION['_ci_previous_url'] ?? Services::request()->getServer('HTTP_REFERER', FILTER_SANITIZE_URL);
```
or
```php
$request->getServer(['SERVER_PROTOCOL', 'REQUEST_URI']);
```
so it seems can use `@param string|int|null` for it.
**Checklist:**
> Fix @param null on RequestInterface::getServer() $filter argument

- system/Database/SQLSRV/Connection.php
- tests/system/Database/Live/ForgeTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/database/metadata.rst
- `getFieldData()` supports nullable
**Checklist:**
> feat: [SQLSRV] getFieldData() supports nullable

- system/HTTP/IncomingRequest.php
- tests/system/HTTP/IncomingRequestTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/outgoing/localization.rst
Fixes #4297
- add `IncomingRequest::setValidLocales()`
**Checklist:**
> fix: can't change and override valid locales

- composer.json
Use coding-standard's dependency.
See https://github.com/CodeIgniter/coding-standard/releases/tag/v1.7.2
**Checklist:**
> chore: remove php-cs-fixer in composer.json

- system/Helpers/text_helper.php
- user_guide_src/source/changelogs/v4.3.3.rst
- user_guide_src/source/helpers/text_helper.rst
See #7326
Related #7327
- use `random_int()` in `random_string('numeric')`
**Checklist:**
> fix: random_string() numeric

- user_guide_src/source/helpers/form_helper.rst
- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/libraries/validation/042.php
Fixes #7332
- add "Redirect and Validation Errors"
- small fixes
**Checklist:**
> docs: update Validation

- user_guide_src/source/incoming/methodspoofing.rst
- update HTML tag
**Checklist:**
> docs: update methodspoofing.rst

- system/API/ResponseTrait.php
- tests/system/API/ResponseTraitTest.php
Fixes #7346 about API\ResponseTrait::respondNoContent() returns Kint script in development mode.
**Checklist:**
> fix: respondNoContent() returns Kint script in development mode

- system/Debug/Exceptions.php
Fixes #7339
Now the last Exception is shown, but showing the first Exception helps for debugging.
This PR shows the first Exception.
```php
<?php
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;
class Tests extends BaseController
{
public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
{
// Do Not Edit This Line
parent::initController($request, $response, $logger);
$this->xx(); // Call to undefined method App\Controllers\Tests::xx()
}
public function __destruct()
{
dd($this->info); // Undefined property: App\Controllers\Tests::$info
}
{
}
}
```
Before:
```
$ php public/index.php tests
[ErrorException] …
```
> fix: use first exception in exceptionHandler()

- system/Helpers/text_helper.php
- user_guide_src/source/changelogs/v4.3.3.rst
- user_guide_src/source/helpers/text_helper.rst
See #7326
Related #7336, #7327
- use `random_bytes()` in `random_string()` alpha alnum nozero
**Checklist:**
> fix: random_string() alpha alnum nozero

- system/Commands/Database/MigrateRollback.php
- user_guide_src/source/dbmgmt/migration.rst
See #7349
Fixes the incorrect documentation and help.
We cannot specify negative number as an option value on CLI.
**Checklist:**
> fix: migrate:rollback -b negative number

- system/Helpers/url_helper.php
- tests/system/Helpers/URLHelper/SiteUrlTest.php
CI3 supports protocol-relative links.
```php
$this->load->helpers('url');
echo site_url('test', ''); // outputs "//localhost:8888/index.php/test"
```
- https://github.com/bcit-ci/CodeIgniter/blob/a6faab2ebf082eefff9c2422fce016e49da548bf/system/core/Config.php#L243-L253
- https://github.com/bcit-ci/CodeIgniter/blob/a6faab2ebf082eefff9c2422fce016e49da548bf/system/core/Config.php#L306-L316
**Checklist:**
> fix: site_url() does not support protocol-relative links

- CHANGELOG.md
- user_guide_src/source/changelogs/v4.3.2.rst
- user_guide_src/source/changelogs/v4.3.3.rst
- user_guide_src/source/helpers/url_helper.rst
- user_guide_src/source/installation/upgrade_432.rst
Follow-up #7135
- add uri_string() BC in v4.3.2
**Checklist:**
> docs: add uri_string() BC in v4.3.2

- user_guide_src/source/outgoing/view_renderer.rst
- add "Setting View Parameters" section
**Checklist:**
> docs: Improve view_renderer.rst

- system/Cache/Handlers/FileHandler.php
> fix: Cache FileHandler error when there is a folder in cache dir

- user_guide_src/source/dbmgmt/seeds.rst
- add section title and TOC
- modify text decoration
- add sample command for Windows
**Checklist:**
> docs: improve seeds.rst

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.3.3.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_433.rst
Updates changelog and version references for 4.3.3.
Ref #7270
**Checklist:**
> Prep for 4.3.3 release

- user_guide_src/source/outgoing/response.rst
- user_guide_src/source/outgoing/response/012.php
- user_guide_src/source/outgoing/response/013.php
- use `getCSP()` instead of the deprecated `CSP` property
**Checklist:**
> docs: update CSP description

- system/Database/BaseResult.php
- system/Database/MySQLi/Result.php
- system/Database/OCI8/Result.php
- system/Database/Postgre/Result.php
- system/Database/SQLSRV/Result.php
- system/Database/SQLite3/Result.php
- system/Test/Mock/MockResult.php
> docs: fix PHPDoc types in Database Results

- system/Helpers/text_helper.php
- user_guide_src/source/changelogs/v4.3.4.rst
- user_guide_src/source/helpers/text_helper.rst
Supersedes #7327
See https://forum.codeigniter.com/showthread.php?tid=87026
**Checklist:**
> docs: deprecate random_string() basic,md5,sha1

- system/Commands/Generators/CellGenerator.php
- system/View/Cells/Cell.php
- tests/_support/View/Cells/AwesomeCell.php
- tests/_support/View/Cells/awesome_cell.php
- tests/system/Commands/CellGeneratorTest.php
- tests/system/View/ControlledCellTest.php
Fixes #7391 
- fix a bug that View Cells cannot load a view file with `_cell` when the classname ends with `Cell`.
- fix a bug that `spark make:cell` creates a view file with `_cell` when the classname does not end with `Cell`.
**Checklist:**
> fix: view cell cannot locate the auto-generated view file

- system/HTTP/IncomingRequest.php
- user_guide_src/source/incoming/incomingrequest.rst
See https://github.com/codeigniter4/CodeIgniter4/issues/6310
**Checklist:**
> docs: replace `mixed` in system/HTTP/IncomingRequest.php

- user_guide_src/source/cli/cli_generators.rst
- user_guide_src/source/cli/cli_generators/001.php
Added explanation on how to locate the view template of a custom generator command. Fixes #7405.
**Checklist:**
> docs: add note for custom command generator template

- .github/workflows/test-phpcpd.yml
- app/Config/Exceptions.php
- system/Debug/BaseExceptionHandler.php
- system/Debug/ExceptionHandler.php
- system/Debug/ExceptionHandlerInterface.php
- system/Debug/Exceptions.php
- tests/system/Debug/ExceptionHandlerTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/general/errors.rst
- user_guide_src/source/general/errors/015.php
- user_guide_src/source/general/errors/016.php
- user_guide_src/source/general/errors/017.php
- user_guide_src/source/installation/upgrade_440.rst
Supersedes #5675, #6710
Allows developers to easily create and integrate their own Exception handler classes, 
and limiting their usage to only the exception or HTTP status code desired.
- add `ExceptionHandlerInterface`, `BaseExceptionHandler`, and `ExceptionHandler`
- add `Config\Exceptions::handler()` to define Exception handler
**Checklist:**
> feat: custom exception handler

- system/Cookie/Cookie.php
- system/Cookie/CookieInterface.php
- tests/system/Cookie/CookieTest.php
> docs: replace type `mixed` in `Cookie` class.

- system/HTTP/CURLRequest.php
- system/Test/Mock/MockCURLRequest.php
- tests/system/HTTP/CURLRequestDoNotShareOptionsTest.php
- tests/system/HTTP/CURLRequestTest.php
- user_guide_src/source/changelogs/v4.3.4.rst
Fixes #7394
- create a new Response object for a request
**Checklist:**
> fix: CURLRequest - clear response headers between requests

- system/Commands/Utilities/Routes/AutoRouterImproved/ControllerMethodReader.php
- tests/system/Commands/Utilities/Routes/AutoRouterImproved/ControllerMethodReaderTest.php
- tests/system/Commands/Utilities/Routes/AutoRouterImproved/Controllers/Home.php
- user_guide_src/source/incoming/routing.rst
Supersedes #7417
Fixes #7415
Methods that are not routed should be removed. 
So the command shows them with `x` so that developers know.
Before:
```
+-----------+--------------+------+-------------------------------------+----------------+---------------+
| Method    | Route        | Name | Handler                             | Before Filters | After Filters |
+-----------+--------------+------+-------------------------------------+----------------+---------------+
| GET(auto) | dir          |      | \App\Controllers\Dir\Home::getIndex |                | toolbar       |
| GET(auto) | dir/home/foo |      | \App\Controllers\Dir\Home::getFoo   | <unknown>      | <unknown>     |
| GET(auto) | /            |      | \App\Controllers\Home::getIndex     |                | toolbar …
```
> fix: [Auto Routing Improved] spark routes shows invalid routes

- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/incoming/routing.rst
- improve description for Default Controller in Auto-Routing
- update for consistency
**Checklist:**
> docs: improve auto routing

- app/Config/Routing.php
- system/Commands/Utilities/Routes.php
- system/Commands/Utilities/Routes/AutoRouterImproved/AutoRouteCollector.php
- system/Router/AutoRouterImproved.php
- tests/system/Router/AutoRouterImprovedTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/incoming/routing.rst
~~Needs #7380~~
Adds module routing.
E.g.,
`app/Config/Routing.php`:
```php
public array $moduleRoutes = [
'blog' => 'Acme\Blog\Controllers',
];
```
`http://localhost:8080/blog/foo/bar` will run `Acme\Blog\Controllers\Foo::getBar()`.
**Checklist:**
> feat: [Auto Routing Improved] Module Routing

- phpstan-baseline.neon.dist
- system/API/ResponseTrait.php
- system/HTTP/ResponseTrait.php
phpstan (1.10.13) reports the following errors:
```
------ ------------------------------------------------------------------------------------------------------------------------ 
Line   system/Database/MySQLi/Connection.php                                                                                   
------ ------------------------------------------------------------------------------------------------------------------------ 
Ignored error pattern #^Property CodeIgniter\\Database\\BaseConnection<mysqli,mysqli_result>\:\:\$strictOn \(bool\) in  
isset\(\) is not nullable\.$# in path                                                                                   
/Users/kenji/work/codeigniter/official/CodeIgniter4/system/Database/MySQLi/Connection.php was not …
```
> docs: fix phpstan errors

- system/Validation/Validation.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/installation/upgrade_440.rst
- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/libraries/validation/012.php
`Validation::check()` should accept array rules.
In #5545, `string` for `$rules` in `setRule()` was removed.
**Checklist:**
> fix: Validation::check() does not accept array rules

- system/Database/BaseConnection.php
- system/Database/ConnectionInterface.php
- system/Database/Postgre/Connection.php
- system/Database/SQLSRV/Connection.php
> docs: fix PHPDoc types in Database Connection.

- system/Validation/Validation.php
- system/Validation/ValidationInterface.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/installation/upgrade_440.rst
Follow-up #7420
PHPStan reports when using `$this->validator->getValidated()` in `Controller`:
> Call to an undefined method CodeIgniter\Validation\ValidationInterface::getValidated().
**Checklist:**
> feat: add ValidationInterface::getValidated()

- system/Config/BaseService.php
- system/Config/Config.php
> docs: replace type `mixed` at Config class.

- system/CLI/BaseCommand.php
- system/CLI/CLI.php
> docs: replace `mixed` type at CLI class.

- system/BaseModel.php
`$DBGroup` is nullable.
**Checklist:**
> docs: fix @var in BaseModel

- system/Commands/Generators/Views/model.tpl.php
Fixes #7440
We should not use `$insertID` in Model.
**Checklist:**
> fix: remove $insertID in make:model template

- system/Router/RouteCollectionInterface.php
> docs: fix PHPDoc types in `Route` class.

- system/Database/BaseResult.php
- system/Database/MySQLi/Result.php
- system/Database/OCI8/Result.php
- system/Database/Postgre/Result.php
- system/Database/ResultInterface.php
- system/Database/SQLSRV/Result.php
- system/Database/SQLite3/Result.php
> docs: fix PHPDoc types in Database Result.

- user_guide_src/source/database/configuration.rst
- user_guide_src/source/database/helpers.rst
- user_guide_src/source/intro/requirements.rst
Small improvements.
**Checklist:**
> docs: improve database driver description

- user_guide_src/source/database/configuration.rst
- user_guide_src/source/database/configuration/009.php
- user_guide_src/source/general/configuration.rst
Closes #7453
- improve description on Env Vars and Config values
- add example to set database.default.encrypt with `.env`
**Checklist:**
> docs: improve description on Env Vars and Config values

- user_guide_src/source/outgoing/view_cells.rst
- fix minor incorrect descriptions
**Checklist:**
> docs: fix view_cells.rst

- system/Database/Forge.php
- system/Database/OCI8/Forge.php
- system/Database/Postgre/Forge.php
- system/Database/SQLSRV/Forge.php
- system/Database/SQLite3/Table.php
- tests/_support/MigrationTestMigrations/Database/Migrations/2018-01-24-102301_Some_migration.php
- tests/system/Commands/Database/MigrateStatusTest.php
- tests/system/Database/DatabaseTestCase/DatabaseTestCaseMigrationOnce1Test.php
- tests/system/Database/DatabaseTestCase/DatabaseTestCaseMigrationOnce2Test.php
- tests/system/Database/DatabaseTestCaseTest.php
- tests/system/Database/Live/ForgeTest.php
- tests/system/Database/Migrations/MigrationRunnerTest.php
- user_guide_src/source/changelogs/v4.3.4.rst
- user_guide_src/source/dbmgmt/forge.rst
- user_guide_src/source/dbmgmt/forge/026.php
- user_guide_src/source/installation/upgrade_434.rst
See #7302
- The `$forge->modifyColumn()` has been fixed. Due to a bug, in previous versions, SQLite3/Postgres/SQLSRV might change `NULL`/`NOT NULL` unpredictably.
- In previous versions, the OCI8 driver did not change `NULL`/`NOT NULL` when you don’t specify `null` value.
- Now in all database drivers `$forge->modifyColumn()` always sets `NULL` when you don’t specify `null` value.
**Checklist:**
> fix: [SQLite3][Postgres][SQLSRV][OCI8] Forge::modifyColumn() changes NULL constraint incorrectly

- app/Config/Generators.php
> ErrorException: Undefined array key "make:cell" in .../CodeIgniter4/system/CLI/GeneratorTrait.php:270
**Checklist:**
> fix: add missing 'make:cell' in app/Config/Generators.php

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.3.4.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_434.rst
Updates changelog and version references for 4.3.4.
Ref #7382
**Checklist:**
> Prep for 4.3.4 release

- user_guide_src/source/incoming/routing/030.php
- user_guide_src/source/incoming/routing/047.php
This is a very stupid edit, just a typo in the url of example.
**Checklist:**
> Double // in url in URI Routing example (Using Named Routes) 

- tests/system/Database/Live/ForgeTest.php
~~Needs #7301~~
From https://zenn.dev/naente/articles/50935eb55c14ea (CodeIgniter4 PostgreSQL always adds NOT NULL constraints when running `modifyColumn()`)
See the current behavior: https://github.com/codeigniter4/CodeIgniter4/pull/7302#issuecomment-1444980360
- add test for `Forge::modifyColumn()` and null
**This bug was fixed in v4.3.4**:
-  #7371
Related #7235
**Checklist:**
> test: Forge::modifyColumn() and null

- user_guide_src/source/_static/css/citheme.css
- user_guide_src/source/_static/css/citheme_dark.css
- user_guide_src/source/conf.py
This is an ancient work from December. It adds a dark mode to our user guide.
Since *Read the Docs* doesn't have built-in support for the dark mode style, I implemented a solution strictly dependent on system settings. So there is no switch to enable or disable dark mode.
Preview: https://michalsn.github.io/CodeIgniter4/ - please don't test it on a sunny day 😅 
**Checklist:**
> feat: user guide dark mode

- system/Database/BaseConnection.php
- system/Database/BasePreparedQuery.php
- system/Database/BaseResult.php
- system/Database/ConnectionInterface.php
- system/Database/MySQLi/Result.php
- system/Database/OCI8/Result.php
- system/Database/Postgre/Result.php
- system/Database/PreparedQueryInterface.php
- system/Database/ResultInterface.php
- system/Database/SQLSRV/Result.php
- system/Database/SQLite3/Result.php
- system/Test/Mock/MockResult.php
To fix this error: https://github.com/codeigniter4/shield/pull/195#issuecomment-1508037593
It seems Psalm does not allow to use `resource` in @template type.
See
- https://github.com/codeigniter4/settings/pull/60#issuecomment-1414894845
- https://github.com/codeigniter4/shield/pull/195#issuecomment-1508037593
**Checklist:**
> fix: PHPDoc @template and @return in database

- system/Filters/FilterInterface.php
- system/Filters/Filters.php
> docs: fix PHPDoc types in `Filter` class.

- system/API/ResponseTrait.php
Fixes #7486
`@property` is used for magic properties.
See https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/property.html#property-property-read-property-write
**Checklist:**
> docs: remove incorrect @property in ResponseTrait

- system/Router/RouteCollection.php
Fixes #7474 
Normalize the route path.
**Checklist:**
> fix: directory separator from routing file.

- system/Validation/Validation.php
- tests/system/Validation/RulesTest.php
- tests/system/Validation/StrictRules/RulesTest.php
- user_guide_src/source/changelogs/v4.3.5.rst
> fix: validation error when a closure is used in combination with permit_empty or if_exist rules

- system/Helpers/array_helper.php
- tests/system/Helpers/ArrayHelperTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/helpers/array_helper.rst
- user_guide_src/source/helpers/array_helper/012.php
- user_guide_src/source/helpers/array_helper/013.php
- user_guide_src/source/helpers/array_helper/014.php
A function to group data rows by values defined by indexes. The function supports the "dot syntax". Optionally it can include empty values (where `empty($value) === true`) and puts them under key `''`.
The depth of return result equals `count($indexes)`.
Example:
```php
$data = [
[
'id'    => 1,
'item'  => 'ball',
'color' => 'blue',
],
[
'id'    => 2,
'item'  => 'book',
'color' => 'red',
],
[
'id'   => 3,
'item' => 'bird',
'age'  => 5,
],
[
'id'    => 4,
'item'  => 'jeans',
'color' => 'blue',
],
];
$result = array_group_by($data, ['color'], true);
```
Returns following result
```php
$result = [
'blue' => [
[
'id'    => 1,
'item'  => 'ball',
'color' => 'blue',
],
[
'id'    => 4,
'item'  => 'jeans',
'color' => 'blue',
],
],
'red' => [
[
'id'    => 2,
'item'  => 'book', …
```
> feat: function array_group_by

- system/Session/Session.php
- typo in log message
**Checklist:**
> fix: typo in log message in Session

- user_guide_src/source/intro/requirements.rst
See https://github.com/codeigniter4/CodeIgniter4/pull/7488#discussion_r1195813607
**Checklist:**
> docs: require PostgreSQL 7.4 or later

- system/Entity/Entity.php
Reassignment makes the code difficult to understand.
**Checklist:**
> refactor: Entity variable

- system/Session/Session.php
- user_guide_src/source/changelogs/v4.3.5.rst
- user_guide_src/source/installation/upgrade_435.rst
- user_guide_src/source/libraries/sessions.rst
- user_guide_src/source/libraries/sessions/038.php
Closes #7501
See https://github.com/codeigniter4/CodeIgniter4/issues/7501#issuecomment-1549005952
**Checklist:**
> fix: Session::stop() does not destroy session

- app/Config/Generators.php
- system/CLI/GeneratorTrait.php
- system/Commands/Generators/CellGenerator.php
- system/View/Cells/Cell.php
- tests/_support/View/Cells/BadCell.php
- tests/system/Commands/CellGeneratorTest.php
- tests/system/View/ControlledCellTest.php
- user_guide_src/source/changelogs/v4.3.5.rst
- user_guide_src/source/cli/cli_generators.rst
- user_guide_src/source/outgoing/view_cells.rst
Fixes #7472 
Fixes #7469 
Supersedes and closes #7479 
Supersedes and closes #7471 
**Checklist:**
> fix: standardize behavior of `make:cell` and `Cells`

- phpstan-baseline.neon.dist
- system/Database/Postgre/Connection.php
Fixes #7484
Fixies logic of PostgreSQL getVersion() method.
> fix: PostgreSQL getVersion() logic

- system/Database/Postgre/Connection.php
- tests/system/Database/Live/GetVersionTest.php
Follow-up #7488
- add test for getVersion()
- fix output version string
**Checklist:**
> fix: PostgreSQL getVersion() output

- tests/_support/Models/ValidErrorsModel.php
- tests/_support/Models/ValidModel.php
- tests/system/Models/ValidationModelTest.php
```
There were 6 errors:
1) CodeIgniter\Models\ValidationModelTest::testValidationPlaceholdersSuccess
LogicException: No validation rules for the placeholder: id
/home/runner/work/CodeIgniter4/CodeIgniter4/system/Validation/Validation.php:687
/home/runner/work/CodeIgniter4/CodeIgniter4/system/Validation/Validation.php:138
/home/runner/work/CodeIgniter4/CodeIgniter4/system/BaseModel.php:1453
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Models/ValidationModelTest.php:157
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:106
2) CodeIgniter\Models\ValidationModelTest::testValidationPlaceholdersFail
LogicException: No validation rules for the placeholder: id
/home/runner/work/CodeIgniter4/CodeIgniter4/system/Validation/Valida …
```
> test: fix Model Validation tests

- system/CodeIgniter.php
- system/Debug/BaseExceptionHandler.php
- system/Debug/Exceptions.php
- system/HTTP/DownloadResponse.php
- system/Test/FeatureTestTrait.php
- tests/system/CodeIgniterTest.php
- tests/system/Test/FeatureTestTraitTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
Fixes #7493
Work with output buffering was carried out incorrectly.
To bypass an existing bug in tests, a hack was used
https://github.com/codeigniter4/CodeIgniter4/blob/3b3cfb57ee564c84487729b3fd5459efa6733920/tests/system/CodeIgniterTest.php#L57-L59
In my opinion, this PR correctly completes output buffering, including for exceptions.
**Checklist:**
> [4.4] Fix output buffering

- psalm-baseline.xml
- psalm.xml
To suppress the following error and warnings:
```
ERROR: UnsupportedPropertyReferenceUsage - system/Test/ControllerResponse.php:51:9 - This reference cannot be analyzed by Psalm. (see https://psalm.dev/321)
$this->dom = &$this->domParser;
```
`ControllerResponse` is deprecated.
```
Warning: "findUnusedBaselineEntry" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.
Warning: "findUnusedCode" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.
```
**Checklist:**
> chore: update psalm baseline.xml

- admin/RELEASE.md
`composer audit` uses GitHub Security Advisory Database.
https://github.com/advisories?query=codeigniter4
So now we don't need to send PR to FriendsOfPHP/security-advisories.
```console
$ php spark | head -2
CodeIgniter v4.3.4 Command Line Tool - Server Time: 2023-05-23 23:59:12 UTC+00:00
```
```console
$ composer audit
Info from https://repo.packagist.org: #StandWithUkraine
Found 1 security vulnerability advisory affecting 1 package:
+-------------------+----------------------------------------------------------------------------------+
| Package           | codeigniter4/framework                                                           |
| CVE               | CVE-2023-32692                                                                   |
| Title             | Remote …
```
> docs: remove sending PR to FriendsOfPHP/security-advisories

- system/Images/Handlers/GDHandler.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/libraries/images.rst
With condition of SEO Strategic, we need compress all image web with `WebP` for speed performance.
**Checklist:**
> feat: `GDHandler` make `WebP` with option quality

- phpstan-baseline.neon.dist
- system/HTTP/IncomingRequest.php
`$this->locale` is set in the `detectLocale()` method called in the constructor.
**Checklist:**
> refactor: remove unneeded code in IncomingRequest

- system/Commands/Utilities/Routes/AutoRouterImproved/ControllerMethodReader.php
- system/Router/AutoRouterImproved.php
- tests/system/Router/AutoRouterImprovedTest.php
- tests/system/Router/Controllers/Subfolder/Home.php
- tests/system/Router/Controllers/Subfolder/Sub/Mycontroller.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/incoming/controllers/025.php
Related #7162
You can pass arguments to the default method of the default controller.
When you have `News\Home` and `public function getIndex($id = null)` in it:
- `GET /news/101`
- → `News` not found
- → `News\101` not found (invalid)
- → `News\101\Home` not found (invalid)
- → `News\Home` found
- → `News\Home::getIndex()` found
- → run `News\Home::getIndex('101')`
This PR makes it possible that one controller one URI.
**Checklist:**
> feat: [Auto Routing Improved] fallback to default controller's default method

- user_guide_src/source/database/query_builder/028.php
- user_guide_src/source/database/query_builder/031.php
- user_guide_src/source/database/query_builder/033.php
- user_guide_src/source/database/query_builder/035.php
- user_guide_src/source/database/query_builder/037.php
- user_guide_src/source/database/query_builder/041.php
- user_guide_src/source/database/query_builder/052.php
- user_guide_src/source/database/query_builder/054.php
- user_guide_src/source/database/query_builder/056.php
- user_guide_src/source/database/query_builder/058.php
- user_guide_src/source/database/query_builder/062.php
- user_guide_src/source/database/query_builder/081.php
This PR makes corrections in the Query Builder section.
- The subquery examples use the ``BaseBuilder`` type hint without importing the class itself.
- Some code examples are long and do not fit completely into the code display block, which causes a scrolling bar to appear.
**Checklist:**
> docs: [QueryBuilder] class without import. scrolling in examples.

- system/CodeIgniter.php
- tests/system/CodeIgniterTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
This PR refactors the CodeIgniter class code so that all successful responses, except those caused by exceptions, are sent from one place.
- The ``CodeIgniter::handleRequest()`` method now always returns a Response.
- Moved HTTP cli check and page cache check to ``CodeIgniter::handleRequest()`` method. Because these methods generate a Response and are actually part of the request processing.
- Event call ``Events::trigger('pre_system')`` moved to method ``CodeIgniter::handleRequest()`` and is now on the same "level" as ``Events::trigger('post_system')``
- The ``CodeIgniter::$returnResponse`` property has been deprecated as it is no longer used.
**Checklist:**
> [4.4] refactor: a single point of sending the Response.

- system/Autoloader/FileLocator.php
- tests/system/Autoloader/FileLocatorTest.php
Because the behavior of locateFile() is difficult to understand.
**Checklist:**
> docs: improve doc comment and tests for locateFile()

- system/Entity/Entity.php
```
------ ------------------------------------------------------------------------------------------------------------------------------------------ 
Line   system/Entity/Entity.php                                                                                                                  
------ ------------------------------------------------------------------------------------------------------------------------------------------ 
455    Method CodeIgniter\Entity\Entity::__set() with return type void returns $this(CodeIgniter\Entity\Entity) but should not return anything.  
464    Method CodeIgniter\Entity\Entity::__set() with return type void returns $this(CodeIgniter\Entity\Entity) but should not return anything.  
------ …
```
> refactor: [Entity] fix incorrect return value

- tests/system/Database/Live/ForgeTest.php
~~Needs #7301~~
See #7235
- add test for `Forge::addColumn()` and null
**Checklist:**
> test: Forge::addColumn() and null

- user_guide_src/source/libraries/validation.rst
> docs: add warning on Validation $data array

- system/Test/FeatureTestTrait.php
- tests/system/Test/FeatureTestTraitTest.php
See https://forum.codeigniter.com/showthread.php?tid=87844
Feature testing shares the Validation object between requests.
So the validation result is incorrect after a failed validation.
**Checklist:**
> fix: feature test with validation

- system/Validation/Validation.php
- system/Validation/ValidationInterface.php
- tests/system/Validation/StrictRules/DatabaseRelatedRulesTest.php
- user_guide_src/source/changelogs/v4.3.6.rst
- user_guide_src/source/installation/upgrade_436.rst
Fixes #7547
- fix that ``$DBGroup`` is ignored when checking the value of a placeholder
- fix that ``check()`` cannot specify non-default database group
- fix ``ValidationInterface::check()``
**Checklist:**
> fix: [Validation] DBGroup is ignored when checking the value of a placeholder

- system/HTTP/Files/FileCollection.php
- system/HTTP/Files/UploadedFile.php
- system/HTTP/Files/UploadedFileInterface.php
- tests/system/HTTP/Files/FileCollectionTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/libraries/uploaded_files.rst
- user_guide_src/source/libraries/uploaded_files/023.php
Supersedes #7538
Added `UploadedFile::getClientPath()` method.  
This returns the `full_path` index of uploaded files (when uploaded via directory).  
This feature is only available in PHP 8.1+. If the method is called below that version then `null` is returned.  
**Checklist:**
> Add access to `full_path` index of uploaded files

- system/Database/BaseBuilder.php
> fix: [QueryBuilder] incorrect SQL without space before "ON DUPLICATE KEY UPDATE"

- system/View/Cell.php
- fix the exception message: `CodeIgniter\View\Exceptions\ViewException: Unable to locate view cell class: "".`
**Checklist:**
> fix: wrong classname in exception message in Cell

- rector.php
- system/Router/AutoRouter.php
- system/Router/AutoRouterImproved.php
- system/Router/AutoRouterInterface.php
- system/Router/RouteCollection.php
- system/Router/Router.php
- tests/system/Router/AutoRouterImprovedTest.php
- tests/system/Test/FeatureTestAutoRoutingImprovedTest.php
- user_guide_src/source/changelogs/v4.3.6.rst
- user_guide_src/source/installation/upgrade_436.rst
See https://forum.codeigniter.com/showthread.php?tid=87818
- fix `AutoRouterInterface::getRoute()`
**Checklist:**
> fix: [Auto Routing Improved] feature testing may not find controller/method

- system/CodeIgniter.php
The `CodeIgniter::$bufferLevel` property is undefined by default.
If an exception is thrown in the `CodeIgniter::handleRequest()` method before the value is assigned to the property, an error occurs when the `CodeIgniter::outputBufferingEnd()` method is called. 
`Typed property CodeIgniter\CodeIgniter::$bufferLevel must not be accessed before initialization`.
This PR sets the `CodeIgniter::$bufferLevel` property in the `CodeIgniter::run()` method to prevent this error.
**Checklist:**
> [4.4] fix: Typed property CodeIgniter::$bufferLevel must not be accessed before initialization

- system/CodeIgniter.php
- system/Test/FeatureTestCase.php
- system/Test/FeatureTestTrait.php
Closes #7434
See https://github.com/codeigniter4/CodeIgniter4/issues/7434#issuecomment-1507972531
**Checklist:**
> docs: remove unneeded @throws in CodeIgniter

- system/Router/AutoRouterImproved.php
Follow-up #7543
`$httpVerb` is used later in the method. So the value should be lower case.
**Checklist:**
> refactor: [Auto Routing Improved] ensure $httpVerb is lower case

- user_guide_src/source/database/query_builder/098.php
- fix incorrect comments
**Checklist:**
> docs: fix incorrect comments in query_builder

- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/incoming/routing/008.php
> docs: improve routing.rst

- psalm_autoload.php
- scan tests/_support/Controllers for Psalm
I don't know why these errors are reported.
```
ERROR: UndefinedClass - tests/system/CodeIgniterTest.php:114:33 - Class, interface or enum named Tests\Support\Controllers\Hello does not exist (see https://psalm.dev/019)
$routes->set404Override('Tests\Support\Controllers\Hello::index');
ERROR: UndefinedClass - tests/system/CodeIgniterTest.php:133:33 - Class, interface or enum named Tests\Support\Controllers\Popcorn does not exist (see https://psalm.dev/019)
$routes->set404Override('Tests\Support\Controllers\Popcorn::pop');
ERROR: UndefinedClass - tests/system/CodeIgniterTest.php:152:33 - Class, interface or enum named Tests\Support\Controllers\Popcorn does not exist (see https://psalm.dev/019) …
```
> chore: [Psalm] workarround for Tests\Support\Controllers\Hello does not exist

- system/Images/Handlers/GDHandler.php
Fixes #7567.
It seems this is a bug of php.
Ref:
1. https://stackoverflow.com/questions/70569197/imagecreatefrompng-gd-png-libpng-warning-interlace-handling-should-be-turne
2. https://github.com/dompdf/dompdf/issues/2718
**Checklist:**
> fix: `imagecreatefrompng()` gd-png: libpng warning

- user_guide_src/source/database/queries.rst
- user_guide_src/source/libraries/pagination.rst
- user_guide_src/source/libraries/pagination/002.php
- user_guide_src/source/libraries/pagination/003.php
- user_guide_src/source/libraries/pagination/004.php
- user_guide_src/source/libraries/pagination/015.php
- user_guide_src/source/libraries/pagination/016.php
- user_guide_src/source/libraries/pagination/017.php
- user_guide_src/source/libraries/pagination/018.php
- add explanation and sample code
**Checklist:**
> docs: improve Paginating with Models

- user_guide_src/source/libraries/sessions.rst
- user_guide_src/source/libraries/sessions/040.php
- update old session config names
**Checklist:**
> docs: fix sessions.rst

- tests/system/ControllerTest.php
- tests/system/Database/Live/SQLite/AlterTableTest.php
- tests/system/I18n/TimeLegacyTest.php
- tests/system/I18n/TimeTest.php
- tests/system/Session/Handlers/Database/RedisHandlerTest.php
> style: update coding style for PHP CS Fixer 3.18.0

- composer.json
Occasionally, `cs-fix` fails with process time out error. This removes the 5-minute timeout for the code style fixes.
See https://getcomposer.org/doc/06-config.md#process-timeout
**Checklist:**
> chore: add Composer\Config::disableProcessTimeout

- tests/system/CLI/CLITest.php
Fixes #7536 
`time()` is volatile. It may be called on the edges causing difference to be at least 1.
**Checklist:**
> fix: change assertion on CLITest::testWaitZero

- app/Config/App.php
- phpstan-baseline.neon.dist
- system/Commands/Generators/MigrationGenerator.php
- system/Config/Services.php
- system/Session/Handlers/BaseHandler.php
- system/Session/Handlers/DatabaseHandler.php
- system/Session/Handlers/FileHandler.php
- system/Session/Handlers/MemcachedHandler.php
- system/Session/Handlers/RedisHandler.php
- system/Session/Session.php
- system/Test/CIUnitTestCase.php
- system/Test/Mock/MockSession.php
- tests/system/CommonFunctionsTest.php
- tests/system/Security/SecurityCSRFSessionRandomizeTokenTest.php
- tests/system/Security/SecurityCSRFSessionTest.php
- tests/system/Session/Handlers/Database/MySQLiHandlerTest.php
- tests/system/Session/Handlers/Database/PostgreHandlerTest.php
- tests/system/Session/Handlers/Database/RedisHandlerTest.php
- tests/system/Session/SessionTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/installation/upgrade_440.rst
Supersedes #7000
This PR is needed for #7308
Session should not depends on `Config\App`. See https://github.com/codeigniter4/CodeIgniter4/issues/4297#issuecomment-813110373
- remove `Config\App` session items
- add property for `Config\Session` in `Session`
**Checklist:**
> Remove Config\App Session items

- system/Test/TestResponse.php
- fix incorrect PHPDoc types
**Checklist:**
> docs: fix incorrect PHPDoc types in TestResponse

- admin/css/debug-toolbar/toolbar.scss
- app/Config/Events.php
- app/Config/Toolbar.php
- system/Debug/Toolbar/Views/toolbar.css
- system/Debug/Toolbar/Views/toolbar.js
- system/Debug/Toolbar/Views/toolbar.tpl.php
- system/Exceptions/FrameworkException.php
- system/HotReloader/DirectoryHasher.php
- system/HotReloader/HotReloader.php
- system/HotReloader/IteratorFilter.php
- system/Language/en/Core.php
- tests/system/HotReloader/DirectoryHasherTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/testing/debugging.rst
This adds a new "Hot Reload" feature to the debug toolbar. When active, it will scan the app directory for any changes to files and instruct the browser to reload if any changes were found. 
I still need to write tests, but submitting it so that others can try it out first and see if you encounter any problems. I've seen at least one strange thing but unsure if it is just my setup or a more widespread problem. 
**Checklist:**
>  feat: Hot Reloading

- system/HTTP/RequestTrait.php
Supersedes and closes #7606
Fixes Rector check failure like https://github.com/codeigniter4/CodeIgniter4/actions/runs/5372608167/jobs/9746170218
**Checklist:**
> refactor: remove unused non-empty array in RequestTrait

- public/index.php
Checked if current directory is pointing to the front controller's directory.
Only change the directory if they differ because chdir call is not necessary and is not performant.
**Checklist:**
> perf: Change current directory in public/index.php only if necessary

- user_guide_src/source/general/errors.rst
- user_guide_src/source/general/errors/010.php
- user_guide_src/source/general/errors/011.php
Fixes #7628
A named route cannot be used with RedirectException.
**Checklist:**
> docs: fix incorrect description on RedirectException

- rector.php
- system/HTTP/Request.php
- system/HTTP/RequestTrait.php
- tests/system/HTTP/IncomingRequestTest.php
- tests/system/HTTP/RequestTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/installation/upgrade_440.rst
~~Needs #7620~~
- ~~remove `Request::$proxyIPs`~~
- drop support for `Config\App::$proxyIPs = ''` (old Config file)
**Checklist:**
> refactor: drop support for `Config\App::$proxyIPs = ''`

- user_guide_src/source/general/errors.rst
Follow-up #7629
Ref https://github.com/codeigniter4/CodeIgniter4/issues/7628#issuecomment-1610451937
A complete URL will be converted to baseURL by `base_url()`. So it cannot be used with RedirectException since v4.0.0.
```php
<?php
use CodeIgniter\Router\Exceptions\RedirectException;
{
{
throw new RedirectException('https://codeigniter.com/foo/bar');
}
}
```
```
$ curl -v http://localhost:8080/
*   Trying 127.0.0.1:8080...
* connect to 127.0.0.1 port 8080 failed: Connection refused
*   Trying [::1]:8080...
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.87.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 …
```
> docs: fix incorrect description on RedirectException (2)

- user_guide_src/source/general/common_functions.rst
- add keywork `HTST` for search
- add note
**Checklist:**
> docs: improve force_https() description

- user_guide_src/source/general/configuration.rst
- user_guide_src/source/general/logging.rst
- user_guide_src/source/libraries/uploaded_files.rst
- user_guide_src/source/models/entities.rst
- user_guide_src/source/outgoing/localization.rst
- user_guide_src/source/testing/response.rst
For consistency.
**Checklist:**
> docs: change "With" in section titles to lowercase

- system/Router/RouteCollection.php
- system/Router/RouteCollectionInterface.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/installation/upgrade_440.rst
~~Needs #7174~~
~~This PR should go to `4.4` branch.~~
Ref https://github.com/codeigniter4/CodeIgniter4/issues/6889#issuecomment-1402605541
- change `RouteCollection::$routes` structure
Before:
```
* [
*     verb => [
*         routeName => [
*             'route' => [
*                 routeKey(regex) => handler,
*             ],
*         ],
*     ],
*     // redirect route
*     '*' => [
*         routeName => [
*             'route' => [
*                 routeKey(regex)(from) => [routeKey(regex)(to) => handler],
*             ],
*             'redirect' => statusCode,
*         ]
*     ],
* ]
```
After:
```
* [
*     verb => [
*         routeKey(regex) => [
*             'name'    => routeName
*             'handler' => handler,
*             'from'    => from,
* …
```
> perf: RouteCollection $routes optimization

- system/Database/SQLSRV/Connection.php
- user_guide_src/source/database/configuration.rst
database connection is refused when using sqlsrv driver with default port. 
fixed by ignoring the default port ( 1433 )
**Checklist:**
Fixes: https://github.com/codeigniter4/CodeIgniter4/issues/6165
> fix: sqlsrv default port cause connection refuse

- system/CodeIgniter.php
> docs: fix @param in CodeIgniter

- system/HTTP/CURLRequest.php
- tests/system/HTTP/CURLRequestTest.php
This pull request addresses the HTTP proxy problem by adding a new conditional statement to the code. Specifically, the code checks if the output string begins with `HTTP/1.1 200 Connection established`.
For example, when the output string contains the following header:
```sh
HTTP/1.1 200 Connection established
Proxy-Agent: Fortinet-Proxy/1.0
```
If it does, then the code uses `substr` function to remove the initial part of the string up to the specified `$breakString`, which helps in handling the HTTP proxy issue. The added code segment is as follows:
```php
if (strpos($output, 'HTTP/1.1 200 Connection established') === 0) {
$output = substr($output, strpos($output, $breakString) + 4);
}
```
This change ensures that the HTTP proxy connection is handled properly and the …
> fix: skip http proxy added header

- system/BaseModel.php
- system/CodeIgniter.php
- system/Common.php
- system/Model.php
> docs: Replace type `mixed` in system.

- system/Helpers/number_helper.php
- user_guide_src/source/helpers/number_helper.rst
- user_guide_src/source/helpers/number_helper/009.php
- fix param type for `$num`
```php
<?php
declare(strict_types=1);
{
{
helper('number');
echo number_to_roman(23);
}
}
```
The above code causes the type error:
```
TypeError
number_to_roman(): Argument #1 ($num) must be of type string, int given
```
**Checklist:**
> fix: number_to_roman() param type

- app/Config/CURLRequest.php
- user_guide_src/source/installation/upgrade_440.rst
- user_guide_src/source/libraries/curlrequest.rst
- user_guide_src/source/libraries/curlrequest/001.php
This should be `false`.
**Checklist:**
> config: change default value of CURLRequest::$shareOptions

- system/HTTP/CURLRequest.php
- tests/system/HTTP/CURLRequestDoNotShareOptionsTest.php
- tests/system/HTTP/CURLRequestTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/libraries/curlrequest.rst
- user_guide_src/source/libraries/curlrequest/035.php
- add request option `proxy`
**Checklist:**
> feat: [CURLRequest] add option for Proxy

- system/Router/AutoRouterImproved.php
- tests/system/Test/FeatureTestAutoRoutingImprovedTest.php
Follow-up #7543 
See https://forum.codeigniter.com/showthread.php?tid=87818&pid=410558#pid410558
- fix a bug that `$this->params` is not reset for a new HTTP request
**Checklist:**
> fix: [Auto Routing Improved] feature testing may use incorrect param count

- system/Helpers/number_helper.php
phpstan 1.10.22
```
------ ------------------------------------------------------------------------------------- 
Line   system/Helpers/number_helper.php                                                     
------ ------------------------------------------------------------------------------------- 
27     Binary operation "+" between 0 and (array<int, string>|string) results in an error.  
------ ------------------------------------------------------------------------------------- 
```
**Checklist:**
> docs: add @phpstan-ignore-next-line in number_to_size()

- user_guide_src/source/libraries/sessions.rst
- user_guide_src/source/libraries/sessions/037.php
Not recomment to use PHP function.
It is a bad practice.
**Checklist:**
> docs: improve Session::destroy()

- system/Format/FormatterInterface.php
- system/HTTP/ResponseTrait.php
- tests/system/Test/FeatureTestTraitTest.php
- tests/system/Test/TestResponseTest.php
- fix test code
- rename test methods
- fix `@param` types
- delete `FeatureTestTraitTest::testCallWithJsonRequestObject()` and add `testAssertJsonExactObject()`
**Checklist:**
> test: fix TestResponseTest

- app/Config/Cache.php
- user_guide_src/source/general/caching.rst
- user_guide_src/source/libraries/caching.rst
- add missing "Configuring Caching"
**Checklist:**
> docs: add missing "Configuring Caching" in Web Page Caching

- system/Router/AutoRouterImproved.php
- tests/system/Router/AutoRouterImprovedTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/installation/upgrade_440.rst
~~Needs #7406~~
When `$translateURIDashes` is true, two URIs correspond to a single controller method,
one URI for dashes (`foo-bar`) and one URI for underscores (`foo_bar`). 
This is incorrect behavior, contrary to the design philosophy.
This PR prohibits the URI for underscores (`foo_bar`) when `$translateURIDashes` is true.
**Checklist:**
> fix: [Auto Routing Improved] one controller method has more than one URI when $translateURIDashes is true

- system/Router/RouteCollection.php
- tests/system/Helpers/URLHelper/MiscUrlTest.php
Fixes #7651
Before:
> Undefined array key 0
After:
> Missing argument for "([a-zA-Z]+)" in route "([a-zA-Z]+)/login".
**Checklist:**
> fix: `url_to()` error message

- system/Commands/Utilities/Routes.php
- system/Debug/Toolbar/Collectors/Routes.php
- system/Router/DefinedRouteCollector.php
- tests/system/Router/DefinedRouteCollectorTest.php
- extract DefinedRouteCollector
**Checklist:**
> refactor: extract DefinedRouteCollector

- system/Test/FeatureTestTrait.php
- tests/system/Test/FeatureTestTraitTest.php
- user_guide_src/source/changelogs/v4.3.7.rst
- user_guide_src/source/installation/upgrade_437.rst
- user_guide_src/source/testing/feature.rst
Fixes #7593
- fix: when you call `withBodyFormat('json')` and pass `$params` to `call()`,  the values in  `$params` is converted to string.
- fix: REQUEST global is set with a JSON/XML request
- $_REQUEST = $_POST + $_GET. It should be empty if it is a JSON/XML request.
- fix: when calling `withBody()` and `withBodyFormat()`, `Content-Type` is not set
- fix: [BC] change priority for request body
- When you call `withBody($body)->withBodyFormat('json')->call('post', $param)`, `$param` is used for the request body from now on. Previously, `$body` was used.
**Checklist:**
> fix: FeatureTestTrait may change $params values passed to call(), and a few bug fixes

- system/Router/RouteCollection.php
4.4 is broken now. 
- fix merge conflicts from #7652 by https://github.com/codeigniter4/CodeIgniter4/commit/37449d3d3d958c84a506067fd655336a21a7dfa4
**Checklist:**
> fix: [4.4] merge conflict in RouteCollection

- user_guide_src/source/database/configuration/008.php
If devs copy and paste the constructor, it won't work becaseu `parent::__construct();` is missing.
**Checklist:**
> docs: improve sample code in Database Configuration

- system/Commands/Utilities/Routes.php
Follow-up #7653
**Checklist:**
> refactor: remove uneeded `if` in Commands\Utilities\Routes

- user_guide_src/source/installation/running.rst
> docs: improve running.rst

- system/Router/AutoRouterImproved.php
Related #7649
The following refactoring will break the code. 
Two tests will fail:
- AutoRouterImprovedTest::testFindsControllerAndMethodAndParam()
- AutoRouterImprovedTest::testPermitsURIWithUnderscoreParam()
```diff
1) system/Router/AutoRouterImproved.php:294
@@ @@
// Update the positions.
$this->methodPos = $this->paramPos;
-            if ($params === []) {
-                $this->paramPos = null;
-            }
+            $this->paramPos = null;
if ($this->paramPos !== null) {
$this->paramPos++;
}
Applied rules:
* RemoveAlwaysTrueIfConditionRector
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/5449192482/jobs/9913186865
**Checklist:**
- [] Component(s) with PHPDoc blocks, only if …
> docs: [4.4] fix Rector's incorrect refactoring

- phpstan.neon.dist
Default PHPStan parallel process timeout is 600.0 seconds so we should take advantage of the longer time.
https://github.com/phpstan/phpstan-src/blob/2861699cdd2d522ae3062559db6f11335844e3fe/conf/config.neon#L116-L121
**Checklist:**
> Remove `parallel.processTimeout`

- .github/workflows/test-rector.yml
- phpstan.neon.dist
Rector is removing parent connecting node, and the config itself removed at PR:
- https://github.com/rectorphp/rector-src/pull/4415#pullrequestreview-1512291349
in rector-src dev-main, I think it can be removed in here as well already.
**Checklist:**
> [Rector] Remove NodeConnectingVisitor from phpstan config

- system/View/Cell.php
Passing parameters as string and array makes two cache files.
Before:
```
+---------------------------------------------------------+---------------------------------------------------------------------------------+-----------+---------------------+
| Name                                                    | Server Path                                                                     | Size      | Date                |
+---------------------------------------------------------+---------------------------------------------------------------------------------+-----------+---------------------+
| AppCellsMyClassCellshow8fd4938d6f28a83da659a38e14e300b0 | ROOTPATH/writable/cache/AppCellsMyClassCellshow8fd4938d6f28a83da659a38e14e300b0 | 78 Bytes  | 2023-07-06 07:12:17 |
| …
```
> fix: [ViewCells] caching

- utils/Rector/UnderscoreToCamelCaseVariableNameRector.php
`findParentByType()` is removed in latest rector dev-main:
- https://github.com/rectorphp/rector-src/pull/4429/files#diff-a658c135f88f0c6bfdd6a0dc7c25761a25747c595ce47a701fb6f7dc2859c74e
We can now temporary use `findParentType()` instead before it actually gone. This PR is ensure it keep up to date with latest change on rector to ensure no huge change when dependabot trigger on next rector new release.
**Checklist:**
> [Rector] Refactor UnderscoreToCamelCaseVariableNameRector as removed findParentByType()

- system/Router/DefinedRouteCollector.php
- system/Router/RouteCollection.php
- tests/system/Router/DefinedRouteCollectorTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
~~Needs #7653~~
- improve `spark routes` output for View routes
- DebugBar shows View routes
```php
$routes->view('about', 'pages/about');
```
```
+---------+-------------+------+------------------------------+----------------+---------------+
| Method  | Route       | Name | Handler                      | Before Filters | After Filters |
+---------+-------------+------+------------------------------+----------------+---------------+
| GET     | about       | »    | (View) pages/about           |                | toolbar       |
+---------+-------------+------+------------------------------+----------------+---------------+
```
**Checklist:**
> feat: improve View route output

- system/Config/Services.php
- tests/system/Config/ServicesTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
#7630 changed the config param type for `Services::security()`.
So this PR changes the config param type for `Services::session()`.
**Checklist:**
> fix: change Services::session() config param type

- utils/Rector/UnderscoreToCamelCaseVariableNameRector.php
Prepare for next Rector release, as `findParentType()` removed on rector/rector:dev-main.
**Checklist:**
> [Rector] Remove findParentType() on UnderscoreToCamelCaseVariableNameRector

- user_guide_src/source/helpers/form_helper.rst
- user_guide_src/source/models/model.rst
- user_guide_src/source/models/model/027.php
- user_guide_src/source/models/model/028.php
- user_guide_src/source/models/model/029.php
- user_guide_src/source/models/model/038.php
- user_guide_src/source/models/model/040.php
- add sub section titles
- add note for validation placeholders
- add note in form helper
**Checklist:**
> docs: improve In-model Validation

- user_guide_src/source/concepts/factories.rst
- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/general/configuration.rst
- user_guide_src/source/general/modules.rst
`config()` description in multiple places, but keyword search is difficult.
**Checklist:**
> docs: add config() in Global Functions

- user_guide_src/source/libraries/validation/003.php
- user_guide_src/source/libraries/validation/013.php
- user_guide_src/source/libraries/validation/015.php
- user_guide_src/source/libraries/validation/016.php
- user_guide_src/source/libraries/validation/032.php
- user_guide_src/source/libraries/validation/033.php
- add missing `extends BaseConfig`
**Checklist:**
> docs: fix sample code of Config\Validation

- system/View/Cell.php
- tests/_support/View/OtherCells/SampleClass.php
- tests/system/View/CellTest.php
> fix: [ViewCells] when there are cells with the same short name, only the first cell is loaded

- user_guide_src/source/installation/running.rst
- improve document structure
- fix the project folder location for the configuration
**Checklist:**
> docs: improve "Hosting with Apache"

- phpstan-baseline.neon.dist
- system/Router/AutoRouter.php
- system/Router/RouteCollection.php
- system/Router/Router.php
- tests/system/Test/FeatureTestTraitTest.php
- user_guide_src/source/changelogs/v4.3.7.rst
- user_guide_src/source/incoming/routing.rst
See https://forum.codeigniter.com/showthread.php?tid=86977
There is a bug:
- When you enable Auto Routing Legacy, if you `$route->add()`, the controller's other methods are inaccessible from the web browser.
```diff
@@ -19,7 +19,7 @@ $routes->set404Override();
// where controller filters or CSRF protection are bypassed.
// If you don't want to define all routes, please use the Auto Routing (Improved).
// Set `$autoRoutesImproved` to true in `app/Config/Feature.php` and set the following to true.
-// $routes->setAutoRoute(false);
+$routes->setAutoRoute(true);
/*
* --------------------------------------------------------------------
@@ -31,6 +31,8 @@ $routes->set404Override();
// route since we don't …
```
> fix: auto routing legacy and $route->add()

- system/Helpers/number_helper.php
- tests/system/Helpers/NumberHelperTest.php
- user_guide_src/source/changelogs/v4.3.7.rst
replaces https://github.com/codeigniter4/CodeIgniter4/pull/7648
1000 gives 1 thousand and not 1000
1000000 gives 1 million and not 1000 thousand
and so on...
And it compares now the same way like the function number_to_size above
**Checklist:**
> Fix number comparison in number_to_amount() in number_helper.php

- app/Config/Autoload.php
- app/Config/Cache.php
- app/Config/ContentSecurityPolicy.php
- app/Config/Logger.php
- app/Config/Migrations.php
- app/Config/Modules.php
- app/Config/Paths.php
- system/Config/Services.php
`Paths` is immutable, so we do not need to share the instance.
And `config(Paths::class)` is slower than `new Paths()`.
Test | Time | Memory
-- | -- | --
new paths() | 0.0023 | 0 Bytes
config(paths::class) | 0.0182 | 0 Bytes
```php
<?php
use Config\Paths;
{
{
$iterator = new \CodeIgniter\Debug\Iterator();
$iterator->add('new Paths()', static function () {
$config = new Paths();
});
$iterator->add('config(Paths::class)', static function () {
$config = config(Paths::class);
});
return $iterator->run(10000);
}
}
```
Related #7696
**Checklist:**
> refactor:  replace `config(Paths::class)`

- system/BaseModel.php
- system/Validation/Validation.php
- tests/_support/Config/Validation.php
- tests/_support/Models/ValidModelRuleGroup.php
- tests/system/Models/ValidationModelRuleGroupTest.php
- user_guide_src/source/changelogs/v4.3.7.rst
- user_guide_src/source/installation/upgrade_437.rst
Fixes #7689
- fix setValidationRule() cannot use with ruleGroup
- fix cannot set custom error messages with `Config\Validation::$ruleGroup_errors`
**Checklist:**
> fix: [Model] setValidationRule() cannot use with ruleGroup

- rector.php
The `GetMockBuilderGetMockToCreateMockRector` bug was fixed at PR:
- https://github.com/rectorphp/rector-phpunit/pull/205
**Checklist:**
> [Rector] Enable skipped GetMockBuilderGetMockToCreateMockRector on EmailTest.php

- .php-cs-fixer.dist.php
- .php-cs-fixer.no-header.php
- .php-cs-fixer.user-guide.php
`php-cs-fixer` recently adjusted the return types of its `Preg` methods. Yes, that class is internal but `cs-config` depended on that. With the return type change, it used the native `preg_*` functions instead. Since `cs-config` needs `^8.0.1` the fix won't work with 7.4.
**Checklist:**
> Adjust registering of custom fixers for PHP 8.0+ only

- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/general/common_functions/002.php
> docs: improve `old()` description

- app/Config/Routing.php
- system/Config/Routing.php
- system/Debug/BaseExceptionHandler.php
- system/Exceptions/FrameworkException.php
- system/HTTP/SiteURI.php
- system/HotReloader/HotReloader.php
- system/Router/AutoRouterImproved.php
Supersedes #7721
See #7713
- add types to new classes or private methods
**Checklist:**
> refactor: [4.4] add types for phpstan

- composer.json
> chore: `disableProcessTimeout` in `analyze` script

- system/Debug/Toolbar.php
From https://github.com/codeigniter4/CodeIgniter4/pull/7660/commits/6f8f3a21b3eccae7619ad8d6c1abf3c72dd9fc36
I don't know why, but this bug crashes `spark serve` with #7733
**Steps to Reproduce**
Check out #7733. Run `spark serve`.
```
CodeIgniter development server started on http://localhost:8080
Press Control-C to stop.
[Tue Jul 25 14:07:30 2023] PHP 8.1.21 Development Server (http://localhost:8080) started
```
Navigate to http://localhost:8080/, and I see:
>Unable to connect
>Firefox can’t establish a connection to the server at localhost:8080.
```
[Tue Jul 25 14:07:55 2023] [::1]:50620 Accepted
CodeIgniter development server started on http://localhost:8081
Press Control-C to stop.
[Tue Jul 25 14:07:55 2023] PHP 8.1.21 Development Server (http://localhost:8081) …
```
> fix: wrong Config classname to config() in Toolbar

- system/HTTP/IncomingRequest.php
- system/HTTP/SiteURIFactory.php
- system/Superglobals.php
- tests/system/HTTP/SiteURIFactoryDetectRoutePathTest.php
- tests/system/HTTP/SiteURIFactoryTest.php
- tests/system/SuperglobalsTest.php
~~Needs #7252~~
Supersedes #7239
Add `SiteURIFactory` to create the current URI object.
To create the current URI object before the Request object creation. 
Also, to remove all URI adjustment processing currently performed in the constructor of the Request object.
This PR does not change any existing features yet. The next #7282 changes the behavior.
- add `SiteURIFactory::createFromGlobals()`
- add `Superglobals`
**Checklist:**
> feat: add SiteURIFactory

- tests/system/Commands/RoutesTest.php
- tests/system/Commands/Utilities/NamespacesTest.php
Fixes the line ending and directory separators identified for those 2 tests in #7491 
**Checklist:**
> Fix failing tests in Windows for RoutesTest and NamespacesTest

- phpstan-baseline.php
- system/Debug/Exceptions.php
- tests/system/Debug/ExceptionsTest.php
Fixes #7708
- fix: params defined in `$sensitiveDataInTrace` may not be masked
- fix: `maskSensitiveData()` may mask backtrace data like `file`
**Checklist:**
> fix: $sensitiveDataInTrace does not work

- user_guide_src/source/installation/running.rst
~~Needs  #7679~~
Related #7676
- add "Hosting with Subfolder"
**Checklist:**
> docs: add Apache config for baseURL with subfolder

- system/Debug/BaseExceptionHandler.php
- system/Debug/Exceptions.php
- tests/system/Debug/ExceptionHandlerTest.php
Follow-up #7725
`Exception::maskSensitiveData()` has been moved to `BaseExceptionHandler` in 4.4.
**Checklist:**
> fix: [4.4] merge Exception::maskSensitiveData() fix into BaseExceptionHandler

- .php-cs-fixer.dist.php
- .php-cs-fixer.no-header.php
- .php-cs-fixer.user-guide.php
- app/Config/Logger.php
- tests/system/Database/Live/OCI8/CallStoredProcedureTest.php
- tests/system/Database/Live/UpdateTest.php
- tests/system/Database/Live/UpsertTest.php
- tests/system/Test/TestCaseTest.php
> style: Use all available checked tokens for `no_extra_blank_lines`

- app/Config/Kint.php
- app/Controllers/BaseController.php
- app/Controllers/Home.php
- phpstan-baseline.php
See #7731 
See https://kint-php.github.io/kint/settings/
**Checklist:**
> Add types for app

- psalm-baseline.xml
- system/Config/Factories.php
- tests/system/Config/FactoriesTest.php
- tests/system/Database/ModelFactoryTest.php
- tests/system/Test/FabricatorTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/concepts/factories.rst
- user_guide_src/source/concepts/factories/014.php
- user_guide_src/source/concepts/factories/015.php
- user_guide_src/source/general/configuration.rst
- user_guide_src/source/general/modules.rst
- user_guide_src/source/installation/upgrade_440.rst
Fixes #7694
- add `Factories::define()` to explicitly *override* a class
- [BC] `preferApp` works only for no namespaced classname
- [BC] rename `Factories::$basenames` to `$aliases`
I would like to deprecate `preferApp` option.
**Changes**
Property structure:
```php
$basenames = [component => [basename => FQCN]];
↓
$aliases = [component => [alias => FQCN]];
```
*basename* is a short classname, or short classname with sub-directories.
*alias* is a FQCN, short classname, or short classname with sub-directories.
`Factories::define()` sets `$aliases`.
Behavior:
- `model(\Myth\Auth\Models\UserModel::class)` or `model('Myth\Auth\Models\UserModel')`
- before: 
- returns `App\Models\UserModel` if exists and `preferApp` is true
- returns `Myth\Auth\Models\UserModel` if exists and …
> feat: add Factories::define() to explicitly override a class

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.3.7.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_437.rst
Updates changelog and version references for 4.3.7.
Previous version: #7587
New Changelog: TODO 
**Checklist:**
> Prep for 4.3.7 release

- user_guide_src/source/extending/composer_packages.rst
- user_guide_src/source/extending/index.rst
- user_guide_src/source/general/modules.rst
- add "Creating Composer Packages"
**Checklist:**
> docs: add "Creating Composer Packages"

- .github/workflows/test-autoreview.yml
- admin/framework/composer.json
- admin/starter/composer.json
- composer.json
- tests/system/AutoReview/ComposerJsonTest.php
> chore: Add `composer-normalize` to auto-review testing of composer.json

- user_guide_src/source/extending/composer_packages.rst
See https://forum.codeigniter.com/showthread.php?tid=88163&pid=411449#pid411449
**Checklist:**
> docs: add sub section "Choosing License"

- phpstan-baseline.php
- system/Autoloader/Autoloader.php
- tests/system/Autoloader/AutoloaderTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
Ref: https://www.php.net/manual/en/function.spl-autoload-register.php
As a result of this change, this may be a potential BC break. I added this to the changelog. Also marked `@internal` those 2 callbacks.
**Checklist:**
> Return signatures of Autoloader's loaders should be void

- phpstan-baseline.php
- system/Cache/CacheInterface.php
- system/Test/Mock/MockCache.php
> docs: PHPStan `Cache` no type specified

- system/Config/BaseService.php
- system/Config/Services.php
- system/Debug/Exceptions.php
- tests/system/Config/ServicesTest.php
- tests/system/Debug/ExceptionsTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
In 4.3 or before, Request and Response objects are created in `Services::exceptions()` in `CodeIgniter::initialize()`. It is too early, and it created bug #7668.
In 4.4 branch, we have already removed instantiation of Request in `Services::exceptions()`.
This PR removes the instantiation of Response, and both Request and Response objects will be created in `CodeIgniter::run()`.
**Checklist:**
> fix: remove instantiation of Response in `Services::exceptions()`

- phpstan-baseline.php
- system/Events/Events.php
> Dev: remove the `event` ignore errors in phpstan-baseline.php

- phpstan-baseline.php
- system/Config/Services.php
- system/Pager/Pager.php
- system/View/View.php
> fix: [Pager] knocks down variables for View

- system/Autoloader/Autoloader.php
- tests/system/Autoloader/AutoloaderTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
> Remove trimming logic of `Autoloader::loadClass()`

- phpstan-baseline.php
- system/Email/Email.php
> Dev: Remove the `email` ignore errors.

- phpstan-baseline.php
- system/Filters/Filters.php
> Dev: Remove the `Filter` ignore errors in phpstan-baseline.php

- phpstan-baseline.php
- system/Helpers/cookie_helper.php
- system/Helpers/kint_helper.php
- system/Helpers/test_helper.php
> Dev: Remove the Helpers ignore errors in phpstan-baseline.php

- rector.php
`AssertPropertyExistsRector` no longer exists, so it doesn't need to be in skip list.
**Checklist:**
> [Rector] Remove skipped AssertPropertyExistsRector

- phpstan-baseline.php
- tests/system/HTTP/SiteURITest.php
- tests/system/Helpers/ArrayHelperTest.php
- tests/system/View/TableTest.php
`4.4` branch is now broken.
- update phpstan-baseline.php
**Checklist:**
> fix: [4.4] merge

- system/BaseModel.php
- system/Model.php
~~Needs #7759~~
Follow-up #6827
#7759 makes `$tempPrimaryKeyValue` unnecessary.
**Checklist:**
> refactor: remove Model::$tempPrimaryKeyValue

- phpstan-baseline.php
- system/Pager/Exceptions/PagerException.php
- system/Pager/Pager.php
- system/Pager/PagerRenderer.php
- system/Publisher/Exceptions/PublisherException.php
- system/Publisher/Publisher.php
- system/RESTful/BaseResource.php
> Dev: Remove the `Pager`, `Publisher` and `RESTful` ignore errors in phpstan-baseline.php

- phpstan-baseline.php
- system/Images/Exceptions/ImageException.php
- system/Images/Handlers/BaseHandler.php
- system/Images/Handlers/ImageMagickHandler.php
> Dev: Remove the `image` ignore errors in phpstan-baseline.php

- phpstan-baseline.php
- system/Honeypot/Exceptions/HoneypotException.php
- system/Honeypot/Honeypot.php
- system/I18n/TimeTrait.php
> Dev: Remove the `Honeypot` and `I18n` ignore errors in phpstan-baseline.php

- phpstan-baseline.php
- system/Security/Exceptions/SecurityException.php
- system/Validation/Exceptions/ValidationException.php
- system/Validation/Validation.php
- system/Validation/ValidationInterface.php
> Dev: Remove the `Security` and `Validation` ignore errors in phpstan-baseline.php

- phpstan-baseline.php
- system/Encryption/Handlers/SodiumHandler.php
- system/Entity/Entity.php
> Dev: Remove the ignore errors of `Encryption` and `Entity` in phpstan.

- system/Cookie/Cookie.php
- system/Helpers/cookie_helper.php
- user_guide_src/source/helpers/cookie_helper.rst
- user_guide_src/source/libraries/cookies.rst
- user_guide_src/source/libraries/cookies/004.php
- user_guide_src/source/libraries/cookies/006.php
- user_guide_src/source/libraries/cookies/017.php
- user_guide_src/source/libraries/cookies/018.php
- user_guide_src/source/outgoing/response.rst
See https://forum.codeigniter.com/showthread.php?tid=88176
- fix docs
- refactor
**Checklist:**
> docs: improve cookies

- system/BaseModel.php
- tests/system/Models/UpdateModelTest.php
> fix: [Model] updateBatch() may generate invalid SQL statement

- phpstan-baseline.php
- system/Files/Exceptions/FileException.php
- system/Files/Exceptions/FileNotFoundException.php
- system/Files/File.php
**Description** 
See #7731
**Checklist:**
> Fix: Remove the `File` ignore errors.

- phpstan-baseline.php
- system/Traits/PropertiesTrait.php
- system/View/Cell.php
- system/View/Cells/Cell.php
- system/View/Exceptions/ViewException.php
- system/View/Table.php
- system/View/View.php
> Fix: Remove the ignore errors of `View` in phpstan.

- phpstan-baseline.php
- system/Router/AutoRouter.php
- system/Router/RouteCollection.php
- system/Router/Router.php
> Fix: Remove the ignore errors of `Router` in phpstan.

- phpstan-baseline.php
- system/HTTP/CLIRequest.php
- system/HTTP/CURLRequest.php
- system/HTTP/ContentSecurityPolicy.php
- system/HTTP/DownloadResponse.php
- system/HTTP/Files/FileCollection.php
- system/HTTP/Files/UploadedFileInterface.php
- system/HTTP/IncomingRequest.php
- system/HTTP/RequestTrait.php
- system/HTTP/ResponseTrait.php
- system/HTTP/URI.php
- system/HTTP/UserAgent.php
> Fix: Remove the ignore errors of `HTTP` in phpstan.

- public/index.php
- system/CodeIgniter.php
- system/Test/Mock/MockCodeIgniter.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/installation/upgrade_440.rst
The method is not needed.
**Checklist:**
> refactor: move callExit() to index.php

- system/Router/AutoRouterImproved.php
- system/Router/RouteCollection.php
- tests/system/ControllerTest.php
See #7820
- update cs
**Checklist:**
> [4.4] style: update cs

- .github/workflows/deploy-apidocs.yml
Fixes #7821
Fix GPG key to trust in deploy api docs action
Fix below error in GitHub Action.
e.g. https://github.com/codeigniter4/CodeIgniter4/actions/runs/5886110536/job/15963492748
```
sudo phive --no-progress install --global --trust-gpg-keys 67F861C3D889C656 phpDocumentor
shell: /usr/bin/bash -e {0}
env:
COMPOSER_PROCESS_TIMEOUT: 0
COMPOSER_NO_INTERACTION: 1
COMPOSER_NO_AUDIT: 1
Phive 0.15.2 - Copyright (C) 2015-202[3](https://github.com/codeigniter4/CodeIgniter4/actions/runs/5886110536/job/15963492748#step:6:3) by Arne Blankerts, Sebastian Heuer and Contributors
Fetching repository list
Downloading https://phar.io/data/repositories.xml
Downloading https://api.github.com/repos/phpdocumentor/phpdocumentor2/releases?per_page=100
Downloading …
```
> [GitHub Actions] Fix GPG key to trust in deploy api docs action

- system/Validation/Validation.php
- tests/system/Validation/ValidationTest.php
Instances of Validation rules are incremented each time `run()` is executed.
**Checklist:**
> fix: instances of Validation rules are incremented each time `run()` is executed

- .github/workflows/deploy-apidocs.yml
Follow-up #7832 
Fix GitHub Actions Error.
e.g. https://github.com/codeigniter4/CodeIgniter4/actions/runs/5887864586/job/15967978898
```
Run phpDocumentor run --ansi --verbose
PHP Warning:  require(phar:///usr/local/bin/phpDocumentor/bin/phpdoc): Failed to open stream: phar error: no directory in "phar:///usr/local/bin/phpDocumentor/bin/phpdoc", must have at least phar:///usr/local/bin/phpDocumentor/bin/phpdoc/ for root directory (always use full path to a new phar) in /usr/local/bin/phpDocumentor on line 10
PHP Fatal error:  Uncaught Error: Failed opening required 'phar:///usr/local/bin/phpDocumentor/bin/phpdoc' (include_path='.:/usr/share/php') in /usr/local/bin/phpDocumentor:10
Stack trace:
#0 {main}
thrown in /usr/local/bin/phpDocumentor on line 10
Error: Process …
```
> [GitHub Actions] Fix `deploy-apidocs.yml` for phpDocumentor usage

- .github/workflows/deploy-apidocs.yml
fixes #7821
Use `--trust-gpg-keys` option and remove `--global` option for `phive install`
**Checklist:**
ref. #7832, #7833
> [GitHub Actions] Use `--trust-gpg-keys` option and remove `--global` option for phpDocumentor installation

- .github/workflows/deploy-apidocs.yml
Fixes #7821
Use PHP 8.1 for phpDocumentor
fix this error: https://github.com/codeigniter4/CodeIgniter4/actions/runs/5889034105/job/15971401987
```
php tools/phpDocumentor run --ansi --verbose
cp -R ${GITHUB_WORKSPACE}/source/api/build/* ${GITHUB_WORKSPACE}/api/docs
shell: /usr/bin/bash -e {0}
env:
COMPOSER_PROCESS_TIMEOUT: 0
COMPOSER_NO_INTERACTION: 1
COMPOSER_NO_AUDIT: 1
Composer detected issues in your platform:
Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.29.
PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.29. in phar:///home/runner/.phive/phars/phpdocumentor-[3](https://github.com/codeigniter4/CodeIgniter4/actions/runs/5889034105/job/15971401 …
```
> [GitHub Actions] Use PHP 8.1 for phpDocumentor

- app/Config/Paths.php
- psalm-baseline.xml
- public/index.php
- spark
- system/Cache/FactoriesCache.php
- system/Cache/FactoriesCache/FileVarExportHandler.php
- system/CodeIgniter.php
- system/Config/BaseConfig.php
- system/Config/Factories.php
- system/Config/Services.php
- system/HTTP/UserAgent.php
- system/Modules/Modules.php
- tests/system/Cache/FactoriesCacheFileHandlerTest.php
- tests/system/Cache/FactoriesCacheFileVarExportHandlerTest.php
- tests/system/Config/FactoriesTest.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/concepts/factories.rst
- user_guide_src/source/installation/upgrade_440.rst
To improve performance.
How It Works:
- Save the all Config instances in Factories into a cache file before shutdown, if the state of the Config instances in Factories changes.
- Restore cached Config instances before CodeIgniter initialization if a cache is available.
Precautions:
- Once cached, the cache is never expired, and not updated unless the state of the Config instances in Factories changes.
- A change in the state of Config instances in Factories means that a new Config class is instantiated and shared in Factories.
- Therefore, simply changing a existing Config file (or changing Environment Variables for it) will continue to use the Config instance with the old cached values. In that case, you must manually delete the cache file.
- By default, every Config …
> feat: [Factories] Config caching

- system/Filters/Filters.php
- tests/system/Filters/FiltersTest.php
- user_guide_src/source/changelogs/v4.3.8.rst
See https://github.com/codeigniter4/CodeIgniter4/issues/7822#issuecomment-1678597588
This PR changes the behavior:
- `['except' => []]` means to exclude nothing.
- `['except' => '']` means to exclude baseURL only.
- because the URI string `''` means the URI path for the baseURL.
- when navigating to the baseURL, `uri_string()` returns `''`.
---
`['except' => []]` or `['except' => '']` means "except all" in the current code.
This behavior is unexpected, and not good for security.
If a dev comments out all items in `except` key accidentally, the filter will be disabled.
```php
['except' => [
// 'foo/*',
// 'bar/*',
]]
```
**Checklist:**
> fix: filter except empty

- user_guide_src/source/installation/installing_composer.rst
- add how to use next minor version branch
**Checklist:**
> docs: add how to use next minor version branch

- system/Helpers/form_helper.php
- tests/system/Helpers/FormHelperTest.php
Fixes #7814
`set_checkbox()` with default `true` checks unchecked checkbox when redirected back with input.
**Checklist:**
> fix: `set_checkbox()` checks unchecked checkbox

- user_guide_src/source/outgoing/view_parser.rst
- user_guide_src/source/outgoing/view_parser/012.php
- user_guide_src/source/outgoing/view_parser/023.php
Fixed typo in view parser docs for:
- class reference for `renderString()`
- custom filters
- PHP native functions as filters
**Checklist:**
> docs: fixed typo in view-parser

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.3.8.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_438.rst
Updates changelog and version references for 4.3.8.
Previous version: #7749
**Checklist:**
> Prep for 4.3.8 release

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.4.0.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_440.rst
Updates changelog and version references for 4.4.0.
**Checklist:**
> Prep for 4.4.0 release

- .github/scripts/validate-version
Fixes #7854
```console
$ bash .github/scripts/validate-version 4.4.0
CodeIgniter version is updated to v4.4.0
```
**Checklist:**
> chore: fix validate-version

- phpstan-baseline.php
- system/Cache/Handlers/BaseHandler.php
- system/Cache/Handlers/DummyHandler.php
- system/Cache/Handlers/FileHandler.php
- system/Cache/Handlers/MemcachedHandler.php
- system/Cache/Handlers/PredisHandler.php
- system/Cache/Handlers/RedisHandler.php
- system/Cache/Handlers/WincacheHandler.php
- system/CodeIgniter.php
> fix: add types for cache handlers

- user_guide_src/source/installation/upgrade_440.rst
From https://forum.codeigniter.com/showthread.php?tid=88338&pid=412086#pid412086
Add missing upgrade instructions.
**Checklist:**
> docs: add missing Config updates for Hot Reloading

- system/Router/RouteCollection.php
- tests/system/Test/FeatureTestTraitTest.php
From https://forum.codeigniter.com/showthread.php?tid=88353&pid=412136#pid412136
**Checklist:**
> fix: auto route legacy does not work

- system/Config/Factories.php
- tests/system/Config/FactoriesTest.php
If you call `config(AuthJWT::class)` (FQCN) and after that, call `config('AuthJWT')` (shortname),
the new instance is returned even if both are exactly the same class.
And the first shared instance is replaced with the next one.
See https://github.com/codeigniter4/shield/issues/802
**Checklist:**
> fix: Factories may not return shared instance

- app/Config/Autoload.php
- app/Config/DocTypes.php
- app/Config/ForeignCharacters.php
- app/Config/Mimes.php
- app/Config/Modules.php
There is no reason to change the values after the instantiation.
**Checklist:**
> docs: add @immutable to Config classes that do not extend BaseConfig

- system/CLI/CLI.php
- system/Config/Services.php
- system/Database/BaseBuilder.php
- system/Database/Migration.php
- system/Database/Query.php
- system/Debug/Toolbar.php
- system/Encryption/Exceptions/EncryptionException.php
- system/Entity/Entity.php
- system/Format/Exceptions/FormatException.php
- system/HTTP/URI.php
- system/HTTP/UserAgent.php
- system/Images/Handlers/BaseHandler.php
- system/Images/ImageHandlerInterface.php
- system/Log/Handlers/ChromeLoggerHandler.php
- system/Pager/Pager.php
- system/Router/RouteCollectionInterface.php
- system/Test/DOMParser.php
- system/Test/FeatureTestCase.php
- system/Test/FeatureTestTrait.php
- system/Validation/CreditCardRules.php
- system/Validation/FormatRules.php
- system/Validation/Rules.php
- tests/_support/Config/Services.php
php-cs-fixer has been modified to remove these tags.
```
23) tests/_support/Config/Services.php (no_superfluous_phpdoc_tags, phpdoc_trim_consecutive_blank_line_separation)
--- /home/runner/work/CodeIgniter4/CodeIgniter4/tests/_support/Config/Services.php
+++ /home/runner/work/CodeIgniter4/CodeIgniter4/tests/_support/Config/Services.php
@@ -28,8 +28,6 @@
/**
* The URI class provides a way to model and manipulate URIs.
*
-     * @param string $uri
-     *
* @return URI
*/
public static function uri(?string $uri = null, bool $getShared = true)
Found 23 of 875 files that can be fixed in 92.546 seconds, 46.000 MB memory used
Error: Process completed with exit code 8.
```
See …
> docs: fix or remove @param

- system/Common.php
- system/Typography/Typography.php
- tests/system/CommonFunctionsTest.php
- tests/system/Helpers/FormHelperTest.php
- tests/system/Helpers/HTMLHelperTest.php
Supersedes #7860
- fix the error "FactoriesCache undefined method Config\DocTypes::__set_state" when using Config Caching and html helper.
- change `_solidus()` for testing.
**Checklist:**
> fix: replace `config(DocTypes::class)` with `new DocTypes()`

- system/CodeIgniter.php
- system/Test/FeatureTestTrait.php
- tests/_support/Config/Filters.php
- tests/_support/Filters/RedirectFilter.php
- tests/system/Test/FeatureTestTraitTest.php
See https://github.com/codeigniter4/shield/issues/802
```
1) Tests\Authentication\Filters\PermissionFilterTest::testFilterNotAuthorized
Test code or tested code did not (only) close its own output buffers
```
**Checklist:**
> fix: FeatureTest may cause risky tests

- system/Router/RouteCollection.php
- tests/system/Helpers/URLHelper/MiscUrlTest.php
Fixes #7237
Fixes #7876
Fix the error "preg_match(): Compilation failed: missing closing parenthesis" when defining a route with nested parentheses.
**Checklist:**
> fix: reverse routing causes ErrorException

- app/Config/Email.php
- system/Email/Email.php
- user_guide_src/source/libraries/email.rst
> fix: Email library forces to switch to TLS when setting port 465

- admin/css/debug-toolbar/toolbar.scss
- system/Debug/Toolbar/Views/toolbar.css
Make debugbar's `.rotate`-class less broad.
Fixes #7875 
**Checklist:**
> fix: [DebugBar] make rotate class less broad

- system/Test/FeatureTestTrait.php
- tests/system/Test/FeatureTestTraitTest.php
- fix bug that HTTP tests fail (do redirect) when forceGlobalSecureRequests is true
See https://github.com/codeigniter4projects/website/pull/393#pullrequestreview-1604257604
**Checklist:**
> fix: FeatureTest fails when forceGlobalSecureRequests is true

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.4.1.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_441.rst
Updates changelog and version references for 4.4.1.
Previous version: #7852
TODO:
**Checklist:**
> Prep for 4.4.1 release

- user_guide_src/source/libraries/publisher.rst
- user_guide_src/source/libraries/publisher/009.php
1. Fix `$source`, because `realpath('twbs/bootstrap/') `will return `false` and the command will throw an exception. 
2. Added a note that `$destination` must exist. For the same reason - there is an `is_dir()` check inside. When there is no folder, the command will throw an exception
**Checklist:**
> docs: Improve publisher.rst

- user_guide_src/source/dbmgmt/db_commands.rst
> docs: db_commands.rst typo code-block

- app/Config/View.php
- phpstan-baseline.php
- psalm-baseline.xml
- system/Config/View.php
- system/View/Parser.php
See #7731 
References:
- [@phpstan-type](https://phpstan.org/writing-php-code/phpdoc-types#local-type-aliases)
- [callable](https://phpstan.org/writing-php-code/phpdoc-types#callables)
**Checklist:**
> fix: add types to View $filters and $plugins

- user_guide_src/source/general/environments.rst
- user_guide_src/source/general/urls.rst
- user_guide_src/source/installation/running.rst
- user_guide_src/source/tutorial/index.rst
See https://forum.codeigniter.com/showthread.php?tid=88363
- add about `$indexPage`
**Checklist:**
> docs:  improve on Site URIs setting

- system/Database/BaseUtils.php
- system/Database/MySQLi/Utils.php
- system/Database/OCI8/Utils.php
- system/Database/Postgre/Utils.php
- system/Database/SQLSRV/Utils.php
- system/Database/SQLite3/Utils.php
> docs: replace type mixed in DB Utils

- tests/system/Helpers/TextHelperTest.php
- tests/system/View/ParserFilterTest.php
See #7850
E.g.,
```
1) CodeIgniter\Helpers\TextHelperTest::testHighlightCode
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'<code><span style="color: #000000">
-<span style="color: #0000BB">&lt;?php&nbsp;var_dump</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">);&nbsp;</span><span style="color: #0000BB">?&gt;&nbsp;</span>
-</span>
-</code>'
+'<pre><code style="color: #000000"><span style="color: #0000BB">&lt;?php var_dump</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">); </span><span style="color: #0000BB">?&gt; ?&gt;</span></code></pre>'
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Helpers/TextHelpe …
```
> [PHP 8.3] test: update expectation for highlight code

- system/HTTP/IncomingRequest.php
> docs: fix directory separator in comments

- system/Session/Handlers/RedisHandler.php
- tests/system/Session/Handlers/Database/RedisHandlerTest.php
See #7695 
The close function not only needs to delete the lock from redis but also needs to clear the variable value by using releaseLock function.
**Checklist:**
> Fix: [Session] the problem of secondary retrieving values ​​in RedisHandler

- system/Test/ReflectionHelper.php
- tests/system/CLI/CLITest.php
See #7850
- update deprecated code in PHP 8.3
E.g.,
```
1) CodeIgniter\CLI\CLITest::testWindow
ErrorException: Calling ReflectionProperty::setValue() with a single argument is deprecated
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/CLI/CLITest.php:441
```
See https://github.com/codeigniter4/CodeIgniter4/actions/runs/6035726283/job/16376653028?pr=7886
**Checklist:**
> [PHP 8.3] refactor: ReflectionProperty::setValue() signature deprecation

- app/Config/Migrations.php
- system/Commands/Database/MigrateRollback.php
- system/Database/MigrationRunner.php
- user_guide_src/source/changelogs/v4.4.2.rst
- user_guide_src/source/dbmgmt/migration.rst
See #7891
- fix description for `-g` in `spark migrate`, `migrate:refresh`, and `migrate:status`
- remove `-g` option in `spark migrate:rollback` because it does not work (and should not work)
`migrage:rollback`:
```console
$ php spark migrate:status
CodeIgniter v4.4.0 Command Line Tool - Server Time: 2023-09-04 06:10:28 UTC+00:00
+-----------+-------------------+----------------+---------+---------------------+-------+
| Namespace | Version           | Filename       | Group   | Migrated On         | Batch |
+-----------+-------------------+----------------+---------+---------------------+-------+
| App       | 2023-09-04-013453 | DefaultAddBlog | default | 2023-09-04 06:10:26 | 1     |
| App       | 2023-09-04-013454 | Test1AddBlog   | test1   | 2023-09-04 06:10:26 | 1 …
```
> fix: `spark migrate` `-g` option

- composer.json
- phpstan-baseline.php
- phpstan.neon.dist
To disallow `empty()` - it's a very loose comparison (see [manual](https://php.net/empty)), it's recommended to use more strict one. See https://github.com/codeigniter4/CodeIgniter4/pull/7896#issuecomment-1711441144
- add https://github.com/phpstan/phpstan-strict-rules
- enable the rule disallowedConstructs
**Checklist:**
> chore: add phpstan-strict-rules disallowedConstructs

- admin/css/debug-toolbar/_theme-dark.scss
- system/Debug/Toolbar/Views/toolbar.css
> fix: [DebugBar] dark mode `timeline-color-open` color text on `Debug`

- phpstan-baseline.php
- system/Common.php
> fix: types for common functions

- .github/label-conflict.yml
I think this help
**Checklist:**
> GH: auto label conflict PR

- .github/workflows/test-phpunit.yml
See #7850
- add PHP 8.3 to test-phpunit.yml
**Checklist:**
> chore: add PHP 8.3 to test-phpunit.yml

- system/HTTP/CLIRequest.php
- tests/system/Helpers/URLHelper/SiteUrlCliTest.php
Follow-up #7282
From https://forum.codeigniter.com/showthread.php?tid=88410
> assert($currentURI instanceof SiteURI)
> at SYSTEMPATH\Helpers\url_helper.php:34
The following functions (and more) does not work:
- base_url
- site_url
- anchor
**Checklist:**
> fix: base_url()/site_url() does not work on CLI

- phpstan.neon.dist
We already follow the rule.
See https://github.com/phpstan/phpstan-strict-rules/blob/1.5.x/src/Rules/Methods/WrongCaseOfInheritedMethodRule.php
**Checklist:**
> chore: add PHPStan matchingInheritedMethodNames rule

- README.md
- admin/framework/README.md
- admin/starter/README.md
- user_guide_src/source/intro/requirements.rst
Older versions of PHP that are not supported should not be used.
**Checklist:**
> docs: add warning on PHP 7.4 EOL

- user_guide_src/source/installation/backward_compatibility_notes.rst
I would like to remove depreciated features to clean up the code. E.g. #7903
**Checklist:**
> docs: update Backward Compatibility Notes

- user_guide_src/source/installation/upgrade_validations.rst
- add description of incompatible behavior
See https://github.com/bcit-ci/CodeIgniter/blob/63d037565dd782795021dcbd3b1ca6f8c8a509e4/system/libraries/Form_validation.php#L503-L508
**Checklist:**
> docs: add description of incompatible behavior in Validation

- app/Config/Feature.php
- phpstan-baseline.php
- system/CodeIgniter.php
- system/Commands/Utilities/Routes/FilterFinder.php
- system/Filters/Filters.php
- system/Router/RouteCollection.php
- system/Router/Router.php
- tests/system/Commands/Utilities/Routes/FilterFinderTest.php
- tests/system/Filters/FiltersTest.php
- tests/system/Router/RouterTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/installation/upgrade_450.rst
- always enable [multiple filters](https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html#multiple-filters)
- remove related deprecated items
**Checklist:**
> refactor: always use multiple filters

- .github/workflows/label-signing.yml
I think this help
See https://github.com/1Password/check-signed-commits-action
**Checklist:**
> chore: GH: auto comment unsigned PR

- rector.php
- system/Commands/Utilities/Routes/AutoRouterImproved/ControllerMethodReader.php
- system/Email/Email.php
- system/Router/RouteCollection.php
with enable `StringifyStrNeedlesRector`, the cast `(string)` is applied to array data with mixed type. 
This PR apply `@var string[]` so it skipped by `StringifyStrNeedlesRector` correctly.
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#stringifystrneedlesrector
**Checklist:**
> [PHPStan] Add @var string[] on array of string, detected by enable StringifyStrNeedlesRector

- .github/workflows/label-conflict.yml
Based on https://github.com/actions/labeler#permissions and https://github.com/prince-chrismc/label-merge-conflicts-action#faq---how-do-i-fix-resource-not-accessible-by-integration must using event `pull_request_target`
> In order to add labels to pull requests, the GitHub labeler action requires write permissions on the pull-request. However, when the action runs on a pull request from a forked repository, GitHub only grants read access tokens for pull_request events, at most. If you encounter an Error: HttpError: Resource not accessible by integration, it's likely due to these permission constraints. To resolve this issue, you can modify the on: section of your workflow to use [pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-wor …
> chore: fix: event trigger label conflict

- system/Router/RouteCollection.php
This occours because the argument definition is `string $routesFile = APPPATH . 'Config/Routes.php'` (using an slash `/`) and in the constructor `$this->routeFiles` is initialized with `realpath($routesFile)`.
When validating if `$routesFile` exist in the `$routeFiles` array it do not exist, so add it to the `$routeFiles[]` duplicating the path.
**expected**:
```
$routeFiles = [
0 => 'D:\projects\tests\app\Config\Routes.php',
];
```
**result**: 
```
$routeFiles = [
0 => 'D:\projects\tests\app\Config\Routes.php',
1 => 'D:\projects\tests\app\Config/Routes.php',
];
```
**Checklist:**
> Fix: Routing::loadRoutes() in windows do not validate correctly $routesFiles

- system/Commands/Translation/LocalizationFinder.php
- system/Commands/Translation/LocalizationFinder/ArrayHelper.php
- tests/_support/Services/Translation/TranslationFour.php
- tests/_support/Services/Translation/TranslationNested/TranslationFour.php
- tests/_support/Services/Translation/TranslationOne.php
- tests/_support/Services/Translation/TranslationThree.php
- tests/_support/Services/Translation/TranslationTwo.php
- tests/system/Commands/Translation/LocalizationFinder/ArrayHelperTest.php
- tests/system/Commands/Translation/LocalizationFinderTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/outgoing/localization.rst
- user_guide_src/source/outgoing/localization/019.php
Supersedes #7889
See thread https://forum.codeigniter.com/showthread.php?tid=88299
Ready to discuss the solution.
Edit #7889: Start with branch 4.5
**Checklist:**
> feat: Language translations finder and update

- phpstan-baseline.php
- system/Security/Security.php
- tests/system/Security/SecurityCSRFSessionRandomizeTokenTest.php
- tests/system/Security/SecurityCSRFSessionTest.php
- tests/system/Security/SecurityTest.php
- user_guide_src/source/changelogs/v4.4.2.rst
- user_guide_src/source/libraries/security.rst
CSRF check for PUT, PATCH, and DELETE type of requests is made only for JSON data. This PR fixes that by adding the raw input data to check.
**Checklist:**
> fix: check for CSRF token in the raw body

- phpstan-baseline.php
- system/CodeIgniter.php
See #7731 
Supersedes #7884
**Checklist:**
> docs: PHPStan `Codeigniter` no type specified

- system/BaseModel.php
- system/CLI/CLI.php
- system/Format/JSONFormatter.php
- system/Images/Handlers/GDHandler.php
- system/Images/Handlers/ImageMagickHandler.php
- system/Throttle/Throttler.php
- tests/_support/View/Cells/MultiplierCell.php
CodeIgniter/coding-standard#13 already merged and released.
**Checklist:**
> style: run `cs-fix` after rules shorthand operator

- phpstan-baseline.php
- system/Router/RouteCollection.php
Apply PHPStan rule "Short ternary operator is not allowed" to RouteCollection
**Checklist:**
> Refactor: Apply PHPStan rule "Short ternary operator is not allowed" to RouteCollection

- .github/workflows/reusable-coveralls.yml
Fixes #7941
Fixes the following error:
> PHP Fatal error: Uncaught Error: Class "Config\Autoload" not found in /home/runner/work/CodeIgniter4/CodeIgniter4/system/Test/Mock/MockAutoload.php:16
**Checklist:**
> chore: fix Upload coverage results to Coveralls / coveralls

- .github/workflows/test-coding-standards.yml
- .github/workflows/test-phpunit.yml
- .github/workflows/test-rector.yml
- .php-cs-fixer.dist.php
- .php-cs-fixer.no-header.php
- .php-cs-fixer.user-guide.php
- README.md
- admin/framework/README.md
- admin/framework/composer.json
- admin/starter/.github/workflows/phpunit.yml
- admin/starter/README.md
- admin/starter/composer.json
- composer.json
- contributing/pull_request.md
- public/index.php
- spark
- system/Autoloader/Autoloader.php
- tests/system/Debug/TimerTest.php
- tests/system/Helpers/ArrayHelperTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/installation/installing_composer.rst
- user_guide_src/source/installation/upgrade_4xx.rst
- user_guide_src/source/intro/requirements.rst
See #6921
Supersedes #6922
**Checklist:**
> Drop PHP 7.4 support

- user_guide_src/source/libraries/validation.rst
Update validation documentation with a note that ``setRules()`` overwrites any previously set rules
> Add note that setRules() overwrites any previously set rules

- user_guide_src/source/outgoing/response.rst
For consistency.
**Checklist:**
> docs: add `()` after method names

- system/Config/Services.php
`CodeIgniter\Config\Services::request()` should return `Config\Services::incomingrequest()` instead of `static::incomingrequest()` to allow override the `IncomingRequest`
**Checklist:**
> fix: Services::request() should call AppServices instead static

- phpstan-baseline.php
- system/BaseModel.php
- system/Model.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/installation/upgrade_450.rst
- fix incorrect return types
**Checklist:**
> fix: incorrect return type for Model::objectToRawArray()

- system/Validation/Validation.php
- tests/system/Validation/ValidationTest.php
- user_guide_src/source/installation/upgrade_validations.rst
- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/libraries/validation/046.php
- user_guide_src/source/libraries/validation/047.php
For better compatibility to CI3 users. 
**Checklist:**
> feat: [Validation] Callable Rules

- tests/system/Database/Live/ForgeTest.php
See the first error of #7929 
**Checklist:**
> test: fix the testcase error on MariaDB.

- phpstan-baseline.php
- system/CodeIgniter.php
- system/HTTP/IncomingRequest.php
- system/Helpers/form_helper.php
- system/Helpers/url_helper.php
- tests/system/CodeIgniterTest.php
- tests/system/Helpers/URLHelper/MiscUrlTest.php
- tests/system/View/ParserPluginTest.php
Functions and methods should not directly call the `$_SESSION` array but use the `session()` helper to obtain their contents from the `Services::Session` library.
This avoids the need to override code if someone needs to organize the `$_SESSION` array in another way.
**Checklist:**
> refactor: remove $_SESSION from methods and functions

- app/Config/Feature.php
- system/CodeIgniter.php
- system/Commands/Utilities/Routes/FilterFinder.php
- system/Filters/Filters.php
- tests/system/Commands/Utilities/Routes/FilterFinderTest.php
- tests/system/Filters/FiltersTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/incoming/filters.rst
- user_guide_src/source/installation/upgrade_450.rst
Supersedes #7404
The **globals** before filters should be applied first. 
CSRF filter or Auth filter is often defined as globals before filter, and they should run first.
The current order of execution is different from what developers normally assume, and thus may cause security issues.
See https://forum.codeigniter.com/showthread.php?tid=86619, https://github.com/codeigniter4/shield/issues/798
- change filter exec order
- (1) filter group order
- (2) after filter order will be reversed in **route** filters and **filters** filters
- add `Config\Feature::$oldFilterOrder` for backward compatibility
before filters:
```
Previous: route → globals → methods → filters
Now: globals → methods → filters → route
```
after filters:
```
Previous: route → globals → filters
Now: route → …
```
> fix: filter exec order

- system/Language/Language.php
- system/Language/en/Language.php
- tests/system/Language/LanguageTest.php
- user_guide_src/source/changelogs/v4.4.2.rst
See https://github.com/codeigniter4/shield/issues/851
- fix `Language::formatMessage()`
- add lang item `Language.invalidMessageFormat`
**Checklist:**
> fix: lang() may return false

- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.4.2.rst
Fixes #8009
Navigate to `http://localhost:8080/404`, you will get "200 OK" status code.
**Checklist:**
> fix: CI returns "200 OK" when PageNotFound

- system/Debug/Toolbar.php
- remove unnecessary `()`
**Checklist:**
> style: remove unnecessary () in Toolbar

- system/Filters/Filters.php
- user_guide_src/source/changelogs/v4.4.2.rst
- user_guide_src/source/general/modules.rst
- user_guide_src/source/general/modules/015.php
See https://github.com/codeigniter4/CodeIgniter4/pull/7955#issuecomment-1737177748
**Checklist:**
> docs: make discoverFilters() deprecated

- system/CLI/Console.php
- user_guide_src/source/changelogs/v4.4.2.rst
Fix a bug that `spark` may not show exceptions in production mode, or show backtrace as json.
**How to Reproduce**
(1) Setup MySQL and use the default Config (no `.env`). That is `database` is an empty string and in `production` mode.
Before:
```console
CodeIgniter v4.4.1 Command Line Tool - Server Time: 2023-09-25 02:24:59 UTC+00:00
```
After:
```console
CodeIgniter v4.4.1 Command Line Tool - Server Time: 2023-09-25 02:23:08 UTC+00:00
[mysqli_sql_exception]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
at SYSTEMPATH/Database/MySQLi/Connection.php:306
```
(2) Change to `development` mode.
Before:
```console …
```
> fix: spark may not show exceptions or show backtrace as json

- system/CLI/CLI.php
Before:
```console
CodeIgniter v4.4.1 Command Line Tool - Server Time: 2023-09-25 23:24:52 UTC+00:00
[0]  , CONCAT('',`password`) AS `email`
[1]  blog
[2]  migrations
Which table do you want to see? [0, 1, 2]: a
The Which table do you want to see? field must be one of: 0, 1, 2.
```
The last line is strange.
After:
```console
CodeIgniter v4.4.1 Command Line Tool - Server Time: 2023-09-25 23:25:26 UTC+00:00
[0]  , CONCAT('',`password`) AS `email`
[1]  blog
[2]  migrations
Which table do you want to see? [0, 1, 2]: a
The "Which table do you want to see?" field must be one of: 0, 1, 2.
```
**Checklist:**
- [] Component(s) with PHPDoc blocks, only if …
> fix: CLI prompt validation message

- system/Commands/Utilities/Routes/FilterCollector.php
- system/Test/ControllerTestTrait.php
- system/Test/ControllerTester.php
- system/Test/FeatureTestTrait.php
`Services::request()` returns the current Request object.
The parameter `$config` and `$getShared` are deprecated.
https://github.com/codeigniter4/CodeIgniter4/blob/0cd39937d7a8dbd8074237596024adce0fe3c2af/system/Config/Services.php#L508-L525
**Checklist:**
> refactor: replace deprecated `Services::request(config, false)`

- system/Autoloader/Autoloader.php
- system/bootstrap.php
- delete duplicate code
**Checklist:**
> refactor: delete duplicate code for Composer loading

- admin/starter/composer.json
- app/Config/Autoload.php
- composer.json
- system/Autoloader/Autoloader.php
- system/Config/AutoloadConfig.php
- tests/system/Commands/Utilities/NamespacesTest.php
- tests/system/Config/ConfigTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/concepts/autoloader.rst
- user_guide_src/source/concepts/autoloader/001.php
- user_guide_src/source/dbmgmt/migration.rst
- user_guide_src/source/dbmgmt/migration/004.php
- user_guide_src/source/general/modules/001.php
To improve the performance of autoloader.
Benchmark: https://github.com/codeigniter4/CodeIgniter4/pull/8005#issuecomment-1747641598 and https://github.com/codeigniter4/CodeIgniter4/pull/8005#issuecomment-1747686877
- add `App` and `Config` namespaces to `composer.json`
- change the priority of the autoloaders
Before: 1. CI classmap loader, 2. CI PSR-4 autoloader, 3. Composer autoloader
After: 1. Composer autoloader, 2. CI classmap loader, 3. CI PSR-4 autoloader
**Checklist:**
> perf: autoloader

- app/Config/Kint.php
- system/CodeIgniter.php
- user_guide_src/source/installation/upgrade_450.rst
We do not need to share the Config file, or change the values with `.env`.
And if we enable Config Caching, it cannot be loaded from `FactoriesCache` when we run `composer install --no-dev`. 
https://github.com/codeigniter4/CodeIgniter4/blob/efb12a8f2952f9f545fb637653993d523ce86cd7/public/index.php#L51-L53
Because the autoloader for Kint is registered in `CodeIgniter::initialize()`.
https://github.com/codeigniter4/CodeIgniter4/blob/efb12a8f2952f9f545fb637653993d523ce86cd7/system/CodeIgniter.php#L279-L291
**Checklist:**
> fix: error on `Config\Kint` with Config Caching

- system/CLI/CLI.php
- user_guide_src/source/changelogs/v4.4.2.rst
No need to be public.
**Checklist:**
> docs: [CLI] make public properties deprecated 

- system/Commands/Database/ShowTableInfo.php
- system/Database/BaseConnection.php
- tests/system/Commands/Database/ShowTableInfoTest.php
To make it easy to see which database is being connected to.
```console
CodeIgniter v4.4.1 Command Line Tool - Server Time: 2023-09-25 02:52:48 UTC+00:00
+-----------+----------+----------+----------+----------+------+
| hostname  | database | username | DBDriver | DBPrefix | port |
+-----------+----------+----------+----------+----------+------+
| localhost | ci4      | root     | MySQLi   |          | 3306 |
+-----------+----------+----------+----------+----------+------+
...
```
**Checklist:**
> feat: db:table shows db config

- user_guide_src/source/installation/upgrade_440.rst
- The `'` should be removed.
**Checklist:**
> docs: fix typo in upgrade_440

- tests/system/Commands/RoutesTest.php
We cannot change the namespace for Auto Routing Legacy now.
Because `APPPATH . 'Controllers/'` is hard coded.
**Checklist:**
> test: fix incorrect testRoutesCommandRouteLegacy

- phpstan.neon.dist
- system/Config/Factories.php
See https://github.com/CodeIgniter/phpstan-codeigniter/releases/tag/v1.4.0
```
------ ----------------------------------------------------------------------- 
Line   system/CLI/BaseCommand.php                                             
------ ----------------------------------------------------------------------- 
127    Call to function config with Config\Exceptions::class is discouraged.  
💡 Use config('Exceptions') instead to allow overriding.               
------ ----------------------------------------------------------------------- 
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/6490312938/job/17625890673
**Checklist:**
> fix: PHPStan errors

- system/Autoloader/FileLocator.php
- tests/system/Autoloader/FileLocatorTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/installation/upgrade_450.rst
- With this PR, `FileLocator::findQualifiedNameFromPath()` returns a FQCN without leading `\`
FQCN should not start with `\`.
`get_class()` of `::class` returns FQCN without leading `\`.
The following code does not work as expected.:
```php
$class = FileLocator::findQualifiedNameFromPath(...);
if ($class === Foo::class) {
// do something
}
```
**Checklist:**
> fix: `FileLocator::findQualifiedNameFromPath()` behavior

- system/Honeypot/Honeypot.php
- tests/system/Honeypot/HoneypotTest.php
Fixes  #8020 
See https://github.com/codeigniter4/CodeIgniter4/issues/8020#issuecomment-1754561573
The tag like this was added before `</head>` tag in every page. 
```html
<style nonce="ccdd15247e8da0a5b9023a5e">#hpc { display:none }</style>
```
**Checklist:**
> fix: CSP style nonce is added even if honeypot is not attached

- system/CLI/Console.php
> fix: named routes don't work with spark

- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.4.2.rst
It is already not used.
**Checklist:**
> docs: deprecate CodeIgniter::displayCache() param

- phpstan-baseline.php
- system/Database/Forge.php
- tests/system/Database/Live/ForgeTest.php
- user_guide_src/source/changelogs/v4.4.2.rst
> fix: add a primary key to an existing table

- system/Router/RouteCollection.php
- tests/system/Helpers/URLHelper/MiscUrlTest.php
- tests/system/Router/RouteCollectionReverseRouteTest.php
By default, the following code returns `http://localhost:8080/index.php/` (the first route).
```php
<?php
{
{
dd(url_to(''));
}
}
```
There is a test case for an empty string: https://github.com/codeigniter4/CodeIgniter4/blob/0d9460602e79958fc5067473f27486f8d9ad9955/tests/system/Helpers/URLHelper/MiscUrlTest.php#L866
But it passes because no route is registered at the test execution.
**Checklist:**
> fix: reverse route for `''` is not `false`

- phpstan-baseline.php
- system/BaseModel.php
- system/Model.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/installation/upgrade_450.rst
> refactor: remove deprecated methods in Model

- system/Router/RouteCollection.php
- tests/system/Router/RouteCollectionTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/incoming/routing/026.php
- user_guide_src/source/installation/upgrade_450.rst
Supersedes #7981
Fixes #7963
If routes are grouped, the outer filter should be applied to all routes within.
If there is a filter that should be excluded on an inner route, that route should not be defined within the group.
- merge outer `group()` options with inner `group()` options
- outer group filter is merged with inner group filter. See https://github.com/codeigniter4/CodeIgniter4/pull/8033/files#diff-9e755caf334ca07345b43d4fdc3986ac1f9bb9594c6f78ebdec59bc780699b73R344-R368
**Checklist:**
> fix: route options are not merged (outer filter is merged with inner filter)

- system/Router/RouteCollection.php
- tests/system/Router/RouteCollectionTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/incoming/routing/026.php
- user_guide_src/source/installation/upgrade_450.rst
Fixes #7963
- merge outer `group()` options with inner `group()` options
- outer group filter option is not merged with inner group filter option. See https://github.com/codeigniter4/CodeIgniter4/pull/7981/files#diff-9e755caf334ca07345b43d4fdc3986ac1f9bb9594c6f78ebdec59bc780699b73R375-R400
**Checklist:**
> fix: route options are not merged (inner filter overrides outer filter)

- phpstan-baseline.php
- system/CLI/Commands.php
- system/Config/BaseConfig.php
- system/Config/BaseService.php
- system/Config/Factories.php
- system/Filters/Filters.php
- system/Publisher/Publisher.php
~~Needs  #8010~~
To be honest, I am not sure if the speed has increased, but memory consumption has definitely decreased.
Welcome page:
Before:
After:
macOS 12.7
```
$ php -v
PHP 8.1.24 (cli) (built: Sep 28 2023 22:29:09) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.24, Copyright (c) Zend Technologies
with Zend OPcache v8.1.24, Copyright (c), by Zend Technologies
```
**Checklist:**
> perf: replace $locator->getClassname() with findQualifiedNameFromPath()

- system/Autoloader/FileLocator.php
- system/Autoloader/FileLocatorCached.php
- system/Autoloader/FileLocatorInterface.php
- system/CLI/Commands.php
- system/Commands/Utilities/Routes/ControllerFinder.php
- system/Config/BaseService.php
- system/Publisher/Publisher.php
- system/Router/RouteCollection.php
- system/View/Parser.php
- system/View/View.php
- tests/system/Autoloader/FileLocatorCachedTest.php
- tests/system/Autoloader/FileLocatorTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/concepts/autoloader.rst
- user_guide_src/source/concepts/autoloader/004.php
To improve performance.
Benchmark: https://github.com/codeigniter4/CodeIgniter4/pull/8017#issuecomment-1751937870
- add `FileLocatorInterface`
- add `FileLocatorCached`
How to Use:
```php
<?php
namespace Config;
use CodeIgniter\Autoloader\FileLocator;
use CodeIgniter\Autoloader\FileLocatorCached;
use CodeIgniter\Config\BaseService;
class Services extends BaseService
{
public static function locator(bool $getShared = true)
{
if ($getShared) {
if (! isset(static::$instances['locator'])) {
static::$instances['locator'] = new FileLocatorCached(
new FileLocator(static::autoloader())
);
}
return static::$mocks['locator'] ?? static::$instances['locator'];
}
return new FileLocator(static::autoloader());
}
}
```
**Checklist:**
> feat: FileLocator caching

- phpstan-baseline.php
- rector.php
- system/Autoloader/FileLocator.php
- system/BaseModel.php
- system/CLI/CLI.php
- system/CLI/Commands.php
- system/Cache/Handlers/PredisHandler.php
- system/Cache/Handlers/RedisHandler.php
- system/CodeIgniter.php
- system/Config/Factories.php
- system/Debug/ExceptionHandler.php
- system/Debug/Exceptions.php
- system/Encryption/Encryption.php
- system/HTTP/CURLRequest.php
- system/HTTP/SiteURI.php
- system/HTTP/URI.php
- system/Helpers/test_helper.php
- system/Log/Logger.php
- system/Pager/Pager.php
- system/Test/FeatureTestCase.php
- system/Test/FeatureTestTrait.php
- system/Validation/Validation.php
- system/View/View.php
@kenjis @paulbalandan here based on https://github.com/codeigniter4/CodeIgniter4/pull/7943#pullrequestreview-1630449886
I apply `BooleanInIfConditionRuleFixerRector` to ensure pass bool to if cond.
**Checklist:**
> [Rector] Apply BooleanInIfConditionRuleFixerRector

- system/Router/DefinedRouteCollector.php
- tests/system/Router/DefinedRouteCollectorTest.php
- user_guide_src/source/changelogs/v4.4.2.rst
> fix: `spark routes` may show incorrect route names

- user_guide_src/source/libraries/curlrequest.rst
- user_guide_src/source/libraries/curlrequest/026.php
Feedback in Slack.
By default, you cannot see the response body when the response code is 400 or greater.
**Checklist:**
> docs: improve curlrequest.rst

- user_guide_src/source/testing/overview.rst
> docs: add note for routes after calling resetServices()

- tests/system/Database/BaseConnectionTest.php
Fixes #7864
```
1) CodeIgniter\Database\BaseConnectionTest::testStoresConnectionTimings Failed asserting that '0.000000' is greater than 0.0.
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Database/BaseConnectionTest.php:125
```
**Checklist:**
> test: fix assertion in BaseConnectionTest::testStoresConnectionTimings()

- system/Config/Factories.php
- tests/system/Config/FactoriesTest.php
See https://github.com/codeigniter4/CodeIgniter4/pull/8036#issuecomment-1758950847
- fix a bug that `$options` are not saved in cache
- refactor
**Details**
This bug is hidden. Because when restoring the cache, `Config\App` is instantiated and calls:
https://github.com/codeigniter4/CodeIgniter4/blob/da6492d90911db1df8e6c5d7adc0b340226a9636/system/Config/BaseConfig.php#L85
The above code calls `Factories::getOptions()` and it calls `setOptions()` and sets `self::$options['config']`.
Therefore after the instantiation, `Factories::$options['config']` is always set.
But [this change](https://github.com/codeigniter4/CodeIgniter4/pull/8036/files#diff-394cabe11630b173e3c22a66329b36e39d5ec3bd8317a77be2d59856c8cc4d5eL85-R85) removed `config()`. So after the instantiation, …
> fix: Factories caching bug

- system/Debug/Toolbar/Collectors/Files.php
Sort by full path.
Before:
After:
**Checklist:**
> fix: file sort order in Files DebugBar

- phpstan-baseline.php
- system/CodeIgniter.php
- tests/system/CodeIgniterTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- remove deprecated properties and methods
**Checklist:**
> refactor: remove deprecated properties and methods in CodeIgniter class

- .github/workflows/deploy-userguide-latest.yml
- .github/workflows/reusable-phpunit-test.yml
- .github/workflows/test-coding-standards.yml
- .github/workflows/test-phpcpd.yml
- .github/workflows/test-phpunit.yml
- .github/workflows/test-rector.yml
- README.md
- admin/framework/README.md
- admin/framework/composer.json
- admin/starter/.github/workflows/phpunit.yml
- admin/starter/README.md
- admin/starter/composer.json
- composer.json
- contributing/pull_request.md
- public/index.php
- spark
- system/Cookie/Cookie.php
- system/View/Cells/Cell.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/installation/installing_composer.rst
- user_guide_src/source/installation/upgrade_4xx.rst
- user_guide_src/source/intro/requirements.rst
See #7320
Ref #7924
**Checklist:**
> Drop PHP 8.0 support

- admin/framework/composer.json
- composer.json
- system/ThirdParty/Escaper/Escaper.php
Closes #8029
laminas-escaper 2.13 requires PHP 8.1 or later.
https://packagist.org/packages/laminas/laminas-escaper#2.13.0
**Checklist:**
> chore: update laminas-escaper to ^2.13

- system/Config/Factories.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/installation/upgrade_450.rst
See https://github.com/codeigniter4/CodeIgniter4/pull/8037#discussion_r1356646943
**Checklist:**
> fix: make Factories final

- admin/RELEASE.md
> docs: update RELEASE.md

- app/Config/Filters.php
- system/Test/FilterTestTrait.php
- tests/system/Test/FilterTestTraitTest.php
The `$aliases` values can be an array.
See https://codeigniter4.github.io/CodeIgniter4/incoming/filters.html#aliases
**Checklist:**
> fix: FilterTestTrait::getFilterCaller() does not support Filter classes as array

- system/Filters/Filters.php
```diff
1 file with changes
===================
1) system/Filters/Filters.php:620
@@ @@
}
if (is_array($this->config->aliases[$alias])) {
-                $filtersClass = array_merge($filtersClass, $this->config->aliases[$alias]);
+                $filtersClass = [...$filtersClass, ...$this->config->aliases[$alias]];
} else {
$filtersClass[] = $this->config->aliases[$alias];
}
Applied rules:
* LongArrayToShortArrayRector
* ArraySpreadInsteadOfArrayMergeRector (https://wiki.php.net/rfc/spread_operator_for_array)
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/6601535164/job/17932652976
**Checklist:**
> [4.5] refactor: Filters by rector

- user_guide_src/source/changelogs/v4.4.2.rst
- user_guide_src/source/extending/events.rst
- user_guide_src/source/installation/upgrade_4xx.rst
> docs: fix event points descriptions

- system/HTTP/IncomingRequest.php
- user_guide_src/source/changelogs/v4.5.0.rst
~~Needs #8057~~
Fixes #5344
**Checklist:**
> refactor: make IncomingRequest::$uri protected

- user_guide_src/source/changelogs/v4.4.2.rst
- user_guide_src/source/extending/events.rst
- user_guide_src/source/installation/upgrade_4xx.rst
Reverts codeigniter4/CodeIgniter4#8055
> Revert "docs: fix event points descriptions"

- user_guide_src/source/libraries/validation.rst
Also add explanation regarding rule ``uploaded``, that it makes the file upload required.
> Add note that only file rules can be used to validate files

- system/Commands/Generators/ModelGenerator.php
- system/Commands/Generators/Views/model.tpl.php
- tests/system/Commands/ModelGeneratorTest.php
The property `$DBGroup` should only be added to the generated model template when specified as an option: `--dbgroup`.
Fixes #8073 
**Checklist:**
> fix: add dbgroup to model template only when specified as an option

- composer.json
- phpstan-baseline.php
- phpstan.neon.dist
- system/Config/BaseConfig.php
- system/Config/BaseService.php
- tests/system/Cache/FactoriesCacheFileVarExportHandlerTest.php
- tests/system/Config/BaseConfigTest.php
> Update phpstan-codeigniter and fix errors on Modules

- system/Common.php
- user_guide_src/source/concepts/autoloader.rst
- user_guide_src/source/general/helpers.rst
- user_guide_src/source/general/modules.rst
- user_guide_src/source/helpers/index.rst
The helper loading description is still CI3's and differs from the current behavior.
- fix descriptions
- add section "Auto-Discovery and Composer Packages"
- see #8082
**Checklist:**
> docs: fix helper loading

- system/Validation/StrictRules/Rules.php
- tests/system/Validation/RulesTest.php
From Slack
- `exact_length` in traditional rules passes int values
- but `exact_length` in strict rules passes only string values
- it is not intuitive that the rule `‘required|numeric|exact_length[10]` is invalid, and if you pass `1234567890`, you will get the error "The XXX field must be exactly 10 characters in length."
**Checklist:**
> fix: [Validation] exact_length does not pass int values

- user_guide_src/source/models/model.rst
> docs: improve $DBGroup description in Model

- phpstan-baseline.php
- system/BaseModel.php
Closes  #7935
- defer instantiation of Validation in Model
Memory Usage:
```
before: 17392
after:  7216
```
```php
<?php
use CodeIgniter\Model;
{
{
$before = memory_get_usage();
$model = new Model();
$after = memory_get_usage();
return $after - $before;
}
}
```
**Checklist:**
> perf: defer instantiation of Validation in Model

- system/HTTP/Request.php
- system/HTTP/RequestInterface.php
- tests/system/HTTP/CLIRequestTest.php
- tests/system/HTTP/RequestTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- remove deprecated `Request::isValidIP()` and `RequestInterface::isValidIP()`
**Checklist:**
> refactor: remove deprecated Request::isValidIP()

- system/Config/BaseConfig.php
- tests/system/Config/BaseConfigTest.php
Closes #8094
Follow-up #8036
- add `BaseConfig::reset()` for testing
- reset state after testing
```console
$ ./phpunit tests/system/Config/
PHPUnit 9.6.13 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.1.24
Configuration: /.../CodeIgniter4/phpunit.xml
................................................................................................................................. 129 / 140 ( 92%)
...........                                                                                                                       140 / 140 (100%)
Time: 00:05.899, Memory: 22.00 MB
OK (140 tests, 241 assertions)
```
**Checklist:**
> test: fix BaseConfigTest

- system/View/Table.php
- tests/system/View/TableTest.php
> fix: [Table] field named `data` will produce bugged output

- CHANGELOG.md
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.4.3.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_443.rst
Updates changelog and version references for 4.4.3.
Previous version: #8061
**Checklist:**
> Prep for 4.4.3 release

- .github/workflows/test-autoreview.yml
- .github/workflows/test-phpunit.yml
Shorten the names to allow elapsed time to be displayed on PR pages.
Before:
After:
**Checklist:**
> chore: add names to github workflows

- rector.php
- system/Config/BaseService.php
- tests/system/Database/Live/GroupTest.php
Changes `in_array()` with single element to identical check.
**Checklist:**
> [Rector] Apply SingleInArrayToCompareRector

- system/HTTP/ResponseInterface.php
- system/HTTP/ResponseTrait.php
- system/Helpers/cookie_helper.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/helpers/cookie_helper.rst
- user_guide_src/source/outgoing/response.rst
- user_guide_src/source/outgoing/response/023.php
In the docs, the param `$expire` is "Number of seconds until expiration", and the type is `int`:
https://www.codeigniter.com/user_guide/helpers/cookie_helper.html#set_cookie
So it should be `int`, not `string`.
The param `$expires_or_options` for `setcookie()` is also `int`.
https://www.php.net/manual/en/function.setcookie.php
**Checklist:**
> fix: set_cookie() $expire type

- phpstan-baseline.php
- system/Validation/FormatRules.php
- system/Validation/Rules.php
- system/Validation/Validation.php
- tests/system/Validation/CreditCardRulesTest.php
- tests/system/Validation/StrictRules/CreditCardRulesTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/libraries/validation.rst
Fixes #6489
To add `declare(strict_types=1)`. See #8072
There is no guarantee that a string will be passed, so declaring strict types may result in a `TypeError`.
**Checklist:**
> fix: remove traditional validation rule param types

- phpstan-baseline.php
- system/CLI/BaseCommand.php
- system/Commands/Cache/ClearCache.php
- system/Commands/Database/Migrate.php
- system/Commands/Database/MigrateRefresh.php
- system/Commands/Database/MigrateRollback.php
- system/Commands/Encryption/GenerateKey.php
- system/Commands/Generators/CellGenerator.php
- system/Commands/Generators/CommandGenerator.php
- system/Commands/Generators/ConfigGenerator.php
- system/Commands/Generators/ControllerGenerator.php
- system/Commands/Generators/EntityGenerator.php
- system/Commands/Generators/FilterGenerator.php
- system/Commands/Generators/MigrateCreate.php
- system/Commands/Generators/MigrationGenerator.php
- system/Commands/Generators/ModelGenerator.php
- system/Commands/Generators/ScaffoldGenerator.php
- system/Commands/Generators/SeederGenerator.php
- system/Commands/Generators/SessionMigrationGenerator.php
- system/Commands/Generators/ValidationGenerator.php
- system/Commands/Help.php
- system/Commands/Housekeeping/ClearLogs.php
- system/Commands/ListCommands.php
- system/Commands/Server/Serve.php
- system/Commands/Utilities/Environment.php
- system/Commands/Utilities/FilterCheck.php
- system/Commands/Utilities/Namespaces.php
- system/Commands/Utilities/Publish.php
- system/Commands/Utilities/Routes.php
- tests/_support/Commands/Unsuffixable.php
- make array types more accurate
**Checklist:**
> docs: fix @param array type for Commands

- app/Config/Modules.php
- phpstan-baseline.php
- system/Modules/Modules.php
> docs: add correct array signatures for Modules

- system/Commands/Generators/CommandGenerator.php
- tests/system/Commands/CommandGeneratorTest.php
- user_guide_src/source/cli/cli_generators.rst
`CodeIgniter` is already used for the framework commands.
```
CodeIgniter
env                Retrieves the current environment, or set a new one.
filter:check       Check filters for a route.
help               Displays basic usage information.
list               Lists the available commands.
namespaces         Verifies your namespaces are setup correctly.
publish            Discovers and executes all predefined Publisher classes.
routes             Displays all routes.
serve              Launches the CodeIgniter PHP-Development Server.
```
**Checklist:**
> fix: change make:command default $group to `App`

- system/Debug/Exceptions.php
See https://forum.codeigniter.com/showthread.php?tid=88724&pid=413505#pid413505
- add HTTP method and Route in Exception logging
E.g.,
```
CRITICAL - 2023-10-27 21:16:26 --> Allowed memory size of 8388608 bytes exhausted (tried to allocate 20971552 bytes)
[Method: GET, Route: /]
in APPPATH/Controllers/Home.php on line 9.
1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
```
```
CRITICAL - 2023-10-27 21:16:49 --> Allowed memory size of 8388608 bytes exhausted (tried to allocate 20971552 bytes)
[Method: GET, Route: test]
in APPPATH/Controllers/Home.php on line 9.
1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
```
```
CRITICAL - 2023-10-27 23:23:20 --> Allowed memory size of 8388608 bytes exhausted (tried to allocate 10485792 …
```
> feat: add Method/Route logging in exceptionHandler()

- system/CLI/CLI.php
- system/Cache/ResponseCache.php
- system/CodeIgniter.php
- system/Database/BasePreparedQuery.php
- system/Database/Query.php
- system/Email/Email.php
- system/Entity/Cast/DatetimeCast.php
- system/Format/XMLFormatter.php
- system/HTTP/Files/FileCollection.php
- system/HTTP/ResponseInterface.php
- system/Helpers/html_helper.php
- system/Helpers/number_helper.php
- system/Helpers/text_helper.php
- system/I18n/TimeTrait.php
- system/Images/Handlers/BaseHandler.php
- system/Router/RouteCollection.php
- system/Router/Router.php
- system/View/Cell.php
- system/View/Filters.php
- system/View/Parser.php
- tests/system/Commands/ClearDebugbarTest.php
- tests/system/CommonFunctionsSendTest.php
- tests/system/CommonFunctionsTest.php
- tests/system/Debug/Toolbar/Collectors/HistoryTest.php
- tests/system/HTTP/ResponseSendTest.php
- tests/system/HTTP/ResponseTest.php
- tests/system/Helpers/CookieHelperTest.php
- tests/system/Helpers/FilesystemHelperTest.php
- tests/system/Helpers/TextHelperTest.php
- fix types for adding `declare(strict_types=1)`
**Checklist:**
> refactor: fix types

- user_guide_src/source/libraries/validation.rst
> docs: Fix typo in validation.rst

- system/Commands/Utilities/FilterCheck.php
> fix: typo in help message in `spark filter:check`

- system/Debug/Toolbar/Views/toolbar.js
- system/Debug/Toolbar/Views/toolbar.tpl.php
- system/HotReloader/HotReloader.php
When we use the session globally, it can block other requests as they wait for the session to be available for writing. The hot reloader runs in the background as a "long-running process".
This PR may potentially fix: 8093
**Checklist:**
> fix: Hot reloading when session is enabled

- user_guide_src/source/incoming/filters.rst
- user_guide_src/source/incoming/filters/004.php
- user_guide_src/source/incoming/filters/008.php
- small fix in sample code
- small improvement for readability
**Checklist:**
> docs: improve filters

- system/Commands/Utilities/ConfigCheck.php
- tests/system/Commands/Utilities/ConfigCheckTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/general/configuration.rst
~~Needs #8111~~
- add spark `config:check` command to check the current values
We don't know the current values if we look at the Config file.
```console
bash-3.2$ php spark config:check Filters
CodeIgniter v4.4.3 Command Line Tool - Server Time: 2023-10-28 02:00:44 UTC+00:00
Config\Filters#42 (4) (
public 'aliases' -> array (14) [
'csrf' => string (24) "CodeIgniter\Filters\CSRF"
'toolbar' => string (32) "CodeIgniter\Filters\DebugToolbar"
'honeypot' => string (28) "CodeIgniter\Filters\Honeypot"
'invalidchars' => string (32) "CodeIgniter\Filters\InvalidChars"
'secureheaders' => string (33) "CodeIgniter\Filters\SecureHeaders"
'session' => string (38) "CodeIgniter\Shield\Filters\SessionAuth"
'tokens' => string (36) "CodeIgniter\Shield\Filters\TokenAuth"
'hmac' => string (35) …
```
> feat: add `config:check` command to check Config vaules

- system/Validation/Rules.php
Follow-up #8078
Type `?string` still remains in `system/Validation/Rules.php`.
The `differs` and `matches` will be handled in #8122.
**Checklist:**
> fix: remove traditional validation rule param types (2/2)

- admin/css/debug-toolbar/_theme-dark.scss
- contributing/css.md
- system/Debug/Toolbar/Views/toolbar.css
Fixes #8064
Before:
After:
**Checklist:**
> fix: [DebugBar] dark mode timeline "Controller"

- system/Validation/Validation.php
- tests/system/Validation/ValidationTest.php
- user_guide_src/source/changelogs/v4.4.4.rst
- user_guide_src/source/installation/upgrade_444.rst
- user_guide_src/source/installation/upgrade_444/001.php
- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/libraries/validation/009.php
- user_guide_src/source/libraries/validation/010.php
Fixes #8128
Superseds #8126
**Checklist:**
> fix: Validation rule with `*` gets incorrect values as dot array syntax

- app/Config/Generators.php
- system/CLI/GeneratorTrait.php
- system/Commands/Generators/CellGenerator.php
- system/Commands/Generators/CommandGenerator.php
- system/Commands/Generators/ConfigGenerator.php
- system/Commands/Generators/ControllerGenerator.php
- system/Commands/Generators/EntityGenerator.php
- system/Commands/Generators/FilterGenerator.php
- system/Commands/Generators/MigrationGenerator.php
- system/Commands/Generators/ModelGenerator.php
- system/Commands/Generators/SeederGenerator.php
- system/Commands/Generators/ValidationGenerator.php
- tests/_support/Commands/LanguageCommand.php
- tests/_support/Commands/Unsuffixable.php
Closes #7524
- add `$templatePath` property
**Checklist:**
> feat: one generator command could have multiple views

- phpstan-baseline.php
- system/Commands/Translation/LocalizationFinder.php
- system/Helpers/Array/ArrayHelper.php
- system/Helpers/array_helper.php
- tests/system/Helpers/Array/ArrayHelperRecursiveDiffTest.php
- tests/system/Helpers/Array/ArrayHelperTest.php
- move `ArrayHelper` class to `system/Helpers/Array`
- move code from `array_helper.php` to `ArrayHelper.php`
**Checklist:**
> refactor: move ArrayHelper class

- user_guide_src/source/general/ajax.rst
It is not valid that "application/json" and "GET".
The HTTP method names are case-sensitive, and it is not "get" but "GET".
> The method token is case-sensitive because it might be used as a gateway to object-based systems with case-sensitive method names. By convention, standardized methods are defined in all-uppercase US-ASCII letters.
https://www.rfc-editor.org/rfc/rfc9110#name-overview
**Checklist:**
> docs: fix incorrect sample code in ajax.rst

- system/Commands/Generators/Views/controller.tpl.php
See #6310
- fix PHPDoc types in `controller.tpl.php`
**Checklist:**
> fix: PHPDoc types in controller.tpl.php

- tests/system/Commands/Database/ShowTableInfoTest.php
- fix test that waits user input forever
```console
CodeIgniter v4.4.3 Command Line Tool - Server Time: 2023-11-03 04:34:35 UTC+00:00
+-----------+----------+----------+----------+----------+------+
| hostname  | database | username | DBDriver | DBPrefix | port |
+-----------+----------+----------+----------+----------+------+
| localhost | ci4      | root     | MySQLi   |          | 3306 |
+-----------+----------+----------+----------+----------+------+
[0]  migrations
Which table do you want to see? 0: 
```
**Checklist:**
> [4.5] test: fix ShowTableInfoTest::testDbTableShowsDBConfig()

- system/HTTP/ResponseInterface.php
See 
- https://github.com/php-fig/http-message/blob/2.0/src/ResponseInterface.php#L30
- https://github.com/codeigniter4/CodeIgniter4/pull/3946/files#diff-2cab244a084ce08ac666dff9a88aee13003b4170f6c02a690263e3260dac26d8R32
**Checklist:**
> docs: remove unneeded @deprecated in ResponseInterface::getStatusCode()

- phpstan-baseline.php
- system/Cache/Handlers/RedisHandler.php
- system/Session/Handlers/RedisHandler.php
- fix PHPStan 1.10.41 errors
- https://github.com/phpstan/phpstan/releases/tag/1.10.41
```
Error: Comparison operation ">" between (int|Redis|false) and 0 results in an error.
Error: Ignored error pattern #^Only booleans are allowed in a negated boolean, int given\.$# in path /home/runner/work/CodeIgniter4/CodeIgniter4/system/Session/Handlers/RedisHandler.php was not matched in reported errors.
Error: Comparison operation ">" between (int|Redis|false) and 0 results in an error.
------ --------------------------------------------------------------------- 
Line   system/Cache/Handlers/RedisHandler.php                               
------ --------------------------------------------------------------------- 
250    Comparison operation ">" between (int|Redis|false) and 0 …
```
> refactor: RedisHandler ttl() calls

- system/Helpers/Array/ArrayHelper.php
- tests/system/Helpers/Array/ArrayHelperDotKeyExistsTest.php
~~Needs #8130~~
- add helper method to check array key with dot array syntax to implement #8123
**Checklist:**
> feat: add ArrayHelper::dotKeyExists()

- tests/system/Config/BaseConfigTest.php
- tests/system/Database/Live/SelectTest.php
- tests/system/Entity/EntityTest.php
- tests/system/HTTP/CURLRequestDoNotShareOptionsTest.php
- tests/system/HTTP/CURLRequestTest.php
- tests/system/HTTP/IncomingRequestTest.php
- tests/system/Session/Handlers/Database/RedisHandlerTest.php
- tests/system/Throttle/ThrottleTest.php
Run latest rector dev-main to apply `assertEqualsWithDelta()` when possible.
**Checklist:**
> [Testing] Use assertEqualsWithDelta() when possible

- system/Validation/Rules.php
- system/Validation/StrictRules/Rules.php
- tests/system/Validation/RulesTest.php
- tests/system/Validation/StrictRules/RulesTest.php
- user_guide_src/source/changelogs/v4.4.4.rst
- user_guide_src/source/installation/upgrade_444.rst
- fix TypeError in Strict Rules
- fix behaviors
- Strict Rules: https://github.com/codeigniter4/CodeIgniter4/pull/8122/commits/e89fbd8fbf7454e3c6e8d22f4798e266c8493ba4#diff-7418849ccba3c428c9c850f68e98a540d116ead6b80e37e0963290bc861207fe
- Traditional Rules are changed to the same as CI3 behavior: https://github.com/codeigniter4/CodeIgniter4/pull/8122/commits/36c0de9d9040372a3d7e73f4ccceede117033805#diff-cf7521c5d54b849f1a6fab1604700fdb41c3319230f71eab68e5922c099531f9
Note: Adding `?string` in CI4 makes the behavior different from that of CI3. There may be similar bugs in other Traditional Rules.
**Checklist:**
> fix: validation rule `matches` and `differs`
