codeigniter4/CodeIgniter4

- system/Commands/Generators/Views/filter.tpl.php
See #6310 
- fix `@return` in `filter.tpl.php`
**Checklist:**
> fix: `@return` in filter.tpl.php

- user_guide_src/source/incoming/incomingrequest.rst
- user_guide_src/source/libraries/validation.rst
> docs: add warning to `getVar()`

- phpstan-baseline.php
- system/HTTP/IncomingRequest.php
- tests/system/HTTP/IncomingRequestTest.php
- fix bug that when request body is `0`, $body will be null
**Checklist:**
> fix: when request body is `0`, $body will be null

- system/Common.php
- system/Language/Language.php
- fix `@return`
**Checklist:**
> docs: fix return type for lang()

- user_guide_src/source/libraries/security.rst
> docs: add warning about Cookie based CSRF protection

- user_guide_src/source/outgoing/response.rst
- user_guide_src/source/outgoing/response/031.php
- user_guide_src/source/outgoing/response/034.php
- user_guide_src/source/outgoing/response/035.php
- add explanation about redirect and Cookies/Headers
**Checklist:**
> docs: add explanation about redirect and Cookies/Headers

- user_guide_src/source/libraries/security.rst
Fixes #8163
- add warning
Related #8165
**Checklist:**
> docs: add warning on CSRF cookie and redirect()

- phpstan-baseline.php
- system/CLI/CLI.php
- system/Commands/Database/MigrateStatus.php
- system/Database/MigrationRunner.php
- system/Session/Handlers/RedisHandler.php
- system/Test/CIUnitTestCase.php
- system/Validation/Validation.php
- fix types for #8072
**Checklist:**
> [4.5] refactor: fix types

- system/Commands/Utilities/Routes/SampleURIGenerator.php
- tests/system/Commands/Utilities/Routes/SampleURIGeneratorTest.php
Fixes #7997
See https://github.com/codeigniter4/CodeIgniter4/issues/7997#issuecomment-1798317449
**Checklist:**
> fix: `spark routes` outputs <unknown> only when {locale} with `useSupportedLocalesOnly(true)`

- user_guide_src/source/libraries/validation.rst
> docs: [Validation] make it clear these rules accept only ASCII alphabets

- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/incoming/controllers/006.php
Supersedes #8157
`validate()` has many pitfalls and is not recommended.
**Checklist:**
> docs:  add warning to validate() in controller

- user_guide_src/source/incoming/incomingrequest.rst
- user_guide_src/source/incoming/incomingrequest/008.php
- user_guide_src/source/incoming/incomingrequest/010.php
- user_guide_src/source/incoming/incomingrequest/014.php
- user_guide_src/source/incoming/incomingrequest/027.php
- user_guide_src/source/incoming/incomingrequest/028.php
- user_guide_src/source/incoming/incomingrequest/029.php
- user_guide_src/source/incoming/incomingrequest/030.php
- user_guide_src/source/incoming/incomingrequest/031.php
- user_guide_src/source/incoming/incomingrequest/041.php
- user_guide_src/source/incoming/incomingrequest/042.php
- user_guide_src/source/incoming/incomingrequest/043.php
- user_guide_src/source/incoming/incomingrequest/044.php
- user_guide_src/source/incoming/incomingrequest/045.php
The `getVar()` method is complicated and difficult to use.
It is not recommended.
- change the descriptions so that `getVar()` can be deprecated.
- fix small errors.
**Checklist:**
> docs: fix incomingrequest.rst and note to getVar()

- user_guide_src/source/incoming/routing.rst
The `add()` and `map()` are not recommended.
**Checklist:**
> docs: add notes to not recommened methods in routing.rst

- user_guide_src/source/tutorial/create_news_items.rst
- user_guide_src/source/tutorial/create_news_items/005.php
`validate()` is not recommended. See #8157
**Checklist:**
> docs: use validateData() instead of validate() in Tutorial

- system/Commands/Database/ShowTableInfo.php
Before:
```console
CodeIgniter v4.4.3 Command Line Tool - Server Time: 2023-11-08 04:13:04 UTC+00:00
[0]  migrations
Which table do you want to see? 0: a
[ErrorException]
Undefined array key "a"
at SYSTEMPATH/Commands/Database/ShowTableInfo.php:136
Backtrace:
1    SYSTEMPATH/Commands/Database/ShowTableInfo.php:136
CodeIgniter\Debug\Exceptions()->errorHandler(2, 'Undefined array key "a"', '/.../CodeIgniter4/system/Commands/Database/ShowTableInfo.php', 136)
2    SYSTEMPATH/CLI/Commands.php:65
CodeIgniter\Commands\Database\ShowTableInfo()->run([])
3    SYSTEMPATH/CLI/Console.php:46
CodeIgniter\CLI\Commands()->run('db:table', [])
4    ROOTPATH/spark:102
CodeIgniter\CLI\Console()->run()
```
After:
```console
$ php …
```
> fix: Undefined array key error in `spark db:table`

- user_guide_src/source/libraries/validation.rst
`withRequest()` is not recommended.
**Checklist:**
> docs: add notes to not recommened withRequest()

- system/Controller.php
- fix incorrect `@var`
**Checklist:**
> docs: fix `@var` for $validator in Controller

- user_guide_src/source/incoming/filters.rst
- user_guide_src/source/incoming/routing.rst
The current description is inaccurate.
**Checklist:**
> docs: make note for `spark routes` and filters more accurate

- user_guide_src/source/helpers/cookie_helper.rst
- user_guide_src/source/installation/upgrade_4xx.rst
- user_guide_src/source/outgoing/response.rst
Setting Cookies/Headers means setting them to a Response instance.
**Checklist:**
> docs: add explanation for setting cookies/headers

- user_guide_src/source/libraries/curlrequest.rst
It is not recommended.
**Checklist:**
> docs: add note to not recommended `CURLRequest::$shareOptions`

- user_guide_src/source/libraries/validation.rst
They are not recommended.
**Checklist:**
> docs: add note to not recommended Traditional Validation Rules

- user_guide_src/source/extending/core_classes.rst
Update the list.
**Checklist:**
> docs: add missing core classes

- utils/Rector/UnderscoreToCamelCaseVariableNameRector.php
Update left over custom rule: `UnderscoreToCamelCaseVariableNameRector` to inject `phpDocInfoFactory` on `__construct()` instead of from `AbstractRector`
**Checklist:**
> [Rector] Fix deprecated dynamic pull phpDocInfoFactory from AbstractRector on UnderscoreToCamelCaseVariableNameRector

- tests/system/API/ResponseTraitTest.php
- tests/system/Cache/ResponseCacheTest.php
- tests/system/CommonFunctionsTest.php
- tests/system/ControllerTest.php
- tests/system/Filters/InvalidCharsTest.php
- tests/system/HTTP/IncomingRequestDetectingTest.php
- tests/system/HTTP/IncomingRequestTest.php
- tests/system/Helpers/CookieHelperTest.php
- tests/system/Pager/PagerTest.php
- tests/system/RESTful/ResourceControllerTest.php
- tests/system/Security/SecurityCSRFCookieRandomizeTokenTest.php
- tests/system/Security/SecurityCSRFSessionRandomizeTokenTest.php
- tests/system/Security/SecurityCSRFSessionTest.php
- tests/system/Security/SecurityTest.php
- tests/system/Validation/ValidationTest.php
`IncomingRequest` is actually already using `SiteURI`.
**Checklist:**
> test: update tests to use SiteURI

- user_guide_src/source/incoming/routing.rst
- fix method name
**Checklist:**
> docs: add missing `get` in method name in Auto Routing Improved

- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/installation/upgrade_controllers.rst
- add missing explanation
**Checklist:**
> docs: add about Controller returns string/Response

- user_guide_src/source/models/model.rst
> docs: improve Model

- psalm-baseline.xml
- system/Config/View.php
- system/View/Parser.php
I propose to change the naming convention to `@phpstan-type`.
Using snake_case makes it easy to know it is not a classname.
By the way, I don't know why Psalm does not recognize `@phpstan-type`.
**Checklist:**
> docs: change phpstan-type names

- system/Common.php
- tests/system/CommonFunctionsTest.php
> fix: force_https() redirects to wrong URL when baseURL has subfolder

- system/HTTP/Exceptions/HTTPException.php
- system/HTTP/IncomingRequest.php
- system/Language/en/HTTP.php
- tests/system/HTTP/IncomingRequestTest.php
- tests/system/Validation/ValidationTest.php
- user_guide_src/source/changelogs/v4.4.4.rst
~~Needs #8161~~
Fixes #8134
- `IncomingRequest` will throw `HTTPException` when the body is invalid as JSON
- add lang key `HTTP.invalidJSON`.
**Checklist:**
> fix: Validation raises TypeError when invalid JSON comes

- system/Test/FilterTestTrait.php
- tests/system/Test/FilterTestTraitTest.php
Fixes #8113
Follow-up #8058
**Checklist:**
> fix: FilterTestTrait Undefined variable $filterClasses

- tests/system/Validation/ValidationTest.php
```
Error: tests/system/Validation/ValidationTest.php:800:53: UndefinedClass: Class, interface or enum named CodeIgniter\Validation\URI does not exist (see https://psalm.dev/019)
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/6916967990/job/18817589705
```
1) CodeIgniter\Validation\StrictRules\ValidationTest::testJsonInputInvalid
Failed asserting that exception of type "Error" matches expected exception "CodeIgniter\HTTP\Exceptions\HTTPException". Message was: "Class "CodeIgniter\Validation\URI" not found" at
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Validation/ValidationTest.php:800
.
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/6916968004/job/18817590692
**Checklist:**
- [] Component(s) with PHPDoc blocks, only if necessary …
> test: fix failed ValidationTest

- system/Autoloader/FileLocator.php
- tests/system/Autoloader/FileLocatorTest.php
fix issue where running getClassName on a directory would cause a PHP
This issue specifically comes up when you put commands in folders for better organization, the previous setup used `findQualifiedNameFromPath` instead of `getClassname`, `getClassname` has no checking to see if what is passed in is a directory, which could easily happen as `listFiles` can return directories as well as files.
```
An uncaught Exception was encountered
Type:        ErrorException
Message:     file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory
Filename:    vendor/codeigniter4/framework/system/Autoloader/FileLocator.php
Line Number: 122
Backtrace:
-122 - vendor/codeigniter4/framework/system/Autoloader/FileLocator.php::file_get_contents
-104 - …
```
> fix issue where running FileLocator::getClassname() on a directory would cause a PHP error

- system/HTTP/ContentSecurityPolicy.php
- tests/system/HTTP/ContentSecurityPolicyTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/outgoing/csp.rst
- user_guide_src/source/outgoing/csp/014.php
> feat: add CSP clearDirective() to clear existing directive

- system/Common.php
- system/Language/en/Validation.php
- system/Validation/Rules.php
- system/Validation/StrictRules/Rules.php
- system/Validation/Validation.php
- tests/system/Validation/RulesTest.php
- tests/system/Validation/StrictRules/RulesTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/libraries/validation.rst
~~Needs #8131~~
For #8006
- add rule to check if the field exist in the data
**Checklist:**
> feat: [Validation] add `field_exists` rule

- app/Config/App.php
- app/Config/Filters.php
- phpstan-baseline.php
- system/CodeIgniter.php
- system/Config/Filters.php
- system/Debug/Toolbar/Collectors/Routes.php
- system/Filters/Filters.php
- system/Filters/ForceHTTPS.php
- system/Filters/PageCache.php
- system/Filters/PerformanceMetrics.php
- tests/system/CodeIgniterTest.php
- tests/system/Commands/FilterCheckTest.php
- tests/system/Commands/RoutesTest.php
- tests/system/Commands/Utilities/Routes/AutoRouterImproved/AutoRouteCollectorTest.php
- tests/system/Commands/Utilities/Routes/FilterCollectorTest.php
- tests/system/Test/FilterTestTraitTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/incoming/filters.rst
- user_guide_src/source/incoming/filters/013.php
- user_guide_src/source/installation/upgrade_450.rst
- user_guide_src/source/testing/debugging.rst
~~Needs #8050~~
- add "Required Filters" that always run (before filters) before Page Cache check and routing
- add `ForceHTTPS`, `PageCache` and `PerformanceMetrics` as "Required Filters"
- fix benchmark points
**Checklist:**
> feat: new Required Filters

- psalm_autoload.php
```
Error: tests/system/Router/RouteCollectionTest.php:1813:34: UndefinedClass: Class, interface or enum named App\Controllers\Product does not exist (see https://psalm.dev/019)
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/6922932775/job/18830239844
Related #8180
**Checklist:**
> chore: [Psalm] workaround for UndefinedClass 

- psalm_autoload.php
This error does not occur in my environment, so I cannot confirm that it has been resolved.
```
Error: tests/system/Config/BaseConfigTest.php:81:23: UndefinedClass: Class, interface or enum named SimpleConfig does not exist (see https://psalm.dev/019)
Error: Process completed with exit code 2.
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/6794733818/job/18471613113?pr=8175
**Checklist:**
> chore: [Psalm] workaround for UndefinedClass SimpleConfig

- system/CLI/CLI.php
- system/Commands/Database/MigrateStatus.php
- tests/system/Models/InsertModelTest.php
- fix param types for #8072
**Checklist:**
> refactor: fix param types

- user_guide_src/source/helpers/filesystem_helper.rst
- user_guide_src/source/helpers/filesystem_helper/004.php
- add text decration
- add links to PHP manual
**Checklist:**
> docs: improve  filesystem_helper

- system/BaseModel.php
- system/Database/BaseBuilder.php
- system/Model.php
> docs: add PHPDoc types to Model for PHPStan

- system/Database/MigrationRunner.php
- user_guide_src/source/dbmgmt/migration.rst
Related #8221
- clarify that `$db` is for testing purposes
**Checklist:**
> docs: [Migration] clarify that `$db` is for testing purposes

- system/HTTP/RequestTrait.php
- user_guide_src/source/changelogs/v4.4.4.rst
- user_guide_src/source/incoming/incomingrequest.rst
- user_guide_src/source/incoming/request.rst
This method does not work from the beginning, and it was intentional.
```php
{
dd($this->request->getEnv('CI_ENVIRONMENT'));
}
```
```
$this->request->getEnv(...) null
```
**Checklist:**
> fix: make Request::getEnv() deprecated

- system/Database/BaseResult.php
- system/Database/ResultInterface.php
- system/Email/Email.php
- system/HTTP/Files/FileCollection.php
- fix PHPDoc type errors found by Psalm
**Checklist:**
> docs: fix incorrect PHPDoc types

- user_guide_src/source/extending/core_classes/002.php
RouteCollection constructor parameters are out of date in the Creating Core System Classes docs. Minor point, but might save someone a few minutes working out what they should be.
Referenced in <#8204>
**Checklist:**
> docs: update sample code in "Creating Core System Classes"

- tests/_support/Models/UserTimestampModel.php
- tests/system/Models/TimestampModelTest.php
- add tests for the current behaviors.
**Checklist:**
> test: add tests for Model timestamp

- phpstan-baseline.php
- system/BaseModel.php
- system/Model.php
> docs: fix PHPDoc types for Model

- system/Cache/Handlers/FileHandler.php
- tests/system/Cache/Handlers/FileHandlerTest.php
When using some default `prefix` in cache config with `FileHandler` being used, the `increment` function would save the updated result with the key having the prefix twice. To fix it, instead of passing the already prefixed key, now it is passing the non-prefixed key to the save function and save function itself appends the prefix when calling `validateKey`.
**Checklist:**
> fix: [Cache] Double prefix for increment in FileHandler

- user_guide_src/source/testing/overview.rst
- user_guide_src/source/testing/overview/021.php
- add missing Time::setTestNow()
**Checklist:**
> docs: add missing Time::setTestNow()

- user_guide_src/source/models/entities.rst
Entities can also be used for non-database data.
**Checklist:**
> docs: improve Entities

- app/Views/errors/html/error_exception.php
- deptrac.yaml
- system/Cache/ResponseCache.php
- system/Debug/Toolbar.php
- system/HTTP/CURLRequest.php
- system/HTTP/RedirectResponse.php
- system/HTTP/ResponseTrait.php
- tests/system/HTTP/CURLRequestDoNotShareOptionsTest.php
Follow-up #8194
Fixes #5041
**Checklist:**
> fix: use `addHeader()`

- system/Validation/Validation.php
Follow-up #8123
- fix type inconsistency for #8072
**Checklist:**
> refactor: Validation rule field_exists

- system/Pager/PagerRenderer.php
- user_guide_src/source/libraries/pagination.rst
> docs: improve pagination

- system/Commands/Database/ShowTableInfo.php
- system/Database/BaseConnection.php
- system/Database/BaseUtils.php
- system/Database/Postgre/Builder.php
- system/Database/SQLSRV/Connection.php
- fix TypeError for #8072
**Checklist:**
> refactor: fix TypeError in strict mode

- user_guide_src/source/installation/upgrade_sessions.rst
The `timestamp` column type has changed.
- https://codeigniter4.github.io/CodeIgniter4/libraries/sessions.html#creating-database-table
- https://codeigniter.com/userguide3/libraries/sessions.html#database-driver
**Checklist:**
> docs: add about session table change in upgrading from 3.x

- user_guide_src/source/database/utilities.rst
- user_guide_src/source/database/utilities/001.php
- user_guide_src/source/database/utilities/002.php
- user_guide_src/source/database/utilities/003.php
- fix `getXMLFromResult()` description
- add "Initializing the Utility Class"
**Checklist:**
> docs: fix Database Utility Class `getXMLFromResult()`

- user_guide_src/source/database/utilities.rst
- user_guide_src/source/database/utilities/004.php
- user_guide_src/source/database/utilities/005.php
- user_guide_src/source/database/utilities/006.php
- user_guide_src/source/database/utilities/007.php
- user_guide_src/source/database/utilities/008.php
- user_guide_src/source/database/utilities/009.php
- user_guide_src/source/database/utilities/010.php
~~Needs #8276~~
- add missing methods
**Checklist:**
> docs: add DBUtils missing methods

- admin/framework/composer.json
- composer.json
Some extensions are included with PHP. It is better to exclude them from requirements as these are most likely unavailable from package managers.
The details of the extensions can be viewed at https://www.php.net/manual/en/extensions.alphabetical.php.
I recommend to open a new tab for each extension of interest and visit section **Installation** which indicates if it is shipped by default or not.
**Checklist:**
> Exclude default extensions for PHP ^8.1

- CHANGELOG.md
- system/HTTP/CURLRequest.php
- tests/system/HTTP/CURLRequestDoNotShareOptionsTest.php
- tests/system/HTTP/CURLRequestTest.php
- user_guide_src/source/changelogs/v4.4.4.rst
- user_guide_src/source/installation/upgrade_444.rst
Supersedes  #8257
When CURLRequest options 'verify' is set to false, some CURLOPT_SSL_... options should be disabled in such a way as to allow requests to pass through in case the destination is for example on private networks.
Avoids SSL errors: SSL: certificate subject name 'CA' does not match target host name 'localhost'
**Checklist:**
> fix: [CURLRequest] skip hostname checks if options 'verify' false

- system/Commands/Utilities/FilterCheck.php
- system/Commands/Utilities/Routes/FilterCollector.php
- system/Commands/Utilities/Routes/FilterFinder.php
- system/Filters/Filters.php
- tests/system/Commands/FilterCheckTest.php
~~Needs #8235~~
Follow-up #8186
```console
$ ./spark filter:check GET /
CodeIgniter v4.4.3 Command Line Tool - Server Time: 2023-11-20 06:15:09 UTC+00:00
+--------+-------+----------------------+-------------------------------+
| Method | Route | Before Filters       | After Filters                 |
+--------+-------+----------------------+-------------------------------+
| GET    | /     | forcehttps pagecache | pagecache performance toolbar |
+--------+-------+----------------------+-------------------------------+
```
**Checklist:**
> feat: `spark filter:check` shows "Required Filters"

- system/Test/bootstrap.php
> fix: autoload helpers in test bootstrap

- app/Config/Boot/production.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/installation/upgrade_450.rst
There is no reason to change error level only in production.
> In production, you may wish to set this to a less verbose level such as E_ALL & ~E_NOTICE & ~E_DEPRECATED, but in many cases E_ALL is also appropriate, as it may provide early warning of potential issues. 
https://www.php.net/manual/en/language.errors.basics.php#language.errors.basics.handling
**Checklist:**
> config: change the default error reporting level in production

- changelogs/CHANGELOG_4.3.md
- fix dead link
**Checklist:**
> docs: fix CHANGELOG_4.3.md

- user_guide_src/source/libraries/validation.rst
- improve description
**Checklist:**
> docs: improve note in validation.rst

- tests/_support/Test/TestForReflectionHelper.php
- tests/system/Test/ReflectionHelperTest.php
- tests/system/Test/TestCaseTest.php
- fix Psalm error
- fix Class not found
**Checklist:**
> test: fix test code

- user_guide_src/source/general/helpers.rst
- user_guide_src/source/general/helpers/008.php
From https://forum.codeigniter.com/showthread.php?tid=88591&pid=414184#pid414184
**Checklist:**
> docs: improve helpers

- system/Helpers/filesystem_helper.php
- tests/system/Helpers/FilesystemHelperTest.php
- user_guide_src/source/changelogs/v4.4.4.rst
- user_guide_src/source/helpers/filesystem_helper.rst
Supersedes #8225
`get_filenames()` should follow symlinks.
See https://github.com/codeigniter4/CodeIgniter4/pull/8225#issuecomment-1815345901
**Checklist:**
> fix: get_filenames() does not follow symlinks

- system/HTTP/Exceptions/HTTPException.php
- system/Language/en/HTTP.php
- system/Validation/Validation.php
- tests/system/Validation/ValidationTest.php
- user_guide_src/source/changelogs/v4.4.4.rst
> fix: Handle non-array JSON in validation

- phpstan-baseline.php
- system/Controller.php
- user_guide_src/source/changelogs/v4.5.0.rst
- remove deprecated Controller::loadHelpers()
**Checklist:**
> refactor: remove deprecated Controller::loadHelpers()

- system/Security/Security.php
- system/Security/SecurityInterface.php
- user_guide_src/source/changelogs/v4.5.0.rst
- remove deprecated methods in Security
**Checklist:**
> refactor: remove deprecated methods in Security

- phpstan-baseline.php
- system/BaseModel.php
- system/Model.php
- fix and add PHPDoc types
- extract methods
- rename parameter names
**Checklist:**
> refactor: Model

- system/Commands/Translation/LocalizationFinder.php
- system/Helpers/Array/ArrayHelper.php
- tests/_support/Services/Translation/TranslationTwo.php
- tests/system/Commands/Translation/LocalizationFinderTest.php
- tests/system/Helpers/Array/ArrayHelperSortValuesByNaturalTest.php
- user_guide_src/source/outgoing/localization.rst
Superseds #8149 
- Add filepath in list bad keys
- Add natural sorting output values (bad keys)
```console
$ ./spark lang:find --verbose
...
Files found: 10
New translates found: 30
Bad translates found: 5
+------------------------+---------------------------------+
| Bad Key                | Filepath                        |
+------------------------+---------------------------------+
| ..invalid_nested_key.. | app/Controllers/Translation.php |
| .invalid_key           | app/Controllers/Translation.php |
| TranslationBad         | app/Controllers/Translation.php |
| TranslationBad.        | app/Controllers/Translation.php |
| TranslationBad...      | app/Controllers/Translation.php |
+------------------------+---------------------------------+
All operations done!
``` …
> feat: [Commands] `lang:find` show bad keys when scanning (v2)

- admin/framework/composer.json
- composer.json
Reported in https://github.com/codeigniter4/CodeIgniter4/pull/8273#issuecomment-1835500040
- add missing ext-sodium
**Checklist:**
> chore: add missing ext-sodium in suggest

- user_guide_src/source/libraries/email.rst
- add text decoration
- add link to the section
**Checklist:**
> docs: improve email.rst

- system/Commands/Database/ShowTableInfo.php
- system/Database/Config.php
- tests/system/Commands/Database/ShowTableInfoTest.php
- tests/system/Validation/StrictRules/DatabaseRelatedRulesTest.php
https://forum.codeigniter.com/showthread.php?tid=87978
```console
$ ./spark db:table --show --dbgroup tests
CodeIgniter v4.4.3 Command Line Tool - Server Time: 2023-12-04 22:07:51 UTC+00:00
+-----------+----------+----------+----------+----------+------+
| hostname  | database | username | DBDriver | DBPrefix | port |
+-----------+----------+----------+----------+----------+------+
| 127.0.0.1 | ci4_test | root     | MySQLi   | db_      | 3306 |
+-----------+----------+----------+----------+----------+------+
The following is a list of the names of all database tables:
+----+---------------------------+-------------+---------------+
| ID | Table Name                | Num of Rows | Num of Fields |
+----+---------------------------+-------------+---------------+
| 1  | …
```
> feat: add `--dbgroup` option to `spark db:table`

- phpstan-baseline.php
Because of PHPStan upgrade.
```
Error: Ignored error pattern #^Return type \(CodeIgniter\\Database\\MySQLi\\PreparedQuery\) of method CodeIgniter\\Database\\MySQLi\\PreparedQuery\:\:_prepare\(\) should be covariant with return type \(\$this\(CodeIgniter\\Database\\BasePreparedQuery\<TConnection, TStatement, TResult\>\)\) of method CodeIgniter\\Database\\BasePreparedQuery\<mysqli,mysqli_stmt,mysqli_result\>\:\:_prepare\(\)$# in path /home/runner/work/CodeIgniter4/CodeIgniter4/system/Database/MySQLi/PreparedQuery.php was not matched in reported errors.
Error: Ignored error pattern #^Return type \(CodeIgniter\\Database\\OCI8\\PreparedQuery\) of method CodeIgniter\\Database\\OCI8\\PreparedQuery\:\:_prepare\(\) should be covariant with return type …
```
> chore: update phpstan-baseline.php

- system/Test/bootstrap.php
Supersedes  #8314
`COMPOSER_PATH` may be false.
```
PHP Fatal error:  Uncaught TypeError: is_file(): Argument #1 ($filename) must be of type string, bool given in /home/runner/work/CodeIgniter4/CodeIgniter4/system/Autoloader/Autoloader.php:126
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/7148219475/job/19469003051
**Checklist:**
> test: fix COMPOSER_PATH may be false

- system/Honeypot/Honeypot.php
- tests/system/Honeypot/HoneypotTest.php
Reported in https://forum.codeigniter.com/showthread.php?tid=88952
```
[DEPRECATED] str_ireplace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in SYSTEMPATH\Honeypot\Honeypot.php on line 93.
```
**Checklist:**
> fix: DEPRECATED error in Honeypot

- system/Database/BaseBuilder.php
The function returns false on failure, but on success it returns the BaseResult unless the pretend flag is set in the query() function. In that case it returns a Query object. Not having this in the PHPdoc is giving PHPStorm fits.
**Checklist:**
> docs: fix `@return` in BaseBuilder.php

- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/dbmgmt/db_commands.rst
Follow-up #8292
**Checklist:**
> docs: spark db:table --dbgroup

- system/Commands/Utilities/Routes/AutoRouterImproved/ControllerMethodReader.php
- tests/system/Commands/Utilities/Routes/AutoRouterImproved/ControllerMethodReaderTest.php
- tests/system/Commands/Utilities/Routes/AutoRouterImproved/Controllers/Dash_folder/Dash_controller.php
Follow-up #7422
Before:
```
+-----------+-----------------+------+--------------------------------------+----------------+---------------+
| Method    | Route           | Name | Handler                              | Before Filters | After Filters |
+-----------+-----------------+------+--------------------------------------+----------------+---------------+
| GET(auto) | foo_bar/foo_bar |      | \App\Controllers\Foo_bar::getFoo_bar |                | toolbar       |
+-----------+-----------------+------+--------------------------------------+----------------+---------------+
```
After:
```
+-----------+-----------------+------+--------------------------------------+----------------+---------------+
| Method    | Route           | Name | Handler …
```
> fix: [Auto Routing Improved] `spark routes` shows incorrect routes when translateURIDashes is enabled

- system/Router/AutoRouter.php
- system/Router/AutoRouterImproved.php
- system/Router/Router.php
- tests/system/Router/AutoRouterImprovedTest.php
Follow-up #8235
- refactor `AutoRouter` and `AutoRouterImproved` (They are final classes, so these changes are not breaking changes.)
- use `HTTP\Method` in tests
**Checklist:**
> refactor: HTTP verbs in Router

- phpstan-baseline.php
- system/Database/Migration.php
- system/Database/MigrationRunner.php
- tests/system/Database/Migrations/MigrationRunnerTest.php
Closes  #8060
When using custom array connection for migration runner, the migrations ran do not use the custom connection of the runner but instead uses the default shared connection.
**Checklist:**
> fix: migrations not using custom DB connection of migration runner

- app/Config/Routing.php
- phpstan-baseline.php
- system/Commands/Utilities/Routes/AutoRouterImproved/ControllerMethodReader.php
- system/Config/Routing.php
- system/Router/AutoRouterImproved.php
- tests/system/Commands/Utilities/Routes/AutoRouterImproved/ControllerMethodReaderTest.php
- tests/system/Commands/Utilities/Routes/AutoRouterImproved/Controllers/SubDir/BlogController.php
- tests/system/Router/AutoRouterImprovedTest.php
- tests/system/Router/Controllers/BlogController.php
- tests/system/Router/Controllers/SubDir/BlogController.php
- tests/system/Router/Controllers/Subfolder/Sub/BlogController.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/incoming/controllers.rst
This PR adds an option to translate URI dashes to CamelCase controller and method names.
For example, the URI `sub-dir/hello-controller/some-method` will execute the `SubDir\HelloController::getSomeMethod()` method.
**Checklist:**
> feat: [Auto Routing Improved] add option to translate uri to camel case

- user_guide_src/source/models/model.rst
> docs: improve Model Event

- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/libraries/validation/001.php
- `validate()` is not recommended
**Checklist:**
> docs: use validateData() instead of validate() in Validation

- system/Commands/Utilities/Routes.php
- tests/system/Commands/RoutesTest.php
~~Needs #8235, #8236~~
Follow-up #8053
```console
$ ./spark routes
CodeIgniter v4.4.3 Command Line Tool - Server Time: 2023-11-20 07:17:40 UTC+00:00
+--------+-------+------+------------------------------+----------------+---------------+
| Method | Route | Name | Handler                      | Before Filters | After Filters |
+--------+-------+------+------------------------------+----------------+---------------+
| GET    | /     | »    | \App\Controllers\Home::index |                |               |
+--------+-------+------+------------------------------+----------------+---------------+
Required Before Filters: forcehttps, pagecache
Required After Filters: pagecache, performance, toolbar
```
**Checklist:**
> feat: `spark routes` shows "Required Filters"

- app/Config/Feature.php
- phpstan-baseline.php
- system/BaseModel.php
- system/Database/BaseBuilder.php
- system/Database/SQLSRV/Builder.php
- system/Model.php
- tests/system/Database/Builder/GetTest.php
- tests/system/Database/Live/GetTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/database/query_builder.rst
- user_guide_src/source/installation/upgrade_450.rst
- user_guide_src/source/installation/upgrade_database.rst
Fixes #8278
- `LIMIT` can be used in MySQL, SQLite3, PostgreSQL, and they return 0 rows when we specify `LIMIT 0`.
- `limit()` is to limit the result rows. So when we specify it, the result should be limited, not be all rows.
> LIMIT 0 quickly returns an empty set. This can be useful for checking the validity of a query.
https://dev.mysql.com/doc/refman/5.7/en/limit-optimization.html
**Checklist:**
> fix: QueryBuilder limit(0) bug

- app/Config/Boot/development.php
- app/Config/Boot/testing.php
- spark
Replaces `error_reporting(-1);` with `error_reporting(E_ALL);` for better readability.
**Checklist:**
- [O] Unit testing, with >80% coverage
- [O] User guide updated
- [O] Conforms to style guide
O = does not apply
> replace -1 with E_ALL in error_reporting calls

- system/I18n/Time.php
- system/I18n/TimeLegacy.php
- system/I18n/TimeTrait.php
- add `@property`
See https://codeigniter4.github.io/CodeIgniter4/libraries/time.html#getters
Related #8338
**Checklist:**
> docs: add @property to Time

- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/incoming/routing/011.php
- user_guide_src/source/incoming/routing/045.php
- user_guide_src/source/incoming/routing/046.php
- user_guide_src/source/incoming/routing/049.php
- user_guide_src/source/incoming/routing/050.php
- user_guide_src/source/incoming/routing/051.php
- user_guide_src/source/incoming/routing/052.php
- user_guide_src/source/incoming/routing/068.php
- add sample code with variable-length argument lists for multiple URI segments matched a placeholder
**Checklist:**
> docs: improve routing

- user_guide_src/source/libraries/validation.rst
Add explanation about the placement of error messages if the dev needs to change the default for his/her project. 
**Checklist:**
> Add explanation on changing default error messages

- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/incoming/controllers/015.php
Follow-up #8329
- update config sample
**Checklist:**
> docs: update config files for Auto Routing in controllers.rst

- user_guide_src/source/libraries/validation.rst
Modified explanation where to place default error messages for custom validation rules, since current explanation was somewhat incomplete and misleading.
**Checklist:**
> docs: [Validation] Add explanation where to place custom validation rules error messages

- tests/system/View/ParserFilterTest.php
- user_guide_src/source/outgoing/view_parser.rst
- fix docs
- add test cases
**Checklist:**
> docs: fix Parser filter `default` explanation

- system/Autoloader/FileLocatorInterface.php
- system/Test/FeatureTestTrait.php
Follow-up: https://github.com/codeigniter4/CodeIgniter4/commit/ed4fce13abb12cf37950e53230729b42081dfafe
- fix merge mistake in FeatureTestTrait
- docs: update `@param` in FileLocatorInterface
**Checklist:**
> [4.5] fix: merge mistake

- admin/framework/composer.json
- composer.json
Temporarily fix the version because of conflicts between php-cs-fixer updates and a Rector rule.
See https://github.com/codeigniter4/CodeIgniter4/pull/8367#issuecomment-1868853441
**Checklist:**
> chore: fix php-cs-fixer version to 3.41.*

- user_guide_src/source/installation/upgrade_4xx.rst
From https://forum.codeigniter.com/showthread.php?tid=88993
- add "Error Handling" in "Upgrading from 3.x to 4.x"
See
- https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/Common.php#L600
- https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Debug/Exceptions.php#L202
**Checklist:**
> docs: add "Error Handling" in "Upgrading from 3.x to 4.x"

- phpstan-baseline.php
- system/Test/DOMParser.php
- tests/system/Test/DOMParserTest.php
- fix bug with `empty()`
**Checklist:**
> fix: DOMParser cannot see element with `id="0"`

- tests/system/View/TableTest.php
> test: add missing test case in HTML Table

- tests/_support/Entity/Cast/CastBase64.php
```diff
1 file with changes
===================
1) tests/_support/Entity/Cast/CastBase64.php:21
@@ @@
*
* @param mixed $value  Data
* @param array $params Additional param
-     *
-     * @return mixed
*/
public static function get($value, array $params = []): string
{
@@ @@
*
* @param mixed $value  Data
* @param array $params Additional param
-     *
-     * @return mixed
*/
public static function set($value, array $params = []): string
{
Applied rules:
* RemoveUselessReturnTagRector
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/7324536612/job/19948207442?pr=8364
**Checklist:**
> test: fix PHPDoc types in CastBase64

- system/View/ViewDecoratorTrait.php
Use `View::$config` instead of  `config()` function
> refactor: rely on $config property in ViewDecoratorTrait

- system/Commands/Generators/TestGenerator.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/cli/cli_generators.rst
Follow-up #8333
- add missing docs
- fix help message
**Checklist:**
> fix: make:test help and docs

- system/Cache/ResponseCache.php
- system/HTTP/Method.php
- tests/system/Cache/ResponseCacheTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/general/caching.rst
Closes  #8363
Enhancement to https://codeigniter4.github.io/CodeIgniter4/general/caching.html
- add HTTP method to page cache key
The current issue:
If we use RESTful Resource Handling, operation *Create* and *List* have the same URI.
https://codeigniter4.github.io/CodeIgniter4/incoming/restful.html#presenter-controller-comparison
If we enable page caching to List (GET), Create (POST) will return the cached List response.
**Checklist:**
> feat: HTTP method-aware web page caching

- .github/workflows/test-phpcpd.yml
- app/Config/Kint.php
- phpstan-baseline.php
- system/API/ResponseTrait.php
- system/Autoloader/FileLocator.php
- system/BaseModel.php
- system/CodeIgniter.php
- system/Model.php
- system/RESTful/ResourceController.php
- system/Session/Session.php
- system/Test/CIUnitTestCase.php
- system/Test/DatabaseTestTrait.php
- system/Test/Fabricator.php
- system/Test/FeatureTestCase.php
- system/Test/Mock/MockCache.php
- system/Test/Mock/MockConnection.php
- system/Test/TestResponse.php
- system/Validation/CreditCardRules.php
- system/Validation/Rules.php
- system/Validation/StrictRules/Rules.php
- system/Validation/Validation.php
- system/Validation/Views/list.php
- system/View/Filters.php
- system/View/Parser.php
- system/View/Table.php
- system/View/View.php
~~Needs #8344~~
- replace empty()
**Checklist:**
> refactor: replace empty() Part 1

- user_guide_src/source/libraries/official_packages.rst
Updated the official packages page: 
- updated URLs of Shield and Settings to the new sub-domains. 
- Added information about Tasks and Queue. 
My big question is whether the team thinks we should hold off adding Tasks and Queue until we get an official beta version out.
> docs: update official packages page

- CHANGELOG.md
- phpdoc.dist.xml
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.4.4.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_444.rst
Updates changelog and version references for 4.4.4.
Previous version: #8097
**Checklist:**
> Prep for 4.4.4 release

- tests/system/Commands/Utilities/ConfigCheckTest.php
When `xdebug.cli_color` is set to `2`, Xdebug forces adding colors on overloaded `var_dump()` calls, causing tests to fail.
```
1) CodeIgniter\Commands\Utilities\ConfigCheckTest::testGetVarDump
Failed asserting that 'class Config\App#22494 (12) {\n
public string $baseURL =>\n
string(19) "http://example.com/"\n
public array $allowedHostnames =>\n
array(0) {\n
}\n
public string $indexPage =>\n
string(9) "index.php"\n
public string $uriProtocol =>\n
string(11) "REQUEST_URI"\n
public string $defaultLocale =>\n
string(2) "en"\n
public bool $negotiateLocale =>\n
bool(false)\n
public array $supportedLocales =>\n
array(1) {\n
[0] =>\n
string(2) "en"\n
}\n
public string $appTimezone =>\n
string(3) "UTC"\n
public string $charset =>\n
string(5) "UTF-8"\n
public bool …
```
> test: strip colors on `xdebug.cli_color=2`

- user_guide_src/source/changelogs/v4.4.4.rst
"Enhancements" is located in the wrong place.
https://codeigniter4.github.io/CodeIgniter4/changelogs/v4.4.4.html
**Checklist:**
> docs: fix section title level in v4.4.4.rst

- tests/system/AutoReview/ComposerJsonTest.php
Fixes wrong clean path of composer.json in `admin/` folder.
To test, just change any version constraint of a `require-dev` dependency in the root composer.json.
**Checklist:**
> test: fix path name of composer.json

- system/Session/Session.php
After upgrading 4.4.3 to 4.4.4 a bug are coming, spark not launching the CI with cmd. php spark server*
Error log: 
Undefined global variable $_SESSION
at SYSTEMPATH\Session\Session.php:499
Backtrace:
1    SYSTEMPATH\Session\Session.php:499
CodeIgniter\Debug\Exceptions()->errorHandler(2, 'Undefined global variable $_SESSION', 'C:\\wamp64\\www\\system\\Session\\Session.php', 499)
My fix working with no errors and launching correctly CI.
**Checklist:**
> Fix bug 4.4.4 `spark serve` not working when using Session in Routes.php

- tests/system/Encryption/EncryptionTest.php
For contributors, when running `EncryptionTest` and there is a `.env` file in the root, tests will fail because of a set encryption key.
```
There were 2 failures:
1) CodeIgniter\Encryption\EncryptionTest::testConstructor
Failed asserting that a string is empty.
/Users/paul/Workspace/CodeIgniter4/tests/system/Encryption/EncryptionTest.php:61
2) CodeIgniter\Encryption\EncryptionTest::testServiceWithoutKey
Failed asserting that exception of type "CodeIgniter\Encryption\Exceptions\EncryptionException" is thrown.
```
This PR will backup the `.env` and unset any environment variables already set by the file.
**Checklist:**
> test: ensure no .env when EncryptionTest is run

- .github/prlint.json
Enforce Conventional Commit format of PR title using [PRLint Reloaded](https://github.com/marketplace/prlintreloaded)
Step 1: Allow access to the `codeigniter4` org then to this repo for the app (I have no rights to do so)
Step 2: Merge this PR to let the configuration kick in
For the regex reference: https://regex101.com/r/Yh1iT9/1
**Checklist:**
> chore: enforce PR title format with PRLint Reloaded

- system/View/Table.php
- refactor to fix PHPStan error
**Checklist:**
> refactor: Table class to fix phpstan errors

- phpstan-baseline.php
- system/Pager/Views/default_simple.php
`getnext` -> `getNext`
**Checklist:**
> fix: typo in pager default_simple

- .github/workflows/reusable-phpunit-test.yml
- .github/workflows/test-phpunit.yml
To fix the upload-artifact error.
See https://github.com/codeigniter4/CodeIgniter4/pull/8417#issuecomment-1893209525
**Checklist:**
> [4.5] chore: fix phpunit.yml

- admin/framework/composer.json
- composer.json
- phpstan-baseline.php
- system/Database/SQLite3/Table.php
- tests/system/Database/Live/SQLite/GetIndexDataTest.php
- tests/system/Debug/ExceptionsTest.php
- tests/system/View/ViewTest.php
Follow-up #8416
Supersedes #8420
- update php-cs-fixer
- update style
**Checklist:**
> chore: update php-cs-fixer to v3.47.1

- phpstan-baseline.php
- system/Files/File.php
- fix incorrect case
**Checklist:**
> style: fix incorrect case method name `SplFileInfo-getBaseName()`

- system/Validation/DotArrayFilter.php
- tests/system/Validation/DotArrayFilterTest.php
Supersedes #8414
The use of array_merge_recursive rewrites numerically indexed values when attempting to retrieve validated data. Use of the array_replace_recursive preserves their ordering. [For an in-depth explanation and test harness](https://forum.codeigniter.com/showthread.php?tid=89132&pid=414939). There appears to be a similar issue in [Laravel](https://github.com/laravel/framework/issues/24332).
**Checklist:**
> fix: [Validation] DotArrayFilter returns incorrect array when numeric index array is passed

- user_guide_src/requirements.txt
```
Running Sphinx v4.5.0
Sphinx version error:
The sphinxcontrib.devhelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
make: *** [Makefile:20: html] Error 2
Traceback (most recent call last):
File "/entrypoint.py", line 22, in <module>
action.build_all_docs(github_env, [os.environ.get("INPUT_DOCS-FOLDER")])
File "/sphinx_action/action.py", line 167, in build_all_docs
raise RuntimeError("Build failed")
RuntimeError: Build failed
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/7564707135/job/20599261845
**Checklist:**
> chore: update Sphinx version to 5.3

- tests/system/Database/Live/SQLite/GetFieldDataTest.php
- tests/system/Database/Live/SQLite3/AlterTableTest.php
- tests/system/Database/Live/SQLite3/GetFieldDataTest.php
- tests/system/Database/Live/SQLite3/GetIndexDataTest.php
- add test
- refactor tests
**Checklist:**
> test: add test for SQLite3 getFieldData()

- phpstan-baseline.php
- system/Database/Forge.php
- system/Database/MySQLi/Forge.php
- system/Database/OCI8/Forge.php
- system/Database/Postgre/Forge.php
- system/Database/SQLSRV/Forge.php
- system/Database/SQLite3/Forge.php
- system/Database/SQLite3/Table.php
- rename variable names
**Checklist:**
> refactor: improve Forge variable names

- system/Database/OCI8/Forge.php
- fix a bug that OCI8 Forge always sets `NOT NULL` when `BOOLEAN` is specified. See https://github.com/codeigniter4/CodeIgniter4/pull/8439#issuecomment-1902546711
**Checklist:**
> fix: OCI8 Forge always sets NOT NULL when BOOLEAN is specified

- tests/system/Database/Live/AbstractGetFieldDataTest.php
- tests/system/Database/Live/MySQLi/GetFieldDataTest.php
- tests/system/Database/Live/SQLite3/GetFieldDataTest.php
~~Needs #8432~~
- add test
**Checklist:**
> test: add test for MySQLi getFieldData()

- system/Autoloader/Autoloader.php
- system/Autoloader/FileLocator.php
- system/CLI/GeneratorTrait.php
- system/Commands/Generators/TestGenerator.php
- system/Commands/Utilities/Namespaces.php
- system/Config/AutoloadConfig.php
- tests/system/Commands/Utilities/NamespacesTest.php
- user_guide_src/source/cli/cli_generators.rst
Supersedes #8374
- `make:test` creates test files in `/tests/` directory
- add `tests/system` for namespace `CodeIgniter`
E.g.,
```console
$ ./spark make:test FooTest 
File created: ROOTPATH/tests/FooTest.php
```
```console
$ ./spark make:test Bar/FooTest 
File created: ROOTPATH/tests/Bar/FooTest.php
```
```console
$ ./spark make:test CodeIgniter\\Commands\\FooTest
File created: ROOTPATH/tests/system/Commands/FooTest.php
```
If you set:
```php
public $psr4 = [
APP_NAMESPACE => [APPPATH, TESTPATH . 'app'],
];
```
```console
$ ./spark make:test App\\Controllers\\FooTest
File created: ROOTPATH/tests/app/Controllers/FooTest.php
```
**Checklist:**
> feat: `spark make:test` creates test files in `/tests/` directory v2

- system/Test/DatabaseTestTrait.php
The shared migration holds an old DB connection.
If SQLite3 `:memory:` is used, a new DB connection is a connection to a new database.
Before:
```console
$ vendor/bin/phpunit tests/system/Database/Live/TransactionDBDebugTrueTest.php 
PHPUnit 9.6.16 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.2.15
Configuration: /Users/kenji/work/codeigniter/official/CodeIgniter4/phpunit.xml
.EEEE                                                                5 / 5 (100%)
Time: 00:00.136, Memory: 18.00 MB
There were 4 errors:
1) CodeIgniter\Database\Live\TransactionDBDebugTrueTest::testTransStartTransException
CodeIgniter\Database\Exceptions\DatabaseException: SQLite3::exec(): no such table: db_user
```
After:
```console
$ vendor/bin/phpunit …
```
> fix: DB Seeder may use wrong DB connection during testing

- system/Database/Postgre/Builder.php
- tests/system/Database/Live/DeleteTest.php
- fix type error in `deleteBatch()` on PostgreSQL
Ref #8439
**Checklist:**
> fix: [Postgre] QueryBuilder::deleteBatch() does not work

- tests/system/Database/Live/UpsertTest.php
- add test
```php
$data = [
// new row insert
[
'type_varchar'  => 'insert', // Key
'type_bigint'   => 9_999_999,
'type_date'     => '2024-01-01',
'type_datetime' => '2024-01-01 09:00:00',
],
// update
[
'type_varchar'  => 'test1', // Key
'type_bigint'   => 9_999_999,
'type_date'     => '2024-01-01',
'type_datetime' => '2024-01-01 09:00:00',
],
];
$builder->onConstraint('type_varchar')->upsertBatch($data);
```
```sql
INSERT INTO "db_type_test" ("type_bigint", "type_date", "type_datetime", "type_varchar")
VALUES (9999999,'2024-01-01','2024-01-01 09:00:00','insert'), (9999999,'2024-01-01','2024-01-01 09:00:00','test1')
ON CONFLICT("type_varchar")
DO UPDATE SET
"type_bigint" = "excluded"."type_bigint",
"type_date" = "excluded"."type_date",
"type_datetime" = …
```
> test: add test for Postgre upsertBatch()

- user_guide_src/source/dbmgmt/forge.rst
Follow-up #7371
This bug was fixed in v4.3.4.
**Checklist:**
> docs: fix incorrect descriptions in Forge::modifyColumn() notes

- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/outgoing/csp.rst
Small improvements.
**Checklist:**
> docs: improve csp

- system/Email/Email.php
- tests/system/Email/EmailTest.php
> fix: [Email] setAttachmentCID() does not work with buffer string

- user_guide_src/source/dbmgmt/forge.rst
- user_guide_src/source/dbmgmt/forge/007.php
- user_guide_src/source/dbmgmt/forge/025.php
- user_guide_src/source/dbmgmt/forge/028.php
- add section about Data Types
**Checklist:**
> docs: add about field data types on Forge

- user_guide_src/source/database/query_builder.rst
- add section titles for Insert/Upsert/Detete Batch
**Checklist:**
> docs: improve query_builder

- system/Commands/Generators/Views/model.tpl.php
- user_guide_src/source/models/model.rst
- user_guide_src/source/models/model/005.php
- add missing $allowEmptyInserts to user guide and make:model template
**Checklist:**
> fix: add undocumented Model $allowEmptyInserts

- .github/prlint.json
- CHANGELOG.md
- phpdoc.dist.xml
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.4.5.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_445.rst
Updates changelog and version references for 4.4.5.
Previous version: #8376
**Checklist:**
> Prep for 4.4.5 release

- system/BaseModel.php
- system/Common.php
- system/Database/BaseConnection.php
- system/Database/BasePreparedQuery.php
- system/Database/BaseResult.php
- system/Database/ConnectionInterface.php
- system/Database/Forge.php
- system/Database/MySQLi/Forge.php
- system/Database/OCI8/Forge.php
- system/Database/Postgre/Connection.php
- system/Database/Postgre/Forge.php
- system/Database/Postgre/PreparedQuery.php
- system/Database/PreparedQueryInterface.php
- system/Database/ResultInterface.php
- system/Database/SQLSRV/Forge.php
- system/Database/SQLite3/Forge.php
- system/Database/SQLite3/Table.php
- system/HTTP/CLIRequest.php
- system/HTTP/IncomingRequest.php
- system/HTTP/RequestTrait.php
- system/HTTP/SiteURI.php
- system/Model.php
- system/RESTful/ResourceController.php
- system/Traits/ConditionalTrait.php
- system/View/Filters.php
- system/View/RendererInterface.php
- system/View/View.php
Using this new configuration to `phpdoc_align` fixer:
```
'phpdoc_align' => [
'align'   => 'vertical',
'spacing' => 1,
'tags'    => [
'method',
'param',
'phpstan-assert',
'phpstan-assert-if-true',
'phpstan-assert-if-false',
'phpstan-param',
'phpstan-property',
'phpstan-return',
'property',
'return',
'throws',
'type',
'var',
],
],
```
Run: `vendor/bin/php-cs-fixer describe phpdoc_align` for more details.
**Checklist:**
> style: apply new options to `phpdoc_align` fixer

- tests/system/Images/ImageMagickHandlerTest.php
This refactors the test to:
- check all available sources of the `convert` program
- move the extension_loaded check to the native PHPUnit annotation
- fail gracefully and skip the tests altogether if `convert` is missing instead of erroring midway through the test, i.e. `Esh: /usr/local/bin/convert: No such file or directory`
**Checklist:**
> test: refactor ImageMagickHandlerTest

- contributing/pull_request.md
- add how to update PHPStan baseline
**Checklist:**
> docs: add how to update PHPStan baseline

- app/Config/Routing.php
- phpstan-baseline.php
- system/Config/Routing.php
- system/Router/Router.php
- tests/system/Router/RouterTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/incoming/routing/069.php
See https://forum.codeigniter.com/showthread.php?tid=88954&pid=414392#pid414392
- add an option to pass multiple URI segments to one Controller parameter
The current implementation passes the captured value to the controller after splitting it with `/`.
So if `path/to/image-file.png` is captured, the controller will receive three parameters.
This PR adds an option to pass it to one parameter.
E.g.,
```php
$routes->get('img/(:any)', 'Image::display/$1');
```
```php
<?php
use App\Controllers\BaseController;
use CodeIgniter\HTTP\ResponseInterface;
class Image extends BaseController
{
public function display(...$params)
{
dd($params);
}
}
```
Navigate to `http://localhost:8080/img/path/to/image-file.png`.
The current behavior:
```
$params array (3) …
```
> feat: [Routing] add option to pass multiple URI segments to one Controller parameter

- system/Database/OCI8/Connection.php
- tests/system/Database/Live/ForgeTest.php
- tests/system/Database/Live/OCI8/GetFieldDataTest.php
- fix a bug that returns `''` instead of `null`
Found in #8457 
https://github.com/codeigniter4/CodeIgniter4/actions/runs/7664355802/job/20888609701?pr=8457
```
1) CodeIgniter\Database\Live\ForgeTest::testModifyColumnRename
Failed asserting that '' is null.
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Database/Live/ForgeTest.php:1339
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:106
```
**Checklist:**
> fix: [OCI8] getFieldData() returns incorrect `default` value

- contributing/signing.md
- contributing/workflow.md
- add "Set Default Signing" section and refer it
**Checklist:**
> docs: improve contributing/signing.md

- system/Database/SQLite3/Connection.php
- tests/system/Database/Live/ForgeTest.php
- tests/system/Database/Live/SQLite3/GetFieldDataTest.php
- user_guide_src/source/database/metadata.rst
The return type is integer, not boolean.
> primary_key - integer 1 if the column is a primary key (all integer 1, even if there are multiple primary keys), otherwise integer 0 (This field is currently only available for MySQL and SQLite3)
See https://codeigniter4.github.io/CodeIgniter4/database/metadata.html#retrieve-field-metadata
**Checklist:**
> fix: [SQLite3] getFieldData() returns incorrect `primary_key` values

- user_guide_src/source/testing/fabricator.rst
- user_guide_src/source/testing/fabricator/005.php
- user_guide_src/source/testing/fabricator/006.php
- user_guide_src/source/testing/fabricator/008.php
- user_guide_src/source/testing/fabricator/021.php
- update fabricator.rst
**Checklist:**
> docs: update fabricator.rst

- phpstan-baseline.php
- system/Test/TestLogger.php
> docs: fix phpstan errors on TestLogger

- system/Database/OCI8/Connection.php
- system/Database/Postgre/Connection.php
- system/Database/SQLSRV/Connection.php
- system/Database/SQLite3/Connection.php
- tests/system/Database/Live/ForgeTest.php
- tests/system/Database/Live/OCI8/GetFieldDataTest.php
- user_guide_src/source/database/metadata.rst
Change the order of properties in the stdClass object returned by `getFieldData()` to the same for all DB drivers.
**Checklist:**
> fix: [OCI8][Postgre][SQLSRV][SQLite3] change order of properties returned by getFieldData()

- system/Database/SQLite3/Connection.php
- system/Database/SQLite3/PreparedQuery.php
See https://github.com/codeigniter4/CodeIgniter4/issues/6913#issuecomment-1912990005
Use enableExceptions().
See https://www.php.net/manual/en/sqlite3.enableexceptions.php
**Checklist:**
> fix: SQLite3 may not throw DatabaseException

- app/Config/Routing.php
- system/Config/Routing.php
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/incoming/routing/051.php
- user_guide_src/source/incoming/routing/069.php
- improve the description
- update doc comment. See https://github.com/codeigniter4/CodeIgniter4/issues/8485#issuecomment-1918859583
**Checklist:**
> docs: update description for 404 Override

- user_guide_src/source/intro/requirements.rst
Closes #5663
We are using `OFFSET`.
SQL Server 2012 also reached the end of life: Jul 12, 2022. 
https://learn.microsoft.com/en-us/lifecycle/products/microsoft-sql-server-2012
**Checklist:**
> docs: fix supported SQL Server version

- user_guide_src/source/testing/feature.rst
- user_guide_src/source/testing/feature/001.php
> docs: improve testing/feature.rst

- user_guide_src/source/testing/index.rst
"Mocking" is about PHPUnit testing.
**Checklist:**
> docs: fix section order in testing

- system/Database/SQLite3/Forge.php
- system/Database/SQLite3/Table.php
- tests/system/Database/Live/ForgeTest.php
- tests/system/Database/Live/SQLite3/AlterTableTest.php
- tests/system/Database/Live/SQLite3/ForgeModifyColumnTest.php
Fixes #8410
~~OCI8 test failure will be fixed in #8459~~
**Checklist:**
> fix: [SQLite3] Forge::modifyColumn() messes up table

- system/Log/Logger.php
Fixed by php-cs-fixer v3.49.0.
```diff
Detected deprecations in use:
- Rule "escape_implicit_backslashes" is deprecated. Use "string_implicit_backslashes" instead.
1) system/Log/Logger.php (phpdoc_scalar, unary_operator_spaces, not_operator_with_successor_space)
--- /home/runner/work/CodeIgniter4/CodeIgniter4/system/Log/Logger.php
+++ /home/runner/work/CodeIgniter4/CodeIgniter4/system/Log/Logger.php
@@ -37,7 +37,7 @@
* Used by the logThreshold Config setting to define
* which errors to show.
*
-     * @var array<string, integer>
+     * @var array<string, int>
*/
protected $logLevels = [
'emergency' => 1,
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/7749714872/job/21134753620?pr=8493 …
> docs: update coding style for v3.49.0

- user_guide_src/source/testing/controllers/001.php
- user_guide_src/source/testing/controllers/002.php
- user_guide_src/source/testing/controllers/011.php
- user_guide_src/source/testing/controllers/012.php
- user_guide_src/source/testing/controllers/014.php
`namespace CodeIgniter` should not be used in app testing.
**Checklist:**
> docs: fix sample code in testing/controllers

- user_guide_src/source/testing/overview.rst
- user_guide_src/source/testing/overview/002.php
- user_guide_src/source/testing/overview/003.php
- user_guide_src/source/testing/overview/016.php
- user_guide_src/source/testing/overview/017.php
- user_guide_src/source/testing/overview/018.php
- user_guide_src/source/testing/overview/019.php
- user_guide_src/source/testing/overview/020.php
- update some descriptiions
**Checklist:**
> docs: improve testing/overview.rst

- user_guide_src/source/database/results/016.php
> You can also use the getRow() method in exactly the same way.
https://codeigniter4.github.io/CodeIgniter4/database/results.html#getcustomrowobject
So it should show a sample code for `getRow()`.
**Checklist:**
> docs: fix incorrect sample code in database/results

- admin/starter/tests/README.md
You can set up test database with `.env`.
Now we provide only `CIUnitTestCase`.
**Checklist:**
> docs: update starter/tests/README.md

- tests/system/Database/Live/AbstractGetFieldDataTest.php
- refactor test
**Checklist:**
> test: use array_sort_by_multiple_keys() in AbstractGetFieldDataTest

- tests/system/Database/Live/SQLite3/ForgeModifyColumnTest.php
- add missing `declare(strict_types=1)`
**Checklist:**
> [4.5] refactor: add `declare(strict_types=1)` to ForgeModifyColumnTest

- system/Database/BaseResult.php
- system/Database/ResultInterface.php
> docs: fix incorrect @return type in `ResultInterface-getCustomRowObject()`

- phpstan-baseline.php
- system/Database/BaseBuilder.php
- system/Database/Postgre/Builder.php
- system/Email/Email.php
- system/Router/AutoRouter.php
- system/Router/RouteCollection.php
- system/Router/RouteCollectionInterface.php
- system/Router/Router.php
- system/Router/RouterInterface.php
- fix PHPDoc types in #7964. These are needed for #8354
- update PHPDocs
**Checklist:**
> docs: fix PHPDocs

- system/BaseModel.php
- system/Commands/Generators/Views/model.tpl.php
- tests/system/Models/UpdateModelTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/models/model.rst
- user_guide_src/source/models/model/005.php
- add an option to always update all Entity fields, not just those that have changed.
See https://forum.codeigniter.com/showthread.php?tid=87742
**Checklist:**
> feat: [Model] add option $updateOnlyChanged

- system/CLI/Commands.php
- system/CLI/Console.php
- tests/system/CLI/ConsoleTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/extending/events.rst
Closes #8442
- add event points `pre_command` and `post_command`
**Checklist:**
> feat: add event points for spark commands

- system/HTTP/SiteURI.php
- system/Helpers/url_helper.php
- user_guide_src/source/helpers/url_helper.rst
- user_guide_src/source/helpers/url_helper/004.php
- user_guide_src/source/helpers/url_helper/026.php
- add about `base_url()`/`site_url()` protocol-relative link
**Checklist:**
> docs: add undocumented `base_url()` protocol-relative link

- system/CodeIgniter.php
- tests/_support/Errors.php
- tests/system/CodeIgniterTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
Closes #8485
In the current implementation, 404 closure can get the PageNotFoundException message as a parameter,
but 404 controller can't.
This PR enables 404 controller to get the messsage as the first parameter.
**Checklist:**
> feat: 404 controller also can get PageNotFoundException message

- system/API/ResponseTrait.php
- system/RESTful/ResourceController.php
- tests/system/API/ResponseTraitTest.php
- tests/system/Test/ControllerTestTraitTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/installation/upgrade_450.rst
- user_guide_src/source/outgoing/api_responses.rst
Fixes #8397
- When you pass a string, `$this->respond()` returns `text/html`. But it should return `application/json`.
- When you pass an int, `$this->respond()` returns `application/json`.
- When you pass a boolean, `$this->respond()` returns `application/json`.
Before:
```console
$ curl -v http://localhost:8080/
...
< HTTP/1.1 200 OK
< Host: localhost:8080
< Date: Wed, 31 Jan 2024 07:57:40 GMT
< Connection: close
< X-Powered-By: PHP/8.2.15
< Cache-Control: no-store, max-age=0, no-cache
< Content-Type: text/html; charset=UTF-8
< 
* Closing connection
message
```
After:
```console
$ curl -v http://localhost:8080/
...
< HTTP/1.1 200 OK
< Host: localhost:8080
< Date: Wed, 31 Jan 2024 07:59:11 GMT
< Connection: close
< X-Powered-By: PHP/8.2.15
< Cache-Control: no-store, …
```
> fix: API\ResponseTrait can't return string as JSON

- system/Database/SQLSRV/Forge.php
- tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
- tests/system/Database/Live/GetTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/dbmgmt/forge.rst
> refactor: [SQLSRV] convert ENUM to VARCHAR(n) in Forge

- user_guide_src/source/models/entities.rst
- user_guide_src/source/models/entities/018.php
- user_guide_src/source/models/entities/020.php
- modify sentences
**Checklist:**
> docs: modify sentences slightly in Entity

- deptrac.yaml
- system/Validation/Validation.php
- system/Validation/ValidationInterface.php
- tests/system/Validation/StrictRules/DatabaseRelatedRulesTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/installation/upgrade_450.rst
Closes #6723
Supersedes  #8188
**Checklist:**
> feat: Validation::run() accepts DB connection

- system/Database/Postgre/Builder.php
- tests/system/Database/Live/UpdateTest.php
Follow-up #8439
From https://forum.codeigniter.com/showthread.php?tid=89336
**Checklist:**
> fix: [Postgre] updateBatch() breaks `char` type data

- tests/system/Database/Live/AbstractGetFieldDataTest.php
- tests/system/Database/Live/MySQLi/GetFieldDataTest.php
- tests/system/Database/Live/OCI8/GetFieldDataTest.php
- tests/system/Database/Live/Postgre/GetFieldDataTest.php
- tests/system/Database/Live/SQLSRV/GetFieldDataTest.php
- tests/system/Database/Live/SQLite3/GetFieldDataTest.php
~~Needs #8480~~
- add tests for the current behaviors
**Checklist:**
> test: add tests for getFieldData() type

- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/outgoing/view_renderer.rst
- user_guide_src/source/outgoing/views.rst
- add links
- make the description more precise
**Checklist:**
> docs: improve view() and view renderer

- system/View/Parser.php
- system/View/RendererInterface.php
- system/View/View.php
> docs: add missing null to @param to RendererInterface

- system/Filters/Filters.php
- system/View/View.php
- tests/system/Helpers/FormHelperTest.php
Follow-up #8053
Fix a bug that `DEBUG-VIEW` comments are not output.
**Checklist:**
> [4.5] fix: DEBUG-VIEW comments are not output

- tests/system/Database/Live/SQLSRV/GetFieldDataTest.php
Follow-up #8478
```diff
1) CodeIgniter\Database\Live\SQLSRV\GetFieldDataTest::testGetFieldDataType
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
)
7 => Array &8 (
'name' => 'type_enum'
-        'type' => 'text'
-        'max_length' => 2147483647
+        'type' => 'varchar'
+        'max_length' => 5
'nullable' => true
'default' => null
)
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Database/Live/AbstractGetFieldDataTest.php:169
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Database/Live/SQLSRV/GetFieldDataTest.php:229
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/7851204632/job/21428585497
**Checklist:**
- [] Unit testing, with >80% …
> [4.5] test: update asssertion for SQLSRV ENUM

- user_guide_src/source/installation/installing_composer.rst
- some updates and small fixes
**Checklist:**
> docs: update installing_composer.rst

- user_guide_src/source/libraries/uploaded_files/002.php
Closes #8430
Supersedes #8445
**Checklist:**
> docs: use validateData() instead of validate() in uploaded_files

- app/Config/Database.php
- system/Database/BaseConnection.php
- tests/system/Database/BaseConnectionTest.php
- user_guide_src/source/database/configuration.rst
See #7177
- add DB config `dateFormat`
We should have this config value in the `Connection` class. Because each connection has the datetime format.
The current DB related class layers:
```
Entity
Model
Builder
Connection
```
**Checklist:**
> feat: add DB config `dateFormat` to provide default date/time formats

- user_guide_src/source/incoming/routing/069.php
> docs: add sample code to get URI segments in 404 closure

- system/Commands/Generators/TestGenerator.php
- system/Config/AutoloadConfig.php
- tests/system/Commands/Utilities/NamespacesTest.php
Follow-up #8388
```console
$ composer install --no-dev
$ ./spark
```
```
[Error]
Class "PHPUnit\Framework\TestCase" not found
at SYSTEMPATH/Test/CIUnitTestCase.php:40
Backtrace:
1    VENDORPATH/composer/ClassLoader.php:576
include()
2    VENDORPATH/composer/ClassLoader.php:427
Composer\Autoload\{closure}('/Users/kenji/work/codeigniter/official/CodeIgniter4-4.5/vendor/composer/../../system/Test/CIUnitTestCase.php')
3    ROOTPATH/tests/system/Commands/BaseCommandTest.php:26
Composer\Autoload\ClassLoader()->loadClass('CodeIgniter\\Test\\CIUnitTestCase')
4    SYSTEMPATH/Autoloader/Autoloader.php:310
include_once('/Users/kenji/work/codeigniter/official/CodeIgniter4-4.5/tests/system/Commands/BaseCommandTest.php')
5    SYSTEMPATH/Autoloader/Autoloader.php:289 …
```
> [4.5] fix: spark does not work with composer install --no-dev

- app/Views/welcome_message.php
- system/Debug/Toolbar/Views/_config.tpl
- system/Session/Handlers/BaseHandler.php
- use official site URLs
**Checklist:**
> refactor: use official site URLs

- user_guide_src/source/intro/index.rst
- update "Welcome to CodeIgniter4"
**Checklist:**
> docs: update "Welcome to CodeIgniter4"

- user_guide_src/source/installation/upgrade_file_upload/001.php
- user_guide_src/source/installation/upgrade_validations.rst
- user_guide_src/source/installation/upgrade_validations/001.php
- user_guide_src/source/installation/upgrade_validations/002.php
- user_guide_src/source/libraries/validation.rst
- user_guide_src/source/libraries/validation/045.php
`$this->validate()` is not recommended.
Related #8537
**Checklist:**
> docs: replace `$this->validate()` with `validateData()`

- system/HTTP/CURLRequest.php
- tests/system/HTTP/CURLRequestTest.php
> fix: [CURLRequest] Multiple HTTP 100 return by API.

- system/CodeIgniter.php
- tests/system/CodeIgniterTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/installation/upgrade_450.rst
The *404 Override* feature should set 404 by default, because it is for 404 pages.
**Checklist:**
> feat: 404 Override sets 404 by default

- system/CodeIgniter.php
- tests/system/CodeIgniterTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/incoming/routing.rst
- permit `__invoke()` method as Controller default method
**Checklist:**
> feat: permit __invoke() method as Controller default method

- system/Test/bootstrap.php
- autoloader now loads URL helper
**Checklist:**
> refactor: remove redundant URL helper loading

- spark
- user_guide_src/source/changelogs/v4.5.0.rst
- remove deprecated const SPARKED
**Checklist:**
> refactor: remove deprecated const SPARKED

- user_guide_src/source/database/events.rst
- user_guide_src/source/installation/troubleshooting.rst
- user_guide_src/source/testing/debugging.rst
- improve debugging
**Checklist:**
> docs: improve debugging

- system/I18n/TimeTrait.php
- tests/system/I18n/TimeTest.php
- user_guide_src/source/changelogs/v4.4.6.rst
- user_guide_src/source/installation/upgrade_446.rst
- user_guide_src/source/libraries/time.rst
From https://github.com/codeigniter4/shield/pull/1027/files#r1488969384
`Time::createFromTimestamp()` returns Time with the timezone `UTC`.
This behavior is misleading.
```diff
@@ -109,7 +109,7 @@ class App extends BaseConfig
* @see https://www.php.net/manual/en/timezones.php for list of timezones
*      supported by PHP.
*/
-    public string $appTimezone = 'UTC';
+    public string $appTimezone = 'Asia/Tokyo';
/**
* --------------------------------------------------------------------------
```
```php
//        UTC 1999-12-31 15:00:00
// Asia/Tokyo 2000-01-01 00:00:00
$timestamp = 946652400;
$time = DatetimeCast::get($timestamp);
return $time->format('Y-m-d H:i:s'); // 1999-12-31 15:00:00
```
Carbon sets the current …
> fix: Time::createFromTimestamp() returns Time with UTC

- composer.json
- phpmetrics.json
- tools/phpmetrics/composer.json
- add [PhpMetrics](https://phpmetrics.github.io/website/)
How to Use:
```console
$ composer metrics
$ open build/phpmetrics/index.html
```
**Checklist:**
> chore: add PhpMetrics

- system/Autoloader/Autoloader.php
Move function call in nested loop to outside.
**Checklist:**
> refactor: small improvement in `loadInNamespace` Autoloader

- user_guide_src/source/installation/running.rst
- add "Deployment to Shared Hosting Services"
**Checklist:**
> docs: add "Deployment to Shared Hosting Services"

- user_guide_src/source/libraries/cookies/004.php
- user_guide_src/source/models/model.rst
- use word "UNIX timestamp" for consistency
**Checklist:**
> docs: use word "UNIX timestamp" for consistency

- system/Model.php
To fix PHPStan error. Also, using a local variable is a bit faster than method calling twice.
```
------ -------------------------------------------- 
Line   system/Model.php                            
------ -------------------------------------------- 
211    Variable $returnType might not be defined.  
213    Variable $returnType might not be defined.  
275    Variable $returnType might not be defined.  
278    Variable $returnType might not be defined.  
316    Variable $returnType might not be defined.  
318    Variable $returnType might not be defined.  
------ -------------------------------------------- 
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/7982852609/job/21797025530
**Checklist:**
> [4.5] refactor: use local variables in Model

- user_guide_src/source/installation/upgrade_4xx.rst
I saw a YouTube video that a dev had moved index.php to the project root.
Also this description is on the README file, but not in the User Guide upgrading section.
a**Checklist:**
> docs: add note for index.php change

- system/Session/Handlers/RedisHandler.php
Fixes #4391
Fixes #8567
- fix Redis Session race condition
- fix that `close()` does not return `false` if `releaseLock()` failed
- fix that `read()` does not return `false` if `lockSession()` failed
- macOS 12.7.2
- PHP 8.2.16
- symfony CLI version 5.7.4
- Redis 7.2.4
```diff
--- a/app/Config/Session.php
+++ b/app/Config/Session.php
@@ -4,7 +4,6 @@ namespace Config;
use CodeIgniter\Config\BaseConfig;
use CodeIgniter\Session\Handlers\BaseHandler;
-use CodeIgniter\Session\Handlers\FileHandler;
class Session extends BaseConfig
{
@@ -21,7 +20,7 @@ class Session extends BaseConfig
*
* @var class-string<BaseHandler>
*/
-    public string $driver = FileHandler::class;
+    public string $driver = 'CodeIgniter\Session\Handlers\RedisHandler';
/**
* …
```
> fix: [Session] Redis session race condition

- CHANGELOG.md
- phpdoc.dist.xml
- system/CodeIgniter.php
- system/I18n/TimeTrait.php
- system/Images/Handlers/ImageMagickHandler.php
- user_guide_src/source/changelogs/v4.4.6.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_446.rst
Updates changelog and version references for 4.4.6.
Previous version: #8463
**Checklist:**
> Prep for 4.4.6 release

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.4.7.rst
- user_guide_src/source/installation/upgrade_447.rst
- user_guide_src/source/installation/upgrading.rst
- add changelog and upgrade for v4.4.7
**Checklist:**
> docs: add changelog and upgrade for v4.4.7

- user_guide_src/source/installation/deployment.rst
- user_guide_src/source/installation/running.rst
Because In 4.5 branch the "Deployment" page is added.
**Checklist:**
> [4.5] docs: move "Deployment to Shared Hosting Services" to "Deployment" page

- psalm-baseline.xml
- system/Config/View.php
Related #8530
I don't know why Psalm does not understand `@phpstan-type`.
**Checklist:**
> docs: suppress Psalm errors

- deptrac.yaml
- system/Commands/Utilities/PhpIniCheck.php
- system/Security/CheckPhpIni.php
- tests/system/Security/CheckPhpIniTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/installation/running.rst
To easily check important php.ini settings.
```console
$ php spark phpini:check
CodeIgniter v4.4.6 Command Line Tool - Server Time: 2024-02-25 01:23:22 UTC+00:00
+-------------------------+---------+---------+-------------+-----------------------+
| Directive               | Global  | Current | Recommended | Remark                |
+-------------------------+---------+---------+-------------+-----------------------+
| error_reporting         | 32767   | 32767   | 5111        |                       |
| display_errors          | 1       | 1       | 0           |                       |
| display_startup_errors  | 1       | 1       | 0           |                       |
| log_errors              | 1       | 1       |             |                       |
| error_log …
```
> feat: add spark command to check php.ini

- phpstan-baseline.php
- system/Config/BaseService.php
- user_guide_src/source/changelogs/v4.5.0.rst
- remove deprecated BaseService::discoverServices()
**Checklist:**
> refactor: remove deprecated BaseService::discoverServices()

- system/Validation/FileRules.php
Fixes #8591
```
ErrorException
Trying to access array offset on value of type bool
SYSTEMPATH/Validation/FileRules.php at line 246
```
**Checklist:**
> fix: [Validation] FileRules cause error if getimagesize() returns false

- system/HTTP/Response.php
- tests/system/Test/TestCaseTest.php
See https://github.com/codeigniter4/CodeIgniter4/pull/8069#issuecomment-1963302623
**Checklist:**
> test: remove meaningless `TestCaseTest::testPHPUnitHeadersEmitted()`

- user_guide_src/source/models/entities.rst
- user_guide_src/source/models/model.rst
> docs: improve Model and Entity

- tests/system/I18n/TimeLegacyTest.php
- tests/system/I18n/TimeTest.php
- fix failed tests. See https://github.com/codeigniter4/CodeIgniter4/pull/8558#issuecomment-1970195838
- remove unnecessary timezone `America/Chicago`
**Checklist:**
> test: fix TimeTest

- system/Config/BaseService.php
- user_guide_src/source/changelogs/v4.5.0.rst
- deprecate `BaseService::$services`. It is not used elsewhere.
**Checklist:**
> refactor: remove unnecessary BaseService::$services assignment

- system/Database/BaseConnection.php
- system/Database/Postgre/Connection.php
- tests/system/Database/Live/WriteTypeQueryTest.php
This pull request attempts to fix some issues I ran into with queries being miscategorized as isWriteType or not, particularly with PostgreSQL:
- Operations with CTE (flagged by WITH) were not being counted as isWriteType, even if followed by an appropriate operator like INSERT/UPDATE.
- In Postgre, INSERT/UPDATE operations with RETURNING were being counted as isWriteType if there was whitespace before INSERT/UPDATE.
- In Postgre, DELETE operations with RETURNING were always being counted as isWriteType.
**Edit:** this pull request has been modified to remove the Postgre override of isWriteType, and to incorporate RETURNING handling in isWriteType on a uniform basis for all database types.
**Checklist:**
> fix: isWriteType() to recognize CTE; always excluding RETURNING

- system/Config/Services.php
Fixes #7266
- remove the default CI4 `Cache-Control` header before the Session starts.
Before:
```
HTTP/1.1 200 OK
Host: localhost:8080
Date: Sat, 02 Mar 2024 12:54:18 GMT
Connection: close
X-Powered-By: PHP/7.4.33
Expires: Thu, 19 Nov 1981 08:52:00 GMT             // PHP Session
Cache-Control: no-store, no-cache, must-revalidate // PHP Session
Pragma: no-cache                                   // PHP Session
Cache-Control: no-store, max-age=0, no-cache       // CI4
Content-Type: text/html; charset=UTF-8
```
After:
```
HTTP/1.1 200 OK
Host: localhost:8080
Date: Sat, 02 Mar 2024 12:56:08 GMT
Connection: close
X-Powered-By: PHP/7.4.33
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Type: text/html; …
```
> fix: duplicate Cache-Control header with Session

- phpstan-baseline.php
- system/Test/Mock/MockCache.php
PHPStan update now causes an error.
PHPDoc types have been fixed along with it.
```
------ ---------------------------------------------------------------------------------------------------- 
Line   system/Test/Mock/MockCache.php                                                                      
------ ---------------------------------------------------------------------------------------------------- 
Ignored error pattern #^Cannot unset offset string on array<int, int>\|null\.$# in path             
/Users/kenji/work/codeigniter/official/CodeIgniter4/system/Test/Mock/MockCache.php was not matched  
in reported errors.                                                                                 
------ ---------------------------------------------------------------- …
```
> docs: add/fix PHPDoc types in MockCache

- admin/css/debug-toolbar/toolbar.scss
- system/Debug/Toolbar/Views/toolbar.css
- system/Debug/Toolbar/Views/toolbar.tpl.php
> fix: [DebugBar] scroll to top

- preload.php
- user_guide_src/source/general/managing_apps.rst
- user_guide_src/source/installation/deployment.rst
- user_guide_src/source/installation/preloading/001.php
Fixed #8596
For note using preload.
**Checklist:**
> docs: preload notes

- system/HTTP/IncomingRequest.php
- system/HTTP/Request.php
- system/HTTP/RequestTrait.php
- user_guide_src/source/changelogs/v4.5.0.rst
- remove deprecated items in Request
**Checklist:**
> refactor: remove deprecated items in Request

- .github/workflows/test-deptrac.yml
The current workflow does not work when the phar file is updated.
```
Run sudo phive --no-progress install --global qossmic/deptrac --trust-gpg-keys B8F640134AB1782E
Phive 0.15.2 - Copyright (C) 2015-2024 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/rate_limit
Downloading https://github.com/qossmic/deptrac/releases/download/2.0.0-alpha/deptrac.phar
Downloading https://github.com/qossmic/deptrac/releases/download/2.0.0-alpha/deptrac.phar.asc
Downloading key 47436587D82C4A39
Trying to connect to keys.openpgp.org (37.218.245.50)
Downloading https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0x47436587D82C4A39
Successfully downloaded key.
Fingerprint: 57CB 556F 242F C8D4 FD48 3C2C 4743 6587 D82C 4A39
Gennadi McKelvey …
```
> chore: update test-deptrac.yml

- system/Commands/Utilities/Routes/ControllerMethodReader.php
Apply early return (or return early) pattern. 
It's more readable and a bit shorter
**Checklist:**
> refactor: apply early return pattern

- app/Views/errors/html/debug.css
- app/Views/errors/html/error_exception.php
- user_guide_src/source/installation/upgrade_447.rst
See https://github.com/codeigniter4/CodeIgniter4/pull/8616#issuecomment-1997478306
It is useful when reporting errors.
Before:
After:
**Checklist:**
> refactor: move footer info to top in error_exception.php

- .github/workflows/test-phpcpd.yml
- public/index.php
- spark
- system/Autoloader/Autoloader.php
- system/CodeIgniter.php
- system/Test/bootstrap.php
- system/bootstrap.php
- tests/system/CommonFunctionsTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/installation/upgrade_450.rst
Supersedes #8558
- move `CodeIgniter::initializeKint()` to Autoloader
- `CodeIgniter::initializeKint()` registers an autoloader. So it is better to be in Autoloader.
- Config caching cannot load Kint files. See https://forum.codeigniter.com/showthread.php?tid=88992&pid=414620#pid414620
The following items are also needed, so included in this PR:
- move `CodeIgniter::bootstrapEnvironment()` to bootstrap.php
- move `Services::exceptions()->initialize()` to bootstrap.php
- move `CodeIgniter::resolvePlatformExtensions()` to bootstrap.php
**Checklist:**
> fix: move Kint loading to Autoloader

- system/Common.php
Follow-up #8607
Why not use `service()` after improvement.
**Checklist:**
> refactor: followup performance `service()`

- tests/system/Database/Live/SQLite3/GetFieldDataTest.php
- tests/system/Database/Live/SQLite3/GetIndexDataTest.php
- tests/system/Database/Migrations/MigrationRunnerTest.php
Currently, `writable/` has two leftover DB files from sqlite3: `database.db` and `runner.sqlite`. This PR cleans them.
**Checklist:**
> test: ensure cleanup of sqlite3 db files after test

- phpstan-baseline.php
- system/HTTP/Negotiate.php
- system/Helpers/form_helper.php
Remove unnecessary if check, applied by running latest rector/rector:dev-main
**Checklist:**
> chore: remove unnecessary if check

- user_guide_src/source/concepts/factories.rst
Small typo in factories.rst. Change all "full qualified classname" to "fully qualified classname".
**Checklist:**
> docs: Small typo in factories.rst

- system/Common.php
- tests/system/CommonFunctionsTest.php
> fix: esc() for 'raw' context

- .github/workflows/test-rector.yml
- rector.php
Let's try enable rector cache based on https://getrector.com/documentation/cache-in-ci 
**Checklist:**
> chore: Enable rector cache

- phpstan-baseline.php
- system/Filters/CSRF.php
- system/Filters/DebugToolbar.php
- system/Filters/FilterInterface.php
- system/Filters/Filters.php
- system/Filters/Honeypot.php
- system/Filters/InvalidChars.php
- system/Filters/SecureHeaders.php
- user_guide_src/source/libraries/throttler/002.php
- fix PHPDoc types for Filters
**Checklist:**
> docs: fix PHPDoc types for Filters

- composer.json
Follow-up #8005
- remove `Config\\` from autoload.psr4
If we use this repository from appstarter, the Config files in `app/Config/` in this repository are loaded first.
**Checklist:**
> [4.5] fix: Composer autoload.psr4

- app/Config/Session.php
- phpstan-baseline.php
- system/Session/Handlers/RedisHandler.php
- tests/system/Session/Handlers/Database/RedisHandlerTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/libraries/sessions.rst
- add config for lock timeout
- support Redis ACL (username/password)
**Checklist:**
> feat: improve Redis Session

- user_guide_src/source/database/configuration.rst
Small improvements for readability.
**Checklist:**
> docs: improve Database Configuration

- system/Validation/Validation.php
- tests/system/Validation/StrictRules/DatabaseRelatedRulesTest.php
- user_guide_src/source/libraries/validation.rst
> refactor: improve Validation Placeholder error message

- user_guide_src/source/libraries/curlrequest.rst
- user_guide_src/source/libraries/curlrequest/014.php
- fix description
```php
<?php
{
{
$client   = \Config\Services::curlrequest();
$response = $client->request('GET', 'http://google.com');
return $response->getBody();
}
}
```
You will see:
> 301 Moved
The document has moved [here](http://www.google.com/).
**Checklist:**
> docs: fix incorrect CURLRequest allow_redirects description

- system/BaseModel.php
- system/CodeIgniter.php
- system/Commands/Utilities/Routes/FilterFinder.php
- system/Database/BaseBuilder.php
- system/Database/SQLSRV/Builder.php
- system/Filters/Filters.php
- system/Model.php
Needs #8569
- add code for backward compatibiltiy
**Checklist:**
> [4.5] fix: errors when not updating Config\Feature

- public/index.php
- spark
- system/Boot.php
- system/Exceptions/FrameworkException.php
- system/Test/bootstrap.php
- system/bootstrap.php
- user_guide_src/source/changelogs/v4.5.0.rst
~~Needs #8603~~
Closes #7824
- add `Boot` class, then `index.php`, `spark`, and `Test/bootstrap.php` use it
- discontinue `system/bootstrap.php`
**Checklist:**
> feat: add Boot class

- .github/prlint.json
There is a PR that contains only config changes.
**Checklist:**
> chore: add "config", "revert" to prlint.json

- env
~~Needs #8665~~
By default, `Config\Database::$tests` is for SQLite3, and these values are different.
**Checklist:**
> config: add charset and DBCollat for database.tests in env

- user_guide_src/source/concepts/autoloader.rst
See https://forum.codeigniter.com/showthread.php?tid=90491
- update descriptions
**Checklist:**
> docs: add and update Autoloader descriptions

- system/Autoloader/FileLocatorCached.php
- system/Commands/Utilities/Optimize.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/concepts/autoloader.rst
- user_guide_src/source/concepts/factories.rst
- user_guide_src/source/installation/deployment.rst
~~Needs #8605~~
- add `spark optimize` command to:
- enable caching features
- clear cache
- remove Composer dev packages
**Checklist:**
> feat: add `spark optimize` command

- user_guide_src/source/libraries/time.rst
- user_guide_src/source/libraries/time/001.php
See https://github.com/codeigniter4/CodeIgniter4/pull/8659#discussion_r1538450417
**Checklist:**
> docs: small improvements to Time

- system/Database/Postgre/Connection.php
- tests/system/Database/ConfigTest.php
I don't know why `Postgre` driver supports PDO_PGSQL DSN.
It came from https://github.com/codeigniter4/CodeIgniter4/commit/30063c9f#diff-d627f02b770edc4ab06280dbc671681df326dc7790e9bc7b1cf268a5da58e465
**Checklist:**
> docs: add commnets on Postgre::convertDSN()

- system/I18n/TimeTrait.php
- tests/system/I18n/TimeDifferenceTest.php
- user_guide_src/source/changelogs/v4.4.7.rst
- user_guide_src/source/installation/upgrade_447.rst
- user_guide_src/source/libraries/time.rst
- user_guide_src/source/libraries/time/042.php
Supersedes #8659
See https://forum.codeigniter.com/showthread.php?tid=90472
Fixed to not convert to UTC when the two time zones are the same.
**Checklist:**
> fix: Time::difference() DST bug

- system/Database/BaseBuilder.php
- system/Model.php
- tests/system/Models/UpdateModelTest.php
See https://forum.codeigniter.com/showthread.php?tid=90502
> When you need a more flexible solution, you can leave the parameters empty and it functions like the Query Builder’s update command, with the added benefit of validation, events, etc:
https://codeigniter4.github.io/CodeIgniter4/models/model.html#update
So, `Model::set()` should accept object or Entity.
**Checklist:**
> fix: Model::set() does not accept object

- CHANGELOG.md
- phpdoc.dist.xml
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.4.7.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_447.rst
Updates changelog and version references for 4.4.7.
Previous version: #8574
**Checklist:**
> Prep for 4.4.7 release

- CHANGELOG.md
Follow-up #8674
**Checklist:**
> docs: add missing SECURITY to v4.4.7 in CHANGELOG.md

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.4.8.rst
- user_guide_src/source/installation/upgrade_448.rst
- user_guide_src/source/installation/upgrading.rst
add changelog and upgrade for v4.4.8
**Checklist:**
> docs: add changelog and upgrade for v4.4.8

- admin/RELEASE.md
- admin/prepare-release.php
**Description**-
- update the script and manual
**Checklist:**
> docs: slight update to release process

- system/Filters/Filters.php
- tests/system/Commands/Utilities/ConfigCheckTest.php
- tests/system/Filters/FiltersTest.php
- fix TypeError
- update test code
**Checklist:**
> [4.5] fix: TypeError in Filters 

- phpstan-baseline.php
- system/Images/Handlers/ImageMagickHandler.php
- tests/system/Images/ImageMagickHandlerTest.php
We should check if the `convert` program exists before doing any processing. Currently, it just checks for a non-empty string in the config file, which is insufficient.
**Checklist:**
> fix: [ImageMagickHandler] early terminate processing of invalid library path

- system/Images/Handlers/ImageMagickHandler.php
- tests/system/Images/ImageMagickHandlerTest.php
Refactoring to use one `preg_match` call instead of `preg_match` then `str_replace`.
**Checklist:**
> refactor: simplify ImageMagickHandler::getVersion()

- phpstan-baseline.php
- system/BaseModel.php
```
------ ------------------------------------------------------------------------- 
Line   src/Models/LoginModel.php                                                
------ ------------------------------------------------------------------------- 
37     Property CodeIgniter\Shield\Models\LoginModel::$validationRules          
(list<string>|string) does not accept default value of type              
array{ip_address: 'required', id_type: 'required', identifier:           
'permit_empty|string', user_agent: 'permit_empty|string', user_id:       
'permit_empty', date: 'required'}.                                       
💡 Type #1 from the union: array{ip_address: 'required', id_type:         
'required', identifier: 'permit_empty|string', user_agent: …
```
> docs: fix PHPDoc types in BaseModel

- .github/workflows/test-phpcpd.yml
- app/Config/Cors.php
- app/Config/Filters.php
- system/CodeIgniter.php
- system/Config/Filters.php
- system/Filters/Cors.php
- system/HTTP/Cors.php
- tests/system/Filters/CorsTest.php
- tests/system/HTTP/CorsTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/incoming/filters.rst
- user_guide_src/source/libraries/cors.rst
- user_guide_src/source/libraries/cors/001.php
- user_guide_src/source/libraries/cors/002.php
- user_guide_src/source/libraries/cors/003.php
- user_guide_src/source/libraries/cors/004.php
- user_guide_src/source/libraries/cors/005.php
- user_guide_src/source/libraries/index.rst
- add `Cors` filter class
- add `HTTP\Cors` class
**Checklist:**
> feat: add CORS filter

- user_guide_src/source/installation/upgrade_450.rst
- improve upgrade instruction
**Checklist:**
> docs: improve upgrade instruction to Auto Routing (Legacy)

- system/Test/Fabricator.php
- tests/system/Database/Live/FabricatorLiveTest.php
- tests/system/Test/FabricatorTest.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/testing/fabricator.rst
- user_guide_src/source/testing/fabricator/022.php
- user_guide_src/source/testing/fabricator/023.php
> feat: Support faker modifiers on Fabricator

- app/Config/Security.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/installation/upgrade_450.rst
- user_guide_src/source/libraries/security.rst
Set to `true` automatically in production environment.
**Checklist:**
> feat: environment-specific Config\Security::$redirect

- user_guide_src/source/installation/upgrade_4xx.rst
- user_guide_src/source/installation/upgrade_images.rst
- user_guide_src/source/installation/upgrade_images/001.php
- user_guide_src/source/installation/upgrade_images/ci3sample/001.php
> docs: add missing "Upgrade Image Manipulation Class"

- system/Debug/ExceptionHandler.php
- tests/system/Debug/ExceptionHandlerTest.php
- user_guide_src/source/changelogs/v4.4.8.rst
It should be determined by the HTTP status code.
Otherwise, if by chance an exception with code 404 is thrown, a 404 Not Found page will be displayed.
```php
<?php
use Exception;
{
{
throw new Exception('This is an exception message', 404);
}
}
```
Before:
404 - Page Not Found
```
404
This is an exception message
```
HTTP Status: 500
After:
Exception
```
Exception #404
This is an exception message 
```
HTTP Status: 500
**Checklist:**
> fix: the error view is determined by Exception code

- app/Config/Database.php
- phpstan-baseline.php
- system/Database/BaseConnection.php
- system/Database/MySQLi/Forge.php
- user_guide_src/source/changelogs/v4.5.0.rst
- remove inappropriate default values
- add sample db config as comments
- deprecate BaseConnection::$strictOn
**Checklist:**
> refactor: DB config properties

- system/Database/BaseBuilder.php
`BaseConnection` is implements `ConnectionInterface` so it can be removed from `@return` doc. Detected by run latest `"rector/rector": "dev-main"`
**Checklist:**
> docs: remove useless @return BaseConnection|ConnectionInterface on BaseBuilder::db()

- phpstan-baseline.php
- rector.php
- system/CLI/CLI.php
- system/Commands/Database/MigrateStatus.php
- system/Config/DotEnv.php
- system/Controller.php
- system/Database/OCI8/Builder.php
- system/HTTP/DownloadResponse.php
- system/Helpers/filesystem_helper.php
- system/Helpers/form_helper.php
- system/Helpers/html_helper.php
- system/Helpers/url_helper.php
- system/Router/RouteCollection.php
- system/Session/Handlers/FileHandler.php
- system/View/Table.php
- tests/system/Cache/ResponseCacheTest.php
Make if conditions more explicit and reduce phpstan baseline errors.
**Checklist:**
> refactor: [Rector] Apply ExplicitBoolCompareRector

- phpstan-baseline.php
- system/Pager/Pager.php
- tests/system/Pager/PagerTest.php
Closes #8698
See https://github.com/codeigniter4/CodeIgniter4/issues/8698#issuecomment-2033999881
**Checklist:**
> fix: `Pager::only([])` does not work

- phpstan-baseline.php
- system/BaseModel.php
- update `@var` types
**Checklist:**
> docs: update `@var` types in BaseModel

- user_guide_src/source/models/model/003.php
- user_guide_src/source/models/model/004.php
- user_guide_src/source/models/model/027.php
- user_guide_src/source/models/model/034.php
- user_guide_src/source/models/model/038.php
- user_guide_src/source/models/model/040.php
- user_guide_src/source/models/model/041.php
- user_guide_src/source/models/model/050.php
- user_guide_src/source/models/model/051.php
- user_guide_src/source/models/model/052.php
- user_guide_src/source/models/model/054.php
To make it clear that only a part of the code is shown.
**Checklist:**
> docs: add `// ...` to Model sample code

- user_guide_src/source/outgoing/alternative_php.rst
- user_guide_src/source/outgoing/alternative_php/001.php
It is bad practice to output variables without escaping in HTML.
**Checklist:**
> docs: add escaping to variables in sample code

- user_guide_src/source/concepts/security.rst
Follow-up #8652
- update "Security Guidelines" for 4.5
**Checklist:**
> docs: add new 4.5 features to "Security Guidelines"

- system/Commands/Utilities/ConfigCheck.php
- user_guide_src/source/general/configuration.rst
- `spark config:check` detects Config Caching.
- it shows Config Caching state at the bottom.
```console
$ php spark config:check Security
CodeIgniter v4.4.7 Command Line Tool - Server Time: 2024-04-05 00:14:18 UTC+00:00
Config\Security#32 (9) (
public 'csrfProtection' -> string (6) "cookie"
public 'tokenRandomize' -> boolean false
public 'tokenName' -> string (14) "csrf_test_name"
public 'headerName' -> string (12) "X-CSRF-TOKEN"
public 'cookieName' -> string (16) "csrf_cookie_name"
public 'expires' -> integer 7200
public 'regenerate' -> boolean true
public 'redirect' -> boolean false
public 'samesite' -> string (3) "Lax"
)
Config Caching: Disabled
```
**Checklist:**
- [] Unit testing, with >80% …
> feat: `spark config:check` detects Config Caching

- user_guide_src/source/concepts/security.rst
- user_guide_src/source/models/model.rst
~~Needs #8652~~
- add "OWASP API Security Top 10 2023"
Frankly, CI4 offers very few features for API Security.
**Checklist:**
> docs: add "OWASP API Security Top 10 2023" to Security Guidelines

- user_guide_src/source/concepts/security.rst
Follow-up #8669
- add items to "CodeIgniter provisions"
**Checklist:**
> docs: update "Security Guidelines" for APIs

- user_guide_src/source/incoming/controllers.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/installation/index.rst
- user_guide_src/source/installation/upgrade_4xx.rst
- user_guide_src/source/installation/upgrade_configuration.rst
- user_guide_src/source/installation/upgrade_controllers.rst
- user_guide_src/source/installation/upgrade_database.rst
- user_guide_src/source/installation/upgrade_emails.rst
- user_guide_src/source/installation/upgrade_encryption.rst
- user_guide_src/source/installation/upgrade_file_upload.rst
- user_guide_src/source/installation/upgrade_html_tables.rst
- user_guide_src/source/installation/upgrade_images.rst
- user_guide_src/source/installation/upgrade_localization.rst
- user_guide_src/source/installation/upgrade_migrations.rst
- user_guide_src/source/installation/upgrade_models.rst
- user_guide_src/source/installation/upgrade_pagination.rst
- user_guide_src/source/installation/upgrade_responses.rst
- user_guide_src/source/installation/upgrade_routing.rst
- user_guide_src/source/installation/upgrade_security.rst
- user_guide_src/source/installation/upgrade_sessions.rst
- user_guide_src/source/installation/upgrade_validations.rst
- user_guide_src/source/installation/upgrade_view_parser.rst
- user_guide_src/source/installation/upgrade_views.rst
- user_guide_src/source/libraries/uploaded_files.rst
It seems we often use `3.x` instead of `3.X`.
See https://codeigniter.com/user_guide/installation/upgrade_4xx.html
**Checklist:**
> docs: make CI3 notation consistent

- system/HTTP/Files/UploadedFile.php
- system/HTTP/Files/UploadedFileInterface.php
- fix `@param` types
**Checklist:**
> docs: fix @param types in UploadedFile

- CHANGELOG.md
- phpdoc.dist.xml
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.4.8.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_448.rst
Updates changelog and version references for 4.4.8.
Previous version: #8674
**Checklist:**
> Prep for 4.4.8 release

- user_guide_src/source/installation/deployment.rst
- user_guide_src/source/installation/running.rst
Because the section has moved to a new page in 4.5 branch.
**Checklist:**
> docs: fix merge mistake about "Deployment to Shared Hosting Services"

- CHANGELOG.md
- phpdoc.dist.xml
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.5.0.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_450.rst
- user_guide_src/source/intro/requirements.rst
Updates changelog and version references for 4.5.0.
Previous version: #8718
**Checklist:**
> Prep for 4.5.0 release

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.5.1.rst
- user_guide_src/source/installation/upgrade_451.rst
- user_guide_src/source/installation/upgrading.rst
- add changelog and upgrade for v4.5.1
**Checklist:**
> docs: add changelog and upgrade for v4.5.1

- user_guide_src/source/installation/upgrade_450.rst
> docs: fix typo in upgrade_450

- user_guide_src/source/tutorial/static_pages/002.php
Because new php-cs-fixer moves the comment line.
```diff
--- /home/runner/work/CodeIgniter4/CodeIgniter4/user_guide_src/source/tutorial/static_pages/002.php
+++ /home/runner/work/CodeIgniter4/CodeIgniter4/user_guide_src/source/tutorial/static_pages/002.php
@@ -2,7 +2,9 @@
-use CodeIgniter\Exceptions\PageNotFoundException; // Add this line
+use CodeIgniter\Exceptions\PageNotFoundException;
+
+ // Add this line
class Pages extends BaseController
{
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/8608835712/job/23591835999?pr=8731
**Checklist:**
> docs: change comment position in Tutorial code

- system/Commands/Housekeeping/ClearDebugbar.php
- tests/system/Commands/ClearDebugbarTest.php
- writable/index.html
Follow-up #8734
- update ClearDebugbar.php
- update test code
- add writable/index.html
**Checklist:**
> fix: update `debugbar:clear` code because of file changes

- phpstan-baseline.php
- system/BaseModel.php
- system/Model.php
Follow-up #8538
See #7177
See https://github.com/codeigniter4/shield/issues/1092
**Checklist:**
> fix: TypeError when Time is passed to Model

- phpstan-baseline.php
- tests/_support/Config/Registrar.php
See #8732
- replace `empty()`
- add types
**Checklist:**
> test: refactor Config/Registrar.php

- phpstan-baseline.php
- system/CLI/BaseCommand.php
See #8732
- replace `empty()`
- add types
**Checklist:**
> refactor: system/CLI/BaseCommand.php

- system/Config/Factories.php
- tests/system/Config/FactoriesTest.php
If we define() and get(), the error like this occurs:
```
ErrorException: Undefined array key "models"
```
**Checklist:**
> fix: Factories::get() cannot get defined classes

- system/Database/BaseConnection.php
- system/Database/Postgre/Connection.php
- system/I18n/Time.php
- tests/system/Database/Live/EscapeTest.php
Supersedes #8739
- `BaseConnection::escape()` accepts Stringable
- `BaseConnection::escapeString()` accepts Stringable
- `Time` implements `Stringable`
```
TypeError: CodeIgniter\Database\SQLite3\Connection::_escapeString(): Argument #1 ($str) must be of type string, CodeIgniter\I18n\Time given
```
See also https://github.com/codeigniter4/shield/issues/1092
**Checklist:**
> fix: `BaseConnection::escape()` does not accept Stringable

- phpstan-baseline.php
- system/HTTP/CURLRequest.php
- tests/system/HTTP/CURLRequestDoNotShareOptionsTest.php
- tests/system/HTTP/CURLRequestTest.php
Fixes #8750
- remove the default Response Content-Type header
**Checklist:**
> fix: [CURLRequest] `getHeaderLine('Content-Type')` causes InvalidArgumentException

- phpstan-baseline.php
- system/HTTP/CURLRequest.php
The construct parameter should be used.
**Checklist:**
> fix: [CURLRequest] construct param $config is not used

- system/View/Plugins.php
- tests/system/View/ParserPluginTest.php
- fix method name
- add test cases
**Checklist:**
> refactor: fix method name `ValidationErrors` in View\Plugins

- tests/system/Helpers/FormHelperTest.php
- add tests for form_helper with CSRF filter
**Checklist:**
> test: add tests for form_helper with CSRF filter

- phpstan-baseline.php
- system/Debug/BaseExceptionHandler.php
See https://forum.codeigniter.com/showthread.php?tid=90626
- improve error message
- replace `empty()`
**Checklist:**
> refactor: improve error message in BaseExceptionHandler

- admin/create-new-changelog.php
Does not work for minor update.
**Checklist:**
> chore: fix `create-new-changelog.php` for minor update

- phpstan-baseline.php
- system/Test/Interfaces/FabricatorModel.php
- tests/_support/Models/FabricatorModel.php
- user_guide_src/source/testing/fabricator/001.php
See #8732
- add array types
**Checklist:**
> refactor: FabricatorModel

- system/Autoloader/FileLocator.php
See https://github.com/codeigniter4/shield/issues/1091
If you define a namespace in another namespace,
```php
public $psr4 = [
APP_NAMESPACE => APPPATH,
'Shield'      => APPPATH . 'ThirdParty/Shield',
];
```
The file path `app/ThirdParty/Shield/Config/Auth.php` could be
1. `App\ThirdParty\Shield\Config\Auth`
2. `Shield\Config\Auth`
`findQualifiedNameFromPath()` tries to find `App\ThirdParty\Shield\Config\Auth` more than once,
then the following error occurs:
> Cannot declare class Shield\Config\Auth, because the name is already in use
The error does not occur if `app/Config/Auth.php` exists.
**Checklist:**
> fix: [FileLocator] Cannot declare class XXX, because the name is already in use

- user_guide_src/source/installation/installing_composer.rst
- user_guide_src/source/installation/installing_manual.rst
- add a sub section
**Checklist:**
> docs: add "Upgrading to a Specified Version"

- user_guide_src/source/incoming/controllers.rst
Change "a HTTP" to "an HTTP".
**Checklist:**
> docs: Small typo in controllers.rst

- user_guide_src/source/incoming/routing.rst
Changed "a HTTP" to "an HTTP".
**Checklist:**
> docs: Small typo in routing.rst

- admin/css/debug-toolbar/README.md
- admin/css/debug-toolbar/toolbar.scss
- contributing/css.md
- system/Debug/Toolbar/Views/toolbar.css
From https://forum.codeigniter.com/showthread.php?tid=90624
If a dev changes CSS for `h1`, the toolbar dislpay will be broken.
Before:
After:
```diff
--- a/app/Views/welcome_message.php
+++ b/app/Views/welcome_message.php
@@ -34,6 +34,16 @@
.menu {
padding: .4rem 2rem;
}
+        h1 {
+            font-size: 1.8em;
+            font-weight: 400;
+            font-family:'Open Sans', Sans-serif;
+            text-transform: uppercase;
+            color: #464646;
+            background-color: #f4f9eb;
+            padding: 1.4em 0 1.4em 20px;
+            margin: 0 0 1em;
+        }
header ul {
border-bottom: 1px solid rgba(242, 242, 242, 1);
list-style-type: none;
```
**Checklist:**
> fix: [DebugBar] Toolbar display may be broken

- .gitignore
- admin/framework/.gitignore
- admin/framework/phpunit.xml.dist
- admin/starter/.gitignore
- admin/starter/phpunit.xml.dist
- phpunit.xml.dist
- move PHPUnit cache to build/
- update phpunit.xml.dist for framework and appstarter
- update gitignore
**Checklist:**
> chore: move PHPUnit cache to build/

- system/Config/BaseService.php
Follow-up #8745
See https://github.com/codeigniter4/CodeIgniter4/pull/8745#issuecomment-2052569997
In this case, `CodeIgniter\Config\Services` was already loaded in the `Boot` class.
In auto-discovery, checking `vendor/codeigniter4/codeigniter4/system/Config/Services.php` first time (`Translations\vendor\codeigniter4\codeigniter4\system\Config\Services`) causes a Fatal error.
**Checklist:**
> fix: Cannot declare class CodeIgniter\Config\Services, because the name is already in use

- user_guide_src/source/database/configuration/010.php
See #8771
The following setting 
```
'DSN' => 'Postgre://postgres:postgres@localhost:5432/test?charset=utf8&connect_timeout=5&sslmode=1',    
```
causes the error:
>CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: invalid sslmode value: "1"
See "Table 33.1. SSL Mode Descriptions"
in https://www.postgresql.org/docs/12/libpq-ssl.html#LIBPQ-SSL-PROTECTION
**Checklist:**
> docs: fix Postgre DSN sample

- CHANGELOG.md
- phpdoc.dist.xml
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.5.1.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_451.rst
Updates changelog and version references for 4.5.1.
Previous version: #8722
**Checklist:**
> Prep for 4.5.1 release

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/installation/upgrade_460.rst
- user_guide_src/source/installation/upgrading.rst
```
php admin/create-new-changelog.php 4.5.x 4.6.0
```
**Checklist:**
> docs: add changelog and upgrade for v4.6.0

- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/outgoing/index.rst
- user_guide_src/source/outgoing/view_decorators.rst
- user_guide_src/source/outgoing/view_decorators/002.php
- user_guide_src/source/outgoing/view_parser.rst
- user_guide_src/source/outgoing/views.rst
- minor improvements
**Checklist:**
> docs: improve View pages

- .php-cs-fixer.dist.php
- .php-cs-fixer.no-header.php
- .php-cs-fixer.tests.php
- .php-cs-fixer.user-guide.php
Reverts the changes to #7712 now that v4.5.0 is out.
**Checklist:**
> chore: Revert disabling custom fixers for PHP 7.4

- phpstan-baseline.php
- system/API/ResponseTrait.php
- tests/system/API/ResponseTraitTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/installation/upgrade_460.rst
- user_guide_src/source/outgoing/api_responses/002.php
- remove deprecated method. It was deprecated in v4.1.2 https://github.com/codeigniter4/CodeIgniter4/pull/4609/commits/3af7080d809863e6d81eb205220b4f633a4421be
**Checklist:**
> refactor: remove deprecated failValidationError() in API\ResponseTrait

- .php-cs-fixer.dist.php
- preload.php
- system/Boot.php
> fix: update `preload.php` for 4.5

- system/Security/CheckPhpIni.php
Fixes #8803
```console
$ ./spark phpini:check
CodeIgniter v4.5.1 Command Line Tool - Server Time: 2024-04-19 00:01:44 UTC+00:00
+-------------------------+----------+----------+-------------+-----------------------+
| Directive               | Global   | Current  | Recommended | Remark                |
+-------------------------+----------+----------+-------------+-----------------------+
| error_reporting         | 32767    | 32767    | 5111        |                       |
| display_errors          | 1        | 1        | 0           |                       |
| display_startup_errors  | 1        | 1        | 0           |                       |
| log_errors              | 1        | 1        |             |                       |
| error_log               |          | …
```
> fix: [ErrorException] Undefined array key in `spark phpini:check`

- system/HTTP/ResponseTrait.php
- system/Language/en/Security.php
- system/Security/Exceptions/SecurityException.php
- tests/system/HTTP/ResponseSendTest.php
- user_guide_src/source/changelogs/v4.5.2.rst
See https://forum.codeigniter.com/showthread.php?tid=90653&pid=418015#pid418015
This is a server side misconfiguration, not a client error.
**Checklist:**
> fix: incorrect Security exception message

- phpstan-baseline.php
- system/Database/BaseBuilder.php
See https://github.com/codeigniter4/CodeIgniter4/actions/runs/8748888596/job/24009622239
Related #8732
**Checklist:**
> docs: fix @param BaseBuilder.php

- system/Database/BaseBuilder.php
- system/Database/SQLSRV/Builder.php
- tests/system/Database/Builder/JoinTest.php
Fixes #8791
This PR makes the same behavior as v4.4.x or before.
- ad hoc fix
**Checklist:**
> fix: [QueryBuilder] TypeError in join() with BETWEEN

- user_guide_src/source/installation/upgrade_4xx.rst
- user_guide_src/source/installation/upgrade_responses.rst
- change page title
- fix typo
**Checklist:**
> docs: small fixes in  upgrade responses.rst

- user_guide_src/source/database/configuration.rst
- user_guide_src/source/database/helpers.rst
- user_guide_src/source/database/index.rst
- user_guide_src/source/database/query_builder.rst
- user_guide_src/source/database/results.rst
Some typos in database/configuration.rst
**Checklist:**
> docs: Some typos in database/configuration.rst

- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/outgoing/localization.rst
> docs: improve lang()

- user_guide_src/source/libraries/curlrequest/009.php
The `getReason()` method is deprecated. See https://codeigniter4.github.io/CodeIgniter4/installation/upgrade_405.html#message-getheader-s
- update deprecated method in sample code
**Checklist:**
> docs: update deprecated method in sample code in CURLRequest

- system/Database/SQLSRV/Builder.php
- tests/system/Database/Builder/FromTest.php
> fix: [SQLSRV] Query Builder always sets "<database>"."<schema>". to the table name.

- system/Test/Mock/MockCache.php
It is not defined in the interface or other classes, and not used at all.
See also https://github.com/codeigniter4/CodeIgniter4/pull/8846#discussion_r1585689583
**Checklist:**
> fix: remove unused undefined param $raw in MockCache::save()

- phpstan-baseline.php
- system/Config/Filters.php
See #8732
Added doc comment in system/Config/Filters.php 
**Checklist:**
> docs: Resolved phpstan error in Config/Filters.php

- .github/workflows/test-phpstan.yml
- phpstan-baseline.php
Follow-up #8821
- add `tests/` for PHPStan paths
- update PHPStan baseline
**Checklist:**
> chore: update phpstan-baseline

- system/Files/FileCollection.php
- tests/system/Files/FileCollectionTest.php
- tests/system/Helpers/FilesystemHelperTest.php
- tests/system/Publisher/PublisherInputTest.php
- tests/system/Publisher/PublisherOutputTest.php
Fixes a bug that the pseudo-regex `'*_?.php'` matches `fig_3.php.txt`.
**Checklist:**
> fix: FileCollection pseudo-regex

- system/DataCaster/DataCaster.php
- tests/_support/Models/UserCastsTimestampModel.php
> fix: [Model] casting may throw InvalidArgumentException: Invalid parameter: nullable

- system/Model.php
- tests/system/Models/DataConverterModelTest.php
Supersedes #8807
Fixes #8806
**Checklist:**
> fix: [Model] casting causes TypeError when finding no record

- user_guide_src/source/libraries/uploaded_files.rst
- user_guide_src/source/libraries/validation.rst
See #8874
- improve readability
**Checklist:**
> docs: improve file upload validation

- system/Email/Email.php
Make them the same as in the Config\Email.
Related #8851
**Checklist:**
> fix: correct property default values in Email

- phpstan-baseline.php
- system/CLI/CLI.php
- tests/system/CLI/CLITest.php
Fixes #8861
- fix CLI::promptByMultipleKeys() TypeError
- fix bug that CLI::prompt() may incorrectly return default value
**Checklist:**
> fix: CLI::promptByMultipleKeys() and prompt()

- user_guide_src/source/concepts/autoloader.rst
> docs: fix text decoration in autoloader.rst

- user_guide_src/source/_static/css/citheme.css
Prevent text-wrap in user guide. For example 
```
$this-
>validateData() should stay unwrapped ($this->validateData()).
```
**Checklist:**
> docs: Prevent text-wrap in user guide

- phpstan-baseline.php
- system/View/Cell.php
- system/View/Filters.php
- system/View/Parser.php
- system/View/RendererInterface.php
- system/View/Table.php
- system/View/View.php
> docs: fix PHPDocs for `View`

- user_guide_src/source/libraries/uploaded_files.rst
Small typos in libraries/uploaded_files.rst
**Checklist:**
> docs: Small typos in libraries/uploaded_files.rst

- user_guide_src/source/models/model.rst
- improve the description
**Checklist:**
> docs: improve Note for in-Model Validation

- .github/workflows/test-file-permissions.yml
- utils/check_permission_x.php
See https://github.com/codeigniter4/CodeIgniter4/pull/8918#pullrequestreview-2082853252
Result:
```
Run php utils/check_permission_x.php
Files with unnecessary execution permissions were detected:
- admin/starter/tests/index.html
- admin/starter/tests/.htaccess
- app/Config/DocTypes.php
- system/Test/Mock/MockResponse.php
- system/Helpers/text_helper.php
- system/Helpers/cookie_helper.php
- system/Helpers/inflector_helper.php
- system/Helpers/html_helper.php
- system/HTTP/IncomingRequest.php
- system/Database/SQLSRV/Builder.php
- system/Database/SQLSRV/Connection.php
- system/Database/SQLSRV/PreparedQuery.php
- system/Database/SQLSRV/Forge.php
- system/Database/SQLSRV/Result.php
- system/Database/SQLSRV/Utils.php
- tests/system/Helpers/InflectorHelperTest.php
- …
```
> chore: add file permission check workflow

- system/Test/PhpStreamWrapper.php
Detected by latest rector rule: `RemoveUnusedPublicMethodParameterRector` 
- https://github.com/rectorphp/rector-src/pull/5925
**Checklist:**
> refactor: remove unused path parameter on PhpStreamWrapper::stream_open()

- user_guide_src/source/outgoing/view_cells.rst
- user_guide_src/source/outgoing/view_cells/023.php
See https://forum.codeigniter.com/showthread.php?tid=90967&pid=419195#pid419195
This is due to the behavior of get_object_vars().
See https://www.php.net/manual/ja/function.get-object-vars.php#127940
**Checklist:**
> docs: add note for View Cells typed properties

- system/Database/BaseConnection.php
- system/Database/Postgre/Connection.php
- tests/system/Database/Live/Postgre/ConnectTest.php
See #8912
Shows PostgreSQL error message in Database Exception.
**Checklist:**
> fix: [Postgres] show missing error message

- user_guide_src/source/testing/overview.rst
Small typo in testing/overview.rst
**Checklist:**
> docs: Small typo in testing/overview.rst

- user_guide_src/source/libraries/caching.rst
Fix typos in libraries/caching.rst
**Checklist:**
> docs: Fix typos in libraries/caching.rst

- user_guide_src/source/_static/css/citheme.css
Add span.pre to span.std to prevent text-wrap in user guide citheme.css
**Checklist:**
> docs: Prevent text-wrap for span.pre in user guide citheme.css

- system/Helpers/number_helper.php
- tests/system/Helpers/NumberHelperTest.php
From https://forum.codeigniter.com/showthread.php?tid=90996
**Checklist:**
> fix: TypeError in  number_to_amount() 

- user_guide_src/source/helpers/form_helper.rst
- user_guide_src/source/incoming/filters.rst
- user_guide_src/source/libraries/security.rst
Superseds #8915
- Change HTML 'tag's to 'element's in helpers/form_helper.rst
**Checklist:**
> docs: fix helpers/form_helper.rst

- user_guide_src/source/general/errors.rst
Supersedes #8907
**Checklist:**
> docs: fix typo in errors.rst

- CHANGELOG.md
- admin/next-upgrading-guide.rst
- phpdoc.dist.xml
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.5.2.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_452.rst
Updates changelog and version references for 4.5.2.
Previous version: #8782
**Checklist:**
> Prep for 4.5.2 release

- user_guide_src/source/extending/core_classes.rst
Fix typo in extending/core_classes.rst
**Checklist:**
> docs: Fix typo in extending/core_classes.rst

- user_guide_src/source/concepts/goals.rst
- user_guide_src/source/concepts/index.rst
I don't know why this "Design and Architectural Goals" was removed in 4.0 user guide.
But I would like to restore it.
Basically, this goal is still valid today. If there are any changes that should be made, 
please comment.
**Checklist:**
> docs: restore goals.rst from 3.0 user guide

- user_guide_src/source/extending/events.rst
Small typos in extending/events.rst
**Checklist:**
> docs: Small typos in extending/events.rst

- system/Cache/Handlers/RedisHandler.php
- tests/system/Cache/Handlers/RedisHandlerTest.php
Supersedes and closes #8878 
**Checklist:**
> fix: `RedisHandler::deleteMatching()` not deleting matching keys if cache prefix is used

- system/Files/FileCollection.php
- tests/system/Files/FileCollectionTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/libraries/file_collections.rst
- user_guide_src/source/libraries/files/016.php
Supersedes #8953
Add a method to ``FileCollection`` that accepts an array of strings to retain multiple patterns in the file collection.
**Checklist:**
> feat: [FileCollection] add function to reatain multiple patterns

- phpstan-baseline.php
- system/Router/DefinedRouteCollector.php
- system/Router/RouteCollectionInterface.php
- system/Router/Router.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/installation/upgrade_460.rst
Supersedes #8206
See #6814
- fix RouteCollectionInterface
- DefinedRouteCollector uses RouteCollectionInterface instead of RouteCollection
**Checklist:**
> fix: DefinedRouteCollector to use RouteCollectionInterface

- composer.json
See https://github.com/codeigniter4/CodeIgniter4/issues/8951#issuecomment-2164052589
E.g.,
> Class Laminas\Escaper\Escaper located in ./system/ThirdParty/Escaper/Escaper.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
**Checklist:**
> chore: add autoload.exclude-from-classmap to suppress Composer 2.7.7 warnings

- .github/workflows/deploy-apidocs.yml
Closes #8949
See https://github.com/phpDocumentor/phpDocumentor/issues/3725#issuecomment-2145896103
**Checklist:**
> chore: workaround for phpDocumentor error

- system/Router/DefinedRouteCollector.php
- tests/system/Router/DefinedRouteCollectorTest.php
Fixes #8954
```
1) CodeIgniter\Router\DefinedRouteCollectorTest::testCollect
TypeError: CodeIgniter\Router\RouteCollection::getRoutesOptions(): Argument #1 ($from) must be of type ?string, int given, called in .../CodeIgniter4/system/Router/DefinedRouteCollector.php on line 48
```
**Checklist:**
> fix: TypeError in DefinedRouteCollector::collect()

- system/Commands/Database/MigrateRollback.php
- tests/system/Commands/DatabaseCommandsTest.php
> fix: `migrate:rollback -b` does not work due to TypeError

- phpstan-baseline.php
- tests/system/Commands/CommandTest.php
- fix PHPStan errors
**Checklist:**
> test: fix PHPStan errors in CommandTest

- system/Validation/FormatRules.php
- system/Validation/Validation.php
- tests/system/Validation/RulesTest.php
- tests/system/Validation/StrictRules/RulesTest.php
Fixes #8956
Fixed the bug that If an array is passed, Validation with `if_exist` rule always returns `true`.
**Checklist:**
> fix: [Validation] `if_exist` does not work with array data

- admin/starter/composer.json
- user_guide_src/source/concepts/autoloader.rst
See https://github.com/codeigniter4/CodeIgniter4/issues/8951#issuecomment-2164059098
To suppress Composer's warning like this:
> Class Config\Email located in ./app/Config/Email.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
**Checklist:**
> chore: add `Config` namespace to appstarter autoload.psr4

- phpstan-baseline.php
- system/Commands/Database/ShowTableInfo.php
- system/Commands/ListCommands.php
- system/Commands/Utilities/Routes/AutoRouterImproved/AutoRouteCollector.php
> docs: fix `PHPStan` in `Commands`

- system/Commands/Utilities/Routes/FilterFinder.php
- system/Config/BaseService.php
- system/Router/Router.php
- tests/system/Commands/RoutesTest.php
Fixes #8972
```diff
@@ -6,3 +6,4 @@ use CodeIgniter\Router\RouteCollection;
* @var RouteCollection $routes
*/
+$routes->options('picker/(.+)', 'Options::index');
```
Before:
```console
$ ./spark routes
CodeIgniter v4.5.2 Command Line Tool - Server Time: 2024-06-19 03:40:45 UTC+00:00
[CodeIgniter\HTTP\Exceptions\BadRequestException]
The URI you submitted has disallowed characters: "(. )"
at SYSTEMPATH/Router/Router.php:736
Backtrace:
1    SYSTEMPATH/Router/Router.php:203
CodeIgniter\Router\Router()->checkDisallowedChars('picker/(. )')
...
```
After:
```console
$ ./spark routes
CodeIgniter v4.5.2 Command Line Tool - Server Time: 2024-06-19 03:41:40 UTC+00:00 …
```
> fix: `spark routes` may show BadRequestException when a route has a regexp

- system/Validation/FileRules.php
- tests/system/Validation/FileRulesTest.php
- tests/system/Validation/StrictRules/FileRulesTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/libraries/validation.rst
Add  `min_dims` validation rule to the `FileRules` class
**Checklist:**
> feat: [Validation] add `min_dims` rule in FileRules

- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/incoming/routing/026.php
> docs: fix incorrect description for route group filter

- phpstan-baseline.php
- system/Database/BaseConnection.php
- system/Database/MySQLi/Connection.php
- system/Database/Postgre/Connection.php
- system/Database/SQLSRV/Connection.php
- system/Database/SQLite3/Connection.php
- system/Test/Mock/MockConnection.php
- Make return types a little precise.
- Fixed a param type of MockConnection
**Checklist:**
> fix: return and param types of BaseConnection

- tests/system/Config/BaseConfigTest.php
- tests/system/Test/FabricatorTest.php
using phpunit 10 assertObjectHasNotProperty() and assertObjectHasProperty(), detected by latest rector dev-main
- https://github.com/rectorphp/rector-phpunit/pull/338
- https://github.com/rectorphp/rector-phpunit/pull/340
**Checklist:**
> refactor: using phpunit 10 assertObjectHasNotProperty() and assertObjectHasProperty()

- system/CLI/Commands.php
- tests/_support/_command/ListCommands.php
- tests/system/Commands/CommandOverrideTest.php
This PR allows users to override commands in the framework with commands in `App\Commands`,
and prevents other packages from overriding commands in the framework.
This PR changes to use the first command class discovered.
In the current implementation, the last class discovered is executed. 
However, for CI4's behavior, if there is a command class in `App\Commands`, it should take precedence.
See also https://forum.codeigniter.com/showthread.php?tid=90877&pid=418854#pid418854
**Checklist:**
> fix: precedence of command classes with the same `$name`

- system/View/View.php
- tests/system/View/ViewTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
From https://forum.codeigniter.com/showthread.php?tid=91082
The method should not use `echo`, because it has side effects.
**Checklist:**
> fix: View::renderSection() return type

- phpstan-baseline.php
- system/Filters/Filters.php
- tests/system/CodeIgniterTest.php
- tests/system/Filters/FiltersTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/incoming/filters.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/installation/upgrade_460.rst
Fixes #8973
- enables a filter to run more than once with the different arguments
- changes array structure of `Filters::$filters` and `$filtersClasses`
- `Filters::$arguments` and `$argumentsClass` are no longer used
- does not instantiate the same filter class more than once
- `spark routes` and `filter:check` show filter arguments
**Checklist:**
> feat: [Filters] enables a filter to run more than once with different arguments

- system/Language/en/Validation.php
- user_guide_src/source/changelogs/v4.6.0.rst
Add missing validation message for `min_dims` validation rule introduced in #8966 
**Checklist:**
> [4.6] fix: add validation message for min_dims

- system/Router/AutoRouterImproved.php
- tests/system/Router/AutoRouterImprovedTest.php
- fix bug that [Default Method Fallback](https://codeigniter4.github.io/CodeIgniter4/incoming/controllers.html#default-method-fallback) does not work with `$translateUriToCamelCase`
Navigate to `http://localhost:8080/product/15/edit`.
Before:
```
404
"\App\Controllers\Product::get15()" is not found.
```
After:
```
$id string (2) "15"
$action string (4) "edit"
⧉ Called from .../app/Controllers/Product.php:12 [dd()]
```
```php
<?php
use App\Controllers\BaseController;
use CodeIgniter\HTTP\ResponseInterface;
class Product extends BaseController
{
public function getIndex($id = null, $action = '')
{
dd($id, $action);
}
}
```
```diff
diff --git a/app/Config/Feature.php b/app/Config/Feature.php
index efd4a0b20a..3e9e009657 100644
--- …
```
> fix: [Auto Routing Improved] Default Method Fallback does not work with `$translateUriToCamelCase`

- system/Commands/Server/Serve.php
- system/rewrite.php
From https://forum.codeigniter.com/showthread.php?tid=91137&pid=419751#pid419751
- move `rewrite.php` to `system/rewrite.php`
To avoid `CodeIgniter\CLI\Commands->discoverCommands()` loads `rewrite.php`.
`FileLocator::findQualifiedNameFromPath()` tries to generate classname from the path, and calls `class_exists()`, then it loads `rewrite.php`. If PHP_SAPI is `apache2handler`, it will be executed.
Before:
```diff
--- a/app/Controllers/Home.php
+++ b/app/Controllers/Home.php
@@ -6,6 +6,6 @@ class Home extends BaseController
{
{
-        return view('welcome_message');
+        return command('list');
}
}
diff --git a/system/Commands/Server/rewrite.php b/system/Commands/Server/rewrite.php
index f936cd63f0..6912b23834 100644
--- …
```
> fix: `command()` may execute `rewrite.php`

- CHANGELOG.md
- phpdoc.dist.xml
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.5.3.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_453.rst
Updates changelog and version references for 4.5.3.
Previous version: #8947
**Checklist:**
> Prep for 4.5.3 release

- admin/starter/composer.json
It seems better to put `/` at the end of directories. 
See https://getcomposer.org/doc/04-schema.md#psr-4
**Checklist:**
> chore: add missing `/` at the end in `starter/composer.json`

- user_guide_src/source/installation/upgrade_420.rst
> docs: add note to upgrade_420.rst

- app/Config/Database.php
- phpstan-baseline.php
- system/Database/BaseConnection.php
- system/Database/MySQLi/Connection.php
- tests/system/Database/Live/MySQLi/FoundRowsTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/database/configuration.rst
Added a new database config `foundRows` for MySQLi. Enabling this adds the flag `MYSQLI_CLIENT_FOUND_ROWS` when connecting to a MySQL database.
The flag changes the behaviour of `affectedRows()` for `UPDATE` or `INSERT ... ON DUPLICATE KEY UPDATE`, where the number of rows updated to the same value will also be returned. By default, it only returns the number rows with a value changed.
**Checklist:**
> feat: add `foundRows` option for MySQLi config

- rector.php
new `RectorConfig::configure()` syntax exists since Rector 1.0, this PR update to new syntax.
**Checklist:**
> chore: update to new RectorConfig::configure() syntax for config

- system/CLI/BaseCommand.php
- system/CLI/CLI.php
- system/CLI/GeneratorTrait.php
- system/Commands/ListCommands.php
- system/Commands/Utilities/Routes.php
- system/Commands/Utilities/Routes/AutoRouterImproved/AutoRouteCollector.php
- system/Cookie/Cookie.php
- system/DataCaster/DataCaster.php
- system/Database/BaseConnection.php
- system/Database/Forge.php
- system/Database/MigrationRunner.php
- system/Database/OCI8/Forge.php
- system/Database/SQLite3/Forge.php
- system/Images/Handlers/GDHandler.php
- system/Router/RouteCollection.php
- system/Validation/Rules.php
Detected by latest rector dev-main 
- https://github.com/rectorphp/rector-src/pull/6027
**Checklist:**
> refactor: use first class callable on function call

- phpstan-baseline.php
- system/Commands/Utilities/FilterCheck.php
- system/Commands/Utilities/Routes/FilterCollector.php
- system/Commands/Utilities/Routes/FilterFinder.php
- system/Filters/Filters.php
- tests/system/Commands/FilterCheckTest.php
- tests/system/Commands/Utilities/Routes/FilterFinderTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/incoming/filters.rst
Needs #8977
Before:
```console
$ ./spark filter:check GET admin/users/list
CodeIgniter v4.5.2 Command Line Tool - Server Time: 2024-06-24 00:57:28 UTC+00:00
+--------+------------------+----------------------------------------------+-------------------------------------------------------+
| Method | Route            | Before Filters                               | After Filters                                         |
+--------+------------------+----------------------------------------------+-------------------------------------------------------+
| GET    | admin/users/list | forcehttps pagecache csrf:config csrf:region | csrf:region csrf:config pagecache performance toolbar |
+--------+------------------+----------------------------------------------+------------------- …
```
> feat: `spark filter:check` shows filter classnames

- app/Config/Events.php
- rector.php
- system/Autoloader/Autoloader.php
- system/CLI/CLI.php
- system/CodeIgniter.php
- system/DataConverter/DataConverter.php
- system/Database/Postgre/Builder.php
- system/Database/Query.php
- system/Database/SQLSRV/Builder.php
- system/Database/SQLite3/Result.php
- system/Debug/Toolbar.php
- system/Filters/Filters.php
- system/HTTP/IncomingRequest.php
- system/HTTP/RequestTrait.php
enable AddClosureVoidReturnTypeWhereNoReturnRector to add void return on closure 
**Checklist:**
> refactor: enable AddClosureVoidReturnTypeWhereNoReturnRector to add void return on closure

- phpstan-baseline.php
- system/Filters/Filters.php
- tests/system/Filters/FiltersTest.php
This PR normalizes `$filters` arguments.
Because Route filter's arguments are already normalized (trimmed). 
https://github.com/codeigniter4/CodeIgniter4/blob/ab64aeb36ff9bb72da8459e4f73321b925c2c498/system/Filters/Filters.php#L489
https://github.com/codeigniter4/CodeIgniter4/blob/ab64aeb36ff9bb72da8459e4f73321b925c2c498/system/Filters/Filters.php#L517-L531
- normalize `$filters` arguments
- refactor
**Checklist:**
> fix: [Filters] normalize `$filters` arguments

- system/Database/BaseConnection.php
- tests/system/Database/Live/TransactionDBDebugTrueTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/database/transactions.rst
- user_guide_src/source/database/transactions/009.php
See #6909 https://github.com/codeigniter4/CodeIgniter4/pull/6886#issuecomment-1324182519
To restart transactions after strict mode failure.
**Checklist:**
> feat: add BaseConnection::resetTransStatus()

- system/Database/OCI8/Connection.php
- tests/system/Database/Live/OCI8/ConnectionTest.php
Fixes #9005
Follow-up #8986
**Checklist:**
> fix: [OCI8] Easy Connect string validation

- rector.php
- system/Common.php
- system/Helpers/cookie_helper.php
- system/Helpers/kint_helper.php
enable AddFunctionVoidReturnTypeWhereNoReturnRector to add void to functions
**Checklist:**
> refactor: enable AddFunctionVoidReturnTypeWhereNoReturnRector to add void to functions

- phpstan-baseline.php
- system/Database/BaseBuilder.php
- tests/system/Database/Builder/SelectTest.php
> fix: [QueryBuilder] select() with RawSql may cause TypeError

- system/Database/BaseBuilder.php
- tests/system/Database/Builder/SelectTest.php
Follow-up #1169
Fixes bug that `select()` does not escape items after `NULL`.
**Checklist:**
> fix: [QueryBuilder] `select()` does not escape after `NULL`

- rector.php
Resolve notice:
```
Run vendor/bin/rector process --dry-run --no-progress-bar
Warning: ] The following files were skipped as starting with short open tag.    
Migrate to long open PHP tag first:                                  
tests/system/View/Views/apples.php                                   
tests/system/View/Views/broken.php                                   
tests/system/View/Views/extend.php                                   
tests/system/View/Views/extend_include.php                           
tests/system/View/Views/extend_reuse_section.php                     
tests/system/View/Views/extend_two.php         
```
they are fixture files, so no need to be scanned by rector.
**Checklist:**
> chore: skip tests View fixtures from rector

- user_guide_src/source/libraries/validation.rst
> docs: improve validation.rst

- system/HTTP/CURLRequest.php
- tests/system/HTTP/CURLRequestTest.php
- user_guide_src/source/changelogs/v4.5.4.rst
The [docs](https://codeigniter4.github.io/userguide/libraries/curlrequest.html#version) (as of 4.5.3) specifies *"To set the HTTP protocol to use, you can pass a string or float with the version number"*. However, the code in the library does a strict comparison with `=== 2.0` so a string value **will not work**.
Adding a strict comparison with `'1.0'`, `'1.1'` and `'2.0'` since this seems to be the coding style used in the library. (A `==` comparison would work, but casting could introduce some issues?)
**Checklist:**
> fix: allow string as parameter to CURLRequest version

- system/Security/CheckPhpIni.php
> fix: `spark phpini:check` may cause TypeError

- admin/css/debug-toolbar/toolbar.scss
- system/Debug/Toolbar/Views/toolbar.css
Fixes #9041
How to Test:
```diff
--- a/app/Views/welcome_message.php
+++ b/app/Views/welcome_message.php
@@ -6,6 +6,8 @@
<meta name="description" content="The small framework with powerful features">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="shortcut icon" type="image/png" href="/favicon.ico">
+    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.10/dist/full.min.css" rel="stylesheet" type="text/css" />
+    <script src="https://cdn.tailwindcss.com"></script>
```
Before:
After:
**Checklist:**
> fix: DebugBar CSS for daisyUI

- .github/workflows/test-psalm.yml
- admin/starter/.github/workflows/phpunit.yml
This fixes a warning given by the Github Actions extension on vscode.
**Checklist:**
> chore: fix invalid symbol '"'

- user_guide_src/source/libraries/email.rst
Fix typos and add missing preferences in libraries/email.rst
**Checklist:**
> docs: Fix typos and add missing preferences in libraries/email.rst

- .github/workflows/reusable-phpunit-test.yml
Trying to fix the latest GitHub Actions failure for MSSQL.
See
- https://github.com/codeigniter4/CodeIgniter4/pull/9068#discussion_r1690620653
- https://github.com/microsoft/mssql-docker/issues/892#issuecomment-2248045546
- https://github.com/microsoft/mssql-docker/issues/892#issuecomment-2249029917
**Checklist:**
> chore: fix mssql-server 2022 failing to start

- system/Files/File.php
- user_guide_src/source/libraries/files.rst
`File::getSize` and `File::getSizeByUnit()` may cause a `RunTimeException` if the file does not exist or an error occurs. From the original docblock my expectation was that the functions would return `false` on an error (e.g. file does not exist), but the called `SplFileInfo::getSize()` throws a runtime error if the file does not exist.
From [the PHP docs](https://www.php.net/manual/en/splfileinfo.getsize.php)
> The filesize in bytes on success, or [false](https://www.php.net/manual/en/reserved.constants.php#constant.false) on failure.
> A RuntimeException will be thrown if the file does not exist or an error occurs.
From the PHP docs it is not quite clear to me when to expect an exception and when to expect `false`.
If return of `false` on any error is desired, I am happy …
> docs: [File Instance] RunTimeException if file does not exist

- system/Throttle/Throttler.php
Fix for PHPStan v1.11.8
```
------ ------------------------------------------------------------------------------------------------------- 
Line   system/Throttle/Throttler.php                                                                          
------ ------------------------------------------------------------------------------------------------------- 
:126   Binary operation "+=" between array|bool|float|int|object|string and (float|int) results in an error.  
🪪  assignOp.invalid                                                                                   
✏️  system/Throttle/Throttler.php:126                                                                  
------ ------------------------------------------------------------------------------------------------ …
```
> refactor: fix `Throttler::check()` $tokens

- .github/workflows/test-phpstan.yml
- composer.json
- Add composer scripts for phpstan
- The `--verbose` flag adds identifiers to errors reported
Why `:` instead of `-` in the names? Because Composer uses Symfony Console, and the latter groups commands with `:` in their names. So, running `composer` in the terminal will give:
**Checklist:**
> chore: add composer scripts for phpstan

- system/Router/RouteCollection.php
- tests/system/Router/RouteCollectionTest.php
- user_guide_src/source/changelogs/v4.5.4.rst
- user_guide_src/source/incoming/routing.rst
Fixes #9063
```php
$routes->group('', ['filter' => ['csrf']], static function ($routes) {
$routes->get('getuserinfo', 'Mmeber::getUserInfo', ['filter' => ['honeypot']]);
});
```
Before:
```
+--------+-------------+------+--------------------------------------+----------------+---------------+
| Method | Route       | Name | Handler                              | Before Filters | After Filters |
+--------+-------------+------+--------------------------------------+----------------+---------------+
| GET    | getuserinfo | »    | \App\Controllers\Mmeber::getUserInfo | honeypot       | honeypot      |
+--------+-------------+------+--------------------------------------+----------------+---------------+
```
After:
``` …
```
> fix: filters passed to the ``$routes->group()`` are not merged into the filters passed to the inner routes

- CHANGELOG.md
- phpdoc.dist.xml
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.5.4.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_454.rst
Updates changelog and version references for 4.5.4.
Previous version: #8996
**Checklist:**
> Prep for 4.5.4 release

- tests/system/CodeIgniterTest.php
> Error: tests/system/CodeIgniterTest.php:138:33: UndefinedClass: Class, interface or enum named Tests\Support\Errors does not exist (see https://psalm.dev/019)
https://github.com/codeigniter4/CodeIgniter4/actions/runs/10103403558/job/27940714508
**Checklist:**
> test: suppress psalm error

- admin/framework/composer.json
- composer.json
- tests/system/Autoloader/AutoloaderTest.php
- tests/system/CodeIgniterTest.php
- tests/system/Commands/GenerateKeyTest.php
- tests/system/CommonFunctionsSendTest.php
- tests/system/CommonFunctionsTest.php
- tests/system/Config/BaseConfigTest.php
- tests/system/Config/DotEnvTest.php
- tests/system/Config/ServicesTest.php
- tests/system/Events/EventsTest.php
- tests/system/Filters/HoneypotTest.php
- tests/system/HTTP/ContentSecurityPolicyTest.php
- tests/system/HTTP/DownloadResponseTest.php
- tests/system/HTTP/IncomingRequestTest.php
- tests/system/HTTP/RedirectResponseTest.php
- tests/system/HTTP/ResponseSendTest.php
- tests/system/Helpers/FormHelperTest.php
- tests/system/Helpers/URLHelper/MiscUrlTest.php
- tests/system/RESTful/ResourceControllerTest.php
- tests/system/RESTful/ResourcePresenterTest.php
- tests/system/Security/SecurityCSRFSessionRandomizeTokenTest.php
- tests/system/Security/SecurityCSRFSessionTest.php
- tests/system/Session/SessionTest.php
- tests/system/Test/ControllerTestTraitTest.php
- tests/system/Test/TestCaseEmissionsTest.php
- tests/system/View/ParserPluginTest.php
Update phpunit to `^10.5.16 || ^11.2`
**Checklist:**
> chore: Update phpunit to `^10.5.16 || ^11.2`

- system/Config/BaseConfig.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/installation/upgrade_460.rst
- user_guide_src/source/installation/upgrade_460/001.php
See #9069
Any Registrar class should be a class that simply returns an array without side effects.
If a Registrar file instantiates any Config class, it runs Auto-Discovery again during Auto-Discovery, and duplicate runs are not expected.
This PR checks for duplicate Registrar Auto-Discovery runs, and throws Exception.
```php
<?php
namespace Config;
class Registrar
{
public static function hack(): void
{
$config = config('Cache');
// Does something.
}
}
Registrar::hack(); // Bad. When this class is loaded, Config\Cache will be instantiated.
```
```console
$ ./spark config:check App
PHP Fatal error:  Uncaught CodeIgniter\Exceptions\ConfigException: During Auto-Discovery of Registrars, "Config\Cache" executes Auto-Discovery again. …
```
> fix: add check for duplicate Registrar Auto-Discovery runs

- .github/workflows/test-phpcpd.yml
It seems that **phpcpd**  was not setuped correctly. I couldn't figure out why.
https://github.com/codeigniter4/CodeIgniter4/actions/runs/10152748314/job/28077826735?pr=9085
```console
Run shivammathur/setup-php@v2
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh
==> Setup PHP
✓ PHP Updated to PHP 8.1.29
==> Setup Extensions
✓ dom Enabled
✓ mbstring Enabled
==> Setup Tools
✓ composer Added composer 2.[7](https://github.com/codeigniter4/CodeIgniter4/actions/runs/10166194607/job/28115790693?pr=9090#step:3:8).7
✗ phpcpd Could not setup phpcpd
==> Sponsor setup-php
✓ setup-php https://setup-php.com/sponsor
0s
Run phpcpd --exclude system/Test --exclude system/ThirdParty --exclude system/Database/SQLSRV/Builder.php --exclude …
```
> chore: use codeigniter4/.github/.github/ for phpcpd

- system/DataCaster/Cast/DatetimeCast.php
- system/I18n/TimeTrait.php
- tests/system/DataConverter/DataConverterTest.php
- tests/system/I18n/TimeTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/installation/upgrade_460.rst
- user_guide_src/source/installation/upgrade_460/002.php
- user_guide_src/source/installation/upgrade_460/003.php
- user_guide_src/source/installation/upgrade_460/004.php
- user_guide_src/source/installation/upgrade_460/005.php
- user_guide_src/source/installation/upgrade_460/006.php
- user_guide_src/source/installation/upgrade_460/007.php
- user_guide_src/source/models/model.rst
- user_guide_src/source/models/model/063.php
Fixes #9079
Since PHP 7.1, DateTime constructor incorporates microseconds.
See https://www.php.net/manual/en/migration71.incompatible.php#migration71.incompatible.datetime-microseconds
and `Time` constructor also holds microseconds in most cases.
But some methods below in `Time` lost microseconds.
- `__construct()` ... not all cases
- `createFromFormat()`
- `createFromInstance()`
- `toDateTime()`
- `setTestNow()`
- `equals()`
- `sameAs()`
- `isBefore()`
- `isAfter()`
Also fixes:
- `DatetimeCast::set()`
**Checklist:**
> fix: Time loses microseconds

- user_guide_src/source/installation/upgrade_models.rst
- user_guide_src/source/installation/upgrade_models/002.php
- user_guide_src/source/installation/upgrade_models/ci3sample/001.php
- The current CI4 sample code <https://codeigniter.com/user_guide/installation/upgrade_models.html#code-example> does not work because the `insert()` method parameters are different.
- `public function insert($name, $address, $email)`  cannot be defined in CI4 model because it is  already defined.
**Checklist:**
> docs: improve Upgrade Models sample code

- phpstan-baseline.php
- system/Commands/Database/ShowTableInfo.php
- system/Database/BaseBuilder.php
- system/Database/BaseConnection.php
- system/Database/MySQLi/Connection.php
- system/Database/OCI8/Connection.php
- system/Database/Postgre/Connection.php
- system/Database/SQLSRV/Connection.php
- system/Database/SQLite3/Connection.php
- system/Database/TableName.php
- system/Test/Mock/MockConnection.php
- tests/system/Database/Builder/AliasTest.php
- tests/system/Database/TableNameTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
Superesedes #8696
Fixes #6765
- add `TableName` class
- fix `spark db:table` causes errors with table name including special chars
```console
$ ./spark db:table
CodeIgniter v4.5.1 Command Line Tool - Server Time: 2024-05-02 02:19:47 UTC+00:00
+-----------+----------+----------+----------+----------+------+
| hostname  | database | username | DBDriver | DBPrefix | port |
+-----------+----------+----------+----------+----------+------+
| localhost | ci4      | root     | MySQLi   |          | 3306 |
+-----------+----------+----------+----------+----------+------+
[0]  , CONCAT('',`password`) AS `email`
[1]  migrations
Which table do you want to see? [0, 1]: 0
Data of Table ", CONCAT('',`password`) AS `email`":
+----+------+
| id | …
```
> feat: fix spark db:table causes errors with table name including special chars

- system/Helpers/text_helper.php
- tests/system/Helpers/TextHelperTest.php
- user_guide_src/source/helpers/text_helper.rst
- user_guide_src/source/helpers/text_helper/009.php
- user_guide_src/source/helpers/text_helper/010.php
- refactor to suppress PHPStan error (false positive)
- fix user guide
- refactor test code
```
------ ------------------------------------------------------------------- 
Line   system/Helpers/text_helper.php                                     
------ ------------------------------------------------------------------- 
529    Regex pattern is invalid: Compilation failed: quantifier does not  
follow a repeatable item at offset 5 in pattern: #.*{2,}#          
🪪  regexp.pattern                                                 
------ ------------------------------------------------------------------- 
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/10208178324/job/28244217081
But the pattern  is `#,{2,}#` by default: …
> refactor: reduce_multiples() and fix user guide

- user_guide_src/source/libraries/curlrequest.rst
- user_guide_src/source/libraries/curlrequest/028.php
- improve readability
**Checklist:**
> docs: improve CURLRequest sample code

- phpstan-baseline.php
- system/BaseModel.php
See #8732
- fix PHPDoc type
**Checklist:**
> docs: fix `@return` type in BaseModel

- phpstan-baseline.php
- system/HTTP/ContentSecurityPolicy.php
- tests/system/HTTP/ContentSecurityPolicyTest.php
> docs: update PHPDoc in ContentSecurityPolicy

- phpstan-baseline.php
- tests/system/ControllerTest.php
> test: add tests for `validateData()` with custom error messages

- system/Validation/StrictRules/Rules.php
- tests/system/Validation/RulesTest.php
> fix: Validation rule `differs`/`matches` with dot array

- system/Commands/Database/ShowTableInfo.php
- system/Database/TableName.php
- tests/system/Database/Builder/AliasTest.php
- tests/system/Database/TableNameTest.php
Follow-up #8748
`TableName` should not depend on DB Connection.
Because it may be a table name in another database. See #9085
**Checklist:**
> refactor: remove dependency on BaseConnection in TableName

- phpstan-baseline.php
- system/Entity/Entity.php
- tests/system/Entity/EntityTest.php
See #7731, #8732
- add type definitions
- fix incorrect test code
**Checklist:**
> test: fix EntityTest PHPStan errors

- user_guide_src/source/changelogs/v4.1.2.rst
- user_guide_src/source/outgoing/api_responses/002.php
> docs: replace deprecated failValidationError()

- system/Filters/CSRF.php
- system/Security/Security.php
- update comments
**Checklist:**
> docs: update comments for CSRF

- phpstan-baseline.php
- system/Common.php
- tests/system/Language/LanguageTest.php
- user_guide_src/source/outgoing/localization.rst
- user_guide_src/source/outgoing/localization/020.php
- user_guide_src/source/outgoing/localization/021.php
- some improvements
- add tests for the current behavior
- refactor test
See #7960
**Checklist:**
> docs: improve Localization

- system/Commands/Utilities/PhpIniCheck.php
- system/Security/CheckPhpIni.php
- add directives to `phpini:check`
- max_execution_time
- max_input_vars
- zend.assertions
```
+-------------------------+---------+---------+-------------+-----------------------+
| Directive               | Global  | Current | Recommended | Remark                |
+-------------------------+---------+---------+-------------+-----------------------+
| error_reporting         | 32767   | 32767   | 5111        |                       |
| display_errors          | 1       | 1       | 0           |                       |
| display_startup_errors  | 1       | 1       | 0           |                       |
| log_errors              | 1       | 1       |             |                       |
| error_log               |         |         |             |                       | …
```
> feat: add directives to `phpini:check` command

- phpstan-baseline.php
- system/DataCaster/Cast/TimestampCast.php
- system/Entity/Cast/DatetimeCast.php
- system/I18n/Time.php
- system/I18n/TimeLegacy.php
- system/I18n/TimeTrait.php
- tests/system/DataConverter/DataConverterTest.php
- tests/system/Entity/EntityTest.php
- tests/system/I18n/TimeTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/installation/upgrade_460.rst
- user_guide_src/source/libraries/time.rst
- user_guide_src/source/models/model.rst
~~Needs  #9107~~
Follow-up #8544
- `Time::createFromTimestamp()` (without timezone specified) should return `Time` with the timezone UTC, because `DateTime(Immutable)::createFromTimestamp()` in PHP 8.4 returns an instance with the timezone `+00:00`.
- update the method signature for PHP 8.4.
- replace`self` with `static`.
PHP 8.4 introduces new `DateTime(Immutable)::createFromTimestamp()` method.
https://php.watch/versions/8.4/datetime-createFromTimestamp
```console
bash-3.2$ php -v
PHP 8.4.0-dev (cli) (built: Aug  5 2024 00:57:29) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.4.0-dev, Copyright (c) Zend Technologies
with Zend OPcache v8.4.0-dev, Copyright (c), by Zend Technologies
```
```console
bash-3.2$ php -a
Interactive shell
php > $d = …
```
> fix: Time::createFromTimestamp() change for PHP 8.4

- system/I18n/TimeLegacy.php
- system/I18n/TimeTrait.php
- tests/system/I18n/TimeTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/installation/upgrade_460.rst
- user_guide_src/source/installation/upgrade_460/008.php
- user_guide_src/source/installation/upgrade_460/009.php
- user_guide_src/source/libraries/time.rst
- user_guide_src/source/libraries/time/030.php
Follow-up #9105
- fix Time::setTimestamp() behavior.
**Checklist:**
> fix: Time::setTimestamp()'s different behavior than DateTime

- user_guide_src/source/models/model.rst
Closes #9124
See #8306
- update descriptions for `beforeUpdate/afterUpdate` `id` 
**Checklist:**
> docs: make Model Event Parameters description more precise

- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/incoming/routing/071.php
- user_guide_src/source/incoming/routing/072.php
I was unable to find clear documentation on how to retrieve the controller and method names for the current route in CodeIgniter 4. After searching through the user guide without success, I had to read the source code to figure out the correct approach. While I'm not entirely sure if this has been documented elsewhere, I believe this addition will be helpful for developers who need to dynamically interact with the controller or method handling the current request.
- Retrieving the Controller and Method Names
- Accessing Active Filters in Router
**Checklist:**
> docs: add Getting Routing Information

- user_guide_src/source/changelogs/v4.6.0.rst
> docs: fix typo in changelog v4.6.0

- utils/composer.json
```diff
PHP CS Fixer 3.63.1 7th Gear by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.1.29
Running analysis on 4 cores with 10 files per process.
Parallel runner is an experimental feature and may be unstable, use it at your own risk. Feedback highly appreciated!
Loaded config CodeIgniter4 Coding Standards from ".php-cs-fixer.user-guide.php".
0/1593 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%  160/1593 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]  10%  319/1593 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  20%  478/1593 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  30%  638/1593 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  40%  797/1593 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  50%  956/1593 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░]  60% 1116/1593 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░]  70% 1275/1593 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░]  80% …
```
> chore: workaround for php-cs-fixer 3.63

- phpstan-baseline.php
- system/Validation/Validation.php
- tests/system/Validation/ValidationTest.php
See https://forum.codeigniter.com/showthread.php?tid=91483
**Checklist:**
> fix: [Validation] TypeError when using numeric field names

- phpstan-baseline.php
- rector.php
- system/Database/BaseBuilder.php
- system/Database/Postgre/Builder.php
- tests/system/API/ResponseTraitTest.php
- tests/system/Router/AutoRouterImprovedTest.php
- tests/system/Test/BootstrapFCPATHTest.php
Change private method param type to strict type, based on passed strict types via `AddMethodCallBasedStrictParamTypeRector`
**Checklist:**
> refactor: enable AddMethodCallBasedStrictParamTypeRector

- user_guide_src/source/intro/requirements.rst
> [4.6] docs: add note about PHP versions supported by CI4 versions

- .github/workflows/reusable-phpunit-test.yml
- .github/workflows/test-phpunit.yml
- composer.json
Supersedes #9133
See #9116
- add PHP 8.4 to test-phpunit.yml
- add `--ignore-platform-req=php` temporarily to `@composer update --working-dir=utils`
**Checklist:**
> [4.6] chore: add PHP 8.4 to test-phpunit.yml

- utils/composer.json
Closes #9154
Follow-up #9152
```console
$ composer cs-fix
> Composer\Config::disableProcessTimeout
> utils/vendor/bin/php-cs-fixer fix --ansi --verbose --diff --config=.php-cs-fixer.user-guide.php
PHP CS Fixer 3.63.2 7th Gear by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.2.20
Running analysis on 4 cores with 10 files per process.
Parallel runner is an experimental feature and may be unstable, use it at your own risk. Feedback highly appreciated!
Loaded config CodeIgniter4 Coding Standards from ".php-cs-fixer.user-guide.php".
Using cache file "build/.php-cs-fixer.user-guide.cache".
1593/1593 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
Fixed 0 of 1593 files in 2.020 seconds, 20.00 MB memory used
> utils/vendor/bin/php-cs-fixer fix --ansi --verbose --diff …
```
> chore: update php-cs-fixer to ^3.63.2

- system/Debug/ExceptionHandler.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/general/errors.rst
See https://github.com/codeigniter4/CodeIgniter4/issues/9120#issuecomment-2295905729
- fix the condition to show error details for non-HTML requests
**Checklist:**
> [4.6] fix: inconsistency in detailed error reporting

- system/Router/Router.php
> docs: fix doc comments for Router

- system/Router/RouteCollection.php
- tests/system/Router/RouteCollectionTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/incoming/routing/073.php
Supersedes #9031
Example
```php
$routes->group('api', ['hostname' =>  ['api.website.com', 'api.website.net]], function ($routes) {
$routes->get('/', 'Api::royplayer');
});
```
Thanks to @mrjk990
**Checklist:**
> feat: multiple hostname routing

- system/Database/Database.php
Supersedes #9051
See #9158
```console
$ php spark db:create report
CodeIgniter v4.5.4 Command Line Tool - Server Time: 2024-08-30 00:59:08 UTC+00:00
[CodeIgniter\Exceptions\CriticalError]
The required PHP extension "sqlsrv" is not loaded. Install and enable it to use "SQLSRV" driver.
at SYSTEMPATH/Database/Database.php:177
...
```
**Checklist:**
> refactor: improve error message for missing PHP DB extensions

- system/Debug/Exceptions.php
- system/Session/Handlers/FileHandler.php
- system/Session/Session.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/installation/upgrade_460.rst
Supersedes #9135
See #9116 and https://github.com/codeigniter4/CodeIgniter4/issues/9116#issuecomment-2300918329
These INI settings have been deprecated in PHP 8.4. 
This PR enforces the behavior in PHP 9.
**Checklist:**
> [4.6] feat: force PHP default 32 chars length at 4 bits to Session ID

- system/Helpers/html_helper.php
- update PHPDoc
**Checklist:**
> docs: update PHPDoc in html_helper

- user_guide_src/source/helpers/html_helper.rst
Fix some typos in helpers/html_helper.rst
**Checklist:**
> docs: Fix some typos in helpers/html_helper.rst

- system/Debug/Exceptions.php
~~Needs  #9139~~
See #9116
- add workaround for the error like the following.
> ErrorException: Kint\Parser\Parser::__construct(): Implicitly marking parameter $caller as nullable is deprecated, the explicit nullable type must be used instead
**Checklist:**
> [4.6] feat: workaround for implicit nullable deprecations in PHP 8.4

- user_guide_src/source/helpers/html_helper.rst
Fix track function definition in helpers/html_helper.rst
**Checklist:**
> docs: Fix track function definition in helpers/html_helper.rst

- system/Helpers/url_helper.php
- tests/system/Helpers/URLHelper/MiscUrlTest.php
- user_guide_src/source/changelogs/v4.5.5.rst
Fixes #9165
Supersedes  #9167
- update `auto_link()` regexp to use the [latest CI3 code](https://github.com/bcit-ci/CodeIgniter/blob/2042929bab8ffc14faf6193de0107b7f95abbdaf/system/helpers/url_helper.php#L397)
**Checklist:**
> fix: `auto_link()` regexp

- CHANGELOG.md
- phpdoc.dist.xml
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.5.5.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_455.rst
Updates changelog and version references for 4.5.5.
Previous version: #9082
**Checklist:**
> Prep for 4.5.5 release

- user_guide_src/source/helpers/url_helper.rst
- fix parameter types
- decorate text
**Checklist:**
> docs: improve url_helper.rst

- user_guide_src/source/dbmgmt/migration.rst
See #9177
- improve the description for "Migration File Names"
**Checklist:**
> docs: improve "Migration File Names"

- rector.php
- system/Config/Factories.php
To make private property typed by assign.
**Checklist:**
> refactor: enable TypedPropertyFromAssignsRector

- system/HTTP/CURLRequest.php
- tests/system/HTTP/CURLRequestTest.php
PHP 8.4 coming soon, see #9116
Reference:
- php/php-src#15350
- https://gist.github.com/bagder/a88d3bedc8ecb69d19aeb542fa538e9b
- https://php.watch/articles/php-curl-http3
**Checklist:**
> feat: support CURL HTTP3

- system/Helpers/url_helper.php
- tests/system/Helpers/URLHelper/MiscUrlTest.php
See https://github.com/codeigniter4/CodeIgniter4/issues/9165#issuecomment-2333630422
- fix a bug that `auto_link()` converts invalid strings without a scheme like `://codeigniter.com`
> scheme      = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )
https://datatracker.ietf.org/doc/html/rfc3986#section-3.1
**Checklist:**
> fix: auto_link() converts invalid strings like `://codeigniter.com`

- system/Commands/Utilities/FilterCheck.php
Fix return type
```console
> vendor/bin/rector process --dry-run
2/2 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
1 file with changes
===================
1) system/Commands/Utilities/FilterCheck.php:166
@@ @@
*/
private function colorItems(array $array): array
{
-        return array_map(function ($item) {
+        return array_map(function ($item): array|string {
if (is_array($item)) {
return $this->colorItems($item);
}
Applied rules:
* ClosureReturnTypeRector
```
> refactor: return type to closuer in FilterCheck

- system/Router/RouteCollection.php
This PR optimizes the getMethodParams method by removing the unnecessary `is_countable()` check.
The `preg_match_all()` function guarantees that `$matches` will always be an array.
If no matches are found, `$matches[0]` will be an empty array, and the function will return 0.
See : https://github.com/codeigniter4/CodeIgniter4/actions/runs/11033764630/job/30645688529?pr=9202
```console
------ --------------------------------------------------------------------- 
Line   system/Router/RouteCollection.php                                    
------ --------------------------------------------------------------------- 
1614   Call to function is_countable() with array<int, string> will always  
evaluate to true.                                                    
🪪 …
```
> refactor: remove unnecessary `is_countable()` check in `getMethodParams()`

- system/Encryption/Handlers/SodiumHandler.php
While I recognize that this change might be seen as a BC, it appears that it will not significantly impact many users. The improved validation of the starter key in the SodiumHandler class primarily focuses on enhancing error handling and preventing potential issues related to an empty key, which should lead to a more robust encryption process.
See : https://github.com/codeigniter4/CodeIgniter4/actions/runs/11033764630/job/30645688529?pr=9202
```console
------ ----------------------------------------------------------------------- 
Line   system/Encryption/Handlers/SodiumHandler.php                           
------ ----------------------------------------------------------------------- 
66     Property CodeIgniter\Encryption\Handlers\SodiumHandler::$key (string)  
does …
```
> refactor: starter key handling in SodiumHandler

- system/Session/Session.php
- user_guide_src/source/changelogs/v4.5.6.rst
The session class clutters out-of-the-box configured logs with debug information about its driver initialization on startup, using a `INFO` classification.
This is especially problematic in authenticated webapps as every request will write at least one info message. 
The message itself has a debug purpose and therefore should be classified as `DEBUG`
**Checklist:**
> fix: change session start log level

- rector.php
- tests/system/Database/Live/UpdateTest.php
We can enable `codeQuality` sets once we are on max level. This PR apply level one by one, and I can see it apply on level 9, with cleared rules manual definitions that included in previous level.
**Checklist:**
> refactor: enable Rector Code Quality level, apply level 9 for SimplifyConditionsRector

- .github/workflows/deploy-distributables.yml
- .github/workflows/deploy-userguide-latest.yml
- .github/workflows/test-userguide.yml
This PR pins the Python version to `3.12`. Recently, we are not able to build the user guide correctly. This is because the `imghdr` module was removed in Python `3.13`.
```
Running Sphinx v5.3.0
Extension error:
Could not import extension sphinx.builders.epub3 (exception: No module named 'imghdr')
make: *** [Makefile:20: html] Error 2
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/11307496056/job/31449280998?pr=9221
More information about removing the `imghdr` module:
https://github.com/sphinx-doc/sphinx/issues/10440
Since for some reason we are blocked on Sphinx v5 (I'm guessing because of some extensions?), pinning the Python version is the only option.
**Checklist:**
> fix: pin python version for sphinx

- system/Validation/DotArrayFilter.php
- tests/system/Validation/ValidationTest.php
- user_guide_src/source/changelogs/v4.5.6.rst
> fix: `getValidated()` when validation multiple asterisk

- system/Session/Handlers/DatabaseHandler.php
While making changes to [#9928](https://github.com/codeigniter4/CodeIgniter4/pull/9228) noticed there were two variables prior to the return statement which add horizontal space padding around $max_lifetime. These statements are unnecessary and do not enhance code readability.
**Checklist:**
> refactor: cleanup `DatabaseHandler::gc()` for session

- system/View/Parser.php
- tests/system/View/ParserTest.php
- user_guide_src/source/changelogs/v4.5.6.rst
Fixes the conflict when replacing View Parser {variables} in the provided data with the same key name, even when on different levels.
This fix focus on ```parse()``` method, in which the return of ```parsePair``` and ```parseSingle``` methods are stored independently , then merged together (Pairs with Single), and finally replaced. With this approach, the replacement happens from the Pairs to Single and the output is as expected.
More details and examples in issue #9245 
Fixes #9245 
**Checklist:**
> fix: Parser - Equal key name replace conflict

- .github/workflows/reusable-phpunit-test.yml
- system/Database/BaseBuilder.php
- system/Database/SQLSRV/Forge.php
- tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
- tests/_support/Database/Seeds/CITestSeeder.php
- tests/system/Database/Live/ForgeTest.php
- tests/system/Database/Live/GetTest.php
- tests/system/Database/Live/LikeTest.php
- user_guide_src/source/changelogs/v4.5.6.rst
This PR fixes the case insensitivity option in the `like()` method when we deal with accented characters.
Closes #9236
**Checklist:**
> fix: case-insensitivity in the `like()` method when in use with accented characters

- system/Router/Router.php
- tests/system/Router/RouterTest.php
- user_guide_src/source/changelogs/v4.5.6.rst
This pull request addresses a `TypeError` that occurs in CodeIgniter 4 when the `translateURIDashes` property is set to `true` in the `Routes.php` configuration file and an `OPTIONS` route is defined using a closure. The error message indicates that the `str_replace()` function receives a `Closure` instead of the expected `string` or `array`.
**Related Issue:**
Fixes #9208 
**Checklist:**
> fix: TypeError for routes when translateURIDashes is enabled

- rector.php
- system/CodeIgniter.php
- system/Common.php
- system/Database/BaseConnection.php
- system/Database/Migration.php
- system/Database/Seeder.php
- system/HTTP/DownloadResponse.php
- system/HTTP/Exceptions/RedirectException.php
- system/HTTP/Negotiate.php
- system/HTTP/SiteURI.php
- system/Log/Handlers/ChromeLoggerHandler.php
- system/Validation/FileRules.php
- tests/system/API/ResponseTraitTest.php
- utils/src/Rector/UnderscoreToCamelCaseVariableNameRector.php
enable FlipTypeControlToUseExclusiveTypeRector to flip type control from null compare to use exclusive instanceof object for more verbose check.
**Checklist:**
> refactor: enable FlipTypeControlToUseExclusiveTypeRector

- phpstan-baseline.php
- tests/system/CLI/ConsoleTest.php
- tests/system/Cache/Handlers/MemcachedHandlerTest.php
- tests/system/CodeIgniterTest.php
- tests/system/Config/DotEnvTest.php
- tests/system/ControllerTest.php
- tests/system/Files/FileWithVfsTest.php
- tests/system/HTTP/Files/FileMovingTest.php
- tests/system/Helpers/CookieHelperTest.php
- tests/system/Images/BaseHandlerTest.php
- tests/system/Images/ImageTest.php
- tests/system/Log/Handlers/FileHandlerTest.php
- tests/system/Publisher/PublisherOutputTest.php
- tests/system/View/CellTest.php
Use local variable when only used on `setUp()` method.
**Checklist:**
> refactor: Move property to local variable on usage only in setUp() method in tests

- tests/system/Database/Live/ForgeTest.php
- tests/system/Database/Live/OCI8/CallStoredProcedureTest.php
- tests/system/Database/Live/OCI8/LastInsertIDTest.php
- tests/system/Files/FileCollectionTest.php
- tests/system/HTTP/ResponseCookieTest.php
- tests/system/Helpers/DateHelperTest.php
- tests/system/Helpers/TextHelperTest.php
- tests/system/Models/EventsModelTest.php
- tests/system/Models/ValidationModelRuleGroupTest.php
- tests/system/Models/ValidationModelTest.php
- tests/system/Pager/PagerTest.php
- tests/system/Router/RouteCollectionTest.php
- tests/system/Router/RouterTest.php
the actual value should be on the right.
**Checklist:**
> refactor: flip assert and actual value position on tests

- phpstan-baseline.php
- system/Database/Forge.php
The usage of `keys` property is as array, eg: `count($this->key)` so compare with empty array is fine, other check also compare with empty array.
**Checklist:**
> refactor: use compare empty array on Forge on keys property

- rector.php
- tests/system/Database/Live/OCI8/GetFieldDataTestCase.php
- tests/system/Database/RawSqlTest.php
Applied `SimplifyRegexPatternRector` to simplify regex pattern to known ranges
**Checklist:**
> refactor: Apply code quality level 24 for Rector

- system/HTTP/RequestTrait.php
- tests/system/HTTP/RequestTest.php
- tests/system/Test/FeatureTestTraitTest.php
- user_guide_src/source/changelogs/v4.5.6.rst
Closes  #9204, #9211
Before that, the method could not get a value if the POST, GET... data is stored as a list.
This affected FeatureTestTrait
> I think there is a potential error in fetchGlobal() - it does not understand the numeric keys $_GET[0]['one'] = 1
**Checklist:**
> fix: `fetchGlobal()` with numeric key

- system/HTTP/URI.php
> fix: curl request crashes with params that give an int once hexed.

- phpstan-baseline.php
- system/BaseModel.php
> docs: allow boolean values in the model for PHPStan

- phpstan-baseline.php
- system/Autoloader/Autoloader.php
- system/Autoloader/FileLocator.php
- system/Autoloader/FileLocatorCached.php
- system/Autoloader/FileLocatorInterface.php
- system/Common.php
- system/Config/Factories.php
- system/Test/ReflectionHelper.php
- tests/system/Autoloader/AutoloaderTest.php
- tests/system/Autoloader/FileLocatorCachedTest.php
- tests/system/Autoloader/FileLocatorTest.php
- tests/system/View/DecoratorsTest.php
- tests/system/View/ParserFilterTest.php
- tests/system/View/ParserTest.php
- tests/system/View/ViewTest.php
I cleaned up the errors from **phpstan-baseline.php** . There are several changes + phpdoc update
**Checklist:**
> refactor: Fix `phpstan` errors related to `Autoloader`

- system/Validation/Validation.php
- tests/system/Validation/ValidationTest.php
- user_guide_src/source/changelogs/v4.5.6.rst
This PR fixes a bug where complex language strings in the validation class are not handled properly.
The problem was that in the validation class, we were forming the final message using the `str_replace()` function, instead of using the built-in solutions that `MessageFormatter::formatMessage` gives us. 
**Checklist:**
> fix: respect complex language strings when using validation

- phpstan-baseline.php
- system/Exceptions/DownloadException.php
- system/HTTP/DownloadResponse.php
- tests/system/HTTP/DownloadResponseTest.php
- user_guide_src/source/changelogs/v4.5.6.rst
This PR fixes a bug when we cannot update the `Cache-Control` header for a `DownloadResponse` class.
By default, the cache is disabled by calling the `noCache()` method in the constructor of the parent class. But now we are able to override these settings simply by using the `setHeader()` or `setCache()` methods.
I don't know why previously it was decided that `setCache()` would throw an exception since setting the cache should be possible. In many cases, we probably don't want to do that, but still... it should be possible.
Last but not least, the header `Expire-Disposition` (this is the first time I have seen it) was removed since I don't think it's a valid one and has no effect.
Ref: #9234
**Checklist:**
> fix: `DownloadResponse` cache headers

- system/Commands/Utilities/Routes/FilterCollector.php
- system/Validation/StrictRules/FileRules.php
- tests/system/Database/Live/MySQLi/FoundRowsTest.php
- tests/system/Router/RouteCollectionTest.php
- tests/system/View/ViewTest.php
This PR fixes code issues for CS and Rector.
**Checklist:**
> fix: code issues after merging develop

- system/HTTP/ResponseInterface.php
The function setJSON also accepts objects, as is already implemented in the ResponseTrait.php (lines 166 to 178), thus use the same types (array|object|string) for the interface, only "object" was missing.
**Checklist:**
> fix: `ResponseInterface::setJSON()` also accepts objects

- system/HTTP/CURLRequest.php
- tests/system/HTTP/CURLRequestTest.php
- user_guide_src/source/changelogs/v4.5.6.rst
> fix: [CURLRequest] body contains "HTTP/1.0 200 Connection established"

- user_guide_src/source/libraries/pagination.rst
Small typos in libraries/pagination.rst
**Checklist:**
> docs: Small typos in libraries/pagination.rst

- system/Database/Postgre/Connection.php
- user_guide_src/source/changelogs/v4.5.6.rst
> fix: `Postgre\Connection::reconnect()` `TypeError` in `pg_ping()`

- phpstan-baseline.php
- tests/system/Commands/Utilities/ConfigCheckTest.php
Needed for #9289 
**Checklist:**
> test: refactor `ConfigCheckTest`

- system/Config/Services.php
- system/HTTP/ContentSecurityPolicy.php
- tests/system/HTTP/CURLRequestShareOptionsTest.php
- tests/system/HTTP/CURLRequestTest.php
Fixes #9265 
Replaces and closes #9280 
**Checklist:**
> refactor: use `baseURI` instead of `base_uri`

- system/Validation/Rules.php
- system/Validation/StrictRules/Rules.php
- tests/system/Validation/StrictRules/DatabaseRelatedRulesTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/libraries/validation.rst
> feat: [Validation] add support for `$dbGroup` as parameter in `is_unique` and `is_not_unique`

- system/Commands/Utilities/Publish.php
- system/Language/en/Publisher.php
- system/Publisher/Publisher.php
- tests/system/Publisher/PublisherSupportTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/libraries/publisher.rst
- user_guide_src/source/libraries/publisher/016.php
This option allows you to run only Publishers of a specific namespace
The `namespace` option is used to define the namespace from which to search for publishers. This not only limits the files to be scanned but also prevents a publisher from being reexecuted.
If a library has misconfigured its publisher, reexecution may result in a file being replaced, for example a configuration file of library.
**Checklist:**
> feat: added the `namespace` option to the `publish` command

- user_guide_src/source/tutorial/create_news_items/001.php
Resolved a fatal error:
Type of Config\Filters::$methods must be array (as in class CodeIgniter\Config\Filters)
by explicitly declaring $methods as an array to ensure compatibility with strict typing.
**Checklist:**
> refactor: explicitly declare $methods property as array in Filters configuration

- user_guide_src/source/helpers/html_helper.rst
Fix $indexPage parameter explanations in helpers/html_helper.rst
**Checklist:**
> docs: Fix $indexPage param explanations in helpers/html_helper.rst

- system/Files/File.php
- system/Files/FileSizeUnit.php
- tests/system/Files/FileTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/libraries/files.rst
- user_guide_src/source/libraries/files/017.php
- user_guide_src/source/libraries/files/018.php
**Notice** 
This originated from another PR: https://github.com/codeigniter4/CodeIgniter4/pull/9271
Noticed that the file size calculation mixes up the SI unit prefixes with the NIST/IEC unit prefixes, by taking "kb" and "mb" but calculating "kib" and "mib". 
Fixed by providing both possibilities. 
This therefore will break existing code!
**Checklist:**
> feat: Differentiate between kilobyte/kibibyte and megabyte/mebibyte

- user_guide_src/source/incoming/filters.rst
This PR fixes a note in the user guide about required filters.
Fixes: #9292
**Checklist:**
> docs: update note about required filters

- phpstan-baseline.php
- system/BaseModel.php
- system/Database/BaseBuilder.php
- system/Database/BaseConnection.php
- system/Model.php
- system/Router/RouteCollection.php
- system/Test/FilterTestTrait.php
- system/Validation/Validation.php
Fixed errors like
> ...with no signature specified for Closure
The types are too blurry - this is a working option at this stage.
Fixed **19** errors out of **3925**, **2** left
**Checklist:**
> refactor: fix `phpstan` signature for Closure

- phpstan-baseline.php
- system/Model.php
- tests/system/Models/SaveModelTest.php
- user_guide_src/source/changelogs/v4.5.6.rst
This PR fixes a bug that caused the `Model::getIdValue()` to not correctly recognize the primary key in the ``Entity`` object if a data mapping for the primary key was used.
Fixes: #9306
**Checklist:**
> fix: primary key mapping in the model for the entity

- user_guide_src/source/changelogs/v4.6.0.rst
This PR adds missing info about changes in handling exceptions for non-HTML responses.
See: #9308
**Checklist:**
> docs: add missing info about exceptions for non-HTML responses

- phpstan-baseline.php
- system/Database/MySQLi/Connection.php
- tests/system/Cache/FactoriesCacheFileHandlerTest.php
Fixing the easy fixes in the baseline.
**Checklist:**
> refactor: fix `phpDoc.parseError` errors

- phpstan-baseline.php
- system/Test/ControllerTestTrait.php
- tests/system/Database/Live/InsertTest.php
- tests/system/Database/Live/UpsertTest.php
- tests/system/Format/FormatTest.php
- tests/system/HTTP/Files/FileCollectionTest.php
- tests/system/Test/ControllerTestTraitTest.php
- tests/system/Validation/FormatRulesTest.php
- user_guide_src/source/testing/controllers.rst
- user_guide_src/source/testing/controllers/002.php
- user_guide_src/source/testing/controllers/009.php
Yes, we have these kind of errors in our baseline 🤷🏻‍♂️ 
**Checklist:**
> refactor: fix `method.nameCase` errors

- phpstan-baseline.php
- tests/system/Router/RouteCollectionTest.php
Last errors for `class.nameCase`
**Checklist:**
> refactor: rename `controller` to `Controller`

- phpstan-baseline.php
- system/Commands/Utilities/Routes/AutoRouterImproved/AutoRouteCollector.php
- system/Helpers/url_helper.php
- tests/system/DataConverter/DataConverterTest.php
Implicit arrays are prone to bugs.
**Checklist:**
> refactor: fix implicit array creation

- system/Boot.php
This PR adds a check that `WRITEPATH` is defined correctly.
Fixes: #9309
**Checklist:**
> fix: check if defined `WRITEPATH` exists

- composer.json
This PR upgrade to use PHPStan 2 and Rector 2.
**Checklist:**
> refactor: upgrade to use phpstan 2 and rector 2

- system/Cache/Handlers/FileHandler.php
- system/Database/BaseConnection.php
- system/Database/MySQLi/Connection.php
- system/Helpers/filesystem_helper.php
- system/Security/Security.php
- system/Security/SecurityInterface.php
> docs: phpdoc incorrect explanation regarding variable naming

- .github/workflows/reusable-phpunit-test.yml
- .github/workflows/test-coding-standards.yml
- .github/workflows/test-phpunit.yml
- .github/workflows/test-rector.yml
- admin/framework/composer.json
- composer.json
Review without `ignore-platform-php`, Reference to #9116 latest checklist.
**Checklist:**
> feat: full support on `PHP8.4`

- system/Database/Forge.php
- utils/phpstan-baseline/assign.propertyType.neon
- utils/phpstan-baseline/missingType.iterableValue.neon
Latest PHPStan changed the error message, so fixing this now.
**Checklist:**
> refactor: fix `Forge::processIndexes()` for empty `$this->fields`

- tests/system/Database/Live/ForgeTest.php
After all the tests, the database files remain. They should be deleted.
```console
$ tree -L 1  --dirsfirst
.
├── cache
├── debugbar
├── logs
├── session
├── uploads
├── database.db
├── index.html
└── test_com.sitedb.web
6 directories, 3 files
```
> test: remove DB files after tests

- system/BaseModel.php
- system/Test/ReflectionHelper.php
- system/Traits/PropertiesTrait.php
- tests/system/CLI/CLITest.php
Refer: https://wiki.php.net/rfc/make-reflection-setaccessible-no-op
**Checklist:**
> refactor: `Reflection*::setAccessible()` is now no-op in PHP 8.1

- rector.php
- system/CLI/Commands.php
- system/CodeIgniter.php
- system/Commands/Database/MigrateRollback.php
- system/Database/BaseBuilder.php
- system/Filters/CSRF.php
- system/Filters/Cors.php
- system/Filters/DebugToolbar.php
- system/Filters/FilterInterface.php
- system/Filters/ForceHTTPS.php
- system/Filters/Honeypot.php
- system/Filters/InvalidChars.php
- system/Filters/PageCache.php
- system/Filters/PerformanceMetrics.php
- system/Filters/SecureHeaders.php
- system/Images/Handlers/BaseHandler.php
- system/Language/Language.php
- system/Security/CheckPhpIni.php
- system/Session/Session.php
- system/Test/CIUnitTestCase.php
- tests/_support/Filters/Customfilter.php
- tests/_support/Filters/RedirectFilter.php
- tests/system/Filters/fixtures/GoogleCurious.php
- tests/system/Filters/fixtures/GoogleEmpty.php
- tests/system/Filters/fixtures/GoogleYou.php
- tests/system/Filters/fixtures/Multiple1.php
- tests/system/Filters/fixtures/Multiple2.php
- utils/phpstan-baseline/missingType.iterableValue.neon
- utils/phpstan-baseline/return.missing.neon
Applied `ExplicitReturnNullRector` to  add explicit return null to method/function that returns a value, but missed main return.
void in union should not happen.
**Checklist:**
> refactor: enable code quality level 34 for rector

- .php-cs-fixer.tests.php
- system/Database/BasePreparedQuery.php
- system/Database/MySQLi/PreparedQuery.php
- system/Database/OCI8/PreparedQuery.php
- system/Database/Postgre/Forge.php
- system/Database/Postgre/PreparedQuery.php
- system/Database/SQLSRV/Connection.php
- system/Database/SQLSRV/Forge.php
- system/Database/SQLSRV/PreparedQuery.php
- system/Database/SQLite3/PreparedQuery.php
- tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
- tests/system/Database/Live/AbstractGetFieldDataTestCase.php
- tests/system/Database/Live/Postgre/GetFieldDataTestCase.php
- tests/system/Database/Live/PreparedQueryTest.php
- tests/system/Database/Live/SQLSRV/GetFieldDataTestCase.php
- user_guide_src/source/changelogs/v4.5.6.rst
- user_guide_src/source/database/queries.rst
This PR fixes problems with handling binary data when working with Prepared Query.
I have not been able to test OCI8 even through the docker on my Mac, so we will see how it goes.
Fixes #9335
**Checklist:**
> fix: handling binary data for prepared statement

- system/HTTP/ResponseTrait.php
- tests/system/HTTP/ResponseSendTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/outgoing/response.rst
This PR changes the way headers are set. Now headers set by the `Response` class will be prioritized and will replace those set by calling the `header()` function.
Why is this important? Without this change, we cannot override the headers set previously with the `header()` function.
This is relevant, especially when we work with a session. By default, `session.cache_limiter` is set to `nocache`, which is fine for the default setting and will automatically set headers:
```
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
```
But we have no option to change these headers, even when we set different `Cache-Control` etc with the `Response` class. If we do so, we end up with two entries for `Cache-Control`, which will …
> fix: prioritize headers set by the `Response` class

- CHANGELOG.md
- phpdoc.dist.xml
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.5.6.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_456.rst
**Description:**
Updates changelog and version references for 4.5.6.
Previous version: #9173 
**Checklist:**
> Prep for 4.5.6 release

- system/Common.php
- tests/system/CommonHelperTest.php
Closes https://github.com/codeigniter4/CodeIgniter4/pull/9350
@yllumi this should handle https://github.com/codeigniter4/CodeIgniter4/pull/9350
**Checklist:**
> fix: handle namespaced helper found on Common helper

- system/Database/Forge.php
- system/Database/SQLite3/Forge.php
- tests/system/Database/Live/ForgeTest.php
- user_guide_src/source/changelogs/v4.5.7.rst
- utils/phpstan-baseline/missingType.iterableValue.neon
Fixes #8849 
Replaces and closes #8931
Changes are coming from the original PR. Not sure if there's anymore needed for this fix.
**Checklist:**
> fix: `Forge::dropColumn()` always returns `false` on SQLite3 driver

- system/CLI/CLI.php
- system/Database/BaseBuilder.php
- system/Database/Query.php
- system/Database/SQLSRV/Builder.php
- system/Email/Email.php
- system/Helpers/text_helper.php
- system/Helpers/url_helper.php
- system/Session/Handlers/MemcachedHandler.php
- system/Typography/Typography.php
- system/View/Parser.php
Continue of PR: 
- https://github.com/codeigniter4/CodeIgniter4/pull/9339
this ensure `preg_match_all()` which with falsy check ensure got exact equal result, wich compare to `>=1` or `<1` which can be false or 0.
**Checklist:**
> refactor: use more strict result check on preg_match_all() result

- system/Database/BaseBuilder.php
- system/Database/Postgre/Connection.php
- system/Database/SQLSRV/Connection.php
- tests/system/Database/Live/InsertTest.php
- tests/system/Database/Live/TransactionTest.php
- user_guide_src/source/changelogs/v4.5.8.rst
- user_guide_src/source/database/query_builder.rst
This PR fixes a bug in the `Postgre` and `SQLSRV` handlers when calling `Builder::affectedRows()` after a failed query.
This is because when `Builder::affectedRows()` is called after a failed query, the `$resultID` is set to `false`, and a boolean value is not acceptable for either `pg_affected_rows()` or `sqlsrv_rows_affected()`.
Fixes #9362
**Checklist:**
> fix: gather affected rows after query call failed

- tests/system/CommonHelperTest.php
- utils/phpstan-baseline/function.notFound.neon
- utils/phpstan-baseline/loader.neon
Only ignore this error.
**Checklist:**
> refactor: Fix phpstan function.notFound

- system/CLI/CLI.php
- utils/phpstan-baseline/if.condNotBoolean.neon
- utils/phpstan-baseline/loader.neon
This is a rare case, but there are no tests for wrong `$options` values (`"", null, []` ...). Leaving it?
**Checklist:**
> refactor: Fix phpstan if.condNotBoolean

- system/Test/Mock/MockCache.php
- utils/phpstan-baseline/loader.neon
- utils/phpstan-baseline/unset.offset.neon
Wrong PHPDoc type `$expirations`
**Checklist:**
> refactor: Fix phpstan when delete string key

- system/Images/Handlers/BaseHandler.php
- system/Images/Handlers/ImageMagickHandler.php
- system/Images/ImageHandlerInterface.php
- utils/phpstan-baseline/greaterOrEqual.invalid.neon
- utils/phpstan-baseline/loader.neon
- utils/phpstan-baseline/missingType.iterableValue.neon
Some comments have been deleted as duplicates from the parent class.
**Checklist:**
> refactor: Fix phpstan greaterOrEqual.invalid

- app/Config/Feature.php
- system/HTTP/Negotiate.php
- tests/system/HTTP/NegotiateTest.php
- user_guide_src/source/changelogs/v4.5.8.rst
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/incoming/content_negotiation.rst
- user_guide_src/source/incoming/content_negotiation/008.php
- user_guide_src/source/installation/upgrade_458.rst
- user_guide_src/source/installation/upgrade_460.rst
See #9256
I added a setting for the desired behavior.
**Checklist:**
> feat: Strict locale negotiation

- tests/system/CommonHelperTest.php
- utils/phpstan-baseline/function.inner.neon
- utils/phpstan-baseline/loader.neon
Just ignoring it.
**Checklist:**
> refactor: Fix phpstan function.inner

- system/Commands/Utilities/Namespaces.php
- system/Helpers/text_helper.php
- system/View/View.php
- tests/system/Commands/Utilities/NamespacesTest.php
- tests/system/Helpers/TextHelperTest.php
- tests/system/View/ViewTest.php
- user_guide_src/source/changelogs/v4.5.8.rst
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/helpers/text_helper.rst
* Unicode namespases `App\Контроллеры\Админ`  allowed in `Namespaces::truncate()`
* Now `$view->excerpt('<unicode string>')` and ``excerpt('<unicode string>')`` works correctly with characters, not bytes. 
Can someone clarify why `excerpt()` adds an extra space and removes a character from the string?  See tests - ` It sad  So some nice`, ` Это печ льно. И вот несколько`. Missing **dot** and "**a**".
https://github.com/codeigniter4/CodeIgniter4/blob/6ee2083aed1d70861a80a8586d21240a9170aef8/tests/system/Helpers/TextHelperTest.php#L395
https://github.com/codeigniter4/CodeIgniter4/blob/6ee2083aed1d70861a80a8586d21240a9170aef8/tests/system/Helpers/TextHelperTest.php#L399
**Checklist:**
> fix: Add support for multibyte strings

- system/Router/RouteCollection.php
- tests/system/Commands/Utilities/Routes/FilterFinderTest.php
- utils/phpstan-baseline/loader.neon
- utils/phpstan-baseline/return.type.neon
`static` or `self` will decide what is returned.
**Checklist:**
> refactor: Fix phpstan return.type

- system/Database/BaseBuilder.php
- utils/phpstan-baseline/isset.offset.neon
- utils/phpstan-baseline/loader.neon
It seems `$matches` always has `6` keys. In addition, other indexes are not checked - they are expected to exist.
```console
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ $matches                                                                                                                                                                                            │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
array (6) [
0 => string (34) " j.name  LIKE :j.name: …
```
> refactor: Fix phpstan isset offset

- system/Test/Mock/MockResult.php
- utils/phpstan-baseline/return.missing.neon
Don't you think `MockResult` is a dead class? It is not used anywhere.
**Checklist:**
> refactor: Fix phpstan return.missing

- system/Helpers/filesystem_helper.php
- utils/phpstan-baseline/booleanAnd.rightAlwaysTrue.neon
- utils/phpstan-baseline/loader.neon
`is_file($target)` not needed, as it will be overwritten anyway.
Question: Is it worth checking copy() and throwing an exception?
**Checklist:**
> refactor: Fix phpstan booleanAnd.rightAlwaysTrue

- .github/mergeable.yml
Here's the successful test run: https://github.com/paulbalandan/b40d520f57f086f2e58d1f21d093935d/issues/3#issuecomment-2582515768
**Checklist:**
> chore: fix mergeable integration file

- tests/system/API/ResponseTraitTest.php
- utils/phpstan-baseline/assign.propertyType.neon
- utils/phpstan-baseline/missingType.iterableValue.neon
- utils/phpstan-baseline/missingType.parameter.neon
- utils/phpstan-baseline/missingType.property.neon
Run latest rector/rector:dev-main and apply changes on tests.
**Checklist:**
> refactor: using property promotion on ResponseTraitTest

- .php-cs-fixer.dist.php
- user_guide_src/source/libraries/publisher/005.php
```console
❯ utils/vendor/bin/php-cs-fixer describe get_class_to_class_keyword
PHP CS Fixer 3.67.0 Persian Successor by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.3.15
Description of the `get_class_to_class_keyword` rule.
Replace `get_class` calls on object variables with class keyword syntax.
Fixer applying this rule is RISKY.
Risky if the `get_class` function is overridden.
* Example #1.
--- Original
+++ New
@@ -1,2 +1,2 @@
<?php
-get_class($a);
+$a::class;
* Example #2.
--- Original
+++ New
@@ -1,4 +1,4 @@
<?php
$date = new \DateTimeImmutable();
-$class = get_class($date);
+$class = $date::class; …
```
> style: enable `get_class_to_class_keyword` fixer

- user_guide_src/source/changelogs/v4.6.0.rst
This PR adds a missing changelog entry for `phpini:check` command.
Ref: #9032
**Checklist:**
> docs: changelog entry for phpini:check command

- app/Config/Constants.php
- tests/system/Events/EventsTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/extending/events.rst
- user_guide_src/source/installation/upgrade_460.rst
- utils/phpstan-baseline/method.notFound.neon
See #6000 (**v4.2.0**)
Constants are used a little in the system, so there are few updates. 
**Checklist:**
> refactor: Remove deprecated `EVENT_PRIORITY_*`

- system/View/View.php
- user_guide_src/source/changelogs/v4.6.0.rst
See https://github.com/codeigniter4/CodeIgniter4/pull/4622 **v4.1.2**
The property is no longer in use. Only in special cases when extending the `View`
**Checklist:**
> refactor: Remove deprecated `View::$currentSection`

- app/Config/Cache.php
- system/Cache/Handlers/FileHandler.php
- tests/system/Cache/CacheFactoryTest.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/installation/upgrade_460.rst
- utils/phpstan-baseline/function.alreadyNarrowedType.neon
See https://github.com/codeigniter4/CodeIgniter4/pull/4103 **v4.0.5**
`$storePath` has been removed and the tests have been updated.
**Checklist:**
> refactor: Remove deprecated `Cache::$storePath`

- app/Config/Format.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/installation/upgrade_460.rst
See https://github.com/codeigniter4/CodeIgniter4/pull/3563 **v4.0.5**
**Checklist:**
> refactor: Remove deprecated `Config\Format::getFormatter()`

- phpunit.xml.dist
- tests/system/DebugTraceableTraitTest.php
- I don't know why, but `includeUncoveredFiles` is missing from XSD for **11.5**. Although this parameter is available in the documentation.
- `CoversTrait` is deprecated. I didn't understand what it was for. Tell me if this is a test error. See https://github.com/sebastianbergmann/phpunit/issues/5958 
- 
**Checklist:**
> chore: Fix phpunit deprecations

- system/Security/Security.php
- tests/system/Security/SecurityTest.php
- user_guide_src/source/changelogs/v4.5.8.rst
Make sure the CSRF token must be a string, because hackers can fake the request and pass csrf_main as an array, the system will break 500.
**Checklist:**
> fix: ensure csrf token is string

- .github/prlint.json
`\d\.\d\.\d Merge code` is used to merge minor version branches.
**Checklist:**
> chore: allow "Merge code" as valid PR title for PRLint

- CHANGELOG.md
- phpdoc.dist.xml
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.6.0.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_460.rst
Updates changelog and version references for 4.x.x.
Previous version: #9415
**Checklist:**
> Prep for 4.6.0 release

- system/HTTP/CURLRequest.php
- tests/system/HTTP/CURLRequestTest.php
- user_guide_src/source/changelogs/v4.6.1.rst
Fixes an issue where multiple header sections are returned if there are redirects. The original code would only parse the first header section, and treated the rest as body. For example:
With output:
```http
HTTP/2 308
content-type: text/html; charset=utf-8
content-length: 211
location: http://example.com
date: Mon, 20 Jan 2025 11:46:34 GMT
server: nginx/1.21.6
vary: Origin
HTTP/2 200
content-type: text/html; charset=utf-8
content-length: 211
date: Mon, 20 Jan 2025 11:46:34 GMT
server: nginx/1.21.6
vary: Origin
Hello world
```
`$response->getBody()` returns:
```http
HTTP/2 200
content-type: text/html; charset=utf-8
content-length: 211
date: Mon, 20 Jan 2025 11:46:34 GMT
server: nginx/1.21.6
vary: Origin
Hello world
```
With these changes, the redirect header section is …
> fix(CURLRequest): multiple header sections after redirects

- utils/phpstan-baseline/argument.type.neon
- utils/phpstan-baseline/assign.propertyType.neon
- utils/phpstan-baseline/codeigniter.cacheHandlerInstance.neon
- utils/phpstan-baseline/codeigniter.getReassignArray.neon
- utils/phpstan-baseline/codeigniter.superglobalAccess.neon
- utils/phpstan-baseline/codeigniter.superglobalAccessAssign.neon
- utils/phpstan-baseline/codeigniter.unknownServiceMethod.neon
- utils/phpstan-baseline/empty.notAllowed.neon
- utils/phpstan-baseline/method.alreadyNarrowedType.neon
- utils/phpstan-baseline/method.childReturnType.neon
- utils/phpstan-baseline/method.notFound.neon
- utils/phpstan-baseline/missingType.iterableValue.neon
- utils/phpstan-baseline/missingType.property.neon
- utils/phpstan-baseline/nullCoalesce.property.neon
- utils/phpstan-baseline/offsetAccess.notFound.neon
- utils/phpstan-baseline/property.nonObject.neon
- utils/phpstan-baseline/property.notFound.neon
- utils/phpstan-baseline/property.protected.neon
- utils/phpstan-baseline/property.readOnlyByPhpDocAssignOutOfClass.neon
- utils/phpstan-baseline/property.readOnlyByPhpDocDefaultValue.neon
- utils/phpstan-baseline/staticMethod.notFound.neon
- utils/phpstan-baseline/ternary.shortNotAllowed.neon
- utils/phpstan-baseline/varTag.type.neon
- utils/phpstan-baseline/variable.undefined.neon
The update brings the correct count of baselined errors. To date, that's a whopping 3,800 errors.
```
composer phpstan:baseline
```
**Checklist:**
> chore: update phpstan baseline count of errors

- composer.json
- system/HTTP/Exceptions/RedirectException.php
- utils/phpstan-baseline/ternary.shortNotAllowed.neon
This was prompted by rector. But I don't believe `Location` should be checked against `0` so changed it against `''` only.  Other changes are cosmetic.
**Checklist:**
> refactor: fix rector change on RedirectException

- tests/system/Cache/ResponseCacheTest.php
- tests/system/Filters/CorsTest.php
- tests/system/HTTP/Files/FileCollectionTest.php
- tests/system/HTTP/ResponseTest.php
- tests/system/Images/GDHandlerTest.php
- tests/system/Images/ImageMagickHandlerTest.php
Run rector latest dev-main.
**Checklist:**
> refactor: use assertNotInstanceOf over assertNull on nullable object return and flip actual/expect on constant check

- user_guide_src/source/outgoing/localization.rst
> docs: Typo fix, classname misspelled

- user_guide_src/source/incoming/routing.rst
- user_guide_src/source/incoming/routing/074.php
- Added information about the method
https://forum.codeigniter.com/showthread.php?tid=88747
**Checklist:**
> docs: Add info about `Router::getMatchedRouteOptions()`

- system/Filters/Cors.php
- system/HTTP/Cors.php
- tests/system/Filters/CorsTest.php
- tests/system/HTTP/CorsTest.php
- user_guide_src/source/changelogs/v4.6.1.rst
- user_guide_src/source/libraries/cors/002.php
This PR fixes a bug where CORS was not set correctly due to the response object being returned in the `before` filter. ~~Now all CORS headers are set in the `before` filter, and the `after` filter is no longer used.~~
This change should not break anyone's code.
Fixes #9431
**Checklist:**
> fix: set headers for CORS

- system/Config/Filters.php
- utils/phpstan-baseline/missingType.iterableValue.neon
- utils/phpstan-baseline/property.phpDocType.neon
Missed PHPDoc in **system/Config/Filters.php**.
**Checklist:**
> refactor: Add phpDoc for `Filters`

- .github/workflows/deploy-apidocs.yml
This PR updates the GPG key for PHPDocumentor.
See: https://github.com/codeigniter4/CodeIgniter4/actions/runs/13340303631/job/37270601750
GPG key change confirmation: https://github.com/phpDocumentor/phpDocumentor/issues/3873#issuecomment-2660849527
**Checklist:**
> chore: update gpg key for phpdocumentor workflow

- system/ThirdParty/Escaper/Escaper.php
> chore: bump to laminas-escaper v2.16

- user_guide_src/source/models/model.rst
This PR improves the description for `beforeDelete` and `afterDelete` model events.
Original report on the forum: https://forum.codeigniter.com/showthread.php?tid=92343&pid=424350#pid424350
**Checklist:**
> docs: improved description of `beforeDelete` and `afterDelete` model events

- user_guide_src/source/changelogs/index.rst
- user_guide_src/source/changelogs/v4.7.0.rst
- user_guide_src/source/installation/upgrade_470.rst
- user_guide_src/source/installation/upgrading.rst
The changelog for 4.7.0 is missing.
```cli
php admin/create-new-changelog.php 4.6.x 4.7.0
```
**Checklist:**
> docs: add changelog and upgrade for v4.7.0

- user_guide_src/source/outgoing/view_parser.rst
Some template tags, such as {+ siteURL "login" +}, had extra quotation marks that caused parsing errors. We've resolved this by switching to code syntax for examples, ensuring correct interpretation and execution of the tags.
**Checklist:**
> docs: switch to code syntax for parsing examples

- admin/css/debug-toolbar/toolbar.scss
- system/Debug/Toolbar/Views/toolbar.css
https://github.com/user-attachments/assets/ccdf2db7-958c-4db4-b809-adefb9951653
https://github.com/user-attachments/assets/d454b56a-3510-45b1-9cae-7749e6650ea6
**Checklist:**
> fix: [DebugBar] make debug bar more user-friendly on mobile

- system/Common.php
default not sync with return
```php
env('myconfig.isLogApi', config(MyConfig::class)->isLogApi); // bool
env('myconfig.httpVersion', config(MyConfig::class)->httpVersion); // float
env('myconfig.timeout', config(MyConfig::class)->timeout); // int
```
**Checklist:**
> refactor: PHPDocs in `env()`

- tests/system/Filters/DebugToolbarTest.php
Fix phpstan error:
```console
------ --------------------------------------------------------------------------------------------- 
Line   tests/system/Filters/DebugToolbarTest.php                                                    
------ --------------------------------------------------------------------------------------------- 
:63    Call to method CodeIgniter\Filters\DebugToolbar::before() on a separate line has no effect.  
🪪  method.resultUnused                                                                      
------ ---------------------------------------------------------------------------------------------
```
**Checklist:**
> refactor: Update Toolbar tests

- system/Database/Postgre/Builder.php
- system/Database/SQLite3/Builder.php
- tests/_support/Database/Migrations/20160428212500_Create_test_tables.php
- tests/_support/Database/Seeds/CITestSeeder.php
- tests/system/Database/Live/MetadataTest.php
- tests/system/Database/Live/UpsertTest.php
- user_guide_src/source/changelogs/v4.6.1.rst
- user_guide_src/source/database/query_builder.rst
This PR fixes a bug in `Postgre` and `SQLite3` where composite indexes are not fully taken into account when using `upsert()`. 
Both handlers:
* requires specifying all columns in the composite unique constraint
* and cannot mix columns from multiple unique constraints
Fixes #9450
**Checklist:**
> fix: upsert with composite unique index

- system/Cache/Handlers/RedisHandler.php
- system/Commands/Generators/MigrationGenerator.php
- system/HTTP/CURLRequest.php
- system/I18n/TimeTrait.php
- system/Test/ReflectionHelper.php
- tests/system/Commands/Utilities/ConfigCheckTest.php
- utils/phpstan-baseline/varTag.type.neon
- `Redis::scan()` does not return `Redis`.
- `config()` already supports the hint for classes. Removed the creation of a one-time variable.
- `TimeTrait::$timezone` it can be a `string` during initialization.
- It seems that `Closure(mixed...)` cannot be specified, so I only changed the return type.  
**Checklist:**
> refactor: Fix phpstan `varTag.type` errors

- app/Views/errors/html/debug.css
Adjusts the panel’s position to ensure it fully touches the top, eliminating the unwanted spacing and improving the UI. The panel has a small gap from the top position, causing a visual misalignment.
https://github.com/user-attachments/assets/dcd15284-b70e-4c44-b58f-17188c6520e6
**Checklist:**
> fix: [Views] adjust panel top spacing

- tests/system/I18n/TimeLegacyTest.php
- tests/system/I18n/TimeTest.php
> fix: Time tests for arab locale

- system/Database/OCI8/Connection.php
- system/Database/SQLSRV/Connection.php
- tests/system/Database/Live/GetVersionTest.php
- user_guide_src/source/changelogs/v4.6.1.rst
- utils/phpstan-baseline/property.notFound.neon
This PR fixes a bug in OCI8 and SQLSRV `getVersion()` method, which will return an empty string when no connection is established.
Issue discovered in #9469
**Checklist:**
> fix: `getVersion()` for OCI8 and SQLSRV drivers

- user_guide_src/source/database/results.rst
- user_guide_src/source/dbmgmt/forge.rst
- user_guide_src/source/general/common_functions.rst
- user_guide_src/source/libraries/typography.rst
Update camelCase  style.
**Checklist:**
> docs: Update hint vars in userguide

- system/Autoloader/FileLocator.php
- system/Autoloader/FileLocatorInterface.php
- system/CLI/CLI.php
- system/CLI/Commands.php
- system/CLI/Console.php
- system/Common.php
- system/Config/BaseConfig.php
- system/Config/Factories.php
- system/Publisher/Publisher.php
- tests/system/CLI/CLITest.php
- tests/system/CLI/ConsoleTest.php
- tests/system/Commands/CommandTest.php
- utils/phpstan-baseline/codeigniter.superglobalAccessAssign.neon
- utils/phpstan-baseline/missingType.iterableValue.neon
Preparing for the big update. Updated types, several code reductions.
After approval, it is advisable to merge into **v4.7** to continue working.
**Checklist:**
> refactor: Typing commands

- tests/system/API/ResponseTraitTest.php
- tests/system/Autoloader/AutoloaderTest.php
- tests/system/CodeIgniterTest.php
- tests/system/Commands/Translation/LocalizationSyncTest.php
- tests/system/Commands/Utilities/ConfigCheckTest.php
- tests/system/Commands/Utilities/NamespacesTest.php
- tests/system/Config/BaseConfigTest.php
- tests/system/ControllerTest.php
- tests/system/Database/ConfigTest.php
- tests/system/Database/Live/ForgeTest.php
- tests/system/Database/Live/OCI8/ConnectionTest.php
- tests/system/Database/Migrations/MigrationRunnerTest.php
- tests/system/Debug/ExceptionHandlerTest.php
- tests/system/Debug/ExceptionsTest.php
- tests/system/Files/FileCollectionTest.php
- tests/system/HTTP/CURLRequestTest.php
- tests/system/Models/MiscellaneousModelTest.php
- tests/system/Models/ValidationModelRuleGroupTest.php
- tests/system/Models/ValidationModelTest.php
- tests/system/Publisher/PublisherSupportTest.php
- tests/system/RESTful/ResourceControllerTest.php
- tests/system/Security/SecurityTest.php
- tests/system/Session/Handlers/Database/AbstractHandlerTestCase.php
- tests/system/Test/FabricatorTest.php
- tests/system/Test/ReflectionHelperTest.php
- tests/system/Validation/ValidationTest.php
- user_guide_src/source/testing/overview/013.php
I am developing a new phpstan extension for `ReflectionHelper::getPrivateMethodInvoker()` to give a precise Closure return type instead of just `Closure(mixed...): mixed)` return. To achieve this, I created a `DynamicStaticMethodReturnTypeExtension` since the method is _static_.
Now, the extension is working well pre-testing. The only setback I faced is that here in the repo we use the dynamic call instead of static call. This makes the extension useless as PHPStan does not call it anymore since the call is, well, dynamic. To fix this, I might just need to replicate the extension in a `DynamicMethodReturnTypeExtension` to handle dynamic calls, but that is not very DRY. So, I just opted to fix the calls here to static, as they should have been.
P.S. The amount of characters …
> refactor: call `getPrivateMethodInvoker()` statically

- tests/system/ControllerTest.php
- tests/system/Database/ConfigTest.php
Fixes the following phpstan errors after having smarter return type for `getPrivateMethodInvoker()`.
```
------ ------------------------------------ 
Line   tests/system/ControllerTest.php     
------ ------------------------------------ 
:98    Result of closure (void) is used.   
🪪  callable.void                   
✏️  tests/system/ControllerTest.php  
------ ------------------------------------ 
------ ------------------------------------------------------- 
Line   tests/system/Database/ConfigTest.php                   
------ ------------------------------------------------------- 
:171   Unreachable statement - code above always terminates.  
🪪  deadCode.unreachable                               
✏️  tests/system/Database/ConfigTest.php               
:211 …
```
> refactor: fix tests after smarter `getPrivateMethodInvoker()` return

- system/Security/CheckPhpIni.php
> fix: Inconsistent directives value between Default and OPCache groups

- system/Database/OCI8/Builder.php
- utils/phpstan-baseline/missingType.return.neon
This PR refactors the `limit()` method in the OCI8 driver by removing legacy code that was only required for OCI8 versions below `12.1`, which are no longer supported by CodeIgniter.
Reference: https://github.com/codeigniter4/CodeIgniter4/blob/develop/user_guide_src/source/intro/requirements.rst?plain=1#L69
Closes: #9469
**Checklist:**
> refactor: OCI8 `limit()` method

- system/HTTP/UserAgent.php
- utils/phpstan-baseline/loader.neon
- utils/phpstan-baseline/method.alreadyNarrowedType.neon
- utils/phpstan-baseline/offsetAccess.notFound.neon
This PR updates the PHPStan baseline and one Rector error that occurred in the last build. IDK if there is a better way to handle PHPStan, but this seemed the simplest approach.
* PHPStan errors: https://github.com/codeigniter4/CodeIgniter4/actions/runs/14101988822/job/39499990729
* Rector error: https://github.com/codeigniter4/CodeIgniter4/actions/runs/14101988834/job/39499990763
**Checklist:**
> refactor: update PHPStan baseline and fix Rector

- user_guide_src/source/incoming/routing.rst
It fixes the case described me in the forum topic https://forum.codeigniter.com/showthread.php?tid=92672
If we have two routes and the name of the second route is the same as the path of the first route, they conflict, and the second route is not added to the list of all routes.
```php
$routes->match(['GET', 'POST'], 'edit', 'PostController::edit');
$routes->match(['GET', 'POST'], 'edit/(:num)', 'PostController::edit/$1', ['as' => 'edit']); 
```
So, with this route configuration, we get a 404 on **/edit/10**.
> docs: Add description of conflicts between named and unnamed routes

- system/Log/Logger.php
- tests/system/Log/LoggerTest.php
- user_guide_src/source/changelogs/v4.6.1.rst
- utils/phpstan-baseline/argument.type.neon
- utils/phpstan-baseline/loader.neon
This PR fixes a bug where the `{line}` variable in the Logger cannot be used without specifying the `{file}` variable in the logged message.
Fixes #9501
**Checklist:**
> fix: Logger - allow variable {line} to be used without variable {file} when logging message

- system/Debug/Toolbar.php
- system/Debug/Toolbar/Views/toolbar.js
- user_guide_src/source/changelogs/v4.6.1.rst
This PR fixes issues with the debug bar when `maxHistory` is set to `0`:
- A JavaScript error occurred because the expected button does not exist.
- Debug toolbar history files were not properly cleaned up.
Fixes #9504
**Checklist:**
> fix: Toolbar when `maxHistory` is set to `0`

- user_guide_src/source/libraries/sessions.rst
- user_guide_src/source/libraries/sessions/045.php
See https://github.com/codeigniter4/CodeIgniter4/issues/9505#issuecomment-2781505010
- Added a clarification.
**Checklist:**
> docs: Notes about switching types in session

- system/Cache/Handlers/FileHandler.php
- user_guide_src/source/changelogs/v4.6.1.rst
Deprecates the following protected methods of `FileHandler` as being redundant from related `filesystem_helper` functions:
- `FileHandler::writeFile()`
- `FileHandler::deleteFiles()`
- `FileHandler::getDirFileInfo()`
- `FileHandler::getFileInfo()`
**Checklist:**
> refactor: deprecate redundant `FileHandler` cache methods

- system/HTTP/SiteURI.php
- system/HTTP/URI.php
- utils/phpstan-baseline/empty.notAllowed.neon
- utils/phpstan-baseline/loader.neon
- utils/phpstan-baseline/missingType.iterableValue.neon
- utils/phpstan-baseline/notIdentical.alwaysTrue.neon
- utils/phpstan-baseline/nullCoalesce.property.neon
Fixes a few errors in `URI` class.
**Checklist:**
> refactor: fix phpstan errors in `URI` and `SiteURI`

- phpstan.neon.dist
- system/Test/Fabricator.php
- utils/phpstan-baseline/codeigniter.modelArgumentType.neon
- utils/phpstan-baseline/loader.neon
1. Save the model call from instantiating non class-strings.
2. Added `Tests\Support\Models` namespace as known model namespaces.
~3. Adding Shield's namespace is not enough since PHPStan must know the class do exist, so we required shield as a dev dependency.~
**Checklist:**
> refactor: fix `codeigniter.modelArgumentType` errors

- system/Session/Session.php
- tests/system/Session/SessionTest.php
- user_guide_src/source/changelogs/v4.6.1.rst
> fix: `Session::markAsTempdata()` adding wrong TTL

- admin/framework/composer.json
- composer.json
This PR updates `predis/predis` to v3.
I removed v1, since it's not fully compatible with PHP 8.1 - it may return some deprecation warnings.
v2 and v3 support the same PHP versions without breaking changes, so since this is a dev requirement, it seems fine.
Closes #9548
**Checklist:**
> chore: update predis/predis to version 3

- system/ThirdParty/Escaper/Escaper.php
- system/ThirdParty/Escaper/EscaperInterface.php
Bump to latest version
**Checklist:**
> chore: bump to laminas-escaper v2.17

- system/HTTP/CURLRequest.php
- tests/system/HTTP/CURLRequestTest.php
- user_guide_src/source/changelogs/v4.7.0.rst
- user_guide_src/source/libraries/curlrequest.rst
- user_guide_src/source/libraries/curlrequest/038.php
Added option to disable fresh connection.
**Checklist:**
> feat: added `fresh_connect` options to `CURLRequest`

- system/Helpers/security_helper.php
- system/Security/Security.php
- system/Security/SecurityInterface.php
- user_guide_src/source/changelogs/v4.6.2.rst
- user_guide_src/source/helpers/security_helper.rst
- user_guide_src/source/libraries/security.rst
This PR fixes a bug where the `sanitize_filename()` helper function could not be used in CLI requests.
The `sanitize_filename()` function in the Security helper now contains the logic that was previously in the `Security::sanitizeFilename()` method. The method has been updated to delegate to the helper function, reversing the previous dependency. This change allows the function to be used in CLI requests without relying on the service.
Fixes: #9555
**Checklist:**
> fix: remove service dependency from sanitize_filename() helper function

- .php-cs-fixer.tests.php
- tests/_support/Autoloader/FatalLocator.php
- tests/_support/Config/Services.php
- tests/_support/Entity/Cast/CastPassParameters.php
- tests/system/Files/FileTest.php
- tests/system/Models/TimestampModelTest.php
- tests/system/Test/BootstrapFCPATHTest.php
Enforce the `phpdoc_to_return_type` fixer to the tests. I have to manually fix some transformations particularly on unions with `false` changing to `bool`.
**Checklist:**
> test: ensure all test methods have native return types

- system/Boot.php
- system/util_bootstrap.php
- utils/check_permission_x.php
Replaces and closes #9558 
Ref: https://github.com/codeigniter4/CodeIgniter4/pull/9558#issuecomment-2883805377
Depends on: #9561 
This was trickier than I initially thought, due to the following:
- We cannot use `bootWeb()` as it will require a CLI route registered to `/` (currently throws an Error 404)
- We cannot use `bootSpark()` as it will also print `spark`'s list of commands
- We cannot use `bootTest()` due to the reason outlined in the previous PRs
**Checklist:**
> refactor: add `system/util_bootstrap.php` to curb overreliance to `system/Test/bootstrap.php`

- user_guide_src/source/libraries/cookies/013.php
`CookieStore::get()` requires a `$name` parameter and does not give an array of Cookie objects
**Checklist:**
> docs: `CookieStore::get()` does not give an array of Cookie objects

- tests/system/Publisher/PublisherInputTest.php
Fixes #7470 
It seems the tests are being rate limited by GitHub. So, we instead use a mock curl request to prevent that. The tests do not care anyway of the contents of the queried files so it should be okay.
**Checklist:**
> test: fix `PublisherInputTest::testAddUri(s)` failing due to rate limiting

- phpstan-bootstrap.php
- psalm_autoload.php
- rector.php
- system/util_bootstrap.php
- user_guide_src/source/installation/running.rst
- utils/check_tabs_in_rst.php
Follow up to #9562 
**Checklist:**
> refactor: update places to use `system/util_bootstrap.php`

- system/Cookie/Cookie.php
- system/Cookie/CookieInterface.php
- tests/system/Cookie/CookieStoreTest.php
- utils/phpstan-baseline/argument.type.neon
- utils/phpstan-baseline/loader.neon
Uses array shape for the array phpdocs.
**Checklist:**
> refactor: more accurate array PHPDocs of Cookie

- system/Email/Email.php
> refactor: cleanup code in `Email`

- system/Cookie/CookieInterface.php
- tests/system/Cookie/CookieTest.php
- user_guide_src/source/changelogs/v4.7.0.rst
- user_guide_src/source/libraries/cookies/004.php
When I first made this Cookie component, the [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Set-Cookie) states that the date format is `D, d-M-Y H:i:s T` (RFC 850). Now, it seems this format is obsolete and recommends using RFC 5322 format (`D, d M Y H:i:s \G\M\T` - without dashes`). This PR updates the date format to that.
This change will not be breaking as per RFC 7231 section 7.1.1.1. Although RFC 850 is obsolete, it SHOULD still be accepted. Since we're moving from obsolete to recommended, I think we should not have any problems.
**Checklist:**
> feat: update `CookieInterface::EXPIRES_FORMAT` to use date format per RFC 7231

- system/Cookie/Cookie.php
- system/Cookie/CookieInterface.php
- user_guide_src/source/changelogs/v4.7.0.rst
- user_guide_src/source/libraries/cookies/006.php
If you run `vendor/bin/phpunit --filter CookieTest` you get:
```console
❯ vendor/bin/phpunit --filter CookieTest
PHPUnit 11.5.20 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.3.21 with Xdebug 3.4.3
Configuration: /Users/paul/Workspace/CodeIgniter4/phpunit.xml.dist
..F.............................................                                                                                        48 / 48 (100%)
Time: 00:02.209, Memory: 80.00 MB
1) CodeIgniter\Cookie\CookieTest::testCookieInitializationWithDefaults
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'lax'
+'Lax'
/Users/paul/Workspace/CodeIgniter4/tests/system/Cookie/CookieTest.php:58
FAILURES!
Tests: 48, Assertions: 133, Failures: 1. …
```
> fix: ucfirst all cookie samesite values

- system/Traits/ConditionalTrait.php
- tests/system/Database/Builder/WhenTest.php
- user_guide_src/source/changelogs/v4.6.2.rst
- user_guide_src/source/database/query_builder.rst
This PR fixes a bug where the `when()` and `whenNot()` methods did not treat certain falsy values like `0`, `'0'`, `null`, and empty arrays consistently with native PHP conditionals. 
The condition checks are now explicitly cast to boolean using `(bool)`, ensuring consistent and expected behavior across all falsy and truthy values.
Fixes #9575
**Checklist:**
> fix: use native PHP truthiness for condition evaluation in when()/whenNot()

- system/View/Parser.php
- system/View/View.php
- utils/phpstan-baseline/booleanAnd.rightNotBoolean.neon
- utils/phpstan-baseline/if.condNotBoolean.neon
- utils/phpstan-baseline/loader.neon
Fix non-booleans in if conditions.
**Checklist:**
> refactor: fix non-booleans in if conditions

- system/Format/Exceptions/FormatException.php
- system/Format/Format.php
- system/Format/FormatterInterface.php
- system/Format/JSONFormatter.php
- system/Format/XMLFormatter.php
- tests/system/Format/JSONFormatterTest.php
- tests/system/Format/XMLFormatterTest.php
- utils/phpstan-baseline/loader.neon
- utils/phpstan-baseline/missingType.iterableValue.neon
Just fixing phpstan errors and micro-optimising code in tests
**Checklist:**
> refactor: fix and micro-optimize code in `Format`

- user_guide_src/source/incoming/routing.rst
This PR updates the description for the `(:num)` placeholder in routes.
We received a question in Slack about why negative numbers don’t work with this placeholder. This update aims to clarify its behavior and address that confusion.
**Checklist:**
> docs: update description for the `(:num)` placeholder in routes

- system/Cache/Handlers/FileHandler.php
- tests/system/Cache/Handlers/FileHandlerTest.php
- user_guide_src/source/changelogs/v4.6.2.rst
This PR fixes the `FileHandler::getItem()` method to gracefully manage corrupted or malformed cache files that cannot be read or unserialized.
* `unserialize()` is now wrapped in a try/catch block, since it may throw a `Throwable` that the `@` operator cannot suppress
* `file_get_contents()` and `unlink()` are prefixed with @ to suppress warnings, as these functions only emit warnings and do not throw exceptions
Fixes #9573
**Checklist:**
> fix: add error handling for corrupted cache files in `FileHandler`

- system/Autoloader/Autoloader.php
- system/Autoloader/FileLocator.php
- system/Autoloader/FileLocatorCached.php
- system/Autoloader/FileLocatorInterface.php
- tests/system/Autoloader/AutoloaderTest.php
- utils/phpstan-baseline/loader.neon
- utils/phpstan-baseline/method.alreadyNarrowedType.neon
File path cannot be empty.
**Checklist:**
> refactor: precise PHPDocs for Autoloader

- system/Validation/Validation.php
- tests/system/Validation/FormatRulesTest.php
- user_guide_src/source/changelogs/v4.7.0.rst
- user_guide_src/source/libraries/validation.rst
This PR updates the validation behavior for the `regex_match` rule to require double curly braces `{{...}}` for placeholders instead of single ones `{...}`.
Using single braces for placeholders conflicts with valid regex syntax, such as quantifiers (`{1,3}`), which can lead to invalid regex patterns and hard-to-debug validation issues.
What changed:
- Placeholder parsing within `regex_match` now requires `{{value}}`
- Single-brace placeholders like `{value}` will no longer be parsed within `regex_match`
Fixes #9596
**Checklist:**
> feat: require double curly braces for placeholders in `regex_match` rule

- system/HTTP/URI.php
- tests/system/HTTP/URITest.php
- user_guide_src/source/changelogs/v4.6.2.rst
This PR fixes a bug in `URI` authority generation where schemes without defined default ports (like `rtsp://`) would cause issues due to missing array key handling.
Fixes: #9604
**Checklist:**
> fix: URI authority generation for schemes without default ports

- system/Validation/Validation.php
This PR applies Rector rule `TernaryImplodeToImplodeRector`.
Needed by: #9612
Details: https://github.com/codeigniter4/CodeIgniter4/actions/runs/15880423046/job/44779000194
**Checklist:**
> fix: apply rector rule TernaryImplodeToImplodeRector

- system/HTTP/SiteURIFactory.php
- tests/system/HTTP/SiteURIFactoryDetectRoutePathTest.php
- user_guide_src/source/changelogs/v4.6.2.rst
This PR fixes a bug where route path detection was failing when serving the app from a subfolder using Apache `mod_rewrite` (to "hide" `public` directory) while preserving `index.php` in URL.
 So something like: `https://localhost/ci/index.php/controller/method` - when our real directory structure was like: `ci/public/index.php`.  This caused the route path to return: `index.php/controller/method` instead of `controller/method`.
 
 Closes #9607
Fixes #9602 
 
**Checklist:**
> fix: correct path parsing in `SiteURIFactory::parseRequestURI()`

- system/HTTP/SiteURIFactory.php
- tests/system/HTTP/SiteURIFactoryDetectRoutePathTest.php
- user_guide_src/source/changelogs/v4.6.2.rst
This PR fixes a bug where folder names containing multibyte (non-ASCII) characters were not correctly resolved by `SiteURIFactory::parseRequestURI()` when the application was served from a subfolder.
The problem was spotted here: https://github.com/codeigniter4/CodeIgniter4/pull/9613#discussion_r2168053386
Needs #9613
**Checklist:**
> fix: support for multibyte folder names when the app is served from a subfolder

- .github/workflows/test-coding-standards.yml
- .php-cs-fixer.dist.php
- system/BaseModel.php
- system/Model.php
- system/Test/Interfaces/FabricatorModel.php
- utils/composer.json
- utils/phpstan-baseline/loader.neon
- utils/phpstan-baseline/missingType.iterableValue.neon
- The `PHP_CS_FIXER_IGNORE_ENV` is deprecated and suggests to use `Config::setUnsupportedPhpVersionAllowed(true)` in config which is already addressed by `coding-standard` latest version
- Third commit manually fixes phpdoc ordering issues: `@phpstan-param` is moved after the `@param` so I just manually merged them
- Removed deprecated fixer from cs-config
**Checklist:**
> style: fix code styles from php-cs-fixer v3.76

- tests/system/CommonSingleServiceTest.php
- tests/system/Config/MimesTest.php
- tests/system/Config/ServicesTest.php
- tests/system/DataConverter/DataConverterTest.php
- tests/system/Database/BaseQueryTest.php
- tests/system/Database/Builder/WhenTest.php
- tests/system/Database/Builder/WhereTest.php
- tests/system/Database/Live/LikeTest.php
- tests/system/Email/EmailTest.php
- tests/system/Files/FileTest.php
- tests/system/Filters/FiltersTest.php
- tests/system/HTTP/HeaderTest.php
- tests/system/HTTP/IncomingRequestTest.php
- tests/system/HTTP/MessageTest.php
- tests/system/HTTP/SiteURITest.php
- tests/system/HTTP/URITest.php
- tests/system/Helpers/ArrayHelperTest.php
- tests/system/Helpers/InflectorHelperTest.php
- tests/system/Helpers/URLHelper/CurrentUrlTest.php
- tests/system/Helpers/URLHelper/MiscUrlTest.php
- tests/system/Language/LanguageTest.php
- tests/system/Models/DeleteModelTest.php
- tests/system/Router/RouteCollectionReverseRouteTest.php
- tests/system/Router/RouteCollectionTest.php
- tests/system/Test/DOMParserTest.php
- tests/system/Test/FeatureTestTraitTest.php
- tests/system/Validation/FormatRulesTest.php
- tests/system/Validation/RulesTest.php
- tests/system/Validation/ValidationTest.php
- tests/system/View/ParserTest.php
See: https://github.com/codeigniter4/CodeIgniter4/actions/runs/16148108303/job/45572194348?pr=9628
**Checklist:**
> style: fix code styles from php-cs-fixer v3.82.1

- system/HTTP/CURLRequest.php
- tests/system/HTTP/CURLRequestTest.php
- user_guide_src/source/changelogs/v4.6.2.rst
This PR fixes a bug in `CURLRequest` where intermediate HTTP responses were not properly removed from the response chain in certain scenarios, causing incorrect status codes and headers to be returned instead of the final response.
The problem was that the original logic processed different types of intermediate responses separately, which could miss responses that appeared in mixed order.
* Refactored `send()` method to use unified intermediate response removal
* Removed `handleRedirectHeaders()` private method  
* Added `removeIntermediateResponses()` and `shouldRemoveCurrentResponse()` private methods, which now handle the entire process of intermediate headers removal
The issue was reported on the forum: https://forum.codeigniter.com/showthread.php?tid=93094&pid=426075# …
> fix: improve CURLRequest intermediate HTTP response handling

- system/Commands/Generators/TestGenerator.php
- user_guide_src/source/changelogs/v4.6.2.rst
Fixes #9634 . Pending fix confirmation from @b-and-p for Windows.
As this is Windows-related, I cannot write a unit test. But you can test this fix in macOS by reversing the directory separator, the phenomenon experienced in Windows.
```diff
diff --git a/system/Commands/Generators/TestGenerator.php b/system/Commands/Generators/TestGenerator.php
index d37864d76e..55791eaee2 100644
--- a/system/Commands/Generators/TestGenerator.php
+++ b/system/Commands/Generators/TestGenerator.php
@@ -179,7 +179,7 @@ class TestGenerator extends BaseCommand
$testPaths = service('autoloader')->getNamespace($testNamespace);
foreach ($testPaths as $candidate) {
-            if (str_contains($candidate, DIRECTORY_SEPARATOR . 'tests' . DIRECTORY_SEPARATOR)) {
+            if …
```
> fix: ensure `make:test` works on Windows

- system/HTTP/DownloadResponse.php
- tests/system/HTTP/DownloadResponseTest.php
- user_guide_src/source/changelogs/v4.6.2.rst
This PR fixes a bug in `DownloadResponse::inline()` method where filename parameters were missing for content disposition. This caused browsers to fall back to using the last URL segment as the filename instead of the intended filename.
The browser will display the filename that was set for image and PDF files.
I added `addslashes()` because if the filename contains a quote character (`"`), it would break the header syntax by prematurely terminating the quoted string.
The problem was recognized here: https://forum.codeigniter.com/showthread.php?tid=93147
**Checklist:**
> fix: add filename parameters to inline Content-Disposition headers

- CHANGELOG.md
- phpdoc.dist.xml
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.6.2.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_462.rst
Updates changelog and version references for 4.x.x.
Previous version: #9545 
**Checklist:**
> Prep for 4.6.2 release

- app/Config/Paths.php
- system/Boot.php
- system/Commands/Encryption/GenerateKey.php
- system/Commands/Utilities/Environment.php
- user_guide_src/source/changelogs/v4.7.0.rst
- user_guide_src/source/general/managing_apps.rst
This PR restores the ability to set a custom .env file path, which was no longer possible after #8604 due to hardcoded handling in Boot.php.
**Checklist:**
> feat: customizable `.env` directory path

- preload.php
Followup preload #9562
**Checklist:**
> refactor: update preload script to exclude `util_bootstrap`

- system/Debug/Toolbar/Collectors/Routes.php
- system/Email/Email.php
- system/Router/RouteCollection.php
- system/Test/Mock/MockConnection.php
- user_guide_src/source/changelogs/v4.6.3.rst
This PR fixes a bug where the destructor was checking `$this->SMTPConnect !== null` to validate SMTP connections.
However, `fclose()` creates closed resources that are not `null`, which led to unnecessary cleanup attempts on already-closed connections.
When the `SMTPKeepAlive` option is `false` (the default), the `quit` command is called before the destructor is reached.
Fixes #9647
**Checklist:**
> fix: SMTP connection resource validation in `Email` class destructor

- app/Config/Filters.php
- system/Config/Filters.php
This PR updates PHPDoc for `Config\Filters::$globals`
Fixes #9651
**Checklist:**
> refactor: phpdoc for `Config\Filters::$globals`

- CHANGELOG.md
- phpdoc.dist.xml
- system/CodeIgniter.php
- user_guide_src/source/changelogs/v4.6.3.rst
- user_guide_src/source/conf.py
- user_guide_src/source/installation/upgrade_463.rst
Updates changelog and version references for 4.6.3
Previous version: #9641
**Checklist:**
> Prep for 4.6.3 release

- system/API/ResponseTrait.php
- system/Debug/BaseExceptionHandler.php
- system/Debug/ExceptionHandler.php
- system/Debug/ExceptionHandlerInterface.php
Given that we currently have an interface disconnect with the concrete implementations, I think it makes sense to change the phpdocs for now to those complete concrete classes.
Closes #9650
**Checklist:**
> refactor: change `$request` to `CLIRequest|IncomingRequest` in `ResponseTrait`

- system/Common.php
- system/Helpers/cookie_helper.php
- tests/system/CommonFunctionsTest.php
- utils/phpstan-baseline/argument.type.neon
- utils/phpstan-baseline/loader.neon
- utils/phpstan-baseline/missingType.iterableValue.neon
The main task was to update `esc()`, but a little more was done :smile: 
We can use templates (DB, cookies) for dependent functions, but then I might make a mistake with the imports.
**Checklist:**
> refactor: Update phpDoc typing

- tests/system/Config/DotEnvTest.php
- utils/phpstan-baseline/argument.type.neon
- utils/phpstan-baseline/loader.neon
The test is useless as it does not test the class itself but PHP's strict typing.
**Checklist:**
> test: remove useless `DotEnvTest` test

- system/Database/Config.php
- tests/system/Database/Live/ConnectTest.php
- user_guide_src/source/changelogs/v4.6.4.rst
This PR fixes a bug where non-shared database instances were incorrectly stored in the shared instances cache, causing modifications to non-shared instances to affect subsequent shared connections.
Fixes #9678
**Checklist:**
> fix: prevent non-shared DB instances from polluting shared cache

- app/Config/Migrations.php
- system/Database/MigrationRunner.php
- system/Language/en/Migrations.php
- tests/system/Database/Migrations/MigrationRunnerTest.php
- user_guide_src/source/changelogs/v4.7.0.rst
- user_guide_src/source/dbmgmt/migration.rst
- user_guide_src/source/installation/upgrade_470.rst
- utils/phpstan-baseline/empty.notAllowed.neon
- utils/phpstan-baseline/loader.neon
This PR introduces a database-agnostic locking system for migrations. It guarantees consistent behavior across all supported databases. Lock cleanup is safe and automatically handled through `finally` blocks, and there are no modifications to the public API, ensuring full compatibility with existing workflows.
Closes #9646
**Checklist:**
> feat: migrations lock

- system/BaseModel.php
- tests/system/Models/ReplaceModelTest.php
- user_guide_src/source/changelogs/v4.6.4.rst
This PR fixes a bug where the `created_at` field wasn't set correctly when using the `Model::replace()` method.
Fixes #9692
**Checklist:**
> fix: setting `created_at` field in `Model::replace()` method

- .github/workflows/reusable-phpunit-test.yml
- .github/workflows/test-coding-standards.yml
- .github/workflows/test-phpunit.yml
- .github/workflows/test-psalm.yml
- .github/workflows/test-rector.yml
- composer.json
See #9664
Closes #9686 as no longer needed
**Checklist:**
> chore: add `PHP 8.5` to Github Action

- system/BaseModel.php
- tests/system/Models/InsertModelTest.php
- tests/system/Models/UpdateModelTest.php
- user_guide_src/source/changelogs/v4.6.4.rst
- utils/phpstan-baseline/missingType.property.neon
This PR fixes the bug where casting was not performed on the rows during `insertBatch()` and `updateBatch()` methods inside `BaseModel` file.
Fixes #9695.
**Checklist:**
> fix: Casting in insertBatch and updateBatch methods.

- system/Database/BaseBuilder.php
- tests/system/Database/Builder/SelectTest.php
- user_guide_src/source/changelogs/v4.6.4.rst
This PR fixes a bug in `BaseBuilder::compileOrderBy()` where the method could overwrite `QBOrderBy` with a string instead of keeping it as an array. This caused type errors and made it impossible to append additional `ORDER BY` clauses.
Fixes #9696
**Checklist:**
> fix: `compileOrderBy()` method

- .github/workflows/test-deptrac.yml
- deptrac.yaml
See https://github.com/codeigniter4/CodeIgniter4/actions/runs/17066835318/job/48385901679
**Checklist:**
> refactor: change `qossmic/deptrac-shim` has abandoned

- system/BaseModel.php
- tests/system/Models/UpdateModelTest.php
- user_guide_src/source/changelogs/v4.7.0.rst
- utils/phpstan-baseline/missingType.property.neon
This PR updates `BaseModel` so that `insertBatch()` and `updateBatch()` now respect model-level properties, like `updateOnlyChanged` and `allowEmptyInserts`. Previously, these methods bypassed these settings, which caused inconsistent behavior compared to `insert()` and `update()`. With this change, all insert and update operations are handled consistently.
This is a follow-up for #9698
**Checklist:**
> feat: make `insertBatch()` and `updateBatch()` respect model rules

- system/Common.php
- system/Test/CIUnitTestCase.php
- system/Test/DatabaseTestTrait.php
- system/Test/FeatureTestTrait.php
- tests/system/Database/DatabaseTestCase/DatabaseTestCaseMigrationOnce1Test.php
- tests/system/Database/DatabaseTestCase/DatabaseTestCaseMigrationOnce2Test.php
- tests/system/Database/DatabaseTestCaseTest.php
- tests/system/Database/Live/MetadataTest.php
- utils/phpstan-baseline/loader.neon
- utils/phpstan-baseline/missingType.iterableValue.neon
- utils/phpstan-baseline/nullCoalesce.property.neon
- utils/phpstan-baseline/property.defaultValue.neon
- utils/phpstan-baseline/property.phpDocType.neon
Improved typing. 
What is done:
_OFFTOP:_ I'll ask again: Do we really need repeated code descriptions? (You answered **Yes**.)
Because of this, it needs to be fixed in several places. See, example  `$namespace` property. Modern IDEs fully support type highlighting and you can switch to declarations. If not, then is it worth adding missing comments everywhere? I would leave it as it is now, but this contradicts the desire to duplicate the code: Everywhere without repeating, or always duplicate typing.
**Checklist:**
> refactor: Improve types for phpstan

- app/Config/Database.php
- tests/_support/Config/Registrar.php
- user_guide_src/source/changelogs/v4.6.4.rst
- user_guide_src/source/installation/upgrade_464.rst
On some systems, there may be a huge drop when reading/writing even to SSD. I think data loss is not critical for tests, you can disable it.
The framework already knows how to work with the option, it's worth leaving at least **NORMAL (1)** in production.
See see https://www.sqlite.org/pragma.html#pragma_synchronous
**UPD:** 
```console
// Before PHP 8.4
Time: 00:34.360, Memory: 80.50 MB
// Before PHP 8.3
Time: 00:25.448, Memory: 78.50 MB
// After PHP 8.4
Time: 00:07.573, Memory: 80.50 MB
// After PHP 8.3
Time: 00:07.320, Memory: 78.50 MB
```
**Checklist:**
> refactor: Add `synchronous` option for SQLite tests

- system/Database/SQLite3/Connection.php
- user_guide_src/source/changelogs/v4.6.4.rst
This PR fixes incorrect password handling in the `SQLite3` driver when the password was set to an empty string.
See: https://github.com/codeigniter4/CodeIgniter4/pull/9728#discussion_r2384107915
**Checklist:**
> fix: SQLite3 password handling for empty string

- system/Validation/FormatRules.php
- tests/system/Validation/FormatRulesTest.php
- user_guide_src/source/changelogs/v4.6.4.rst
This PR fixes a bug in the `valid_base64` validation rule that caused a TypeError when checking invalid base64 strings.
Fixes #9732
**Checklist:**
> fix: TypeError in `valid_base64` rule when checking invalid base64 strings

- system/Debug/Toolbar/Views/toolbar.js
This PR fixes an `Uncaught TypeError: Cannot read properties of null` in `toolbar.js` within the `toggleViewsHints` method.
Fixes #9726
**Checklist:**
> fix: cannot read properties of null in `toggleViewsHints` (`toolbar.js`)

- rector.php
- system/Commands/Database/CreateDatabase.php
- system/Database/BaseBuilder.php
- system/Database/BaseUtils.php
- system/Database/Database.php
- system/Database/MigrationRunner.php
- system/Database/SQLSRV/Builder.php
- system/Debug/Timer.php
- system/Email/Email.php
- system/HTTP/Response.php
- system/HTTP/URI.php
- system/Helpers/form_helper.php
- system/Images/Handlers/ImageMagickHandler.php
- system/Model.php
- system/Test/Fabricator.php
- system/Validation/Validation.php
Applied `SwitchNegatedTernaryRector` to Switch negated ternary condition
**Checklist:**
> refactor: apply code quality level 51 for Rector

- rector.php
- system/Images/Handlers/ImageMagickHandler.php
Apply `SingularSwitchToIfRector` to change `switch` with only 1 check to `if`
**Checklist:**
> refactor: apply code quality level 52 for Rector
